var annotated_dup =
[
    [ "activities", "namespaceactivities.html", "namespaceactivities" ],
    [ "appXml", "namespaceappXml.html", "namespaceappXml" ],
    [ "appXml2", "namespaceappXml2.html", "namespaceappXml2" ],
    [ "basicRegistration", "namespacebasicRegistration.html", "namespacebasicRegistration" ],
    [ "boost", null, [
      [ "python", null, [
        [ "objects", null, [
          [ "pointer_holder", "structboost_1_1python_1_1objects_1_1pointer__holder.html", null ]
        ] ]
      ] ]
    ] ],
    [ "camp", null, [
      [ "ExtendedClassVisitor", "classcamp_1_1ExtendedClassVisitor.html", "classcamp_1_1ExtendedClassVisitor" ],
      [ "isMapping", "structcamp_1_1isMapping.html", "structcamp_1_1isMapping" ],
      [ "MapProperty", "classcamp_1_1MapProperty.html", "classcamp_1_1MapProperty" ]
    ] ],
    [ "camp_ext", null, [
      [ "ArrayMapper< std::set< T > >", "structcamp__ext_1_1ArrayMapper_3_01std_1_1set_3_01T_01_4_01_4.html", "structcamp__ext_1_1ArrayMapper_3_01std_1_1set_3_01T_01_4_01_4" ],
      [ "MapMapper", "structcamp__ext_1_1MapMapper.html", null ],
      [ "MapMapper< MAP, typename boost::enable_if_c< camp::isMapping< MAP >::value >::type >", "structcamp__ext_1_1MapMapper_3_01MAP_00_01typename_01boost_1_1enable__if__c_3_01camp_1_1isMappin5db9bd91424627f4a8cef0927b896ae4.html", "structcamp__ext_1_1MapMapper_3_01MAP_00_01typename_01boost_1_1enable__if__c_3_01camp_1_1isMappin5db9bd91424627f4a8cef0927b896ae4" ],
      [ "ValueMapper< ::boost::filesystem::path >", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1filesystem_1_1path_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1filesystem_1_1path_01_4" ],
      [ "ValueMapper< ::boost::logic::tribool >", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1logic_1_1tribool_01_4.html", null ],
      [ "ValueMapper< ::boost::posix_time::ptime >", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1posix__time_1_1ptime_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1posix__time_1_1ptime_01_4" ],
      [ "ValueMapper< ::boost::uint64_t >", "structcamp__ext_1_1ValueMapper_3_01_1_1boost_1_1uint64__t_01_4.html", null ],
      [ "ValueMapper< ::fwAtoms::Blob::sptr >", "structcamp__ext_1_1ValueMapper_3_01_1_1fwAtoms_1_1Blob_1_1sptr_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1fwAtoms_1_1Blob_1_1sptr_01_4" ],
      [ "ValueMapper< ::fwData::TransferFunction::TFColor >", "structcamp__ext_1_1ValueMapper_3_01_1_1fwData_1_1TransferFunction_1_1TFColor_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1fwData_1_1TransferFunction_1_1TFColor_01_4" ],
      [ "ValueMapper< ::fwMedData::NavigationSeries::CoordinateType >", "structcamp__ext_1_1ValueMapper_3_01_1_1fwMedData_1_1NavigationSeries_1_1CoordinateType_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1fwMedData_1_1NavigationSeries_1_1CoordinateType_01_4" ],
      [ "ValueMapper< ::fwTools::Type >", "structcamp__ext_1_1ValueMapper_3_01_1_1fwTools_1_1Type_01_4.html", "structcamp__ext_1_1ValueMapper_3_01_1_1fwTools_1_1Type_01_4" ],
      [ "ValueMapper< std::shared_ptr< T > >", "structcamp__ext_1_1ValueMapper_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structcamp__ext_1_1ValueMapper_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
      [ "ValueMapper< T, typename boost::enable_if_c< camp::isMapping< T >::value >::type >", "structcamp__ext_1_1ValueMapper_3_01T_00_01typename_01boost_1_1enable__if__c_3_01camp_1_1isMappinb191d18af6dd7fcd02f7ab91b71e7498.html", null ],
      [ "ValueMapper< unsigned char >", "structcamp__ext_1_1ValueMapper_3_01unsigned_01char_01_4.html", null ],
      [ "wrapperTribbol", "structcamp__ext_1_1wrapperTribbol.html", null ],
      [ "wrapperTribbol< std::string >", "structcamp__ext_1_1wrapperTribbol_3_01std_1_1string_01_4.html", null ]
    ] ],
    [ "common", null, [
      [ "FileAtIndex", "classcommon_1_1FileAtIndex.html", "classcommon_1_1FileAtIndex" ],
      [ "FormatReturn", "classcommon_1_1FormatReturn.html", "classcommon_1_1FormatReturn" ]
    ] ],
    [ "ctrlCamp", "namespacectrlCamp.html", "namespacectrlCamp" ],
    [ "ctrlMemory", "namespacectrlMemory.html", "namespacectrlMemory" ],
    [ "ctrlSelection", "namespacectrlSelection.html", "namespacectrlSelection" ],
    [ "dataReg", "namespacedataReg.html", "namespacedataReg" ],
    [ "filterVRRender", "namespacefilterVRRender.html", "namespacefilterVRRender" ],
    [ "fwActivities", "namespacefwActivities.html", "namespacefwActivities" ],
    [ "fwAtomConversion", "namespacefwAtomConversion.html", "namespacefwAtomConversion" ],
    [ "fwAtoms", "namespacefwAtoms.html", "namespacefwAtoms" ],
    [ "fwAtomsBoostIO", "namespacefwAtomsBoostIO.html", "namespacefwAtomsBoostIO" ],
    [ "fwAtomsFilter", "namespacefwAtomsFilter.html", "namespacefwAtomsFilter" ],
    [ "fwAtomsPatch", "namespacefwAtomsPatch.html", "namespacefwAtomsPatch" ],
    [ "fwCamp", "namespacefwCamp.html", "namespacefwCamp" ],
    [ "fwCom", "namespacefwCom.html", "namespacefwCom" ],
    [ "fwCommand", "namespacefwCommand.html", "namespacefwCommand" ],
    [ "fwCore", "namespacefwCore.html", "namespacefwCore" ],
    [ "fwData", "namespacefwData.html", "namespacefwData" ],
    [ "fwDataCamp", "namespacefwDataCamp.html", "namespacefwDataCamp" ],
    [ "fwDataIO", "namespacefwDataIO.html", "namespacefwDataIO" ],
    [ "fwDataTools", "namespacefwDataTools.html", "namespacefwDataTools" ],
    [ "fwDcmtkIO", "namespacefwDcmtkIO.html", "namespacefwDcmtkIO" ],
    [ "fwDcmtkTools", "namespacefwDcmtkTools.html", "namespacefwDcmtkTools" ],
    [ "fwDicomIOFilter", "namespacefwDicomIOFilter.html", "namespacefwDicomIOFilter" ],
    [ "fwDicomIOFilterQt", "namespacefwDicomIOFilterQt.html", "namespacefwDicomIOFilterQt" ],
    [ "fwDicomTools", "namespacefwDicomTools.html", "namespacefwDicomTools" ],
    [ "fwGdcmIO", "namespacefwGdcmIO.html", "namespacefwGdcmIO" ],
    [ "fwGui", "namespacefwGui.html", "namespacefwGui" ],
    [ "fwGuiQt", "namespacefwGuiQt.html", "namespacefwGuiQt" ],
    [ "fwItkIO", "namespacefwItkIO.html", "namespacefwItkIO" ],
    [ "fwJobs", "namespacefwJobs.html", "namespacefwJobs" ],
    [ "fwLog", "namespacefwLog.html", "namespacefwLog" ],
    [ "fwMDSemanticPatch", "namespacefwMDSemanticPatch.html", "namespacefwMDSemanticPatch" ],
    [ "fwMedData", "namespacefwMedData.html", "namespacefwMedData" ],
    [ "fwMedDataCamp", "namespacefwMedDataCamp.html", "namespacefwMedDataCamp" ],
    [ "fwMedDataTools", "namespacefwMedDataTools.html", "namespacefwMedDataTools" ],
    [ "fwMemory", "namespacefwMemory.html", "namespacefwMemory" ],
    [ "fwPacsIO", "namespacefwPacsIO.html", "namespacefwPacsIO" ],
    [ "fwPreferences", null, [
      [ "IPreferences", "classfwPreferences_1_1IPreferences.html", "classfwPreferences_1_1IPreferences" ]
    ] ],
    [ "fwRender", "namespacefwRender.html", "namespacefwRender" ],
    [ "fwRenderVTK", "namespacefwRenderVTK.html", "namespacefwRenderVTK" ],
    [ "fwRuntime", "namespacefwRuntime.html", "namespacefwRuntime" ],
    [ "fwServices", "namespacefwServices.html", "namespacefwServices" ],
    [ "fwStructuralPatch", "namespacefwStructuralPatch.html", "namespacefwStructuralPatch" ],
    [ "fwTest", null, [
      [ "generator", null, [
        [ "Image", "classfwTest_1_1generator_1_1Image.html", null ],
        [ "Mesh", "classfwTest_1_1generator_1_1Mesh.html", "classfwTest_1_1generator_1_1Mesh" ],
        [ "Object", "classfwTest_1_1generator_1_1Object.html", null ],
        [ "RandFloat", "structfwTest_1_1generator_1_1RandFloat.html", "structfwTest_1_1generator_1_1RandFloat" ],
        [ "SeriesDB", "classfwTest_1_1generator_1_1SeriesDB.html", null ]
      ] ],
      [ "helper", null, [
        [ "Thread", "classfwTest_1_1helper_1_1Thread.html", "classfwTest_1_1helper_1_1Thread" ]
      ] ],
      [ "Data", "classfwTest_1_1Data.html", null ],
      [ "DicomReaderTest", "classfwTest_1_1DicomReaderTest.html", null ],
      [ "Exception", "classfwTest_1_1Exception.html", "classfwTest_1_1Exception" ],
      [ "File", "classfwTest_1_1File.html", null ],
      [ "LogInitialization", "structfwTest_1_1LogInitialization.html", "structfwTest_1_1LogInitialization" ]
    ] ],
    [ "fwThread", "namespacefwThread.html", "namespacefwThread" ],
    [ "fwTools", "namespacefwTools.html", "namespacefwTools" ],
    [ "fwVtkIO", null, [
      [ "helper", null, [
        [ "Mesh", "classfwVtkIO_1_1helper_1_1Mesh.html", null ],
        [ "TransferFunction", "classfwVtkIO_1_1helper_1_1TransferFunction.html", null ],
        [ "vtkLambdaCommand", "classfwVtkIO_1_1helper_1_1vtkLambdaCommand.html", "classfwVtkIO_1_1helper_1_1vtkLambdaCommand" ]
      ] ],
      [ "FilteringStream", "structfwVtkIO_1_1FilteringStream.html", "structfwVtkIO_1_1FilteringStream" ],
      [ "ImageReader", "classfwVtkIO_1_1ImageReader.html", "classfwVtkIO_1_1ImageReader" ],
      [ "ImageStream", "classfwVtkIO_1_1ImageStream.html", "classfwVtkIO_1_1ImageStream" ],
      [ "ImageWriter", "classfwVtkIO_1_1ImageWriter.html", "classfwVtkIO_1_1ImageWriter" ],
      [ "MeshReader", "classfwVtkIO_1_1MeshReader.html", "classfwVtkIO_1_1MeshReader" ],
      [ "MeshWriter", "classfwVtkIO_1_1MeshWriter.html", "classfwVtkIO_1_1MeshWriter" ],
      [ "MetaImageReader", "classfwVtkIO_1_1MetaImageReader.html", "classfwVtkIO_1_1MetaImageReader" ],
      [ "MetaImageWriter", "classfwVtkIO_1_1MetaImageWriter.html", "classfwVtkIO_1_1MetaImageWriter" ],
      [ "ModelSeriesObjWriter", "classfwVtkIO_1_1ModelSeriesObjWriter.html", "classfwVtkIO_1_1ModelSeriesObjWriter" ],
      [ "SeriesDBReader", "classfwVtkIO_1_1SeriesDBReader.html", "classfwVtkIO_1_1SeriesDBReader" ],
      [ "TypeTranslator", "structfwVtkIO_1_1TypeTranslator.html", "structfwVtkIO_1_1TypeTranslator" ],
      [ "VtiImageReader", "classfwVtkIO_1_1VtiImageReader.html", "classfwVtkIO_1_1VtiImageReader" ],
      [ "VtiImageWriter", "classfwVtkIO_1_1VtiImageWriter.html", "classfwVtkIO_1_1VtiImageWriter" ]
    ] ],
    [ "fwZip", "namespacefwZip.html", "namespacefwZip" ],
    [ "gui", "namespacegui.html", "namespacegui" ],
    [ "guiQt", "namespaceguiQt.html", "namespaceguiQt" ],
    [ "io", "namespaceio.html", "namespaceio" ],
    [ "ioAtoms", "namespaceioAtoms.html", "namespaceioAtoms" ],
    [ "ioData", "namespaceioData.html", "namespaceioData" ],
    [ "ioDcmtk", "namespaceioDcmtk.html", "namespaceioDcmtk" ],
    [ "ioDicom", "namespaceioDicom.html", "namespaceioDicom" ],
    [ "ioGdcm", "namespaceioGdcm.html", "namespaceioGdcm" ],
    [ "ioITK", "namespaceioITK.html", "namespaceioITK" ],
    [ "ioPacs", "namespaceioPacs.html", "namespaceioPacs" ],
    [ "ioQt", null, [
      [ "Plugin", "structioQt_1_1Plugin.html", "structioQt_1_1Plugin" ],
      [ "SPdfWriter", "classioQt_1_1SPdfWriter.html", "classioQt_1_1SPdfWriter" ]
    ] ],
    [ "ioTuto", null, [
      [ "ExternalDataReaderService", "classioTuto_1_1ExternalDataReaderService.html", "classioTuto_1_1ExternalDataReaderService" ],
      [ "Plugin", "structioTuto_1_1Plugin.html", "structioTuto_1_1Plugin" ]
    ] ],
    [ "ioVTK", "namespaceioVTK.html", "namespaceioVTK" ],
    [ "ioVtkGdcm", "namespaceioVtkGdcm.html", "namespaceioVtkGdcm" ],
    [ "itk", null, [
      [ "InrImageIO", "classitk_1_1InrImageIO.html", "classitk_1_1InrImageIO" ],
      [ "InrImageIOFactory", "classitk_1_1InrImageIOFactory.html", "classitk_1_1InrImageIOFactory" ]
    ] ],
    [ "memory", "namespacememory.html", "namespacememory" ],
    [ "monitor", "namespacemonitor.html", "namespacemonitor" ],
    [ "my_module", null, [
      [ "my_interface", "interfacemy__module_1_1my__interface.html", "interfacemy__module_1_1my__interface" ]
    ] ],
    [ "mymodule", null, [
      [ "myinterface", "interfacemymodule_1_1myinterface.html", "interfacemymodule_1_1myinterface" ]
    ] ],
    [ "opImageFilter", "namespaceopImageFilter.html", "namespaceopImageFilter" ],
    [ "opVTKMesh", "namespaceopVTKMesh.html", "namespaceopVTKMesh" ],
    [ "osx_install_name_tool", null, [
      [ "BinaryFile", "classosx__install__name__tool_1_1BinaryFile.html", "classosx__install__name__tool_1_1BinaryFile" ],
      [ "DepFilter", "classosx__install__name__tool_1_1DepFilter.html", null ]
    ] ],
    [ "patchMedicalData", "namespacepatchMedicalData.html", "namespacepatchMedicalData" ],
    [ "preferences", null, [
      [ "Plugin", "classpreferences_1_1Plugin.html", "classpreferences_1_1Plugin" ],
      [ "SPreferences", "classpreferences_1_1SPreferences.html", "classpreferences_1_1SPreferences" ]
    ] ],
    [ "scene2D", "namespacescene2D.html", "namespacescene2D" ],
    [ "servicesReg", "namespaceservicesReg.html", "namespaceservicesReg" ],
    [ "Tuto02DataServiceBasicCtrl", null, [
      [ "Plugin", "classTuto02DataServiceBasicCtrl_1_1Plugin.html", "classTuto02DataServiceBasicCtrl_1_1Plugin" ]
    ] ],
    [ "Tuto15MultithreadCtrl", "namespaceTuto15MultithreadCtrl.html", "namespaceTuto15MultithreadCtrl" ],
    [ "TutoTrianConverterCtrl", null, [
      [ "Plugin", "classTutoTrianConverterCtrl_1_1Plugin.html", "classTutoTrianConverterCtrl_1_1Plugin" ]
    ] ],
    [ "uiGeneric", "namespaceuiGeneric.html", "namespaceuiGeneric" ],
    [ "uiImage", "namespaceuiImage.html", "namespaceuiImage" ],
    [ "uiIO", "namespaceuiIO.html", "namespaceuiIO" ],
    [ "uiMeasurement", "namespaceuiMeasurement.html", "namespaceuiMeasurement" ],
    [ "uiMeasurementQt", "namespaceuiMeasurementQt.html", "namespaceuiMeasurementQt" ],
    [ "uiMedData", "namespaceuiMedData.html", "namespaceuiMedData" ],
    [ "uiMedDataQt", "namespaceuiMedDataQt.html", "namespaceuiMedDataQt" ],
    [ "uiPreferences", "namespaceuiPreferences.html", "namespaceuiPreferences" ],
    [ "uiReconstruction", "namespaceuiReconstruction.html", "namespaceuiReconstruction" ],
    [ "uiTF", "namespaceuiTF.html", "namespaceuiTF" ],
    [ "uiVisu", "namespaceuiVisu.html", "namespaceuiVisu" ],
    [ "visuVTK", "namespacevisuVTK.html", "namespacevisuVTK" ],
    [ "visuVTKAdaptor", "namespacevisuVTKAdaptor.html", "namespacevisuVTKAdaptor" ],
    [ "visuVTKQt", "namespacevisuVTKQt.html", "namespacevisuVTKQt" ],
    [ "visuVTKVRAdaptor", "namespacevisuVTKVRAdaptor.html", "namespacevisuVTKVRAdaptor" ],
    [ "vtkCompositeMesh", "namespacevtkCompositeMesh.html", "namespacevtkCompositeMesh" ],
    [ "vtkGdcmIO", "namespacevtkGdcmIO.html", "namespacevtkGdcmIO" ],
    [ "vtkSimpleMesh", "namespacevtkSimpleMesh.html", "namespacevtkSimpleMesh" ],
    [ "vtkSimpleNegato", "namespacevtkSimpleNegato.html", "namespacevtkSimpleNegato" ],
    [ "Camera2Clallback", "classCamera2Clallback.html", "classCamera2Clallback" ],
    [ "cat_curve", "classcat__curve.html", "classcat__curve" ],
    [ "cmCAPI", "structcmCAPI.html", "structcmCAPI" ],
    [ "cmLoadedCommandInfo", "structcmLoadedCommandInfo.html", "structcmLoadedCommandInfo" ],
    [ "curfile64_info", "structcurfile64__info.html", "structcurfile64__info" ],
    [ "DropFilter", "classDropFilter.html", "classDropFilter" ],
    [ "file_in_zip64_read_info_s", "structfile__in__zip64__read__info__s.html", "structfile__in__zip64__read__info__s" ],
    [ "Foo_FINAL", "structFoo__FINAL.html", "structFoo__FINAL" ],
    [ "fwVtkAxesActor", "classfwVtkAxesActor.html", "classfwVtkAxesActor" ],
    [ "fwVtkBoxRepresentation", "classfwVtkBoxRepresentation.html", "classfwVtkBoxRepresentation" ],
    [ "fwVtkCellPicker", "classfwVtkCellPicker.html", "classfwVtkCellPicker" ],
    [ "fwVtkPicker", "classfwVtkPicker.html", "classfwVtkPicker" ],
    [ "fwVtkWindowLevelLookupTable", "classfwVtkWindowLevelLookupTable.html", "classfwVtkWindowLevelLookupTable" ],
    [ "InitializeVtkOutputWindow", "classInitializeVtkOutputWindow.html", "classInitializeVtkOutputWindow" ],
    [ "InteractorStyle2DForNegato", "classInteractorStyle2DForNegato.html", "classInteractorStyle2DForNegato" ],
    [ "InteractorStyle3DForNegato", "classInteractorStyle3DForNegato.html", "classInteractorStyle3DForNegato" ],
    [ "Interface", "structInterface.html", null ],
    [ "Interface< I >", "structInterface_3_01I_01_4.html", null ],
    [ "linkedlist_data_s", "structlinkedlist__data__s.html", "structlinkedlist__data__s" ],
    [ "linkedlist_datablock_internal_s", "structlinkedlist__datablock__internal__s.html", "structlinkedlist__datablock__internal__s" ],
    [ "MeshesBoxClallback", "classMeshesBoxClallback.html", "classMeshesBoxClallback" ],
    [ "Options", "structOptions.html", "structOptions" ],
    [ "Patient", "classPatient.html", null ],
    [ "point", "structpoint.html", "structpoint" ],
    [ "point_list", "classpoint__list.html", "classpoint__list" ],
    [ "TestLister", "classTestLister.html", "classTestLister" ],
    [ "tm_unz_s", "structtm__unz__s.html", "structtm__unz__s" ],
    [ "tm_zip_s", "structtm__zip__s.html", "structtm__zip__s" ],
    [ "TransformCallback", "classTransformCallback.html", "classTransformCallback" ],
    [ "unz64_file_pos_s", "structunz64__file__pos__s.html", "structunz64__file__pos__s" ],
    [ "unz64_s", "structunz64__s.html", "structunz64__s" ],
    [ "unz_file_info64_internal_s", "structunz__file__info64__internal__s.html", "structunz__file__info64__internal__s" ],
    [ "unz_file_info64_s", "structunz__file__info64__s.html", "structunz__file__info64__s" ],
    [ "unz_file_info_s", "structunz__file__info__s.html", "structunz__file__info__s" ],
    [ "unz_file_pos_s", "structunz__file__pos__s.html", "structunz__file__pos__s" ],
    [ "unz_global_info64_s", "structunz__global__info64__s.html", "structunz__global__info64__s" ],
    [ "unz_global_info_s", "structunz__global__info__s.html", "structunz__global__info__s" ],
    [ "vtkOutputWindowToSpyLog", "classvtkOutputWindowToSpyLog.html", "classvtkOutputWindowToSpyLog" ],
    [ "zip64_internal", "structzip64__internal.html", "structzip64__internal" ],
    [ "zip_fileinfo", "structzip__fileinfo.html", "structzip__fileinfo" ],
    [ "zlib_filefunc64_32_def_s", "structzlib__filefunc64__32__def__s.html", "structzlib__filefunc64__32__def__s" ],
    [ "zlib_filefunc64_def_s", "structzlib__filefunc64__def__s.html", "structzlib__filefunc64__def__s" ],
    [ "zlib_filefunc_def_s", "structzlib__filefunc__def__s.html", "structzlib__filefunc__def__s" ]
];