fw4spl: fwComEd::fieldHelper::MedicalImageHelpers Class Reference
fwComEd::fieldHelper::MedicalImageHelpers Class Reference
This class contains helpers for medical image fields.
#include <MedicalImageHelpers.hpp>
Public Member Functions
template<typename T >
std::shared_ptr< ::fwData::Image::BufferType > getPixelBufferInImageSpace (::fwData::Image::sptr image, T &value)
Static Public Member Functions
static FWCOMED_API bool checkLandmarks (::fwData::Image::sptr _pImg)
Check if the image has a landmark field.
static FWCOMED_API bool checkImageValidity (::fwData::Image::sptr _pImg)
Check if the image is valid.
static FWCOMED_API bool checkImageSliceIndex (::fwData::Image::sptr _pImg)
Check if the image has slice index fields.
static FWCOMED_API::fwData::Point::sptr getImageSliceIndices (::fwData::Image::sptr _pImg)
Get the X,Y,Z slice position.
static FWCOMED_API bool checkComment (::fwData::Image::sptr _pImg)
Check if the image has a comment field.
static FWCOMED_API::fwData::Image::sptr initialize (::fwData::Image::sptr imgSrc,::fwData::Image::sptr imgToInitialize=::fwData::Image::sptr())
Initialized an image to 0 from image source (same field, pixel type, buffer size...).
template<typename INT_INDEX >
static bool isPixelNull (::fwData::Image::sptr image, INT_INDEX &point)
Return true if the pixel value is null.
static FWCOMED_API bool isBufNull (const ::fwData::Image::BufferType *buf, const unsigned int len)
template<typename T , typename INT_INDEX >
static void setPixel (::fwData::Image::sptr image, INT_INDEX &point, T &value)
Set a pixel value.
template<typename T >
static void setPixel (::fwData::Image::sptr pImage,::fwData::Point::sptr point, T &value)
Set a pixel value.
template<typename T >
static std::shared_ptr< ::fwData::Image::BufferType > getPixelBufferInImageSpace (::fwData::Image::sptr image, T &value)
Return a buffer of image type's size, containing 'value' casted to image data type.
template<typename MINMAXTYPE >
static void getMinMax (const ::fwData::Image::sptr _img, MINMAXTYPE &_min, MINMAXTYPE &_max)
Return minimum and maximum values contained in image. If image min or max value is out of MINMAXTYPE range, they are clamped to MINMAXTYPE capacity.
Detailed Description
This class contains helpers for medical image fields.
Date
2009.
Definition at line 48 of file MedicalImageHelpers.hpp.
Member Function Documentation
bool fwComEd::fieldHelper::MedicalImageHelpers::checkComment (::fwData::Image::sptr _pImg) static
Check if the image has a comment field.
If the image has no comment field, this is added with default name ("Original image").
Parameters
[in] _pImg image which contains the comment field.
Returns
true if the comment field is added.
Definition at line 150 of file MedicalImageHelpers.cpp.
References fwComEd::Dictionary::m_commentId, and SLM_ASSERT.
bool fwComEd::fieldHelper::MedicalImageHelpers::checkImageSliceIndex (::fwData::Image::sptr _pImg) static
Check if the image has slice index fields.
If the image hasn't frontal, axial and sagittal slice index fields, they are added.
Parameters
_pImg image which must contains the field.
Returns
true if the fields are added.
Definition at line 68 of file MedicalImageHelpers.cpp.
References fwData::Object::getField(), fwComEd::Dictionary::m_axialSliceIndexId, fwComEd::Dictionary::m_frontalSliceIndexId, fwComEd::Dictionary::m_sagittalSliceIndexId, and SLM_ASSERT.
Referenced by getImageSliceIndices().
bool fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity (::fwData::Image::sptr _pImg) static
Check if the image is valid.
The image size must be > 1 for each dimension.
Parameters
[in] _pImg image checked.
Returns
true if the image is valid.
Definition at line 45 of file MedicalImageHelpers.cpp.
References SLM_TRACE_FUNC.
Referenced by fwComEd::helper::Image::createTransferFunctionPool(), initialize(), uiImage::SliceIndexPositionEditor::updateSliceIndexFromImg(), fwComEd::helper::MedicalImageAdaptor::updateTransferFunction(), uiImage::SliceIndexPositionEditor::updating(), uiImage::WindowLevel::updating(), and uiImage::WindowLevel::updatingTFWindowing().
bool fwComEd::fieldHelper::MedicalImageHelpers::checkLandmarks (::fwData::Image::sptr _pImg) static
Check if the image has a landmark field.
If the image hasn't landmark field, it is added and the method return true.
Parameters
[in] _pImg image which must contains the field.
Returns
true if the field is added.
Definition at line 28 of file MedicalImageHelpers.cpp.
References fwComEd::Dictionary::m_imageLandmarksId.
fwData::Point::sptr fwComEd::fieldHelper::MedicalImageHelpers::getImageSliceIndices (::fwData::Image::sptr _pImg) static
Get the X,Y,Z slice position.
Parameters
[in] _pImg current image.
Returns
X,Y,Z slice position of the current image if exist field exist else install field and return (imgSizeX/2,imgSizeY/2,imgSizeZ/2).
Definition at line 130 of file MedicalImageHelpers.cpp.
References checkImageSliceIndex(), fwComEd::Dictionary::m_axialSliceIndexId, fwComEd::Dictionary::m_frontalSliceIndexId, fwComEd::Dictionary::m_sagittalSliceIndexId, and SLM_ASSERT.
template<typename MINMAXTYPE > void fwComEd::fieldHelper::MedicalImageHelpers::getMinMax (const ::fwData::Image::sptr _img, MINMAXTYPE & _min, MINMAXTYPE & _max) static
Return minimum and maximum values contained in image. If image min or max value is out of MINMAXTYPE range, they are clamped to MINMAXTYPE capacity.
Parameters
[in] _img : image
[out] _min : minimum value
[out] _max : maximum value
Definition at line 394 of file MedicalImageHelpers.hpp.
Referenced by fwComEd::helper::Image::createTransferFunctionPool(), uiImage::WindowLevel::info(), fwComEd::helper::MedicalImageAdaptor::updateTransferFunction(), and uiImage::WindowLevel::updating().
template<typename T > static std::shared_ptr< ::fwData::Image::BufferType > fwComEd::fieldHelper::MedicalImageHelpers::getPixelBufferInImageSpace (::fwData::Image::sptr image, T & value) static
Return a buffer of image type's size, containing 'value' casted to image data type.
Parameters
[in] image : reference image
[in] value : value to map
Referenced by setPixel().
fwData::Image::sptr fwComEd::fieldHelper::MedicalImageHelpers::initialize (::fwData::Image::sptr imgSrc, ::fwData::Image::sptr imgToInitialize = ::fwData::Image::sptr()) static
Initialized an image to 0 from image source (same field, pixel type, buffer size...).
Parameters
[in] imgSrc image which gives information (field, pixel type, buffer size...).
[in] imgToInitialize image to initialized (if not null).
Returns
Returns initialized image.
Definition at line 169 of file MedicalImageHelpers.cpp.
References checkImageValidity(), fwData::Object::copy(), and SLM_ASSERT.
template<typename INT_INDEX > bool fwComEd::fieldHelper::MedicalImageHelpers::isPixelNull (::fwData::Image::sptr image, INT_INDEX & point) static
Return true if the pixel value is null.
Parameters
[in] image : image containing the pixel
[in] point : the coordinate of the pixel in the image.
Definition at line 319 of file MedicalImageHelpers.hpp.
References fwComEd::helper::Image::getPixelBuffer().
template<typename T , typename INT_INDEX > void fwComEd::fieldHelper::MedicalImageHelpers::setPixel (::fwData::Image::sptr image, INT_INDEX & point, T & value) static
Set a pixel value.
Parameters
[in] image : image containing the pixel
[in] point : coordinate of the pixel
[in] value : the pixel value
Definition at line 254 of file MedicalImageHelpers.hpp.
References getPixelBufferInImageSpace(), and SPTR.
template<typename T > void fwComEd::fieldHelper::MedicalImageHelpers::setPixel (::fwData::Image::sptr pImage, ::fwData::Point::sptr point, T & value) static
Set a pixel value.
Parameters
[in] pImage : image containing the pixel
[in] point : coordinate of the pixel
[in] value : the pixel value
Definition at line 245 of file MedicalImageHelpers.hpp.
The documentation for this class was generated from the following files:
MedicalImageHelpers.hpp
MedicalImageHelpers.cpp