fw4spl: fwRuntime::profile::Initializer Class Reference
fwRuntime::profile::Initializer Class Reference
Starts a given bundle.
#include <Initializer.hpp>
Public Member Functions
FWRUNTIME_API Initializer (const std::string &identifier)
Constructor.
void apply ()
Applies the initializer on the bundle.
Protected Attributes
const std::string m_identifier
a bundle identifier
Detailed Description
Starts a given bundle.
Date:
2007-2009
Definition at line 30 of file Initializer.hpp.
Constructor & Destructor Documentation
fwRuntime::profile::Initializer::Initializer (const std::string & identifier)
Constructor.
Parameters:
[in] identifier a string containing a bundle identifier
Definition at line 24 of file Initializer.cpp.
Member Function Documentation
void fwRuntime::profile::Initializer::apply ()
Applies the initializer on the bundle.
Remarks:
This method should be called directly.
Definition at line 30 of file Initializer.cpp.
References fwRuntime::Runtime::findBundle(), fwRuntime::profile::getCurrentProfile(), fwRuntime::Runtime::getDefault(), m_identifier, OSLM_FATAL, OSLM_FATAL_IF, and SPTR.
The documentation for this class was generated from the following files:
Initializer.hpp
Initializer.cpp