fw4spl: uiMedData::editor::SSelector Class Reference
uiMedData::editor::SSelector Class Reference
This editor shows information about the medical data. It allows to manipulate (select, erase, ...) studies and series.
#include <SSelector.hpp>
Public Types
typedef ::fwCom::Signal< void(SPTR(::fwMedData::Series)) > SeriesDoubleClickedSignalType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SSelector)(::gui::editor::IEditor))
UIMEDDATAQT_API SSelector ()
Constructor.
virtual UIMEDDATAQT_API ~SSelector () throw ()
Destructor.
Static Public Attributes
static
UIMEDDATAQT_APIconst::fwCom::Signals::SignalKeyType s_SERIES_DOUBLE_CLICKED_SIG = "seriesDoubleClicked"
Key in m_signals map of signal m_sigSeriesDoubleClicked.
Protected Slots
void onSelectedSeries (QVector< ::fwMedData::Series::sptr > selection, QVector< ::fwMedData::Series::sptr > deselection)
Manages the selection vector according to selection/deselection.
void onDoubleClick (const QModelIndex &index)
Send a 'seriesDoubleClicked' signal when the user double click on a series. This signal holds the clicked series.
void onRemoveSeries (QVector< ::fwMedData::Series::sptr > selection)
Removes series from seriesDB and notify.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Installs GUI : create container and add selector.
virtual void stopping () throw (::fwTools::Failed)
Destroys GUI.
virtual void configuring () throw (::fwTools::Failed)
virtual void updating () throw (::fwTools::Failed)
Fill selector with the series contained in SeriesDB.
virtual void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Manages events (fwComEd::SeriesDBMsg::ADDED_OBJECTS, fwComEd::SeriesDBMsg::REMOVED_OBJECTS) This method adds/removes series in the selector widget.
virtual void info (std::ostream &_sstream)
This method is used to give information about the service. Do nothing.
Detailed Description
This editor shows information about the medical data. It allows to manipulate (select, erase, ...) studies and series.
Date:
2013.
Definition at line 34 of file SSelector.hpp.
Member Function Documentation
void uiMedData::editor::SSelector::configuring () throw (::fwTools::Failed) [protected, virtual]
     <service uid="selector" impl="::uiMedData::editor::SSelector" type="::gui::editor::IEditor" autoConnect="yes">
        <selectionId>selections</selectionId>
        <selectionMode>single|extended</selectionMode>
        <allowedRemove>yes|no</allowedRemove>
        <insertMode>yes|no</insertMode>
        <icons>
            <icon series="::fwMedData::ImageSeries" icon="Bundles/media_0-1/icons/ImageSeries.svg" />
            <icon series="::fwMedData::ModelSeries" icon="Bundles/media_0-1/icons/ModelSeries.svg" />
        </icons>
     </service>
selectionId : defines the fwId of the fwData::Vector where the selection will be put or get.
selectionMode : defines the selection mode for the series
allowedRemove : allows user to remove series
insertMode : only allows selection of uiMedData::InsertSeries
icons : defines the icon to associate for a series
series : the series classname
icon : the icon path
Implements fwServices::IService.
Definition at line 175 of file SSelector.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, SLM_ASSERT, and SLM_WARN.
void uiMedData::editor::SSelector::info (std::ostream & _sstream) [protected, virtual]
This method is used to give information about the service. Do nothing.
Todo:
Must be not implemented and class child declaration should be imposed.
Reimplemented from gui::editor::IEditor.
Definition at line 72 of file SSelector.cpp.
void uiMedData::editor::SSelector::onDoubleClick (const QModelIndex & index) [protected, slot]
Send a 'seriesDoubleClicked' signal when the user double click on a series. This signal holds the clicked series.
Parameters:
[in] index index of the clicked item in the selector.
Todo:
Manages double click on a study.
Definition at line 288 of file SSelector.cpp.
References uiMedData::widget::SelectorModel::SERIES, fwGui::dialog::MessageDialog::showMessageDialog(), SLM_ASSERT, and uiMedData::widget::SelectorModel::STUDY.
Referenced by starting().
void uiMedData::editor::SSelector::onRemoveSeries (QVector< ::fwMedData::Series::sptr > selection) [protected, slot]
Removes series from seriesDB and notify.
Parameters:
[in] selection series to remove from seriesDB.
Definition at line 316 of file SSelector.cpp.
Referenced by starting().
void uiMedData::editor::SSelector::onSelectedSeries (QVector< ::fwMedData::Series::sptr > selection, QVector< ::fwMedData::Series::sptr > deselection) [protected, slot]
Manages the selection vector according to selection/deselection.
Parameters:
[in] selection series to add in selection vector.
[in] deselection series to remove from selection vector.
Definition at line 267 of file SSelector.cpp.
References fwComEd::helper::Vector::add(), fwComEd::helper::Vector::notify(), and fwComEd::helper::Vector::remove().
Referenced by starting().
The documentation for this class was generated from the following files:
SSelector.hpp
SSelector.cpp