fw4spl: uiIO::action::SSeriesDBMerger Class Reference
uiIO::action::SSeriesDBMerger Class Reference
This action allows to load a new SeriesDB and merge it with the current SeriesDB.
#include <SSeriesDBMerger.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SSeriesDBMerger)(::fwGui::IActionSrv))
Protected Member Functions
void configuring () throw (::fwTools::Failed)
Configure action. Retrieves the IOSelector config.
void starting () throw (::fwTools::Failed)
Start action.
void updating () throw (::fwTools::Failed)
Show the SeriesDB reader selector, load the new SeriesDB and merge it the the current SeriesDB.
void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Does nothing.
void stopping () throw (::fwTools::Failed)
Stop action.
void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
This action allows to load a new SeriesDB and merge it with the current SeriesDB.
Date:
2013.
The available reader can be configured
    <service uid="action_seriesDBMerger" type="::fwGui::IActionSrv" impl="::uiIO::action::SSeriesDBMerger" autoConnect="no">
        <IOSelectorSrvConfig name="seriesDBImporterConfig" />
    </service>
With :
seriesDBImporterConfig : the id of a configuration for IOSelectorService for example
    <extension implements="::fwServices::registry::ServiceConfig">
        <id>seriesDBImporterConfig</id>
        <service>::uiIO::editor::IOSelectorService</service>
        <desc>IOSelector config to import SeriesDB</desc>
        <config>
            <type mode="reader" />
            <selection mode="exclude" />
            <addSelection service="::ioAtoms::SReader" />
        </config>
    </extension>
Definition at line 48 of file SSeriesDBMerger.hpp.
Member Function Documentation
void uiIO::action::SSeriesDBMerger::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 41 of file SSeriesDBMerger.cpp.
void uiIO::action::SSeriesDBMerger::updating () throw (::fwTools::Failed) [protected, virtual]
Show the SeriesDB reader selector, load the new SeriesDB and merge it the the current SeriesDB.
Create IOSelectorService on the new SeriesDB and execute it.
Implements fwServices::IService.
Definition at line 64 of file SSeriesDBMerger.cpp.
References fwServices::registry::ServiceConfig::getDefault(), fwComEd::helper::SeriesDB::merge(), fwComEd::helper::SeriesDB::notify(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
SSeriesDBMerger.hpp
SSeriesDBMerger.cpp