fw4spl: uiMedData::SSeriesViewer Class Reference
uiMedData::SSeriesViewer Class Reference
This Service allows to preview the selected series in the Vector. For the moment, it works only on a single selection.
#include <SSeriesViewer.hpp>
Classes
struct SeriesConfigInfo
Stucture to register configuration informations.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SSeriesViewer)(::fwServices::IController))
UIMEDDATAQT_API SSeriesViewer ()
Constructor.
virtual UIMEDDATAQT_API ~SSeriesViewer () throw ()
Destructor.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Calls updating on starting.
virtual void stopping () throw (::fwTools::Failed)
Stops the config if it is running.
virtual void configuring () throw (::fwTools::Failed)
Configures the service.
virtual void updating () throw (::fwTools::Failed)
Launch the config on the object if possible.
virtual void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Listen Vector notification when objects are added or deleted.
virtual void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
This Service allows to preview the selected series in the Vector. For the moment, it works only on a single selection.
Date:
2013.
Definition at line 26 of file SSeriesViewer.hpp.
Member Function Documentation
void uiMedData::SSeriesViewer::configuring () throw (::fwTools::Failed) [protected, virtual]
Configures the service.
    <service uid="seriesViewer" type="::fwServices::IController" impl="::uiMedData::SSeriesViewer" autoConnect="yes">
        <parentView>preview</parentView>
        <configs>
            <config id="2DSimpleConfig" type="::fwMedData::ImageSeries">
                <extract path="@image" pattern="imageID" />
            </config>
            <config id="2DPacsPreviewConfig" type="::fwDicomData::DicomSeries" >
                <parameter replace="PACS_CONFIGURATION" by="None" />
            </config>
            <config id="3DSimpleConfig" type="::fwMedData::ModelSeries" />
        </configs>
    </service>
parentView : wid of the view where the config will install its windows.
config : gives the available association between data type and associated config.
id : identifier of the AppConfig to launch
type : classname of the object stored in Vector associated to this config.
parameter : allow to pass specific value to the associ config
replace : name of the parameter to be replaced
by : specific value to replace for the parameter
extract : extracts the object from the path and replaces pattern with its fwID
Implements fwServices::IService.
Definition at line 141 of file SSeriesViewer.cpp.
References info(), fwServices::IService::m_configuration, OSLM_ASSERT, and SLM_ASSERT.
void uiMedData::SSeriesViewer::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 46 of file SSeriesViewer.cpp.
Referenced by configuring(), and updating().
void uiMedData::SSeriesViewer::updating () throw (::fwTools::Failed) [protected, virtual]
Launch the config on the object if possible.
If there is a single selection : it launchs an AppConfig on the object defined in this service configuration (stored in m_seriesConfigs). The selected object fwID replaces the 'objectID' parameter in the AppConfig. no configuration are launched if there is no selection, a multiple selection or if there is no configuration associated with the selected object.
Implements fwServices::IService.
Definition at line 85 of file SSeriesViewer.cpp.
References fwServices::registry::AppConfig::getDefault(), fwTools::fwID::getID(), fwServices::IService::getObject(), fwServices::registry::AppConfig::getUniqueIdentifier(), info(), OSLM_ASSERT, and SLM_ASSERT.
Referenced by starting().
The documentation for this class was generated from the following files:
SSeriesViewer.hpp
SSeriesViewer.cpp