fw4spl: uiMedData::editor::SModelSeriesList Class Reference
uiMedData::editor::SModelSeriesList Class Reference
SModelSeriesList service.
#include <SModelSeriesList.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SModelSeriesList)(::gui::editor::IEditor))
UIMEDDATAQT_API SModelSeriesList () throw ()
Constructor. Do nothing.
virtual UIMEDDATAQT_API ~SModelSeriesList () throw ()
Destructor. Do nothing.
Protected Types
typedef std::map< std::string,
ValueView * > DisplayedInformation
Protected Slots
void onCurrentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
Slot called when new current item is setted in m_organChoice.
void onCurrentItemChanged (QTreeWidgetItem *current, int column)
void onShowReconstructions (int state)
void onOrganChoiceVisibility (QTreeWidgetItem *item, int column)
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
This method launches the IEditor::starting method.
virtual void stopping () throw (::fwTools::Failed)
This method launches the IEditor::stopping method.
virtual void receiving (SPTR(const ::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Managment of observations (overides)
virtual void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual void configuring () throw (fwTools::Failed)
Configures the editor.
virtual void info (std::ostream &_sstream)
Overrides.
void updateReconstructions ()
void fillTree ()
Detailed Description
SModelSeriesList service.
Date:
2013.
Definition at line 47 of file SModelSeriesList.hpp.
Member Function Documentation
void uiMedData::editor::SModelSeriesList::configuring () throw (fwTools::Failed) [protected, virtual]
Configures the editor.
Configuration example :
     <enable_hide_all>true</enable_hide_all>
     <columns>
         <organ_name>@organ_name</organ_name>
         <volume_cc view="positive" >@volume</volume_cc>
     </columns>
enable_hide_all : if 'true', allows to hide all models through a single checkbox displayed in UI (default value is 'true', allowed values are 'true' and 'false').
columns : defines colums to be shown in reconstruction list. XML child element names follow fwData::Reconstruction serialization attribute names. The attribute 'view' is optional and can has the following values :
positive : a numeric value is displayed only if it is positive. Otherwise, 'Unknown' is displayed.
Exceptions:
fwTools::Failed
Implements fwServices::IService.
Definition at line 196 of file SModelSeriesList.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, SLM_ASSERT, and SLM_TRACE_FUNC.
void uiMedData::editor::SModelSeriesList::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 252 of file SModelSeriesList.cpp.
References updating().
void uiMedData::editor::SModelSeriesList::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 237 of file SModelSeriesList.cpp.
References onCurrentItemChanged().
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
SModelSeriesList.hpp
SModelSeriesList.cpp