fw4spl: fwData::Graph Class Reference
fwData::Graph Class Reference
This class defines a graph object.
#include <Graph.hpp>
Public Types
typedef std::map< Edge::sptr, std::pair< Node::sptr, Node::sptr > > ConnectionContainer
typedef std::set< Node::sptr > NodeContainer
typedef std::vector< ::fwData::Object::sptr > UpdatedDataType
Type of signal m_sigUpdated.
typedef ::fwCom::Signal< void(UpdatedDataType, UpdatedDataType) > UpdatedSignalType
Update signal type Signal updated is composed of two parameters which represent added and removed elements in the graph.
Public Types inherited from fwData::Object
typedef ::fwData::factory::Key Key
typedef std::string FieldNameType
typedef std::vector< FieldNameType > FieldNameVectorType
typedef ::boost::unordered_map< FieldNameType,::fwData::Object::sptr > FieldMapType
typedef ::boost::unordered_map< ::fwData::Object::csptr,::fwData::Object::sptr > DeepCopyCacheType
typedef ::fwCom::Signal< void() > ModifiedSignalType
Type of signal m_sigModified.
typedef std::map< std::string,::fwData::Object::sptr > FieldsContainerType
Type of signal m_sigModified.
typedef ::fwCom::Signal< void(FieldsContainerType) > AddedFieldsSignalType
Type of signal when objects are added.
typedef ::fwCom::Signal< void(FieldsContainerType, FieldsContainerType) > ChangedFieldsSignalType
Type of signal when objects are changed (newObjects, oldObjects)
typedef ::fwCom::Signal< void(FieldsContainerType) > RemovedFieldsSignalType
Type of signal when objects are removed.
Public Types inherited from fwTools::DynamicAttributes< ::fwData::Object >
typedef std::string AttrNameType
typedef std::shared_ptr< ::fwData::Object > AttrType
typedef std::vector< AttrNameType > AttrNameVectorType
typedef ::boost::reference_wrapper< AttrType > AttrRefType
typedef std::map< AttrNameType, AttrRefType > AttrMapType
typedef std::shared_ptr< const ::fwData::Object > ConstAttrType
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Graph)(::fwData::Object))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< Graph >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Graph)(::fwData::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWDATA_API Graph (::fwData::Object::Key key)
Constructor.
virtual FWDATA_API ~Graph ()
Destructor.
FWDATA_API bool addNode (Node::sptr _node)
add a node
FWDATA_API bool removeNode (Node::csptr _node)
remove a node
FWDATA_API const ConnectionContainer & getCRefConnections () const
Get the connection container.
FWDATA_API ConnectionContainer & getRefConnections ()
FWDATA_API bool addEdge (Edge::sptr _edge, Node::csptr _nodeSource, Node::csptr _nodeDestination)
Add and edge.
FWDATA_API Edge::sptr makeConnection (Node::csptr _nodeSource, std::string _nodeSourceOutputPortID, Node::csptr _nodeDestination, std::string _nodeDestinationInputPortID, std::string _EdgeNature)
create an edge from given info and add edge in the graph
FWDATA_API bool removeEdge (Edge::sptr _edge)
remove an edge
FWDATA_API Node::sptr getSourceNode (Edge::sptr _edge)
Get source node.
FWDATA_API Node::sptr getDestinationNode (Edge::sptr _edge)
Get destination node.
FWDATA_API Node::sptr getNode (Edge::sptr _edge, bool _upStream)
Get node.
FWDATA_API std::vector< Edge::sptr > getInputEdges (Node::csptr _node)
Get input edges.
FWDATA_API std::vector< Edge::sptr > getOutputEdges (Node::csptr _node)
Get output edges.
FWDATA_API std::vector< Edge::sptr > getEdges (const Node::csptr &_node, bool _upStream, const std::string &_nature="", const std::string &_portID="")
Get a vector of edges.
FWDATA_API std::vector< ::fwData::Node::sptr > getNodes (const ::fwData::Node::csptr &node, bool upStream, const std::string &nature="", const std::string &portID="")
Get a vector of nodes.
FWDATA_API size_t getNbNodes () const
FWDATA_API size_t getNbEdges () const
FWDATA_API void shallowCopy (const Object::csptr &_source)
FWDATA_API void cachedDeepCopy (const Object::csptr &_source, DeepCopyCacheType &cache)
FWDATA_API bool haveConnectedEdges (Node::csptr _node) const
Check if an edge is connected to the node.
FWDATA_API NodeContainer & getRefNodes ()
Get the node container.
FWDATA_API const NodeContainer & getCRefNodes () const
Get the node container.
Public Member Functions inherited from fwData::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwTools::Object))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwTools::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWDATA_API::fwData::Object::sptr getField (const FieldNameType &name,::fwData::Object::sptr defaultValue=::fwData::Object::sptr()) const
Returns a pointer of corresponding field (null if non exist).
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > setDefaultField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue)
Returns a pointer of corresponding field. If field did not exist, it is set to defaultValue if defaultValue is not null.
FWDATA_API::fwData::Object::csptr getConstField (const FieldNameType &name) const
Returns a pointer of corresponding field (null if non exist).
FWDATA_API const FieldMapType & getFields () const
Returns fields map.
FWDATA_API FieldNameVectorType getFieldNames () const
Returns vector of field names.
FWDATA_API void setField (const FieldNameType &name,::fwData::Object::sptr obj)
Register field with specified name. If the name does already exist, the matching field will be replaced.
FWDATA_API void setFields (const FieldMapType &fieldMap)
Replace the field map content.
FWDATA_API void removeField (const FieldNameType &name)
Removes field with specified name.
FWDATA_API void updateFields (const FieldMapType &fieldMap)
Updates the field map content with fieldMap. Duplicated name will be replaced.
virtual FWDATA_API void shallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void deepCopy (const ::fwData::Object::csptr &source)
Make a deep copy from the source Calling this method may invalidate any DumpLock, RescursiveLock or helper on the object. Prefer using fwData::Object::copy instead.
FWDATA_API void fieldShallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source)
A deep copy of fields (objects in m_children)
::fwCore::mt::ReadWriteMutex & getMutex ()
Returns the object's mutex.
Public Member Functions inherited from fwTools::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual ConstAttrType getConstAttribute (AttrNameType attrName) const
virtual AttrType getAttribute (AttrNameType attrName)
bool hasAttribute (AttrNameType attrName)
virtual void setAttribute (AttrNameType attrName, AttrType _obj)
virtual AttrNameVectorType getAttributeNames ()
virtual void __FWTOOLS_ATTRIBUTES_REGISTER_FUNC_NAME ()
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwData::Object
static bool isTypeOf (const std::string &type)
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Attributes
static FWDATA_API const bool UP_STREAM = true
static FWDATA_API const bool DOWN_STREAM = false
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_UPDATED_SIG = "updated"
Updated signal key.
Static Public Attributes inherited from fwData::Object
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_MODIFIED_SIG = "modified"
Key in m_signals map of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_ADDED_FIELDS_SIG = "addedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_CHANGED_FIELDS_SIG = "changedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_REMOVED_FIELDS_SIG = "removedFields"
Type of signal m_sigModified.
Protected Attributes
NodeContainer m_nodes
ConnectionContainer m_connections
UpdatedSignalType::sptr m_sigUpdated
Updated signal.
Protected Attributes inherited from fwData::Object
FieldMapType m_fields
Fields.
::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect object access.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwTools::DynamicAttributes< ::fwData::Object >
AttrMapType __FWTOOLS_ATTRIBUTE_MAP_NAME
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions inherited from fwData::Object
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
virtual FWDATA_API void cachedDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)=0
Internal-use methods to implement Object's deepCopy.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
__FWCORE_CLASS_TYPEDEFS ((fwID))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((fwID)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Protected Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual AttrRefType getAttributeRef (AttrNameType attrName)
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Static Protected Member Functions inherited from fwData::Object
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
This class defines a graph object.
A graph is represented by connections between Edge and Node.
See also
fwData::Edge, fwData::Node
Definition at line 30 of file fwData/include/fwData/Graph.hpp.
Constructor & Destructor Documentation
fwData::Graph::Graph (::fwData::Object::Key key)
Constructor.
Parameters
key Private construction key
Definition at line 32 of file fwData/src/fwData/Graph.cpp.
References m_sigUpdated, and s_UPDATED_SIG.
Member Function Documentation
fwData::Graph::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< Graph > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Graph)(::fwData::Object)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Graph)(fwData::Object)).
bool fwData::Graph::addEdge (Edge::sptr _edge, Node::csptr _nodeSource, Node::csptr _nodeDestination)
Add and edge.
Returns
true if success
nodes exist
edge is unique
port is compatible identifier & type
Definition at line 121 of file fwData/src/fwData/Graph.cpp.
Referenced by getCRefConnections(), and makeConnection().
bool fwData::Graph::addNode (Node::sptr _node)
add a node
Returns
true on success(node not already in graph)
Definition at line 52 of file fwData/src/fwData/Graph.cpp.
Referenced by getCRefConnections().
const Graph::ConnectionContainer & fwData::Graph::getCRefConnections () const
Get the connection container.
A connection is defined by an edge, a source node and a destination node.
Returns
map<Edge, pair<source node, destination node> >
Definition at line 309 of file fwData/src/fwData/Graph.cpp.
References addEdge(), addNode(), fwData::Object::copy(), fwData::Object::fieldDeepCopy(), fwData::Object::fieldShallowCopy(), getClassname(), and OSLM_ASSERT.
Node::sptr fwData::Graph::getDestinationNode (Edge::sptr _edge)
Get destination node.
Parameters
[in] _edge edge associated with the node
Definition at line 181 of file fwData/src/fwData/Graph.cpp.
References getNode().
std::vector< Edge::sptr > fwData::Graph::getEdges (const Node::csptr & _node, bool _upStream, const std::string & _nature = "", const std::string & _portID = "")
Get a vector of edges.
Parameters
[in] _node node associated with the edges
[in] _upStream if true _node is a source node, else _node is a destination node
[in] _nature if nature is an empty string : no check on nature of edge
[in] _portID if portID not specified (no check) : porID must be an BoolupStream port of given node
Returns
the vector of all edges with correct nature and portID where _node is a source/destination node
Definition at line 225 of file fwData/src/fwData/Graph.cpp.
References SLM_ASSERT.
Referenced by getInputEdges(), getNodes(), and getOutputEdges().
std::vector< Edge::sptr > fwData::Graph::getInputEdges (Node::csptr _node)
Get input edges.
Parameters
[in] _node source node
Returns
a vector of edges where _node is source node
Definition at line 211 of file fwData/src/fwData/Graph.cpp.
References getEdges().
size_t fwData::Graph::getNbEdges () const
Returns
Number of edges
Definition at line 302 of file fwData/src/fwData/Graph.cpp.
size_t fwData::Graph::getNbNodes () const
Returns
Number of nodes
Definition at line 295 of file fwData/src/fwData/Graph.cpp.
Node::sptr fwData::Graph::getNode (Edge::sptr _edge, bool _upStream)
Get node.
Parameters
[in] _edge edge associated with the node
[in] _upStream if true return source node, else return destination node
Returns
source or destination node if edge exists, else return a new node
Definition at line 188 of file fwData/src/fwData/Graph.cpp.
Referenced by getDestinationNode(), and getSourceNode().
std::vector<::fwData::Node::sptr > fwData::Graph::getNodes (const ::fwData::Node::csptr & node, bool upStream, const std::string & nature = "", const std::string & portID = "")
Get a vector of nodes.
Parameters
[in] node node associated with the nodes
[in] upStream if true _node is a source node, else _node is a destination node
[in] nature if nature is an empty string : no check on nature of edge
[in] portID if portID not specified (no check) : porID muts be an BoolupStream port of given node
Returns
the vector of all nodes associated with _node
Definition at line 270 of file fwData/src/fwData/Graph.cpp.
References getEdges().
std::vector< Edge::sptr > fwData::Graph::getOutputEdges (Node::csptr _node)
Get output edges.
Parameters
[in] _node destination node
Returns
a vector of edges where _node is destination node
Definition at line 218 of file fwData/src/fwData/Graph.cpp.
References getEdges().
Node::sptr fwData::Graph::getSourceNode (Edge::sptr _edge)
Get source node.
Parameters
[in] _edge edge associated with the node
Definition at line 174 of file fwData/src/fwData/Graph.cpp.
References getNode().
bool fwData::Graph::haveConnectedEdges (Node::csptr _node) const
Check if an edge is connected to the node.
Returns
true if at least one edge is connected to given node
Definition at line 85 of file fwData/src/fwData/Graph.cpp.
Referenced by removeNode().
Edge::sptr fwData::Graph::makeConnection (Node::csptr _nodeSource, std::string _nodeSourceOutputPortID, Node::csptr _nodeDestination, std::string _nodeDestinationInputPortID, std::string _EdgeNature)
create an edge from given info and add edge in the graph
Returns
new edge created if success else return null one
Definition at line 99 of file fwData/src/fwData/Graph.cpp.
References addEdge().
bool fwData::Graph::removeEdge (Edge::sptr _edge)
remove an edge
Parameters
[in] _edge edge to be remove
Returns
true iif success
Definition at line 167 of file fwData/src/fwData/Graph.cpp.
bool fwData::Graph::removeNode (Node::csptr _node)
remove a node
Returns
true on success
Definition at line 59 of file fwData/src/fwData/Graph.cpp.
References haveConnectedEdges().
The documentation for this class was generated from the following files:
fwData/include/fwData/Graph.hpp
fwData/src/fwData/Graph.cpp