fw4spl: fwGdcmIO::helper::DicomDataReader Class Reference
fwGdcmIO::helper::DicomDataReader Class Reference
This class contains helpers to handle GDCM data reading.
#include <DicomDataReader.hxx>
Static Public Member Functions
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static std::string getTagValue (const ::gdcm::DataSet &dataset, const std::string &charset="", const ::fwLog::Logger::sptr &logger=nullptr)
Return a string from a tag found in dataset. An empty string returned means the tag is not found or empty. The value is returned without binary space padding.
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static std::string getTagValue (const std::string &buffer, const std::string &charset="", const ::fwLog::Logger::sptr &logger=0)
Return an utf-8 tag value from the tag value's buffer.
template<std::uint16_t GROUP, std::uint16_t ELEMENT, typename T >
static const T getTagValue (const ::gdcm::DataSet &dataset)
Return a value from a tag found in dataset.
Detailed Description
This class contains helpers to handle GDCM data reading.
Definition at line 27 of file DicomDataReader.hxx.
Member Function Documentation
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static std::string fwGdcmIO::helper::DicomDataReader::getTagValue (const ::gdcm::DataSet & dataset, const std::string & charset = "", const ::fwLog::Logger::sptr & logger = nullptr) inline static
Return a string from a tag found in dataset. An empty string returned means the tag is not found or empty. The value is returned without binary space padding.
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Parameters
[in] dataset Data set containing the tag
[in] charset Specific Character Set (if empty assuming ASCII).
[in] logger Logger used for encoding issue
Note
charset shall be set if SpecificCharacterSet (0008,0005) is definied and tag's VR is SH, LO, ST, PN, LT or UT.
Returns
The tag value as string
Definition at line 45 of file DicomDataReader.hxx.
References fwGdcmIO::helper::Encoding::convertString().
Referenced by fwGdcmIO::helper::DicomDir::findDicomDir().
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static std::string fwGdcmIO::helper::DicomDataReader::getTagValue (const std::string & buffer, const std::string & charset = "", const ::fwLog::Logger::sptr & logger = 0) inline static
Return an utf-8 tag value from the tag value's buffer.
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Parameters
[in] buffer Tag value's buffer
[in] charset Specific Character Set (if empty assuming ASCII).
[in] logger Logger used for encoding issue
Note
charset shall be set if SpecificCharacterSet (0008,0005) is definied and tag's VR is SH, LO, ST, PN, LT or UT.
Returns
The tag value as string
Definition at line 102 of file DicomDataReader.hxx.
References fwGdcmIO::helper::Encoding::convertString().
template<std::uint16_t GROUP, std::uint16_t ELEMENT, typename T > static const T fwGdcmIO::helper::DicomDataReader::getTagValue (const ::gdcm::DataSet & dataset) inline static
Return a value from a tag found in dataset.
Template Parameters
GROUP Group of the tag.
ELEMENT Element of the tag.
T Type of value.
Parameters
[in] dataset Data set of tags.
Returns
The tag value.
Definition at line 140 of file DicomDataReader.hxx.
The documentation for this class was generated from the following file:
DicomDataReader.hxx