fw4spl: fwNetworkIO::http::ClientQt Class Reference
fwNetworkIO::http::ClientQt Class Reference
HTTP client using Qt Network.
#include <ClientQt.hpp>
Public Slots
void processError (QNetworkReply::NetworkError errorCode)
Slot triggered when an error occurs.
Public Member Functions
FWNETWORKIO_API QByteArray get (Request::sptr request)
Retrieves data over network.
FWNETWORKIO_API std::string getFile (Request::sptr request)
Retrieves data over network.
FWNETWORKIO_API Request::HeadersType head (Request::sptr request)
Performs head request.
FWNETWORKIO_API QByteArray post (Request::sptr request, const QByteArray &body)
Performs POST request.
FWNETWORKIO_API ClientQt ()
virtual FWNETWORKIO_API ~ClientQt ()
Detailed Description
HTTP client using Qt Network.
Definition at line 35 of file ClientQt.hpp.
Constructor & Destructor Documentation
fwNetworkIO::http::ClientQt::ClientQt ()
Constructor/Destructor
Definition at line 24 of file ClientQt.cpp.
fwNetworkIO::http::ClientQt::~ClientQt () virtual
Constructor/Destructor
Definition at line 30 of file ClientQt.cpp.
Member Function Documentation
QByteArray fwNetworkIO::http::ClientQt::get (Request::sptr request)
Retrieves data over network.
Parameters
request the request
Definition at line 36 of file ClientQt.cpp.
References processError().
Referenced by ioDicomWeb::SQueryEditor::updating(), ioDicomWeb::SSeriesPuller::updating(), and ioDicomWeb::SSliceIndexDicomPullerEditor::updating().
std::string fwNetworkIO::http::ClientQt::getFile (Request::sptr request)
Retrieves data over network.
Parameters
request the request
Definition at line 58 of file ClientQt.cpp.
References fwTools::UUID::generateUUID(), fwTools::System::getTemporaryFolder(), and processError().
Referenced by ioDicomWeb::SSeriesPuller::updating(), and ioDicomWeb::SSliceIndexDicomPullerEditor::updating().
Request::HeadersType fwNetworkIO::http::ClientQt::head (Request::sptr request)
Performs head request.
Parameters
request the request
Returns
headers resulting of the request
Definition at line 158 of file ClientQt.cpp.
QByteArray fwNetworkIO::http::ClientQt::post (Request::sptr request, const QByteArray & body)
Performs POST request.
Parameters
request the request
Returns
body The body content
Definition at line 124 of file ClientQt.cpp.
References processError().
Referenced by ioDicomWeb::SQueryEditor::updating(), ioDicomWeb::SSeriesPusher::updating(), ioDicomWeb::SSeriesPuller::updating(), and ioDicomWeb::SSliceIndexDicomPullerEditor::updating().
The documentation for this class was generated from the following files:
ClientQt.hpp
ClientQt.cpp