fw4spl: fwIO::IWriter Class Reference
fwIO::IWriter Class Reference abstract
Writer service API. It manages extension points definition and extension configuration.
#include <IWriter.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
virtual FWIO_API void configureWithIHM ()=0
Configure the image path (by default does nothing).
virtual FWIO_API::fwIO::IOPathType getIOPathType () const
This method must be implemented by concrete service writers that use path file system to write data.
FWIO_APIconst::boost::filesystem::path & getFile () const
Returns the file path set by the user or set during service configuration.
FWIO_API void setFile (const ::boost::filesystem::path &file)
Sets file path.
FWIO_APIconst::fwIO::LocationsType & getFiles () const
Returns file paths set by the user or set during service configuration.
FWIO_API void setFiles (const ::fwIO::LocationsType &files)
Sets file paths.
FWIO_APIconst::boost::filesystem::path & getFolder () const
Returns folder path set by the user or set during service configuration.
FWIO_API void clearLocations ()
Clear any location set by the setFile/setFiles/setFolder setter.
FWIO_APIconst::fwIO::LocationsType & getLocations () const
Returns file/files/folder paths set by the user or set during service configuration.
FWIO_API void setFolder (const ::boost::filesystem::path &folder)
Sets folder path.
FWIO_API void setFileFolder (::boost::filesystem::path folder)
Slot: Sets the folder when a path is configured in FILE or FILES mode This is ignored if a path is not configured.
FWIO_API bool hasLocationDefined () const
Returns if a location has been defined (by the configuration process or directly by user)
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Attributes
Slots API
static FWIO_APIconst::fwCom::Slots::SlotKeyType s_SET_FILE_FOLDER = "setFileFolder"
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Member Functions
virtual FWIO_API void configuring () override
This method proposes to parse xml configuration to retrieve file/files/folder paths.
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual FWSERVICES_API void starting ()=0
Initialize the service activity.
virtual FWSERVICES_API void stopping ()=0
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual void swapping ()
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API void updating ()=0
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
virtual FWSERVICES_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated objects signals, this method is used for obj/srv auto connection.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
std::string m_windowTitle
Title of the window that will open when the configureWithIHM slot is called.
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
Writer service API. It manages extension points definition and extension configuration.
Slots
setFileFolder(const ::boost::filesystem::path&) : Sets the folder when a path is configured in FILE or FILES mode
This class represents the base interface for writer services. Use the base service methods :
The service is configured with methods setConfiguration(cfg) and configure()
The method start() initialize the service
To write the object use update() method
Finally we must call stop() before deleting the service
Definition at line 33 of file IWriter.hpp.
Member Function Documentation
virtual FWIO_API void fwIO::IWriter::configureWithIHM () pure virtual
Configure the image path (by default does nothing).
This method is used to find the file path using a file selector.
Implemented in ioQt::SPdfWriter, ioAtoms::SWriter, ioVTK::SModelSeriesObjWriter, ioData::MeshWriterService, ioVTK::SImageWriter, ioVTK::SModelSeriesWriter, ioVTK::SMeshWriter, ioITK::JpgImageWriterService, ioVTK::SImageSeriesWriter, ioITK::InrImageWriterService, ioVtkGdcm::SImageSeriesWriter, ioITK::SJpgImageSeriesWriter, ioGdcm::SDicomSeriesWriter, ioITK::SImageSeriesWriter, ioGdcm::SSurfaceSegmentationWriter, ioGdcm::SSeriesDBWriter, and ioData::TransformationMatrix3DWriterService.
void fwIO::IWriter::configuring () override protected virtual
This method proposes to parse xml configuration to retrieve file/files/folder paths.
You can implement your configuring method if you wan check another information or information not correspond to a path on filesystem, else you must use this generic approach.
Sample configuration for a file:
 <service ... >
  <file>/home/user/myFile.jpg<file/>
 </service>
Sample configuration for many files:
 <service ... >
  <file>/home/user/myFile01.jpg<file/>
  <file>/home/user/myFile02.jpg<file/>
  <file>/home/user/myFile03.jpg<file/>
 </service>
Sample configuration for a folder:
 <service ... >
  <folder>/home/user/myFolder<folder/>
 </service>
You may specify the title of the modal file selection window with the windowTitle config attribute as such:
 <service ... >
  <windowTitle>Example window title</windowTitle>
 </service>
Implements fwServices::IService.
Reimplemented in ioVTK::SImageWriter, ioData::MeshWriterService, ioAtoms::SWriter, ioVTK::SModelSeriesObjWriter, ioVTK::SModelSeriesWriter, ioQt::SPdfWriter, ioVTK::SMeshWriter, ioVTK::SImageSeriesWriter, ioData::TransformationMatrix3DWriterService, ioVtkGdcm::SImageSeriesWriter, ioGdcm::SDicomSeriesWriter, ioGdcm::SSurfaceSegmentationWriter, ioGdcm::SSeriesDBWriter, ioITK::JpgImageWriterService, ioITK::InrImageWriterService, ioITK::SJpgImageSeriesWriter, and ioITK::SImageSeriesWriter.
Definition at line 122 of file IWriter.cpp.
References fwIO::FILE, fwIO::FILES, fwIO::FOLDER, getIOPathType(), fwServices::IService::m_configuration, m_windowTitle, setFile(), setFiles(), setFolder(), SLM_ASSERT, and fwIO::TYPE_NOT_DEFINED.
Referenced by ioITK::SImageSeriesWriter::configuring(), ioITK::SJpgImageSeriesWriter::configuring(), ioITK::InrImageWriterService::configuring(), ioITK::JpgImageWriterService::configuring(), ioGdcm::SSeriesDBWriter::configuring(), ioGdcm::SSurfaceSegmentationWriter::configuring(), ioGdcm::SDicomSeriesWriter::configuring(), ioVtkGdcm::SImageSeriesWriter::configuring(), ioData::TransformationMatrix3DWriterService::configuring(), ioVTK::SImageSeriesWriter::configuring(), ioVTK::SMeshWriter::configuring(), ioQt::SPdfWriter::configuring(), ioVTK::SModelSeriesWriter::configuring(), ioVTK::SModelSeriesObjWriter::configuring(), ioAtoms::SWriter::configuring(), ioData::MeshWriterService::configuring(), and ioVTK::SImageWriter::configuring().
const ::boost::filesystem::path & fwIO::IWriter::getFile () const
Returns the file path set by the user or set during service configuration.
Precondition
exception if a file path is not defined (m_locations.empty())
exception if service does not support FILE mode
Definition at line 40 of file IWriter.cpp.
References fwIO::FILE, and getIOPathType().
Referenced by ioITK::SImageSeriesWriter::updating(), ioITK::InrImageWriterService::updating(), ioData::TransformationMatrix3DWriterService::updating(), ioVTK::SImageSeriesWriter::updating(), ioVTK::SMeshWriter::updating(), ioAtoms::SWriter::updating(), ioData::MeshWriterService::updating(), and ioVTK::SImageWriter::updating().
const ::fwIO::LocationsType & fwIO::IWriter::getFiles () const
Returns file paths set by the user or set during service configuration.
Precondition
exception if a file path is not defined (m_locations.empty())
exception if service does not support FILES mode
Definition at line 58 of file IWriter.cpp.
References fwIO::FILES, and getIOPathType().
const ::boost::filesystem::path & fwIO::IWriter::getFolder () const
Returns folder path set by the user or set during service configuration.
Precondition
exception if a folder path is not defined (m_locations.empty())
exception if service does not support FOLDER mode
Definition at line 75 of file IWriter.cpp.
References fwIO::FOLDER, and getIOPathType().
Referenced by ioITK::SJpgImageSeriesWriter::updating(), ioITK::JpgImageWriterService::updating(), ioGdcm::SSeriesDBWriter::updating(), ioGdcm::SSurfaceSegmentationWriter::updating(), ioGdcm::SDicomSeriesWriter::updating(), ioVtkGdcm::SImageSeriesWriter::updating(), ioVTK::SModelSeriesWriter::updating(), and ioVTK::SModelSeriesObjWriter::updating().
fwIO::IOPathType fwIO::IWriter::getIOPathType () const virtual
This method must be implemented by concrete service writers that use path file system to write data.
This method returns supported path format (file, files or folder). A reader can support file and folder, or files and folder, but not file and files (because files include file concept).
Reimplemented in ioQt::SPdfWriter, ioAtoms::SWriter, ioVTK::SImageWriter, ioVtkGdcm::SImageSeriesWriter, ioVTK::SModelSeriesObjWriter, ioGdcm::SDicomSeriesWriter, ioData::MeshWriterService, ioVTK::SModelSeriesWriter, ioVTK::SMeshWriter, ioGdcm::SSurfaceSegmentationWriter, ioVTK::SImageSeriesWriter, ioITK::JpgImageWriterService, ioGdcm::SSeriesDBWriter, ioITK::InrImageWriterService, ioITK::SJpgImageSeriesWriter, ioITK::SImageSeriesWriter, and ioData::TransformationMatrix3DWriterService.
Definition at line 177 of file IWriter.cpp.
Referenced by configuring(), getFile(), getFiles(), getFolder(), setFile(), setFileFolder(), setFiles(), and setFolder().
const ::fwIO::LocationsType & fwIO::IWriter::getLocations () const
Returns file/files/folder paths set by the user or set during service configuration.
Precondition
exception if a file path is not defined (m_locations.empty())
Definition at line 107 of file IWriter.cpp.
Referenced by ioQt::SPdfWriter::updating().
void fwIO::IWriter::setFile (const ::boost::filesystem::path & file)
Sets file path.
Precondition
exception if service does not support FILE mode
Definition at line 49 of file IWriter.cpp.
References fwIO::FILE, and getIOPathType().
Referenced by ioData::TransformationMatrix3DWriterService::configureWithIHM(), ioITK::SImageSeriesWriter::configureWithIHM(), ioITK::InrImageWriterService::configureWithIHM(), ioVTK::SImageSeriesWriter::configureWithIHM(), ioVTK::SMeshWriter::configureWithIHM(), ioVTK::SImageWriter::configureWithIHM(), ioData::MeshWriterService::configureWithIHM(), ioAtoms::SWriter::configureWithIHM(), ioQt::SPdfWriter::configureWithIHM(), and configuring().
void fwIO::IWriter::setFileFolder (::boost::filesystem::path folder)
Slot: Sets the folder when a path is configured in FILE or FILES mode This is ignored if a path is not configured.
Precondition
exception if service does not support FILE or FILES mode
Definition at line 93 of file IWriter.cpp.
References fwIO::FILE, fwIO::FILES, and getIOPathType().
void fwIO::IWriter::setFiles (const ::fwIO::LocationsType & files)
Sets file paths.
Precondition
exception if service does not support FILES mode
Definition at line 67 of file IWriter.cpp.
References fwIO::FILES, and getIOPathType().
Referenced by configuring().
void fwIO::IWriter::setFolder (const ::boost::filesystem::path & folder)
Sets folder path.
Precondition
exception if service does not support FOLDER mode
Definition at line 84 of file IWriter.cpp.
References fwIO::FOLDER, and getIOPathType().
Referenced by ioGdcm::SSeriesDBWriter::configureWithIHM(), ioGdcm::SSurfaceSegmentationWriter::configureWithIHM(), ioGdcm::SDicomSeriesWriter::configureWithIHM(), ioITK::SJpgImageSeriesWriter::configureWithIHM(), ioVtkGdcm::SImageSeriesWriter::configureWithIHM(), ioITK::JpgImageWriterService::configureWithIHM(), ioVTK::SModelSeriesWriter::configureWithIHM(), ioVTK::SModelSeriesObjWriter::configureWithIHM(), and configuring().
The documentation for this class was generated from the following files:
IWriter.hpp
IWriter.cpp