fw4spl: scene2D::adaptor::SNegato Class Reference
scene2D::adaptor::SNegato Class Reference
IAdaptor implementation to display one slice of an image.
#include <SNegato.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
SCENE2D_API::fwServices::IService::KeyConnectionsMap getAutoConnections () const override
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
virtual FWDATATOOLS_API ~MedicalImageAdaptor ()
Destructor. Do nothing.
virtual FWDATATOOLS_API void setOrientation (Orientation orientation)
Set the image orientation.
Orientation getOrientation () const
Return the image orientation.
FWDATATOOLS_API void setTransferFunction (const ::fwData::TransferFunction::sptr &tf)
Set the current TransferFunction.
Public Member Functions inherited from fwRenderQt::IAdaptor
FWRENDERQT_API void setZValue (float _zValue)
Set the zValue.
FWRENDERQT_API float getZValue () const
Get the zValue.
FWRENDERQT_API std::shared_ptr< ::fwRenderQt::SRender > getScene2DRender () const
Get the render that manages the IAdaptor.
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwRenderQt::IAdaptor
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Member Functions
SCENE2D_API void configuring () override
Configure the service before starting. Apply the configuration to service.
SCENE2D_API void starting () override
Initialize the service activity.
SCENE2D_API void updating () override
Perform some computations according to object (this service is attached to) attribute values and its internal state.
SCENE2D_API void stopping () override
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
SCENE2D_API void swapping (const KeyType &key) override
Retrives the current transfer function.
SCENE2D_API void processInteraction (::fwRenderQt::data::Event &_event) override
virtual SCENE2D_API void updateTFPoints () override
Slot: updates the displayed image.
virtual SCENE2D_API void updateTFWindowing (double window, double level) override
Slot: updates the displayed image.
Protected Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
FWDATATOOLS_API MedicalImageAdaptor ()
Constructor. Do nothing.
FWDATATOOLS_API void setOrientation (int orientation)
Set the orientation of the image.
FWDATATOOLS_API void getImageSpacing (double spacing[3]) const
Get the image spacing.
FWDATATOOLS_API void getImageOrigin (double origin[3]) const
Get the image origin.
FWDATATOOLS_API void getImageDataSize (int size[3]) const
Get the image data size (number of slices).
FWDATATOOLS_API void getImageSize (double size[3]) const
Get the image size (= dataSize * spacing).
FWDATATOOLS_API void getCurrentSliceCenter (double center[3])
Get the slice center.
FWDATATOOLS_API void worldToSliceIndex (const double world[3], int index[3])
Convert world coordinates to slice index coordinates.
FWDATATOOLS_API void worldToImageSliceIndex (const double world[3], int index[3])
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void sliceIndexToWorld (const int index[3], double world[3])
Convert from world coordinates system to image coordinates system.
FWDATATOOLS_API::fwData::Image::sptr getImage () const
Return the image.
template<typename FLOAT_ARRAY_3 >
void getImageSpacing (FLOAT_ARRAY_3 spacing)
Get the image spacing.
template<typename INT_INDEX >
void getImageDataSize (INT_INDEX size)
Get the image data size (number of slices).
template<typename WORLD , typename INT_INDEX >
void worldToSliceIndex (const WORLD world, INT_INDEX *index)
Convert world coordinates to slice index coordinates.
template<typename WORLD , typename INT_INDEX >
void worldToImageSliceIndex (const WORLD world, INT_INDEX *index)
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void getPlane (double points[4][3], int sliceNumber)
Return the 4 points of the image plane.
FWDATATOOLS_API bool setSliceIndex (const int index[3])
Set the slice index.
FWDATATOOLS_API void getSliceIndex (::fwData::Integer::sptr index[3])
Get the slice index.
FWDATATOOLS_API void updateImageInfos (::fwData::Image::sptr image)
Update the image information (slice index, min/max,...)
FWDATATOOLS_API void createTransferFunction (::fwData::Image::sptr image)
Create and set the default transfer function.
FWDATATOOLS_API void setOrCreateTF (const ::fwData::TransferFunction::sptr &_tf, const fwData::Image::sptr &_image)
Sets the transfer function, creates one if _tf is null (.
FWDATATOOLS_API::fwData::TransferFunction::sptr getTransferFunction () const
Get the current transfer function.
FWDATATOOLS_API void installTFConnections ()
Install connections to listen TF modifications.
FWDATATOOLS_API void removeTFConnections ()
Remove the TF connections.
FWDATATOOLS_API void installTFSlots (::fwCom::HasSlots *hasslots)
Install the slots to managed TF modifications.
Protected Member Functions inherited from fwRenderQt::IAdaptor
FWRENDERQT_API IAdaptor () noexcept
Constructor, set the zValue to 0.
virtual FWRENDERQT_API ~IAdaptor () noexcept
Basic destructor, do nothing.
FWRENDERQT_API void configureParams ()
Parse the xml configuration for Axis, z value and opacity.
FWRENDERQT_API Point2DType mapAdaptorToScene (const Point2DType &_xy, const ::fwRenderQt::data::Axis::sptr &_xAxis, const ::fwRenderQt::data::Axis::sptr &_yAxis) const
FWRENDERQT_API Point2DType mapSceneToAdaptor (const Point2DType &_xy, const ::fwRenderQt::data::Axis::sptr &_xAxis, const ::fwRenderQt::data::Axis::sptr &_yAxis) const
FWRENDERQT_API ViewSizeRatio getViewSizeRatio () const
Return the ratio between view's initial size and its current size.
FWRENDERQT_API ViewportSizeRatio getViewportSizeRatio () const
Return the ratio between viewport's initial size and its current size.
FWRENDERQT_API void initializeViewSize ()
Initialize the source values used for computing view's size ratio.
FWRENDERQT_API void initializeViewportSize ()
Initialize the source values used for computing viewport's size ratio.
FWRENDERQT_API Scene2DRatio getRatio () const
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual void swapping ()
Swap the service from associated object to another object.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwDataTools::helper::MedicalImageAdaptor
enum Orientation { X_AXIS = 0, Y_AXIS, Z_AXIS }
Image orientation.
Public Types inherited from fwRenderQt::IAdaptor
typedef std::pair< double, double > Point2DType
Point2D coordinate <X, Y>
typedef std::pair< float, float > ViewSizeRatio
<width, height>
typedef std::pair< float, float > ViewportSizeRatio
<width, height>
typedef std::pair< float, float > Scene2DRatio
<width, height>
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Types inherited from fwDataTools::helper::MedicalImageAdaptor
typedef ::fwCom::Slot< void()> UpdateTFPointsSlotType
Slot called when transfer function points are modified.
typedef ::fwCom::Slot< void(double, double)> UpdateTFWindowingSlotType
Slot called when transfer function points are modified.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Attributes inherited from fwDataTools::helper::MedicalImageAdaptor
Orientation m_orientation
Image orientation.
::fwData::Integer::sptr m_axialIndex
Axial slice index.
::fwData::Integer::sptr m_frontalIndex
Frontal slice index.
::fwData::Integer::sptr m_sagittalIndex
Sagittal slice index.
UpdateTFPointsSlotType::sptr m_slotUpdateTFPoints
Slot called when transfer function points are modified.
UpdateTFWindowingSlotType::sptr m_slotUpdateTFWindowing
Slot called when transfer function windowing is modified.
Protected Attributes inherited from fwRenderQt::IAdaptor
::fwRenderQt::data::Axis::sptr m_xAxis
The x Axis.
::fwRenderQt::data::Axis::sptr m_yAxis
The y Axis.
float m_zValue
float m_opacity
Opacity of the adaptor. Default value set to 1 (opaque).
ViewSizeRatio m_viewInitialSize
ViewportSizeRatio m_viewportInitialSize
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Detailed Description
IAdaptor implementation to display one slice of an image.
Slots
updateSliceIndex() : update image slice index
updateSliceType() : update image slice type
updateBuffer() : update image buffer
updateVisibility() : update image visibility
updateTFPoints() : update the displayed image according to the new points
updateTFWindowing(double window, double level) : update the displayed image according to the new window and level
XML Configuration
 <service uid="negato" type="::scene2D::adaptor::SNegato" autoConnect="yes">
     <inout key="image" uid="..." />
     <inout key="tf" uid="..." />
     <config xAxis="xAxis" yAxis="yAxis" color="gray" opacity="0.25" zValue="5" />
 </service>
In-Out
image [fwData::Image]: image to display.
tf [fwData::TransferFunction] (optional): the current TransferFunction. If it is not defined, we use the image's default transferFunction (CT-GreyLevel). The transferFunction's signals are automatically connected to the slots 'updateTFPoints' and 'updateTFWindowing'.
Configuration
config (mandatory): contains the adaptor configuration
xAxis (optional): x axis associated to the adaptor
yAxis (optional): y axis associated to the adaptor
zValue (optional, default=0): z value of the layer
opacity (optional, default=1.0): adaptor opacity (float)
orientation (optional, default axial): image orientation, axial, sagittal or frontal
changeSliceType (optional, default true): specify if the negato allow slice type events
Definition at line 63 of file SNegato.hpp.
Member Function Documentation
void scene2D::adaptor::SNegato::configuring () override protected virtual
Configure the service before starting. Apply the configuration to service.
See also
configure()
Implements fwServices::IService.
Definition at line 74 of file SNegato.cpp.
References fwDataTools::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwRenderQt::IAdaptor::configureParams(), fwServices::IService::getConfigTree(), fwRenderQt::IAdaptor::getScene2DRender(), fwDataTools::helper::MedicalImageAdaptor::getTransferFunction(), fwDataTools::helper::MedicalImageAdaptor::m_axialIndex, fwDataTools::helper::MedicalImageAdaptor::m_frontalIndex, fwDataTools::helper::MedicalImageAdaptor::m_sagittalIndex, fwRenderQt::IAdaptor::m_yAxis, and SLM_FATAL.
fwServices::IService::KeyConnectionsMap scene2D::adaptor::SNegato::getAutoConnections () const override virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Image::s_MODIFIED_SIG to this::s_UPDATE_SLOT Connect Image::s_SLICE_INDEX_MODIFIED_SIG to this::s_UPDATE_SLICE_INDEX_SLOT Connect Image::s_SLICE_TYPE_MODIFIED_SIG to this::s_UPDATE_SLICE_TYPE_SLOT Connect Image::s_VISIBILITY_MODIFIED_SIG to this::s_UPDATE_VISIBILITY_SLOT Connect Image::s_BUFFER_MODIFIED_SIG to this::s_UPDATE_BUFFER_SLOT
Reimplemented from fwServices::IService.
Definition at line 562 of file SNegato.cpp.
References fwData::Image::s_BUFFER_MODIFIED_SIG, fwData::Object::s_MODIFIED_SIG, fwData::Image::s_SLICE_INDEX_MODIFIED_SIG, fwData::Image::s_SLICE_TYPE_MODIFIED_SIG, fwServices::IService::s_UPDATE_SLOT, and fwData::Image::s_VISIBILITY_MODIFIED_SIG.
void scene2D::adaptor::SNegato::processInteraction (::fwRenderQt::data::Event & _event) override protected virtual
Interact with the mouse events catched on the IAdaptor (virtual function, its behavior is only defined in the specific adaptors).
Reimplemented from fwRenderQt::IAdaptor.
Definition at line 434 of file SNegato.cpp.
References fwRenderQt::IAdaptor::getScene2DRender(), fwDataTools::helper::MedicalImageAdaptor::getTransferFunction(), fwDataTools::helper::MedicalImageAdaptor::m_slotUpdateTFWindowing, fwData::TransferFunction::s_WINDOWING_MODIFIED_SIG, and updating().
void scene2D::adaptor::SNegato::starting () override protected virtual
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also
start()
Implements fwServices::IService.
Definition at line 292 of file SNegato.cpp.
References fwDataTools::helper::MedicalImageAdaptor::createTransferFunction(), fwRenderQt::IAdaptor::getScene2DRender(), fwDataTools::helper::MedicalImageAdaptor::installTFConnections(), fwRenderQt::IAdaptor::m_xAxis, fwRenderQt::IAdaptor::m_yAxis, fwRenderQt::IAdaptor::m_zValue, fwDataTools::helper::MedicalImageAdaptor::setTransferFunction(), and fwDataTools::helper::MedicalImageAdaptor::updateImageInfos().
void scene2D::adaptor::SNegato::stopping () override protected virtual
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also
stop()
Implements fwServices::IService.
Definition at line 421 of file SNegato.cpp.
References fwRenderQt::IAdaptor::getScene2DRender(), and fwDataTools::helper::MedicalImageAdaptor::removeTFConnections().
void scene2D::adaptor::SNegato::updating () override protected virtual
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also
update()
Implements fwServices::IService.
Definition at line 321 of file SNegato.cpp.
Referenced by processInteraction(), and swapping().
The documentation for this class was generated from the following files:
SNegato.hpp
SNegato.cpp