fw4spl: gui::action::SSignal Class Reference
gui::action::SSignal Class Reference
Simple Signal serviceTriggers a signal when the action is triggered. If the action uses a confirmation, different signals are emitted depending on the confirmation result.
#include <SSignal.hpp>
Public Types
typedef std::vector
< ::fwData::Object::sptr > ObjectVectorType
typedef
::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef ::fwCom::Signal< void(ObjectVectorType) > TrigerredSignalType
Type of triggered signal.
typedef ::fwCom::Slot< void(ObjectVectorType) > SetObjectsSlotType
Type of setObject slot.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SSignal)(::fwGui::IActionSrv))
GUI_API SSignal () throw ()
Constructor. Do nothing.
virtual GUI_API ~SSignal () throw ()
Destructor. Do nothing.
Protected Member Functions
virtual GUI_API void info (std::ostream &_sstream)
This method gives information about the class. Do nothing.
GUI_API void updating () throw (fwTools::Failed)
This method emit a signal.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Do nothing.
GUI_API void configuring () throw (::fwTools::Failed)
Configures the service.
virtual GUI_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual GUI_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual void setObjects (ObjectVectorType objects)
setObjects slot's method
SPTR (TrigerredSignalType) m_sigTriggered
Signal trigerred when action has been trigerred.
SPTR (TrigerredSignalType) m_sigCancelled
Signal trigerred when action has been cancelled.
SPTR (SetObjectsSlotType) m_slotSetObjects
setObject slot : save a vector of objects
Protected Attributes
ObjectVectorType m_objects
vector of objects passed to triggered signals
Detailed Description
Simple Signal service
Triggers a signal when the action is triggered. If the action uses a confirmation, different signals are emitted depending on the confirmation result.
Definition at line 36 of file SSignal.hpp.
Member Function Documentation
void gui::action::SSignal::configuring () throw (::fwTools::Failed) [protected, virtual]
Configures the service.
     <service uid="..." type="::fwGui::IActionSrv" impl="::gui::action::SSignal" autoConnect="no" />
See also fwGui::IActionSrv::configuring for more configuration parameters.
See also:
IActionSrv::configuring
Implements fwServices::IService.
Definition at line 118 of file SSignal.cpp.
References fwGui::IActionSrv::initialize(), and SLM_TRACE_FUNC.
void gui::action::SSignal::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 69 of file SSignal.cpp.
References fwGui::IActionSrv::actionServiceStarting(), and SLM_TRACE_FUNC.
void gui::action::SSignal::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 77 of file SSignal.cpp.
References fwGui::IActionSrv::actionServiceStopping(), m_objects, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
SSignal.hpp
SSignal.cpp