fw4spl: ioData::MeshWriterService Class Reference
ioData::MeshWriterService Class Reference
Mesh writer service.
#include <MeshWriterService.hpp>
Public Types
typedef ::io::IWriter SuperClass
Super class of writer services.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((MeshWriterService)(::io::IWriter))
IODATA_API MeshWriterService ()
Constructor : does nothing.
IODATA_API ~MeshWriterService () throw ()
destructor
virtual IODATA_API::io::IOPathType getIOPathType () const
Return path type managed by the service, here FILE.
Specified writer service methods (override from ::io::IWriter)
virtual IODATA_API std::vector
< std::string > getSupportedExtensions ()
returns (filename) extension
IODATA_API void configureWithIHM ()
Configure the mesh path.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual void starting () throw (::fwTools::Failed)
Starting method : default does nothing.
virtual void stopping () throw (::fwTools::Failed)
Stopping method : default does nothing.
IODATA_API void updating () throw (::fwTools::Failed)
Updating method. This method is called by update() from base service (fwServices::IService)
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : default does nothing.
virtual IODATA_API void info (std::ostream &_sstream)
Info method.
Detailed Description
Mesh writer service.
Date:
2011.
Service writing a mesh object.
This service has no specified start and stop method.
Use setConfiguration(cfg) and configure() methods to configure the mesh filename.
Use update() to write the mesh and notify observers.
Service registered details :
fwServicesRegisterMacro(::io::IWriter , ::ioData::MeshWriterService , ::fwData::Mesh)
Definition at line 31 of file ioData/include/ioData/MeshWriterService.hpp.
Member Function Documentation
void ioData::MeshWriterService::configureWithIHM () [virtual]
Configure the mesh path.
This method is used to find the file path using a file selector.
Implements io::IWriter.
Definition at line 65 of file ioData/src/ioData/MeshWriterService.cpp.
References fwGui::dialog::LocationDialog::addFilter(), io::IWriter::clearLocations(), fwGui::dialog::LocationDialog::saveDefaultLocation(), fwGui::dialog::LocationDialog::setDefaultLocation(), io::IWriter::setFile(), fwGui::dialog::LocationDialog::setOption(), fwGui::dialog::LocationDialog::setTitle(), fwGui::dialog::LocationDialog::show(), and SLM_TRACE_FUNC.
void ioData::MeshWriterService::info (std::ostream & _sstream) [protected, virtual]
Info method.
This method is used to give informations about the service.
Parameters:
[out] _sstream output stream
Reimplemented from fwServices::IService.
Definition at line 36 of file ioData/src/ioData/MeshWriterService.cpp.
References fwServices::IService::info().
void ioData::MeshWriterService::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [inline, protected]
React on modifications : default does nothing.
Note:
This method is automatically called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 109 of file ioData/include/ioData/MeshWriterService.hpp.
virtual void ioData::MeshWriterService::starting () throw (::fwTools::Failed) [inline, protected, virtual]
Starting method : default does nothing.
This method is used to initialize the service.
Implements fwServices::IService.
Definition at line 84 of file ioData/include/ioData/MeshWriterService.hpp.
virtual void ioData::MeshWriterService::stopping () throw (::fwTools::Failed) [inline, protected, virtual]
Stopping method : default does nothing.
The stopping method is empty for this service.
Implements fwServices::IService.
Definition at line 91 of file ioData/include/ioData/MeshWriterService.hpp.
void ioData::MeshWriterService::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method. This method is called by update() from base service (fwServices::IService)
This method is used to update the service. The mesh is written with the writer fwDataIO::writer::MeshWriter. Notify writing.
Implements fwServices::IService.
Definition at line 92 of file ioData/src/ioData/MeshWriterService.cpp.
References io::IWriter::getFile(), io::IWriter::hasLocationDefined(), fwGui::dialog::MessageDialog::showMessageDialog(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
ioData/include/ioData/MeshWriterService.hpp
ioData/src/ioData/MeshWriterService.cpp