fw4spl: fwGdcmIO::writer::tid::Fiducial Class Reference
fwGdcmIO::writer::tid::Fiducial Class Reference
Fiducial TID.
#include <Fiducial.hpp>
Public Member Functions
FWGDCMIO_API Fiducial (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::csptr &image)
Constructor.
virtual FWGDCMIO_API ~Fiducial ()
Destructor.
virtual FWGDCMIO_API void createNodes (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &parent, bool useSCoord3D=true)
Create nodes according to the template.
Public Member Functions inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
FWGDCMIO_API TemplateID (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< const ::fwData::Image > &object)
Constructor.
virtual FWGDCMIO_API ~TemplateID ()
Destructor.
Protected Member Functions
void createFiducial (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &parent, const std::shared_ptr< const ::fwData::Point > &point, unsigned int id, bool useSCoord3D)
Create a fiducial node.
Additional Inherited Members
Protected Attributes inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
std::shared_ptr< ::gdcm::Writer > m_writer
GDCM Writer.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< const ::fwData::Image > m_object
FW4SPL Object.
Detailed Description
Fiducial TID.
See also
TID t1tt3 FIXME: Set the final TID
Definition at line 30 of file writer/tid/Fiducial.hpp.
Constructor & Destructor Documentation
fwGdcmIO::writer::tid::Fiducial::Fiducial (const std::shared_ptr< ::gdcm::Writer > & writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::csptr & image)
Constructor.
Parameters
[in] writer GDCM writer that must be enriched
[in] instance DICOM instance used to share informations between modules
[in] image Image data
Definition at line 44 of file writer/tid/Fiducial.cpp.
Member Function Documentation
void fwGdcmIO::writer::tid::Fiducial::createFiducial (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & parent, const std::shared_ptr< const ::fwData::Point > & point, unsigned int id, bool useSCoord3D) protected
Create a fiducial node.
Parameters
[in] parent Parent node
[in] point Fiducial (landmark) point
[in] id ID of the ficudial
[in] useSCoord3D True if we must use 3D coordinates
Definition at line 76 of file writer/tid/Fiducial.cpp.
References fwGdcmIO::container::sr::DicomSRNode::addSubNode(), fwGdcmIO::helper::DicomDataTools::convertPointToFrameNumber(), fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_instance, fwDataTools::fieldHelper::Image::m_labelId, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object, and SPTR.
Referenced by createNodes().
void fwGdcmIO::writer::tid::Fiducial::createNodes (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & parent, bool useSCoord3D = true) virtual
Create nodes according to the template.
Parameters
[in] parent Parent node
[in] useSCoord3D True if we must write SCOORD3D, false if we must write SCOORD
Definition at line 59 of file writer/tid/Fiducial.cpp.
References createFiducial(), fwDataTools::fieldHelper::Image::m_imageLandmarksId, and fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object.
Referenced by fwGdcmIO::writer::tid::MeasurementReport::createRootNode().
The documentation for this class was generated from the following files:
writer/tid/Fiducial.hpp
writer/tid/Fiducial.cpp