fw4spl: fwComEd::VectorMsg Class Reference
fwComEd::VectorMsg Class Reference
Object event message specialized for Vector : store modification information.
#include <VectorMsg.hpp>
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((VectorMsg)(::fwServices::ObjectMsg),(()),::fwServices::factory::message::New< VectorMsg >)
FWCOMED_API VectorMsg (::fwServices::ObjectMsg::Key key)
Constructor.
virtual FWCOMED_API ~VectorMsg () throw ()
Destructor : does nothing.
FWCOMED_API void appendAddedObject (::fwData::Object::sptr _pNewObject)
This method add an object in the vector of added objects.
FWCOMED_API::fwData::Vector::sptr getAddedObjects () const
Return the vector of the added objects.
FWCOMED_API void appendRemovedObject (::fwData::Object::sptr _pOldObject)
This method add an object in the vector of removed objects.
FWCOMED_API::fwData::Vector::sptr getRemovedObjects () const
Return the vector of the removed objects.
Static Public Attributes
static FWCOMED_API std::string ADDED_OBJECTS = "ADDED_OBJECTS"
Event identifier used to inform that objects were added.
static FWCOMED_API std::string REMOVED_OBJECTS = "REMOVED_OBJECTS"
Event identifier used to inform that objects were removed.
Detailed Description
Object event message specialized for Vector : store modification information.
Date:
2005-2009.
See also:
fwServices::ObjectMsg
Definition at line 26 of file VectorMsg.hpp.
Constructor & Destructor Documentation
fwComEd::VectorMsg::VectorMsg (::fwServices::ObjectMsg::Key key)
Constructor.
Parameters:
key Private construction key
Definition at line 27 of file VectorMsg.cpp.
Member Function Documentation
void fwComEd::VectorMsg::appendAddedObject (::fwData::Object::sptr _pNewObject)
This method add an object in the vector of added objects.
Parameters:
[in] _pNewObject : the added object.
Definition at line 40 of file VectorMsg.cpp.
References ADDED_OBJECTS, fwServices::ObjectMsg::addEvent(), fwServices::ObjectMsg::hasEvent(), and SLM_ASSERT.
void fwComEd::VectorMsg::appendRemovedObject (::fwData::Object::sptr _pOldObject)
This method add an object in the vector of removed objects.
Parameters:
[in] _pOldObject : the object which will be removed.
Definition at line 62 of file VectorMsg.cpp.
References fwServices::ObjectMsg::addEvent(), fwServices::ObjectMsg::hasEvent(), REMOVED_OBJECTS, and SLM_ASSERT.
The documentation for this class was generated from the following files:
VectorMsg.hpp
VectorMsg.cpp