fw4spl: fwGdcmIO::reader::tid::Fiducial Class Reference
fwGdcmIO::reader::tid::Fiducial Class Reference
Fiducial TID.
#include <Fiducial.hpp>
Public Member Functions
FWGDCMIO_API Fiducial (const std::shared_ptr< const ::fwMedData::DicomSeries > &dicomSeries, const std::shared_ptr< ::gdcm::Reader > &reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::sptr &image, const ::fwLog::Logger::sptr &logger)
Constructor.
virtual FWGDCMIO_API ~Fiducial ()
Destructor.
virtual FWGDCMIO_API void readNode (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &node)
Read a fiducial node.
Public Member Functions inherited from fwGdcmIO::reader::tid::TemplateID< ::fwData::Image >
FWGDCMIO_API TemplateID (const std::shared_ptr< const ::fwMedData::DicomSeries > &dicomSeries, const std::shared_ptr< ::gdcm::Reader > &reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< ::fwData::Image > &object, const ::fwLog::Logger::sptr &logger)
Constructor.
virtual FWGDCMIO_API ~TemplateID ()
Destructor.
Protected Member Functions
void addLandmark (double x, double y, double z, const std::string &label)
Add a landmark into the image.
Additional Inherited Members
Protected Attributes inherited from fwGdcmIO::reader::tid::TemplateID< ::fwData::Image >
std::shared_ptr< const ::fwMedData::DicomSeries > m_dicomSeries
Dicom Series.
std::shared_ptr< ::gdcm::Reader > m_reader
GDCM Reader.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< ::fwData::Image > m_object
FW4SPL Object.
::fwLog::Logger::sptr m_logger
Logger.
Detailed Description
Fiducial TID.
See also
TID t1tt3 FIXME: Set the final TID
Definition at line 27 of file reader/tid/Fiducial.hpp.
Constructor & Destructor Documentation
FWGDCMIO_API fwGdcmIO::reader::tid::Fiducial::Fiducial (const std::shared_ptr< const ::fwMedData::DicomSeries > & dicomSeries, const std::shared_ptr< ::gdcm::Reader > & reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::sptr & image, const ::fwLog::Logger::sptr & logger)
Constructor.
Parameters
[in] dicomSeries DicomSeries used to access computed tag values.
[in] reader GDCM reader that must be used to read series.
[in] instance DICOM instance used to share informations between modules
[in] image FW4SPL data object
[in] logger Logger
Member Function Documentation
void fwGdcmIO::reader::tid::Fiducial::addLandmark (double x, double y, double z, const std::string & label) protected
Add a landmark into the image.
Parameters
x X coordinate
y Y coordinate
z Z coordinate
label Landmark label
Definition at line 126 of file reader/tid/Fiducial.cpp.
References fwDataTools::fieldHelper::Image::m_imageLandmarksId, and fwDataTools::fieldHelper::Image::m_labelId.
void fwGdcmIO::reader::tid::Fiducial::readNode (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & node) virtual
Read a fiducial node.
Parameters
[in] node Node that must be read
Definition at line 47 of file reader/tid/Fiducial.cpp.
References fwGdcmIO::helper::DicomDataTools::convertFrameNumberToZCoordinate(), fwGdcmIO::container::sr::DicomSRNode::getCodedAttribute(), fwGdcmIO::container::sr::DicomSRImageNode::getFrameNumber(), fwGdcmIO::container::sr::DicomSRSCoordNode::getGraphicDataContainer(), fwGdcmIO::container::sr::DicomSRSCoord3DNode::getGraphicDataContainer(), fwGdcmIO::container::sr::DicomSRNode::getSubNodeContainer(), fwGdcmIO::container::sr::DicomSRTextNode::getTextValue(), and SPTR.
Referenced by fwGdcmIO::reader::tid::MeasurementReport::readSR().
The documentation for this class was generated from the following files:
reader/tid/Fiducial.hpp
reader/tid/Fiducial.cpp