fw4spl: fwMemory::BufferManager Class Reference
fwMemory::BufferManager Class Reference
BufferManager implementation.
#include <BufferManager.hpp>
Classes
struct BufferStats
struct StreamInfo
Public Types
enum LoadingModeType { DIRECT, LAZY }
typedef void * BufferType
typedef const void * ConstBufferType
typedef BufferType * BufferPtrType
typedef void const *const * ConstBufferPtrType
typedef BufferInfo::SizeType SizeType
typedef ::fwCom::Signal< void() > UpdatedSignalType
typedef std::map< ConstBufferPtrType, BufferInfo > BufferInfoMapType
Public Member Functions
virtual bool isA (const std::string &type) const
virtual FWMEMORY_API::boost::shared_future< void > registerBuffer (BufferPtrType bufferPtr)
Hook called when a new BufferObject is created.
virtual FWMEMORY_API::boost::shared_future< void > unregisterBuffer (BufferPtrType bufferPtr)
Hook called when a BufferObject is destroyed.
virtual FWMEMORY_API::boost::shared_future< void > allocateBuffer (BufferPtrType bufferPtr, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
Hook called when an allocation is requested from a BufferObject.
virtual FWMEMORY_API::boost::shared_future< void > setBuffer (BufferPtrType bufferPtr,::fwMemory::BufferManager::BufferType buffer, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
Hook called when a request is made to set BufferObject's buffer from an external buffer.
virtual FWMEMORY_API::boost::shared_future< void > reallocateBuffer (BufferPtrType bufferPtr, SizeType newSize)
Hook called when a reallocation is requested from a BufferObject.
virtual FWMEMORY_API::boost::shared_future< void > destroyBuffer (BufferPtrType bufferPtr)
Hook called when a destruction is requested from a BufferObject.
virtual FWMEMORY_API::boost::shared_future< void > swapBuffer (BufferPtrType bufA, BufferPtrType bufB)
Hook called when a request to swap two BufferObject contents is made.
virtual FWMEMORY_API::boost::shared_future< std::shared_ptr< void > > lockBuffer (ConstBufferPtrType bufferPtr)
Hook called when a BufferObject is locked.
virtual FWMEMORY_API::boost::shared_future< bool > unlockBuffer (ConstBufferPtrType bufferPtr)
Hook called when a BufferObject lock is released.
virtual FWMEMORY_API::boost::shared_future< std::string > toString () const
returns BufferManager status string
std::shared_ptr< UpdatedSignalType > getUpdatedSignal ()
Returns a boost::signal emitted when an action has been hooked.
FWMEMORY_API::boost::shared_future< BufferInfoMapType > getBufferInfos () const
Returns the Buffer info map.
FWMEMORY_API::boost::shared_future< BufferStats > getBufferStats () const
Returns managed buffers statistics.
FWMEMORY_API void setDumpPolicy (const std::shared_ptr< ::fwMemory::IPolicy > &policy)
Sets the dump policy.
FWMEMORY_API std::shared_ptr< ::fwMemory::IPolicy > getDumpPolicy () const
Returns the dump policy.
FWMEMORY_API::boost::shared_future< StreamInfo > getStreamInfo (const ConstBufferPtrType bufferPtr) const
Returns stream info.
FWMEMORY_API::boost::shared_future< void > setIStreamFactory (BufferPtrType bufferPtr, const std::shared_ptr< ::fwMemory::stream::in::IFactory > &factory, SizeType size,::fwMemory::FileHolder fsFile,::fwMemory::FileFormatType format, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
FWMEMORY_API LoadingModeType getLoadingMode () const
FWMEMORY_API void setLoadingMode (LoadingModeType mode)
::fwCore::mt::ReadWriteMutex & getMutex () const
FWMEMORY_API::boost::shared_future< bool > dumpBuffer (ConstBufferPtrType bufferPtr)
Dump/restore a buffer.
FWMEMORY_API::boost::shared_future< bool > restoreBuffer (ConstBufferPtrType bufferPtr)
Dump/restore a buffer.
FWMEMORY_API::boost::shared_future< bool > writeBuffer (ConstBufferType buffer, SizeType size,::boost::filesystem::path &path)
Write/read a buffer.
FWMEMORY_API::boost::shared_future< bool > readBuffer (BufferType buffer, SizeType size,::boost::filesystem::path &path)
Write/read a buffer.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWMEMORY_API BufferStats computeBufferStats (const BufferInfoMapType &bufferInfo)
static FWMEMORY_API BufferManager::sptr getDefault ()
Returns the current BufferManager instance.
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
virtual void registerBufferImpl (BufferPtrType bufferPtr)
BufferManager'a Implementation.
virtual void unregisterBufferImpl (BufferPtrType bufferPtr)
BufferManager'a Implementation.
virtual void allocateBufferImpl (BufferPtrType bufferPtr, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
BufferManager'a Implementation.
virtual void setBufferImpl (BufferPtrType bufferPtr,::fwMemory::BufferManager::BufferType buffer, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
BufferManager'a Implementation.
virtual void reallocateBufferImpl (BufferPtrType bufferPtr, SizeType newSize)
BufferManager'a Implementation.
virtual void destroyBufferImpl (BufferPtrType bufferPtr)
BufferManager'a Implementation.
virtual void swapBufferImpl (BufferPtrType bufA, BufferPtrType bufB)
BufferManager'a Implementation.
virtual std::shared_ptr< void > lockBufferImpl (ConstBufferPtrType bufferPtr)
BufferManager'a Implementation.
virtual bool unlockBufferImpl (ConstBufferPtrType bufferPtr)
BufferManager'a Implementation.
virtual std::string toStringImpl () const
BufferManager'a Implementation.
bool dumpBufferImpl (ConstBufferPtrType buffer)
BufferManager'a Implementation.
bool restoreBufferImpl (ConstBufferPtrType buffer)
BufferManager'a Implementation.
bool writeBufferImpl (ConstBufferType buffer, SizeType size,::boost::filesystem::path &path)
BufferManager'a Implementation.
bool readBufferImpl (BufferType buffer, SizeType size,::boost::filesystem::path &path)
BufferManager'a Implementation.
BufferInfoMapType getBufferInfosImpl () const
BufferManager'a Implementation.
StreamInfo getStreamInfoImpl (const ConstBufferPtrType bufferPtr) const
BufferManager'a Implementation.
void setIStreamFactoryImpl (BufferPtrType bufferPtr, const std::shared_ptr< ::fwMemory::stream::in::IFactory > &factory, SizeType size,::fwMemory::FileHolder fsFile,::fwMemory::FileFormatType format, const ::fwMemory::BufferAllocationPolicy::sptr &policy)
BufferManager'a Implementation.
FWMEMORY_API bool dumpBuffer (BufferInfo &info, BufferPtrType bufferPtr)
Dump/restore a buffer.
FWMEMORY_API bool restoreBuffer (BufferInfo &info, BufferPtrType bufferPtr, SizeType size=0)
Dump/restore a buffer.
Protected Attributes
std::shared_ptr< UpdatedSignalType > m_updatedSig
::fwCore::LogicStamp m_lastAccess
BufferInfoMapType m_bufferInfos
std::shared_ptr< ::fwMemory::IPolicy > m_dumpPolicy
LoadingModeType m_loadingMode
std::shared_ptr< fwThread::Worker > m_worker
mutable::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect concurrent access in BufferManager.
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
BufferManager implementation.
This implementation purpose is to manage memory load, freeing memory and restoring freed buffers as needed.
A dump policy is used to trigger memory freeing process. The restore process is always triggers when a lock is requested on a dumped buffer.
Definition at line 61 of file BufferManager.hpp.
Member Function Documentation
boost::shared_future< void > fwMemory::BufferManager::allocateBuffer (BufferManager::BufferPtrType bufferPtr, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr & policy) virtual
Hook called when an allocation is requested from a BufferObject.
Parameters
bufferPtr BufferObject's buffer pointer
size requested size for allocation
policy BufferObject's allocation policy
Definition at line 90 of file BufferManager.cpp.
References allocateBufferImpl().
boost::shared_future< void > fwMemory::BufferManager::destroyBuffer (BufferManager::BufferPtrType bufferPtr) virtual
Hook called when a destruction is requested from a BufferObject.
Parameters
bufferPtr BufferObject's buffer pointer
Definition at line 212 of file BufferManager.cpp.
References destroyBufferImpl().
boost::shared_future< bool > fwMemory::BufferManager::dumpBuffer (BufferManager::ConstBufferPtrType bufferPtr)
Dump/restore a buffer.
Keeps up to date buffer's information
Parameters
bufferPtr Buffer to dump/restore
Returns
true on success
Definition at line 339 of file BufferManager.cpp.
References dumpBufferImpl().
Referenced by dumpBufferImpl().
bool fwMemory::BufferManager::dumpBuffer (BufferInfo & info, BufferManager::BufferPtrType bufferPtr) protected
Dump/restore a buffer.
Used by public dump/restoreBuffer methods
Definition at line 353 of file BufferManager.cpp.
References fwTools::System::getTemporaryFolder(), fwMemory::BufferInfo::loaded, OSLM_TRACE, and writeBufferImpl().
boost::shared_future< BufferManager::BufferInfoMapType > fwMemory::BufferManager::getBufferInfos () const
Returns the Buffer info map.
Returns
Definition at line 545 of file BufferManager.cpp.
References getBufferInfosImpl().
BufferManager::sptr fwMemory::BufferManager::getDefault () static
Returns the current BufferManager instance.
Note
This method is thread-safe.
Definition at line 38 of file BufferManager.cpp.
Referenced by monitor::DumpEditor::changeStatus(), fwDcmtkIO::reader::ImageStorageReader::read(), memory::Plugin::start(), memory::SDumpPolicy::starting(), monitor::DumpEditor::starting(), monitor::action::MemoryInfo::updating(), and monitor::action::SDumpAll::updating().
std::shared_ptr< UpdatedSignalType > fwMemory::BufferManager::getUpdatedSignal () inline
Returns a boost::signal emitted when an action has been hooked.
Returns
Definition at line 232 of file BufferManager.hpp.
References SPTR.
boost::shared_future< std::shared_ptr< void > > fwMemory::BufferManager::lockBuffer (BufferManager::ConstBufferPtrType bufferPtr) virtual
Hook called when a BufferObject is locked.
Parameters
bufferPtr BufferObject's buffer pointer
Returns
false if the BufferManager supported the action
Definition at line 295 of file BufferManager.cpp.
References lockBufferImpl(), and SPTR.
boost::shared_future< bool > fwMemory::BufferManager::readBuffer (BufferManager::BufferType buffer, SizeType size, ::boost::filesystem::path & path)
Write/read a buffer.
The buffer is written/read in a raw format
Parameters
buffer Buffer to write/read
size Buffer's size
path file to write/read
Returns
true on success
Definition at line 469 of file BufferManager.cpp.
References readBufferImpl().
boost::shared_future< void > fwMemory::BufferManager::reallocateBuffer (BufferManager::BufferPtrType bufferPtr, SizeType newSize) virtual
Hook called when a reallocation is requested from a BufferObject.
Parameters
bufferPtr BufferObject's buffer pointer
newSize requested size for reallocation
Definition at line 171 of file BufferManager.cpp.
References reallocateBufferImpl().
boost::shared_future< void > fwMemory::BufferManager::registerBuffer (BufferManager::BufferPtrType bufferPtr) virtual
Hook called when a new BufferObject is created.
Parameters
bufferPtr BufferObject's buffer pointer.
Definition at line 63 of file BufferManager.cpp.
References registerBufferImpl().
boost::shared_future< bool > fwMemory::BufferManager::restoreBuffer (BufferManager::ConstBufferPtrType bufferPtr)
Dump/restore a buffer.
Keeps up to date buffer's information
Parameters
bufferPtr Buffer to dump/restore
Returns
true on success
Definition at line 386 of file BufferManager.cpp.
References restoreBufferImpl().
Referenced by reallocateBufferImpl(), restoreBufferImpl(), and setIStreamFactoryImpl().
bool fwMemory::BufferManager::restoreBuffer (BufferInfo & info, BufferManager::BufferPtrType bufferPtr, BufferManager::SizeType allocSize = 0) protected
Dump/restore a buffer.
Used by public dump/restoreBuffer methods
Definition at line 401 of file BufferManager.cpp.
References fwMemory::BufferInfo::loaded, fwCore::LogicStamp::modified(), OSLM_TRACE, and SPTR.
boost::shared_future< void > fwMemory::BufferManager::setBuffer (BufferManager::BufferPtrType bufferPtr, ::fwMemory::BufferManager::BufferType buffer, SizeType size, const ::fwMemory::BufferAllocationPolicy::sptr & policy) virtual
Hook called when a request is made to set BufferObject's buffer from an external buffer.
Parameters
bufferPtr BufferObject's buffer pointer
buffer new buffer
size requested size for allocation
policy BufferObject's allocation policy
Definition at line 132 of file BufferManager.cpp.
References setBufferImpl().
boost::shared_future< void > fwMemory::BufferManager::swapBuffer (BufferManager::BufferPtrType bufA, BufferManager::BufferPtrType bufB) virtual
Hook called when a request to swap two BufferObject contents is made.
Parameters
bufA First BufferObject's buffer
bufB Second BufferObject's buffer
Definition at line 236 of file BufferManager.cpp.
References swapBufferImpl().
boost::shared_future< bool > fwMemory::BufferManager::unlockBuffer (BufferManager::ConstBufferPtrType bufferPtr) virtual
Hook called when a BufferObject lock is released.
Parameters
bufferPtr BufferObject's buffer pointer
Returns
false if the BufferManager supported the action
Definition at line 323 of file BufferManager.cpp.
References unlockBufferImpl().
boost::shared_future< void > fwMemory::BufferManager::unregisterBuffer (BufferManager::BufferPtrType bufferPtr) virtual
Hook called when a BufferObject is destroyed.
Parameters
bufferPtr BufferObject's buffer pointer.
Definition at line 76 of file BufferManager.cpp.
References unregisterBufferImpl().
boost::shared_future< bool > fwMemory::BufferManager::writeBuffer (BufferManager::ConstBufferType buffer, SizeType size, ::boost::filesystem::path & path)
Write/read a buffer.
The buffer is written/read in a raw format
Parameters
buffer Buffer to write/read
size Buffer's size
path file to write/read
Returns
true on success
Definition at line 449 of file BufferManager.cpp.
References writeBufferImpl().
The documentation for this class was generated from the following files:
BufferManager.hpp
BufferManager.cpp