fw4spl: fwGdcmIO::helper::Fiducial Class Reference
fwGdcmIO::helper::Fiducial Class Reference
Fiducial helper.
#include <Fiducial.hpp>
Static Public Member Functions
static FWGDCMIO_API bool containsLandmarks (const std::shared_ptr< ::fwMedData::SeriesDB > &seriesDB)
Return true if the series contains at least one image containing landmarks.
static FWGDCMIO_API bool containsDistances (const std::shared_ptr< ::fwMedData::SeriesDB > &seriesDB)
Return true if the series contains at least one image containing distances.
static FWGDCMIO_API bool contains3DDistances (const std::shared_ptr< ::fwMedData::SeriesDB > &seriesDB)
Return true if the series contains at least one image containing 3D distances.
Detailed Description
Fiducial helper.
Definition at line 28 of file helper/Fiducial.hpp.
Member Function Documentation
bool fwGdcmIO::helper::Fiducial::contains3DDistances (const std::shared_ptr< ::fwMedData::SeriesDB > & seriesDB) static
Return true if the series contains at least one image containing 3D distances.
Parameters
[in] seriesDB SeriesDB where to look for 3D distances
Definition at line 79 of file helper/Fiducial.cpp.
References fwGdcmIO::helper::DicomDataTools::convertPointToFrameNumber(), fwMedData::SeriesDB::getContainer(), and fwDataTools::fieldHelper::Image::m_imageDistancesId.
Referenced by ioGdcm::SSeriesDBWriter::getIOPathType().
bool fwGdcmIO::helper::Fiducial::containsDistances (const std::shared_ptr< ::fwMedData::SeriesDB > & seriesDB) static
Return true if the series contains at least one image containing distances.
Parameters
[in] seriesDB SeriesDB where to look for distances
Definition at line 53 of file helper/Fiducial.cpp.
References fwMedData::SeriesDB::getContainer(), and fwDataTools::fieldHelper::Image::m_imageDistancesId.
Referenced by ioGdcm::SSeriesDBWriter::getIOPathType().
bool fwGdcmIO::helper::Fiducial::containsLandmarks (const std::shared_ptr< ::fwMedData::SeriesDB > & seriesDB) static
Return true if the series contains at least one image containing landmarks.
Parameters
[in] seriesDB SeriesDB where to look for landmarks
Definition at line 27 of file helper/Fiducial.cpp.
References fwMedData::SeriesDB::getContainer(), and fwDataTools::fieldHelper::Image::m_imageLandmarksId.
Referenced by ioGdcm::SSeriesDBWriter::getIOPathType().
The documentation for this class was generated from the following files:
helper/Fiducial.hpp
helper/Fiducial.cpp