fw4spl: uiVisu::PointEditor Class Reference
uiVisu::PointEditor Class Reference
PointEditor service allows to display point information.
#include <PointEditor.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((PointEditor)(::gui::editor::IEditor))
UIVISUQT_API PointEditor () throw ()
Constructor. Do nothing.
virtual UIVISUQT_API ~PointEditor () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
This method launches the IEditor::starting method.
virtual void stopping () throw (::fwTools::Failed)
This method launches the IEditor::stopping method.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Management of observations (overrides)
void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
virtual void info (std::ostream &_sstream)
Overrides.
Detailed Description
PointEditor service allows to display point information.
Date:
2010.
Definition at line 32 of file PointEditor.hpp.
Member Function Documentation
void uiVisu::PointEditor::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 103 of file PointEditor.cpp.
References fwGui::IGuiContainerSrv::initialize(), and SLM_TRACE_FUNC.
void uiVisu::PointEditor::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 117 of file PointEditor.cpp.
References updating().
void uiVisu::PointEditor::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 111 of file PointEditor.cpp.
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
PointEditor.hpp
PointEditor.cpp