fw4spl: ioVTK::ImageReaderService Class Reference
ioVTK::ImageReaderService Class Reference
Image reader service.Service reading a VTK Image using the fwVtkIO lib.
#include <ImageReaderService.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ImageReaderService)(::io::IReader))
virtual IOVTK_API void configureWithIHM ()
Configure the image path with a dialogBox.
Protected Member Functions
virtual IOVTK_API::io::IOPathType getIOPathType () const
This method must be implemented by concrete service readers that use path file system to read data.
virtual IOVTK_API void starting () throw (::fwTools::Failed)
Method called when the service is started, does nothing.
virtual IOVTK_API void stopping () throw (::fwTools::Failed)
Method called when the service is stopped, does nothing.
IOVTK_API void updating () throw (::fwTools::Failed)
Updating method execute the read process.
IOVTK_API void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : here, this method does nothing.
IOVTK_API void info (std::ostream &_sstream)
Info method gives some informations on service.
Detailed Description
Image reader service.
Service reading a VTK Image using the fwVtkIO lib.
Service registered details :
fwServicesRegisterMacro(::io::IReader , ::ioVTK::ImageReaderService , ::fwData::Image)
Definition at line 35 of file ImageReaderService.hpp.
Member Function Documentation
void ioVTK::ImageReaderService::configureWithIHM () [virtual]
Configure the image path with a dialogBox.
This method is used to find the file path using a file selector.
Implements io::IReader.
Definition at line 52 of file ImageReaderService.cpp.
References fwGui::dialog::LocationDialog::addFilter(), io::IReader::clearLocations(), fwGui::dialog::LocationDialog::saveDefaultLocation(), fwGui::dialog::LocationDialog::setDefaultLocation(), io::IReader::setFile(), fwGui::dialog::LocationDialog::setOption(), fwGui::dialog::LocationDialog::setTitle(), fwGui::dialog::LocationDialog::show(), and SLM_TRACE_FUNC.
io::IOPathType ioVTK::ImageReaderService::getIOPathType () const [protected, virtual]
This method must be implemented by concrete service readers that use path file system to read data.
This method returns supported path format (file, files or folder). A reader can support file and folder, or files and folder, but not file and files (because files include file concept).
Reimplemented from io::IReader.
Definition at line 45 of file ImageReaderService.cpp.
void ioVTK::ImageReaderService::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [protected]
React on modifications : here, this method does nothing.
Note:
This method is automatically called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 210 of file ImageReaderService.cpp.
References SLM_TRACE_FUNC.
void ioVTK::ImageReaderService::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method execute the read process.
This method is used to update the service. The image is read.
Implements fwServices::IService.
Definition at line 105 of file ImageReaderService.cpp.
References io::IReader::getFile(), io::IReader::hasLocationDefined(), OSLM_TRACE, fwGui::Cursor::setCursor(), fwGui::Cursor::setDefaultCursor(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
ImageReaderService.hpp
ImageReaderService.cpp