fw4spl: fwZip::IWriteArchive Class Reference
fwZip::IWriteArchive Class Reference abstract
This interface defines functions to write a file in an archive.
#include <IWriteArchive.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
virtual std::shared_ptr< std::ostream > createFile (const ::boost::filesystem::path &path)=0
Creates a new file entry in archive and returns output stream for this file.
virtual void putFile (const ::boost::filesystem::path &sourceFile, const ::boost::filesystem::path &path)=0
Writes source file in archive.
virtual bool createDir (const ::boost::filesystem::path &path)=0
Creates a folder in archive.
virtual const ::boost::filesystem::path getArchivePath () const =0
Returns archive path.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
This interface defines functions to write a file in an archive.
Definition at line 22 of file IWriteArchive.hpp.
Member Function Documentation
virtual bool fwZip::IWriteArchive::createDir (const ::boost::filesystem::path & path) pure virtual
Creates a folder in archive.
Parameters
path folder to create in archive.
Implemented in fwZip::WriteZipArchive, and fwZip::WriteDirArchive.
Referenced by leafClassname().
virtual std::shared_ptr< std::ostream > fwZip::IWriteArchive::createFile (const ::boost::filesystem::path & path) pure virtual
Creates a new file entry in archive and returns output stream for this file.
Parameters
path file in archive.
Returns
output stream of file entry in archive.
Implemented in fwZip::WriteZipArchive, and fwZip::WriteDirArchive.
Referenced by leafClassname().
virtual void fwZip::IWriteArchive::putFile (const ::boost::filesystem::path & sourceFile, const ::boost::filesystem::path & path) pure virtual
Writes source file in archive.
Parameters
sourceFile source file.
path file in archive.
Implemented in fwZip::WriteZipArchive, and fwZip::WriteDirArchive.
Referenced by leafClassname().
The documentation for this class was generated from the following file:
IWriteArchive.hpp