fw4spl: gui::view::DefaultView Class Reference
gui::view::DefaultView Class Reference
Defines the generic layout for application.
#include <DefaultView.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((DefaultView)(::gui::view::IView))
GUI_API DefaultView () throw ()
Constructor. Do nothing.
virtual GUI_API ~DefaultView () throw ()
Destructor. Do nothing.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual GUI_API void configuring () throw (::fwTools::Failed)
This method is used to configure the class parameters.
virtual GUI_API void starting () throw (::fwTools::Failed)
Register a view with defined id.
virtual GUI_API void stopping () throw (::fwTools::Failed)
This method remove the view in the frame.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
This method is used to update services on notification. Do nothing.
virtual GUI_API void updating () throw (::fwTools::Failed)
This method is used to update services. Do nothing.
virtual GUI_API void info (std::ostream &_sstream)
This method gives information about the class. Do nothing.
Detailed Description
Defines the generic layout for application.
Date:
2009-2010.
Definition at line 28 of file DefaultView.hpp.
Member Function Documentation
void gui::view::DefaultView::configuring () throw (::fwTools::Failed) [protected, virtual]
This method is used to configure the class parameters.
See also:
fwGui::IGuiContainerSrv::initialize()
Implements fwServices::IService.
Definition at line 33 of file DefaultView.cpp.
References fwGui::IGuiContainerSrv::initialize().
void gui::view::DefaultView::starting () throw (::fwTools::Failed) [protected, virtual]
Register a view with defined id.
See also:
fwGui::IGuiContainerSrv::create()
Implements fwServices::IService.
Definition at line 40 of file DefaultView.cpp.
References fwGui::IGuiContainerSrv::create(), and SLM_TRACE_FUNC.
void gui::view::DefaultView::stopping () throw (::fwTools::Failed) [protected, virtual]
This method remove the view in the frame.
See also:
fwGui::IGuiContainerSrv::destroy()
Implements fwServices::IService.
Definition at line 48 of file DefaultView.cpp.
References fwGui::IGuiContainerSrv::destroy(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
DefaultView.hpp
DefaultView.cpp