fw4spl: ioPacs::SSeriesPuller Class Reference
ioPacs::SSeriesPuller Class Reference
This service is used to pull series from a PACS.
#include <SSeriesPuller.hpp>
Public Types
typedef ::fwMedData::SeriesDB::ContainerType DicomSeriesContainerType
typedef std::vector< std::string > InstanceUIDContainerType
typedef std::map< std::string, unsigned int > InstanceCountMapType
typedef std::map< std::string, std::weak_ptr< ::fwMedData::DicomSeries > > DicomSeriesMapType
typedef ::fwCom::Slot< void(DicomSeriesContainerType)> ReadDicomSlotType
typedef ::fwCom::Slot< void(const std::string &)> DisplayMessageSlotType
typedef ::fwCom::Signal< void(std::string) > StartedProgressSignalType
Signal to start the progress (bar id)
typedef ::fwCom::Signal< void(std::string, float, std::string) > ProgressedSignalType
Signal to update the progress (bar id, percentage, message)
typedef ::fwCom::Signal< void(std::string) > StoppedProgressSignalType
Signal to stop the progress (bar id)
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Public Member Functions
virtual bool isA (const std::string &type) const override
IOPACS_API SSeriesPuller () noexcept
Constructor.
virtual IOPACS_API ~SSeriesPuller () noexcept
Destructor.
Public Member Functions inherited from fwServices::IController
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwServices::IController
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Attributes
static IOPACS_APIconst::fwCom::Slots::SlotKeyType s_READ_SLOT
static IOPACS_APIconst::fwCom::Slots::SlotKeyType s_DISPLAY_SLOT = "displayMessage"
static const ::fwCom::Signals::SignalKeyType s_PROGRESSED_SIG = "progressed"
Key in m_signals map of signal m_sigProgressed.
static const ::fwCom::Signals::SignalKeyType s_STARTED_PROGRESS_SIG = "startedProgress"
static const ::fwCom::Signals::SignalKeyType s_STOPPED_PROGRESS_SIG = "stoppedProgress"
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Member Functions
virtual IOPACS_API void configuring () override
Configuring method. This method is used to configure the service.
virtual IOPACS_API void starting () override
Override.
virtual IOPACS_API void stopping () override
Override.
IOPACS_API void updating () override
Override.
IOPACS_API void info (std::ostream &_sstream) override
Override.
IOPACS_API void pullSeries ()
Pull Series.
IOPACS_API void readLocalSeries (DicomSeriesContainerType selectedSeries)
Read local series.
IOPACS_API void displayErrorMessage (const std::string &message) const
Display an error message.
IOPACS_API void storeInstanceCallback (const std::string &seriesInstanceUID, unsigned int instanceNumber, const std::string &filePath)
Store instance callback.
Protected Member Functions inherited from fwServices::IController
FWSERVICES_API IController ()
IController constructor. Do nothing.
virtual FWSERVICES_API ~IController ()
IController destructor. Do nothing.
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual void swapping ()
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated objects signals, this method is used for obj/srv auto connection.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
ReadDicomSlotType::sptr m_slotReadLocalSeries
Slot to call readLocalSeries method.
DisplayMessageSlotType::sptr m_slotDisplayMessage
Slot to call displayErrorMessage method;.
::fwPacsIO::SeriesRetriever::ProgressCallbackSlotType::sptr m_slotStoreInstanceCallbackUsingMoveRequests
Slot to call storeInstanceCallback method using C-MOVE Requests.
::fwPacsIO::SeriesEnquirer::ProgressCallbackSlotType::sptr m_slotStoreInstanceCallbackUsingGetRequests
Slot to call storeInstanceCallback method using C-GET Requests.
ProgressedSignalType::sptr m_sigProgressed
Signal emitted when the bar is progressing.
StartedProgressSignalType::sptr m_sigStartedProgress
Signal emitted when the bar is starting.
StoppedProgressSignalType::sptr m_sigStoppedProgress
Signal emitted when the bar is stopping.
::fwPacsIO::SeriesEnquirer::sptr m_seriesEnquirer
Series enquirer.
::fwPacsIO::data::PacsConfiguration::csptr m_pacsConfiguration
Pacs Configuration object.
::fwIO::IReader::sptr m_dicomReader
Reader.
std::string m_dicomReaderSrvConfig
Reader Config.
std::string m_dicomReaderType
IOPACS Reader.
::fwMedData::SeriesDB::sptr m_tempSeriesDB
Temporary SeriesDB.
::fwMedData::SeriesDB::sptr m_destinationSeriesDB
Destination SeriesDB.
::fwThread::Worker::sptr m_pullSeriesWorker
Pull Worker.
InstanceUIDContainerType m_localSeries
Local Series.
bool m_isPulling
Is pulling is set to true when we are pulling series.
std::string m_progressbarId
Progress Bar ID.
long unsigned int m_seriesCount
Total number of downloaded series.
unsigned int m_seriesIndex
Index of the series being downloaded.
std::size_t m_instanceCount
Total number of instances that must be downloaded.
DicomSeriesMapType m_pullingDicomSeriesMap
Map of Dicom series being pulled.
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
This service is used to pull series from a PACS.
Signals
progressed(std::string) : Signal to start the progress (bar id).
startedProgress(std::string, float, std::string) : Signal to update the progress (bar id, percentage, message).
stoppedProgress(std::string) : Signal to stop the progress (bar id).
XML Configuration
  <service type="::namespace::classname">
      <in key="pacsConfig" uid="..." />
      <in key="selectedSeries" uid="..." />
      <inout key="seriesDB" uid="..." />
      <config dicomReader="::ioGdcm::SSeriesDBReader" dicomReaderConfig="config" />
 </service>
Input
pacsConfig [fwPacsIO::data::PacsConfiguration]: PACS configuration data.
selectedSeries [fwData::Vector]: List of DICOM series to pull from the PACS..
In-Out
seriesDB [fwMedData::SeriesDB]: SeriesDB where to put the retrieved dicom series.
Configuration
dicomReader Reader type to use.
dicomReaderConfig Optional configuration for the DICOM Reader.
Definition at line 65 of file ioPacs/include/ioPacs/SSeriesPuller.hpp.
Member Function Documentation
IOPACS_API void ioPacs::SSeriesPuller::displayErrorMessage (const std::string & message) const protected
Display an error message.
Parameters
[in] message Error message to display
Referenced by SSeriesPuller(), and storeInstanceCallback().
void ioPacs::SSeriesPuller::readLocalSeries (DicomSeriesContainerType selectedSeries) protected
Read local series.
Parameters
[in] selectedSeries Dicom Series that must be read
Definition at line 318 of file ioPacs/src/ioPacs/SSeriesPuller.cpp.
References fwTools::System::getTemporaryFolder(), m_destinationSeriesDB, m_dicomReader, m_localSeries, m_tempSeriesDB, fwMedDataTools::helper::SeriesDB::merge(), fwMedDataTools::helper::SeriesDB::notify(), and fwPacsIO::helper::Series::toSeriesInstanceUIDContainer().
Referenced by SSeriesPuller().
void ioPacs::SSeriesPuller::storeInstanceCallback (const std::string & seriesInstanceUID, unsigned int instanceNumber, const std::string & filePath) protected
Store instance callback.
Parameters
[in] seriesInstanceUID Series instance UID
[in] instanceNumber Instance number
[in] filePath File path
Definition at line 358 of file ioPacs/src/ioPacs/SSeriesPuller.cpp.
References fwGui::dialog::MessageDialog::addButton(), displayErrorMessage(), m_instanceCount, m_progressbarId, m_pullingDicomSeriesMap, m_sigProgressed, fwGui::dialog::MessageDialog::setIcon(), fwGui::dialog::MessageDialog::setMessage(), fwGui::dialog::MessageDialog::setTitle(), fwGui::dialog::MessageDialog::show(), and SLM_WARN.
Referenced by SSeriesPuller().
The documentation for this class was generated from the following files:
ioPacs/include/ioPacs/SSeriesPuller.hpp
ioPacs/src/ioPacs/SSeriesPuller.cpp