fw4spl: uiReconstruction::OrganMaterialEditor Class Reference
uiReconstruction::OrganMaterialEditor Class Reference
OrganMaterialEditor service.
#include <OrganMaterialEditor.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((OrganMaterialEditor)(::gui::editor::IEditor))
UIRECONSTRUCTIONQT_API OrganMaterialEditor () throw ()
Constructor. Do nothing.
virtual UIRECONSTRUCTIONQT_API ~OrganMaterialEditor () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Slots
void onOpacitySlider (int value)
void onColorButton ()
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
This method launches the IEditor::starting method.
virtual void stopping () throw (::fwTools::Failed)
This method launches the IEditor::stopping method.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Management of observations (overrides)
virtual void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual void configuring () throw (fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
virtual void info (std::ostream &_sstream)
Overrides.
void refreshMaterial ()
void materialNotification ()
Detailed Description
OrganMaterialEditor service.
Date:
2010.
Definition at line 31 of file OrganMaterialEditor.hpp.
Member Function Documentation
void uiReconstruction::OrganMaterialEditor::configuring () throw (fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 113 of file OrganMaterialEditor.cpp.
References fwGui::IGuiContainerSrv::initialize(), and SLM_TRACE_FUNC.
void uiReconstruction::OrganMaterialEditor::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 128 of file OrganMaterialEditor.cpp.
References updating().
void uiReconstruction::OrganMaterialEditor::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 121 of file OrganMaterialEditor.cpp.
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
OrganMaterialEditor.hpp
OrganMaterialEditor.cpp