fw4spl: ioAtoms::SReader Class Reference
ioAtoms::SReader Class Reference
Atoms reader. Service to load data from Atoms format.
#include <SReader.hpp>
Public Types
typedef std::map< std::string,
std::string > FileExtension2NameType
Maps file extension to format name.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SReader)(::io::IReader))
SReader ()
Does nothing.
virtual ~SReader () throw ()
Does nothing.
IOATOMS_API void configureWithIHM ()
Propose to choose a medical data file (*.json,*.jsonz,*.xml or *.xmlz)
Static Public Attributes
static const FileExtension2NameType s_EXTENSIONS
Managed file extensions.
Protected Member Functions
IOATOMS_API void starting () throw (::fwTools::Failed)
Does nothing.
IOATOMS_API void stopping () throw (::fwTools::Failed)
Does nothing.
IOATOMS_API void configuring () throw (::fwTools::Failed)
Configures the reader.
IOATOMS_API void updating () throw (::fwTools::Failed)
Tests file extension, applies the good atom reader, and converts atom in fwData::Composite.
IOATOMS_API::io::IOPathType getIOPathType () const
Returns managed path type, here service manages only single file.
Detailed Description
Atoms reader. Service to load data from Atoms format.
Date:
2013
Definition at line 30 of file SReader.hpp.
Member Function Documentation
void ioAtoms::SReader::configuring () throw (::fwTools::Failed) [protected, virtual]
Configures the reader.
     <config>
        <inject>ReadData</inject>
        <uuidPolicy>Strict|Change|Reuse</uuidPolicy>
        <patcher context="..." version="..." />
        <archive backend="json">
            <extension>.j</extension>
        </archive>
        <archive backend="jsonz">
            <extension>.vpz</extension>
        </archive>
        <archive backend="hdf5">
            <extension>.f4s</extension>
            <extension>.mw</extension>
        </archive>
        <extensions>
            <extension label="XML">.xml</extension>
            <extension label="Zipped XML>.xmlz</extension>
            <extension>.f4s</extension>
            <extension>.j</extension>
            <extension label="Medical workspace">.mw</extension>
            <extension>.vpz</extension>
        </extensions>
     </config>
archive : defines custom file extensions. The file to be read with an extension given in 'archive' tag will be processed with the given backend in archive tag (the 'backend' attribute is mandatory). Extensions must begin with '.'. Available 'backend' values are json, xml, jsonz, xmlz, and hdf5.
extensions : defines available extensions displayed in dialog to read file. If the 'extensions' is empty or not specified, all the extensions (.json, .xml, .jsonz, .xmlz, .hdf5 extensions and custom extensions) are available. The attribute label (not mandatory) allows to display a label in front of extension when the file dialog is shown.
See also:
io::IReader
Exceptions:
fwTools::Failed
Reimplemented from io::IReader.
Definition at line 87 of file SReader.cpp.
References fwServices::IService::m_configuration, s_EXTENSIONS, SLM_ASSERT, and SLM_TRACE_FUNC.
void ioAtoms::SReader::updating () throw (::fwTools::Failed) [protected, virtual]
Tests file extension, applies the good atom reader, and converts atom in fwData::Composite.
Note:
Before reading, set dump policy to 'barrier dump' if policy is 'never dump', then reset old policy.
patch atom
Implements fwServices::IService.
Definition at line 248 of file SReader.cpp.
References fwComEd::helper::Composite::add(), io::IReader::getFile(), io::IReader::hasLocationDefined(), fwComEd::helper::Composite::notify(), OSLM_ASSERT, OSLM_ERROR, fwGui::Cursor::setCursor(), fwGui::dialog::MessageDialog::showMessageDialog(), and SLM_ASSERT.
Member Data Documentation
const SReader::FileExtension2NameType ioAtoms::SReader::s_EXTENSIONS [static]
Initial value:
 ::boost::assign::map_list_of(".xml", "XML")
        (".xmlz", "Zipped XML")
        (".json", "JSON")
        (".jsonz", "Zipped JSON")
        (".hdf5", "HDF5")
Managed file extensions.
Definition at line 50 of file SReader.hpp.
Referenced by ioAtoms::SWriter::configuring(), configuring(), SReader(), and ioAtoms::SWriter::SWriter().
The documentation for this class was generated from the following files:
SReader.hpp
SReader.cpp