fw4spl: uiGeneric::action::SShowAbout Class Reference
uiGeneric::action::SShowAbout Class Reference
This action show the about frame.
#include <SShowAbout.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SShowAbout)(::fwGui::IActionSrv))
Constructor/Destructor
UIGENERICQT_API SShowAbout () throw ()
virtual UIGENERICQT_API ~SShowAbout () throw ()
Protected Slots
void onUrlClicked (const QUrl &url)
Triggered when an URL is clicked in the about frame.
Protected Member Functions
void configuring () throw (::fwTools::Failed)
Configuring method.
void starting () throw (::fwTools::Failed)
Starts action.
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Does nothing.
void updating () throw (::fwTools::Failed)
Shows the frame.
void stopping () throw (::fwTools::Failed)
Stops action.
void info (std::ostream &_sstream)
Prints service info.
Detailed Description
This action show the about frame.
Definition at line 30 of file SShowAbout.hpp.
Member Function Documentation
void uiGeneric::action::SShowAbout::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method.
XML configuration sample:
     <service impl="::uiGeneric::action::SShowAbout" type="::fwGui::IActionSrv">
         <filename id=".../aboutFile.html"/>
         <title>title</title>
         <size width="200" height="200" />
     </service>
This method is used to configure the service.
Implements fwServices::IService.
Definition at line 58 of file SShowAbout.cpp.
References fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, OSLM_TRACE, SLM_TRACE, SLM_WARN_IF, and fwServices::IService::SPTR().
void uiGeneric::action::SShowAbout::onUrlClicked (const QUrl & url) [protected, slot]
Triggered when an URL is clicked in the about frame.
Parameters:
url clicked URL
Definition at line 162 of file SShowAbout.cpp.
Referenced by updating().
The documentation for this class was generated from the following files:
SShowAbout.hpp
SShowAbout.cpp