fw4spl: uiMeasurement::action::ShowLandmark Class Reference
uiMeasurement::action::ShowLandmark Class Reference
This action allows to show/hide image landmarks.
#include <ShowLandmark.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ShowLandmark)(::fwGui::IActionSrv))
Protected Member Functions
void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
void starting () throw (::fwTools::Failed)
Initialize the service activity.
void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
UIMEASUREMENT_API void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
UIMEASUREMENT_API void info (std::ostream &_sstream)
Write information in a stream.
Protected Attributes
::fwData::Image::wptr m_observedImage
Detailed Description
This action allows to show/hide image landmarks.
Date:
2010.
Definition at line 25 of file ShowLandmark.hpp.
Member Function Documentation
void uiMeasurement::action::ShowLandmark::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 112 of file ShowLandmark.cpp.
References fwGui::IActionSrv::initialize().
void uiMeasurement::action::ShowLandmark::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 52 of file ShowLandmark.cpp.
void uiMeasurement::action::ShowLandmark::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 101 of file ShowLandmark.cpp.
References fwComEd::ImageMsg::LANDMARK.
void uiMeasurement::action::ShowLandmark::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 119 of file ShowLandmark.cpp.
References fwGui::IActionSrv::actionServiceStarting().
void uiMeasurement::action::ShowLandmark::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 126 of file ShowLandmark.cpp.
References fwGui::IActionSrv::actionServiceStopping().
void uiMeasurement::action::ShowLandmark::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 89 of file ShowLandmark.cpp.
References fwGui::IActionSrv::setIsActive(), and SLM_TRACE_FUNC.
void uiMeasurement::action::ShowLandmark::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 59 of file ShowLandmark.cpp.
References fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwComEd::ImageMsg::LANDMARK, fwComEd::Dictionary::m_imageLandmarksId, fwServices::IEditionService::notify(), fwGui::IActionSrv::setIsActive(), SLM_TRACE_FUNC, and fwData::GenericField< T >::value().
The documentation for this class was generated from the following files:
ShowLandmark.hpp
ShowLandmark.cpp