fw4spl: fwStructuralPatch::fwData::Acquisition::V1ToFwMedDataImageSeriesV1 Class Reference
fwStructuralPatch::fwData::Acquisition::V1ToFwMedDataImageSeriesV1 Class Reference
Transforms an acquisition in version '1' to an image series in version '1'.
#include <V1ToFwMedDataImageSeriesV1.hpp>
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((V1ToFwMedDataImageSeriesV1)(::fwStructuralPatch::fwData::Acquisition::V1ToFwMedDataImageSeriesV1),(()), new V1ToFwMedDataImageSeriesV1)
FWSTRUCTURALPATCH_API V1ToFwMedDataImageSeriesV1 ()
Constructor.
FWSTRUCTURALPATCH_API ~V1ToFwMedDataImageSeriesV1 ()
Destructor.
FWSTRUCTURALPATCH_API V1ToFwMedDataImageSeriesV1 (const V1ToFwMedDataImageSeriesV1 &cpy)
Copy constructor.
virtual FWSTRUCTURALPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies patch.
Detailed Description
Transforms an acquisition in version '1' to an image series in version '1'.
Definition at line 23 of file V1ToFwMedDataImageSeriesV1.hpp.
Member Function Documentation
void fwStructuralPatch::fwData::Acquisition::V1ToFwMedDataImageSeriesV1::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) [virtual]
Applies patch.
Removes attributes from acquisition, changes 'uid' attribute to 'instance_uid', adds attributes 'modality', 'patient', 'equipment', 'performing_physicians_name', 'time' and 'date'.
Implements fwAtomsPatch::IPatch.
Definition at line 55 of file V1ToFwMedDataImageSeriesV1.cpp.
References fwAtomsPatch::helper::Object::addAttribute(), fwAtomsPatch::StructuralCreatorDB::getDefault(), fwAtoms::String::New(), fwAtomsPatch::helper::Object::removeAttribute(), fwAtomsPatch::helper::Object::renameAttribute(), and fwAtomsPatch::IStructuralPatch::updateVersion().
The documentation for this class was generated from the following files:
V1ToFwMedDataImageSeriesV1.hpp
V1ToFwMedDataImageSeriesV1.cpp