fw4spl: fwDataTools::helper::ArrayGetter Class Reference
fwDataTools::helper::ArrayGetter Class Reference
Helper to manage array buffer. Lock the buffer before to modify it.
#include <ArrayGetter.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWDATATOOLS_API ArrayGetter (::fwData::Array::csptr array)
virtual FWDATATOOLS_API const void * getItem (const ::fwData::Array::IndexType &id, const size_t component=0) const
Getter for a buffer item. pointer to the requested item in the buffer.
template<typename T >
const T * getItem (const ::fwData::Array::IndexType &id, const size_t component=0) const
Typed version of getItem.
virtual FWDATATOOLS_API void getItem (const ::fwData::Array::IndexType &id, void *value) const
Copies the data into the buffer pointed by
virtual FWDATATOOLS_API void getItem (const ::fwData::Array::IndexType &id, const size_t component, void *value) const
virtual FWDATATOOLS_API const void * getBuffer () const
Getter for the array buffer.
virtual FWDATATOOLS_API const char * begin () const
Returns the begining/end of the buffer interpreted as a char buffer.
virtual FWDATATOOLS_API const char * end () const
template<typename T >
const T * begin () const
Returns the begining/end of the buffer, casted to T.
template<typename T >
const T * end () const
FWDATATOOLS_API const char * getBufferPtr (const ::fwData::Array::IndexType &id, size_t component, size_t sizeOfType) const
Get a pointer to the value described by given parameters.
FWDATATOOLS_API::fwMemory::BufferObject::Lock getLock () const
Returns a copy of current lock on array.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Protected Attributes
::fwData::Array::csptr m_array
::fwMemory::BufferObject::Lock m_lock
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Helper to manage array buffer. Lock the buffer before to modify it.
Definition at line 28 of file ArrayGetter.hpp.
Member Function Documentation
const void * fwDataTools::helper::ArrayGetter::getBuffer () const virtual
Getter for the array buffer.
Returns
Array's buffer, if exists, else NULL
Definition at line 30 of file ArrayGetter.cpp.
References fwMemory::BufferObject::LockBase< T >::getBuffer().
const char * fwDataTools::helper::ArrayGetter::getBufferPtr (const ::fwData::Array::IndexType & id, size_t component, size_t sizeOfType) const
Get a pointer to the value described by given parameters.
Parameters
id Item id
component Item component id
sizeOfType size of a component
Returns
buffer item pointer
Definition at line 51 of file ArrayGetter.cpp.
References fwDataTools::helper::Array::getBuffer().
const void * fwDataTools::helper::ArrayGetter::getItem (const ::fwData::Array::IndexType & id, const size_t component = 0) const virtual
Getter for a buffer item. pointer to the requested item in the buffer.
Parameters
id Item id
component Component id
Returns
Pointer to the requested item in the buffer
Definition at line 61 of file ArrayGetter.cpp.
References fwDataTools::helper::Array::getBufferPtr().
Referenced by getItem().
template<typename T > const T * fwDataTools::helper::ArrayGetter::getItem (const ::fwData::Array::IndexType & id, const size_t component = 0) const
Typed version of getItem.
Template Parameters
T Type in which the pointer will be returned
Parameters
id Item id
component Component id
Returns
Array buffer pointer casted to T
Definition at line 122 of file ArrayGetter.hpp.
void fwDataTools::helper::ArrayGetter::getItem (const ::fwData::Array::IndexType & id, void * value) const virtual
Copies the data into the buffer pointed by
Parameters
id Item id
[out] value Buffer to write into
Definition at line 70 of file ArrayGetter.cpp.
References fwDataTools::helper::Array::getBufferPtr(), and getItem().
The documentation for this class was generated from the following files:
ArrayGetter.hpp
ArrayGetter.cpp