fw4spl: uiImage::ShowScanEditor Class Reference
uiImage::ShowScanEditor Class Reference
This editor service represent a button to show/hide scan in a generic scene.
#include <ShowScanEditor.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ShowScanEditor)(::gui::editor::IEditor))
UIIMAGEQT_API ShowScanEditor () throw ()
Constructor. Do nothing.
virtual UIIMAGEQT_API ~ShowScanEditor () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Slots
void onChangeScanMode ()
This method is called when the scan button is clicked.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Install the layout.
virtual void stopping () throw (::fwTools::Failed)
Destroy the layout.
virtual void receiving (::boost::shared_ptr< const fwServices::ObjectMsg > _msg) throw (::fwTools::Failed)
Do nothing.
virtual void updating () throw (::fwTools::Failed)
Do nothing.
virtual void swapping () throw (::fwTools::Failed)
Do nothing.
virtual void configuring () throw (fwTools::Failed)
Configure the editor.
virtual void info (std::ostream &_sstream)
Overrides.
Detailed Description
This editor service represent a button to show/hide scan in a generic scene.
Date:
2010.
Definition at line 30 of file ShowScanEditor.hpp.
Member Function Documentation
void uiImage::ShowScanEditor::configuring () throw (fwTools::Failed) [protected, virtual]
Configure the editor.
Example of configuration
     <service uid="showScanNegato3DEditor" type="::gui::editor::IEditor" impl="::uiImage::ShowScanEditor" autoConnect="no">
         <negatoAdaptor uid="myNegatoMPR" />
     </service>
myNegatoMPR is the uid of the visuVTKAdaptor::NegatoMPR service where the scan will be show/hide.
Implements fwServices::IService.
Definition at line 102 of file ShowScanEditor.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, SLM_ASSERT, and SLM_TRACE_FUNC.
void uiImage::ShowScanEditor::onChangeScanMode () [protected, slot]
This method is called when the scan button is clicked.
This service notifies the modification.
Definition at line 138 of file ShowScanEditor.cpp.
References fwTools::fwID::exist(), fwComEd::Dictionary::m_relatedServiceId, fwServices::IEditionService::notify(), OSLM_TRACE, and SLM_ASSERT.
Referenced by starting(), and stopping().
The documentation for this class was generated from the following files:
ShowScanEditor.hpp
ShowScanEditor.cpp