fw4spl: fwGdcmIO::helper::DictionarySegment Class Reference
fwGdcmIO::helper::DictionarySegment Class Reference
This class implement a segmentation dictionary. It allows to get a complete identification of a segmentation from the organ name of a fwData::Reconstruction.
#include <DictionarySegment.hpp>
Static Public Member Functions
static FWGDCMIO_APIconst::fwGdcmIO::container::DicomCodedAttribute * guessAnatRegionFromLabel (const std::string &label)
Get anatomic region sequence from label of an organ.
static FWGDCMIO_APIconst::fwGdcmIO::container::DicomCodedAttribute * guessPropCategoryFromLabel (const std::string &label)
Get segmented property category code sequence from label of an organ.
static FWGDCMIO_APIconst::fwGdcmIO::container::DicomCodedAttribute * guessPropTypeFromLabel (const std::string &label)
Get segmented property type code sequence from label of an organ.
Detailed Description
This class implement a segmentation dictionary. It allows to get a complete identification of a segmentation from the organ name of a fwData::Reconstruction.
Note
Currently, this identification has to be done with tools of this class.
Definition at line 23 of file DictionarySegment.hpp.
Member Function Documentation
const ::fwGdcmIO::container::DicomCodedAttribute * fwGdcmIO::helper::DictionarySegment::guessAnatRegionFromLabel (const std::string & label) static
Get anatomic region sequence from label of an organ.
See also
Tag (0x0008,0x2218)
Note
Returned null pointer means organ name is unknown.
Parameters
[in] label Label from witch the anatomic region is guessed.
Definition at line 330 of file DictionarySegment.cpp.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceSegmentationModule().
const ::fwGdcmIO::container::DicomCodedAttribute * fwGdcmIO::helper::DictionarySegment::guessPropCategoryFromLabel (const std::string & label) static
Get segmented property category code sequence from label of an organ.
See also
Tag (0x0062,0x0003)
Note
Returned null pointer means organ name is unknown.
Parameters
[in] label Label from witch the property category is guessed.
Definition at line 348 of file DictionarySegment.cpp.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceSegmentationModule().
const ::fwGdcmIO::container::DicomCodedAttribute * fwGdcmIO::helper::DictionarySegment::guessPropTypeFromLabel (const std::string & label) static
Get segmented property type code sequence from label of an organ.
See also
Tag (0x0062,0x000F)
Note
Returned null pointer means organ name is unknown.
Parameters
[in] label Label from witch the property type is guessed.
Definition at line 367 of file DictionarySegment.cpp.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceSegmentationModule().
The documentation for this class was generated from the following files:
DictionarySegment.hpp
DictionarySegment.cpp