fw4spl: fwComEd::helper::Mesh Class Reference
fwComEd::helper::Mesh Class Reference
Helper to manage Mesh. Lock the mesh buffer before to modify it.
#include <Mesh.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Mesh))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Mesh,(((::fwData::Mesh::sptr))))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Mesh)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWCOMED_API Mesh (::fwData::Mesh::sptr mesh)
FWCOMED_API void updateLock ()
Updates locks on all internal data Array of Mesh.
FWCOMED_API::fwData::Mesh::Id insertNextPoint (const ::fwData::Mesh::PointValueType p[3]) throw (::fwData::Exception)
Insert a point into the mesh. Reallocates the point array if needed.
FWCOMED_API::fwData::Mesh::Id insertNextPoint (::fwData::Mesh::PointValueType x,::fwData::Mesh::PointValueType y,::fwData::Mesh::PointValueType z) throw (::fwData::Exception)
Insert a point into the mesh.
FWCOMED_API void setPoint (::fwData::Mesh::Id id, const ::fwData::Mesh::PointValueType p[3])
Set a point coordinates. The mesh must be allocated before calling this method.
FWCOMED_API void setPoint (::fwData::Mesh::Id id,::fwData::Mesh::PointValueType x,::fwData::Mesh::PointValueType y,::fwData::Mesh::PointValueType z)
Set a point coordinates.
FWCOMED_API void setPointColor (::fwData::Mesh::Id id, const ::fwData::Mesh::ColorValueType c[4])
Set a point color.
FWCOMED_API void setCellColor (::fwData::Mesh::Id id, const ::fwData::Mesh::ColorValueType c[4])
Set a cell color.
FWCOMED_API void setPointNormal (::fwData::Mesh::Id id, const ::fwData::Mesh::NormalValueType n[3])
Set a point normal.
FWCOMED_API void setCellNormal (::fwData::Mesh::Id id, const ::fwData::Mesh::NormalValueType n[3])
Set a cell normal.
FWCOMED_API void setPointTexCoord (::fwData::Mesh::Id id, const ::fwData::Mesh::TexCoordValueType t[2])
Set a point texCoord.
FWCOMED_API void setCellTexCoord (::fwData::Mesh::Id id, const ::fwData::Mesh::TexCoordValueType t[2])
Set a cell texCoord.
FWCOMED_API::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellTypesEnum type, const ::fwData::Mesh::CellValueType *cell, size_t nb) throw (::fwData::Exception)
Insert a cell into the mesh.
FWCOMED_API::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellValueType p) throw (::fwData::Exception)
Insert a cell into the mesh.
FWCOMED_API::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellValueType p1,::fwData::Mesh::CellValueType p2) throw (::fwData::Exception)
Insert a cell into the mesh.
FWCOMED_API::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellValueType p1,::fwData::Mesh::CellValueType p2,::fwData::Mesh::CellValueType p3) throw (::fwData::Exception)
Insert a cell into the mesh.
FWCOMED_API::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellValueType p1,::fwData::Mesh::CellValueType p2,::fwData::Mesh::CellValueType p3,::fwData::Mesh::CellValueType p4) throw (::fwData::Exception)
Insert a cell into the mesh.
template<typename T >
::fwData::Mesh::Id insertNextCell (::fwData::Mesh::CellTypesEnum type, const T &pointsBegin, const T &pointsEnd) throw (::fwData::Exception)
Insert a cell into the mesh.
FWCOMED_API::fwData::Mesh::PointsMultiArrayType getPoints () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellTypesMultiArrayType getCellTypes () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellDataMultiArrayType getCellData () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellDataOffsetsMultiArrayType getCellDataOffsets () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::PointColorsMultiArrayType getPointColors () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellColorsMultiArrayType getCellColors () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::PointNormalsMultiArrayType getPointNormals () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellNormalsMultiArrayType getCellNormals () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::PointTexCoordsMultiArrayType getPointTexCoords () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::CellTexCoordsMultiArrayType getCellTexCoords () const
Returns the internal corresponding array as a boost::multi_array_ref.
FWCOMED_API::fwData::Mesh::csptr getMesh () const
Returns the internal fwData::Mesh.
FWCOMED_API bool isClosed ()
Return true if the mesh is closed. The result is computed for each call.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Protected Attributes
::fwData::Mesh::sptr m_mesh
::fwComEd::helper::Array::sptr m_helperPoints
::fwComEd::helper::Array::sptr m_helperCellTypes
::fwComEd::helper::Array::sptr m_helperCellData
::fwComEd::helper::Array::sptr m_helperCellDataOffsets
::fwComEd::helper::Array::sptr m_helperPointColors
::fwComEd::helper::Array::sptr m_helperCellColors
::fwComEd::helper::Array::sptr m_helperPointNormals
::fwComEd::helper::Array::sptr m_helperCellNormals
::fwComEd::helper::Array::sptr m_helperPointTexCoords
::fwComEd::helper::Array::sptr m_helperCellTexCoords
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Helper to manage Mesh. Lock the mesh buffer before to modify it.
Date
2012
Definition at line 30 of file SrcLib/core/fwComEd/include/fwComEd/helper/Mesh.hpp.
Member Function Documentation
fwComEd::helper::Mesh::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Mesh, (((::fwData::Mesh::sptr))))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Mesh)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Mesh)).
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellTypesEnum type, const ::fwData::Mesh::CellValueType * cell, size_t nb) throw (::fwData::Exception)
Insert a cell into the mesh.
Reallocates the mesh concerned arrays if needed.
Returns
The id of the new cell
Exceptions
fwData::Exception
Definition at line 168 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
References SLM_ASSERT.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellValueType p) throw (::fwData::Exception)
Insert a cell into the mesh.
See also
insertNextCell
Definition at line 232 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellValueType p1, ::fwData::Mesh::CellValueType p2) throw (::fwData::Exception)
Insert a cell into the mesh.
See also
insertNextCell
Definition at line 240 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellValueType p1, ::fwData::Mesh::CellValueType p2, ::fwData::Mesh::CellValueType p3) throw (::fwData::Exception)
Insert a cell into the mesh.
See also
insertNextCell
Definition at line 249 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellValueType p1, ::fwData::Mesh::CellValueType p2, ::fwData::Mesh::CellValueType p3, ::fwData::Mesh::CellValueType p4) throw (::fwData::Exception)
Insert a cell into the mesh.
See also
insertNextCell
Definition at line 259 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
template<typename T > ::fwData::Mesh::Id fwComEd::helper::Mesh::insertNextCell (::fwData::Mesh::CellTypesEnum type, const T & pointsBegin, const T & pointsEnd) throw (::fwData::Exception)
Insert a cell into the mesh.
See also
insertNextCell
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextPoint (const ::fwData::Mesh::PointValueType p[3]) throw (::fwData::Exception)
Insert a point into the mesh. Reallocates the point array if needed.
Parameters
p point coordinates
Returns
The id of the new point
Exceptions
fwData::Exception
Definition at line 82 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
fwData::Mesh::Id fwComEd::helper::Mesh::insertNextPoint (::fwData::Mesh::PointValueType x, ::fwData::Mesh::PointValueType y, ::fwData::Mesh::PointValueType z) throw (::fwData::Exception)
Insert a point into the mesh.
See also
insertNextPoint
Definition at line 98 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
void fwComEd::helper::Mesh::setCellColor (::fwData::Mesh::Id id, const ::fwData::Mesh::ColorValueType c[4])
Set a cell color.
Depending on the type of allocated cell-colors array (RGB or RGBA), 3 or 4 points will be read from p. The color array must be allocated before calling this method.
Parameters
id cell index
c color
Exceptions
fwData::Exception
Definition at line 133 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwDataTools::Mesh::colorizeMeshCells(), fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
void fwComEd::helper::Mesh::setCellNormal (::fwData::Mesh::Id id, const ::fwData::Mesh::NormalValueType n[3])
Set a cell normal.
The normal array must be allocated before calling this method.
Parameters
id cell index
n normal
Exceptions
fwData::Exception
Definition at line 147 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
void fwComEd::helper::Mesh::setCellTexCoord (::fwData::Mesh::Id id, const ::fwData::Mesh::TexCoordValueType t[2])
Set a cell texCoord.
The texCoord array must be allocated before calling this method.
Parameters
id cell index
t texCoord
Exceptions
fwData::Exception
Definition at line 161 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
void fwComEd::helper::Mesh::setPoint (::fwData::Mesh::Id id, const ::fwData::Mesh::PointValueType p[3])
Set a point coordinates. The mesh must be allocated before calling this method.
Parameters
id point index
p point coordinates
Exceptions
fwData::Exception
Definition at line 108 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
void fwComEd::helper::Mesh::setPoint (::fwData::Mesh::Id id, ::fwData::Mesh::PointValueType x, ::fwData::Mesh::PointValueType y, ::fwData::Mesh::PointValueType z)
Set a point coordinates.
See also
setPoint
Definition at line 115 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
void fwComEd::helper::Mesh::setPointColor (::fwData::Mesh::Id id, const ::fwData::Mesh::ColorValueType c[4])
Set a point color.
Depending on the type of allocated point-colors array (RGB or RGBA), 3 or 4 points will be read from p. The color array must be allocated before calling this method.
Parameters
id point index
c color
Exceptions
fwData::Exception
Definition at line 126 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwDataTools::Mesh::colorizeMeshPoints(), fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
void fwComEd::helper::Mesh::setPointNormal (::fwData::Mesh::Id id, const ::fwData::Mesh::NormalValueType n[3])
Set a point normal.
The normal array must be allocated before calling this method.
Parameters
id point index
n normal
Exceptions
fwData::Exception
Definition at line 140 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
void fwComEd::helper::Mesh::setPointTexCoord (::fwData::Mesh::Id id, const ::fwData::Mesh::TexCoordValueType t[2])
Set a point texCoord.
The texCoord array must be allocated before calling this method.
Parameters
id point index
t texCoord
Exceptions
fwData::Exception
Definition at line 154 of file SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp.
Referenced by fwVtkIO::helper::Mesh::fromVTKGrid(), and fwVtkIO::helper::Mesh::fromVTKMesh().
The documentation for this class was generated from the following files:
SrcLib/core/fwComEd/include/fwComEd/helper/Mesh.hpp
SrcLib/core/fwComEd/src/fwComEd/helper/Mesh.cpp