fw4spl: uiMedData::editor::SOrganTransformation Class Reference
uiMedData::editor::SOrganTransformation Class Reference
Display the organs list and allow an interactive selection to set the corresponding meshes in a composite.
#include <SOrganTransformation.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SOrganTransformation)(::gui::editor::IEditor))
UIMEDDATAQT_API SOrganTransformation () throw ()
constructor
virtual UIMEDDATAQT_API ~SOrganTransformation () throw ()
destructor
Protected Member Functions
virtual UIMEDDATAQT_API void configuring () throw (::fwTools::Failed)
configures the service
virtual UIMEDDATAQT_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual UIMEDDATAQT_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual UIMEDDATAQT_API void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual UIMEDDATAQT_API void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual UIMEDDATAQT_API void receiving (::fwServices::ObjectMsg::csptr msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
virtual UIMEDDATAQT_API void info (::std::ostream &stream)
Detailed Description
Display the organs list and allow an interactive selection to set the corresponding meshes in a composite.
Definition at line 37 of file SOrganTransformation.hpp.
Member Function Documentation
void uiMedData::editor::SOrganTransformation::configuring () throw (::fwTools::Failed) [protected, virtual]
configures the service
       <service impl="::uiMedData::editor::SOrganTransformation" type="::gui::editor::IEditor" autoConnect="yes">
           <TMSUid>MESHDB_UID</TMSUid>
       </service>
TMSUid = composite uid
Implements fwServices::IService.
Definition at line 65 of file SOrganTransformation.cpp.
References fwGui::IGuiContainerSrv::initialize(), and fwServices::IService::m_configuration.
void uiMedData::editor::SOrganTransformation::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 154 of file SOrganTransformation.cpp.
References fwComEd::ModelSeriesMsg::ADD_RECONSTRUCTION.
void uiMedData::editor::SOrganTransformation::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 76 of file SOrganTransformation.cpp.
References fwGui::IGuiContainerSrv::create(), SLM_ASSERT, and updating().
void uiMedData::editor::SOrganTransformation::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 123 of file SOrganTransformation.cpp.
References fwGui::IGuiContainerSrv::destroy().
void uiMedData::editor::SOrganTransformation::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 140 of file SOrganTransformation.cpp.
References updating().
void uiMedData::editor::SOrganTransformation::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 147 of file SOrganTransformation.cpp.
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
SOrganTransformation.hpp
SOrganTransformation.cpp