fw4spl: fwDcmtkIO::reader::ImageStorageReader Class Reference
fwDcmtkIO::reader::ImageStorageReader Class Reference
Base class for Dicom instance reader.
#include <ImageStorageReader.hpp>
Public Types
typedef ::fwMedData::DicomSeries::DicomContainerType DicomContainerType
Public Member Functions
FWDCMTKIO_API ImageStorageReader ()
Constructor.
virtual FWDCMTKIO_API ~ImageStorageReader ()
Destructor.
virtual FWDCMTKIO_API::fwMedData::Series::sptr read (const ::fwMedData::DicomSeries::csptr &series)
Override.
Public Member Functions inherited from fwDcmtkIO::reader::IObjectReader
FWDCMTKIO_API IObjectReader ()
Constructor.
virtual FWDCMTKIO_API ~IObjectReader ()
Destructor.
Protected Member Functions
FWDCMTKIO_API void directRead (const ::fwData::Image::sptr &image, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation,::fwTools::Type imageType)
Read an image using direct mode.
FWDCMTKIO_API void directRGBLookupRead (const ::fwData::Image::sptr &image, DcmDataset &dataset, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, unsigned short bitsAllocated)
Read an image using direct mode and perform a RGB lookup.
FWDCMTKIO_API void lazyRead (const ::fwData::Image::sptr &image, const ::fwMedData::DicomSeries::csptr &series, unsigned short rows, unsigned short columns, int depth, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation,::fwTools::Type imageType)
Read an image using lazy mode.
FWDCMTKIO_API void lazyRGBLookupRead (const ::fwData::Image::sptr &image, const ::fwMedData::DicomSeries::csptr &series, DcmDataset &dataset, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, unsigned short bitsAllocated,::fwTools::Type imageType)
Read an image using lazy mode and perform a RGB lookup.
Detailed Description
Base class for Dicom instance reader.
Definition at line 26 of file ImageStorageReader.hpp.
Member Function Documentation
void fwDcmtkIO::reader::ImageStorageReader::directRead (const ::fwData::Image::sptr & image, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation, ::fwTools::Type imageType) protected
Read an image using direct mode.
Parameters
[in] image Image
[in] instances Instances
[in] rows Rows
[in] columns Columns
[in] depth Depth
[in] rescaleSlope Rescale Slope
[in] rescaleIntercept Rescale Intercept
[in] pixelRepresentation Pixel representation
[in] imageType Image Type
Definition at line 277 of file ImageStorageReader.cpp.
References fwDcmtkIO::reader::main::ImageReader::fillImageBuffer(), and fwDataTools::helper::Array::getBuffer().
Referenced by read().
void fwDcmtkIO::reader::ImageStorageReader::directRGBLookupRead (const ::fwData::Image::sptr & image, DcmDataset & dataset, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, unsigned short bitsAllocated) protected
Read an image using direct mode and perform a RGB lookup.
Parameters
[in] image Image
[in] dataset Dataset of the first instance
[in] instances Instances
[in] rows Rows
[in] columns Columns
[in] depth Depth
[in] bitsAllocated Number of bits allocated
Definition at line 298 of file ImageStorageReader.cpp.
References fwDataTools::helper::Array::getBuffer().
Referenced by read().
void fwDcmtkIO::reader::ImageStorageReader::lazyRead (const ::fwData::Image::sptr & image, const ::fwMedData::DicomSeries::csptr & series, unsigned short rows, unsigned short columns, int depth, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation, ::fwTools::Type imageType) protected
Read an image using lazy mode.
Parameters
[in] image Image
[in] series Series
[in] rows Rows
[in] columns Columns
[in] depth Depth
[in] rescaleSlope Rescale Slope
[in] rescaleIntercept Rescale Intercept
[in] pixelRepresentation Pixel Representation
[in] imageType Image Type
Definition at line 372 of file ImageStorageReader.cpp.
Referenced by read().
void fwDcmtkIO::reader::ImageStorageReader::lazyRGBLookupRead (const ::fwData::Image::sptr & image, const ::fwMedData::DicomSeries::csptr & series, DcmDataset & dataset, DicomContainerType instances, unsigned short rows, unsigned short columns, int depth, unsigned short bitsAllocated, ::fwTools::Type imageType) protected
Read an image using lazy mode and perform a RGB lookup.
Parameters
[in] image Image
[in] series Series
[in] dataset Dataset of the first instance
[in] instances Instances
[in] rows Rows
[in] columns Columns
[in] depth Depth
[in] bitsAllocated Bits allocated
[in] imageType Image type
Definition at line 401 of file ImageStorageReader.cpp.
Referenced by read().
The documentation for this class was generated from the following files:
ImageStorageReader.hpp
ImageStorageReader.cpp