fw4spl: fwGdcmIO::reader::ie::Image Class Reference
fwGdcmIO::reader::ie::Image Class Reference
Image Information Entity class.
#include <Image.hpp>
Public Member Functions
FWGDCMIO_API Image (std::shared_ptr< ::fwMedData::DicomSeries >dicomSeries, std::shared_ptr< ::gdcm::Reader >reader, std::shared_ptr< ::fwGdcmIO::container::DicomInstance >instance,::fwData::Image::sptr image,::fwLog::Logger::sptr logger, const ProgressCallback &callback, const bool &cancelled)
Constructor.
virtual FWGDCMIO_API ~Image ()
Destructor.
virtual FWGDCMIO_API void readImagePlaneModule ()
Read Image Plane Module tags.
virtual FWGDCMIO_API void readImagePixelModule ()
Read Image Pixel Module tags.
virtual FWGDCMIO_API void readVOILUTModule ()
Read VOI LUT Module tags.
void setBufferRotationEnabled (bool enabled)
Enable buffer rotation.
Public Member Functions inherited from fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >
FWGDCMIO_API InformationEntity (std::shared_ptr< ::fwMedData::DicomSeries >dicomSeries, std::shared_ptr< ::gdcm::Reader >reader, std::shared_ptr< ::fwGdcmIO::container::DicomInstance >instance, std::shared_ptr< ::fwData::Image >object,::fwLog::Logger::sptr logger, const ProgressCallback &callback, const bool &cancelled)
Constructor.
virtual FWGDCMIO_API ~InformationEntity ()
Destructor.
Protected Types
typedef ::boost::numeric::ublas::matrix< double,::boost::numeric::ublas::row_major, std::vector< double > > MatrixType
typedef ::boost::numeric::ublas::vector< double > VectorType
Protected Member Functions
char * readImageBuffer (const std::vector< unsigned int > &dimensions, unsigned short bitsAllocated, unsigned short newBitsAllocated, bool performRescale) throw (::fwGdcmIO::exception::Failed)
Read image buffer.
char * correctImageOrientation (char *buffer, const std::vector< unsigned int > &dimensions, unsigned short bitsAllocated)
Correct image buffer according to image orientation.
MatrixType computeInverseMatrix (MatrixType matrix)
Compute the inverse of matrix.
Protected Attributes
bool m_enableBufferRotation
Enable buffer rotation.
Protected Attributes inherited from fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >
std::shared_ptr< ::fwMedData::DicomSeries > m_dicomSeries
Dicom Series.
std::shared_ptr< ::gdcm::Reader > m_reader
GDCM Reader.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< ::fwData::Image > m_object
FW4SPL Object.
::fwLog::Logger::sptr m_logger
Logger.
const ProgressCallback & m_progressCallback
Progress callback for jobs.
const bool & m_cancelled
Cancel information for jobs.
Additional Inherited Members
Public Types inherited from fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >
typedef std::function< void(unsigned int &) > ProgressCallback
Detailed Description
Image Information Entity class.
Definition at line 27 of file SrcLib/io/fwGdcmIO/include/fwGdcmIO/reader/ie/Image.hpp.
Constructor & Destructor Documentation
fwGdcmIO::reader::ie::Image::Image (std::shared_ptr< ::fwMedData::DicomSeries > dicomSeries, std::shared_ptr< ::gdcm::Reader > reader, std::shared_ptr< ::fwGdcmIO::container::DicomInstance > instance, ::fwData::Image::sptr image, ::fwLog::Logger::sptr logger, const ProgressCallback & callback, const bool & cancelled)
Constructor.
Parameters
[in] dicomSeries DicomSeries used to access computed tag values.
[in] reader GDCM reader that must be enriched
[in] instance DICOM instance used to share informations between modules
[in] image Image data
[in] logger Logger
[in] callback Progress callback
[in] cancelled cancel information
Definition at line 45 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
Member Function Documentation
Image::MatrixType fwGdcmIO::reader::ie::Image::computeInverseMatrix (MatrixType matrix) protected
Compute the inverse of matrix.
Parameters
[in] matrix Matrix that must be inverted
Definition at line 635 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References SLM_WARN.
Referenced by correctImageOrientation().
char * fwGdcmIO::reader::ie::Image::correctImageOrientation (char * buffer, const std::vector< unsigned int > & dimensions, unsigned short bitsAllocated) protected
Correct image buffer according to image orientation.
Parameters
[in,out] buffer Image buffer
[in] dimensions Image dimensions
[in] bitsAllocated Number of bits allocated before rescale
Definition at line 432 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References computeInverseMatrix(), fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_cancelled, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_logger, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_progressCallback, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_reader, and SPTR.
Referenced by readImagePixelModule().
char * fwGdcmIO::reader::ie::Image::readImageBuffer (const std::vector< unsigned int > & dimensions, unsigned short bitsAllocated, unsigned short newBitsAllocated, bool performRescale) throw (::fwGdcmIO::exception::Failed) protected
Read image buffer.
Parameters
[in] dimensions Image dimensions
[in] bitsAllocated Number of bits allocated before rescale
[in] newBitsAllocated Number of bits allocated after rescale
[in] performRescale Set to true when a rescale must be perfromed
Returns
Global raw buffer of the image.
Definition at line 304 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References fwGdcmIO::helper::DicomData::getPixelType(), fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_cancelled, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_dicomSeries, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_instance, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_logger, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_progressCallback, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_reader, and SPTR.
Referenced by readImagePixelModule().
void fwGdcmIO::reader::ie::Image::readImagePixelModule () virtual
Read Image Pixel Module tags.
See also
PS 3.3 C.7.6.3
Definition at line 184 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References correctImageOrientation(), fwDicomTools::Image::findImageTypeFromMinMaxValues(), fwGdcmIO::helper::DicomData::getPixelType(), fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_cancelled, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_dicomSeries, m_enableBufferRotation, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_reader, OSLM_TRACE, readImageBuffer(), fwDataTools::helper::Array::setBuffer(), and SPTR.
void fwGdcmIO::reader::ie::Image::readImagePlaneModule () virtual
Read Image Plane Module tags.
See also
PS 3.3 C.7.6.2
Definition at line 66 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_dicomSeries, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_logger, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_reader, OSLM_TRACE, and SPTR.
void fwGdcmIO::reader::ie::Image::readVOILUTModule () virtual
Read VOI LUT Module tags.
See also
PS 3.3 C.11.2
Definition at line 133 of file SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp.
References fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::reader::ie::InformationEntity< ::fwData::Image >::m_reader, and OSLM_TRACE.
The documentation for this class was generated from the following files:
SrcLib/io/fwGdcmIO/include/fwGdcmIO/reader/ie/Image.hpp
SrcLib/io/fwGdcmIO/src/fwGdcmIO/reader/ie/Image.cpp