fw4spl: fwStructuralPatch::fwData::Material::V4ToV3 Class Reference
fwStructuralPatch::fwData::Material::V4ToV3 Class Reference
Structural patch to convert a fwData::Material from version '4' to version '3'.
#include <V4ToV3.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWSTRUCTURALPATCH_API V4ToV3 ()
Constructor.
FWSTRUCTURALPATCH_API ~V4ToV3 ()
Destructor.
FWSTRUCTURALPATCH_API V4ToV3 (const V4ToV3 &cpy)
Copy constructor.
virtual FWSTRUCTURALPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies patch.
Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
FWATOMSPATCH_API IStructuralPatch ()
Constructor.
FWATOMSPATCH_API IStructuralPatch (const IStructuralPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IStructuralPatch ()
Destructor.
virtual FWATOMSPATCH_API void apply (const std::shared_ptr< ::fwAtoms::Object > &previous, const std::shared_ptr< ::fwAtoms::Object > &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies the patch to the specified object.
virtual FWATOMSPATCH_API const std::string & getTargetClassname () const
Returns the target classname of the object.
virtual FWATOMSPATCH_API const std::string & getTargetVersion () const
Returns the target version of the object.
Public Member Functions inherited from fwAtomsPatch::IPatch
FWATOMSPATCH_API IPatch ()
Constructor. Does nothing.
FWATOMSPATCH_API IPatch (const IPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IPatch ()
Destructor. Does nothing.
virtual FWATOMSPATCH_API const std::string & getOriginClassname () const
Returns the origin classname of the object.
virtual FWATOMSPATCH_API const std::string & getOriginVersion () const
Returns the origin version of the object.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwAtomsPatch::IPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwAtomsPatch::IPatch
typedef std::map< ::fwAtoms::Object::sptr,::fwAtoms::Object::sptr > NewVersionsType
Protected Member Functions inherited from fwAtomsPatch::IStructuralPatch
FWATOMSPATCH_API void updateVersion (std::shared_ptr< ::fwAtoms::Object > current)
Updates the version of the patched object.
Protected Attributes inherited from fwAtomsPatch::IStructuralPatch
std::string m_targetClassname
Target type.
std::string m_targetVersion
Target version.
Protected Attributes inherited from fwAtomsPatch::IPatch
std::string m_originClassname
Origin classname of the object.
std::string m_originVersion
Origin version of the object.
Detailed Description
Structural patch to convert a fwData::Material from version '4' to version '3'.
Definition at line 25 of file V4ToV3.hpp.
Member Function Documentation
void fwStructuralPatch::fwData::Material::V4ToV3::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) virtual
Applies patch.
Added new map of additional array.
Implements fwAtomsPatch::IPatch.
Definition at line 48 of file V4ToV3.cpp.
References fwAtomsPatch::helper::Object::addAttribute(), fwAtoms::Object::getAttribute(), fwAtoms::Boolean::New(), fwAtoms::String::New(), fwAtomsPatch::helper::Object::replaceAttribute(), and fwAtomsPatch::IStructuralPatch::updateVersion().
The documentation for this class was generated from the following files:
V4ToV3.hpp
V4ToV3.cpp