fw4spl: fwGdcmIO::helper::StructuredReport Class Reference
fwGdcmIO::helper::StructuredReport Class Reference
This class contains helpers for DICOM Structured Reporting (SR).
#include <StructuredReport.hpp>
Static Public Member Functions
static FWGDCMIO_API std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRContainerNode > readSR (const ::gdcm::DataSet &dataset)
Read a Structured Report.
static FWGDCMIO_API void dumpSR (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &root, std::ostream &out=std::cout)
Dump the SR in graphviz format.
Static Protected Member Functions
static void readSubNodeContainer (const ::gdcm::DataSet &dataset, std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > parent)
Read all sub nodes and add it as children to the parent node.
static void readSubNode (const ::gdcm::DataSet &dataset, std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > parent)
Read a sub node and add it as a child to the parent node.
static FWGDCMIO_API void dumpSRNode (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &node, std::ostream &out, int &index)
Dump an SR node in graphviz format.
template<uint16_t GROUP, uint16_t ELEMENT>
::fwGdcmIO::container::DicomCodedAttribute readCodeSequence (const ::gdcm::DataSet &dataset)
Read content of a code sequence (eg : Concept Name Code Sequence, ...)
Detailed Description
This class contains helpers for DICOM Structured Reporting (SR).
Definition at line 26 of file StructuredReport.hpp.
Member Function Documentation
void fwGdcmIO::helper::StructuredReport::dumpSR (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & root, std::ostream & out = std::cout) static
Dump the SR in graphviz format.
Parameters
[in] root Root node
[in] out Destination stream
Definition at line 245 of file StructuredReport.cpp.
References dumpSRNode().
void fwGdcmIO::helper::StructuredReport::dumpSRNode (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & node, std::ostream & out, int & index) static protected
Dump an SR node in graphviz format.
Parameters
[in] node Node
[in] out Destination stream
[in] index Node index
Definition at line 255 of file StructuredReport.cpp.
References fwGdcmIO::container::sr::DicomSRNode::getSubNodeContainer(), and SPTR.
Referenced by dumpSR().
template<uint16_t GROUP, uint16_t ELEMENT> ::fwGdcmIO::container::DicomCodedAttribute fwGdcmIO::helper::StructuredReport::readCodeSequence (const ::gdcm::DataSet & dataset) inline static protected
Read content of a code sequence (eg : Concept Name Code Sequence, ...)
Note
This method can return a DicomCodedAttribute with empty members.
Parameters
[in] dataset Data set where the code sequence is supposed to be.
Template Parameters
GROUP Tag group of the code sequence.
ELEMENT Element group of the code sequence.
Definition at line 80 of file StructuredReport.hpp.
std::shared_ptr<::fwGdcmIO::container::sr::DicomSRContainerNode > fwGdcmIO::helper::StructuredReport::readSR (const ::gdcm::DataSet & dataset) static
Read a Structured Report.
Parameters
[in] dataset Dataset from which the SR must be created
Definition at line 25 of file StructuredReport.cpp.
References readSubNodeContainer(), and SPTR.
Referenced by fwGdcmIO::reader::ie::Document::readSR().
void fwGdcmIO::helper::StructuredReport::readSubNode (const ::gdcm::DataSet & dataset, std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > parent) static protected
Read a sub node and add it as a child to the parent node.
Parameters
[in] dataset Dataset from which the sub node must been read
[in] parent Parent node
Definition at line 67 of file StructuredReport.cpp.
References fwGdcmIO::container::sr::DicomSRNode::addSubNode(), readSubNodeContainer(), SLM_WARN, and SPTR.
Referenced by readSubNodeContainer().
void fwGdcmIO::helper::StructuredReport::readSubNodeContainer (const ::gdcm::DataSet & dataset, std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > parent) static protected
Read all sub nodes and add it as children to the parent node.
Parameters
[in] dataset Dataset from which the sub nodes must been read
[in] parent Parent node
Definition at line 47 of file StructuredReport.cpp.
References readSubNode().
Referenced by readSR(), and readSubNode().
The documentation for this class was generated from the following files:
StructuredReport.hpp
StructuredReport.cpp