fw4spl: ioVTK::SImageSeriesWriter Class Reference
ioVTK::SImageSeriesWriter Class Reference
Image series writer service.Service writing an image series using the fwVtkIO lib.
#include <SImageSeriesWriter.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SImageSeriesWriter)(::io::IWriter))
virtual IOVTK_API void configureWithIHM ()
Configure the image path.
Protected Member Functions
virtual IOVTK_API::io::IOPathType getIOPathType () const
This method must be implemented by concrete service writers that use path file system to write data.
virtual IOVTK_API void starting () throw (::fwTools::Failed)
Starting method.
virtual IOVTK_API void stopping () throw (::fwTools::Failed)
Stopping method.
IOVTK_API void updating () throw (::fwTools::Failed)
Updating method.
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : default does nothing.
IOVTK_API void info (std::ostream &_sstream)
Info method.
Detailed Description
Image series writer service.
Service writing an image series using the fwVtkIO lib.
Definition at line 33 of file ioVTK/include/ioVTK/SImageSeriesWriter.hpp.
Member Function Documentation
io::IOPathType ioVTK::SImageSeriesWriter::getIOPathType () const [protected, virtual]
This method must be implemented by concrete service writers that use path file system to write data.
This method returns supported path format (file, files or folder). A reader can support file and folder, or files and folder, but not file and files (because files include file concept).
Reimplemented from io::IWriter.
Definition at line 47 of file ioVTK/src/ioVTK/SImageSeriesWriter.cpp.
void ioVTK::SImageSeriesWriter::info (std::ostream & _sstream) [protected, virtual]
Info method.
This method is used to give informations about the service.
Reimplemented from fwServices::IService.
Definition at line 98 of file ioVTK/src/ioVTK/SImageSeriesWriter.cpp.
void ioVTK::SImageSeriesWriter::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [inline, protected]
React on modifications : default does nothing.
Note:
This method is automatically called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 79 of file ioVTK/include/ioVTK/SImageSeriesWriter.hpp.
void ioVTK::SImageSeriesWriter::starting () throw (::fwTools::Failed) [protected, virtual]
Starting method.
This method is used to initialize the service.
Implements fwServices::IService.
Definition at line 84 of file ioVTK/src/ioVTK/SImageSeriesWriter.cpp.
References SLM_TRACE_FUNC.
void ioVTK::SImageSeriesWriter::stopping () throw (::fwTools::Failed) [protected, virtual]
Stopping method.
The stopping method is empty for this service.
Implements fwServices::IService.
Definition at line 91 of file ioVTK/src/ioVTK/SImageSeriesWriter.cpp.
References SLM_TRACE_FUNC.
void ioVTK::SImageSeriesWriter::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method.
This method is used to update the service. The image is read.
Implements fwServices::IService.
Definition at line 105 of file ioVTK/src/ioVTK/SImageSeriesWriter.cpp.
References io::IWriter::getFile(), io::IWriter::hasLocationDefined(), OSLM_TRACE, ioVTK::ImageWriterService::saveImage(), fwGui::Cursor::setCursor(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
ioVTK/include/ioVTK/SImageSeriesWriter.hpp
ioVTK/src/ioVTK/SImageSeriesWriter.cpp