fw4spl: fwGui::IActionSrv Class Reference
fwGui::IActionSrv Class Reference
Defines the service interface managing the menu items.
#include <IActionSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IActionSrv)(::fwServices::IService))
fwCoreAllowSharedFromThis ()
FWGUI_API void actionServiceStopping ()
Method called when the action service is stopping.
FWGUI_API void actionServiceStarting ()
Method called when the action service is starting.
virtual FWGUI_API void setIsActive (bool isActive)
Set the action service is active/inactive.
FWGUI_API bool getIsActive ()
Return true if action service is active.
bool getActiveStateValue ()
Return true if action 'check' feedback is inverted.
FWGUI_API void setIsExecutable (bool isExecutable)
Set the action service executable or not.
FWGUI_API bool getIsExecutable ()
Return action service is executable.
FWGUI_API bool confirmAction ()
Confirm that the action must be executed.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr ConfigurationType
Protected Member Functions
FWGUI_API void initialize ()
Initialize the action.
Detailed Description
Defines the service interface managing the menu items.
Date:
2009-2010.
Definition at line 26 of file IActionSrv.hpp.
Member Function Documentation
bool fwGui::IActionSrv::confirmAction ()
Confirm that the action must be executed.
If action is configured to be confirmed : show a dialog box to confirm execution. Else return true
Returns:
true if user click on 'yes' button.
Definition at line 144 of file IActionSrv.cpp.
References fwGui::dialog::MessageDialog::addButton(), fwGui::dialog::MessageDialog::setDefaultButton(), fwGui::dialog::MessageDialog::setIcon(), fwGui::dialog::MessageDialog::setMessage(), fwGui::dialog::MessageDialog::setTitle(), fwGui::dialog::MessageDialog::show(), and SLM_WARN.
Referenced by gui::action::ActionNotifyService::updating(), and gui::action::SSignal::updating().
void fwGui::IActionSrv::initialize () [protected]
Initialize the action.
Example of configuration
           <service uid="item" type="::fwGui::IActionSrv" impl="::gui::action::NothingActionSrv" autoConnect="no" >
              <state active="false" executable="false" inverse="true" />
              <confirmation value="yes" message="..." />
           </service>
<state active="false" executable="false" /> : fix the state of the action in the menu and Toolbar.
executable not mandatory (Default value true) : allows to enable/disable the execution of the action. If the action appears in the interface it will be enable/disable.
active not mandatory (Default value false): If the action appears in the interface it will be check/uncheck.
inverse not mandatory (Default value true) : allow to invert the state of the action (if "check")
<confirmation value="yes" message="..." /> : configure if the action must be confirm by user before to execute it.
value : if true the action will show a confirmation message before to be executed.
message not mandatory : if not empty the message is shown in dialog box.
defaultbutton not mandatory (default defined by underlying gui backend) : specify the dialog default button (yes or no)
Definition at line 34 of file IActionSrv.cpp.
References OSLM_ASSERT, and SLM_ASSERT.
Referenced by uiMeasurement::action::LoadLandmark::configuring(), uiMeasurement::action::SaveLandmark::configuring(), monitor::action::fwMetrics::configuring(), uiMeasurement::action::AddDistance::configuring(), uiMeasurement::action::AddLandmark::configuring(), monitor::action::MemoryInfo::configuring(), uiMeasurement::action::ShowLandmark::configuring(), monitor::action::SDumpAll::configuring(), opImageFilter::action::ImageFilter::configuring(), uiMeasurement::action::SAddLabeledPoint::configuring(), uiMeasurement::action::RemoveDistance::configuring(), uiMeasurement::action::RemoveLandmark::configuring(), monitor::action::ClassFactoryRegistryInfo::configuring(), opVTKMesh::action::VTKMeshCreation::configuring(), uiMeasurement::action::ShowDistance::configuring(), uiMeasurement::action::FocusLandmark::configuring(), monitor::action::ComponentsTree::configuring(), uiGeneric::action::ShowHelpContents::configuring(), uiGeneric::action::ShowAcknowledgments::configuring(), monitor::action::MemoryConsumption::configuring(), gui::action::NothingActionSrv::configuring(), uiGeneric::action::LaunchBrowserActionService::configuring(), gui::action::QuitAction::configuring(), uiVisu::action::CameraOrientationAction::configuring(), uiPython::action::Test::configuring(), uiPython::action::StringRun::configuring(), uiMedData::action::SExportSeries::configuring(), uiMedData::action::SInitNewSeries::configuring(), uiGeneric::action::SShowAbout::configuring(), uiGeneric::action::ShowRevInfo::configuring(), uiIO::action::SSeriesDBMerger::configuring(), gui::action::ActionNotifyService::configuring(), gui::action::PushObjectSrv::configuring(), ioData::action::SMeshModifier::configuring(), uiVisu::action::CrossTypeAction::configuring(), uiVisu::action::SSnapshot::configuring(), gui::action::SSlotCaller::configuring(), gui::action::SSignal::configuring(), gui::action::ModifyLayoutActionSrv::configuring(), activities::action::SActivityLauncher::configuring(), gui::action::StarterActionService::configuring(), gui::action::SConfigLauncher::configuring(), and gui::action::ConfigActionSrv::configuring().
The documentation for this class was generated from the following files:
IActionSrv.hpp
IActionSrv.cpp