fw4spl: fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource Class Reference
fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource Class Reference
Class used to build a std::istream using the ::boost::iostreams api.
#include <ImageRGBLookupLazyStream.hpp>
Public Types
typedef char char_type
typedef ::boost::iostreams::source_tag category
Public Member Functions
ImageRGBLookupLazySource (ImageRGBLookupLazyInformation::sptr dcmInfo)
Constructor.
std::streamsize read (char *stream, std::streamsize size)
Method to read n bytes in dicom buffer and write it in s.
Detailed Description
Class used to build a std::istream using the ::boost::iostreams api.
Definition at line 68 of file ImageRGBLookupLazyStream.hpp.
Constructor & Destructor Documentation
fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource::ImageRGBLookupLazySource (ImageRGBLookupLazyInformation::sptr dcmInfo)
Constructor.
Parameters
[in] dcmInfo DICOM information
Definition at line 27 of file ImageRGBLookupLazyStream.cpp.
References fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader::createInstanceBuffer(), fwMemory::BufferObject::LockBase< T >::getBuffer(), and SLM_ASSERT.
Member Function Documentation
std::streamsize fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource::read (char * stream, std::streamsize size)
Method to read n bytes in dicom buffer and write it in s.
Parameters
[in] size Number of bytes
[out] stream Destination buffer
Definition at line 116 of file ImageRGBLookupLazyStream.cpp.
References fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader::createInstanceBuffer(), and SLM_TRACE.
The documentation for this class was generated from the following files:
ImageRGBLookupLazyStream.hpp
ImageRGBLookupLazyStream.cpp