fw4spl: fwData::Color Class Reference
fwData::Color Class Reference
This class defines color object.
#include <Color.hpp>
Public Types
typedef float ColorType
typedef ::boost::array
< ColorType, 4 > ColorArray
Public Member Functions
fwCoreClassDefinitionsWithNFactoriesMacro ((Color)(::fwData::Object),((::fwData::factory::New< Color >,()))((ColorFactory,((ColorType))((ColorType)(1.0))((ColorType)(1.0))((ColorType)(1.0)))))
fwCampMakeFriendDataMacro ((fwData)(Color))
FWDATA_API Color (::fwData::Object::Key key)
Constructor.
virtual FWDATA_API ~Color ()
Destructor.
FWDATA_API void shallowCopy (const Object::csptr &_source)
Defines shallow copy.
FWDATA_API void cachedDeepCopy (const Object::csptr &_source, DeepCopyCacheType &cache)
Defines deep copy.
fwGettersSettersDocMacro (RGBA, vRGBA, ColorArray, the array of color values(red, green, blue, alpha).)
FWDATA_API void setRGBA (const ColorType red, const ColorType green, const ColorType blue, const ColorType alpha=1.0)
set RGBA color
FWDATA_API void setRGBA (std::string hexaColor)
set RGBA from hexadecimal format (#ffffff)
color attributes accessor
FWDATA_API ColorType & red ()
Get editable reference to color attributes.
FWDATA_API ColorType & green ()
Get editable reference to color attributes.
FWDATA_API ColorType & blue ()
Get editable reference to color attributes.
FWDATA_API ColorType & alpha ()
Get editable reference to color attributes.
FWDATA_API const ColorType & red () const
Get read-only reference to color attributes.
FWDATA_API const ColorType & green () const
Get read-only reference to color attributes.
FWDATA_API const ColorType & blue () const
Get read-only reference to color attributes.
FWDATA_API const ColorType & alpha () const
Get read-only reference to color attributes.
Static Protected Member Functions
static FWDATA_API sptr ColorFactory (ColorType red, ColorType green, ColorType blue, ColorType alpha)
Protected Attributes
ColorArray m_vRGBA
RGBA of the image (in terms of points)
Detailed Description
This class defines color object.
Definition at line 24 of file Color.hpp.
Constructor & Destructor Documentation
fwData::Color::Color (::fwData::Object::Key key)
Constructor.
Parameters:
key Private construction key
Definition at line 20 of file src/fwData/Color.cpp.
References m_vRGBA.
Member Function Documentation
void fwData::Color::setRGBA (const ColorType red, const ColorType green, const ColorType blue, const ColorType alpha = 1.0)
set RGBA color
Parameters:
[in] red
[in] green
[in] blue
[in] alpha
Definition at line 72 of file src/fwData/Color.cpp.
References alpha(), blue(), green(), m_vRGBA, and red().
Referenced by setRGBA().
void fwData::Color::setRGBA (std::string hexaColor)
set RGBA from hexadecimal format (#ffffff)
Parameters:
[in] hexaColor c hexadecimal format (#ffffff)
Definition at line 82 of file src/fwData/Color.cpp.
References OSLM_ASSERT, and setRGBA().
The documentation for this class was generated from the following files:
Color.hpp
src/fwData/Color.cpp