fw4spl: ctrlSelection::updater::SDrop Class Reference
ctrlSelection::updater::SDrop Class Reference
Drop received object to associated fwData::Composite.
#include <SDrop.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SDrop)(::ctrlSelection::IUpdaterSrv))
CTRLSELECTION_API SDrop () throw ()
Constructor. Do nothing.
virtual CTRLSELECTION_API ~SDrop () throw ()
Destructor. Do nothing.
Protected Member Functions
virtual CTRLSELECTION_API void starting () throw (::fwTools::Failed)
Implements starting method derived from IService. Do nothing.
virtual CTRLSELECTION_API void stopping () throw (::fwTools::Failed)
Implements stopping method derived from IService. Do nothing.
virtual CTRLSELECTION_API void configuring () throw (::fwTools::Failed)
Implements configuring method derived from IService. Do nothing.
virtual CTRLSELECTION_API void reconfiguring () throw (::fwTools::Failed)
Implements reconfiguring method derived from IService. Do nothing.
virtual CTRLSELECTION_API void updating () throw (::fwTools::Failed)
Implements updating method derived from IService. Do nothing.
virtual CTRLSELECTION_API void info (std::ostream &_sstream)
Implements info method derived from IService. Print classname.
virtual CTRLSELECTION_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
Detailed Description
Drop received object to associated fwData::Composite.
Definition at line 24 of file SDrop.hpp.
Member Function Documentation
void ctrlSelection::updater::SDrop::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 42 of file SDrop.cpp.
References fwComEd::helper::Composite::add(), fwComEd::helper::Composite::clear(), fwTools::UUID::get(), and fwComEd::helper::Composite::notify().
The documentation for this class was generated from the following files:
SDrop.hpp
SDrop.cpp