fw4spl: fwTools::UUID Class Reference
fwTools::UUID Class Reference
Management of UUID on objects.
#include <UUID.hpp>
Public Types
typedef std::string UUIDType
Public Member Functions
virtual bool isA (const std::string &type) const
virtual FWTOOLS_API ~UUID ()
Destructor : does nothing.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (const UUIDType &uuid)
Return true iff the given uuid is used.
static FWTOOLS_API const UUIDType & get (::fwTools::Object::sptr object)
Return an uuid to the given object : if no one previously set then generate a new one.
static FWTOOLS_API::fwTools::Object::sptr get (const UUIDType &uuid)
Return a smart ptr on the object related to a given UUID : return null shared if not supervised.
static FWTOOLS_API UUIDType generateUUID ()
Return a new extended UUID;.
static FWTOOLS_API bool set (::fwTools::Object::sptr object, const UUID::UUIDType &uuid)
Attempt to set an UUID. If uuid already exists, do nothing.
Protected Types
typedef std::map< UUIDType,::fwTools::Object::wptr > UUIDContainer
Store association std::weak_ptr <–> uuid as a string.
Protected Member Functions
FWTOOLS_API UUID ()
Default constructor : does nothing.
Protected Attributes
::fwCore::mt::ReadWriteMutex m_uuidMutex
Mutex used to lock uuid object access.
Static Protected Attributes
static FWTOOLS_API UUIDContainer s_uuidMap
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Management of UUID on objects.
Date
2007-2009.
Definition at line 28 of file UUID.hpp.
Member Function Documentation
bool fwTools::UUID::exist (const UUIDType & uuid) static
Return true iff the given uuid is used.
Note
This method is thread-safe.
Definition at line 42 of file UUID.cpp.
UUID::UUIDType fwTools::UUID::generateUUID () static
Return a new extended UUID;.
Note
This method is thread-safe.
Definition at line 114 of file UUID.cpp.
Referenced by fwMDSemanticPatch::V1::V2::fwData::Patient::apply(), fwMDSemanticPatch::V1::V2::fwData::Study::apply(), fwMDSemanticPatch::V1::V2::fwData::Acquisition::apply(), fwMDSemanticPatch::V1::V2::fwData::Composite::apply(), fwMDSemanticPatch::V1::V2::fwData::Composite::Composite(), fwAtomsPatch::helper::generateID(), get(), guiQt::editor::SDynamicView::info(), fwVtkIO::SeriesDBReader::read(), ioITK::SInrSeriesDBReader::updating(), ioData::SAttachmentSeriesReader::updating(), and uiMedData::editor::SActivityWizard::updating().
const UUID::UUIDType & fwTools::UUID::get (::fwTools::Object::sptr object) static
Return an uuid to the given object : if no one previously set then generate a new one.
Note
This method is thread-safe.
Definition at line 50 of file UUID.cpp.
References generateUUID(), and SLM_ASSERT.
Referenced by fwAtomConversion::DataVisitor::DataVisitor(), ioVTK::SModelSeriesWriter::updating(), fwVtkIO::ModelSeriesObjWriter::write(), and ctrlSelection::updater::SDrop::~SDrop().
fwTools::Object::sptr fwTools::UUID::get (const UUIDType & uuid) static
Return a smart ptr on the object related to a given UUID : return null shared if not supervised.
Note
This method thread-safe.
Definition at line 74 of file UUID.cpp.
bool fwTools::UUID::set (::fwTools::Object::sptr object, const UUID::UUIDType & uuid) static
Attempt to set an UUID. If uuid already exists, do nothing.
Returns
true if the uuid is set, else false.
Note
This method is thread-safe.
Definition at line 88 of file UUID.cpp.
The documentation for this class was generated from the following files:
UUID.hpp
UUID.cpp