fw4spl: fwAtoms::Map Class Reference
fwAtoms::Map Class Reference
Map is a container for mapping representation.
#include <Map.hpp>
Public Types
typedef std::map< std::string,
Base::sptr > MapType
typedef MapType::key_type KeyType
typedef MapType::mapped_type MappedType
typedef MapType::value_type ValueType
typedef MapType::iterator IteratorType
typedef MapType::const_iterator ConstIteratorType
typedef MapType::reverse_iterator ReverseIteratorType
typedef
MapType::const_reverse_iterator ConstReverseIteratorType
typedef MapType::size_type SizeType
typedef MapType::key_type key_type
typedef MapType::mapped_type mapped_type
typedef MapType::value_type value_type
typedef MapType::iterator iterator
typedef MapType::const_iterator const_iterator
typedef MapType::reverse_iterator reverse_iterator
typedef
MapType::const_reverse_iterator const_reverse_iterator
typedef MapType::size_type size_type
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((Map)(::fwAtoms::Base),(()),::fwAtoms::factory::New< Map >)
Map (::fwAtoms::Base::Key key)
Constructor.
virtual ~Map ()
Destructor.
std::pair< IteratorType, bool > insert (const std::string &key, const Base::sptr &value)
Insert a new value in the map.
size_t size () const
retrieve size of map
IteratorType begin ()
Provide an iterator on the first element.
ConstIteratorType begin () const
Provide a const iterator on the first element.
IteratorType end ()
Return an iterator after the last element in the map.
ConstIteratorType end () const
Return a const iterator after the last element in the map.
void clear ()
clear the map
bool empty () const
test if the map is empty
const MapType & getValue () const
returns atom's map
MapType::const_iterator find (const std::string &key) const
find an element in the map
Base::sptr operator[] (const std::string &key)
Access to a member with [].
virtual FWATOMS_API Base::sptr clone () const
Returns a clone object.
::fwAtoms::Base::AtomType type () const
returns Atom type
Protected Attributes
MapType m_value
Detailed Description
Map is a container for mapping representation.
For exemple, this metadata is used to bind :
std::map
boost::unordered_map
fwData::Graph (a part)
boost graph
Definition at line 32 of file Map.hpp.
Member Typedef Documentation
typedef MapType::const_iterator fwAtoms::Map::const_iterator
boost_foreach/stl compatibility
Definition at line 55 of file Map.hpp.
typedef MapType::const_reverse_iterator fwAtoms::Map::const_reverse_iterator
boost_foreach/stl compatibility
Definition at line 57 of file Map.hpp.
typedef MapType::iterator fwAtoms::Map::iterator
boost_foreach/stl compatibility
Definition at line 54 of file Map.hpp.
typedef MapType::key_type fwAtoms::Map::key_type
boost_foreach/stl compatibility
Definition at line 51 of file Map.hpp.
typedef MapType::mapped_type fwAtoms::Map::mapped_type
boost_foreach/stl compatibility
Definition at line 52 of file Map.hpp.
typedef MapType::reverse_iterator fwAtoms::Map::reverse_iterator
boost_foreach/stl compatibility
Definition at line 56 of file Map.hpp.
typedef MapType::size_type fwAtoms::Map::size_type
boost_foreach/stl compatibility
Definition at line 58 of file Map.hpp.
typedef MapType::value_type fwAtoms::Map::value_type
boost_foreach/stl compatibility
Definition at line 53 of file Map.hpp.
Constructor & Destructor Documentation
fwAtoms::Map::Map (::fwAtoms::Base::Key key) [inline]
Constructor.
Parameters:
key Private construction key
Definition at line 65 of file Map.hpp.
Member Function Documentation
IteratorType fwAtoms::Map::begin () [inline]
Provide an iterator on the first element.
Returns:
An iterator on the first element, end() if map is empty.
Definition at line 92 of file Map.hpp.
ConstIteratorType fwAtoms::Map::begin () const [inline]
Provide a const iterator on the first element.
Returns:
An iterator on the first element, end() if map is empty.
Definition at line 98 of file Map.hpp.
bool fwAtoms::Map::empty () const [inline]
test if the map is empty
Returns:
true if empty
Definition at line 117 of file Map.hpp.
MapType::const_iterator fwAtoms::Map::find (const std::string & key) const [inline]
find an element in the map
Parameters:
key the key
Returns:
an iterator on value pointed by key if exist, else return Map.end()
Definition at line 131 of file Map.hpp.
Referenced by fwMDSemanticPatch::V1::V2::fwData::Acquisition::apply().
std::pair<IteratorType, bool> fwAtoms::Map::insert (const std::string & key, const Base::sptr & value) [inline]
Insert a new value in the map.
Parameters:
key the key, if exist the oldest value is erased.
value the new value
Definition at line 79 of file Map.hpp.
References insert().
Referenced by insert().
Base::sptr fwAtoms::Map::operator[] (const std::string & key) [inline]
Access to a member with [].
Parameters:
key a key in the map
Returns:
the value associated with the key or an empty base if the key is not in the map.
Definition at line 140 of file Map.hpp.
size_t fwAtoms::Map::size () const [inline]
retrieve size of map
Returns:
the map size
Definition at line 86 of file Map.hpp.
The documentation for this class was generated from the following files:
Map.hpp
Map.cpp