fw4spl: fwData::Array Class Reference
fwData::Array Class Reference
Provides a way to manage a view on a multidimentionnal array.
#include <Array.hpp>
Public Types
typedef std::vector< size_t > SizeType
Array size type.
typedef std::vector< size_t > OffsetType
Offset type.
typedef OffsetType IndexType
Index type.
Public Types inherited from fwData::Object
typedef ::fwData::factory::Key Key
typedef std::string FieldNameType
typedef std::vector< FieldNameType > FieldNameVectorType
typedef ::boost::unordered_map< FieldNameType,::fwData::Object::sptr > FieldMapType
typedef ::boost::unordered_map< ::fwData::Object::csptr,::fwData::Object::sptr > DeepCopyCacheType
typedef ::fwCom::Signal< void() > ModifiedSignalType
Type of signal m_sigModified.
typedef std::map< std::string,::fwData::Object::sptr > FieldsContainerType
Type of signal m_sigModified.
typedef ::fwCom::Signal< void(FieldsContainerType) > AddedFieldsSignalType
Type of signal when objects are added.
typedef ::fwCom::Signal< void(FieldsContainerType, FieldsContainerType) > ChangedFieldsSignalType
Type of signal when objects are changed (newObjects, oldObjects)
typedef ::fwCom::Signal< void(FieldsContainerType) > RemovedFieldsSignalType
Type of signal when objects are removed.
Public Types inherited from fwTools::DynamicAttributes< ::fwData::Object >
typedef std::string AttrNameType
typedef std::shared_ptr< ::fwData::Object > AttrType
typedef std::vector< AttrNameType > AttrNameVectorType
typedef ::boost::reference_wrapper< AttrType > AttrRefType
typedef std::map< AttrNameType, AttrRefType > AttrMapType
typedef std::shared_ptr< const ::fwData::Object > ConstAttrType
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Array)(::fwData::Object))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< Array >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Array)(::fwData::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWDATA_API Array (::fwData::Object::Key key)
Constructor.
FWDATA_API void cachedDeepCopy (const Object::csptr &_source, DeepCopyCacheType &cache)
Defines deep copy.
virtual FWDATA_API size_t resize (const ::fwTools::Type &type, const SizeType &size, size_t nbOfComponents, bool reallocate=false) throw (::fwData::Exception)
Resizes and allocate (if needed) the array.
virtual FWDATA_API size_t resize (const std::string &type, const SizeType &size, size_t nbOfComponents, bool reallocate=false) throw (::fwData::Exception)
Aliases to the resize method.
virtual FWDATA_API size_t resize (const SizeType &size, size_t nbOfComponents, bool reallocate=false) throw (::fwData::Exception)
virtual FWDATA_API size_t resize (const SizeType &size, bool reallocate=false) throw (::fwData::Exception)
virtual FWDATA_API void clear ()
Clear this array. Size, type, nbOfComponents are reset, buffer is released.
virtual FWDATA_API bool empty () const
Test whether array is empty.
virtual FWDATA_API size_t getElementSizeInBytes () const
Get the size of one element of the array, ie. sizeof type * nbOfComponents.
virtual FWDATA_API size_t getNumberOfElements () const
Get the number of elements of type <getType()> in the array.
virtual FWDATA_API size_t getSizeInBytes () const
Getter for the array view size.
virtual FWDATA_API const SizeType & getSize () const
Getter for the array size.
virtual FWDATA_API const OffsetType & getStrides () const
Getter for the array strides.
virtual FWDATA_API void setNumberOfComponents (size_t nb)
Setter for array's number of components If the array has a buffer and owns it, the buffer will be reallocated.
virtual FWDATA_API size_t getNumberOfComponents () const
Getter for number of components.
virtual FWDATA_API size_t getNumberOfDimensions () const
Getter for number of dimensions, ie. getSize().size()
virtual FWDATA_API void setIsBufferOwner (const bool own)
Set array's buffer ownership.
virtual FWDATA_API bool getIsBufferOwner () const
Getter for array's buffer ownership.
virtual FWDATA_API void setType (const std::string &type)
Setter for array's type.
virtual FWDATA_API void setType (const ::fwTools::Type &type)
virtual FWDATA_API::fwTools::Type getType () const
Getter for array's type.
FWDATA_API size_t getBufferOffset (const ::fwData::Array::IndexType &id, size_t component, size_t sizeOfType) const
Compute offset in buffer for given parameters of type.
::fwMemory::BufferObject::sptr getBufferObject () const
void setBufferObject (const ::fwMemory::BufferObject::sptr &val)
FWDATA_API void swap (Array::sptr _source)
Exchanges the content of the Array with the content of _source.
Public Member Functions inherited from fwData::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwTools::Object))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwTools::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWDATA_API::fwData::Object::sptr getField (const FieldNameType &name,::fwData::Object::sptr defaultValue=::fwData::Object::sptr()) const
Returns a pointer of corresponding field (null if non exist).
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > setDefaultField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue)
Returns a pointer of corresponding field. If field did not exist, it is set to defaultValue if defaultValue is not null.
FWDATA_API::fwData::Object::csptr getConstField (const FieldNameType &name) const
Returns a pointer of corresponding field (null if non exist).
FWDATA_API const FieldMapType & getFields () const
Returns fields map.
FWDATA_API FieldNameVectorType getFieldNames () const
Returns vector of field names.
FWDATA_API void setField (const FieldNameType &name,::fwData::Object::sptr obj)
Register field with specified name. If the name does already exist, the matching field will be replaced.
FWDATA_API void setFields (const FieldMapType &fieldMap)
Replace the field map content.
FWDATA_API void removeField (const FieldNameType &name)
Removes field with specified name.
FWDATA_API void updateFields (const FieldMapType &fieldMap)
Updates the field map content with fieldMap. Duplicated name will be replaced.
virtual FWDATA_API void shallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void deepCopy (const ::fwData::Object::csptr &source)
Make a deep copy from the source Calling this method may invalidate any DumpLock, RescursiveLock or helper on the object. Prefer using fwData::Object::copy instead.
FWDATA_API void fieldShallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source)
A deep copy of fields (objects in m_children)
::fwCore::mt::ReadWriteMutex & getMutex ()
Returns the object's mutex.
Public Member Functions inherited from fwTools::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual ConstAttrType getConstAttribute (AttrNameType attrName) const
virtual AttrType getAttribute (AttrNameType attrName)
bool hasAttribute (AttrNameType attrName)
virtual void setAttribute (AttrNameType attrName, AttrType _obj)
virtual AttrNameVectorType getAttributeNames ()
virtual void __FWTOOLS_ATTRIBUTES_REGISTER_FUNC_NAME ()
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWDATA_API OffsetType computeStrides (SizeType size, size_t nbOfComponents, size_t sizeOfType)
Compute strides for given parameters.
Static Public Member Functions inherited from fwData::Object
static bool isTypeOf (const std::string &type)
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
Array (const Array &)
Not implemented.
const Array & operator= (const Array &)
Protected Member Functions inherited from fwData::Object
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
virtual FWDATA_API void cachedDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)=0
Internal-use methods to implement Object's deepCopy.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
__FWCORE_CLASS_TYPEDEFS ((fwID))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((fwID)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Protected Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual AttrRefType getAttributeRef (AttrNameType attrName)
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
OffsetType m_strides
::fwTools::Type m_type
::fwMemory::BufferObject::sptr m_bufferObject
SizeType m_size
size_t m_nbOfComponents
bool m_isBufferOwner
Protected Attributes inherited from fwData::Object
FieldMapType m_fields
Fields.
::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect object access.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwTools::DynamicAttributes< ::fwData::Object >
AttrMapType __FWTOOLS_ATTRIBUTE_MAP_NAME
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Public Attributes inherited from fwData::Object
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_MODIFIED_SIG = "modified"
Key in m_signals map of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_ADDED_FIELDS_SIG = "addedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_CHANGED_FIELDS_SIG = "changedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_REMOVED_FIELDS_SIG = "removedFields"
Type of signal m_sigModified.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwData::Object
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Provides a way to manage a view on a multidimentionnal array.
If the array own his buffer, it will perform the allocation, reallocation, destruction of the buffer. Else, this class will provide an array "view" of the buffer
Definition at line 32 of file fwData/include/fwData/Array.hpp.
Constructor & Destructor Documentation
fwData::Array::Array (::fwData::Object::Key key)
Constructor.
Parameters
key Private construction key
Definition at line 54 of file fwData/src/fwData/Array.cpp.
References clear().
Member Function Documentation
fwData::Array::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< Array > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Array)(::fwData::Object)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Array)(fwData::Object)).
fwData::Array::OffsetType fwData::Array::computeStrides (SizeType size, size_t nbOfComponents, size_t sizeOfType) static
Compute strides for given parameters.
Parameters
size Array size
nbOfComponents number of components
sizeOfType size of a component
Returns
Definition at line 38 of file fwData/src/fwData/Array.cpp.
Referenced by resize().
bool fwData::Array::empty () const virtual
Test whether array is empty.
Returns
Returns whether array is empty, ie. this->getSize() is an empty vector.
Definition at line 194 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::getBufferOffset (const ::fwData::Array::IndexType & id, size_t component, size_t sizeOfType) const
Compute offset in buffer for given parameters of type.
Parameters
id Item id
component Item component id
sizeOfType size of a component
Returns
buffer offset
Definition at line 305 of file fwData/src/fwData/Array.cpp.
References OSLM_ASSERT.
size_t fwData::Array::getElementSizeInBytes () const virtual
Get the size of one element of the array, ie. sizeof type * nbOfComponents.
Returns
One array elemet size in bytes.
Definition at line 201 of file fwData/src/fwData/Array.cpp.
References fwTools::Type::sizeOf().
bool fwData::Array::getIsBufferOwner () const virtual
Getter for array's buffer ownership.
Returns
Current array buffer ownership
Definition at line 271 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::getNumberOfComponents () const virtual
Getter for number of components.
Returns
Array's number of components
Definition at line 250 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::getNumberOfDimensions () const virtual
Getter for number of dimensions, ie. getSize().size()
Returns
Array's number of dimensions
Definition at line 257 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::getNumberOfElements () const virtual
Get the number of elements of type <getType()> in the array.
Returns
number of array elements
Definition at line 208 of file fwData/src/fwData/Array.cpp.
const ::fwData::Array::SizeType & fwData::Array::getSize () const virtual
Getter for the array size.
Returns
vector of size lengths in each dimension
Definition at line 223 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::getSizeInBytes () const virtual
Getter for the array view size.
Returns
Array view size in bytes.
Definition at line 215 of file fwData/src/fwData/Array.cpp.
References fwTools::Type::sizeOf().
const ::fwData::Array::OffsetType & fwData::Array::getStrides () const virtual
Getter for the array strides.
Returns
vector of steps in each dimension for array walking
Definition at line 230 of file fwData/src/fwData/Array.cpp.
fwTools::Type fwData::Array::getType () const virtual
Getter for array's type.
Returns
Type of array
Definition at line 298 of file fwData/src/fwData/Array.cpp.
size_t fwData::Array::resize (const ::fwTools::Type & type, const SizeType & size, size_t nbOfComponents, bool reallocate = false) throw (::fwData::Exception) virtual
Resizes and allocate (if needed) the array.
If no buffer is allocated and reallocate is true, this method will allocate a buffer and take it ownership.
If the combination of type, size and components parameters do not match anymore the size of the previously allocated buffer, a reallocation is needed. In this case :
if reallocate is true and if the Array do not own the buffer, an exception is thrown
else if reallocate is false, the array will update the view informations
else, the reallocation is performed.
Parameters
type Type of the array view
size Size of the array view
nbOfComponents Number of components of the array view, Min value : 1
reallocate If true, allow buffer reallocation
Returns
return the size of the array view
Exceptions
fwData::Exception
Definition at line 117 of file fwData/src/fwData/Array.cpp.
References computeStrides().
Referenced by cachedDeepCopy(), resize(), setNumberOfComponents(), and setType().
void fwData::Array::setIsBufferOwner (const bool own) virtual
Set array's buffer ownership.
Parameters
own New ownership value
Definition at line 264 of file fwData/src/fwData/Array.cpp.
void fwData::Array::setNumberOfComponents (size_t nb) virtual
Setter for array's number of components If the array has a buffer and owns it, the buffer will be reallocated.
Parameters
nb number of components
Definition at line 237 of file fwData/src/fwData/Array.cpp.
References resize().
void fwData::Array::setType (const std::string & type) virtual
Setter for array's type.
Parameters
type new array type
Definition at line 278 of file fwData/src/fwData/Array.cpp.
References resize().
The documentation for this class was generated from the following files:
fwData/include/fwData/Array.hpp
fwData/src/fwData/Array.cpp