fw4spl: ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv Class Reference
ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv Class Reference
This service forwards an event from all objects of composite to the composite .
#include <ObjToCompositeMsgForwarderSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ObjToCompositeMsgForwarderSrv)(::ctrlSelection::IWrapperSrv))
Protected Member Functions
virtual CTRLSELECTION_API void starting () throw (::fwTools::Failed)
Creates connections to receives signals from all the objects of the composite.
virtual CTRLSELECTION_API void stopping () throw (::fwTools::Failed)
Removes all the object connections.
virtual CTRLSELECTION_API void swapping () throw (::fwTools::Failed)
Does nothing.
virtual CTRLSELECTION_API void configuring () throw (::fwTools::Failed)
Configures the service.
virtual CTRLSELECTION_API void updating () throw (::fwTools::Failed)
Does nothing.
virtual CTRLSELECTION_API void info (std::ostream &_sstream)
Implements info method derived from IService. Print classname.
virtual CTRLSELECTION_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
Detailed Description
This service forwards an event from all objects of composite to the composite .
Date:
2011.
Definition at line 30 of file ObjToCompositeMsgForwarderSrv.hpp.
Member Function Documentation
void ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
Configures the service.
     <forward fromKey="objKey" onEvent="UPDATED_OBJECT" msgType="::fwComEd::ImageMsg" />
With this configuration : message with event "UPDATED_OBJECT" received from oject with key objKey" are forwarded to the composite. New message of type fwComEd::ImageMsg will be created and sent to the composite.
Note:
fromKey attibute can be "*", so the message can be received from any object.
Implements fwServices::IService.
Definition at line 151 of file ObjToCompositeMsgForwarderSrv.cpp.
References fwRuntime::ConfigurationElementContainer::getElements(), fwServices::IService::m_configuration, OSLM_INFO, fwRuntime::ConfigurationElementContainer::size(), SLM_ASSERT, SLM_FATAL_IF, and SLM_TRACE_FUNC.
void ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 39 of file ObjToCompositeMsgForwarderSrv.cpp.
References fwComEd::CompositeMsg::ADDED_KEYS, fwComEd::CompositeMsg::CHANGED_KEYS, fwCom::Connection::disconnect(), fwServices::IEditionService::notify(), OSLM_ASSERT, fwComEd::CompositeMsg::REMOVED_KEYS, fwData::Object::s_OBJECT_MODIFIED_SIG, fwServices::IService::s_RECEIVE_SLOT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
ObjToCompositeMsgForwarderSrv.hpp
ObjToCompositeMsgForwarderSrv.cpp