fw4spl: fwPacsIO::SeriesEnquirer Class Reference
fwPacsIO::SeriesEnquirer Class Reference
Reads DICOM series from pacs.
#include <SeriesEnquirer.hpp>
Public Types
typedef ::fwCom::Slot< void(const std::string &, unsigned int, const std::string &)> ProgressCallbackSlotType
typedef std::vector< std::string > InstanceUIDContainer
typedef std::vector< ::boost::filesystem::path > InstancePathContainer
Public Member Functions
virtual bool isA (const std::string &type) const
FWPACSIO_API SeriesEnquirer ()
Constructor.
FWPACSIO_API ~SeriesEnquirer ()
Destructor.
FWPACSIO_API void initialize (const std::string &applicationTitle, const std::string &peerHostName, unsigned short peerPort, const std::string &peerApplicationTitle, const std::string &moveApplicationTitle="", ProgressCallbackSlotType::sptr progressCallback=ProgressCallbackSlotType::sptr())
Initialize the connection.
FWPACSIO_API bool connect ()
Negotiate Association.
FWPACSIO_API void disconnect ()
Release association.
FWPACSIO_API bool pingPacs ()
Assemble and send C-ECHO request.
FWPACSIO_API bool isConnectedToPacs () const
Return true if there is an existing association.
FWPACSIO_API OFList< QRResponse * > findSeriesByPatientName (const std::string &name)
Find series by patient name.
FWPACSIO_API OFList< QRResponse * > findSeriesByDate (const std::string &fromDate, const std::string &toDate)
Find series by study date.
FWPACSIO_API OFList< QRResponse * > findSeriesByUID (const std::string &uid)
Find series by series UID.
FWPACSIO_API std::string findSOPInstanceUID (const std::string &seriesInstanceUID, unsigned int instanceNumber)
Find SOPInstanceUID of the specified instance.
FWPACSIO_API void pullSeriesUsingMoveRetrieveMethod (InstanceUIDContainer instanceUIDContainer)
Pull series using C-MOVE requests.
FWPACSIO_API void pullSeriesUsingGetRetrieveMethod (InstanceUIDContainer instanceUIDContainer)
Pull series using C-GET requests.
FWPACSIO_API void pullInstanceUsingMoveRetrieveMethod (const std::string &seriesInstanceUID, const std::string &sopInstanceUID)
Pull instance using C-MOVE requests.
FWPACSIO_API void pullInstanceUsingGetRetrieveMethod (const std::string &seriesInstanceUID, const std::string &sopInstanceUID)
Pull instance using C-GET requests.
FWPACSIO_API void pushSeries (const InstancePathContainer &pathContainer)
Push instances using C-STORE requests.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Attributes
static FWPACSIO_APIconst::fwCom::Slots::SlotKeyType s_PROGRESS_CALLBACK_SLOT = "CGetProgressCallback"
Protected Member Functions
FWPACSIO_API OFList< QRResponse * > sendFindRequest (DcmDataset dataset)
Send Find Request.
FWPACSIO_API OFCondition sendMoveRequest (DcmDataset dataset)
Send Move Request.
FWPACSIO_API OFCondition sendGetRequest (DcmDataset dataset)
Send Get Request.
FWPACSIO_API OFCondition sendStoreRequest (const ::boost::filesystem::path &path)
Send Store Request.
virtual FWPACSIO_API OFCondition handleMOVEResponse (const T_ASC_PresentationContextID presID, RetrieveResponse *response, OFBool &waitForNextResponse)
Handle MOVE Response (Override)
virtual FWPACSIO_API OFCondition handleSTORERequest (const T_ASC_PresentationContextID presID, DcmDataset *incomingObject, OFBool &continueCGETSession, Uint16 &cStoreReturnStatus)
Handle STORE Request (Override)
FWPACSIO_API Uint8 findUncompressedPC (const OFString &sopClass)
Find uncompressed presentation context.
Protected Attributes
std::string m_moveApplicationTitle
MOVE destination AE Title.
::boost::filesystem::path m_path
Path where the files must be saved.
ProgressCallbackSlotType::sptr m_progressCallback
Progress callback slot.
unsigned int m_instanceIndex
Dowloaded instance index.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Reads DICOM series from pacs.
Definition at line 29 of file SeriesEnquirer.hpp.
Member Function Documentation
OFList< QRResponse * > fwPacsIO::SeriesEnquirer::findSeriesByDate (const std::string & fromDate, const std::string & toDate)
Find series by study date.
Parameters
[in] fromDate Beginning date
[in] toDate Ending date
Returns
dcmtk response list
Definition at line 312 of file SeriesEnquirer.cpp.
References sendFindRequest().
OFList< QRResponse * > fwPacsIO::SeriesEnquirer::findSeriesByPatientName (const std::string & name)
Find series by patient name.
Parameters
[in] name Patient name
Returns
dcmtk response list
Definition at line 275 of file SeriesEnquirer.cpp.
References sendFindRequest().
OFList< QRResponse * > fwPacsIO::SeriesEnquirer::findSeriesByUID (const std::string & uid)
Find series by series UID.
Parameters
[in] uid Series UID
Returns
dcmtk response list
Definition at line 349 of file SeriesEnquirer.cpp.
References sendFindRequest().
std::string fwPacsIO::SeriesEnquirer::findSOPInstanceUID (const std::string & seriesInstanceUID, unsigned int instanceNumber)
Find SOPInstanceUID of the specified instance.
Parameters
[in] seriesInstanceUID Series instance UID
[in] instanceNumber Instance number
Returns
SOPInstanceUID corresponding to the instanceNumber
Definition at line 384 of file SeriesEnquirer.cpp.
References sendFindRequest().
Uint8 fwPacsIO::SeriesEnquirer::findUncompressedPC (const OFString & sopClass) protected
Find uncompressed presentation context.
Parameters
[in] sopClass SOP class which needs the presentation context
Definition at line 49 of file SeriesEnquirer.cpp.
Referenced by sendFindRequest(), sendGetRequest(), sendMoveRequest(), and sendStoreRequest().
void fwPacsIO::SeriesEnquirer::initialize (const std::string & applicationTitle, const std::string & peerHostName, unsigned short peerPort, const std::string & peerApplicationTitle, const std::string & moveApplicationTitle = "", ProgressCallbackSlotType::sptr progressCallback = ProgressCallbackSlotType::sptr())
Initialize the connection.
Parameters
[in] applicationTitle Local application title
[in] peerHostName Pacs host name
[in] peerPort Pacs port
[in] peerApplicationTitle Pacs application title
[in] path Local dicom folder path
[in] moveApplicationTitle Move application title
[in] progressCallback Progress callback
Definition at line 66 of file SeriesEnquirer.cpp.
References fwTools::System::getTemporaryFolder(), fwDcmtkTools::Dictionary::loadDictionary(), m_moveApplicationTitle, m_path, and m_progressCallback.
void fwPacsIO::SeriesEnquirer::pullInstanceUsingGetRetrieveMethod (const std::string & seriesInstanceUID, const std::string & sopInstanceUID)
Pull instance using C-GET requests.
Parameters
[in] seriesInstanceUID Series instance UID
[in] sopInstanceUID SOP Instance UID
Definition at line 515 of file SeriesEnquirer.cpp.
References m_instanceIndex, sendGetRequest(), and SLM_TRACE.
void fwPacsIO::SeriesEnquirer::pullInstanceUsingMoveRetrieveMethod (const std::string & seriesInstanceUID, const std::string & sopInstanceUID)
Pull instance using C-MOVE requests.
Parameters
[in] seriesInstanceUID Series instance UID
[in] sopInstanceUID SOP Instance UID
Definition at line 483 of file SeriesEnquirer.cpp.
References m_instanceIndex, sendMoveRequest(), and SLM_TRACE.
void fwPacsIO::SeriesEnquirer::pullSeriesUsingGetRetrieveMethod (InstanceUIDContainer instanceUIDContainer)
Pull series using C-GET requests.
Parameters
[in] instanceUIDContainer Series instance UID container
Definition at line 451 of file SeriesEnquirer.cpp.
References m_instanceIndex, sendGetRequest(), and SLM_TRACE.
void fwPacsIO::SeriesEnquirer::pullSeriesUsingMoveRetrieveMethod (InstanceUIDContainer instanceUIDContainer)
Pull series using C-MOVE requests.
Parameters
[in] instanceUIDContainer Series instance UID container
Definition at line 418 of file SeriesEnquirer.cpp.
References m_instanceIndex, sendMoveRequest(), and SLM_TRACE.
void fwPacsIO::SeriesEnquirer::pushSeries (const InstancePathContainer & pathContainer)
Push instances using C-STORE requests.
Parameters
[in] pathContainer Instance paths container
Definition at line 547 of file SeriesEnquirer.cpp.
References m_instanceIndex, m_progressCallback, sendStoreRequest(), and SLM_TRACE.
OFList< QRResponse * > fwPacsIO::SeriesEnquirer::sendFindRequest (DcmDataset dataset) protected
Send Find Request.
Parameters
[in] dataset Request dataset
Returns
dcmtk response list
Definition at line 197 of file SeriesEnquirer.cpp.
References findUncompressedPC().
Referenced by findSeriesByDate(), findSeriesByPatientName(), findSeriesByUID(), and findSOPInstanceUID().
OFCondition fwPacsIO::SeriesEnquirer::sendGetRequest (DcmDataset dataset) protected
Send Get Request.
Parameters
[in] dataset Request dataset
Returns
OFTrue on success
Definition at line 235 of file SeriesEnquirer.cpp.
References findUncompressedPC(), m_path, SLM_ASSERT, and SLM_WARN.
Referenced by pullInstanceUsingGetRetrieveMethod(), and pullSeriesUsingGetRetrieveMethod().
OFCondition fwPacsIO::SeriesEnquirer::sendMoveRequest (DcmDataset dataset) protected
Send Move Request.
Parameters
[in] dataset Request dataset
Returns
OFTrue on success
Definition at line 217 of file SeriesEnquirer.cpp.
References findUncompressedPC(), m_moveApplicationTitle, m_path, SLM_ASSERT, and SLM_WARN_IF.
Referenced by pullInstanceUsingMoveRetrieveMethod(), and pullSeriesUsingMoveRetrieveMethod().
OFCondition fwPacsIO::SeriesEnquirer::sendStoreRequest (const ::boost::filesystem::path & path) protected
Send Store Request.
Parameters
[in] path File path
Returns
OFTrue on success
Definition at line 256 of file SeriesEnquirer.cpp.
References findUncompressedPC(), OSLM_WARN, and SLM_WARN.
Referenced by pushSeries().
The documentation for this class was generated from the following files:
SeriesEnquirer.hpp
SeriesEnquirer.cpp