fw4spl: fwMedDataTools::helper::SeriesDB Class Reference
fwMedDataTools::helper::SeriesDB Class Reference
Defines an helper to modify an fwMedData::SeriesDB and create in parallel the message to announce this modification.
#include <SeriesDB.hpp>
Public Member Functions
FWMEDDATATOOLS_API SeriesDB (::fwMedData::SeriesDB::wptr seriesDB)
Constructor. Initialize parameters.
FWMEDDATATOOLS_API ~SeriesDB ()
Destrucotr. Do nothing.
FWMEDDATATOOLS_API void add (::fwMedData::Series::sptr newSeries)
Add a Series in the SeriesDB.
FWMEDDATATOOLS_API void remove (::fwMedData::Series::sptr oldSeries)
Remove a Series in the SeriesDB.
FWMEDDATATOOLS_API void clear ()
Clear all series in the SeriesDB.
FWMEDDATATOOLS_API void merge (::fwMedData::SeriesDB::sptr seriesDBIn)
Merge seriesDBIn all series from seriesDBIn to the SeriesDB.
FWMEDDATATOOLS_API void notify ()
Send the signal of modification.
Detailed Description
Defines an helper to modify an fwMedData::SeriesDB and create in parallel the message to announce this modification.
Definition at line 23 of file core/fwMedDataTools/include/fwMedDataTools/helper/SeriesDB.hpp.
Member Function Documentation
void fwMedDataTools::helper::SeriesDB::add (::fwMedData::Series::sptr newSeries)
Add a Series in the SeriesDB.
Parameters
[in] newSeries object to add in the SeriesDB
Prepare the signal to announce the modification.
Definition at line 35 of file core/fwMedDataTools/src/fwMedDataTools/helper/SeriesDB.cpp.
References OSLM_ASSERT.
Referenced by ioDicom::SFilterSelectionEditor::addFilter(), ctrlSelection::SManage::addOrSwap(), ctrlSelection::SManage::clear(), ioGdcm::SSeriesDBWriter::getIOPathType(), fwGdcmIO::reader::SeriesDB::isDicomDirAvailable(), fwDcmtkIO::SeriesDBReader::isDicomDirAvailable(), merge(), uiMedDataQt::editor::SSeries::onExportClicked(), fwGdcmIO::reader::SeriesDB::readDicomSeries(), fwDcmtkIO::SeriesDBReader::readDicomSeries(), uiMedDataQt::action::SInitNewSeries::updating(), ioDicom::SSeriesDBMerger::updating(), ioGdcm::SSeriesDBWriter::updating(), uiMedDataQt::action::SExportSeries::updating(), ioData::SAttachmentSeriesReader::updating(), and activities::SActivitySequencer::updating().
void fwMedDataTools::helper::SeriesDB::clear ()
Clear all series in the SeriesDB.
Prepare the signal to announce the modification.
Definition at line 66 of file core/fwMedDataTools/src/fwMedDataTools/helper/SeriesDB.cpp.
Referenced by ioDicom::SFilterSelectionEditor::addFilter(), ctrlSelection::SManage::clear(), ioGdcm::SDicomSeriesDBReader::getSelectorDialogTitle(), ioGdcm::SSeriesDBReader::getSelectorDialogTitle(), ioDicom::SSliceIndexDicomEditor::readImage(), ioPacs::SSliceIndexDicomPullerEditor::readImage(), ioGdcm::SDicomSeriesConverter::updating(), ioGdcm::SDicomSeriesDBReader::updating(), and ioVTK::SSeriesDBReader::updating().
void fwMedDataTools::helper::SeriesDB::merge (::fwMedData::SeriesDB::sptr seriesDBIn)
Merge seriesDBIn all series from seriesDBIn to the SeriesDB.
Prepare the signal to announce the modification.
Definition at line 78 of file core/fwMedDataTools/src/fwMedDataTools/helper/SeriesDB.cpp.
References add().
Referenced by ioPacs::SSeriesPuller::readLocalSeries(), ioGdcm::SDicomSeriesConverter::updating(), ioITK::SInrSeriesDBReader::updating(), ioDicomWeb::SSeriesPuller::updating(), and uiIO::action::SSeriesDBMerger::updating().
void fwMedDataTools::helper::SeriesDB::remove (::fwMedData::Series::sptr oldSeries)
Remove a Series in the SeriesDB.
Parameters
[in] oldSeries object to remove from the SeriesDB.
Prepare the signal to announce the modification.
Definition at line 50 of file core/fwMedDataTools/src/fwMedDataTools/helper/SeriesDB.cpp.
References OSLM_ASSERT.
Referenced by ctrlSelection::SManage::remove(), and ctrlSelection::SManage::removeIfPresent().
The documentation for this class was generated from the following files:
core/fwMedDataTools/include/fwMedDataTools/helper/SeriesDB.hpp
core/fwMedDataTools/src/fwMedDataTools/helper/SeriesDB.cpp