fw4spl: fwMDSemanticPatch::V09ALA::V10::fwData::Image Class Reference
fwMDSemanticPatch::V09ALA::V10::fwData::Image Class Reference
Patch the 'landmarks' field of an image from version 'V9ALA' to 'V10' within 'MedicalData' context.
#include <Image.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWMDSEMANTICPATCH_API Image ()
Constructor.
FWMDSEMANTICPATCH_API ~Image ()
Destructor.
FWMDSEMANTICPATCH_API Image (const Image &cpy)
Copy constructor.
virtual FWMDSEMANTICPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions) override
Applies patch.
Public Member Functions inherited from fwAtomsPatch::ISemanticPatch
FWATOMSPATCH_API ISemanticPatch ()
Constructor.
FWATOMSPATCH_API ISemanticPatch (const ISemanticPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~ISemanticPatch ()
Destructor.
virtual FWATOMSPATCH_API void apply (const std::shared_ptr< ::fwAtoms::Object > &previous, const std::shared_ptr< ::fwAtoms::Object > &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions) override
Applies modifications between given objects.
virtual FWATOMSPATCH_API bool isApplicable (const std::string &context, const std::string &originVersion, const std::string &targetVersion) const
Returns true if patch is applicable into the context from origin to target versions.
Public Member Functions inherited from fwAtomsPatch::IPatch
FWATOMSPATCH_API IPatch ()
Constructor. Does nothing.
FWATOMSPATCH_API IPatch (const IPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IPatch ()
Destructor. Does nothing.
virtual FWATOMSPATCH_API const std::string & getOriginClassname () const
Returns the origin classname of the object.
virtual FWATOMSPATCH_API const std::string & getOriginVersion () const
Returns the origin version of the object.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::ISemanticPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwAtomsPatch::IPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwAtomsPatch::IPatch
typedef std::map< ::fwAtoms::Object::sptr,::fwAtoms::Object::sptr > NewVersionsType
Protected Types inherited from fwAtomsPatch::ISemanticPatch
typedef std::vector< Context > ContextVectorType
Protected Member Functions inherited from fwAtomsPatch::ISemanticPatch
virtual FWATOMSPATCH_API void addContext (const std::string &context, const std::string &originVersion, const std::string &targetVersion)
Add a context where the patch can be applied.
Protected Attributes inherited from fwAtomsPatch::ISemanticPatch
mutable::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect concurrent access for m_contexts.
ContextVectorType m_contexts
Vector used to store the contexts where the patch can be applied.
Protected Attributes inherited from fwAtomsPatch::IPatch
std::string m_originClassname
Origin classname of the object.
std::string m_originVersion
Origin version of the object.
Detailed Description
Patch the 'landmarks' field of an image from version 'V9ALA' to 'V10' within 'MedicalData' context.
Definition at line 24 of file patch/fwMDSemanticPatch/include/fwMDSemanticPatch/V09ALA/V10/fwData/Image.hpp.
Member Function Documentation
void fwMDSemanticPatch::V09ALA::V10::fwData::Image::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) override virtual
Applies patch.
Converts the "m_imageLandmarksId" field from a fwData::PointList to a fwData::Landmarks in "m_landmarksId" .
Implements fwAtomsPatch::IPatch.
Definition at line 54 of file patch/fwMDSemanticPatch/src/fwMDSemanticPatch/V09ALA/V10/fwData/Image.cpp.
References fwTools::UUID::generateUUID(), fwAtomsPatch::StructuralCreatorDB::getDefault(), fwAtoms::Boolean::New(), fwAtoms::Numeric::New(), fwAtoms::String::New(), and SLM_ASSERT.
The documentation for this class was generated from the following files:
patch/fwMDSemanticPatch/include/fwMDSemanticPatch/V09ALA/V10/fwData/Image.hpp
patch/fwMDSemanticPatch/src/fwMDSemanticPatch/V09ALA/V10/fwData/Image.cpp