fw4spl: fwData::ProcessObject Class Reference
fwData::ProcessObject Class Reference
Provides the notion of Process Object: object having inputs and outputs.
#include <ProcessObject.hpp>
Public Types
typedef std::string ParamNameType
typedef std::vector< std::string > ParamNameVectorType
typedef std::map< ParamNameType,::fwData::Object::sptr > ProcessObjectMapType
Public Types inherited from fwData::Object
typedef ::fwData::factory::Key Key
typedef std::string FieldNameType
typedef std::vector< FieldNameType > FieldNameVectorType
typedef ::boost::unordered_map< FieldNameType,::fwData::Object::sptr > FieldMapType
typedef ::boost::unordered_map< ::fwData::Object::csptr,::fwData::Object::sptr > DeepCopyCacheType
typedef ::fwCom::Signal< void() > ModifiedSignalType
Type of signal m_sigModified.
typedef std::map< std::string,::fwData::Object::sptr > FieldsContainerType
Type of signal m_sigModified.
typedef ::fwCom::Signal< void(FieldsContainerType) > AddedFieldsSignalType
Type of signal when objects are added.
typedef ::fwCom::Signal< void(FieldsContainerType, FieldsContainerType) > ChangedFieldsSignalType
Type of signal when objects are changed (newObjects, oldObjects)
typedef ::fwCom::Signal< void(FieldsContainerType) > RemovedFieldsSignalType
Type of signal when objects are removed.
Public Types inherited from fwTools::DynamicAttributes< ::fwData::Object >
typedef std::string AttrNameType
typedef std::shared_ptr< ::fwData::Object > AttrType
typedef std::vector< AttrNameType > AttrNameVectorType
typedef ::boost::reference_wrapper< AttrType > AttrRefType
typedef std::map< AttrNameType, AttrRefType > AttrMapType
typedef std::shared_ptr< const ::fwData::Object > ConstAttrType
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((ProcessObject)(::fwData::Object))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< ProcessObject >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((ProcessObject)(::fwData::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWDATA_API ProcessObject (::fwData::Object::Key key)
Constructor.
virtual FWDATA_API ~ProcessObject ()
Destructor.
FWDATA_API::fwData::Object::sptr getInput (const ParamNameType &name)
Retrieves the input data associated with specified name (null if non exist).
template<class OBJECTTYPE >
OBJECTTYPE::sptr getInput (const ParamNameType &name)
Retrieves the input data associated with specified name type OBJECTTYPE (null if non exist).
FWDATA_API::fwData::Object::sptr getOutput (const ParamNameType &name)
Retrieves the output data associated with specified name (null if non exist).
template<class OBJECTTYPE >
OBJECTTYPE::sptr getOutput (const ParamNameType &name)
Retrieves the output data associated with specified name type OBJECTTYPE (null if non exist).
FWDATA_API void setInputValue (const ParamNameType &name,::fwData::Object::sptr object)
Register input value with specified name. If the name does already exist, the matching value will be replaced.
FWDATA_API void setOutputValue (const ParamNameType &name,::fwData::Object::sptr object)
Register output value with specified name. If the name does already exist, the matching value will be replaced.
FWDATA_API ParamNameVectorType getInputsParamNames () const
Returns vector of input parameters names.
FWDATA_API ParamNameVectorType getOutputsParamNames () const
Returns vector of output parameters names.
FWDATA_API void clearInputs ()
Unregister all inputs parameters.
FWDATA_API void clearOutputs ()
Unregister all output parameters.
FWDATA_API void shallowCopy (const Object::csptr &source)
Defines shallow copy.
FWDATA_API void cachedDeepCopy (const Object::csptr &source, DeepCopyCacheType &cache)
Defines deep copy.
const ProcessObjectMapType & getInputs () const
Retrieve the input data.
void setInputs (const ProcessObjectMapType &val)
Retrieve the input data.
const ProcessObjectMapType & getOutputs () const
void setOutputs (const ProcessObjectMapType &val)
Public Member Functions inherited from fwData::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwTools::Object))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwTools::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWDATA_API::fwData::Object::sptr getField (const FieldNameType &name,::fwData::Object::sptr defaultValue=::fwData::Object::sptr()) const
Returns a pointer of corresponding field (null if non exist).
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > setDefaultField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue)
Returns a pointer of corresponding field. If field did not exist, it is set to defaultValue if defaultValue is not null.
FWDATA_API::fwData::Object::csptr getConstField (const FieldNameType &name) const
Returns a pointer of corresponding field (null if non exist).
FWDATA_API const FieldMapType & getFields () const
Returns fields map.
FWDATA_API FieldNameVectorType getFieldNames () const
Returns vector of field names.
FWDATA_API void setField (const FieldNameType &name,::fwData::Object::sptr obj)
Register field with specified name. If the name does already exist, the matching field will be replaced.
FWDATA_API void setFields (const FieldMapType &fieldMap)
Replace the field map content.
FWDATA_API void removeField (const FieldNameType &name)
Removes field with specified name.
FWDATA_API void updateFields (const FieldMapType &fieldMap)
Updates the field map content with fieldMap. Duplicated name will be replaced.
virtual FWDATA_API void shallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void deepCopy (const ::fwData::Object::csptr &source)
Make a deep copy from the source Calling this method may invalidate any DumpLock, RescursiveLock or helper on the object. Prefer using fwData::Object::copy instead.
FWDATA_API void fieldShallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source)
A deep copy of fields (objects in m_children)
::fwCore::mt::ReadWriteMutex & getMutex ()
Returns the object's mutex.
Public Member Functions inherited from fwTools::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual ConstAttrType getConstAttribute (AttrNameType attrName) const
virtual AttrType getAttribute (AttrNameType attrName)
bool hasAttribute (AttrNameType attrName)
virtual void setAttribute (AttrNameType attrName, AttrType _obj)
virtual AttrNameVectorType getAttributeNames ()
virtual void __FWTOOLS_ATTRIBUTES_REGISTER_FUNC_NAME ()
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwData::Object
static bool isTypeOf (const std::string &type)
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
FWDATA_API ParamNameVectorType getParamNames (const ProcessObjectMapType &params) const
Returns vector of parameters names from params map.
FWDATA_API void setValue (const ParamNameType &name,::fwData::Object::sptr object, ProcessObjectMapType &params)
Register value with specified name in params map. If the name does already exist, the matching value will be replaced.
FWDATA_API::fwData::Object::sptr getValue (const ParamNameType &name, const ProcessObjectMapType &params)
Retrieves data associated with specified name in params map (null if non exist).
FWDATA_API void clearParams (ProcessObjectMapType &params)
Unregister all parameters in params map.
Protected Member Functions inherited from fwData::Object
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
virtual FWDATA_API void cachedDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)=0
Internal-use methods to implement Object's deepCopy.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
__FWCORE_CLASS_TYPEDEFS ((fwID))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((fwID)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Protected Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual AttrRefType getAttributeRef (AttrNameType attrName)
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
ProcessObjectMapType m_inputs
Inputs values map.
ProcessObjectMapType m_outputs
Outputs values map.
Protected Attributes inherited from fwData::Object
FieldMapType m_fields
Fields.
::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect object access.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwTools::DynamicAttributes< ::fwData::Object >
AttrMapType __FWTOOLS_ATTRIBUTE_MAP_NAME
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Public Attributes inherited from fwData::Object
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_MODIFIED_SIG = "modified"
Key in m_signals map of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_ADDED_FIELDS_SIG = "addedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_CHANGED_FIELDS_SIG = "changedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_REMOVED_FIELDS_SIG = "removedFields"
Type of signal m_sigModified.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwData::Object
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Provides the notion of Process Object: object having inputs and outputs.
Definition at line 27 of file ProcessObject.hpp.
Constructor & Destructor Documentation
fwData::ProcessObject::ProcessObject (::fwData::Object::Key key)
Constructor.
Parameters
key Private construction key
Definition at line 23 of file src/fwData/ProcessObject.cpp.
Member Function Documentation
fwData::ProcessObject::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwData::factory::New< ProcessObject > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((ProcessObject)(::fwData::Object)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((ProcessObject)(fwData::Object)).
fwData::Object::sptr fwData::ProcessObject::getInput (const ParamNameType & name)
Retrieves the input data associated with specified name (null if non exist).
Parameters
[in] name Input name
Returns
null sptr if input is not found
Definition at line 48 of file src/fwData/ProcessObject.cpp.
References getValue(), and m_inputs.
template<class OBJECTTYPE > OBJECTTYPE::sptr fwData::ProcessObject::getInput (const ParamNameType & name) inline
Retrieves the input data associated with specified name type OBJECTTYPE (null if non exist).
Parameters
[in] name Input name
Returns
null sptr if input is not found
Definition at line 181 of file ProcessObject.hpp.
fwData::Object::sptr fwData::ProcessObject::getOutput (const ParamNameType & name)
Retrieves the output data associated with specified name (null if non exist).
Parameters
[in] name Output name
Returns
null sptr if output is not found
Definition at line 55 of file src/fwData/ProcessObject.cpp.
References getValue(), and m_outputs.
template<class OBJECTTYPE > OBJECTTYPE::sptr fwData::ProcessObject::getOutput (const ParamNameType & name) inline
Retrieves the output data associated with specified name type OBJECTTYPE (null if non exist).
Parameters
[in] name Output name
Returns
null sptr if output is not found
Definition at line 189 of file ProcessObject.hpp.
const ProcessObject::ProcessObjectMapType & fwData::ProcessObject::getOutputs () const inline
the output data.
Definition at line 210 of file ProcessObject.hpp.
fwData::Object::sptr fwData::ProcessObject::getValue (const ParamNameType & name, const ProcessObjectMapType & params) protected
Retrieves data associated with specified name in params map (null if non exist).
Parameters
[in] name Param name
params parameters map containing the data
Returns
null sptr if param is not found
Definition at line 35 of file src/fwData/ProcessObject.cpp.
Referenced by getInput(), and getOutput().
void fwData::ProcessObject::setInputValue (const ParamNameType & name, ::fwData::Object::sptr object)
Register input value with specified name. If the name does already exist, the matching value will be replaced.
Parameters
[in] name Input name
[in] object Input value
Definition at line 74 of file src/fwData/ProcessObject.cpp.
References m_inputs, and setValue().
void fwData::ProcessObject::setOutputs (const ProcessObjectMapType & val) inline
the output data.
Definition at line 217 of file ProcessObject.hpp.
void fwData::ProcessObject::setOutputValue (const ParamNameType & name, ::fwData::Object::sptr object)
Register output value with specified name. If the name does already exist, the matching value will be replaced.
Parameters
[in] name Output name
[in] object Output value
Definition at line 81 of file src/fwData/ProcessObject.cpp.
References m_outputs, and setValue().
void fwData::ProcessObject::setValue (const ParamNameType & name, ::fwData::Object::sptr object, ProcessObjectMapType & params) protected
Register value with specified name in params map. If the name does already exist, the matching value will be replaced.
Parameters
[in] name Param name
[in] object Param
params parameters map to insert object
Definition at line 62 of file src/fwData/ProcessObject.cpp.
Referenced by setInputValue(), and setOutputValue().
The documentation for this class was generated from the following files:
ProcessObject.hpp
src/fwData/ProcessObject.cpp