fw4spl: fwGdcmIO::helper::DicomSeries Class Reference
fwGdcmIO::helper::DicomSeries Class Reference
DicomSeries Helper. This class is used to generate/fill DicomSeries.
#include <DicomSeries.hpp>
Public Types
typedef std::vector< std::string > FilenameContainerType
typedef std::vector< std::shared_ptr< ::fwMedData::DicomSeries > > DicomSeriesContainerType
Public Member Functions
FWGDCMIO_API DicomSeries ()
Constructor.
FWGDCMIO_API ~DicomSeries ()
Destructor.
FWGDCMIO_API DicomSeriesContainerType read (FilenameContainerType &filenames, const std::shared_ptr< ::fwJobs::Observer > &readerObserver, const std::shared_ptr< ::fwJobs::Observer > &completeSeriesObserver)
Read DicomSeries from paths.
FWGDCMIO_API void complete (DicomSeriesContainerType &seriesDB, const std::shared_ptr< ::fwJobs::Observer > &completeSeriesObserver)
Fill DicomSeries information for series generated using DICOMDIR helper.
FWGDCMIO_API std::shared_ptr< ::fwMedData::DicomSeries > createBlob (FilenameContainerType &filenames)
Create DicomSeries containing a blob.
Protected Types
typedef std::map< std::string, std::shared_ptr< ::fwMedData::Patient > > PatientMapType
typedef std::map< std::string, std::shared_ptr< ::fwMedData::Study > > StudyMapType
typedef std::map< std::string, std::shared_ptr< ::fwMedData::Equipment > > EquipmentMapType
Protected Member Functions
void fillSeries (DicomSeriesContainerType &seriesDB, const std::shared_ptr< ::fwJobs::Observer > &completeSeriesObserver)
Fill series with information contained in first instance.
DicomSeriesContainerType splitFiles (FilenameContainerType &filenames, const std::shared_ptr< ::fwJobs::Observer > &readerObserver)
Create DicomSeries from list of files. Every instance is read in order to retrieve instance information regarding the matching series.
void createSeries (DicomSeriesContainerType &seriesDB, const ::gdcm::Scanner &scanner, const std::string &filename)
Create a series from the dataset and store it in the series map.
std::shared_ptr< ::fwMedData::Patient > createPatient (const ::gdcm::Scanner &scanner, const std::string &filename)
Create a patient from the dataset and store it in the patient map.
std::shared_ptr< ::fwMedData::Study > createStudy (const ::gdcm::Scanner &scanner, const std::string &filename)
Create a study from the dataset and store it in the study map.
std::shared_ptr< ::fwMedData::Equipment > createEquipment (const ::gdcm::Scanner &scanner, const std::string &filename)
Create an equipment from the dataset and store it in the equipment map.
Protected Attributes
PatientMapType m_patientMap
Patient Map.
StudyMapType m_studyMap
Study Map.
EquipmentMapType m_equipmentMap
Equipment Map.
Detailed Description
DicomSeries Helper. This class is used to generate/fill DicomSeries.
It can be used to read DicomSeries from a list of files (using read function).
It can be used to complete DicomSeries that have been created using the DicomDir helper (using complete function).
Definition at line 49 of file io/fwGdcmIO/include/fwGdcmIO/helper/DicomSeries.hpp.
Member Function Documentation
void fwGdcmIO::helper::DicomSeries::complete (DicomSeriesContainerType & seriesDB, const std::shared_ptr< ::fwJobs::Observer > & completeSeriesObserver)
Fill DicomSeries information for series generated using DICOMDIR helper.
Parameters
[in,out] seriesDB List of DicomSeries that must be completed with information
[in] completeSeriesObserver complete series observer
Definition at line 97 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References fillSeries(), and SLM_ERROR.
Referenced by fwGdcmIO::reader::SeriesDB::readDicomSeries().
fwMedData::DicomSeries::sptr fwGdcmIO::helper::DicomSeries::createBlob (FilenameContainerType & filenames)
Create DicomSeries containing a blob.
Parameters
[in] filenames instance paths
Definition at line 165 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References fwMedData::DicomSeries::BLOB.
Referenced by fwGdcmIO::reader::SeriesDB::readDicomSeries().
fwMedData::Equipment::sptr fwGdcmIO::helper::DicomSeries::createEquipment (const ::gdcm::Scanner & scanner, const std::string & filename) protected
Create an equipment from the dataset and store it in the equipment map.
Parameters
[in] scanner GDCM Scanner used to read information
[in] filename Filename from which the information must be read
Definition at line 456 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References m_equipmentMap.
Referenced by fillSeries().
fwMedData::Patient::sptr fwGdcmIO::helper::DicomSeries::createPatient (const ::gdcm::Scanner & scanner, const std::string & filename) protected
Create a patient from the dataset and store it in the patient map.
Parameters
[in] scanner GDCM Scanner used to read information
[in] filename Filename from which the information must be read
Definition at line 370 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References m_patientMap.
Referenced by fillSeries().
void fwGdcmIO::helper::DicomSeries::createSeries (DicomSeriesContainerType & seriesDB, const ::gdcm::Scanner & scanner, const std::string & filename) protected
Create a series from the dataset and store it in the series map.
Parameters
[in,out] seriesDB List of DicomSeries that must be completed with information
[in] scanner GDCM Scanner used to read information
[in] filename Filename from which the information must be read
Definition at line 300 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References fwMedData::DicomSeries::PATHS.
Referenced by splitFiles().
fwMedData::Study::sptr fwGdcmIO::helper::DicomSeries::createStudy (const ::gdcm::Scanner & scanner, const std::string & filename) protected
Create a study from the dataset and store it in the study map.
Parameters
[in] scanner GDCM Scanner used to read information
[in] filename Filename from which the information must be read
Definition at line 409 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References m_studyMap.
Referenced by fillSeries().
void fwGdcmIO::helper::DicomSeries::fillSeries (DicomSeriesContainerType & seriesDB, const std::shared_ptr< ::fwJobs::Observer > & completeSeriesObserver) protected
Fill series with information contained in first instance.
Parameters
[in,out] seriesDB List of DicomSeries that must be completed with information
[in] completeSeriesObserver complete series observer
Definition at line 230 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References createEquipment(), createPatient(), createStudy(), m_equipmentMap, m_patientMap, m_studyMap, OSLM_ASSERT, and SLM_ERROR.
Referenced by complete(), and read().
DicomSeries::DicomSeriesContainerType fwGdcmIO::helper::DicomSeries::read (FilenameContainerType & filenames, const std::shared_ptr< ::fwJobs::Observer > & readerObserver, const std::shared_ptr< ::fwJobs::Observer > & completeSeriesObserver)
Read DicomSeries from paths.
Parameters
[in] filenames instance paths
[in] readerObserver reader observer
[in] completeSeriesObserver complete series observer
Returns
container containing DicomSeries
Definition at line 86 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References fillSeries(), and splitFiles().
Referenced by fwGdcmIO::reader::SeriesDB::readDicomSeries().
DicomSeries::DicomSeriesContainerType fwGdcmIO::helper::DicomSeries::splitFiles (FilenameContainerType & filenames, const std::shared_ptr< ::fwJobs::Observer > & readerObserver) protected
Create DicomSeries from list of files. Every instance is read in order to retrieve instance information regarding the matching series.
Parameters
[in] filenames List of files
[in] readerObserver reader observer
Definition at line 187 of file io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp.
References createSeries(), and OSLM_ASSERT.
Referenced by read().
The documentation for this class was generated from the following files:
io/fwGdcmIO/include/fwGdcmIO/helper/DicomSeries.hpp
io/fwGdcmIO/src/fwGdcmIO/helper/DicomSeries.cpp