fw4spl: fwGdcmIO::writer::Series Class Reference
fwGdcmIO::writer::Series Class Reference
This class handles DICOM files writing. It defines needs of data storage and delegates writing to appropriate tools. It manages all related data of one patient.
#include <Series.hpp>
Public Types
enum FiducialsExportMode { SPATIAL_FIDUCIALS = 1, COMPREHENSIVE_SR = 2, COMPREHENSIVE_3D_SR = 3 }
typedef std::map< std::string, std::shared_ptr< ::fwGdcmIO::container::DicomInstance > > DicomInstanceMapType
Public Types inherited from fwDataIO::writer::GenericObjectWriter< ::fwMedData::Series >
typedef ::fwMedData::Series DataType
the object type related
Public Types inherited from fwDataIO::writer::IObjectWriter
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< void() > CancelCallback
typedef ::fwDataIO::writer::factory::Key Key
Public Types inherited from fwTools::ProgressAdviser
typedef ::boost::signals2::signal< void(float, std::string) > ProgessSignal
define a boost signal signature for the ProgessHandler
typedef ProgessSignal::slot_type ProgessHandler
define the ProgessHandler type
Public Member Functions
virtual bool isA (const std::string &type) const
FWGDCMIO_API Series (::fwDataIO::writer::IObjectWriter::Key key)
Constructor.
FWGDCMIO_API ~Series ()
Destructor.
FWGDCMIO_API void write () throw (::fwGdcmIO::exception::Failed)
Load and start appropriate writing tools. In addition, it creates an adapted folder tree where DICOM files will be stored. It manages writing of the following general DICOM modules : patient, study and series.
FWGDCMIO_API std::string extension ()
Do nothing.
const FiducialsExportMode & getFiducialsExportMode () const
Get Fiducials Export Mode.
void setFiducialsExportMode (const FiducialsExportMode &fiducialsExportMode)
Set Fiducials Export Mode);.
Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwMedData::Series >
GenericObjectWriter ()
Constructor. Do nothing.
virtual ~GenericObjectWriter ()
Destructor. Do nothing.
virtual void setObject (::fwTools::Object::sptr obj)
m_object setter.
virtual std::shared_ptr< DataType > getConcreteObject ()
m_object getter.
Public Member Functions inherited from fwDataIO::writer::IObjectWriter
virtual FWDATAIO_API void setLocation (const ::fwData::location::ILocation::sptr location)
m_location setter.
virtual FWDATAIO_API::fwData::location::ILocation::sptr getLocation ()
m_location getter.
virtual FWDATAIO_API::fwTools::Object::sptr getObject ()
m_object getter.
virtual FWDATAIO_API void cancel ()
Requests writer abortion.
virtual FWDATAIO_API std::shared_ptr< ::fwJobs::IJob > getJob () const
Returns the internal job, nullptr by default.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwData::location::enableFolder< ::fwDataIO::writer::IObjectWriter >
enableFolder (::fwDataIO::writer::IObjectWriter *rw)
constructor
void setFolder (ILocation::PathType folder)
Set folder filesystem path.
ILocation::PathType getFolder ()
Get folder filesystem path.
void setRecursive (bool val)
Set the flag if folder location is recursive.
bool getRecursive ()
Get the flag if folder location is recursive.
Public Member Functions inherited from fwTools::ProgressAdviser
FWTOOLS_API void addHandler (const ProgessHandler &handler)
FWTOOLS_API void notifyProgress (float percent, const std::string &msg="") const
notify modification for all handler
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwMedData::Series >
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwDataIO::writer::IObjectWriter
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Protected Member Functions inherited from fwDataIO::writer::IObjectWriter
FWDATAIO_API IObjectWriter ()
Constructor. Do nothing.
virtual FWDATAIO_API ~IObjectWriter ()
Destructor. Do nothing.
Protected Attributes inherited from fwDataIO::writer::IObjectWriter
::fwTools::Object::wptr m_object
Object write on filesystem by the process.
::fwData::location::ILocation::sptr m_location
Object location (file path, directory path, url, etc)
std::string m_extension
Extension of file format.
Protected Attributes inherited from fwTools::ProgressAdviser
ProgessSignal m_progressSignal
to notify progress simply use m_progressSignal(percent,msg) to notify to Handler
Detailed Description
This class handles DICOM files writing. It defines needs of data storage and delegates writing to appropriate tools. It manages all related data of one patient.
Definition at line 30 of file io/fwGdcmIO/include/fwGdcmIO/writer/Series.hpp.
Member Enumeration Documentation
enum fwGdcmIO::writer::Series::FiducialsExportMode
Enumerator
COMPREHENSIVE_SR
Export Fiducials using SpatialFiducialsIOD
COMPREHENSIVE_3D_SR
Export Fiducials using ComprehensiveSRIOD
Definition at line 40 of file io/fwGdcmIO/include/fwGdcmIO/writer/Series.hpp.
Member Function Documentation
std::string fwGdcmIO::writer::Series::extension () virtual
Do nothing.
Override
Implements fwDataIO::writer::IObjectWriter.
Definition at line 138 of file io/fwGdcmIO/src/fwGdcmIO/writer/Series.cpp.
void fwGdcmIO::writer::Series::write () throw (::fwGdcmIO::exception::Failed) virtual
Load and start appropriate writing tools. In addition, it creates an adapted folder tree where DICOM files will be stored. It manages writing of the following general DICOM modules : patient, study and series.
Note
Currently, it handles image, SR and RT document writing.
Implements fwDataIO::writer::IObjectWriter.
Definition at line 51 of file io/fwGdcmIO/src/fwGdcmIO/writer/Series.cpp.
References COMPREHENSIVE_3D_SR, fwDataIO::writer::GenericObjectWriter< ::fwMedData::Series >::getConcreteObject(), fwData::Object::getField(), fwData::location::enableFolder< ::fwDataIO::writer::IObjectWriter >::getFolder(), fwDataTools::fieldHelper::Image::m_imageDistancesId, fwDataTools::fieldHelper::Image::m_imageLandmarksId, SLM_ASSERT, SLM_WARN, SPTR, fwGdcmIO::writer::iod::CTMRImageIOD::write(), fwGdcmIO::writer::iod::ComprehensiveSRIOD::write(), fwGdcmIO::writer::iod::SpatialFiducialsIOD::write(), and fwGdcmIO::writer::iod::SurfaceSegmentationIOD::write().
The documentation for this class was generated from the following files:
io/fwGdcmIO/include/fwGdcmIO/writer/Series.hpp
io/fwGdcmIO/src/fwGdcmIO/writer/Series.cpp