fw4spl: fwCore::HiResTimer Class Reference
fwCore::HiResTimer Class Reference
This class provide a timer (stopwatch). HiResTimer is able to measure the elapsed time with a few micro-seconds. accuracy, on Linux, Mac OS and Windows.
#include <HiResTimer.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((HiResTimer)(BaseObject))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new HiResTimer,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((HiResTimer)(BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWCORE_API void start ()
Start the timer.
FWCORE_API void stop ()
Stop the timer. stop() will not reset the timer.
FWCORE_API void reset (::fwCore::HiResClock::HiResClockType initial_value=0.)
Reset the timer and leave it in the same state it was (started or stopped).
Constructor/Destructor
FWCORE_API HiResTimer ()
virtual FWCORE_API ~HiResTimer ()
Elapsed time
These methods return the cumulated elapsed running time of the timer the timer is running when start() has been invoked and stop running on stop() or reset() invokation.
FWCORE_API::fwCore::HiResClock::HiResClockType getElapsedTimeInSec ()
FWCORE_API::fwCore::HiResClock::HiResClockType getElapsedTimeInMilliSec ()
FWCORE_API::fwCore::HiResClock::HiResClockType getElapsedTimeInMicroSec ()
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
This class provide a timer (stopwatch). HiResTimer is able to measure the elapsed time with a few micro-seconds. accuracy, on Linux, Mac OS and Windows.
Definition at line 28 of file HiResTimer.hpp.
Member Function Documentation
fwCore::HiResTimer::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new HiResTimer, (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((HiResTimer)(BaseObject)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((HiResTimer)(BaseObject)).
fwCore::HiResClock::HiResClockType fwCore::HiResTimer::getElapsedTimeInMicroSec ()
Returns
Elapsed time in microseconds
Definition at line 55 of file HiResTimer.cpp.
Referenced by getElapsedTimeInMilliSec(), and getElapsedTimeInSec().
fwCore::HiResClock::HiResClockType fwCore::HiResTimer::getElapsedTimeInMilliSec ()
Returns
Elapsed time in milliseconds
Definition at line 66 of file HiResTimer.cpp.
References getElapsedTimeInMicroSec().
Referenced by vtkGdcmIO::SeriesDBLazyReader::~SeriesDBLazyReader().
fwCore::HiResClock::HiResClockType fwCore::HiResTimer::getElapsedTimeInSec ()
Returns
Elapsed time in seconds
Definition at line 72 of file HiResTimer.cpp.
References getElapsedTimeInMicroSec().
void fwCore::HiResTimer::reset (::fwCore::HiResClock::HiResClockType initial_value = 0.)
Reset the timer and leave it in the same state it was (started or stopped).
Parameters
initial_value Initial value in microseconds from which the timer will start to count.
Definition at line 39 of file HiResTimer.cpp.
References start(), and stop().
The documentation for this class was generated from the following files:
HiResTimer.hpp
HiResTimer.cpp