fw4spl: fwGdcmIO::container::sr::DicomSRNumNode Class Reference
fwGdcmIO::container::sr::DicomSRNumNode Class Reference
This class defines a NUM node in a SR document.
#include <DicomSRNumNode.hpp>
Public Member Functions
FWGDCMIO_API DicomSRNumNode (const DicomCodedAttribute &codedAttribute, const std::string &relationship, double numValue, const DicomCodedAttribute &measurementUnits)
Constructor.
virtual FWGDCMIO_API ~DicomSRNumNode ()
Destructor.
virtual FWGDCMIO_API void write (::gdcm::DataSet &dataset) const
Write the SR node in the dataset.
const double & getNumValue () const
Get Numeric value.
void setNumValue (const double &numValue)
Set Numeric value.
const DicomCodedAttribute & getMeasurementUnits () const
Get Measurement units.
void setMeasurementUnits (const DicomCodedAttribute &measurementUnits)
Set Measurement units.
Public Member Functions inherited from fwGdcmIO::container::sr::DicomSRNode
FWGDCMIO_API void addSubNode (const std::shared_ptr< DicomSRNode > &node)
Add a sub node.
const SubNodeContainer & getSubNodeContainer () const
Get Sub node container.
void setSubNodeContainer (const SubNodeContainer &subNodeContainer)
Set Sub node container.
const DicomCodedAttribute & getCodedAttribute () const
Get Coded attribute.
void setCodedAttribute (const DicomCodedAttribute &codedAttribute)
Set Coded attribute.
const std::string & getType () const
Get Type.
void setType (const std::string &type)
Set Type.
const std::string & getRelationship () const
Get Relationship.
void setRelationship (const std::string &relationship)
Set Relationship.
Protected Member Functions
virtual void print (std::ostream &os) const
Dump function.
void writeMeasuredValueSequence (::gdcm::DataSet &dataset) const
Write a Measured Value Sequence.
Protected Member Functions inherited from fwGdcmIO::container::sr::DicomSRNode
DicomSRNode (const DicomCodedAttribute &codedAttribute, const std::string &type, const std::string &relationship="")
Constructor.
virtual ~DicomSRNode ()
Destructor.
::gdcm::SmartPointer< ::gdcm::SequenceOfItems > createConceptNameCodeSequence (::gdcm::DataSet &dataset, const DicomCodedAttribute &codedAttribute) const
Create a concept name code sequence.
void writeContentSequence (::gdcm::DataSet &dataset) const
Write a content sequence.
Protected Attributes
double m_numValue
Numeric Value.
DicomCodedAttribute m_measurementUnits
Measurement Units.
Protected Attributes inherited from fwGdcmIO::container::sr::DicomSRNode
SubNodeContainer m_subNodeContainer
SubNode container.
DicomCodedAttribute m_codedAttribute
Coded entry of the node.
std::string m_type
Node type (0040, a040)
std::string m_relationship
Node relationship (0040, a010)
Additional Inherited Members
Public Types inherited from fwGdcmIO::container::sr::DicomSRNode
typedef std::vector< std::shared_ptr< DicomSRNode > > SubNodeContainer
Detailed Description
This class defines a NUM node in a SR document.
Definition at line 29 of file DicomSRNumNode.hpp.
Member Function Documentation
void fwGdcmIO::container::sr::DicomSRNumNode::write (::gdcm::DataSet & dataset) const virtual
Write the SR node in the dataset.
Parameters
[in] dataset Destination dataset
Reimplemented from fwGdcmIO::container::sr::DicomSRNode.
Definition at line 39 of file DicomSRNumNode.cpp.
References fwGdcmIO::container::sr::DicomSRNode::write(), and writeMeasuredValueSequence().
void fwGdcmIO::container::sr::DicomSRNumNode::writeMeasuredValueSequence (::gdcm::DataSet & dataset) const protected
Write a Measured Value Sequence.
See also
PS 3.3 Table C.18.1
Parameters
[in] dataset Destination dataset
Definition at line 49 of file DicomSRNumNode.cpp.
References fwGdcmIO::container::sr::DicomSRNode::createConceptNameCodeSequence(), m_measurementUnits, and m_numValue.
Referenced by write().
The documentation for this class was generated from the following files:
DicomSRNumNode.hpp
DicomSRNumNode.cpp