fw4spl: fwGui::dialog::MessageDialog Class Reference
fwGui::dialog::MessageDialog Class Reference
Defines the generic message box for IHM. Use the Delegate design pattern.
#include <MessageDialog.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWGUI_API MessageDialog ()
Constructor. Create the implementation of the specific message box.
FWGUI_API MessageDialog (const std::string &title, const std::string &message,::fwGui::dialog::IMessageDialog::Icons icon=INFO)
virtual FWGUI_API ~MessageDialog ()
Destructor. Do nothing.
virtual FWGUI_API void setTitle (const std::string &title)
Set the title of the message box.
virtual FWGUI_API void setMessage (const std::string &msg)
Set the message.
virtual FWGUI_API void setIcon (IMessageDialog::Icons icon)
Set the icon (CRITICAL, WARNING, INFO or QUESTION)
virtual FWGUI_API void addButton (IMessageDialog::Buttons button)
Add a button (OK, YES_NO, YES, NO, CANCEL)
void setDefaultButton (IMessageDialog::Buttons button)
Set the default button.
virtual FWGUI_API IMessageDialog::Buttons show ()
Show the message box and return the clicked button.
Public Member Functions inherited from fwGui::dialog::IMessageDialog
FWGUI_API IMessageDialog ()
Constructor. Do nothing.
virtual FWGUI_API ~IMessageDialog ()
Destructor. Do nothing.
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWGUI_API IMessageDialog::Buttons showMessageDialog (const std::string &title, const std::string &message,::fwGui::dialog::IMessageDialog::Icons icon=INFO)
Static Public Member Functions inherited from fwGui::dialog::IMessageDialog
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes
::fwGui::dialog::IMessageDialog::sptr m_implementation
Implementation of a message box in a specific IHM (wx/Qt)
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwGui::dialog::IMessageDialog
enum Icons {
CRITICAL, WARNING, INFO, QUESTION,
NONE
}
Icon type.
enum Buttons {
NOBUTTON = 0, OK = 1 << 1, YES = 1 << 2, NO = 1 << 3,
CANCEL = 1 << 4, YES_NO = YES | NO
}
Buttons type.
typedef std::string FactoryRegistryKeyType
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Static Public Attributes inherited from fwGui::dialog::IMessageDialog
static FWGUI_API const FactoryRegistryKeyType REGISTRY_KEY = "::fwGui::dialog::MessageDialog"
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
Defines the generic message box for IHM. Use the Delegate design pattern.
Definition at line 24 of file include/fwGui/dialog/MessageDialog.hpp.
Constructor & Destructor Documentation
fwGui::dialog::MessageDialog::MessageDialog (const std::string & title, const std::string & message, ::fwGui::dialog::IMessageDialog::Icons icon = INFO)
Constructor Creates a message box with the specified title text and icon.
Parameters
title Title of the message box
message Message of the message box
icon Icon of the message box (CRITICAL, WARNING, INFO or QUESTION)
Definition at line 40 of file src/fwGui/dialog/MessageDialog.cpp.
References m_implementation.
Member Function Documentation
IMessageDialog::Buttons fwGui::dialog::MessageDialog::showMessageDialog (const std::string & title, const std::string & message, ::fwGui::dialog::IMessageDialog::Icons icon = INFO) static
Opens a default message box with the specified title, text and icon.
Parameters
title Title of the message box
message Message of the message box
icon Icon of the message box (CRITICAL, WARNING, INFO or QUESTION)
Returns
Returns the button enum value corresponding to the pressed button
Definition at line 19 of file src/fwGui/dialog/MessageDialog.cpp.
References addButton(), and show().
Referenced by monitor::DumpEditor::changeStatus(), visuVTKAdaptor::ImagesBlend::checkImageInformations(), ioITK::SInrSeriesDBReader::configureWithIHM(), ioDcmtk::SDicomSeriesDBReader::getSelectorDialogTitle(), ioVtkGdcm::SSeriesDBLazyReader::getSelectorDialogTitle(), ioVtkGdcm::SSeriesDBReader::getSelectorDialogTitle(), ioGdcm::SDicomSeriesDBReader::getSelectorDialogTitle(), ioDcmtk::SSeriesDBReader::getSelectorDialogTitle(), ioGdcm::SSeriesDBReader::getSelectorDialogTitle(), ioITK::InrImageWriterService::info(), ioITK::JpgImageWriterService::info(), ioITK::InrImageReaderService::info(), ioVTK::SSeriesDBReader::info(), ioVTK::SMeshReader::info(), guiQt::editor::SDynamicView::info(), guiQt::editor::DynamicView::info(), activities::action::SActivityLauncher::info(), guiQt::editor::DynamicView::launchTab(), uiMedData::editor::SSelector::onDoubleClick(), ioVTK::SImageWriter::saveImage(), ioDicom::SFilterSelectionEditor::starting(), uiTF::TransferFunctionEditor::stopping(), guiQt::editor::SDynamicView::swapping(), uiMeasurement::action::SaveLandmark::updating(), uiMeasurement::action::LoadLandmark::updating(), uiMeasurement::action::FocusLandmark::updating(), monitor::action::MemoryInfo::updating(), monitor::action::SDumpAll::updating(), basicRegistration::SImagesSubstract::updating(), uiMeasurement::action::AddLandmark::updating(), ioDcmtk::SDicomSeriesDBReader::updating(), ioVtkGdcm::SSeriesDBLazyReader::updating(), ioGdcm::SSeriesDBWriter::updating(), basicRegistration::SPointListRegistration::updating(), ioVtkGdcm::SSeriesDBReader::updating(), ioVtkGdcm::SImageSeriesWriter::updating(), ioGdcm::SDicomSeriesConverter::updating(), ioGdcm::SDicomSeriesWriter::updating(), ioDcmtk::SDicomTagSeriesDBReader::updating(), ioVTK::SImageReader::updating(), ioData::action::SMeshModifier::updating(), ioVTK::SModelSeriesReader::updating(), ioGdcm::SDicomSeriesDBReader::updating(), ioVTK::SMeshWriter::updating(), ioVTK::SModelSeriesWriter::updating(), activities::action::SCreateActivity::updating(), ioData::MeshReaderService::updating(), ioDcmtk::SSeriesDBReader::updating(), uiIO::editor::SIOSelector::updating(), ioData::MeshWriterService::updating(), ioAtoms::SWriter::updating(), gui::action::SStarter::updating(), ioAtoms::SReader::updating(), and activities::action::SActivityLauncher::updating().
The documentation for this class was generated from the following files:
include/fwGui/dialog/MessageDialog.hpp
src/fwGui/dialog/MessageDialog.cpp