fw4spl: fwNetworkIO::http::Request Class Reference
fwNetworkIO::http::Request Class Reference
HTTP request.
#include <Request.hpp>
Public Types
typedef std::map< std::string, std::string > HeadersType
Maps header name to its value.
Public Member Functions
virtual bool isA (const std::string &type) const override
FWNETWORKIO_API void addHeader (const std::string &key, const std::string &value)
add element in the request header
FWNETWORKIO_API void setHeaders (const HeadersType &headers)
headers setter.
FWNETWORKIO_API const HeadersType & getHeaders () const
headers getter.
FWNETWORKIO_API const std::string & getUrl () const
return current url
FWNETWORKIO_API void setUrl (const std::string &url)
set current url
Constructor/Destructor
FWNETWORKIO_API Request ()
Construct a new Request with given url.
FWNETWORKIO_API Request (const std::string &url)
Construct a new Request with given url.
virtual ~Request ()
Construct a new Request with given url.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWNETWORKIO_API Request::sptr New (const std::string &url)
Creates a new Request with given url.
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
HTTP request.
Definition at line 24 of file Request.hpp.
Member Function Documentation
Request::sptr fwNetworkIO::http::Request::New (const std::string & url) static
Creates a new Request with given url.
Parameters
url URL belonging to the request.
Returns
the newly created Request object
Definition at line 26 of file Request.cpp.
Referenced by ioDicomWeb::SQueryEditor::updating(), ioDicomWeb::SSeriesPusher::updating(), ioDicomWeb::SSeriesPuller::updating(), and ioDicomWeb::SSliceIndexDicomPullerEditor::updating().
The documentation for this class was generated from the following files:
Request.hpp
Request.cpp