fw4spl: fwServices::AppConfigManager Class Reference
fwServices::AppConfigManager Class Reference
This class provides an API to manage config template.
#include <AppConfigManager.hpp>
Classes
struct ProxyConnections
Public Member Functions
virtual bool isA (const std::string &type) const
FWSERVICES_API AppConfigManager ()
Constructor. Do nothing.
virtual FWSERVICES_API ~AppConfigManager ()
Destructor. Do nothing.
virtual FWSERVICES_API void startBundle ()
Starts the bundle associated to the config.
Overrides
virtual FWSERVICES_API void setConfig (const std::string &configId, const FieldAdaptorType &replaceFields=FieldAdaptorType())
Set configuration.
virtual FWSERVICES_API void setConfig (const std::string &configId, const ::fwData::Composite::csptr &replaceFields)
Set configuration.
virtual FWSERVICES_API::fwData::Object::sptr getConfigRoot () const
Get config root.
virtual FWSERVICES_API void launch ()
Calls methods : create, start then update.
virtual FWSERVICES_API void stopAndDestroy ()
Stops and destroys services specified in config, then resets the configRoot sptr.
virtual FWSERVICES_API void create ()
Creates objects and services from config.
virtual FWSERVICES_API void start ()
Starts services specified in config.
virtual FWSERVICES_API void update ()
Updates services specified in config.
virtual FWSERVICES_API void stop ()
Stops services specified in config.
virtual FWSERVICES_API void destroy ()
Destroys services specified in config.
Public Member Functions inherited from fwServices::IAppConfigManager
FWSERVICES_API IAppConfigManager ()
Constructor. Do nothing.
virtual FWSERVICES_API ~IAppConfigManager ()
Destructor. Do nothing.
bool isCreated () const
Return state.
bool isStarted () const
bool isStopped () const
bool isDestroyed () const
void setConfig (::fwRuntime::ConfigurationElement::csptr cfgElem)
Set config param.
Public Member Functions inherited from fwTools::Object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwServices::IAppConfigManager
static bool isTypeOf (const std::string &type)
static FWSERVICES_API std::shared_ptr< IAppConfigManager > New ()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef std::vector< ::fwServices::IService::wptr > ServiceContainer
typedef ::boost::tuple< std::string, bool > ConfigAttribute
typedef std::vector< ProxyConnections > ProxyConnectionsVectType
Protected Types inherited from fwServices::IAppConfigManager
enum ConfigState { STATE_CREATED, STATE_STARTED, STATE_STOPPED, STATE_DESTROYED }
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions
FWSERVICES_API::fwData::Object::sptr getNewObject (ConfigAttribute type, const std::string &uid, ConfigAttribute id=ConfigAttribute("", false))
FWSERVICES_API::fwData::Object::sptr getNewObject (ConfigAttribute type, ConfigAttribute uid=ConfigAttribute("", false), ConfigAttribute id=ConfigAttribute("", false))
FWSERVICES_API::fwData::Object::sptr getRefObject (ConfigAttribute type, const std::string &uid, ConfigAttribute id=ConfigAttribute("", false))
FWSERVICES_API::fwServices::IService::sptr getNewService (ConfigAttribute type, ConfigAttribute uid, ConfigAttribute implType)
FWSERVICES_API void autoSigSlotConnection (::fwData::Object::sptr obj,::fwServices::IService::sptr srv, ConfigAttribute priority)
FWSERVICES_API void startConnections ()
FWSERVICES_API void stopConnections ()
FWSERVICES_API void stopStartedServices ()
FWSERVICES_API void destroyCreatedServices ()
FWSERVICES_API void processStartItems ()
FWSERVICES_API void processUpdateItems ()
virtual FWSERVICES_API::fwData::Object::sptr createObject ()
virtual FWSERVICES_API void createServices ()
virtual FWSERVICES_API void createServices (::fwRuntime::ConfigurationElement::csptr cfgElem)
virtual FWSERVICES_API void bindService (::fwRuntime::ConfigurationElement::csptr srvElem)
virtual FWSERVICES_API void createConnections ()
virtual FWSERVICES_API void createProxy (::fwRuntime::ConfigurationElement::csptr config)
virtual FWSERVICES_API void destroyProxies ()
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Attributes
::fwData::Object::sptr m_configuredObject
Root of the config.
::fwServices::IXMLParser::sptr m_objectParser
ProxyConnectionsVectType m_vectProxyCtns
std::string m_configId
ServiceContainer m_createdSrv
ServiceContainer m_startedSrv
::fwCom::helper::SigSlotConnection m_connections
Protected Attributes inherited from fwServices::IAppConfigManager
::fwRuntime::ConfigurationElement::csptr m_cfgElem
XML Configuration tree.
ConfigState m_state
Running state of the app config manager.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwServices::IAppConfigManager
typedef registry::FieldAdaptorType FieldAdaptorType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Protected Attributes inherited from fwServices::IAppConfigManager
static int s_VERSION = 0
Tells which implementation we are running.
Detailed Description
This class provides an API to manage config template.
Definition at line 33 of file AppConfigManager.hpp.
Member Function Documentation
void fwServices::AppConfigManager::setConfig (const std::string & configId, const FieldAdaptorType & replaceFields = FieldAdaptorType()) virtual
Set configuration.
Parameters
configId the identifier of the requested config.
replaceFields the associations between the value and the pattern to replace in the config.
Implements fwServices::IAppConfigManager.
Definition at line 687 of file AppConfigManager.cpp.
References fwServices::registry::AppConfig::getDefault(), and fwServices::IAppConfigManager::m_cfgElem.
void fwServices::AppConfigManager::setConfig (const std::string & configId, const ::fwData::Composite::csptr & replaceFields) virtual
Set configuration.
Parameters
configId the identifier of the requested config.
replaceFields composite of association between the value and the pattern to replace in the config.
Implements fwServices::IAppConfigManager.
Definition at line 696 of file AppConfigManager.cpp.
References fwServices::registry::AppConfig::getDefault(), and fwServices::IAppConfigManager::m_cfgElem.
void fwServices::AppConfigManager::startBundle () virtual
Starts the bundle associated to the config.
Note
Does nothing if the bundle is already started or if the config id is not specified (ie. if config is set with setConfig(::fwRuntime::ConfigurationElement::csptr cfgElem)).
Definition at line 704 of file AppConfigManager.cpp.
References fwServices::registry::AppConfig::getDefault(), and SLM_WARN_IF.
Referenced by launch().
void fwServices::AppConfigManager::startConnections () protected
Connections are already started
Definition at line 148 of file AppConfigManager.cpp.
References fwCom::helper::SigSlotConnection::disconnect(), fwTools::fwID::exist(), fwServices::get(), fwServices::registry::ServiceFactory::getDefault(), fwServices::registry::ActiveWorkers::getDefault(), fwServices::registry::ServiceConfig::getDefault(), fwServices::IAppConfigManager::m_cfgElem, m_configuredObject, OSLM_ASSERT, OSLM_FATAL, SLM_ASSERT, SLM_ERROR_IF, and update().
Referenced by start().
The documentation for this class was generated from the following files:
AppConfigManager.hpp
AppConfigManager.cpp