fw4spl: fwGdcmIO::writer::ie::Image Class Reference
fwGdcmIO::writer::ie::Image Class Reference
Image Information Entity class.
#include <Image.hpp>
Public Member Functions
FWGDCMIO_API Image (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::csptr &image, const ::fwLog::Logger::sptr &logger=nullptr, ProgressCallback progress=nullptr, CancelRequestedCallback cancel=nullptr)
Constructor.
virtual FWGDCMIO_API ~Image ()
Destructor.
virtual FWGDCMIO_API void writeGeneralImageModule ()
Write General Image Module tags.
virtual FWGDCMIO_API void writeGeneralImageModuleSpecificTags (unsigned int instanceNumber)
Write General Image Module specific tags.
virtual FWGDCMIO_API void writeImagePlaneModule ()
Write Image Plane Module tags.
virtual FWGDCMIO_API void writeImagePlaneModuleSpecificTags (unsigned int instanceNumber)
Write Image Plane Module tags.
virtual FWGDCMIO_API void writeImagePixelModule ()
Write Image Pixel Module tags.
virtual FWGDCMIO_API void writeImagePixelModuleSpecificTags (unsigned int instanceNumber)
Write Image Pixel Module specific tags.
virtual FWGDCMIO_API void writeVOILUTModule ()
Write VOI LUT Module tags.
virtual FWGDCMIO_API void writeSOPCommonModule ()
Write SOP Common Module tags.
virtual FWGDCMIO_API void writeSOPCommonModuleSpecificTags (unsigned int instanceNumber)
Write SOP Common Module specific tags.
virtual FWGDCMIO_API void writeCTImageModule ()
Write CT Image Module tags.
virtual FWGDCMIO_API void writeMRImageModule ()
Write MR Image Module tags.
Public Member Functions inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >
FWGDCMIO_API InformationEntity (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< const ::fwData::Image > &object, const ::fwLog::Logger::sptr &logger=nullptr, ProgressCallback progress=nullptr, CancelRequestedCallback cancel=nullptr)
Constructor.
virtual FWGDCMIO_API ~InformationEntity ()
Destructor.
Additional Inherited Members
Public Types inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< bool() > CancelRequestedCallback
Protected Attributes inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >
std::shared_ptr< ::gdcm::Writer > m_writer
GDCM Writer.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< const ::fwData::Image > m_object
FW4SPL Object.
::fwLog::Logger::sptr m_logger
Logger.
ProgressCallback m_progressCallback
Progress callback for jobs.
CancelRequestedCallback m_cancelRequestedCallback
Cancel information for jobs.
Detailed Description
Image Information Entity class.
Definition at line 23 of file io/fwGdcmIO/include/fwGdcmIO/writer/ie/Image.hpp.
Constructor & Destructor Documentation
fwGdcmIO::writer::ie::Image::Image (const std::shared_ptr< ::gdcm::Writer > & writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::csptr & image, const ::fwLog::Logger::sptr & logger = nullptr, ProgressCallback progress = nullptr, CancelRequestedCallback cancel = nullptr)
Constructor.
Parameters
[in] writer GDCM writer that must be enriched
[in] instance DICOM instance used to share information between modules
[in] image Image data
[in] logger Logger
[in] progress Progress callback
[in] cancel Cancel requested callback
Definition at line 27 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
Member Function Documentation
void fwGdcmIO::writer::ie::Image::writeCTImageModule () virtual
Write CT Image Module tags.
See also
PS 3.3 C.8.2.1
Definition at line 216 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer.
void fwGdcmIO::writer::ie::Image::writeGeneralImageModule () virtual
Write General Image Module tags.
See also
PS 3.3 C.7.6.1
Definition at line 45 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
void fwGdcmIO::writer::ie::Image::writeGeneralImageModuleSpecificTags (unsigned int instanceNumber) virtual
Write General Image Module specific tags.
See also
PS 3.3 C.7.6.1
Parameters
[in] instanceNumber Instance number
Definition at line 52 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer.
void fwGdcmIO::writer::ie::Image::writeImagePixelModule () virtual
Write Image Pixel Module tags.
See also
PS 3.3 C.7.6.3
Definition at line 110 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::helper::DicomDataTools::getPhotometricInterpretation(), fwGdcmIO::helper::DicomDataTools::getPixelType(), fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_instance, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, and OSLM_TRACE.
void fwGdcmIO::writer::ie::Image::writeImagePixelModuleSpecificTags (unsigned int instanceNumber) virtual
Write Image Pixel Module specific tags.
See also
PS 3.3 C.7.6.3
Parameters
[in] instanceNumber Instance number
Definition at line 145 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwDataTools::helper::ImageGetter::getBuffer(), fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_instance, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, and SLM_ASSERT.
void fwGdcmIO::writer::ie::Image::writeImagePlaneModule () virtual
Write Image Plane Module tags.
See also
PS 3.3 C.7.6.2
Definition at line 64 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, OSLM_TRACE, and SPTR.
void fwGdcmIO::writer::ie::Image::writeImagePlaneModuleSpecificTags (unsigned int instanceNumber) virtual
Write Image Plane Module tags.
See also
PS 3.3 C.7.6.2
Parameters
[in] instanceNumber Instance number
Definition at line 94 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, and SPTR.
void fwGdcmIO::writer::ie::Image::writeMRImageModule () virtual
Write MR Image Module tags.
See also
PS 3.3 C.8.3.1
Definition at line 240 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer.
void fwGdcmIO::writer::ie::Image::writeSOPCommonModule () virtual
Write SOP Common Module tags.
See also
PS 3.3 C.12.1
Definition at line 192 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_instance, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, and SLM_TRACE.
void fwGdcmIO::writer::ie::Image::writeSOPCommonModuleSpecificTags (unsigned int instanceNumber) virtual
Write SOP Common Module specific tags.
See also
PS 3.3 C.12.1
Parameters
[in] instanceNumber Instance number
Definition at line 204 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_instance, and fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer.
void fwGdcmIO::writer::ie::Image::writeVOILUTModule () virtual
Write VOI LUT Module tags.
See also
PS 3.3 C.11.2
Definition at line 170 of file io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwData::Image >::m_writer, and OSLM_TRACE.
The documentation for this class was generated from the following files:
io/fwGdcmIO/include/fwGdcmIO/writer/ie/Image.hpp
io/fwGdcmIO/src/fwGdcmIO/writer/ie/Image.cpp