fw4spl: uiImage::ImageTransparency Class Reference
uiImage::ImageTransparency Class Reference
ImageTransparency service allows to change image transparency.
#include <ImageTransparency.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ImageTransparency)(::gui::editor::IEditor))
Protected Slots
void onModifyVisibility (bool value)
This method is called when the visibility value change using action shortcut.
void onModifyVisibility (int value)
This method is called when the visibility value change clicking on checkbox.
void onModifyTransparency (int value)
This method is called when the transparency value change moving slider.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Starts editor.
virtual void stopping () throw (::fwTools::Failed)
Stops editor.
virtual void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Receive InteractionMsg and updates text informations.
virtual void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
virtual void info (std::ostream &_sstream)
This method is used to give information about the service. Do nothing.
Detailed Description
ImageTransparency service allows to change image transparency.
Date:
2011.
Definition at line 34 of file ImageTransparency.hpp.
Member Function Documentation
void uiImage::ImageTransparency::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 106 of file ImageTransparency.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, SLM_ASSERT, and SLM_TRACE_FUNC.
void uiImage::ImageTransparency::info (std::ostream & _sstream) [protected, virtual]
This method is used to give information about the service. Do nothing.
Todo:
Must be not implemented and class child declaration should be imposed.
Reimplemented from gui::editor::IEditor.
Definition at line 190 of file ImageTransparency.cpp.
void uiImage::ImageTransparency::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 166 of file ImageTransparency.cpp.
References updating().
void uiImage::ImageTransparency::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 123 of file ImageTransparency.cpp.
References fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity(), onModifyTransparency(), and onModifyVisibility().
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
ImageTransparency.hpp
ImageTransparency.cpp