fw4spl: fwGdcmIO::writer::tid::MeasurementReport Class Reference
fwGdcmIO::writer::tid::MeasurementReport Class Reference
Measurement Report TID - This a root template.
#include <MeasurementReport.hpp>
Public Member Functions
FWGDCMIO_API MeasurementReport (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::csptr &image)
Constructor.
virtual FWGDCMIO_API ~MeasurementReport ()
Destructor.
virtual FWGDCMIO_API std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > createRootNode (bool useSCoord3D=true)
Create Measurement Report template root node.
Public Member Functions inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
FWGDCMIO_API TemplateID (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< const ::fwData::Image > &object)
Constructor.
virtual FWGDCMIO_API ~TemplateID ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
std::shared_ptr< ::gdcm::Writer > m_writer
GDCM Writer.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< const ::fwData::Image > m_object
FW4SPL Object.
Detailed Description
Measurement Report TID - This a root template.
See also
TID t1tt1 FIXME: Set the final TID
Definition at line 25 of file writer/tid/MeasurementReport.hpp.
Constructor & Destructor Documentation
fwGdcmIO::writer::tid::MeasurementReport::MeasurementReport (const std::shared_ptr< ::gdcm::Writer > & writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::csptr & image)
Constructor.
Parameters
[in] writer GDCM writer that must be enriched
[in] instance DICOM instance used to share informations between modules
[in] image Image data
Definition at line 45 of file writer/tid/MeasurementReport.cpp.
Member Function Documentation
std::shared_ptr<::fwGdcmIO::container::sr::DicomSRNode > fwGdcmIO::writer::tid::MeasurementReport::createRootNode (bool useSCoord3D = true) virtual
Create Measurement Report template root node.
Parameters
[in] useSCoord3D True if we must write SCOORD3D, false if we must write SCOORD
Definition at line 60 of file writer/tid/MeasurementReport.cpp.
References fwGdcmIO::writer::tid::Fiducial::createNodes(), fwGdcmIO::writer::tid::Measurement::createNodes(), fwDataTools::fieldHelper::Image::m_imageDistancesId, fwDataTools::fieldHelper::Image::m_imageLandmarksId, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_instance, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_writer, and SPTR.
Referenced by fwGdcmIO::writer::ie::Document::writeSRDocumentContentModule().
The documentation for this class was generated from the following files:
writer/tid/MeasurementReport.hpp
writer/tid/MeasurementReport.cpp