fw4spl: fwGdcmIO::helper::DicomDataWriter Class Reference
fwGdcmIO::helper::DicomDataWriter Class Reference
This class contains helpers to write information into GDCM datasets.
#include <DicomDataWriter.hxx>
Public Member Functions
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static::gdcm::SmartPointer< ::gdcm::SequenceOfItems > createAndSetSequenceTagValue (::gdcm::DataSet &dataset)
Create and set a sequence of items with a tag in the specified data set.
Static Public Member Functions
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setEmptyTagValue (::gdcm::DataSet &dataset)
Insert an empty tag in a data set. Useful for empty type 2 tags.
template<typename T , std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setTagValue (const T &value,::gdcm::DataSet &dataset)
Insert the value of a tag in a data set.
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setTagValue (const std::string &value,::gdcm::DataSet &dataset)
Insert the string value of a tag in a data set.
template<typename T , std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setTagValues (const T *array, const size_t size,::gdcm::DataSet &dataset)
Insert multiple values of a tag in a data set.
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setSequenceTagValue (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence,::gdcm::DataSet &dataset)
Set and insert a sequence of items with a tag in the specified data set.
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setAndMergeSequenceTagValue (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence,::gdcm::DataSet &dataset)
Insert a sequence of items with a tag in the specified data set. If the tag already exists, items of the old and new sequences are added in a new one.
template<std::uint16_t GROUP, std::uint16_t ELEMENT>
static void setCodeSequenceTagValue (::fwGdcmIO::container::DicomCodedAttribute attribute,::gdcm::DataSet &dataset)
Set tag value for the code sequence.
Detailed Description
This class contains helpers to write information into GDCM datasets.
Definition at line 27 of file DicomDataWriter.hxx.
Member Function Documentation
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static ::gdcm::SmartPointer< ::gdcm::SequenceOfItems > fwGdcmIO::helper::DicomDataWriter::createAndSetSequenceTagValue (::gdcm::DataSet & dataset) inline
Create and set a sequence of items with a tag in the specified data set.
Parameters
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 121 of file DicomDataWriter.hxx.
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setAndMergeSequenceTagValue (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, ::gdcm::DataSet & dataset) inline static
Insert a sequence of items with a tag in the specified data set. If the tag already exists, items of the old and new sequences are added in a new one.
Parameters
[in] sequence Sequence of items to insert
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 139 of file DicomDataWriter.hxx.
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setCodeSequenceTagValue (::fwGdcmIO::container::DicomCodedAttribute attribute, ::gdcm::DataSet & dataset) inline static
Set tag value for the code sequence.
Parameters
[in] attribute attribute to set
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 172 of file DicomDataWriter.hxx.
References fwGdcmIO::container::DicomCodedAttribute::getCodeMeaning(), fwGdcmIO::container::DicomCodedAttribute::getCodeValue(), fwGdcmIO::container::DicomCodedAttribute::getCodingSchemeDesignator(), and fwGdcmIO::container::DicomCodedAttribute::getCodingSchemeVersion().
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setEmptyTagValue (::gdcm::DataSet & dataset) inline static
Insert an empty tag in a data set. Useful for empty type 2 tags.
Parameters
[in] dataset Data set of tags
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 38 of file DicomDataWriter.hxx.
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setSequenceTagValue (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, ::gdcm::DataSet & dataset) inline static
Set and insert a sequence of items with a tag in the specified data set.
Parameters
[in] sequence Sequence of items to insert
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 101 of file DicomDataWriter.hxx.
template<typename T , std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setTagValue (const T & value, ::gdcm::DataSet & dataset) inline static
Insert the value of a tag in a data set.
Parameters
[in] value Value to set
[in] dataset Data set of tags
Template Parameters
T Type of value
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 53 of file DicomDataWriter.hxx.
template<std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setTagValue (const std::string & value, ::gdcm::DataSet & dataset) inline static
Insert the string value of a tag in a data set.
Parameters
[in] value Value to set
[in] dataset Data set of tags
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 68 of file DicomDataWriter.hxx.
template<typename T , std::uint16_t GROUP, std::uint16_t ELEMENT> static void fwGdcmIO::helper::DicomDataWriter::setTagValues (const T * array, const size_t size, ::gdcm::DataSet & dataset) inline static
Insert multiple values of a tag in a data set.
Parameters
[in] array An Array.
[in] size Size of the array.
[in] dataset Data set of tags.
Template Parameters
T Type of pointer.
GROUP Group of the tag.
ELEMENT Element of the tag.
Definition at line 83 of file DicomDataWriter.hxx.
The documentation for this class was generated from the following file:
DicomDataWriter.hxx