fw4spl: fwServices::registry::AppConfig Class Reference
fwServices::registry::AppConfig Class Reference
This class allows to register all the configuration which has the point extension "::fwServices::registry::AppConfig".
#include <AppConfig.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
virtual FWSERVICES_API ~AppConfig ()
Destructor.
FWSERVICES_API void parseBundleInformation ()
Parses bundle information to retrieve configuration declaration.
FWSERVICES_API void addAppInfo (const std::string &configId, const std::string &group, const std::string &desc, const AppInfo::ParametersType &parameters,::fwRuntime::ConfigurationElement::csptr config, const std::string bundleId, const std::string bundleVersion)
Register a new config.
FWSERVICES_API::fwRuntime::ConfigurationElement::csptr getAdaptedTemplateConfig (const std::string &configId, const FieldAdaptorType replaceFields=FieldAdaptorType()) const
Return the adapted config with the identifier configId.
FWSERVICES_API::fwRuntime::ConfigurationElement::csptr getAdaptedTemplateConfig (const std::string &configId,::fwData::Composite::csptr replaceFields) const
Return the adapted config with the identifier configId.
FWSERVICES_API std::shared_ptr< ::fwRuntime::Bundle > getBundle (const std::string &configId)
Retrieves the bunble from the config id.
FWSERVICES_API std::vector< std::string > getAllConfigs () const
Return all configurations (standard and template) register in the registry.
FWSERVICES_API std::vector< std::string > getConfigsFromGroup (const std::string &group) const
Return all configurations with specified group.
FWSERVICES_API void clearRegistry ()
Clear the registry.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWSERVICES_API std::string getUniqueIdentifier (const std::string &serviceUid="")
Create an unique identifier.
static FWSERVICES_API AppConfig::sptr getDefault ()
Return an instance of AppConfig.
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef std::map< std::string, AppInfo::sptr > Registry
Protected Member Functions
FWSERVICES_API AppConfig ()
Constructor.
Protected Attributes
Registry m_reg
Container of <configId, appConfig information>
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
This class allows to register all the configuration which has the point extension "::fwServices::registry::AppConfig".
Definition at line 36 of file AppConfig.hpp.
Member Function Documentation
void fwServices::registry::AppConfig::addAppInfo (const std::string & configId, const std::string & group, const std::string & desc, const AppInfo::ParametersType & parameters, ::fwRuntime::ConfigurationElement::csptr config, const std::string bundleId, const std::string bundleVersion)
Register a new config.
Parameters
configId the identifier of the registered config.
type the type of the added config. It can be TEMPLATE, STANDARD or PARAMETERS.
group the name of the group that owns the config.
desc the config description.
parameters the list of template parameters in the config.
config the registered config.
Note
This method is thread safe
Definition at line 101 of file AppConfig.cpp.
References m_reg, OSLM_DEBUG, and SLM_ASSERT.
Referenced by parseBundleInformation().
void fwServices::registry::AppConfig::clearRegistry ()
Clear the registry.
Note
This method is thread safe.
Definition at line 135 of file AppConfig.cpp.
References m_reg.
fwRuntime::ConfigurationElement::csptr fwServices::registry::AppConfig::getAdaptedTemplateConfig (const std::string & configId, const FieldAdaptorType replaceFields = FieldAdaptorType()) const
Return the adapted config with the identifier configId.
Parameters
configId the identifier of the requested config.
replaceFields associations between the value and the pattern to replace in the config.
Note
This method is thread safe.
Definition at line 143 of file AppConfig.cpp.
References m_reg, and SLM_ASSERT.
Referenced by getAdaptedTemplateConfig().
fwRuntime::ConfigurationElement::csptr fwServices::registry::AppConfig::getAdaptedTemplateConfig (const std::string & configId, ::fwData::Composite::csptr replaceFields) const
Return the adapted config with the identifier configId.
Parameters
configId the identifier of the requested config.
replaceFields composite of association between the value and the pattern to replace in the config.
Note
This method is thread safe.
Definition at line 183 of file AppConfig.cpp.
References getAdaptedTemplateConfig().
std::vector< std::string > fwServices::registry::AppConfig::getAllConfigs () const
Return all configurations (standard and template) register in the registry.
Note
This method is thread safe.
Definition at line 193 of file AppConfig.cpp.
References m_reg.
std::shared_ptr<::fwRuntime::Bundle > fwServices::registry::AppConfig::getBundle (const std::string & configId)
Retrieves the bunble from the config id.
Parameters
configId the config identifier
Definition at line 305 of file AppConfig.cpp.
References m_reg, and SLM_ASSERT.
std::vector< std::string > fwServices::registry::AppConfig::getConfigsFromGroup (const std::string & group) const
Return all configurations with specified group.
Note
This method is thread safe.
Definition at line 206 of file AppConfig.cpp.
References m_reg.
std::string fwServices::registry::AppConfig::getUniqueIdentifier (const std::string & serviceUid = "") static
Create an unique identifier.
Note
This method is thread safe.
Definition at line 236 of file AppConfig.cpp.
References SLM_TRACE_FUNC.
Referenced by activities::action::SActivityLauncher::info(), guiQt::editor::DynamicView::launchTab(), fwServices::helper::ConfigLauncher::startConfig(), uiMeasurement::action::SaveLandmark::stopping(), uiMeasurement::action::LoadLandmark::stopping(), guiQt::editor::SDynamicView::swapping(), and uiMedData::SSeriesViewer::updating().
void fwServices::registry::AppConfig::parseBundleInformation ()
Parses bundle information to retrieve configuration declaration.
Warning
This method must be launch only once. The same extension will not be parsed twice.
Note
This method is thread safe.
Definition at line 43 of file AppConfig.cpp.
References addAppInfo().
The documentation for this class was generated from the following files:
AppConfig.hpp
AppConfig.cpp