fw4spl: fwAtoms::Boolean Class Reference
fwAtoms::Boolean Class Reference
Represented a Boolean value.
#include <Boolean.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
Boolean (::fwAtoms::Base::Key key)
Constructor.
virtual ~Boolean ()
Destructor.
virtual FWATOMS_API std::string getString () const override
Return the string representation of a value.
virtual FWATOMS_API void setString (const std::string &value)
virtual FWATOMS_API Base::sptr clone () const override
Returns a clone object.
::fwAtoms::Base::AtomType type () const override
returns Atom type
bool getValue () const
Public Member Functions inherited from fwAtoms::Base
bool isValue () const
Test if the current base is a value or not (Value = {string;numeric;boolean})
bool isBoolean () const
Test if the current base is a boolean.
bool isNumeric () const
Test if the current base is a Numeric (real or integer)
bool isString () const
Test if the current base is a string.
bool isSequence () const
Test if the current base is a sequence.
bool isMapping () const
Test if the current base is a mapping.
bool isBlob () const
Test if the current base is a blob (a object with a buffer)
bool isObject () const
Test if the current base is an object (representation of fwData)
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWATOMS_API Boolean::sptr New (std::string value)
Construct an object storing a bool value.
static FWATOMS_API Boolean::sptr New (bool value)
Construct an object storing a bool value.
Static Public Member Functions inherited from fwAtoms::Base
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Member Functions
FWATOMS_API Boolean (bool value)
Construct an object storing a bool value.
FWATOMS_API Boolean (std::string &value)
Construct an object storing a bool value.
Protected Member Functions inherited from fwAtoms::Base
Base ()
Constructor.
Protected Attributes
bool m_value
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwAtoms::Base
enum AtomType {
BOOLEAN = 1, NUMERIC, STRING, OBJECT,
SEQUENCE, MAP, BLOB
}
typedef ::fwAtoms::factory::Key Key
Static Public Attributes inherited from fwAtoms::Base
static FWATOMS_API const std::string s_VERSION = "1"
Defines fwAtoms version.
Detailed Description
Represented a Boolean value.
Definition at line 23 of file fwAtoms/include/fwAtoms/Boolean.hpp.
Constructor & Destructor Documentation
fwAtoms::Boolean::Boolean (::fwAtoms::Base::Key key) inline
Constructor.
Parameters
key Private construction key
Definition at line 32 of file fwAtoms/include/fwAtoms/Boolean.hpp.
FWATOMS_API fwAtoms::Boolean::Boolean (bool value) protected
Construct an object storing a bool value.
Parameters
value the boolena value.
FWATOMS_API fwAtoms::Boolean::Boolean (std::string & value) protected
Construct an object storing a bool value.
Parameters
value a string representing a boolean.
If value = "true" then true is stored otherwise false is stored.
Member Function Documentation
std::string fwAtoms::Boolean::getString () const override virtual
Return the string representation of a value.
Returns
the value's representation, else "<Unknown>"
Reimplemented from fwAtoms::Base.
Definition at line 35 of file fwAtoms/src/fwAtoms/Boolean.cpp.
Boolean::sptr fwAtoms::Boolean::New (std::string value) static
Construct an object storing a bool value.
Parameters
value a string representing a boolean.
If value = "true" then true is stored otherwise false is stored.
Definition at line 17 of file fwAtoms/src/fwAtoms/Boolean.cpp.
Referenced by fwMDSemanticPatch::V09ALA::V10::fwData::Image::apply(), fwStructuralPatch::fwData::Material::V4ToV3::apply(), fwStructuralPatch::fwData::Material::V2ToV3::apply(), clone(), New(), and fwAtomsPatch::patcher::DefaultPatcher::processBase().
Boolean::sptr fwAtoms::Boolean::New (bool value) static
Construct an object storing a bool value.
Parameters
value the boolean value.
Definition at line 26 of file fwAtoms/src/fwAtoms/Boolean.cpp.
References New().
The documentation for this class was generated from the following files:
fwAtoms/include/fwAtoms/Boolean.hpp
fwAtoms/src/fwAtoms/Boolean.cpp