fw4spl: fwAtoms::Numeric Class Reference
fwAtoms::Numeric Class Reference
Storing a numeric value.
#include <Numeric.hpp>
Public Types
enum NumericType {
EMPTY = 0, INT, UINT, FLOAT,
DOUBLE
}
typedef ::boost::variant< ::boost::blank,::boost::int64_t,::boost::uint64_t, float, double > ValueType
Public Types inherited from fwAtoms::Base
enum AtomType {
BOOLEAN = 1, NUMERIC, STRING, OBJECT,
SEQUENCE, MAP, BLOB
}
typedef ::fwAtoms::factory::Key Key
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Numeric)(::fwAtoms::Base))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwAtoms::factory::New< Numeric >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Numeric)(::fwAtoms::Base)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
Numeric (::fwAtoms::Base::Key key)
Constructor.
virtual ~Numeric ()
Destructor.
virtual FWATOMS_API Base::sptr clone () const
Returns a clone object.
::fwAtoms::Base::AtomType type () const
returns Atom type
NumericType variantType () const
Returns currently held numeric type.
const ValueType & getVariant () const
Returns const reference to numeric's variant.
virtual FWATOMS_API std::string getString () const
Returns a string representing the currently held numeric value.
FWATOMS_API void setFromString (const std::string &s, NumericType type=EMPTY)
Sets Numeric's value from given string, using Numeric::valueFromString.
template<typename T >
T getValue () const
Returns the held value static_casted to T.
Public Member Functions inherited from fwAtoms::Base
__FWCORE_CLASS_TYPEDEFS ((Base)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Base)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
bool isValue () const
Test if the current base is a value or not (Value = {string;numeric;boolean})
bool isBoolean () const
Test if the current base is a boolean.
bool isNumeric () const
Test if the current base is a Numeric (real or integer)
bool isString () const
Test if the current base is a string.
bool isSequence () const
Test if the current base is a sequence.
bool isMapping () const
Test if the current base is a mapping.
bool isBlob () const
Test if the current base is a blob (a object with a buffer)
bool isObject () const
Test if the current base is an object (representation of fwData)
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
template<typename T >
static Numeric::sptr New (T value)
Build a new numeric type.
static FWATOMS_API ValueType valueFromString (const std::string &s, NumericType type=EMPTY)
Retuns a ValueType from a std::string.
Static Public Member Functions inherited from fwAtoms::Base
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes
ValueType m_value
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Public Attributes inherited from fwAtoms::Base
static FWATOMS_API const std::string s_VERSION = "1"
Defines fwAtoms version.
Protected Member Functions inherited from fwAtoms::Base
Base ()
Constructor.
Detailed Description
Storing a numeric value.
Definition at line 26 of file Numeric.hpp.
Constructor & Destructor Documentation
fwAtoms::Numeric::Numeric (::fwAtoms::Base::Key key) inline
Constructor.
Parameters
key Private construction key
Definition at line 48 of file Numeric.hpp.
Member Function Documentation
fwAtoms::Numeric::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwAtoms::factory::New< Numeric > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Numeric)(::fwAtoms::Base)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Numeric)(fwAtoms::Base)).
template<typename T > T fwAtoms::Numeric::getValue () const
Returns the held value static_casted to T.
Template Parameters
T wanted type
Exceptions
boost::positive_overflow
boost::negative_overflow
Definition at line 113 of file Numeric.hxx.
const ValueType& fwAtoms::Numeric::getVariant () const inline
Returns const reference to numeric's variant.
Returns
Definition at line 94 of file Numeric.hpp.
template<typename T > Numeric::sptr fwAtoms::Numeric::New (T value) static
Build a new numeric type.
Parameters
value reference of all numeric type Supported tested type are (int8/16/32/64, uint8/16/32/64, float, double)
Definition at line 79 of file Numeric.hxx.
Referenced by fwStructuralPatch::fwData::Image::V1ToV2::apply(), clone(), fwAtomsPatch::patcher::DefaultPatcher::processBase(), and fwAtomConversion::DataVisitor::visit().
Numeric::ValueType fwAtoms::Numeric::valueFromString (const std::string & s, Numeric::NumericType type = EMPTY) static
Retuns a ValueType from a std::string.
Parameters
s source string
type type hint
If hint is EMPTY (default), this method tries to find a fitting type (in order : int64, uint64, double)
Exceptions
fwAtoms::Exception if unable to cast givent string
Returns
a ValueType containing the numeric value
Definition at line 61 of file Numeric.cpp.
References SLM_ASSERT.
Referenced by setFromString().
The documentation for this class was generated from the following files:
Numeric.hpp
Numeric.hxx
Numeric.cpp