fw4spl: fwDataTools::helper::Composite Class Reference
fwDataTools::helper::Composite Class Reference
Defines an helper to modify an fwData::Composite and create in parallel the message to announce this modification.
#include <Composite.hpp>
Public Member Functions
FWDATATOOLS_API Composite (::fwData::Composite::wptr _composite)
Constructor. Initialize parameters.
FWDATATOOLS_API ~Composite ()
Destrucotr. Do nothing.
FWDATATOOLS_API void add (std::string _compositeKey,::fwData::Object::sptr _newObject)
Add an object in the composite.
FWDATATOOLS_API void remove (std::string _compositeKey)
Remove an object in the composite.
FWDATATOOLS_API void clear ()
Clear all objects in the composite.
FWDATATOOLS_API void swap (std::string _compositeKey,::fwData::Object::sptr _newObject)
Replace an object in the composite.
FWDATATOOLS_API void notify ()
Send the message of modification.
Detailed Description
Defines an helper to modify an fwData::Composite and create in parallel the message to announce this modification.
Definition at line 22 of file SrcLib/core/fwDataTools/include/fwDataTools/helper/Composite.hpp.
Member Function Documentation
void fwDataTools::helper::Composite::add (std::string _compositeKey, ::fwData::Object::sptr _newObject)
Add an object in the composite.
Parameters
[in] _compositeKey key of the object in the composite.
[in] _newObject object to add in the composite
Prepare the message to announce the modification.
Definition at line 35 of file SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp.
References OSLM_FATAL_IF.
Referenced by ctrlSelection::updater::SObjFromUid::add(), ctrlSelection::updater::SObjFromSlot::add(), fwDataTools::helper::Image::createTransferFunctionPool(), uiTF::TransferFunctionEditor::initTransferFunctions(), ctrlCamp::SExtractObj::stopping(), uiTF::TransferFunctionEditor::stopping(), uiTF::TransferFunctionEditor::updateTransferFunction(), fwDataTools::helper::MedicalImageAdaptor::updateTransferFunction(), uiMedData::editor::SOrganTransformation::updating(), ctrlCamp::SExtractMeshByType::updating(), ioAtoms::SReader::updating(), and ctrlSelection::updater::SDrop::~SDrop().
void fwDataTools::helper::Composite::clear ()
Clear all objects in the composite.
Prepare the message to announce the modification.
Definition at line 68 of file SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp.
Referenced by uiTF::TransferFunctionEditor::stopping(), and ctrlSelection::updater::SDrop::~SDrop().
void fwDataTools::helper::Composite::notify ()
Send the message of modification.
Parameters
_serviceSource service used to send the message
_allowLoops if true, the _serviceSource will receive the message
Definition at line 112 of file SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp.
References OSLM_INFO_IF, fwData::Composite::s_ADDED_OBJECTS_SIG, fwData::Composite::s_CHANGED_OBJECTS_SIG, and fwData::Composite::s_REMOVED_OBJECTS_SIG.
Referenced by ctrlSelection::updater::SObjFromUid::add(), ctrlSelection::updater::SObjFromSlot::add(), fwDataTools::helper::Image::createTransferFunctionPool(), uiTF::TransferFunctionEditor::initTransferFunctions(), ctrlSelection::updater::SObjFromUid::remove(), ctrlSelection::updater::SObjFromSlot::remove(), visuVTKAdaptor::PlaneSelectionNotifier::selectPlane(), ctrlCamp::SExtractObj::stopping(), uiTF::TransferFunctionEditor::stopping(), ctrlSelection::updater::SObjFromUid::swap(), ctrlSelection::updater::SObjFromSlot::swap(), uiImage::WindowLevel::swapCurrentTFAndNotify(), uiTF::TransferFunctionEditor::updateTransferFunction(), fwDataTools::helper::MedicalImageAdaptor::updateTransferFunction(), uiMedData::editor::SOrganTransformation::updating(), ctrlCamp::SExtractMeshByType::updating(), ioAtoms::SReader::updating(), and ctrlSelection::updater::SDrop::~SDrop().
void fwDataTools::helper::Composite::remove (std::string _compositeKey)
Remove an object in the composite.
Parameters
[in] _compositeKey key of the object in the composite.
Prepare the message to announce the modification.
Definition at line 50 of file SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp.
References OSLM_FATAL_IF.
Referenced by ctrlSelection::updater::SObjFromUid::remove(), ctrlSelection::updater::SObjFromSlot::remove(), visuVTKAdaptor::PlaneSelectionNotifier::selectPlane(), ctrlCamp::SExtractObj::stopping(), uiTF::TransferFunctionEditor::stopping(), and uiMedData::editor::SOrganTransformation::updating().
void fwDataTools::helper::Composite::swap (std::string _compositeKey, ::fwData::Object::sptr _newObject)
Replace an object in the composite.
Parameters
[in] _compositeKey key of the object in the composite.
[in] _newObject the new object to add in the composite.
Prepare the message to announce the modification.
Definition at line 84 of file SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp.
References OSLM_FATAL_IF, and OSLM_INFO.
Referenced by ctrlCamp::SExtractObj::stopping(), ctrlSelection::updater::SObjFromUid::swap(), ctrlSelection::updater::SObjFromSlot::swap(), uiImage::WindowLevel::swapCurrentTFAndNotify(), uiTF::TransferFunctionEditor::updateTransferFunction(), and uiMedData::editor::SOrganTransformation::updating().
The documentation for this class was generated from the following files:
SrcLib/core/fwDataTools/include/fwDataTools/helper/Composite.hpp
SrcLib/core/fwDataTools/src/fwDataTools/helper/Composite.cpp