fw4spl: fwDataTools::helper::MedicalImageAdaptor Class Reference
fwDataTools::helper::MedicalImageAdaptor Class Reference
Helpers for medical image.
#include <MedicalImageAdaptor.hpp>
Public Types
enum Orientation { X_AXIS = 0, Y_AXIS, Z_AXIS }
Image orientation.
Public Member Functions
virtual bool isA (const std::string &type) const
virtual FWDATATOOLS_API ~MedicalImageAdaptor ()
Destructor. Do nothing.
virtual FWDATATOOLS_API void setOrientation (Orientation orientation)
Set the image orientation.
Orientation getOrientation () const
Return the image orientation.
FWDATATOOLS_API void setTFSelectionFwID (const std::string &fwid)
Set TF Selection fwID.
FWDATATOOLS_API const std::string & getTFSelectionFwID () const
Get TF Selection fwID.
FWDATATOOLS_API void setTransferFunctionSelection (::fwData::Composite::wptr selection)
Set TF Selection fwID.
FWDATATOOLS_API void setSelectedTFKey (const std::string &key)
Set selected TF Key.
FWDATATOOLS_API const std::string & getSelectedTFKey () const
Get selected TF Key.
FWDATATOOLS_API void parseTFConfig (::fwRuntime::ConfigurationElement::sptr configuration)
Set selected TF Key and TF Selection fwID from config.
FWDATATOOLS_API double getWindow () const
Get the window of the selected tf.
FWDATATOOLS_API void setWindow (double window)
Set the window of the selected tf.
FWDATATOOLS_API void setWindowLevel (double windowMin, double windowMax)
Set the window level of the selected tf from window min/max.
FWDATATOOLS_API double getLevel () const
Get the level of the selected tf.
FWDATATOOLS_API void setLevel (double level)
Set the level of the selected tf.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Protected Member Functions
FWDATATOOLS_API MedicalImageAdaptor ()
Constructor. Do nothing.
FWDATATOOLS_API void setOrientation (int orientation)
Set the orientation of the image.
FWDATATOOLS_API void getImageSpacing (double spacing[3])
Get the image spacing.
FWDATATOOLS_API void getImageOrigin (double origin[3])
Get the image origin.
FWDATATOOLS_API void getImageDataSize (int size[3])
Get the image data size (number of slices).
FWDATATOOLS_API void getImageSize (double size[3])
Get the image size (= dataSize * spacing).
FWDATATOOLS_API void getCurrentSliceCenter (double center[3])
Get the slice center.
FWDATATOOLS_API void worldToSliceIndex (const double world[3], int index[3])
Convert world coordinates to slice index coordinates.
FWDATATOOLS_API void worldToImageSliceIndex (const double world[3], int index[3])
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void sliceIndexToWorld (const int index[3], double world[3])
Convert from world coordinates system to image coordinates system.
template<typename FLOAT_ARRAY_3 >
void getImageSpacing (FLOAT_ARRAY_3 spacing)
Get the image spacing.
template<typename INT_INDEX >
void getImageDataSize (INT_INDEX size)
Get the image data size (number of slices).
template<typename WORLD , typename INT_INDEX >
void worldToSliceIndex (const WORLD world, INT_INDEX index)
Convert world coordinates to slice index coordinates.
template<typename WORLD , typename INT_INDEX >
void worldToImageSliceIndex (const WORLD world, INT_INDEX index)
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void getPlane (double points[4][3], int sliceNumber)
Return the 4 points of the image plane.
FWDATATOOLS_API bool setSliceIndex (const int index[3])
Set the slice index.
FWDATATOOLS_API void getSliceIndex (::fwData::Integer::sptr index[3])
Get the slice index.
FWDATATOOLS_API::fwData::TransferFunction::sptr getTransferFunction () const
Get the current transfer function.
FWDATATOOLS_API::fwData::Composite::sptr getTransferFunctionSelection () const
Get the current transfer function selection.
FWDATATOOLS_API void updateImageInfos (::fwData::Image::sptr image)
Update the image information (slice index, min/max,...)
FWDATATOOLS_API void updateTransferFunction (::fwData::Image::sptr image)
Update the transfer function information.
FWDATATOOLS_API::fwData::Image::sptr getImage ()
Return the image.
Protected Attributes
Orientation m_orientation
Image orientation.
::fwData::Image::wptr m_weakImage
Current image.
::fwData::Integer::sptr m_axialIndex
Axial slice index.
::fwData::Integer::sptr m_frontalIndex
Frontal slice index.
::fwData::Integer::sptr m_sagittalIndex
Sagittal slice index.
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Connections to transfer function
typedef ::fwCom::Slot< void(::fwData::Composite::ContainerType)> AddedObjectsSlotType
Slot called when objects are added into the composite.
typedef ::fwCom::Slot< void(::fwData::Composite::ContainerType,::fwData::Composite::ContainerType)> ChangedObjectsSlotType
Slot called when objects are added into the composite.
typedef ::fwCom::Slot< void(::fwData::Composite::ContainerType)> RemovedObjectsSlotType
Slot called when objects are added into the composite.
typedef ::fwCom::Slot< void()> UpdateTFPointsSlotType
Slot called when objects are added into the composite.
typedef ::fwCom::Slot< void(double, double)> UpdateTFWindowingSlotType
Slot called when objects are added into the composite.
AddedObjectsSlotType::sptr m_slotAddedObjects
Slot called when objects are added into the composite.
ChangedObjectsSlotType::sptr m_slotChangedObjects
Slot called when objects are changed into the composite.
RemovedObjectsSlotType::sptr m_slotRemovedObjects
Slot called when objects are removed from the composite.
UpdateTFPointsSlotType::sptr m_slotUpdateTFPoints
Slot called when transfer function points are modified.
UpdateTFWindowingSlotType::sptr m_slotUpdateTFWindowing
Slot called when transfer function windowing is modified.
FWDATATOOLS_API void installTFConnections ()
Install connections to listen TF modifications.
FWDATATOOLS_API void removeTFConnections ()
Remove the TF connections.
virtual FWDATATOOLS_API void updatingTFPoints ()
Called when transfer function points are modified.
virtual FWDATATOOLS_API void updatingTFWindowing (double window, double level)
Called when transfer function windowing is modified.
FWDATATOOLS_API void installTFSlots (::fwCom::HasSlots *hasslots)
Install the slots to managed TF modifications.
void addObjects (::fwData::Composite::ContainerType objects)
Slot: add objects.
void changeObjects (::fwData::Composite::ContainerType newObjects,::fwData::Composite::ContainerType oldObjects)
Slot: change objects.
void removeObjects (::fwData::Composite::ContainerType objects)
Slot: remove objects.
void updateTFPoints ()
Slot: called when transfer function points are modified.
void updateTFWindowing (double window, double level)
Slot: called when transfer function windowing is modified.
Detailed Description
Helpers for medical image.
Definition at line 37 of file MedicalImageAdaptor.hpp.
Member Function Documentation
void fwDataTools::helper::MedicalImageAdaptor::getCurrentSliceCenter (double center[3]) protected
Get the slice center.
Parameters
[out] center : the slice center
Definition at line 96 of file MedicalImageAdaptor.cpp.
References getImage(), getImageOrigin(), getImageSize(), getImageSpacing(), getSliceIndex(), and m_orientation.
void fwDataTools::helper::MedicalImageAdaptor::getImageDataSize (int size[3]) protected
Get the image data size (number of slices).
Parameters
[out] size : the image size
Definition at line 70 of file MedicalImageAdaptor.cpp.
References getImage().
Referenced by worldToImageSliceIndex().
template<typename INT_INDEX > void fwDataTools::helper::MedicalImageAdaptor::getImageDataSize (INT_INDEX size) protected
Get the image data size (number of slices).
Parameters
[out] size : the image size
Definition at line 351 of file MedicalImageAdaptor.hpp.
void fwDataTools::helper::MedicalImageAdaptor::getImageOrigin (double origin[3]) protected
Get the image origin.
Parameters
[out] origin : the image origin
Definition at line 61 of file MedicalImageAdaptor.cpp.
References getImage().
Referenced by getCurrentSliceCenter(), sliceIndexToWorld(), and worldToSliceIndex().
void fwDataTools::helper::MedicalImageAdaptor::getImageSize (double size[3]) protected
Get the image size (= dataSize * spacing).
Parameters
[out] size : the image size
Definition at line 80 of file MedicalImageAdaptor.cpp.
References getImage(), and getImageSpacing().
Referenced by getCurrentSliceCenter().
void fwDataTools::helper::MedicalImageAdaptor::getImageSpacing (double spacing[3]) protected
Get the image spacing.
Parameters
[out] spacing : the image spacing
Definition at line 51 of file MedicalImageAdaptor.cpp.
References getImage().
Referenced by getCurrentSliceCenter(), getImageSize(), sliceIndexToWorld(), and worldToSliceIndex().
template<typename FLOAT_ARRAY_3 > void fwDataTools::helper::MedicalImageAdaptor::getImageSpacing (FLOAT_ARRAY_3 spacing) protected
Get the image spacing.
Parameters
[out] spacing : the image spacing
Definition at line 341 of file MedicalImageAdaptor.hpp.
void fwDataTools::helper::MedicalImageAdaptor::getPlane (double points[4][3], int sliceNumber) protected
Return the 4 points of the image plane.
points are ordered in the following way : image origin is the first point
points are inserted using the preference follow X axis if exists, if not exists follow Y axis if Y axis is not present follow Z axis
Definition at line 143 of file MedicalImageAdaptor.cpp.
References getImage(), and m_orientation.
void fwDataTools::helper::MedicalImageAdaptor::installTFSlots (::fwCom::HasSlots * hasslots) protected
Install the slots to managed TF modifications.
Creates slots to listen TF selection Composite and TransferFunction signals.
Warning
It must be called in the service constructor
Definition at line 513 of file MedicalImageAdaptor.cpp.
References addObjects(), changeObjects(), m_slotAddedObjects, m_slotChangedObjects, m_slotRemovedObjects, m_slotUpdateTFPoints, m_slotUpdateTFWindowing, removeObjects(), updateTFPoints(), and updateTFWindowing().
Referenced by scene2D::adaptor::TransferFunction::TransferFunction().
void fwDataTools::helper::MedicalImageAdaptor::setOrientation (int orientation) protected
Set the orientation of the image.
Parameters
[in] orientation must be 0 (X_AXIS), 1 (Y_AXIS) or 2 (Z_AXIS).
Definition at line 130 of file MedicalImageAdaptor.cpp.
References OSLM_ASSERT, and setOrientation().
void fwDataTools::helper::MedicalImageAdaptor::sliceIndexToWorld (const int index[3], double world[3]) protected
Convert from world coordinates system to image coordinates system.
Parameters
[in] index : coordinate in the image
[out] world : coordinate in the world
Definition at line 167 of file MedicalImageAdaptor.cpp.
References getImageOrigin(), and getImageSpacing().
void fwDataTools::helper::MedicalImageAdaptor::updatingTFPoints () protected virtual
Called when transfer function points are modified.
It must be reimplemented to upadte TF.
Reimplemented in uiImage::WindowLevel, visuVTKVRAdaptor::Volume, scene2D::adaptor::TransferFunction, visuVTKAdaptor::Image, visuVTKAdaptor::ImageText, and scene2D::adaptor::Negato.
Definition at line 539 of file MedicalImageAdaptor.cpp.
References SLM_ASSERT.
Referenced by updateTFPoints().
void fwDataTools::helper::MedicalImageAdaptor::updatingTFWindowing (double window, double level) protected virtual
Called when transfer function windowing is modified.
It must be reimplemented to upadte TF.
Reimplemented in uiImage::WindowLevel, visuVTKVRAdaptor::Volume, scene2D::adaptor::TransferFunction, visuVTKAdaptor::Image, visuVTKAdaptor::ImageText, and scene2D::adaptor::Negato.
Definition at line 546 of file MedicalImageAdaptor.cpp.
References SLM_ASSERT.
Referenced by updateTFWindowing().
void fwDataTools::helper::MedicalImageAdaptor::worldToImageSliceIndex (const double world[3], int index[3]) protected
Convert coordinates in the world to coordinates in the image.
Parameters
[in] world : coordinate in the world
[out] index : coordinate in the image
Definition at line 198 of file MedicalImageAdaptor.cpp.
References getImageDataSize(), and worldToSliceIndex().
template<typename WORLD , typename INT_INDEX > void fwDataTools::helper::MedicalImageAdaptor::worldToImageSliceIndex (const WORLD world, INT_INDEX index) protected
Convert coordinates in the world to coordinates in the image.
Parameters
[in] world : coordinate in the world
[out] index : coordinate in the image
Definition at line 379 of file MedicalImageAdaptor.hpp.
void fwDataTools::helper::MedicalImageAdaptor::worldToSliceIndex (const double world[3], int index[3]) protected
Convert world coordinates to slice index coordinates.
Parameters
[in] world : coordinate in the world
[out] index : coordinate in the slice index
Definition at line 181 of file MedicalImageAdaptor.cpp.
References getImageOrigin(), and getImageSpacing().
Referenced by worldToImageSliceIndex().
template<typename WORLD , typename INT_INDEX > void fwDataTools::helper::MedicalImageAdaptor::worldToSliceIndex (const WORLD world, INT_INDEX index) protected
Convert world coordinates to slice index coordinates.
Parameters
[in] world : coordinate in the world
[out] index : coordinate in the slice index
Definition at line 362 of file MedicalImageAdaptor.hpp.
The documentation for this class was generated from the following files:
MedicalImageAdaptor.hpp
MedicalImageAdaptor.cpp