fw4spl: ioData::CameraReaderService Class Reference
ioData::CameraReaderService Class Reference
Camera calibration file reader service.
#include <CameraReaderService.hpp>
Public Types
typedef ::io::IReader SuperClass
Super class of reader services.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((CameraReaderService)(::io::IReader))
virtual void configureWithIHM ()
Configure the path : default does nothing.
Protected Member Functions
virtual IODATA_API::io::IOPathType getIOPathType () const
Return path type managed by the service, here FILE.
Service methods (override from ::fwServices::IService)
virtual void starting () throw (::fwTools::Failed)
Starting method : default does nothing.
virtual void stopping () throw (::fwTools::Failed)
Stopping method : default does nothing.
IODATA_API void updating () throw (::fwTools::Failed)
Updating method. This method is called by update() from base service (fwServices::IService)
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : default does nothing.
virtual IODATA_API void info (std::ostream &_sstream)
Info method.
Specified reader service methods (override from ::io::IReader)
virtual IODATA_API std::vector
< std::string > getSupportedExtensions ()
returns (filename) extension
Detailed Description
Camera calibration file reader service.
Date:
2009.
Service reading camera calibration file and create a camera object.
This service has no specified start and stop method.
Use setConfiguration(cfg) and configure() methods to configure the filename.
Use update() to load the file, create the camera object and notify reading to observers.
Service registered details :
fwServicesRegisterMacro(::io::IReader , ::ioData::CameraReaderService , ::fwData::Camera)
Definition at line 33 of file CameraReaderService.hpp.
Member Function Documentation
virtual void ioData::CameraReaderService::configureWithIHM () [inline, virtual]
Configure the path : default does nothing.
This method is used to find the file path using a file selector.
Implements io::IReader.
Definition at line 46 of file CameraReaderService.hpp.
void ioData::CameraReaderService::info (std::ostream & _sstream) [protected, virtual]
Info method.
This method is used to give informations about the service.
Parameters:
[out] _sstream output stream
Reimplemented from fwServices::IService.
Definition at line 29 of file CameraReaderService.cpp.
References fwServices::IService::info().
void ioData::CameraReaderService::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [inline, protected]
React on modifications : default does nothing.
Note:
This method is automaticaly called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 85 of file CameraReaderService.hpp.
virtual void ioData::CameraReaderService::starting () throw (::fwTools::Failed) [inline, protected, virtual]
Starting method : default does nothing.
This method is used to initialize the service.
Implements fwServices::IService.
Definition at line 60 of file CameraReaderService.hpp.
virtual void ioData::CameraReaderService::stopping () throw (::fwTools::Failed) [inline, protected, virtual]
Stopping method : default does nothing.
The stopping method is empty for this service.
Implements fwServices::IService.
Definition at line 67 of file CameraReaderService.hpp.
void ioData::CameraReaderService::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method. This method is called by update() from base service (fwServices::IService)
This method is used to update the service. Call this method after configuring() to load calibration file. Notify reading.
Implements fwServices::IService.
Definition at line 53 of file CameraReaderService.cpp.
References io::IReader::getFile(), io::IReader::hasLocationDefined(), fwComEd::CameraMsg::NEW_CAMERA, fwServices::IEditionService::notify(), OSLM_INFO, SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
CameraReaderService.hpp
CameraReaderService.cpp