fw4spl: gui::aspect::DefaultMenuBarSrv Class Reference
gui::aspect::DefaultMenuBarSrv Class Reference
Defines the default menubar for standard application.
#include <DefaultMenuBarSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((DefaultMenuBarSrv)(::fwGui::IMenuBarSrv))
GUI_API DefaultMenuBarSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~DefaultMenuBarSrv () throw ()
Destructor. Do nothing.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual GUI_API void configuring () throw (::fwTools::Failed)
Configuring method allows to configure an application with menu bar. Example of configuration.
virtual GUI_API void starting () throw (::fwTools::Failed)
Create the menus and start the managed services.
virtual GUI_API void stopping () throw (::fwTools::Failed)
Stop all menu of this menuBar and destroy MenuBar.
virtual GUI_API void updating () throw (::fwTools::Failed)
Updating service, do nothing.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Updating service on notification, do nothing.
Detailed Description
Defines the default menubar for standard application.
Definition at line 23 of file DefaultMenuBarSrv.hpp.
Member Function Documentation
void gui::aspect::DefaultMenuBarSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method allows to configure an application with menu bar. Example of configuration.
      <service uid="menuBar" type="::fwGui::IMenuBarSrv" impl="::gui::aspect::DefaultMenuBarSrv" autoConnect="no" >
          <gui>
              <layout>
                  <menu name="My Menu"/>
                  <menu name="My Menu 2"/>
              </layout>
          </gui>
          <registry>
              <menu sid="myMenu" start="yes" />
              <menu sid="myMenu2" start="yes" />
          </registry>
      </service>
<gui> </gui> : (mandatory) describe the interface of the service.
<registry> </registry> : (mandatory) describe the service management.
sid of the menu services
start or not the menu service automatically
Warning:
The number of item in the gui section must be equal or greater than in the registry section.
The order of the menu in each section (gui and registry) must be the same.
For example: the menu named "My Menu" will be connected with the service which have the sid = "myMenu".
A menu bar can't have the same service connected on two different menu.
See also:
fwGui::IMenuBarSrv::initialize(), fwGui::layoutManager::IMenuBarLayoutManager::initialize()
Implements fwServices::IService.
Definition at line 42 of file DefaultMenuBarSrv.cpp.
References fwGui::IMenuBarSrv::initialize().
void gui::aspect::DefaultMenuBarSrv::starting () throw (::fwTools::Failed) [protected, virtual]
Create the menus and start the managed services.
See also:
fwGui::IMenuBarSrv::create()
Implements fwServices::IService.
Definition at line 49 of file DefaultMenuBarSrv.cpp.
References fwGui::IMenuBarSrv::create(), and SLM_TRACE_FUNC.
void gui::aspect::DefaultMenuBarSrv::stopping () throw (::fwTools::Failed) [protected, virtual]
Stop all menu of this menuBar and destroy MenuBar.
See also:
fwGui::IMenuBarSrv::destroy()
Implements fwServices::IService.
Definition at line 57 of file DefaultMenuBarSrv.cpp.
References fwGui::IMenuBarSrv::destroy(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
DefaultMenuBarSrv.hpp
DefaultMenuBarSrv.cpp