fw4spl: fwTest::generator::Mesh Class Reference
fwTest::generator::Mesh Class Reference
This helper generates a mesh using specified structure (quad or triangle).
#include <Mesh.hpp>
Public Types
typedef std::map
< ::fwDataTools::Point,::fwData::Mesh::Id > PointsMapType
Static Public Member Functions
static FWTEST_API void initRand ()
Initialize 'rand' seed.
static FWTEST_API void generateMesh (::fwData::Mesh::sptr mesh)
Generate a mesh.
static FWTEST_API void addQuadMesh (::fwData::Mesh::sptr mesh, PointsMapType &points, size_t nbPointsByEdge=10, float edgeDim=100.)
Add quad cells in mesh, this method generates synthetic data (two face of a cube).
static FWTEST_API void addTriangleMesh (::fwData::Mesh::sptr mesh, PointsMapType &points, size_t nbPointsByEdge=10, float edgeDim=100.)
Add triangle cells in mesh, this method generates synthetic data (two face of a cube).
static FWTEST_API void generateQuadMesh (::fwData::Mesh::sptr mesh)
Generate a quad mesh.
static FWTEST_API void generateTriangleMesh (::fwData::Mesh::sptr mesh)
Generate a triangle mesh.
static FWTEST_API void generateTriangleQuadMesh (::fwData::Mesh::sptr mesh)
Generate a mesh with quad and triangle cells.
Static Protected Member Functions
static FWTEST_API::fwData::Mesh::Id addPoint (::fwData::Mesh::PointValueType *pt,::fwComEd::helper::Mesh::sptr meshHelper, PointsMapType &points)
Detailed Description
This helper generates a mesh using specified structure (quad or triangle).
Definition at line 30 of file SrcLib/tests/fwTest/include/fwTest/generator/Mesh.hpp.
Member Function Documentation
void fwTest::generator::Mesh::addQuadMesh (::fwData::Mesh::sptr mesh, PointsMapType & points, size_t nbPointsByEdge = 10, float edgeDim = 100.) [static]
Add quad cells in mesh, this method generates synthetic data (two face of a cube).
Parameters:
[out] mesh fwData::Mesh Mesh structure to fill with quad cells.
[in] points PointsMapType Point registration map used to not create point which already in mesh buffer.
[in] nbPointsByEdge size_t Number of points by edge.
[in] edgeDim float Edge dimension in 3D world.
Definition at line 90 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
Referenced by generateQuadMesh(), and generateTriangleQuadMesh().
void fwTest::generator::Mesh::addTriangleMesh (::fwData::Mesh::sptr mesh, PointsMapType & points, size_t nbPointsByEdge = 10, float edgeDim = 100.) [static]
Add triangle cells in mesh, this method generates synthetic data (two face of a cube).
Parameters:
[out] mesh fwData::Mesh Mesh structure to fill with triangle cells.
[in] points PointsMapType Point registration map used to not create point which already in mesh buffer.
[in] nbPointsByEdge size_t Number of points by edge.
[in] edgeDim float Edge dimension in 3D world.
Definition at line 162 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
Referenced by generateTriangleMesh(), and generateTriangleQuadMesh().
void fwTest::generator::Mesh::generateMesh (::fwData::Mesh::sptr mesh) [static]
Generate a mesh.
Parameters:
mesh mesh to generate
Definition at line 40 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
References fwDataTools::Mesh::colorizeMeshCells(), fwDataTools::Mesh::colorizeMeshPoints(), fwDataTools::Mesh::generateCellNormals(), fwDataTools::Mesh::generatePointNormals(), generateTriangleMesh(), initRand(), and fwDataTools::Mesh::shakePoint().
Referenced by fwTest::generator::SeriesDB::generateReconstruction().
void fwTest::generator::Mesh::generateQuadMesh (::fwData::Mesh::sptr mesh) [static]
Generate a quad mesh.
See also:
addQuadMesh
Parameters:
[out] mesh fwData::Mesh empty mesh structure to fill with quad cells.
Definition at line 79 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
References addQuadMesh().
void fwTest::generator::Mesh::generateTriangleMesh (::fwData::Mesh::sptr mesh) [static]
Generate a triangle mesh.
See also:
addTriangleMesh
Parameters:
[out] mesh fwData::Mesh empty mesh structure to fill with triangle cell.
Definition at line 67 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
References addTriangleMesh().
Referenced by generateMesh().
void fwTest::generator::Mesh::generateTriangleQuadMesh (::fwData::Mesh::sptr mesh) [static]
Generate a mesh with quad and triangle cells.
See also:
addQuadMesh
addTriangleMesh
Parameters:
[out] mesh fwData::Mesh empty mesh structure to fill with quad and triangle cells.
Definition at line 54 of file SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp.
References addQuadMesh(), and addTriangleMesh().
The documentation for this class was generated from the following files:
SrcLib/tests/fwTest/include/fwTest/generator/Mesh.hpp
SrcLib/tests/fwTest/src/fwTest/generator/Mesh.cpp