fw4spl: fwDcmtkIO::reader::main::ImageLazyReader Class Reference
fwDcmtkIO::reader::main::ImageLazyReader Class Reference
This class is used to read the buffer of a DICOM image in LAZY mode.
#include <ImageLazyReader.hpp>
Static Public Member Functions
static FWDCMTKIO_API void * createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr &instance, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation,::fwTools::Type imageType)
Create an instance buffer according to the image type.
Static Protected Member Functions
template<typename T >
static FWDCMTKIO_API void * createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr &instance, double rescaleSlope, double rescaleIntercept,::fwTools::Type imageType)
Create an instance buffer according to the image type. The template T is used to determine if we must use signed or unsigned short when reading pixels.
template<typename T , typename U >
static FWDCMTKIO_API U * createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr &instance, double rescaleSlope, double rescaleIntercept)
Create an instance buffer according to the image type. The template T is used to determine if we must use signed or unsigned short when reading pixels. The template U is used to determine what kind of buffer must be created.
Detailed Description
This class is used to read the buffer of a DICOM image in LAZY mode.
Definition at line 33 of file ImageLazyReader.hpp.
Member Function Documentation
static FWDCMTKIO_API void* fwDcmtkIO::reader::main::ImageLazyReader::createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr & instance, double rescaleSlope, double rescaleIntercept, unsigned short pixelRepresentation, ::fwTools::Type imageType) inline static
Create an instance buffer according to the image type.
Parameters
[in] rows Number of rows
[in] columns Number of columns
[in] instance Path to the instance
[in] rescaleSlope Slope parameter
[in] rescaleIntercept Intercept parameter
[in] pixelRepresentation Pixel representation of the image (signed or unsigned short)
[in] imageType Type of the image used to create the buffer
Definition at line 46 of file ImageLazyReader.hpp.
References fwTools::Type::sizeOf().
Referenced by fwDcmtkIO::reader::main::ImageLazySource::ImageLazySource(), and fwDcmtkIO::reader::main::ImageLazySource::read().
template<typename T > static FWDCMTKIO_API void* fwDcmtkIO::reader::main::ImageLazyReader::createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr & instance, double rescaleSlope, double rescaleIntercept, ::fwTools::Type imageType) inline static protected
Create an instance buffer according to the image type. The template T is used to determine if we must use signed or unsigned short when reading pixels.
Parameters
[in] rows Number of rows
[in] columns Number of columns
[in] instance Path to the instance
[in] rescaleSlope Slope parameter
[in] rescaleIntercept Intercept parameter
[in] imageType Type of the image used to create the buffer
Definition at line 98 of file ImageLazyReader.hpp.
template<typename T , typename U > static FWDCMTKIO_API U* fwDcmtkIO::reader::main::ImageLazyReader::createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr & instance, double rescaleSlope, double rescaleIntercept) inline static protected
Create an instance buffer according to the image type. The template T is used to determine if we must use signed or unsigned short when reading pixels. The template U is used to determine what kind of buffer must be created.
Parameters
[in] rows Number of rows
[in] columns Number of columns
[in] instance Path to the instance
[in] rescaleSlope Slope parameter
[in] rescaleIntercept Intercept parameter
Definition at line 173 of file ImageLazyReader.hpp.
References fwDcmtkIO::helper::Codec::cleanup(), fwMemory::BufferObject::LockBase< T >::getBuffer(), OSLM_WARN_IF, and fwDcmtkIO::helper::Codec::registerCodecs().
The documentation for this class was generated from the following file:
ImageLazyReader.hpp