fw4spl: fwComEd::helper::Image Class Reference
fwComEd::helper::Image Class Reference
Defines an helper to modify an fwData::Image by adding few medical fields and create in parallel the message to announce these modifications.
#include <Image.hpp>
Public Types
typedef ::fwData::Image::SizeType SizeType
typedef ::fwData::Image::IndexType IndexType
typedef ::fwData::Image::BufferType BufferType
typedef ::fwData::Image::BufferIndexType BufferIndexType
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Image))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Image,(((::fwData::Image::sptr))))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Image)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWCOMED_API Image (::fwData::Image::sptr image)
Constructor. Initialize parameters.
virtual FWCOMED_API ~Image ()
Destrucotr. Do nothing.
FWCOMED_API bool createLandmarks ()
Create landmark fields if not exist, NOT GENERATE MESSAGE.
FWCOMED_API bool createTransferFunctionPool ()
Create transfer function pool if the pool is not present, NOT GENERATE MESSAGE.
FWCOMED_API bool createImageSliceIndex ()
Create slice index if indexes are not present, NOT GENERATE MESSAGE.
FWCOMED_API void notify (::fwServices::IService::sptr _serviceSource)
Send the message of modification.
FWCOMED_API void * getBuffer ()
Returns image buffer.
FWCOMED_API::fwMemory::BufferObject::Lock getLock () const
Returns a copy of current lock on image.
FWCOMED_API void * getPixelBuffer (SizeType::value_type x, SizeType::value_type y, SizeType::value_type z)
Helpers for 3D images.
FWCOMED_API void * getPixelBuffer (IndexType index)
Helpers for 3D images.
FWCOMED_API void setPixelBuffer (IndexType index, Image::BufferType *pixBuf)
Helpers for 3D images.
FWCOMED_API const std::string getPixelAsString (SizeType::value_type x, SizeType::value_type y, SizeType::value_type z)
Helpers for 3D images.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Defines an helper to modify an fwData::Image by adding few medical fields and create in parallel the message to announce these modifications.
Definition at line 26 of file SrcLib/core/fwComEd/include/fwComEd/helper/Image.hpp.
Member Function Documentation
fwComEd::helper::Image::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Image, (((::fwData::Image::sptr))))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Image)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Image)).
bool fwComEd::helper::Image::createImageSliceIndex ()
Create slice index if indexes are not present, NOT GENERATE MESSAGE.
If the image hasn't frontal, axial and sagittal slice index fields, they are added.
Returns
true if the fields are added.
Definition at line 114 of file SrcLib/core/fwComEd/src/fwComEd/helper/Image.cpp.
References fwComEd::Dictionary::m_axialSliceIndexId, fwComEd::Dictionary::m_frontalSliceIndexId, fwComEd::Dictionary::m_sagittalSliceIndexId, and SLM_ASSERT.
bool fwComEd::helper::Image::createLandmarks ()
Create landmark fields if not exist, NOT GENERATE MESSAGE.
If the image hasn't landmark field, it is added and the method return true.
Returns
true if the field is added.
Definition at line 47 of file SrcLib/core/fwComEd/src/fwComEd/helper/Image.cpp.
References fwComEd::Dictionary::m_imageLandmarksId.
bool fwComEd::helper::Image::createTransferFunctionPool ()
Create transfer function pool if the pool is not present, NOT GENERATE MESSAGE.
If the image has not transfer functions, the pool is created and a grey level transfer function is added.
Definition at line 65 of file SrcLib/core/fwComEd/src/fwComEd/helper/Image.cpp.
References fwComEd::helper::Composite::add(), fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwComEd::fieldHelper::MedicalImageHelpers::getMinMax(), fwComEd::Dictionary::m_transferFunctionCompositeId, fwComEd::helper::Field::notify(), fwComEd::helper::Composite::notify(), fwData::TransferFunction::s_DEFAULT_TF_NAME, and fwComEd::helper::Field::setField().
Referenced by fwComEd::helper::MedicalImageAdaptor::updateTransferFunction().
The documentation for this class was generated from the following files:
SrcLib/core/fwComEd/include/fwComEd/helper/Image.hpp
SrcLib/core/fwComEd/src/fwComEd/helper/Image.cpp