fw4spl: fwGdcmIO::writer::tid::Measurement Class Reference
fwGdcmIO::writer::tid::Measurement Class Reference
Measurement TID.
#include <Measurement.hpp>
Public Member Functions
FWGDCMIO_API Measurement (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::csptr &image)
Constructor.
virtual FWGDCMIO_API ~Measurement ()
Destructor.
virtual FWGDCMIO_API void createNodes (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &parent, bool useSCoord3D=true)
Create nodes according to the template.
Public Member Functions inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
FWGDCMIO_API TemplateID (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< const ::fwData::Image > &object)
Constructor.
virtual FWGDCMIO_API ~TemplateID ()
Destructor.
Protected Member Functions
void createMeasurement (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &parent, const std::shared_ptr< const ::fwData::PointList > &pointList, unsigned int id, bool useSCoord3D)
Create a measurement node.
Additional Inherited Members
Protected Attributes inherited from fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >
std::shared_ptr< ::gdcm::Writer > m_writer
GDCM Writer.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< const ::fwData::Image > m_object
FW4SPL Object.
Detailed Description
Measurement TID.
See also
TID 300
Definition at line 30 of file writer/tid/Measurement.hpp.
Constructor & Destructor Documentation
fwGdcmIO::writer::tid::Measurement::Measurement (const std::shared_ptr< ::gdcm::Writer > & writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::csptr & image)
Constructor.
Parameters
[in] writer GDCM writer that must be enriched
[in] instance DICOM instance used to share informations between modules
[in] image Image data
Definition at line 43 of file writer/tid/Measurement.cpp.
Member Function Documentation
void fwGdcmIO::writer::tid::Measurement::createMeasurement (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & parent, const std::shared_ptr< const ::fwData::PointList > & pointList, unsigned int id, bool useSCoord3D) protected
Create a measurement node.
Parameters
[in] parent Parent node
[in] pointList Pointlist containing distance points
[in] id ID of the ficudial
[in] useSCoord3D True if we must use 3D coordinates
Definition at line 79 of file writer/tid/Measurement.cpp.
References fwGdcmIO::container::sr::DicomSRNode::addSubNode(), fwGdcmIO::helper::DicomDataTools::convertPointToFrameNumber(), fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_instance, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object, SLM_ASSERT, and SPTR.
Referenced by createNodes().
void fwGdcmIO::writer::tid::Measurement::createNodes (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & parent, bool useSCoord3D = true) virtual
Create nodes according to the template.
Parameters
[in] parent Parent node
[in] useSCoord3D True if we must write SCOORD3D, false if we must write SCOORD
Definition at line 58 of file writer/tid/Measurement.cpp.
References createMeasurement(), fwDataTools::fieldHelper::Image::m_imageDistancesId, and fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object.
Referenced by fwGdcmIO::writer::tid::MeasurementReport::createRootNode().
The documentation for this class was generated from the following files:
writer/tid/Measurement.hpp
writer/tid/Measurement.cpp