fw4spl: gui::action::ModifyLayoutActionSrv Class Reference
gui::action::ModifyLayoutActionSrv Class Reference
This action is used to modify the layout configuration.
#include <ModifyLayoutActionSrv.hpp>
Public Types
typedef
::fwRuntime::ConfigurationElement::sptr ConfigurationType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ModifyLayoutActionSrv)(::fwGui::IActionSrv))
GUI_API ModifyLayoutActionSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~ModifyLayoutActionSrv () throw ()
Destructor. Do nothing.
Protected Types
enum ActionType {
MOVE, SHOW, HIDE, SHOW_OR_HIDE,
ENABLE, DISABLE, DO_NOTHING
}
Protected Member Functions
virtual GUI_API void info (std::ostream &_sstream)
This method gives information about the class. Do nothing.
GUI_API void updating () throw (fwTools::Failed)
This method starts-updates or stops the specified services.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
This method is used to update services on notification. Do nothing.
GUI_API void configuring () throw (::fwTools::Failed)
This method is used to configure the service parameters: specifies which views to show/hide/mode.
virtual GUI_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual GUI_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
Detailed Description
This action is used to modify the layout configuration.
Definition at line 28 of file ModifyLayoutActionSrv.hpp.
Member Function Documentation
void gui::action::ModifyLayoutActionSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
This method is used to configure the service parameters: specifies which views to show/hide/mode.
     <config>
         <move uid="srv_uid" wid="new_view_wid" />
         <show wid="view_to_show" />
         <hide wid="view_to_hide />
         <show_or_hide wid="view_to_show_or_hide />
         <enable uid="action_to_enabled" />
         <disable uid="action_to_disabled" />
     </config>
move configures the services to move in the new view given by wid
show configures the view to show
hide configures the view to hide
show or hide configures the view to show or hide. If the action is activated, the view is shown else it is hidden. The action in the menu/toolbar must be checkable (style="check").
Implements fwServices::IService.
Definition at line 139 of file ModifyLayoutActionSrv.cpp.
References fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, OSLM_FATAL, SLM_ASSERT, and SLM_TRACE_FUNC.
void gui::action::ModifyLayoutActionSrv::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 44 of file ModifyLayoutActionSrv.cpp.
References fwGui::IActionSrv::actionServiceStarting(), and SLM_TRACE_FUNC.
void gui::action::ModifyLayoutActionSrv::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 52 of file ModifyLayoutActionSrv.cpp.
References fwGui::IActionSrv::actionServiceStopping(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
ModifyLayoutActionSrv.hpp
ModifyLayoutActionSrv.cpp