fw4spl: io::IReader Class Reference
io::IReader Class Reference
Reader service API. It manages extension points definition and extension configurationThis class represents the base interface for reader services. Use the base service methods :
#include <IReader.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IReader)(::fwServices::IService))
Specific service methods for reading
virtual IO_API void configureWithIHM ()=0
Configure the image path (by default does nothing).
virtual IO_API std::vector
< std::string > getSupportedExtensions ()
returns (filename) extension
virtual IO_API std::string getSelectorDialogTitle ()
returns the title of selector dialog box
virtual IO_API::io::IOPathType getIOPathType () const
This method must be implemented by concrete service readers that use path file system to read data.
IO_APIconst::boost::filesystem::path & getFile () const
Returns the file path setted by user or setted during service configuration.
IO_API void setFile (const ::boost::filesystem::path &file)
Sets file path.
IO_APIconst::io::LocationsType & getFiles () const
Returns file paths setted by user or setted during service configuration.
IO_API void setFiles (const ::io::LocationsType &files)
Sets file paths.
IO_APIconst::boost::filesystem::path & getFolder () const
Returns folder path setted by user or setted during service configuration.
IO_API void clearLocations ()
Clear any location set by the setFile/setFiles/setFolder setter.
IO_APIconst::io::LocationsType & getLocations () const
Returns file/files/folder paths setted by user or setted during service configuration.
IO_API void setFolder (const ::boost::filesystem::path &folder)
Sets folder path.
IO_API bool hasLocationDefined () const
Returns if a location has been defined (by the configuration process or directly by user)
Protected Member Functions
virtual IO_API void configuring () throw (fwTools::Failed)
This method proposes to parse xml configuration to retrieve file/files/folder paths.
Detailed Description
Reader service API. It manages extension points definition and extension configuration
This class represents the base interface for reader services. Use the base service methods :
The service is configured with methods setConfiguration(cfg) and configure()
The method start() initialize the service
To read the object use update() method
Finally we must call stop() before deleting the service
Todo:
ACH : remove some methods : getSupportedExtensions ? getSelectorDialogTitle ?
Definition at line 32 of file IReader.hpp.
Member Function Documentation
virtual IO_API void io::IReader::configureWithIHM () [pure virtual]
Configure the image path (by default does nothing).
This method is used to find the file path using a file selector.
Implemented in ioTuto::ExternalDataReaderService, ioVtkGdcm::SSeriesDBReader, ioVtkGdcm::SSeriesDBLazyReader, ioITK::SInrSeriesDBReader, ioData::SplineReaderService, ioData::MeshReaderService, ioITK::InrImageReaderService, ioData::TransformationMatrix3DReaderService, ioVTK::SSeriesDBReader, ioVTK::ImageReaderService, ioVTK::MeshReaderService, ioData::CameraReaderService, ioAtoms::SReader, and ioVTK::SModelSeriesReader.
void io::IReader::configuring () throw (fwTools::Failed) [protected, virtual]
This method proposes to parse xml configuration to retrieve file/files/folder paths.
You can implement your configuring method if you wan check another information or information not correspond to a path on filesystem, else you must use this generic approach.
Sample configuration for a file:
     <service ... >
        <file>/home/user/myFile.jpg</file>
     </service>
Sample configuration for many files:
     <service ... >
        <file>/home/user/myFile01.jpg</file>
        <file>/home/user/myFile02.jpg</file>
        <file>/home/user/myFile03.jpg</file>
     </service>
Sample configuration for a folder:
     <service ... >
        <folder>/home/user/myFolder</folder>
     </service>
Implements fwServices::IService.
Reimplemented in ioAtoms::SReader, ioData::SplineReaderService, and ioTuto::ExternalDataReaderService.
Definition at line 113 of file IReader.cpp.
References io::FILE, io::FILES, io::FOLDER, getIOPathType(), fwServices::IService::m_configuration, setFile(), setFiles(), setFolder(), SLM_ASSERT, and io::TYPE_NOT_DEFINED.
const ::boost::filesystem::path & io::IReader::getFile () const
Returns the file path setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
exception if service not supported FILE management
Definition at line 45 of file IReader.cpp.
References io::FILE, and getIOPathType().
Referenced by ioITK::InrImageReaderService::updating(), ioVTK::ImageReaderService::updating(), ioVTK::MeshReaderService::updating(), ioData::CameraReaderService::updating(), ioTuto::ExternalDataReaderService::updating(), ioData::TransformationMatrix3DReaderService::updating(), ioData::MeshReaderService::updating(), and ioAtoms::SReader::updating().
const ::io::LocationsType & io::IReader::getFiles () const
Returns file paths setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
exception if service not supported FILES management
Definition at line 63 of file IReader.cpp.
References io::FILES, and getIOPathType().
Referenced by ioITK::SInrSeriesDBReader::updating(), ioVTK::SModelSeriesReader::updating(), and ioVTK::SSeriesDBReader::updating().
const ::boost::filesystem::path & io::IReader::getFolder () const
Returns folder path setted by user or setted during service configuration.
Precondition:
exception if a folder path is not defined (m_locations.empty())
exception if service not supported FOLDER management
Definition at line 80 of file IReader.cpp.
References io::FOLDER, and getIOPathType().
Referenced by ioVtkGdcm::SSeriesDBLazyReader::updating(), and ioVtkGdcm::SSeriesDBReader::updating().
io::IOPathType io::IReader::getIOPathType () const [virtual]
This method must be implemented by concrete service readers that use path file system to read data.
This method returns supported path format (file, files or folder). A reader can support file and folder, or files and folder, but not file and files (because files include file concept).
Reimplemented in ioAtoms::SReader, ioData::CameraReaderService, ioTuto::ExternalDataReaderService, ioVtkGdcm::SSeriesDBReader, ioVtkGdcm::SSeriesDBLazyReader, ioITK::SInrSeriesDBReader, ioData::MeshReaderService, ioData::TransformationMatrix3DReaderService, ioITK::InrImageReaderService, ioVTK::ImageReaderService, ioVTK::SSeriesDBReader, ioVTK::MeshReaderService, and ioVTK::SModelSeriesReader.
Definition at line 167 of file IReader.cpp.
References io::TYPE_NOT_DEFINED.
Referenced by configuring(), getFile(), getFiles(), getFolder(), setFile(), setFiles(), and setFolder().
const ::io::LocationsType & io::IReader::getLocations () const
Returns file/files/folder paths setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
Definition at line 98 of file IReader.cpp.
void io::IReader::setFile (const ::boost::filesystem::path & file)
Sets file path.
Precondition:
exception if service not supported FILE management
Definition at line 54 of file IReader.cpp.
References io::FILE, and getIOPathType().
Referenced by ioAtoms::SReader::configureWithIHM(), ioVTK::ImageReaderService::configureWithIHM(), ioVTK::MeshReaderService::configureWithIHM(), ioData::TransformationMatrix3DReaderService::configureWithIHM(), ioITK::InrImageReaderService::configureWithIHM(), ioData::MeshReaderService::configureWithIHM(), ioTuto::ExternalDataReaderService::configureWithIHM(), ioTuto::ExternalDataReaderService::configuring(), and configuring().
void io::IReader::setFiles (const ::io::LocationsType & files)
Sets file paths.
Precondition:
exception if service not supported FILES management
Definition at line 72 of file IReader.cpp.
References io::FILES, and getIOPathType().
Referenced by ioVTK::SModelSeriesReader::configureWithIHM(), ioVTK::SSeriesDBReader::configureWithIHM(), ioITK::SInrSeriesDBReader::configureWithIHM(), and configuring().
void io::IReader::setFolder (const ::boost::filesystem::path & folder)
Sets folder path.
Precondition:
exception if service not supported FOLDER management
Definition at line 89 of file IReader.cpp.
References io::FOLDER, and getIOPathType().
Referenced by ioVtkGdcm::SSeriesDBLazyReader::configureWithIHM(), ioVtkGdcm::SSeriesDBReader::configureWithIHM(), and configuring().
The documentation for this class was generated from the following files:
IReader.hpp
IReader.cpp