fw4spl: ctrlSelection::IUpdaterSrv Class Reference
ctrlSelection::IUpdaterSrv Class Reference
An updater is attached on a composite. It is use to add, swap and remove object in the composite when it receives specific message (declared in configuration) and sends corresponding message message. It work mainly with a IManager.
#include <IUpdaterSrv.hpp>
Public Types
enum ActionType {
ADD, SWAP, REMOVE, DO_NOTHING,
REMOVE_IF_PRESENT, ADD_OR_SWAP
}
Action to do on object in the composite.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IUpdaterSrv)(::fwServices::IService))
CTRLSELECTION_API IUpdaterSrv ()
IUpdaterSrv constructor. Do nothing.
virtual CTRLSELECTION_API ~IUpdaterSrv ()
IUpdaterSrv destructor. Do nothing.
Protected Types
typedef std::vector
< ::boost::tuple< std::string,
std::string, std::string,
ActionType > > ManagedEvents
Protected Member Functions
void updateComposite (::fwData::Composite::sptr composite,::fwData::Object::sptr _obj, std::string _compositeKey, ActionType _action)
Update the object in the composite.
void configureManagedEvents (::fwRuntime::ConfigurationElement::sptr configuration)
Configure the event to manage and its corresponding action.
Protected Attributes
ManagedEvents m_managedEvents
List of the managed event.
Detailed Description
An updater is attached on a composite. It is use to add, swap and remove object in the composite when it receives specific message (declared in configuration) and sends corresponding message message. It work mainly with a IManager.
Date:
2007-2009.
Definition at line 30 of file IUpdaterSrv.hpp.
Member Function Documentation
void ctrlSelection::IUpdaterSrv::configureManagedEvents (::fwRuntime::ConfigurationElement::sptr configuration) [protected]
Configure the event to manage and its corresponding action.
Parameters:
configuration configuration of the service
Sample of declaration configuration :
         <update compositeKey="reconstructionKey" onEvent="NEW_RECONSTRUCTION" fromUID="modelSeriesUid" actionType="ADD_OR_SWAP" />
         <update compositeKey="reconstructionKey" onEvent="CLEAR" fromUID="modelSeriesUid" actionType="REMOVE" />
Here, when the updater receives a message with the NEW_RECONSTRUCTION event from the object "modelSeriesUid" the object reconstructionKey is added or swapped in the composite. When the updater receives a message with the CLEAR event from the object "modelSeriesUid" the object reconstructionKey is removed from the composite
The actionType can be : ADD, ADD_OR_SWAP, SWAP, REMOVE, REMOVE_IF_PRESENT and DO_NOTHING
Definition at line 29 of file IUpdaterSrv.cpp.
References fwRuntime::ConfigurationElementContainer::begin(), fwRuntime::ConfigurationElementContainer::end(), fwRuntime::ConfigurationElementContainer::findAllConfigurationElement(), m_managedEvents, OSLM_DEBUG, OSLM_INFO, fwRuntime::ConfigurationElementContainer::size(), SLM_ASSERT, SLM_FATAL, SLM_FATAL_IF, and SLM_TRACE_FUNC.
Referenced by ctrlSelection::updater::DataInfoFromMsgUpdaterSrv::configuring(), ctrlSelection::updater::ObjFromMsgUpdaterSrv::configuring(), ctrlSelection::updater::ReconstructionFromResecUpdaterSrv::configuring(), and ctrlSelection::updater::SReconstructionFromModelSeriesUpdater::configuring().
void ctrlSelection::IUpdaterSrv::updateComposite (::fwData::Composite::sptr composite, ::fwData::Object::sptr _obj, std::string _compositeKey, ActionType _action) [protected]
Update the object in the composite.
Parameters:
composite Composite which will contain the object
_obj object to add in the composite
_compositeKey key of the object in the composite
_action action to do with the object
Note:
the _obj can be null if the action is REMOVE, REMOVE_IF_PRESENT or DO_NOTHING
Definition at line 75 of file IUpdaterSrv.cpp.
References OSLM_INFO, and SLM_FATAL.
Referenced by ctrlSelection::updater::TranslateUpdater::starting().
The documentation for this class was generated from the following files:
IUpdaterSrv.hpp
IUpdaterSrv.cpp