fw4spl: fwComEd::helper::Composite Struct Reference
fwComEd::helper::Composite Struct Reference
Defines an helper to modify an fwData::Composite and create in parallel the message to announce this modification.
#include <Composite.hpp>
Public Member Functions
FWCOMED_API Composite (::fwData::Composite::wptr _composite)
Constructor. Initialize parameters.
FWCOMED_API ~Composite ()
Destrucotr. Do nothing.
FWCOMED_API void add (std::string _compositeKey,::fwData::Object::sptr _newObject)
Add an object in the composite.
FWCOMED_API void remove (std::string _compositeKey)
Remove an object in the composite.
FWCOMED_API void clear ()
Clear all objects in the composite.
FWCOMED_API void swap (std::string _compositeKey,::fwData::Object::sptr _newObject)
Replace an object in the composite.
FWCOMED_API void notify (::fwServices::IService::sptr _serviceSource, bool _allowLoops=true)
Send the message of modification.
Detailed Description
Defines an helper to modify an fwData::Composite and create in parallel the message to announce this modification.
Date:
2007-2009.
Definition at line 29 of file core/fwComEd/include/fwComEd/helper/Composite.hpp.
Member Function Documentation
void fwComEd::helper::Composite::add (std::string _compositeKey, ::fwData::Object::sptr _newObject)
Add an object in the composite.
Parameters:
[in] _compositeKey key of the object in the composite.
[in] _newObject object to add in the composite
Prepare the message to announce the modification.
Definition at line 34 of file core/fwComEd/src/fwComEd/helper/Composite.cpp.
References OSLM_FATAL_IF.
Referenced by fwComEd::helper::Image::createTransferFunctionPool(), ctrlSelection::updater::SDrop::receiving(), uiTF::TransferFunctionEditor::updateTransferFunction(), fwComEd::helper::MedicalImageAdaptor::updateTransferFunction(), and ioAtoms::SReader::updating().
void fwComEd::helper::Composite::clear ()
Clear all objects in the composite.
Prepare the message to announce the modification.
Definition at line 65 of file core/fwComEd/src/fwComEd/helper/Composite.cpp.
Referenced by ctrlSelection::updater::SDrop::receiving().
void fwComEd::helper::Composite::notify (::fwServices::IService::sptr _serviceSource, bool _allowLoops = true)
Send the message of modification.
Parameters:
_serviceSource service used to send the message
_allowLoops if true, the _serviceSource will receive the message
Definition at line 105 of file core/fwComEd/src/fwComEd/helper/Composite.cpp.
References SLM_INFO_IF.
Referenced by fwComEd::helper::Image::createTransferFunctionPool(), ctrlSelection::updater::SDrop::receiving(), uiImage::WindowLevel::swapCurrentTFAndNotify(), uiTF::TransferFunctionEditor::updateTransferFunction(), fwComEd::helper::MedicalImageAdaptor::updateTransferFunction(), and ioAtoms::SReader::updating().
void fwComEd::helper::Composite::remove (std::string _compositeKey)
Remove an object in the composite.
Parameters:
[in] _compositeKey key of the object in the composite.
Prepare the message to announce the modification.
Definition at line 48 of file core/fwComEd/src/fwComEd/helper/Composite.cpp.
References OSLM_FATAL_IF.
void fwComEd::helper::Composite::swap (std::string _compositeKey, ::fwData::Object::sptr _newObject)
Replace an object in the composite.
Parameters:
[in] _compositeKey key of the object in the composite.
[in] _newObject the new object to add in the composite.
Prepare the message to announce the modification.
Definition at line 81 of file core/fwComEd/src/fwComEd/helper/Composite.cpp.
References OSLM_FATAL_IF, and OSLM_INFO.
Referenced by uiImage::WindowLevel::swapCurrentTFAndNotify(), and uiTF::TransferFunctionEditor::updateTransferFunction().
The documentation for this struct was generated from the following files:
core/fwComEd/include/fwComEd/helper/Composite.hpp
core/fwComEd/src/fwComEd/helper/Composite.cpp