fw4spl: fwGdcmIO::helper::DicomDir Class Reference
fwGdcmIO::helper::DicomDir Class Reference
DicomDir Helper. This class is used to extract a list of files from a dicomdir file.
#include <DicomDir.hpp>
Static Public Member Functions
static FWGDCMIO_API::boost::filesystem::path findDicomDir (const ::boost::filesystem::path &root)
Find the DICOMDIR file in the parent arborescence.
static FWGDCMIO_API void retrieveDicomSeries (const ::boost::filesystem::path &dicomdir, std::vector< std::shared_ptr< ::fwMedData::DicomSeries > > &seriesDB, const std::shared_ptr< ::fwLog::Logger >logger, const std::shared_ptr< ::fwJobs::Observer > &fileLookupObserver=nullptr)
Create DicomSeries from information stored in DICOMDIR.
Detailed Description
DicomDir Helper. This class is used to extract a list of files from a dicomdir file.
Definition at line 41 of file fwGdcmIO/include/fwGdcmIO/helper/DicomDir.hpp.
Member Function Documentation
boost::filesystem::path fwGdcmIO::helper::DicomDir::findDicomDir (const ::boost::filesystem::path & root) static
Find the DICOMDIR file in the parent arborescence.
Returns
Path to the DICOMDIR or empty path if the DICOMDIR has not been found
Definition at line 29 of file fwGdcmIO/src/fwGdcmIO/helper/DicomDir.cpp.
Referenced by fwGdcmIO::reader::SeriesDB::isDicomDirAvailable(), and fwGdcmIO::reader::SeriesDB::readDicomSeries().
void fwGdcmIO::helper::DicomDir::retrieveDicomSeries (const ::boost::filesystem::path & dicomdir, std::vector< std::shared_ptr< ::fwMedData::DicomSeries > > & seriesDB, const std::shared_ptr< ::fwLog::Logger > logger, const std::shared_ptr< ::fwJobs::Observer > & fileLookupObserver = nullptr) static
Create DicomSeries from information stored in DICOMDIR.
Parameters
dicomdir Path to dicomdir file
[out] seriesDB Dicom series created
[in] fileLookupObserver file lookup observer
Definition at line 56 of file fwGdcmIO/src/fwGdcmIO/helper/DicomDir.cpp.
References fwJobs::IJob::cancelRequested(), fwJobs::IJob::doneWork(), OSLM_WARN_IF, fwMedData::DicomSeries::PATHS, fwJobs::IJob::setTotalWorkUnits(), SLM_ASSERT, SLM_ERROR, and SLM_WARN_IF.
Referenced by fwGdcmIO::reader::SeriesDB::readDicomSeries().
The documentation for this class was generated from the following files:
fwGdcmIO/include/fwGdcmIO/helper/DicomDir.hpp
fwGdcmIO/src/fwGdcmIO/helper/DicomDir.cpp