fw4spl: gui::aspect::DefaultMenuSrv Class Reference
gui::aspect::DefaultMenuSrv Class Reference
Defines the default menu for standard application.
#include <DefaultMenuSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((DefaultMenuSrv)(::fwGui::IMenuSrv))
GUI_API DefaultMenuSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~DefaultMenuSrv () throw ()
Destructor. Do nothing.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual GUI_API void configuring () throw (::fwTools::Failed)
Configuring method allows to configure a menu with several actions.
virtual GUI_API void starting () throw (::fwTools::Failed)
Create the menu items and start the managed services.
virtual GUI_API void stopping () throw (::fwTools::Failed)
Stop all actions and separator of this menu and remove menu to menuBar.
virtual GUI_API void updating () throw (::fwTools::Failed)
Updating service, do nothing.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Updating service on notification, do nothing.
Detailed Description
Defines the default menu for standard application.
Definition at line 23 of file DefaultMenuSrv.hpp.
Member Function Documentation
void gui::aspect::DefaultMenuSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method allows to configure a menu with several actions.
Example of configuration
      <service uid="menuBar" type="::fwGui::IMenuBarSrv" impl="::gui::aspect::DefaultMenuBarSrv" autoConnect="no" >
          <gui>
              <layout>
                  <menu name="My Menu"/>
                  <menu name="My Menu 2"/>
              </layout>
          </gui>
          <registry>
              <menu sid="myMenu" start="yes" />
              <menu sid="myMenu2" start="yes" />
          </registry>
      </service>
<gui> </gui> : (mandatory) describe the interface of the service.
<separator> : allows to put a separator in the menu
<registry> </registry> : (mandatory) describe the service management.
Warning:
The number of item in the gui section must be equal or greater than in the registry section.
The order of the menu in each section (gui and registry) must be the same.
For example: the menu named "My Menu" will be connected with the service which have the sid = "myMenu".
A menu bar can't have the same service connected on two different menu.
See also:
fwGui::IMenuBarSrv::initialize(), fwGui::layoutManager::IMenuLayoutManager::initialize()
Implements fwServices::IService.
Definition at line 37 of file DefaultMenuSrv.cpp.
References fwGui::IMenuSrv::initialize().
void gui::aspect::DefaultMenuSrv::starting () throw (::fwTools::Failed) [protected, virtual]
Create the menu items and start the managed services.
See also:
fwGui::IMenuSrv::create()
Implements fwServices::IService.
Definition at line 44 of file DefaultMenuSrv.cpp.
References fwGui::IMenuSrv::create(), and SLM_TRACE_FUNC.
void gui::aspect::DefaultMenuSrv::stopping () throw (::fwTools::Failed) [protected, virtual]
Stop all actions and separator of this menu and remove menu to menuBar.
See also:
fwGui::IMenuSrv::destroy()
Implements fwServices::IService.
Definition at line 52 of file DefaultMenuSrv.cpp.
References fwGui::IMenuSrv::destroy(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
DefaultMenuSrv.hpp
DefaultMenuSrv.cpp