fw4spl: ioITK::InrImageReaderService Class Reference
ioITK::InrImageReaderService Class Reference
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((InrImageReaderService)(::io::IReader))
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Override.
virtual void stopping () throw (::fwTools::Failed)
Override.
virtual IOITK_API void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Override.
IOITK_API void info (std::ostream &_sstream)
Override.
virtual IOITK_API void configureWithIHM ()
Override.
IOITK_API::io::IOPathType getIOPathType () const
Return managed file type, here FILE.
Detailed Description
Definition at line 26 of file InrImageReaderService.hpp.
Member Function Documentation
void ioITK::InrImageReaderService::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 127 of file InrImageReaderService.cpp.
References io::IReader::getFile(), io::IReader::hasLocationDefined(), fwGui::Cursor::setCursor(), fwGui::Cursor::setDefaultCursor(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
InrImageReaderService.hpp
InrImageReaderService.cpp