fw4spl: fwGdcmIO::container::DicomInstance Class Reference
fwGdcmIO::container::DicomInstance Class Reference
This class defines a DICOM SOP instance. It is useful during the whole writing process. This class allows to share data between module writers.
#include <DicomInstance.hpp>
Public Types
typedef std::vector< std::string > SOPInstanceUIDContainerType
Public Member Functions
FWGDCMIO_API DicomInstance ()
Constructor.
FWGDCMIO_API DicomInstance (std::shared_ptr< ::fwMedData::Series >series, bool isMultiFiles)
Constructor.
FWGDCMIO_API DicomInstance (std::shared_ptr< ::fwMedData::DicomSeries >dicomSeries)
Constructor.
FWGDCMIO_API DicomInstance (const DicomInstance &dicomInstance)
Copy constructor.
virtual FWGDCMIO_API ~DicomInstance ()
Destructor.
bool getIsMultiFiles () const
Get the flag on multi-files state of an image series.
void setIsMultiFiles (bool isMultiFiles)
Set the flag on multi-files state of an image series.
const std::string & getSOPClassUID () const
Get SOP Class UID.
void setSOPClassUID (const std::string &SOPClassUID)
Set SOP Class UID.
const std::string & getSeriesInstanceUID () const
Get Series Instance UID.
void setSeriesInstanceUID (const std::string &seriesInstanceUID)
Set Series Instance UID.
const std::string & getStudyInstanceUID () const
Get Study Instance UID.
void setStudyInstanceUID (const std::string &studyInstanceUID)
Set Study Instance UID.
const SOPInstanceUIDContainerType & getSOPInstanceUIDContainer () const
Get SOP Instance UID container.
SOPInstanceUIDContainerType & getRefSOPInstanceUIDContainer ()
Get SOP Instance UID container.
void setSOPInstanceUIDContainer (const SOPInstanceUIDContainerType &SOPInstanceUIDContainer)
Set SOP Instance UID Container.
Protected Member Functions
void computeSOPClassUID (std::shared_ptr< ::fwMedData::Series > series)
Compute SOPClassUID.
void generateSOPInstanceUIDs (std::shared_ptr< ::fwMedData::Series > series)
Generate SOPInstanceUIDs according to series type and dimension.
Detailed Description
This class defines a DICOM SOP instance. It is useful during the whole writing process. This class allows to share data between module writers.
Definition at line 38 of file DicomInstance.hpp.
Constructor & Destructor Documentation
fwGdcmIO::container::DicomInstance::DicomInstance (std::shared_ptr< ::fwMedData::Series > series, bool isMultiFiles)
Constructor.
Parameters
[in] series Series from which the instance is created
[in] isMultiFiles Set whether the instance must be split in several files or not
Definition at line 35 of file DicomInstance.cpp.
References computeSOPClassUID(), and generateSOPInstanceUIDs().
fwGdcmIO::container::DicomInstance::DicomInstance (std::shared_ptr< ::fwMedData::DicomSeries > dicomSeries)
Constructor.
Parameters
[in] dicomSeries DicomSeries from which the instance is created
Definition at line 50 of file DicomInstance.cpp.
References fwMedData::DicomSeries::getSOPClassUIDs().
Member Function Documentation
void fwGdcmIO::container::DicomInstance::computeSOPClassUID (std::shared_ptr< ::fwMedData::Series > series) protected
Compute SOPClassUID.
Parameters
[in] series Series
Definition at line 79 of file DicomInstance.cpp.
References getIsMultiFiles(), and setSOPClassUID().
Referenced by DicomInstance().
void fwGdcmIO::container::DicomInstance::generateSOPInstanceUIDs (std::shared_ptr< ::fwMedData::Series > series) protected
Generate SOPInstanceUIDs according to series type and dimension.
Parameters
[in] series Series
Definition at line 123 of file DicomInstance.cpp.
Referenced by DicomInstance().
The documentation for this class was generated from the following files:
DicomInstance.hpp
DicomInstance.cpp