fw4spl: ioTuto::ExternalDataReaderService Class Reference
ioTuto::ExternalDataReaderService Class Reference
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ExternalDataReaderService)(::io::IReader))
IOTUTO_API ExternalDataReaderService ()
Constructor : does nothing.
IOTUTO_API ~ExternalDataReaderService () throw ()
Destructor.
virtual IOTUTO_API std::vector
< std::string > getSupportedExtensions ()
returns (filename) extension
Protected Member Functions
IOTUTO_API::io::IOPathType getIOPathType () const
Returns managed path type, here service manages only single file.
Service methods (override from ::fwServices::IService)
virtual IOTUTO_API void starting () throw (::fwTools::Failed)
Starting method : default does nothing.
virtual IOTUTO_API void stopping () throw (::fwTools::Failed)
Stopping method : default does nothing.
virtual IOTUTO_API void configuring () throw (::fwTools::Failed)
Configure service. This method is called by configure() from base service (fwServices::IService)
IOTUTO_API void configureWithIHM ()
Configure the image path.
IOTUTO_API void updating () throw (::fwTools::Failed)
Updating method. This method is called by update() from base service (fwServices::IService)
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : default does nothing.
virtual IOTUTO_API void info (std::ostream &_sstream)
Info method.
Detailed Description
Definition at line 18 of file ExternalDataReaderService.hpp.
Member Function Documentation
void ioTuto::ExternalDataReaderService::configureWithIHM () [protected, virtual]
Configure the image path.
This method is used to find the file path using a file selector.
Implements io::IReader.
Definition at line 74 of file ExternalDataReaderService.cpp.
References fwGui::dialog::LocationDialog::addFilter(), io::IReader::clearLocations(), fwGui::dialog::LocationDialog::setDefaultLocation(), io::IReader::setFile(), fwGui::dialog::LocationDialog::setOption(), fwGui::dialog::LocationDialog::setTitle(), and fwGui::dialog::LocationDialog::show().
Referenced by updating().
void ioTuto::ExternalDataReaderService::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure service. This method is called by configure() from base service (fwServices::IService)
XML configuration sample:
    <service type="::ioTuto::ExternalDataReaderService">
    </service>
Configure External data info filename.
Reimplemented from io::IReader.
Definition at line 62 of file ExternalDataReaderService.cpp.
References fwServices::IService::m_configuration, OSLM_INFO, and io::IReader::setFile().
void ioTuto::ExternalDataReaderService::info (std::ostream & _sstream) [protected, virtual]
Info method.
This method is used to give informations about the service.
Parameters:
[out] _sstream output stream
Reimplemented from fwServices::IService.
Definition at line 40 of file ExternalDataReaderService.cpp.
void ioTuto::ExternalDataReaderService::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [inline, protected]
React on modifications : default does nothing.
Note:
This method is automatically called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 94 of file ExternalDataReaderService.hpp.
virtual IOTUTO_API void ioTuto::ExternalDataReaderService::starting () throw (::fwTools::Failed) [inline, protected, virtual]
Starting method : default does nothing.
This method is used to initialize the service.
Implements fwServices::IService.
Definition at line 49 of file ExternalDataReaderService.hpp.
virtual IOTUTO_API void ioTuto::ExternalDataReaderService::stopping () throw (::fwTools::Failed) [inline, protected, virtual]
Stopping method : default does nothing.
The stopping method is empty for this service.
Implements fwServices::IService.
Definition at line 56 of file ExternalDataReaderService.hpp.
void ioTuto::ExternalDataReaderService::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method. This method is called by update() from base service (fwServices::IService)
This method is used to update the service.
Implements fwServices::IService.
Definition at line 100 of file ExternalDataReaderService.cpp.
References configureWithIHM(), io::IReader::getFile(), io::IReader::hasLocationDefined(), OSLM_ERROR, and SLM_ASSERT.
The documentation for this class was generated from the following files:
ExternalDataReaderService.hpp
ExternalDataReaderService.cpp