fw4spl: gui::action::ActionNotifyService Class Reference
gui::action::ActionNotifyService Class Reference
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ActionNotifyService)(::fwGui::IActionSrv))
GUI_API ActionNotifyService () throw ()
Constructor. Do nothing.
virtual GUI_API ~ActionNotifyService () throw ()
Destructor. Do nothing.
Protected Types
typedef ::boost::tuple
< std::string, std::string > MsgEventType
Message container [(MessageType, Event)].
typedef std::vector< MsgEventType > MsgVectType
Notify message vector.
Protected Member Functions
virtual GUI_API void info (std::ostream &_sstream)
Write information in a stream.
GUI_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
GUI_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
GUI_API void updating () throw (fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
GUI_API void configuring () throw (::fwTools::Failed)
Configure the message to send.
Protected Attributes
MsgVectType m_vectMsg
Detailed Description
Definition at line 23 of file ActionNotifyService.hpp.
Member Function Documentation
void gui::action::ActionNotifyService::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the message to send.
Example of configuration :
        <service ... >
            <notify type="::fwServices::ObjectMsg" event="APPLY" />
        </service>
<notify> :
type : the type of the message (i.e. fwServices::ObjectMsg)
event : the event of the message (i.e. "APPLY")
Implements fwServices::IService.
Definition at line 93 of file ActionNotifyService.cpp.
References fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, and SLM_ASSERT.
void gui::action::ActionNotifyService::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 45 of file ActionNotifyService.cpp.
void gui::action::ActionNotifyService::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 68 of file ActionNotifyService.cpp.
void gui::action::ActionNotifyService::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 52 of file ActionNotifyService.cpp.
References fwGui::IActionSrv::actionServiceStarting(), and SLM_TRACE_FUNC.
void gui::action::ActionNotifyService::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 60 of file ActionNotifyService.cpp.
References fwGui::IActionSrv::actionServiceStopping(), and SLM_TRACE_FUNC.
void gui::action::ActionNotifyService::updating () throw (fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 73 of file ActionNotifyService.cpp.
References fwGui::IActionSrv::confirmAction(), fwServices::IService::getObject(), fwServices::IEditionService::notify(), and OSLM_ASSERT.
The documentation for this class was generated from the following files:
ActionNotifyService.hpp
ActionNotifyService.cpp