fw4spl: gui::action::PushObjectSrv Class Reference
gui::action::PushObjectSrv Class Reference
To add or remove object in composite with specific key.
#include <PushObjectSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((PushObjectSrv)(::fwGui::IActionSrv))
GUI_API PushObjectSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~PushObjectSrv () throw ()
Destructor. Do nothing.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
virtual void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void configuring () throw (fwTools::Failed)
virtual void info (std::ostream &_sstream)
Overrides.
Detailed Description
To add or remove object in composite with specific key.
Date:
2011.
Definition at line 33 of file PushObjectSrv.hpp.
Member Function Documentation
void gui::action::PushObjectSrv::configuring () throw (fwTools::Failed) [protected, virtual]
Call the IAction::configuring()
Example of this service configuration
       <service impl="::gui::action::PushObjectSrv" type="::fwGui::IActionSrv">
           <push src="COMPOSITE_UID[KEY]" key="KEY_IN_COMPOSITE" />
       </service>
Implements fwServices::IService.
Definition at line 75 of file PushObjectSrv.cpp.
References fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, OSLM_ASSERT, OSLM_FATAL, SLM_ASSERT, SLM_TRACE, and SLM_TRACE_FUNC.
void gui::action::PushObjectSrv::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 43 of file PushObjectSrv.cpp.
References fwGui::IActionSrv::actionServiceStarting(), fwTools::fwID::exist(), OSLM_ASSERT, OSLM_TRACE, fwGui::IActionSrv::setIsExecutable(), SLM_TRACE, and SLM_TRACE_FUNC.
void gui::action::PushObjectSrv::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 67 of file PushObjectSrv.cpp.
References fwGui::IActionSrv::actionServiceStopping(), and SLM_TRACE_FUNC.
void gui::action::PushObjectSrv::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 108 of file PushObjectSrv.cpp.
References fwTools::fwID::exist(), OSLM_ASSERT, and OSLM_WARN_IF.
The documentation for this class was generated from the following files:
PushObjectSrv.hpp
PushObjectSrv.cpp