fw4spl: fwCommand::Manager Class Reference
fwCommand::Manager Class Reference
Keep tracking an history of commands.
#include <Manager.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWCOMMAND_API Manager (const ::boost::uint32_t maxUndoLevel=0, const ::boost::uint32_t maxUndoMemory=0, const ::boost::uint32_t maxCommandMemory=1024 *1024 *32)
Default constructor.
virtual FWCOMMAND_API ~Manager () throw ()
Destructor.
FWCOMMAND_API ICommand::sptr getFirstUndoableCommand ()
Retrieves the first undoable command.
FWCOMMAND_API ICommand::sptr getFirstRedoableCommand ()
Retrieves the first redoable command.
const ::boost::uint32_t getMaxUndoLevel () const
Returns the maximum number of undo that could be stored in the history.
const ::boost::uint32_t getMaxUndoMemory () const
Returns the maximum memory that could be used by the history.
const ::boost::uint32_t getMaxCommandMemory () const
Returns the maximum memory that could be used by a single command.
FWCOMMAND_APIconst::boost::uint32_t getUndoSize ()
Returns the number of commands that can be un-done.
FWCOMMAND_APIconst::boost::uint32_t getRedoSize ()
Returns the number of commans that can be re-done.
FWCOMMAND_API void setNotifier (::fwServices::IService::sptr serviceNotifier)
FWCOMMAND_API::fwServices::IService::sptr getNotifier ()
History management methods.
FWCOMMAND_API void queue (ICommand::sptr cmd, const bool execute=false)
Execute the command and push it in the history.
FWCOMMAND_API void forward ()
Execute the next command if any.
FWCOMMAND_API void backward ()
Execute the previous command if any.
FWCOMMAND_API void clear ()
Remove all commands in history.
Public Member Functions inherited from fwTools::Object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWCOMMAND_API sptr ManagerFactory (const ::boost::uint32_t maxUndoLevel, const ::boost::uint32_t maxUndoMemory, const ::boost::uint32_t maxCommandMemory)
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef std::deque< ICommand::sptr > CmdList
Typedef for list of commands.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions
void removeFirstCmd ()
Remove first command in m_listCmd and desalocate this command.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Attributes
CmdList m_listCmd
History.
::boost::uint32_t m_maxUndoLevel
Maximum number of undo that could be stored in the history.
::boost::uint32_t m_maxUndoMemory
Maximum number of bytes that could be used by the history.
::boost::uint32_t m_maxCommandMemory
Maximum number of bytes that could be used by a single command.
::boost::uint32_t m_usedMemory
Memory used by the history.
CmdList::iterator m_lastCmd
Iterator on the last command applied.
::fwServices::IService::wptr m_serviceNotifier
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Keep tracking an history of commands.
Definition at line 27 of file Manager.hpp.
Constructor & Destructor Documentation
fwCommand::Manager::Manager (const ::boost::uint32_t maxUndoLevel = 0, const ::boost::uint32_t maxUndoMemory = 0, const ::boost::uint32_t maxCommandMemory = 1024*1024*32)
Default constructor.
Parameters
maxUndoLevel maximum number of command that could be stored in the history
maxUndoMemory maximum number of byte that could be stored in the history (but the latest queued command is ignored by the memory usage counter. See below for more explanation)
maxCommandMemory maximum number of byte that could be used by a single command
If the size of a single command is greater than maxCommandMemory, then it would not be stored in the history.
Remarks
The latest queued command is ignored by the memory usage counter in order to ensure that the latest command could always being stored in the history.
The maximum memory used by the history is maxUndoMemory + maxCommandMemory.
Definition at line 21 of file Manager.cpp.
References m_lastCmd, and m_listCmd.
Member Function Documentation
ICommand::sptr fwCommand::Manager::getFirstRedoableCommand ()
Retrieves the first redoable command.
Returns
a shared pointer to the first undoable command, can be empty
Definition at line 186 of file Manager.cpp.
References m_lastCmd, and m_listCmd.
ICommand::sptr fwCommand::Manager::getFirstUndoableCommand ()
Retrieves the first undoable command.
Returns
a shared pointer to the first undoable command, can be empty
Definition at line 179 of file Manager.cpp.
References m_lastCmd, and m_listCmd.
void fwCommand::Manager::queue (ICommand::sptr cmd, const bool execute = false)
Execute the command and push it in the history.
Parameters
cmd the command
execute sets to true if queue must execute the given command, false if not
Definition at line 66 of file Manager.cpp.
References getMaxCommandMemory(), getMaxUndoLevel(), getMaxUndoMemory(), m_lastCmd, m_listCmd, m_usedMemory, and removeFirstCmd().
void fwCommand::Manager::removeFirstCmd () protected
Remove first command in m_listCmd and desalocate this command.
Precondition
m_listCmd not empty.
Definition at line 53 of file Manager.cpp.
References m_listCmd, m_usedMemory, and SLM_ASSERT.
Referenced by queue().
The documentation for this class was generated from the following files:
Manager.hpp
Manager.cpp