fw4spl: uiMeasurement::editor::Distance Class Reference
uiMeasurement::editor::Distance Class Reference
Distance service is represented by a button. It allows to show distances in a generic scene.
#include <Distance.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((Distance)(::gui::editor::IEditor))
UIMEASUREMENTQT_API Distance () throw ()
Constructor. Do nothing.
virtual UIMEASUREMENTQT_API ~Distance () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Slots
void onDistanceButton ()
Notify the scene that a distance is added.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Install the layout.
virtual void stopping () throw (::fwTools::Failed)
Destroy the layout.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Do nothing.
virtual void updating () throw (::fwTools::Failed)
Do nothing.
virtual void swapping () throw (::fwTools::Failed)
Do nothing.
virtual void configuring () throw (fwTools::Failed)
Configure the editor.
virtual void info (std::ostream &_sstream)
Overrides.
Detailed Description
Distance service is represented by a button. It allows to show distances in a generic scene.
Date:
2010.
Definition at line 29 of file LeafUI/uiMeasurementQt/include/uiMeasurementQt/editor/Distance.hpp.
Member Function Documentation
void uiMeasurement::editor::Distance::configuring () throw (fwTools::Failed) [protected, virtual]
Configure the editor.
Example of configuration
    <service uid="distanceEditor" type="::gui::editor::IEditor" impl="::uiMeasurement::editor::Distance" autoConnect="no">
        <placeInScene uid="genericScene" />
    </service>
genericScene is the uid of the fwRenderVTK::VtkRenderService representing the generic scene which will be printed.
Implements fwServices::IService.
Definition at line 96 of file LeafUI/uiMeasurementQt/src/uiMeasurementQt/editor/Distance.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, SLM_ASSERT, and SLM_TRACE_FUNC.
void uiMeasurement::editor::Distance::starting () throw (::fwTools::Failed) [protected, virtual]
Install the layout.
This method launches the IEditor::starting method.
Implements fwServices::IService.
Definition at line 56 of file LeafUI/uiMeasurementQt/src/uiMeasurementQt/editor/Distance.cpp.
References fwGui::IGuiContainerSrv::create(), onDistanceButton(), OSLM_ASSERT, SLM_ASSERT, and SLM_TRACE_FUNC.
void uiMeasurement::editor::Distance::stopping () throw (::fwTools::Failed) [protected, virtual]
Destroy the layout.
This method launches the IEditor::stopping method.
Implements fwServices::IService.
Definition at line 84 of file LeafUI/uiMeasurementQt/src/uiMeasurementQt/editor/Distance.cpp.
References fwGui::IGuiContainerSrv::destroy(), onDistanceButton(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
LeafUI/uiMeasurementQt/include/uiMeasurementQt/editor/Distance.hpp
LeafUI/uiMeasurementQt/src/uiMeasurementQt/editor/Distance.cpp