fw4spl: fwComEd::TransferFunctionMsg Class Reference
fwComEd::TransferFunctionMsg Class Reference
Object event message specialized for transfer function : store modification information.
#include <TransferFunctionMsg.hpp>
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((TransferFunctionMsg)(::fwServices::ObjectMsg),(()),::fwServices::factory::message::New< TransferFunctionMsg >)
FWCOMED_API TransferFunctionMsg (::fwServices::ObjectMsg::Key key)
Constructor.
virtual FWCOMED_API ~TransferFunctionMsg () throw ()
Destuctor : does nothing.
FWCOMED_API void setWindowLevel (double window, double level)
Add a WINDOWING even with window and level.
FWCOMED_API double getWindow () const
Get the window and level .
FWCOMED_API double getLevel () const
Get the level .
Static Public Attributes
Event identifier
static FWCOMED_API std::string MODIFIED_POINTS = "MODIFIED_POINTS"
static FWCOMED_API std::string WINDOWING = "WINDOWING"
Protected Attributes
double m_level
Windowing min.
double m_window
Windowing max.
Detailed Description
Object event message specialized for transfer function : store modification information.
Date:
2007-2009.
See also:
fwServices::ObjectMsg
Definition at line 28 of file TransferFunctionMsg.hpp.
Constructor & Destructor Documentation
fwComEd::TransferFunctionMsg::TransferFunctionMsg (::fwServices::ObjectMsg::Key key)
Constructor.
Parameters:
key Private construction key
Definition at line 23 of file TransferFunctionMsg.cpp.
Member Function Documentation
double fwComEd::TransferFunctionMsg::getLevel () const
Get the level .
Precondition:
The message must have a WINDOWING even
Parameters:
[out] : the level of the image tf
Definition at line 50 of file TransferFunctionMsg.cpp.
References fwServices::ObjectMsg::hasEvent(), m_level, SLM_ASSERT, and WINDOWING.
double fwComEd::TransferFunctionMsg::getWindow () const
Get the window and level .
Precondition:
The message must have a WINDOWING even
Parameters:
[out] : the window of the image tf
Definition at line 42 of file TransferFunctionMsg.cpp.
References fwServices::ObjectMsg::hasEvent(), m_window, SLM_ASSERT, and WINDOWING.
void fwComEd::TransferFunctionMsg::setWindowLevel (double window, double level)
Add a WINDOWING even with window and level.
Parameters:
[in] level : level of the image tf
[in] window : window of the image tf
Definition at line 33 of file TransferFunctionMsg.cpp.
References fwServices::ObjectMsg::addEvent(), m_level, m_window, and WINDOWING.
Member Data Documentation
std::string fwComEd::TransferFunctionMsg::MODIFIED_POINTS = "MODIFIED_POINTS" [static]
Event identifier used to inform for modification
Definition at line 39 of file TransferFunctionMsg.hpp.
Referenced by scene2D::adaptor::TransferFunction::doReceive().
std::string fwComEd::TransferFunctionMsg::WINDOWING = "WINDOWING" [static]
Event identifier used to inform for modification
Definition at line 40 of file TransferFunctionMsg.hpp.
Referenced by scene2D::adaptor::TransferFunction::doReceive(), getLevel(), getWindow(), uiImage::WindowLevel::receiving(), and setWindowLevel().
The documentation for this class was generated from the following files:
TransferFunctionMsg.hpp
TransferFunctionMsg.cpp