fw4spl: fwDataIO::writer::MeshWriter Class Reference
fwDataIO::writer::MeshWriter Class Reference
Mesh writer. Write file format .trian.
#include <MeshWriter.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWDATAIO_API MeshWriter (::fwDataIO::writer::IObjectWriter::Key key)
Constructor. Do nothing.
virtual FWDATAIO_API ~MeshWriter ()
Destructor. Do nothing.
virtual FWDATAIO_API void write ()
virtual FWDATAIO_API std::string extension ()
Defines extension supported by this reader ".trian".
Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Mesh >
GenericObjectWriter ()
Constructor. Do nothing.
virtual ~GenericObjectWriter ()
Destructor. Do nothing.
virtual void setObject (::fwTools::Object::sptr obj)
m_object setter.
virtual std::shared_ptr< DataType > getConcreteObject ()
m_object getter.
Public Member Functions inherited from fwDataIO::writer::IObjectWriter
virtual FWDATAIO_API void setLocation (const ::fwData::location::ILocation::sptr location)
m_location setter.
virtual FWDATAIO_API::fwData::location::ILocation::sptr getLocation ()
m_location getter.
virtual FWDATAIO_API::fwTools::Object::sptr getObject ()
m_object getter.
virtual FWDATAIO_API void cancel ()
Requests writer abortion.
virtual FWDATAIO_API std::shared_ptr< ::fwJobs::IJob > getJob () const
Returns the internal job, nullptr by default.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwData::location::enableSingleFile< ::fwDataIO::writer::IObjectWriter >
enableSingleFile (::fwDataIO::writer::IObjectWriter *rw)
constructor
void setFile (ILocation::PathType path)
Set file system path.
ILocation::PathType getFile ()
Get file system path.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Mesh >
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwDataIO::writer::IObjectWriter
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Mesh >
typedef ::fwData::Mesh DataType
the object type related
Public Types inherited from fwDataIO::writer::IObjectWriter
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< void() > CancelCallback
typedef ::fwDataIO::writer::factory::Key Key
Protected Member Functions inherited from fwDataIO::writer::IObjectWriter
FWDATAIO_API IObjectWriter ()
Constructor. Do nothing.
virtual FWDATAIO_API ~IObjectWriter ()
Destructor. Do nothing.
Protected Attributes inherited from fwDataIO::writer::IObjectWriter
::fwTools::Object::wptr m_object
Object write on filesystem by the process.
::fwData::location::ILocation::sptr m_location
Object location (file path, directory path, url, etc)
std::string m_extension
Extension of file format.
Detailed Description
Mesh writer. Write file format .trian.
Date
2011
Ircad writer to write a fwData::Mesh (with only triangular cells) on filesystem which the file format is .trian. This format is basic. This is an ascii file which contains : 1) nb of points 2) list of points (x,y,z). Line numbers represent index of point in vector 3) nb of triangles 4) list of triangles with index of points and normals (often set a -1)
Definition at line 37 of file core/fwDataIO/include/fwDataIO/writer/MeshWriter.hpp.
Member Function Documentation
void fwDataIO::writer::MeshWriter::write () virtual
Write the file with standard iostream API.
Precondition
Mesh must contains only triangular cells.
Implements fwDataIO::writer::IObjectWriter.
Definition at line 44 of file core/fwDataIO/src/fwDataIO/writer/MeshWriter.cpp.
References fwDataTools::helper::Array::begin(), fwDataIO::writer::GenericObjectWriter< ::fwData::Mesh >::getConcreteObject(), fwData::location::enableSingleFile< ::fwDataIO::writer::IObjectWriter >::getFile(), fwDataTools::helper::Mesh::getPoints(), fwDataTools::Mesh::hasUniqueCellType(), OSLM_ERROR, OSLM_INFO, and SLM_ASSERT.
The documentation for this class was generated from the following files:
core/fwDataIO/include/fwDataIO/writer/MeshWriter.hpp
core/fwDataIO/src/fwDataIO/writer/MeshWriter.cpp