fw4spl: fwServices::IEditionService Class Reference
fwServices::IEditionService Class Reference
This interface defines edition service API. It mainly has the role of the subject in the observer design pattern.
#include <IEditionService.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IEditionService)(::fwServices::IService))
Static Public Member Functions
static FWSERVICES_API void notify (::fwServices::IService::sptr _pSource,::fwData::Object::sptr _pSubject, ObjectMsg::sptr _pMsg)
Invoke the IEditionService::notify(ObjectMsg::csptr) method on _pSubject.
static FWSERVICES_API void notify (::fwServices::IService::sptr _pSource,::fwData::Object::sptr _pSubject, ObjectMsg::sptr _pMsg, bool _allowLoops)
Invoke the IEditionService::notify(ObjectMsg::csptr) method on _pSubject.
Protected Member Functions
FWSERVICES_API IEditionService ()
Constructor. Do nothing.
virtual FWSERVICES_API ~IEditionService () throw ()
Destructor. Do nothing.
Friends
class GlobalEventManager
Detailed Description
This interface defines edition service API. It mainly has the role of the subject in the observer design pattern.
Date:
2007-2009.
This service notifies modifications performed on its associated object. This can be seen a delegate of traditional notifications performed by objects (subjects) which are themselves subject to modification. This ensures a good separation of concerns.
Todo:
the design assumes that any object can have only one service of type IEditionService. For robustness, this should be controlled.
Note:
notification are propagated to "listening" services by invoking the update(const fwServices::ObjectMsg::csptr) methods on referenced communication channels which forward this to their destination service acting as the observer.
could be improved by directly registering the destination service instead of the communication channel. Communication channel, being a first class entity between the subject and observer, have to be preferred to facilitate the configuration, the (des)activation and the monitoring of communications over a software system.
special thanks to Guillaume Brocker
Definition at line 40 of file IEditionService.hpp.
Member Function Documentation
static FWSERVICES_API void fwServices::IEditionService::notify (::fwServices::IService::sptr _pSource, ::fwData::Object::sptr _pSubject, ObjectMsg::sptr _pMsg) [static]
Invoke the IEditionService::notify(ObjectMsg::csptr) method on _pSubject.
Parameters:
[in] _pSource The service which send the message
[in] _pSubject The subject of the message (to retrieve listeners of the subject)
[in] _pMsg message notify to associated object listeners
This method notifies observers of _pSubject. It changes notification status of _pSource during all notification, set correct source and subject of msg and timestamp the message.
Referenced by scene2D::adaptor::ViewportRangeSelector::doStart(), uiImage::ShowScanEditor::onChangeScanMode(), uiImage::SliceListEditor2::onChangeSliceMode(), uiImage::SliceListEditor::onChangeSliceMode(), uiMedData::editor::SModelSeriesList::onCurrentItemChanged(), uiMeasurement::editor::Distance::onDistanceButton(), uiImage::ImageTransparency::onModifyTransparency(), uiVisu::BasicFloatEditor::onModifyValue(), guiQt::editor::Code::onModifyValue(), uiVisu::TransformationMatrixEditor::onSliderChange(), uiVisu::SnapshotEditor::onSnapButton(), scene2D::adaptor::ViewportRangeSelector::processInteraction(), ctrlSelection::wrapper::ImageWrapperSrv::receiving(), ctrlSelection::wrapper::GraphWrapperSrv::receiving(), ctrlSelection::wrapper::MsgWrapperSrv::receiving(), ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv::receiving(), ctrlSelection::wrapper::MsgForwarderSrv::receiving(), uiImage::SliceIndexPositionEditor::sliceIndexNotification(), uiImage::SliceIndexPositionEditor::sliceTypeNotification(), fwServices::ut::ServiceTest::testCommunication(), fwComEd::ut::CompositeMessageTest::testCompositeMessage(), visuVTKAdaptor::MeshesBoxWidget::updateFromVtk(), visuVTKAdaptor::Transform::updateFromVtk(), uiMeasurement::action::LoadLandmark::updating(), uiMeasurement::action::AddDistance::updating(), uiMeasurement::action::AddLandmark::updating(), opImageFilter::action::ImageFilter::updating(), uiMeasurement::action::ShowLandmark::updating(), uiMeasurement::action::SAddLabeledPoint::updating(), opVTKMesh::action::VTKMeshCreation::updating(), uiMeasurement::action::FocusLandmark::updating(), uiMeasurement::action::ShowDistance::updating(), gui::action::ActionNotifyService::updating(), opVTKMesh::SVTKMesher::updating(), uiVisu::action::CrossTypeAction::updating(), uiVisu::action::SSnapshot::updating(), scene2D::processing::SComputeHistogram::updating(), uiVisu::action::CameraOrientationAction::updating(), ctrlSelection::ImageUpdateAxis::updating(), ioVTK::SModelSeriesReader::updating(), ioData::CameraReaderService::updating(), ioData::action::SMeshModifier::updating(), ioData::TransformationMatrix3DReaderService::updating(), ioData::MeshReaderService::updating(), ioData::TransformationMatrix3DWriterService::updating(), and ioData::SplineReaderService::updating().
static FWSERVICES_API void fwServices::IEditionService::notify (::fwServices::IService::sptr _pSource, ::fwData::Object::sptr _pSubject, ObjectMsg::sptr _pMsg, bool _allowLoops) [static]
Invoke the IEditionService::notify(ObjectMsg::csptr) method on _pSubject.
Parameters:
[in] _pSource The service which send the message
[in] _pSubject The subject of the message (to retrieve listeners of the subject)
[in] _pMsg message notify to associated object listeners
[in] _allowLoops Allow loops (be really careful)
This method notifies observers of _pSubject. It changes notification status of _pSource during all notification, set correct source and subject of msg and timestamp the message.
The documentation for this class was generated from the following files:
IEditionService.hpp
IEditionService.cpp