fw4spl: fwDicomTools::Series Class Reference
fwDicomTools::Series Class Reference
DICOM Series Helper.
#include <Series.hpp>
Static Public Member Functions
static FWDICOMTOOLS_API std::shared_ptr< ::fwMedData::ImageSeries > convertToImageSeries (const std::shared_ptr< const ::fwMedData::DicomSeries > &series)
Convert a DicomSeries to an ImageSeries.
static FWDICOMTOOLS_API std::shared_ptr< ::fwMedData::ModelSeries > convertToModelSeries (const std::shared_ptr< const ::fwMedData::DicomSeries > &series)
Convert a DicomSeries to a ModelSeries.
Detailed Description
DICOM Series Helper.
Definition at line 30 of file core/fwDicomTools/include/fwDicomTools/Series.hpp.
Member Function Documentation
fwMedData::ImageSeries::sptr fwDicomTools::Series::convertToImageSeries (const std::shared_ptr< const ::fwMedData::DicomSeries > & series) static
Convert a DicomSeries to an ImageSeries.
Parameters
[in] series DicomSeries that must be converted
Definition at line 18 of file core/fwDicomTools/src/fwDicomTools/Series.cpp.
Referenced by fwDcmtkIO::reader::ImageStorageReader::read(), and fwGdcmIO::reader::Series::read().
fwMedData::ModelSeries::sptr fwDicomTools::Series::convertToModelSeries (const std::shared_ptr< const ::fwMedData::DicomSeries > & series) static
Convert a DicomSeries to a ModelSeries.
Parameters
[in] series DicomSeries that must be converted
Definition at line 35 of file core/fwDicomTools/src/fwDicomTools/Series.cpp.
Referenced by fwGdcmIO::reader::Series::read().
The documentation for this class was generated from the following files:
core/fwDicomTools/include/fwDicomTools/Series.hpp
core/fwDicomTools/src/fwDicomTools/Series.cpp