fw4spl: fwGdcmIO::writer::ie::Surface Class Reference
fwGdcmIO::writer::ie::Surface Class Reference
Surface Information Entity class.
#include <Surface.hpp>
Public Member Functions
FWGDCMIO_API Surface (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &imageInstance, const ::fwMedData::ModelSeries::csptr &series, const ::fwLog::Logger::sptr &logger=nullptr, ProgressCallback progress=nullptr, CancelRequestedCallback cancel=nullptr)
Constructor.
virtual FWGDCMIO_API ~Surface ()
Destructor.
FWGDCMIO_API bool loadSegmentedPropertyRegistry (const ::boost::filesystem::path &filepath)
Load Segmented Property Registry.
virtual FWGDCMIO_API void writeSOPCommonModule ()
Write SOP Common Module tags.
virtual FWGDCMIO_API void writeSurfaceSegmentationAndSurfaceMeshModules ()
Write Surface Segmentation Module tags.
Public Member Functions inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >
FWGDCMIO_API InformationEntity (const std::shared_ptr< ::gdcm::Writer > &writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< const ::fwMedData::ModelSeries > &object, const ::fwLog::Logger::sptr &logger=nullptr, ProgressCallback progress=nullptr, CancelRequestedCallback cancel=nullptr)
Constructor.
virtual FWGDCMIO_API ~InformationEntity ()
Destructor.
Protected Member Functions
virtual FWGDCMIO_API void writeSegmentSequence (const std::shared_ptr< const ::fwData::Reconstruction > &reconstruction,::gdcm::Item &segmentItem, const ::gdcm::SmartPointer< ::gdcm::Segment > &segment, unsigned short segmentNumber)
Write Segment Item into Segment Sequence.
virtual FWGDCMIO_API void writeSurfaceSequence (const std::shared_ptr< const ::fwData::Reconstruction > &reconstruction,::gdcm::Item &surfaceItem, const ::gdcm::SmartPointer< ::gdcm::Surface > &surface, unsigned short segmentNumber)
Write Surface Item into Surface Sequence.
Protected Attributes
::fwGdcmIO::helper::SegmentedPropertyRegistry m_segmentedPropertyRegistry
Structure Dictionary.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_imageInstance
DICOM Image Instance.
Protected Attributes inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >
std::shared_ptr< ::gdcm::Writer > m_writer
GDCM Writer.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< const ::fwMedData::ModelSeries > m_object
FW4SPL Object.
::fwLog::Logger::sptr m_logger
Logger.
ProgressCallback m_progressCallback
Progress callback for jobs.
CancelRequestedCallback m_cancelRequestedCallback
Cancel information for jobs.
Additional Inherited Members
Public Types inherited from fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< bool() > CancelRequestedCallback
Detailed Description
Surface Information Entity class.
Definition at line 28 of file writer/ie/Surface.hpp.
Constructor & Destructor Documentation
fwGdcmIO::writer::ie::Surface::Surface (const std::shared_ptr< ::gdcm::Writer > & writer, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & imageInstance, const ::fwMedData::ModelSeries::csptr & series, const ::fwLog::Logger::sptr & logger = nullptr, ProgressCallback progress = nullptr, CancelRequestedCallback cancel = nullptr)
Constructor.
Parameters
[in] writer GDCM writer that must be enriched
[in] instance DICOM instance used to share information between modules
[in] series Series data
[in] logger Logger
[in] progress Progress callback
[in] cancel Cancel requested callback
Definition at line 45 of file writer/ie/Surface.cpp.
References SLM_ASSERT.
Member Function Documentation
bool fwGdcmIO::writer::ie::Surface::loadSegmentedPropertyRegistry (const ::boost::filesystem::path & filepath)
Load Segmented Property Registry.
Parameters
[in] filepath Path to the registry CSV file
Returns
True on success
Definition at line 67 of file writer/ie/Surface.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_logger, m_segmentedPropertyRegistry, and fwGdcmIO::helper::SegmentedPropertyRegistry::readSegmentedPropertyRegistryFile().
void fwGdcmIO::writer::ie::Surface::writeSegmentSequence (const std::shared_ptr< const ::fwData::Reconstruction > & reconstruction, ::gdcm::Item & segmentItem, const ::gdcm::SmartPointer< ::gdcm::Segment > & segment, unsigned short segmentNumber) protected virtual
Write Segment Item into Segment Sequence.
See also
PS 3.3 C.8.23.1
Parameters
[in] reconstruction Reconstruction data
[in] segmentItem GDCM segment item
[in] segment GDCM segment
[in] segmentNumber Segment number
Definition at line 318 of file writer/ie/Surface.cpp.
References m_imageInstance, fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_logger, and m_segmentedPropertyRegistry.
Referenced by writeSurfaceSegmentationAndSurfaceMeshModules().
void fwGdcmIO::writer::ie::Surface::writeSOPCommonModule () virtual
Write SOP Common Module tags.
See also
PS 3.3 C.12.1
Definition at line 74 of file writer/ie/Surface.cpp.
References fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_instance, fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_writer, and SLM_TRACE.
void fwGdcmIO::writer::ie::Surface::writeSurfaceSegmentationAndSurfaceMeshModules () virtual
Write Surface Segmentation Module tags.
See also
PS 3.3 C.8.23.1 & PS 3.3 C.27.1
Definition at line 91 of file writer/ie/Surface.cpp.
References fwGdcmIO::helper::DicomCodedAttribute::convertEntryToGDCMCodedAttribute(), fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_logger, fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_object, fwGdcmIO::writer::ie::InformationEntity< ::fwMedData::ModelSeries >::m_writer, SLM_WARN_IF, SPTR, writeSegmentSequence(), and writeSurfaceSequence().
void fwGdcmIO::writer::ie::Surface::writeSurfaceSequence (const std::shared_ptr< const ::fwData::Reconstruction > & reconstruction, ::gdcm::Item & surfaceItem, const ::gdcm::SmartPointer< ::gdcm::Surface > & surface, unsigned short segmentNumber) protected virtual
Write Surface Item into Surface Sequence.
See also
PS 3.3 C.27.1
Parameters
[in] reconstruction Reconstruction data
[in] surfaceItem GDCM surface item
[in] surface GDCM surface
[in] segmentNumber Associated segment number
Definition at line 421 of file writer/ie/Surface.cpp.
References fwGdcmIO::helper::DicomDataTools::convertToPresentationType(), fwGdcmIO::container::DicomSurface::getCellBuffer(), fwGdcmIO::container::DicomSurface::getCellBufferSize(), fwGdcmIO::container::DicomSurface::getNormalBuffer(), fwGdcmIO::container::DicomSurface::getNormalBufferSize(), fwGdcmIO::container::DicomSurface::getPointBuffer(), and fwGdcmIO::container::DicomSurface::getPointBufferSize().
Referenced by writeSurfaceSegmentationAndSurfaceMeshModules().
The documentation for this class was generated from the following files:
writer/ie/Surface.hpp
writer/ie/Surface.cpp