fw4spl: fwMDSemanticPatch::V1::V2::fwData::Acquisition Class Reference
fwMDSemanticPatch::V1::V2::fwData::Acquisition Class Reference
Patch an acquisition from version 'V1' to 'V2' within 'MedicalData' context.
#include <Acquisition.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Acquisition)(::fwAtomsPatch::ISemanticPatch))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Acquisition,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Acquisition)(::fwAtomsPatch::ISemanticPatch)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWMDSEMANTICPATCH_API Acquisition ()
Constructor.
FWMDSEMANTICPATCH_API ~Acquisition ()
Destructor.
FWMDSEMANTICPATCH_API Acquisition (const Acquisition &cpy)
Copy constructor.
virtual FWMDSEMANTICPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies patch.
Public Member Functions inherited from fwAtomsPatch::ISemanticPatch
__FWCORE_CLASS_TYPEDEFS ((ISemanticPatch))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((ISemanticPatch)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWATOMSPATCH_API ISemanticPatch ()
Constructor.
FWATOMSPATCH_API ISemanticPatch (const ISemanticPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~ISemanticPatch ()
Destructor.
virtual FWATOMSPATCH_API void apply (const std::shared_ptr< ::fwAtoms::Object > &previous, const std::shared_ptr< ::fwAtoms::Object > &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies modifications between given objects.
virtual FWATOMSPATCH_API bool isApplicable (const std::string &context, const std::string &originVersion, const std::string &targetVersion) const
Returns true if patch is applicable into the context from origin to target versions.
Public Member Functions inherited from fwAtomsPatch::IPatch
__FWCORE_CLASS_TYPEDEFS ((IPatch))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((IPatch)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWATOMSPATCH_API IPatch ()
Constructor. Does nothing.
FWATOMSPATCH_API IPatch (const IPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IPatch ()
Destructor. Does nothing.
virtual FWATOMSPATCH_API const std::string & getOriginClassname () const
Returns the origin classname of the object.
virtual FWATOMSPATCH_API const std::string & getOriginVersion () const
Returns the origin version of the object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::ISemanticPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwAtomsPatch::IPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwAtomsPatch::IPatch
typedef std::map< ::fwAtoms::Object::sptr,::fwAtoms::Object::sptr > NewVersionsType
Protected Types inherited from fwAtomsPatch::ISemanticPatch
typedef std::vector< Context > ContextVectorType
Protected Member Functions inherited from fwAtomsPatch::ISemanticPatch
virtual FWATOMSPATCH_API void addContext (const std::string &context, const std::string &originVersion, const std::string &targetVersion)
Add a context where the patch can be applied.
Protected Attributes inherited from fwAtomsPatch::ISemanticPatch
mutable::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect concurrent access for m_contexts.
ContextVectorType m_contexts
Vector used to store the contexts where the patch can be applied.
Protected Attributes inherited from fwAtomsPatch::IPatch
std::string m_originClassname
Origin classname of the object.
std::string m_originVersion
Origin version of the object.
Detailed Description
Patch an acquisition from version 'V1' to 'V2' within 'MedicalData' context.
Definition at line 25 of file Acquisition.hpp.
Member Function Documentation
fwMDSemanticPatch::V1::V2::fwData::Acquisition::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Acquisition, (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Acquisition)(::fwAtomsPatch::ISemanticPatch)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Acquisition)(fwAtomsPatch::ISemanticPatch)).
void fwMDSemanticPatch::V1::V2::fwData::Acquisition::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) virtual
Applies patch.
Retrieves 'comment' field stored into acquisition's image and moves it into current object 'description' attribute.
Implements fwAtomsPatch::IPatch.
Definition at line 47 of file Acquisition.cpp.
References fwTools::UUID::generateUUID(), fwAtoms::String::New(), and fwAtomsPatch::helper::Object::replaceAttribute().
The documentation for this class was generated from the following files:
Acquisition.hpp
Acquisition.cpp