fw4spl: fwGui::IGuiContainerSrv Class Reference
fwGui::IGuiContainerSrv Class Reference
Defines the service interface managing the layout.
#include <IGuiContainerSrv.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWGUI_API std::shared_ptr< ::fwGui::container::fwContainer > getContainer ()
FWGUI_API void setParent (std::string wid)
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Types
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions
FWGUI_API void initialize ()
Initialize managers.
FWGUI_API void create ()
Creates view, sub-views and toolbar containers. Manages sub-views and toobar services.
FWGUI_API void destroy ()
Stops sub-views and toobar services. Destroys view, sub-views and toolbar containers.
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual FWSERVICES_API void starting ()=0
Initialize the service activity.
virtual FWSERVICES_API void stopping ()=0
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual void swapping ()
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void configuring ()=0
Configure the service before starting. Apply the configuration to service.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API void updating ()=0
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
virtual FWSERVICES_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated objects signals, this method is used for obj/srv auto connection.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Slots
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SET_ENABLED_SLOT = "setEnabled"
Slot to enable/disable the action.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_ENABLE_SLOT = "enable"
Slot to enable the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_DISABLE_SLOT = "disable"
Slot to disable the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SET_VISIBLE_SLOT = "setVisible"
Slot to show/hide the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SHOW_SLOT = "show"
Slot to show the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_HIDE_SLOT = "hide"
Slot to hide the container.
FWGUI_API void setEnabled (bool isEnabled)
SLOT: enable/disable the container.
FWGUI_API void enable ()
SLOT: enable the container.
FWGUI_API void disable ()
SLOT: disable the container.
FWGUI_API void setVisible (bool isVisible)
SLOT: show/hide the container.
FWGUI_API void show ()
SLOT: show the container.
FWGUI_API void hide ()
SLOT: hide the container.
Additional Inherited Members
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Detailed Description
Defines the service interface managing the layout.
Slots
setEnabled(bool isEnabled) : this slot enables the container (if isEnabled = true) or disables it.
enable() : this slot enables the container.
disable() : this slot disables the container
setVisible(bool isVisible) : this slot shows the container (if isVisible = true) or hides it.
show() : this slot shows the container.
hide() : this slot hides the container.
XML Configuration
 <service uid="subView1" type="::gui::view::SDefaultView" autoConnect="no" >
     <gui>
         <layout type="::fwGui::LineLayoutManager" >
             <orientation value="horizontal" />
             <view caption="view3" />
             <view caption="view4" />
             <view caption="view5" />
         </layout>
         <toolBar />
         <slideView />
         <slideView align="top" size="200" opacity="1.0">
             <styleSheet>color: blue; background-color: yellow</styleSheet>
         </slideView>
     </gui>
     <registry>
         <parent wid="myView" />
         <toolBar sid="toolbar1" start="yes" />
         <view sid="subView3" start="yes" />
         <view wid="subView4" />
         <view sid="subView5" />
         <slideView sid="slideView1" start="yes />
         <slideView wid="slideView2" />
      </registry>
 </service>
<layout type="::fwGui::LineLayoutManager" > : give the type of layout.
type {fwGui::LineLayoutManager | fwGui::CardinalLayoutManager | fwGui::TabLayoutManager | fwGui::ToolboxLayoutManager} :
fwGui::LineLayoutManager : all views will be on the same line or column (it depends of the orientation value attribute)
See also
fwGui::layoutManager::LineLayoutManagerBase
fwGui::CardinalLayoutManager : all views will be added around a central view define by the align attribute.
See also
fwGui::layoutManager::CardinalLayoutManagerBase
fwGui::TabLayoutManager : all views will be draw as tab.
See also
fwGui::layoutManager::TabLayoutManagerBase
fwGui::ToolboxLayoutManager : all views will be draw in toolbox.
See also
fwGui::layoutManager::ToolboxLayoutManagerBase
toolBar: defines the toolBar configuration.
See also
fwGui::builder::IToolBarBuilder
slideView: defines a slide view.
See also
fwGui::builder::ISlideViewBuilder
Note
The layout and registry sections can be empty. In this case no subview will be created.
Warning
The order of the view in each section (gui and registry) must be the same.
For example: the view caption "view3" will be connected with the service which have the sid = "subView3" and so one (it also could be a wid).
Definition at line 105 of file IGuiContainerSrv.hpp.
Member Function Documentation
void fwGui::IGuiContainerSrv::create () protected
Creates view, sub-views and toolbar containers. Manages sub-views and toobar services.
Precondition
Parent container must be registered.
Definition at line 111 of file IGuiContainerSrv.cpp.
References fwServices::registry::ActiveWorkers::getDefaultWorker(), and SLM_ASSERT.
Referenced by uiVisuQt::PointEditor::starting(), gui::view::SDefaultView::starting(), uiVisuQt::SnapshotEditor::starting(), basicRegistration::SImagesSubstract::starting(), uiReconstructionQt::OrganMaterialEditor::starting(), uiImageQt::ImageInfo::starting(), monitorQt::DumpEditor::starting(), uiMedDataQt::editor::SOrganTransformation::starting(), uiVisuQt::STransformEditor::starting(), guiQt::editor::Code::starting(), uiReconstructionQt::RepresentationEditor::starting(), vtkSimpleNegato::SRenderer::starting(), ioPacs::SQueryEditor::starting(), uiImageQt::ImageTransparency::starting(), ioDicomWeb::SQueryEditor::starting(), uiImageQt::SliceIndexPositionEditor::starting(), uiMeasurementQt::editor::Distance::starting(), uiTF::TransferFunctionEditor::starting(), uiMedDataQt::editor::SSeries::starting(), guiQt::editor::SSignalButton::starting(), guiQt::editor::SActivityView::starting(), activities::editor::SCreateActivity::starting(), guiQt::editor::SSelectionMenuButton::starting(), uiMeasurementQt::editor::SLandmarks::starting(), uiMedDataQt::editor::SSelector::starting(), guiQt::editor::SListView::starting(), uiImageQt::WindowLevel::starting(), ioDicom::SFilterSelectionEditor::starting(), guiQt::editor::SSlider::starting(), ioDicom::SSliceIndexDicomEditor::starting(), ioPacs::SPacsConfigurationEditor::starting(), guiQt::editor::SDynamicView::starting(), ioDicomWeb::SSliceIndexDicomPullerEditor::starting(), guiQt::editor::DynamicView::starting(), ioPacs::SSliceIndexDicomPullerEditor::starting(), uiMedDataQt::editor::SActivityWizard::starting(), guiQt::editor::SParameters::starting(), and fwRenderQt::SRender::starting().
void fwGui::IGuiContainerSrv::initialize () protected
Initialize managers.
See also
fwGui::registrar::ViewRegistrar::initialize(), fwGui::layoutManager::IViewLayoutManager::initialize(), fwGui::builder::IToolBarBuilder::initialize()
Definition at line 60 of file IGuiContainerSrv.cpp.
References fwTools::fwID::getID(), fwServices::IService::m_configuration, and SLM_ASSERT.
Referenced by gui::view::SDefaultView::configuring(), basicRegistration::SImagesSubstract::configuring(), uiVisuQt::PointEditor::configuring(), uiVisuQt::STransformEditor::configuring(), uiMedDataQt::editor::SOrganTransformation::configuring(), ioPacs::SQueryEditor::configuring(), uiReconstructionQt::OrganMaterialEditor::configuring(), ioDicomWeb::SQueryEditor::configuring(), uiImageQt::ImageInfo::configuring(), uiReconstructionQt::RepresentationEditor::configuring(), monitorQt::DumpEditor::configuring(), fwGui::view::IActivityView::configuring(), guiQt::editor::Code::configuring(), uiVisuQt::SnapshotEditor::configuring(), uiImageQt::ImageTransparency::configuring(), uiTF::TransferFunctionEditor::configuring(), activities::editor::SCreateActivity::configuring(), vtkSimpleNegato::SRenderer::configuring(), uiMeasurementQt::editor::Distance::configuring(), uiMedDataQt::editor::SSelector::configuring(), ioDicom::SFilterSelectionEditor::configuring(), guiQt::editor::SSignalButton::configuring(), uiImageQt::SliceIndexPositionEditor::configuring(), uiMedDataQt::editor::SSeries::configuring(), uiMeasurementQt::editor::SLandmarks::configuring(), guiQt::editor::SSelectionMenuButton::configuring(), guiQt::editor::SListView::configuring(), ioDicom::SSliceIndexDicomEditor::configuring(), uiImageQt::WindowLevel::configuring(), ioPacs::SPacsConfigurationEditor::configuring(), ioDicomWeb::SSliceIndexDicomPullerEditor::configuring(), guiQt::editor::SSlider::configuring(), ioPacs::SSliceIndexDicomPullerEditor::configuring(), guiQt::editor::SParameters::configuring(), fwRenderQt::SRender::configuring(), uiMedDataQt::editor::SActivityWizard::configuring(), guiQt::editor::DynamicView::configuring(), and visuVTKAdaptor::SOrientationMarker::starting().
The documentation for this class was generated from the following files:
IGuiContainerSrv.hpp
IGuiContainerSrv.cpp