fw4spl: fwStructuralPatch::fwData::Material::V3ToV4 Class Reference
fwStructuralPatch::fwData::Material::V3ToV4 Class Reference
Structural patch to convert a fwData::Material from version '3' to version '4'.
#include <V3ToV4.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((V3ToV4)(::fwStructuralPatch::fwData::Material::V3ToV4))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new V3ToV4,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((V3ToV4)(::fwStructuralPatch::fwData::Material::V3ToV4)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWSTRUCTURALPATCH_API V3ToV4 ()
Constructor.
FWSTRUCTURALPATCH_API ~V3ToV4 ()
Destructor.
FWSTRUCTURALPATCH_API V3ToV4 (const V3ToV4 &cpy)
Copy constructor.
virtual FWSTRUCTURALPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies patch.
Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
__FWCORE_CLASS_TYPEDEFS ((IStructuralPatch))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((IStructuralPatch)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWATOMSPATCH_API IStructuralPatch ()
Constructor.
FWATOMSPATCH_API IStructuralPatch (const IStructuralPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IStructuralPatch ()
Destructor.
virtual FWATOMSPATCH_API void apply (const std::shared_ptr< ::fwAtoms::Object > &previous, const std::shared_ptr< ::fwAtoms::Object > &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions)
Applies the patch to the specified object.
virtual FWATOMSPATCH_API const std::string & getTargetClassname () const
Returns the target classname of the object.
virtual FWATOMSPATCH_API const std::string & getTargetVersion () const
Returns the target version of the object.
Public Member Functions inherited from fwAtomsPatch::IPatch
__FWCORE_CLASS_TYPEDEFS ((IPatch))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((IPatch)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWATOMSPATCH_API IPatch ()
Constructor. Does nothing.
FWATOMSPATCH_API IPatch (const IPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IPatch ()
Destructor. Does nothing.
virtual FWATOMSPATCH_API const std::string & getOriginClassname () const
Returns the origin classname of the object.
virtual FWATOMSPATCH_API const std::string & getOriginVersion () const
Returns the origin version of the object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwAtomsPatch::IPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwAtomsPatch::IPatch
typedef std::map< ::fwAtoms::Object::sptr,::fwAtoms::Object::sptr > NewVersionsType
Protected Member Functions inherited from fwAtomsPatch::IStructuralPatch
FWATOMSPATCH_API void updateVersion (std::shared_ptr< ::fwAtoms::Object > current)
Updates the version of the patched object.
Protected Attributes inherited from fwAtomsPatch::IStructuralPatch
std::string m_targetClassname
Target type.
std::string m_targetVersion
Target version.
Protected Attributes inherited from fwAtomsPatch::IPatch
std::string m_originClassname
Origin classname of the object.
std::string m_originVersion
Origin version of the object.
Detailed Description
Structural patch to convert a fwData::Material from version '3' to version '4'.
Definition at line 24 of file V3ToV4.hpp.
Member Function Documentation
fwStructuralPatch::fwData::Material::V3ToV4::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new V3ToV4, (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((V3ToV4)(::fwStructuralPatch::fwData::Material::V3ToV4)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((V3ToV4)(fwStructuralPatch::fwData::Material::V3ToV4)).
void fwStructuralPatch::fwData::Material::V3ToV4::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) virtual
Applies patch.
Added new map of additional array.
Implements fwAtomsPatch::IPatch.
Definition at line 49 of file V3ToV4.cpp.
References fwAtoms::Object::getAttribute(), fwAtoms::String::New(), fwAtomsPatch::helper::Object::removeAttribute(), fwAtomsPatch::helper::Object::replaceAttribute(), fwAtoms::Numeric::setFromString(), and fwAtomsPatch::IStructuralPatch::updateVersion().
The documentation for this class was generated from the following files:
V3ToV4.hpp
V3ToV4.cpp