fw4spl: fwPacsIO::helper::Series Class Reference
fwPacsIO::helper::Series Class Reference
Series Helper.
#include <Series.hpp>
Public Types
typedef ::fwMedData::SeriesDB::ContainerType DicomSeriesContainer
typedef std::vector< std::string > InstanceUIDContainer
typedef std::map< std::string, unsigned int > InstanceCountMap
Static Public Member Functions
static FWPACSIO_API void releaseResponses (OFList< QRResponse * > responses)
Release the responses.
static FWPACSIO_API DicomSeriesContainer toFwMedData (OFList< QRResponse * > responses)
Convert DCMTK series to fwMedData::DicomSeries.
static FWPACSIO_API InstanceUIDContainer toSeriesInstanceUIDContainer (OFList< QRResponse * > responses)
Convert DCMTK series to instance uid vector.
static FWPACSIO_API InstanceUIDContainer toSeriesInstanceUIDContainer (DicomSeriesContainer series)
Convert std::vector< ::fwMedData::DicomSeries > to series instance uid container.
Detailed Description
Series Helper.
Definition at line 38 of file io/fwPacsIO/include/fwPacsIO/helper/Series.hpp.
Member Function Documentation
void fwPacsIO::helper::Series::releaseResponses (OFList< QRResponse * > responses) static
Release the responses.
Parameters
[in] responses Responses to free
Definition at line 25 of file io/fwPacsIO/src/fwPacsIO/helper/Series.cpp.
Referenced by ioPacs::SSeriesPusher::checkSeriesOnPACS(), and ioPacs::SQueryEditor::updating().
Series::DicomSeriesContainer fwPacsIO::helper::Series::toFwMedData (OFList< QRResponse * > responses) static
Convert DCMTK series to fwMedData::DicomSeries.
Parameters
[in] responses DCMTK responses from the pacs that must be converted
Definition at line 36 of file io/fwPacsIO/src/fwPacsIO/helper/Series.cpp.
Referenced by ioPacs::SQueryEditor::updating().
Series::InstanceUIDContainer fwPacsIO::helper::Series::toSeriesInstanceUIDContainer (OFList< QRResponse * > responses) static
Convert DCMTK series to instance uid vector.
Parameters
[in] responses DCMTK responses from the pacs that must be converted
Definition at line 164 of file io/fwPacsIO/src/fwPacsIO/helper/Series.cpp.
Referenced by ioPacs::SSeriesPuller::pullSeries(), and ioPacs::SSeriesPuller::readLocalSeries().
Series::InstanceUIDContainer fwPacsIO::helper::Series::toSeriesInstanceUIDContainer (DicomSeriesContainer series) static
Convert std::vector< ::fwMedData::DicomSeries > to series instance uid container.
Parameters
[in] series Series vector used to extract the series instance uids
Definition at line 150 of file io/fwPacsIO/src/fwPacsIO/helper/Series.cpp.
The documentation for this class was generated from the following files:
io/fwPacsIO/include/fwPacsIO/helper/Series.hpp
io/fwPacsIO/src/fwPacsIO/helper/Series.cpp