fw4spl: fwComEd::CompositeMsg Class Reference
fwComEd::CompositeMsg Class Reference
Object event message specialized for Composite : store modification information.
#include <CompositeMsg.hpp>
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((CompositeMsg)(::fwServices::ObjectMsg),(()),::fwServices::factory::message::New< CompositeMsg >)
FWCOMED_API CompositeMsg (::fwServices::ObjectMsg::Key key)
Constructor.
virtual FWCOMED_API ~CompositeMsg () throw ()
Destructor : does nothing.
FWCOMED_API void appendAddedKey (std::string _compositeKey,::fwData::Object::sptr _pNewObject)
This method add an object in the composite of added keys.
FWCOMED_API::fwData::Composite::sptr getAddedKeys () const
Return the composite of the added keys.
FWCOMED_API void appendRemovedKey (std::string _compositeKey,::fwData::Object::sptr _pOldObject)
This method add an object in the composite of removed keys.
FWCOMED_API::fwData::Composite::sptr getRemovedKeys () const
Return the composite of the removed keys.
FWCOMED_API void appendChangedKey (std::string _compositeKey,::fwData::Object::sptr _pOldObject,::fwData::Object::sptr _pNewObject)
This method add an object in the composites of changed keys.
FWCOMED_API::fwData::Composite::sptr getOldChangedKeys () const
Return the composite of the old changed keys (key which will be replaced).
FWCOMED_API::fwData::Composite::sptr getNewChangedKeys () const
Return the composite of the new changed keys.
Static Public Attributes
static FWCOMED_API std::string ADDED_KEYS = "ADDED_KEYS"
Event identifier used to inform that keys were added.
static FWCOMED_API std::string REMOVED_KEYS = "REMOVED_KEYS"
Event identifier used to inform that keys were removed.
static FWCOMED_API std::string CHANGED_KEYS = "CHANGED_KEYS"
Event identifier used to inform that keys were changed.
Detailed Description
Object event message specialized for Composite : store modification information.
Date:
2005-2009.
See also:
fwServices::ObjectMsg
Definition at line 26 of file CompositeMsg.hpp.
Constructor & Destructor Documentation
fwComEd::CompositeMsg::CompositeMsg (::fwServices::ObjectMsg::Key key)
Constructor.
Parameters:
key Private construction key
Definition at line 28 of file CompositeMsg.cpp.
Member Function Documentation
void fwComEd::CompositeMsg::appendAddedKey (std::string _compositeKey, ::fwData::Object::sptr _pNewObject)
This method add an object in the composite of added keys.
Parameters:
[in] _compositeKey : the key of the added object.
[in] _pNewObject : the added object.
Definition at line 43 of file CompositeMsg.cpp.
References ADDED_KEYS, fwServices::ObjectMsg::addEvent(), fwServices::ObjectMsg::hasEvent(), and SLM_ASSERT.
void fwComEd::CompositeMsg::appendChangedKey (std::string _compositeKey, ::fwData::Object::sptr _pOldObject, ::fwData::Object::sptr _pNewObject)
This method add an object in the composites of changed keys.
Parameters:
[in] _compositeKey : the key of the changed object.
[in] _pOldObject : the old object which will be replaced.
[in] _pNewObject : the new object.
Definition at line 85 of file CompositeMsg.cpp.
References fwServices::ObjectMsg::addEvent(), CHANGED_KEYS, fwServices::ObjectMsg::hasEvent(), and SLM_ASSERT.
void fwComEd::CompositeMsg::appendRemovedKey (std::string _compositeKey, ::fwData::Object::sptr _pOldObject)
This method add an object in the composite of removed keys.
Parameters:
[in] _compositeKey : the key of the removed object.
[in] _pOldObject : the object which will be removed.
Definition at line 64 of file CompositeMsg.cpp.
References fwServices::ObjectMsg::addEvent(), fwServices::ObjectMsg::hasEvent(), REMOVED_KEYS, and SLM_ASSERT.
The documentation for this class was generated from the following files:
CompositeMsg.hpp
CompositeMsg.cpp