fw4spl: fwServices::ObjectMsg Class Reference
fwServices::ObjectMsg Class Reference
Object message : indicate modifications having occurred or being performed on a object.
#include <ObjectMsg.hpp>
Classes
class Registrar
Class used to register a class factory in factory registry. This class defines also the objectMsg factory ('create')
Public Types
typedef
::fwServices::factory::message::Key Key
typedef ::boost::function< void() > MessageCallbackType
Defines callback type.
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((ObjectMsg)(::fwTools::Object),(()),::fwServices::factory::message::New< ObjectMsg >)
FWSERVICES_API ObjectMsg (::fwServices::ObjectMsg::Key key)
Constructor.
virtual FWSERVICES_API ~ObjectMsg ()
Destructor, do nothing.
FWSERVICES_API std::string getGeneralInfo () const
Give some message informations in a string.
FWSERVICES_API void setMessageCallback (MessageCallbackType callback)
Set a callback to the message which will be executed during message destruction.
Event management
FWSERVICES_API void addEvent (std::string _eventId,::fwData::Object::csptr _pDataInfo=::fwData::Object::sptr())
This method add an event to the message before message notification.
FWSERVICES_API bool hasEvent (std::string _eventId) const
This method is used to know if a specific event declared in the message.
FWSERVICES_API std::vector
< std::string > getEventIds () const
This method returns all id event contained in the message.
FWSERVICES_API::fwData::Object::csptr getDataInfo (std::string _eventId) const
This method returns the data info associated to event, this data can be an null ptr when the event not needs some additional informations.
Management of source/subject message
FWSERVICES_API void setSource (WPTR(::fwServices::IService) _source)
Set message source (service which notifies subject obsevers)
FWSERVICES_API WPTR (::fwServices::IService) getSource() const
Get message source (service which notifies subject obsevers)
FWSERVICES_API void setSubject (::fwData::Object::wptr _subject)
Set message subject (object observed)
FWSERVICES_API::fwData::Object::wptr getSubject () const
Get message subject (object observed)
Static Public Attributes
static FWSERVICES_API std::string NEW_OBJECT = "ObjectMsg::NEW_OBJECT"
Event identifier used to inform that an object was created.
static FWSERVICES_API std::string UPDATED_OBJECT = "ObjectMsg::UPDATED_OBJECT"
Event identifier used to inform that an object was modified.
static FWSERVICES_API std::string DELETE_OBJECT = "ObjectMsg::DELETE_OBJECT"
Event identifier used to inform that an object has to be removed.
static FWSERVICES_API std::string ADDED_FIELDS = "ADDED_FIELDS"
Event identifier used to inform that fields were added, removed or changed.
static FWSERVICES_API std::string REMOVED_FIELDS = "REMOVED_FIELDS"
Event identifier used to inform that fields were added, removed or changed.
static FWSERVICES_API std::string CHANGED_FIELDS = "CHANGED_FIELDS"
Event identifier used to inform that fields were added, removed or changed.
Protected Member Functions
FWSERVICES_API ObjectMsg ()
Constructor, do nothing.
virtual FWSERVICES_API void info (std::ostream &_sstream) const
Give some message informations, this method uses getGeneralInfo.
Protected Attributes
std::map< std::string,::fwData::Object::csptr > m_eventId2DataInfo
Intern map which associates an Event Id (string) to a dataInfo (fwData::Object).
ModifiedFieldsContainerType m_removedFields
ModifiedFieldsContainerType m_addedFields
ModifiedFieldsContainerType m_oldChangedFields
ModifiedFieldsContainerType m_newChangedFields
Friends
FWSERVICES_API friend
std::ostream & operator<< (std::ostream &_sstream, const ObjectMsg &_message)
Streaming a service.
Field events
typedef std::map< std::string,::fwData::Object::sptr > ModifiedFieldsContainerType
Append an object to the added fields list.
typedef
::fwData::Object::FieldNameType FieldNameType
Append an object to the added fields list.
FWSERVICES_API void appendAddedField (const FieldNameType &fieldName,::fwData::Object::sptr object)
Append an object to the added fields list.
FWSERVICES_API const
ModifiedFieldsContainerType & getAddedFields () const
Return the map of the added fields.
FWSERVICES_API void appendRemovedField (const FieldNameType &fieldName,::fwData::Object::sptr object)
Append an object to the removed fields list.
FWSERVICES_API const
ModifiedFieldsContainerType & getRemovedFields () const
Return the map of the removed fields.
FWSERVICES_API void appendChangedField (const FieldNameType &fieldName,::fwData::Object::sptr oldObject,::fwData::Object::sptr newObject)
Append an object to the changed fields list.
FWSERVICES_API const
ModifiedFieldsContainerType & getOldChangedFields () const
Return a map of old object in changed fields list.
FWSERVICES_API const
ModifiedFieldsContainerType & getNewChangedFields () const
Return a map of new object in changed fields list.
Detailed Description
Object message : indicate modifications having occurred or being performed on a object.
Date:
2007-2009.
The message only provides identifiers enabling to retrieve the modified information on the object. This should be embed the information. The m_subject is present to check that the considered object (subject to modifications) is the one known (or referenced) by the service receiving the message through the observation mechanism.
The m_subject should a priori not be used by a service to access the object. Indeed, to be able to work without observation (therefore without messages, this being possible as observations are optional), a service requires a reference to the object allowing to perform computations. This reference is generally acquired either at attachment time (e.g. the object of interest being the one the considered service is attached to) or at configuration time (e.g. passing an unique universal identifier in the XML configuration). Therefore, for coherence and homogeneity, a service should be able to access object(s) it requires in the same way, whatever the working mode (i.e. explicit execution without observations or implicit execution with observation).
Concerning the type of m_subject : a software instance is based on a (root) tree structured complex object (to which services are attached, corresponding to functionalities). So that the root object naturally destroys through unreferencement, it must be avoided that instances (except pure data objects) keep strong references on data objects composing the root, otherwise there is a risk of cross strong references, forgiving the natural destruction of objects. For this reason, messages should also respect this rule and the m_subject should be a weak reference (weak pointer).
The ObjectMsg contains event identifiers with associated additional information.
Definition at line 47 of file ObjectMsg.hpp.
Member Typedef Documentation
typedef ::fwData::Object::FieldNameType fwServices::ObjectMsg::FieldNameType
Append an object to the added fields list.
Parameters:
[in] fieldName : the field name of the added object.
[in] object : the added object.
Definition at line 165 of file ObjectMsg.hpp.
typedef std::map<std::string, ::fwData::Object::sptr> fwServices::ObjectMsg::ModifiedFieldsContainerType
Append an object to the added fields list.
Parameters:
[in] fieldName : the field name of the added object.
[in] object : the added object.
Definition at line 164 of file ObjectMsg.hpp.
Constructor & Destructor Documentation
fwServices::ObjectMsg::ObjectMsg (::fwServices::ObjectMsg::Key key)
Constructor.
Parameters:
key Private construction key
Definition at line 30 of file ObjectMsg.cpp.
Member Function Documentation
void fwServices::ObjectMsg::addEvent (std::string _eventId, ::fwData::Object::csptr _pDataInfo = ::fwData::Object::sptr())
This method add an event to the message before message notification.
Parameters:
[in] _eventId the event added in the message
[in] _pDataInfo additional information concerning message (it is an optional parameter)
Note:
a message can contain many events.
Definition at line 50 of file ObjectMsg.cpp.
References m_eventId2DataInfo.
Referenced by fwComEd::GraphMsg::addedNode(), fwComEd::GraphMsg::addingEdge(), appendAddedField(), fwComEd::CompositeMsg::appendAddedKey(), fwComEd::VectorMsg::appendAddedObject(), fwComEd::SeriesDBMsg::appendAddedSeries(), appendChangedField(), fwComEd::CompositeMsg::appendChangedKey(), appendRemovedField(), fwComEd::CompositeMsg::appendRemovedKey(), fwComEd::VectorMsg::appendRemovedObject(), fwComEd::SeriesDBMsg::appendRemovedSeries(), fwComEd::GraphMsg::removedNode(), fwComEd::GraphMsg::removingNode(), fwComEd::GraphMsg::selectedNode(), fwComEd::InteractionMsg::setEvent(), fwComEd::ImageMsg::setSliceIndex(), fwComEd::TransferFunctionMsg::setWindowLevel(), and fwComEd::GraphMsg::unselectedNode().
void fwServices::ObjectMsg::appendAddedField (const FieldNameType & fieldName, ::fwData::Object::sptr object)
Append an object to the added fields list.
Parameters:
[in] fieldName : the field name of the added object.
[in] object : the added object.
Definition at line 182 of file ObjectMsg.cpp.
References ADDED_FIELDS, addEvent(), hasEvent(), and SLM_ASSERT.
void fwServices::ObjectMsg::appendChangedField (const FieldNameType & fieldName, ::fwData::Object::sptr oldObject, ::fwData::Object::sptr newObject)
Append an object to the changed fields list.
Parameters:
[in] fieldName : the field name of the changed object.
[in] oldObject : the old object which will be replaced.
[in] newObject : the new object.
Definition at line 224 of file ObjectMsg.cpp.
References addEvent(), CHANGED_FIELDS, hasEvent(), and SLM_ASSERT.
void fwServices::ObjectMsg::appendRemovedField (const FieldNameType & fieldName, ::fwData::Object::sptr object)
Append an object to the removed fields list.
Parameters:
[in] fieldName : the field name of the removed object.
[in] object : the object which will be removed.
Definition at line 203 of file ObjectMsg.cpp.
References addEvent(), hasEvent(), REMOVED_FIELDS, and SLM_ASSERT.
fwData::Object::csptr fwServices::ObjectMsg::getDataInfo (std::string _eventId) const
This method returns the data info associated to event, this data can be an null ptr when the event not needs some additional informations.
Parameters:
[in] _eventId event id used to find his associated data
Returns:
associated data information
Definition at line 77 of file ObjectMsg.cpp.
References m_eventId2DataInfo.
Referenced by fwComEd::GraphMsg::getAddedNode(), fwComEd::GraphMsg::getAddingEdge(), fwComEd::GraphMsg::getRemovedNode(), fwComEd::GraphMsg::getRemovingNode(), fwComEd::GraphMsg::getSelectedNode(), and fwComEd::GraphMsg::getUnselectedNode().
std::vector< std::string > fwServices::ObjectMsg::getEventIds () const
This method returns all id event contained in the message.
Returns:
the list of event
Definition at line 64 of file ObjectMsg.cpp.
References m_eventId2DataInfo.
bool fwServices::ObjectMsg::hasEvent (std::string _eventId) const
This method is used to know if a specific event declared in the message.
Parameters:
[in] _eventId id of the event researched
Returns:
true if message contain the event id
Definition at line 57 of file ObjectMsg.cpp.
References m_eventId2DataInfo.
Referenced by appendAddedField(), fwComEd::CompositeMsg::appendAddedKey(), fwComEd::VectorMsg::appendAddedObject(), fwComEd::SeriesDBMsg::appendAddedSeries(), appendChangedField(), fwComEd::CompositeMsg::appendChangedKey(), appendRemovedField(), fwComEd::CompositeMsg::appendRemovedKey(), fwComEd::VectorMsg::appendRemovedObject(), fwComEd::SeriesDBMsg::appendRemovedSeries(), fwComEd::TransferFunctionMsg::getLevel(), fwComEd::ImageMsg::getSliceIndex(), and fwComEd::TransferFunctionMsg::getWindow().
Friends And Related Function Documentation
FWSERVICES_API friend std::ostream& operator<< (std::ostream & _sstream, const ObjectMsg & _message) [friend]
Streaming a service.
See also:
ObjectMsg::operator<<(std::ostream & _ostream, ObjectMsg& _service)
Note:
Invoke ObjectMsg::info(std::ostream)
Definition at line 131 of file ObjectMsg.cpp.
Member Data Documentation
std::map< std::string , ::fwData::Object::csptr > fwServices::ObjectMsg::m_eventId2DataInfo [protected]
Intern map which associates an Event Id (string) to a dataInfo (fwData::Object).
Some event has not data info, in this cases, the event is in map but the ::fwData::Object::sptr is null.
Definition at line 235 of file ObjectMsg.hpp.
Referenced by addEvent(), getDataInfo(), getEventIds(), getGeneralInfo(), hasEvent(), and fwComEd::InteractionMsg::setEvent().
The documentation for this class was generated from the following files:
ObjectMsg.hpp
ObjectMsg.cpp