fw4spl: fwTools::fwID Class Reference
fwTools::fwID Class Reference
Defines ID for fwTools::Object. It is used to associate ID with object.
#include <fwID.hpp>
Public Types
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Public Member Functions
virtual bool isA (const std::string &type) const
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
Protected Member Functions
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Defines ID for fwTools::Object. It is used to associate ID with object.
Date
2007-2012.
Definition at line 30 of file fwID.hpp.
Member Enumeration Documentation
enum fwTools::fwID::Policy
Enumerator
EMPTY
return an empty id if no one set
GENERATE
generate a new id if necessary
MUST_EXIST
throw an exception if object has not id.
Definition at line 39 of file fwID.hpp.
Member Function Documentation
bool fwTools::fwID::exist (IDType _id) static
Test if the given id exist (i.e recorded in fwID dictionary)
Parameters
[in] _id : the id to test.
Returns
true iff the given id is recorded in fwID dictionary.
Note
This method is thread-safe.
Definition at line 33 of file fwID.cpp.
Referenced by fwGui::GuiRegistry::actionServiceSetActive(), fwGui::GuiRegistry::actionServiceSetExecutable(), fwGui::GuiRegistry::actionServiceSetVisible(), fwGui::GuiRegistry::actionServiceStarting(), fwGui::GuiRegistry::actionServiceStopping(), fwGui::ActionCallbackBase::check(), ctrlSelection::BookmarkSrv::configuring(), fwGui::ActionCallbackBase::execute(), fwServices::get(), fwServices::AppConfigManager2::getConfigRoot(), getID(), uiMedData::action::SExportSeries::info(), fwGui::registrar::MenuBarRegistrar::manage(), fwGui::registrar::ViewRegistrar::manage(), fwGui::registrar::MenuRegistrar::manage(), fwGui::registrar::ToolBarRegistrar::manage(), fwGui::registrar::ViewRegistrar::manageMenuBar(), fwGui::registrar::ViewRegistrar::manageToolBar(), uiMedData::editor::SSelector::onRemoveSeries(), fwServices::AppConfigManager::startConnections(), preferences::Plugin::stop(), scene2D::processing::SComputeHistogram::stopping(), gui::action::SStarter::stopping(), fwGui::registrar::MenuBarRegistrar::unmanage(), fwGui::registrar::ViewRegistrar::unmanage(), fwGui::registrar::MenuRegistrar::unmanage(), fwGui::registrar::ToolBarRegistrar::unmanage(), fwGui::registrar::ViewRegistrar::unmanageMenuBar(), fwGui::registrar::ViewRegistrar::unmanageToolBar(), fwGui::GuiRegistry::unregisterActionSIDToParentSID(), fwGui::GuiRegistry::unregisterSIDContainer(), fwGui::GuiRegistry::unregisterSIDMenu(), fwGui::GuiRegistry::unregisterSIDMenuBar(), fwGui::GuiRegistry::unregisterSIDToolBar(), gui::action::SBooleanSlotCaller::updating(), gui::action::SSlotCaller::updating(), gui::action::SModifyLayout::updating(), ctrlSelection::ImageUpdateAxis::updating(), uiMedData::editor::SOrganTransformation::updating(), gui::action::SPushObject::updating(), and gui::action::SStarter::updating().
fwID::IDType fwTools::fwID::getID (Policy policy = GENERATE) const protected
Returns the id of the object. If it is not set and the policy value is.
EMPTY then an empty id is returned
GENERATE (default) then a new ID will be generated (and recorded) using the pattern "CLASSNAME-NUM". NUM is always increasing
MUST_EXIST then an exception Failed is raised
Note
We consider an object be constant whatever if its id is generated.
This method is thread-safe.
Definition at line 78 of file fwID.cpp.
References EMPTY, exist(), GENERATE, getRootedClassname(), and MUST_EXIST.
Referenced by gui::action::SSlotCaller::configuring(), fwServices::helper::Config::createProxy(), fwServices::AppConfigManager2::getConfigRoot(), fwServices::IService::getObject(), fwServices::IService::getObjectId(), fwGui::IGuiContainerSrv::initialize(), fwGui::IActionSrv::initialize(), fwServices::helper::Config::parseConnections(), fwServices::IService::reconfiguring(), fwServices::IService::start(), gui::editor::DummyEditor::starting(), gui::action::SConfigLauncher::starting(), fwServices::IService::stop(), fwServices::IService::swap(), fwServices::IService::swapKey(), visuVTKAdaptor::Image::updateImageOpacity(), and uiMedData::SSeriesViewer::updating().
fwTools::Object::sptr fwTools::fwID::getObject (fwID::IDType requestID) static
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
Note
This method is thread-safe.
Definition at line 117 of file fwID.cpp.
References SLM_ASSERT.
Referenced by ctrlSelection::updater::SObjFromUid::add(), ctrlSelection::updater::SObjFromUid::addOrSwap(), uiMedData::widget::ActivityDataView::checkAndComputeData(), uiMedData::widget::ActivityDataView::checkData(), ctrlSelection::BookmarkSrv::configuring(), fwServices::helper::Config::createConnections(), fwServices::helper::Config::createProxy(), fwServices::helper::Config::disconnectProxies(), visuVTKAdaptor::Text::doConfigure(), visuVTKAdaptor::Snapshot::doStop(), uiMedData::widget::ActivityDataView::eventFilter(), fwServices::get(), fwServices::AppConfigManager::getConfigRoot(), fwServices::AppConfigManager2::getConfigRoot(), scene2D::adaptor::IAdaptor::getRegisteredServices(), uiMedData::widget::Selector::getSeries(), uiMedData::widget::Selector::getSeriesFromStudyIndex(), uiTF::TransferFunctionEditor::getTFSelection(), uiMedData::action::SExportSeries::info(), uiMedData::editor::SModelSeriesList::onCurrentItemChanged(), uiMedData::editor::SSeries::onExportClicked(), uiMedData::editor::SSelector::onRemoveSeries(), ctrlSelection::updater::STranslate::starting(), ctrlSelection::wrapper::SImageSignalForwarder::starting(), ioQt::SPdfWriter::starting(), ctrlCamp::SCopy::stopping(), scene2D::processing::SComputeHistogram::stopping(), ctrlSelection::updater::SObjFromUid::swap(), uiImage::WindowLevel::swapCurrentTFAndNotify(), basicRegistration::STransformMesh::updating(), basicRegistration::SImagesSubstract::updating(), gui::action::SBooleanSlotCaller::updating(), uiMedData::action::SInitNewSeries::updating(), gui::action::SSlotCaller::updating(), ctrlSelection::ImageUpdateAxis::updating(), uiMedData::editor::SOrganTransformation::updating(), gui::action::SPushObject::updating(), uiMedData::editor::SSeries::updating(), and uiImage::WindowLevel::updating().
bool fwTools::fwID::hasID () const protected
Return true if the object has an id set.
Note
This method is thread-safe.
Definition at line 48 of file fwID.cpp.
void fwTools::fwID::resetID () protected
Release the id for the object.
Note
This method is thread-safe
Definition at line 134 of file fwID.cpp.
void fwTools::fwID::setID (IDType newID) protected virtual
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
Warning
Cannot set a empty ID.
Note
This method is thread-safe.
Definition at line 56 of file fwID.cpp.
References OSLM_FATAL_IF.
The documentation for this class was generated from the following files:
fwID.hpp
fwID.cpp