fw4spl: fwGdcmIO::helper::DicomData Class Reference
fwGdcmIO::helper::DicomData Class Reference
This class contains helpers to handle GDCM data. It implements many tag value getters/setters. It defines also some tools for converting GDCM data to FW4SPL data.
#include <DicomData.hpp>
Static Public Member Functions
template<uint16_t GROUP, uint16_t ELEMENT>
static const std::string getTagValue (const ::gdcm::DataSet &dataset)
Return a string from a tag found in dataset. An empty string returned means the tag is not found or empty. The value is returned without binary space padding.
template<uint16_t GROUP, uint16_t ELEMENT>
static const std::string getTrimmedTagValue (const ::gdcm::DataSet &dataset)
Return a trimmed string from a tag found in dataset.
template<uint16_t GROUP, uint16_t ELEMENT, typename T >
static const T getTagValue (const ::gdcm::DataSet &dataset)
Return a value from a tag found in dataset.
template<uint16_t GROUP, uint16_t ELEMENT>
static void setTagValue (const std::string &value,::gdcm::DataSet &dataset)
Insert a string of character in a tag of a data set.
template<typename T , uint16_t GROUP, uint16_t ELEMENT>
static void setTagValue (const T &value,::gdcm::DataSet &dataset)
Insert the value of a tag in a data set.
template<typename T , uint16_t GROUP, uint16_t ELEMENT>
static void setTagValues (const T *array, const unsigned int size,::gdcm::DataSet &dataset)
Insert multiple values of a tag in a data set.
static FWGDCMIO_API void setSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, const ::gdcm::Tag &tag,::gdcm::DataSet &dataset)
Set and insert a sequence of items with a tag in the data set specified.
template<uint16_t GROUP, uint16_t ELEMENT>
static void setSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence,::gdcm::DataSet &dataset)
Set and insert a sequence of items with a tag in the data set specified.
template<uint16_t GROUP, uint16_t ELEMENT>
static void insertSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence,::gdcm::DataSet &dataset)
Insert a sequence of items with a tag in the data set specified. If the tag already exists, items of the old and new sequences are added in a new one.
template<typename T >
static bool valueOf (const std::string &str, T &obj)
Return the pixel type of a gdcm Image.
static FWGDCMIO_APIconst::fwTools::Type getPixelType (const ::gdcm::PixelFormat &pixelFormat)
Return the pixel type from a gdcm pixel format.
static FWGDCMIO_APIconst::fwTools::Type getPixelType (const ::gdcm::Image &image)
Return the pixel type of a gdcm Image.
static FWGDCMIO_APIconst::gdcm::PixelFormat getPixelType (const ::fwData::Image::csptr image)
Return the pixel type of a fwData Image.
static FWGDCMIO_APIconst::gdcm::PhotometricInterpretation getPhotometricInterpretation (const ::fwData::Image &image)
Return the photometric interpretation of an acquisition.
static FWGDCMIO_API::gdcm::Surface::VIEWType convertToPresentationType (::fwData::Material::RepresentationType representationMode)
Convert a surface representation mode (FW4SPL) into recommended presentation type (DICOM).
static FWGDCMIO_API::fwData::Material::RepresentationType convertToRepresentationMode (::gdcm::Surface::VIEWType presentationType)
Convert a surface recommended presentation type (DICOM) into representation mode (FW4SPL).
static FWGDCMIO_API const char * convertToPresentationTypeString (::fwData::Material::RepresentationType representationMode)
Convert a representation mode into a DICOM form (eg : SURFACE, POINTS, WIREFRAME).
static FWGDCMIO_API int convertPointToFrameNumber (const ::fwData::Image::csptr &image, const ::fwData::Point::sptr &point) throw (::fwGdcmIO::exception::Failed)
static FWGDCMIO_API double convertFrameNumberToZCoordinate (const ::fwData::Image::csptr &image, int frameNumber) throw (::fwGdcmIO::exception::Failed)
Detailed Description
This class contains helpers to handle GDCM data. It implements many tag value getters/setters. It defines also some tools for converting GDCM data to FW4SPL data.
Definition at line 41 of file DicomData.hpp.
Member Function Documentation
gdcm::Surface::VIEWType fwGdcmIO::helper::DicomData::convertToPresentationType (::fwData::Material::RepresentationType representationMode) static
Convert a surface representation mode (FW4SPL) into recommended presentation type (DICOM).
See also
Recommended Presentation Type Tag (0066,000d).
Parameters
[in] representationMode Surface representation mode.
Returns
Corresponding recommended presentation type.
Definition at line 148 of file DicomData.cpp.
References SLM_WARN.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceMeshModule().
const char * fwGdcmIO::helper::DicomData::convertToPresentationTypeString (::fwData::Material::RepresentationType representationMode) static
Convert a representation mode into a DICOM form (eg : SURFACE, POINTS, WIREFRAME).
See also
DICOM tag (0x0066,0x000d).
Parameters
[in] representationMode Reconstruction's material representation mode (eg : SURFACE, POINT, ...).
Definition at line 192 of file DicomData.cpp.
References SLM_WARN.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceMeshModule().
fwData::Material::RepresentationType fwGdcmIO::helper::DicomData::convertToRepresentationMode (::gdcm::Surface::VIEWType presentationType) static
Convert a surface recommended presentation type (DICOM) into representation mode (FW4SPL).
Parameters
[in] presentationType Surface recommended presentation type.
Returns
Corresponding representation mode
Definition at line 170 of file DicomData.cpp.
References SLM_WARN.
Referenced by fwGdcmIO::reader::ie::Surface::readSurfaceMeshModule().
const gdcm::PhotometricInterpretation fwGdcmIO::helper::DicomData::getPhotometricInterpretation (const ::fwData::Image & image) static
Return the photometric interpretation of an acquisition.
Parameters
[in] image Image
Returns
The photometric interpretation (e.g: MONOCHROME2, RGB, ...)
Definition at line 120 of file DicomData.cpp.
References SLM_ERROR.
Referenced by fwGdcmIO::writer::ie::Image::writeImagePixelModule().
const ::fwTools::Type fwGdcmIO::helper::DicomData::getPixelType (const ::gdcm::PixelFormat & pixelFormat) static
Return the pixel type from a gdcm pixel format.
Parameters
[in] pixelFormat Pixel format in gdcm.
Returns
The dynamic type of pixels (e.g: char, unsigned int, ...)
Definition at line 88 of file DicomData.cpp.
References SLM_ASSERT.
Referenced by fwGdcmIO::reader::ie::Image::readImageBuffer(), fwGdcmIO::reader::ie::Image::readImagePixelModule(), and fwGdcmIO::writer::ie::Image::writeImagePixelModule().
const ::fwTools::Type fwGdcmIO::helper::DicomData::getPixelType (const ::gdcm::Image & image) static
Return the pixel type of a gdcm Image.
Parameters
[in] image GDCM image
Returns
The dynamic type of pixels (e.g: char, unsigned int, ...)
Definition at line 98 of file DicomData.cpp.
References SLM_ASSERT.
const gdcm::PixelFormat fwGdcmIO::helper::DicomData::getPixelType (const ::fwData::Image::csptr image) static
Return the pixel type of a fwData Image.
Parameters
[in] image Image of fwData
Returns
The pixel format (e.g: INT8, UINT16, ...)
Definition at line 109 of file DicomData.cpp.
References SLM_ASSERT.
template<uint16_t GROUP, uint16_t ELEMENT> static const std::string fwGdcmIO::helper::DicomData::getTagValue (const ::gdcm::DataSet & dataset) inline static
Return a string from a tag found in dataset. An empty string returned means the tag is not found or empty. The value is returned without binary space padding.
Parameters
[in] dataset Data set of tags
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Returns
The tag value
Definition at line 55 of file DicomData.hpp.
template<uint16_t GROUP, uint16_t ELEMENT, typename T > static const T fwGdcmIO::helper::DicomData::getTagValue (const ::gdcm::DataSet & dataset) inline static
Return a value from a tag found in dataset.
Parameters
[in] dataset Data set of tags.
Template Parameters
GROUP Group of the tag.
ELEMENT Element of the tag.
T Type of value.
Returns
The tag value.
Definition at line 95 of file DicomData.hpp.
template<uint16_t GROUP, uint16_t ELEMENT> static const std::string fwGdcmIO::helper::DicomData::getTrimmedTagValue (const ::gdcm::DataSet & dataset) inline static
Return a trimmed string from a tag found in dataset.
Parameters
[in] dataset Data set of tags
Returns
The trimmed tag value
Definition at line 79 of file DicomData.hpp.
template<uint16_t GROUP, uint16_t ELEMENT> static void fwGdcmIO::helper::DicomData::insertSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, ::gdcm::DataSet & dataset) inline static
Insert a sequence of items with a tag in the data set specified. If the tag already exists, items of the old and new sequences are added in a new one.
Parameters
[in] sequence Sequence of items to insert
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 195 of file DicomData.hpp.
void fwGdcmIO::helper::DicomData::setSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, const ::gdcm::Tag & tag, ::gdcm::DataSet & dataset) static
Set and insert a sequence of items with a tag in the data set specified.
Parameters
[in] sequence Sequence of items to insert
[in] tag Tag of the sequence
[in] dataset Data set
Definition at line 70 of file DicomData.cpp.
template<uint16_t GROUP, uint16_t ELEMENT> static void fwGdcmIO::helper::DicomData::setSQ (::gdcm::SmartPointer< ::gdcm::SequenceOfItems > sequence, ::gdcm::DataSet & dataset) inline static
Set and insert a sequence of items with a tag in the data set specified.
Parameters
[in] sequence Sequence of items to insert
[in] dataset Data set
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 172 of file DicomData.hpp.
template<uint16_t GROUP, uint16_t ELEMENT> static void fwGdcmIO::helper::DicomData::setTagValue (const std::string & value, ::gdcm::DataSet & dataset) inline static
Insert a string of character in a tag of a data set.
Parameters
[in] value Value to set
[in] dataset Data set of tags
Template Parameters
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 110 of file DicomData.hpp.
template<typename T , uint16_t GROUP, uint16_t ELEMENT> static void fwGdcmIO::helper::DicomData::setTagValue (const T & value, ::gdcm::DataSet & dataset) inline static
Insert the value of a tag in a data set.
Parameters
[in] value Value to set
[in] dataset Data set of tags
Template Parameters
T Type of value
GROUP Group of the tag
ELEMENT Element of the tag
Definition at line 128 of file DicomData.hpp.
template<typename T , uint16_t GROUP, uint16_t ELEMENT> static void fwGdcmIO::helper::DicomData::setTagValues (const T * array, const unsigned int size, ::gdcm::DataSet & dataset) inline static
Insert multiple values of a tag in a data set.
Parameters
[in] array An Array.
[in] size Size of the array.
[in] dataset Data set of tags.
Template Parameters
T Type of pointer.
GROUP Group of the tag.
ELEMENT Element of the tag.
Definition at line 145 of file DicomData.hpp.
template<typename T > static bool fwGdcmIO::helper::DicomData::valueOf (const std::string & str, T & obj) inline static
Return the pixel type of a gdcm Image.
Parameters
[in] str String to convert
[in] obj The content of the string converted in T type.
Returns
return true if the conversion worked.
Definition at line 225 of file DicomData.hpp.
The documentation for this class was generated from the following files:
DicomData.hpp
DicomData.cpp