fw4spl: fwGdcmIO::helper::DicomDataTools Class Reference
fwGdcmIO::helper::DicomDataTools Class Reference
This class contains helpers to handle GDCM data. It implements many tag value getters/setters. It defines also some tools for converting GDCM data to FW4SPL data.
#include <DicomDataTools.hpp>
Static Public Member Functions
static FWGDCMIO_APIconst::gdcm::PixelFormat getPixelType (const ::fwData::Image::csptr &image)
Return the pixel type of a fwData Image.
static FWGDCMIO_APIconst::gdcm::PhotometricInterpretation getPhotometricInterpretation (const ::fwData::Image::csptr &image)
Return the photometric interpretation of an acquisition.
static FWGDCMIO_API::gdcm::Surface::VIEWType convertToPresentationType (::fwData::Material::RepresentationType representationMode)
Convert a surface representation mode (FW4SPL) into recommended presentation type (DICOM).
static FWGDCMIO_API::fwData::Material::RepresentationType convertToRepresentationMode (::gdcm::Surface::VIEWType presentationType)
Convert a surface recommended presentation type (DICOM) into representation mode (FW4SPL).
static FWGDCMIO_API std::size_t convertPointToFrameNumber (const ::fwData::Image::csptr &image, const ::fwData::Point::csptr &point) throw (::fwGdcmIO::exception::Failed)
Convert a 3D point to the closest frame number index.
static FWGDCMIO_API double convertFrameNumberToZCoordinate (const ::fwData::Image::csptr &image, const std::size_t frameNumber) throw (::fwGdcmIO::exception::Failed)
Convert a frame number to a Z coordinate.
Detailed Description
This class contains helpers to handle GDCM data. It implements many tag value getters/setters. It defines also some tools for converting GDCM data to FW4SPL data.
Definition at line 31 of file DicomDataTools.hpp.
Member Function Documentation
double fwGdcmIO::helper::DicomDataTools::convertFrameNumberToZCoordinate (const ::fwData::Image::csptr & image, const std::size_t frameNumber) throw (::fwGdcmIO::exception::Failed) static
Convert a frame number to a Z coordinate.
Parameters
[in] image Image containing the point
[in] frameNumber Frame number
Definition at line 152 of file DicomDataTools.cpp.
Referenced by fwGdcmIO::reader::ie::SpatialFiducials::readLandmark(), fwGdcmIO::reader::tid::Fiducial::readNode(), and fwGdcmIO::reader::tid::Measurement::readNode().
std::size_t fwGdcmIO::helper::DicomDataTools::convertPointToFrameNumber (const ::fwData::Image::csptr & image, const ::fwData::Point::csptr & point) throw (::fwGdcmIO::exception::Failed) static
Convert a 3D point to the closest frame number index.
Parameters
[in] image Image containing the point
[in] point 3D point
Definition at line 129 of file DicomDataTools.cpp.
Referenced by fwGdcmIO::helper::Fiducial::contains3DDistances(), fwGdcmIO::writer::tid::Fiducial::createFiducial(), fwGdcmIO::writer::tid::Measurement::createMeasurement(), and fwGdcmIO::writer::ie::SpatialFiducials::writeLandmarks().
gdcm::Surface::VIEWType fwGdcmIO::helper::DicomDataTools::convertToPresentationType (::fwData::Material::RepresentationType representationMode) static
Convert a surface representation mode (FW4SPL) into recommended presentation type (DICOM).
See also
Recommended Presentation Type Tag (0066,000d).
Parameters
[in] representationMode Surface representation mode.
Returns
Corresponding recommended presentation type.
Definition at line 85 of file DicomDataTools.cpp.
References SLM_WARN.
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceSequence().
fwData::Material::RepresentationType fwGdcmIO::helper::DicomDataTools::convertToRepresentationMode (::gdcm::Surface::VIEWType presentationType) static
Convert a surface recommended presentation type (DICOM) into representation mode (FW4SPL).
Parameters
[in] presentationType Surface recommended presentation type.
Returns
Corresponding representation mode
Definition at line 107 of file DicomDataTools.cpp.
References SLM_WARN.
Referenced by fwGdcmIO::reader::ie::Surface::readSurfaceMeshModule().
const ::gdcm::PhotometricInterpretation fwGdcmIO::helper::DicomDataTools::getPhotometricInterpretation (const ::fwData::Image::csptr & image) static
Return the photometric interpretation of an acquisition.
Parameters
[in] image Image
Returns
The photometric interpretation (e.g: MONOCHROME2, RGB, ...)
Definition at line 57 of file DicomDataTools.cpp.
References SLM_ERROR.
Referenced by fwGdcmIO::writer::ie::Image::writeImagePixelModule().
const ::gdcm::PixelFormat fwGdcmIO::helper::DicomDataTools::getPixelType (const ::fwData::Image::csptr & image) static
Return the pixel type of a fwData Image.
Parameters
[in] image Image of fwData
Returns
The pixel format (e.g: INT8, UINT16, ...)
Definition at line 44 of file DicomDataTools.cpp.
Referenced by fwGdcmIO::reader::ie::Image::readImageBuffer(), fwGdcmIO::reader::ie::Image::readImagePixelModule(), and fwGdcmIO::writer::ie::Image::writeImagePixelModule().
The documentation for this class was generated from the following files:
DicomDataTools.hpp
DicomDataTools.cpp