fw4spl: guiQt::editor::Code Class Reference
guiQt::editor::Code Class Reference
Code Editor working on a fwData::String.
#include <Code.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((Code)(::gui::editor::IEditor))
GUIQT_API Code () throw ()
Constructor. Do nothing.
virtual GUIQT_API ~Code () throw ()
Destructor. Do nothing.
Protected Slots
void onModifyValue ()
This method is called when the value change.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Install the layout.
virtual void stopping () throw (::fwTools::Failed)
Destroy the layout.
virtual void receiving (::boost::shared_ptr< const fwServices::ObjectMsg > _msg) throw (::fwTools::Failed)
Management of observations (overrides). Update the value from the String object.
virtual void updating () throw (::fwTools::Failed)
Update the value from the String object.
virtual void swapping () throw (::fwTools::Failed)
Update the value from the String object.
virtual void configuring () throw (fwTools::Failed)
Do nothing.
virtual void info (std::ostream &_sstream)
Overrides.
Static Protected Attributes
static const std::string PYTHON = "Python"
static const std::string CPP = "Cpp"
Detailed Description
Code Editor working on a fwData::String.
Date:
2010.
Definition at line 34 of file Code.hpp.
Member Function Documentation
void guiQt::editor::Code::onModifyValue () [protected, slot]
This method is called when the value change.
Update the String object value and notify the modification.
Definition at line 155 of file Code.cpp.
References fwData::Object::copy(), fwServices::IEditionService::notify(), OSLM_TRACE, and fwComEd::StringMsg::VALUE_IS_MODIFIED.
Referenced by starting(), and stopping().
The documentation for this class was generated from the following files:
Code.hpp
Code.cpp