fw4spl: uiMeasurement::action::FocusLandmark Class Reference
uiMeasurement::action::FocusLandmark Class Reference
This action moves the image slice on chosen landmark.
#include <FocusLandmark.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((FocusLandmark)(::fwGui::IActionSrv))
Protected Member Functions
UIMEASUREMENT_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
UIMEASUREMENT_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
UIMEASUREMENT_API void receiving (fwServices::ObjectMsg::csptr _pMsg) throw (::fwTools::Failed)
UIMEASUREMENT_API void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
UIMEASUREMENT_API void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
UIMEASUREMENT_API void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
This action moves the image slice on chosen landmark.
Date:
2010.
Definition at line 25 of file FocusLandmark.hpp.
Member Function Documentation
void uiMeasurement::action::FocusLandmark::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 63 of file FocusLandmark.cpp.
References fwGui::IActionSrv::initialize().
void uiMeasurement::action::FocusLandmark::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 78 of file FocusLandmark.cpp.
void uiMeasurement::action::FocusLandmark::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 49 of file FocusLandmark.cpp.
References fwGui::IActionSrv::actionServiceStarting().
void uiMeasurement::action::FocusLandmark::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 56 of file FocusLandmark.cpp.
References fwGui::IActionSrv::actionServiceStopping().
void uiMeasurement::action::FocusLandmark::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 85 of file FocusLandmark.cpp.
References fwGui::dialog::MessageDialog::addButton(), fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwComEd::Dictionary::m_axialSliceIndexId, fwComEd::Dictionary::m_frontalSliceIndexId, fwComEd::Dictionary::m_imageLandmarksId, fwComEd::Dictionary::m_labelId, fwComEd::Dictionary::m_sagittalSliceIndexId, fwServices::IEditionService::notify(), OSLM_DEBUG, fwGui::dialog::MessageDialog::setIcon(), fwGui::dialog::MessageDialog::setMessage(), fwGui::dialog::MessageDialog::setTitle(), fwGui::dialog::MessageDialog::show(), fwGui::dialog::MessageDialog::showMessageDialog(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
FocusLandmark.hpp
FocusLandmark.cpp