fw4spl: uiMeasurement::action::RemoveDistance Class Reference
uiMeasurement::action::RemoveDistance Class Reference
This action removes distances.
#include <RemoveDistance.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((RemoveDistance)(::fwGui::IActionSrv))
Protected Member Functions
void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
void starting () throw (::fwTools::Failed)
Initialize the service activity.
void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
UIMEASUREMENT_API void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
This action removes distances.
Date:
2010.
Definition at line 29 of file RemoveDistance.hpp.
Member Function Documentation
void uiMeasurement::action::RemoveDistance::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 178 of file RemoveDistance.cpp.
References fwGui::IActionSrv::initialize().
void uiMeasurement::action::RemoveDistance::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 50 of file RemoveDistance.cpp.
void uiMeasurement::action::RemoveDistance::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 192 of file RemoveDistance.cpp.
void uiMeasurement::action::RemoveDistance::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 185 of file RemoveDistance.cpp.
References fwGui::IActionSrv::actionServiceStarting().
void uiMeasurement::action::RemoveDistance::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 197 of file RemoveDistance.cpp.
References fwGui::IActionSrv::actionServiceStopping().
void uiMeasurement::action::RemoveDistance::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 143 of file RemoveDistance.cpp.
References fwComEd::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwComEd::Dictionary::m_imageDistancesId, and SLM_ASSERT.
The documentation for this class was generated from the following files:
RemoveDistance.hpp
RemoveDistance.cpp