fw4spl: vtkSimpleNegato::RendererService Class Reference
vtkSimpleNegato::RendererService Class Reference
Renderer service.
#include <RendererService.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((RendererService)(::fwRender::IRender))
VTKSIMPLENEGATO_API RendererService () throw ()
Constructor.
virtual VTKSIMPLENEGATO_API ~RendererService () throw ()
Destructor.
Protected Member Functions
virtual VTKSIMPLENEGATO_API void starting () throw (fwTools::Failed)
Starting method.
virtual VTKSIMPLENEGATO_API void stopping () throw (fwTools::Failed)
Stopping method.
virtual VTKSIMPLENEGATO_API void updating () throw (fwTools::Failed)
Updating method.
virtual VTKSIMPLENEGATO_API void configuring () throw (::fwTools::Failed)
Configuring method.
virtual VTKSIMPLENEGATO_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Receiving method (react on data modifications).
Protected Attributes
vtkRenderer * m_render
vtk renderer
Detailed Description
Renderer service.
Date:
2009.
Service rendering a fwData::Image using VTK.
Service registered details :
fwServicesRegisterMacro(::fwRender::IRender , ::vtkSimpleNegato::RendererService , ::fwData::Image)
Definition at line 35 of file vtkSimpleNegato/include/vtkSimpleNegato/RendererService.hpp.
Member Function Documentation
void vtkSimpleNegato::RendererService::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method.
This method is used to configure the service.
Implements fwServices::IService.
Definition at line 56 of file vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp.
References fwGui::IGuiContainerSrv::initialize(), and SLM_TRACE_FUNC.
void vtkSimpleNegato::RendererService::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Receiving method (react on data modifications).
Parameters:
[in] _msg ::fwServices::ObjectMsg::csptr
This method is used to update the service.
Reimplemented from fwServices::IService.
Definition at line 115 of file vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp.
References fwComEd::ImageMsg::BUFFER, and fwComEd::ImageMsg::NEW_IMAGE.
void vtkSimpleNegato::RendererService::starting () throw (fwTools::Failed) [protected, virtual]
Starting method.
This method is used to initialize the service. Initialize VTK renderer and gui containers
Implements fwServices::IService.
Definition at line 64 of file vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp.
References fwGui::IGuiContainerSrv::create(), and m_render.
void vtkSimpleNegato::RendererService::stopping () throw (fwTools::Failed) [protected, virtual]
Stopping method.
Destroy VTK renderer and gui containers
Implements fwServices::IService.
Definition at line 81 of file vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp.
References fwGui::IGuiContainerSrv::destroy(), m_render, and SLM_ASSERT.
void vtkSimpleNegato::RendererService::updating () throw (fwTools::Failed) [protected, virtual]
Updating method.
This method is used to update the service. Make a render if necessary
Implements fwServices::IService.
Definition at line 106 of file vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp.
The documentation for this class was generated from the following files:
vtkSimpleNegato/include/vtkSimpleNegato/RendererService.hpp
vtkSimpleNegato/src/vtkSimpleNegato/RendererService.cpp