fw4spl: uiMeasurement::action::ShowDistance Class Reference
uiMeasurement::action::ShowDistance Class Reference
This action allows to show/hide image distances.
#include <ShowDistance.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
virtual UIMEASUREMENT_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
virtual UIMEASUREMENT_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Member Functions inherited from fwGui::IActionSrv
FWGUI_API void actionServiceStopping ()
Method called when the action service is stopping.
FWGUI_API void actionServiceStarting ()
Method called when the action service is starting.
virtual FWGUI_API void setIsActive (bool isActive)
Set the action service is active/inactive.
virtual FWGUI_API void activate ()
Set the action service is active.
virtual FWGUI_API void deactivate ()
Set the action service is not active.
FWGUI_API bool getIsActive ()
Return true if action service is active.
bool getActiveStateValue ()
Return true if action 'check' feedback is inverted.
virtual FWGUI_API void setIsExecutable (bool isExecutable)
Set the action service executable or not.
virtual FWGUI_API void setExecutable ()
Set the action service executable.
virtual FWGUI_API void setInexecutable ()
Set the action service not executable.
FWGUI_API bool getIsExecutable ()
Return action service is executable.
FWGUI_API void setVisible (bool isVisible)
Show or hide the action.
FWGUI_API void show ()
Show the action.
FWGUI_API void hide ()
Hide the action.
FWGUI_API bool isVisible ()
FWGUI_API bool confirmAction ()
Confirm that the action must be executed.
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const throw ()
Return the global process status.
FWSERVICES_API bool isStarted () const throw ()
Test if the service is started or not.
FWSERVICES_API bool isStopped () const throw ()
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const throw ()
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const throw ()
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const OutputMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::IActionSrv
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static FWSERVICES_API void setVersion (int version)
static FWSERVICES_API bool isVersion2 ()
Streaming a service.
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
void starting () throw (::fwTools::Failed)
Initialize the service activity.
void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
void info (std::ostream &_sstream)
Write information in a stream.
Protected Member Functions inherited from fwGui::IActionSrv
FWGUI_API void initialize ()
Initialize the action.
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual void swapping (const KeyType &key) throw (::fwTools::Failed)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void reconfiguring () throw (::fwTools::Failed)
Reconfigure the service activity when is started.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwGui::IActionSrv
typedef ::fwCom::Slot< void(bool) > SetVisibleSlotType
Slot to show/hide the action.
typedef ::fwCom::Slot< void() > ShowSlotType
Slot to disable the action.
typedef ::fwCom::Slot< void() > HideSlotType
Slot to disable the action.
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef ::boost::shared_future< void > SharedFutureType
Slot to call start method.
typedef ::boost::packaged_task< void > PackagedTaskType
Slot to call start method.
typedef ::boost::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Static Public Attributes inherited from fwGui::IActionSrv
static const ::fwCom::Slots::SlotKeyType s_SET_VISIBLE_SLOT = "setVisible"
static const ::fwCom::Slots::SlotKeyType s_SHOW_SLOT = "show"
static const ::fwCom::Slots::SlotKeyType s_HIDE_SLOT = "hide"
static const ::fwCom::Slots::SlotKeyType s_SET_IS_ACTIVE_SLOT = "setIsActive"
Slot to activate/deactivate the action.
static const ::fwCom::Slots::SlotKeyType s_ACTIVATE_SLOT = "activate"
Slot to activate the action.
static const ::fwCom::Slots::SlotKeyType s_DEACTIVATE_SLOT = "deactivate"
Slot to desactivate the action.
static const ::fwCom::Slots::SlotKeyType s_SET_IS_EXECUTABLE_SLOT = "setIsExecutable"
Slot to enable/disable the action.
static const ::fwCom::Slots::SlotKeyType s_SET_EXECUTABLE_SLOT = "setExecutable"
Slot to enable the action.
static const ::fwCom::Slots::SlotKeyType s_SET_INEXECUTABLE_SLOT = "setInexecutable"
Slot to disable the action.
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Types inherited from fwGui::IActionSrv
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Detailed Description
This action allows to show/hide image distances.
Definition at line 22 of file ShowDistance.hpp.
Member Function Documentation
void uiMeasurement::action::ShowDistance::configuring () throw (::fwTools::Failed) protected virtual
Configure the service before starting. Apply the configuration to service.
See also
configure()
Implements fwServices::IService.
Definition at line 113 of file ShowDistance.cpp.
References fwGui::IActionSrv::initialize().
fwServices::IService::KeyConnectionsMap uiMeasurement::action::ShowDistance::getAutoConnections () const virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Image::s_DISTANCE_DISPLAYED_SIG to this::s_SHOW_DISTANCE_SLOT
Reimplemented from fwServices::IService.
Definition at line 144 of file ShowDistance.cpp.
References fwData::Image::s_DISTANCE_DISPLAYED_SIG.
fwServices::IService::KeyConnectionsType uiMeasurement::action::ShowDistance::getObjSrvConnections () const virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Image::s_DISTANCE_DISPLAYED_SIG to this::s_SHOW_DISTANCE_SLOT
Reimplemented from fwServices::IService.
Definition at line 134 of file ShowDistance.cpp.
References fwData::Image::s_DISTANCE_DISPLAYED_SIG.
void uiMeasurement::action::ShowDistance::info (std::ostream & _sstream) protected virtual
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 52 of file ShowDistance.cpp.
void uiMeasurement::action::ShowDistance::starting () throw (::fwTools::Failed) protected virtual
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also
start()
Implements fwServices::IService.
Definition at line 120 of file ShowDistance.cpp.
References fwGui::IActionSrv::actionServiceStarting().
void uiMeasurement::action::ShowDistance::stopping () throw (::fwTools::Failed) protected virtual
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also
stop()
Implements fwServices::IService.
Definition at line 127 of file ShowDistance.cpp.
References fwGui::IActionSrv::actionServiceStopping().
void uiMeasurement::action::ShowDistance::swapping () throw (::fwTools::Failed) protected virtual
Swap the service from associated object to another object.
See also
swap()
Deprecated:
use swapping(const KeyType& key) instead
Reimplemented from fwServices::IService.
Definition at line 91 of file ShowDistance.cpp.
References fwGui::IActionSrv::setIsActive().
void uiMeasurement::action::ShowDistance::updating () throw (::fwTools::Failed) protected virtual
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also
update()
Implements fwServices::IService.
Definition at line 59 of file ShowDistance.cpp.
References fwDataTools::fieldHelper::MedicalImageHelpers::checkImageValidity(), fwData::Image::s_DISTANCE_DISPLAYED_SIG, fwGui::IActionSrv::setIsActive(), SLM_TRACE_FUNC, and fwData::GenericField< T >::value().
The documentation for this class was generated from the following files:
ShowDistance.hpp
ShowDistance.cpp