fw4spl: fwRenderQt::IAdaptor Class Reference
fwRenderQt::IAdaptor Class Reference
Root class for all scene2d adaptors.
#include <IAdaptor.hpp>
Public Types
typedef std::pair< double, double > Point2DType
Point2D coordinate <X, Y>
typedef std::pair< float, float > ViewSizeRatio
<width, height>
typedef std::pair< float, float > ViewportSizeRatio
<width, height>
typedef std::pair< float, float > Scene2DRatio
<width, height>
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Public Member Functions
virtual bool isA (const std::string &type) const override
FWRENDERQT_API void setZValue (float _zValue)
Set the zValue.
FWRENDERQT_API float getZValue () const
Get the zValue.
FWRENDERQT_API std::shared_ptr< ::fwRenderQt::SRender > getScene2DRender () const
Get the render that manages the IAdaptor.
virtual FWRENDERQT_API void processInteraction (::fwRenderQt::data::Event &_event)
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Member Functions
FWRENDERQT_API IAdaptor () noexcept
Constructor, set the zValue to 0.
virtual FWRENDERQT_API ~IAdaptor () noexcept
Basic destructor, do nothing.
FWRENDERQT_API void configureParams ()
Parse the xml configuration for Axis, z value and opacity.
FWRENDERQT_API Point2DType mapAdaptorToScene (const Point2DType &_xy, const ::fwRenderQt::data::Axis::sptr &_xAxis, const ::fwRenderQt::data::Axis::sptr &_yAxis) const
FWRENDERQT_API Point2DType mapSceneToAdaptor (const Point2DType &_xy, const ::fwRenderQt::data::Axis::sptr &_xAxis, const ::fwRenderQt::data::Axis::sptr &_yAxis) const
FWRENDERQT_API ViewSizeRatio getViewSizeRatio () const
Return the ratio between view's initial size and its current size.
FWRENDERQT_API ViewportSizeRatio getViewportSizeRatio () const
Return the ratio between viewport's initial size and its current size.
FWRENDERQT_API void initializeViewSize ()
Initialize the source values used for computing view's size ratio.
FWRENDERQT_API void initializeViewportSize ()
Initialize the source values used for computing viewport's size ratio.
FWRENDERQT_API Scene2DRatio getRatio () const
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual FWSERVICES_API void starting ()=0
Initialize the service activity.
virtual FWSERVICES_API void stopping ()=0
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual void swapping ()
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void configuring ()=0
Configure the service before starting. Apply the configuration to service.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API void updating ()=0
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
virtual FWSERVICES_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated objects signals, this method is used for obj/srv auto connection.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
::fwRenderQt::data::Axis::sptr m_xAxis
The x Axis.
::fwRenderQt::data::Axis::sptr m_yAxis
The y Axis.
float m_zValue
float m_opacity
Opacity of the adaptor. Default value set to 1 (opaque).
ViewSizeRatio m_viewInitialSize
ViewportSizeRatio m_viewportInitialSize
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
Root class for all scene2d adaptors.
Definition at line 23 of file fwRenderQt/include/fwRenderQt/IAdaptor.hpp.
Member Function Documentation
void fwRenderQt::IAdaptor::configureParams () protected
Parse the xml configuration for Axis, z value and opacity.
 <config xAxis="x" yAxis="y" zValue="1" opacity="1.0" />
xAxis (optional): x axis associated to the adaptor
yAxis (optional): y axis associated to the adaptor
zValue (optional, default=0): z value of the layer
opacity (optional, default=1.0): adaptor opacity (float)
Definition at line 170 of file fwRenderQt/src/fwRenderQt/IAdaptor.cpp.
References fwServices::IService::getConfigTree(), getScene2DRender(), m_opacity, m_viewInitialSize, m_viewportInitialSize, m_xAxis, m_yAxis, m_zValue, and SLM_ASSERT.
Referenced by scene2D::adaptor::SSquare::configuring(), scene2D::adaptor::SViewportUpdater::configuring(), scene2D::adaptor::SLine::configuring(), scene2D::adaptor::SHistogram::configuring(), scene2D::adaptor::SAxis::configuring(), scene2D::adaptor::SHistogramValue::configuring(), scene2D::adaptor::SScaleValues::configuring(), scene2D::adaptor::SHistogramCursor::configuring(), scene2D::adaptor::SViewportRangeSelector::configuring(), scene2D::adaptor::SCurvedHistogram::configuring(), scene2D::adaptor::SGrid2D::configuring(), scene2D::adaptor::STransferFunction::configuring(), and scene2D::adaptor::SNegato::configuring().
IAdaptor::Point2DType fwRenderQt::IAdaptor::mapAdaptorToScene (const Point2DType & _xy, const ::fwRenderQt::data::Axis::sptr & _xAxis, const ::fwRenderQt::data::Axis::sptr & _yAxis) const protected
Get a pair of doubles (a point), two axis, and convert the pair of doubles values from adaptor coordinates to scene coordinates
Definition at line 92 of file fwRenderQt/src/fwRenderQt/IAdaptor.cpp.
Referenced by scene2D::adaptor::SLine::configuring(), scene2D::adaptor::SGrid2D::configuring(), scene2D::adaptor::STransferFunction::configuring(), scene2D::adaptor::SViewportRangeSelector::processInteraction(), scene2D::adaptor::STransferFunction::processInteraction(), scene2D::adaptor::SViewportRangeSelector::starting(), scene2D::adaptor::SCurvedHistogram::starting(), scene2D::adaptor::SViewportRangeSelector::updateViewportFromShutter(), scene2D::adaptor::SViewportUpdater::updating(), scene2D::adaptor::SHistogram::updating(), scene2D::adaptor::SAxis::updating(), scene2D::adaptor::SCurvedHistogram::updating(), and scene2D::adaptor::SScaleValues::updating().
IAdaptor::Point2DType fwRenderQt::IAdaptor::mapSceneToAdaptor (const Point2DType & _xy, const ::fwRenderQt::data::Axis::sptr & _xAxis, const ::fwRenderQt::data::Axis::sptr & _yAxis) const protected
Get a pair of doubles (a point), two axis, and convert the pair of doubles values from scene coordinates to adaptor coordinates
Definition at line 141 of file fwRenderQt/src/fwRenderQt/IAdaptor.cpp.
Referenced by scene2D::adaptor::STransferFunction::processInteraction(), and scene2D::adaptor::SViewportRangeSelector::updateViewportFromShutter().
void fwRenderQt::IAdaptor::processInteraction (::fwRenderQt::data::Event & _event) virtual
Interact with the mouse events catched on the IAdaptor (virtual function, its behavior is only defined in the specific adaptors).
Reimplemented in scene2D::adaptor::SNegato, scene2D::adaptor::STransferFunction, scene2D::adaptor::SGrid2D, scene2D::adaptor::SScaleValues, scene2D::adaptor::SCurvedHistogram, scene2D::adaptor::SHistogramCursor, scene2D::adaptor::SViewportRangeSelector, scene2D::adaptor::SHistogramValue, scene2D::adaptor::SAxis, scene2D::adaptor::SHistogram, scene2D::adaptor::SViewportUpdater, scene2D::adaptor::SSquare, and scene2D::adaptor::SViewportInteractor.
Definition at line 249 of file fwRenderQt/src/fwRenderQt/IAdaptor.cpp.
Member Data Documentation
ViewSizeRatio fwRenderQt::IAdaptor::m_viewInitialSize protected
Initial size of the widget (view). The goal of keeping a reference on the initial size is to avoid unwanted scaling onto some objects (such as transfer function points, histogram cursor, etc) when a resize event is caught.
Definition at line 118 of file fwRenderQt/include/fwRenderQt/IAdaptor.hpp.
Referenced by configureParams(), scene2D::adaptor::STransferFunction::configuring(), getViewSizeRatio(), initializeViewSize(), scene2D::adaptor::STransferFunction::processInteraction(), scene2D::adaptor::SAxis::updating(), scene2D::adaptor::SHistogramValue::updating(), scene2D::adaptor::SHistogramCursor::updating(), and scene2D::adaptor::SScaleValues::updating().
ViewportSizeRatio fwRenderQt::IAdaptor::m_viewportInitialSize protected
Initial size of the viewport. The goal of keeping a reference on the initial size of the viewport is the same as preceding.
Definition at line 122 of file fwRenderQt/include/fwRenderQt/IAdaptor.hpp.
Referenced by configureParams(), getViewportSizeRatio(), and initializeViewportSize().
float fwRenderQt::IAdaptor::m_zValue protected
The adaptor zValue (depth within the scene). The adaptor with the highest zValue is displayed on top of all adaptors.
Definition at line 110 of file fwRenderQt/include/fwRenderQt/IAdaptor.hpp.
Referenced by configureParams(), scene2D::adaptor::SLine::configuring(), scene2D::adaptor::SAxis::configuring(), scene2D::adaptor::SScaleValues::configuring(), scene2D::adaptor::SGrid2D::configuring(), scene2D::adaptor::STransferFunction::configuring(), getZValue(), setZValue(), scene2D::adaptor::SSquare::starting(), scene2D::adaptor::SHistogramValue::starting(), scene2D::adaptor::SHistogramCursor::starting(), scene2D::adaptor::SViewportRangeSelector::starting(), scene2D::adaptor::SNegato::starting(), scene2D::adaptor::SHistogram::updating(), and scene2D::adaptor::SCurvedHistogram::updating().
The documentation for this class was generated from the following files:
fwRenderQt/include/fwRenderQt/IAdaptor.hpp
fwRenderQt/src/fwRenderQt/IAdaptor.cpp