fw4spl: fwGdcmIO::helper::DicomCodedAttribute Class Reference
fwGdcmIO::helper::DicomCodedAttribute Class Reference
Helper class to manage DICOM coded attributes.
#include <DicomCodedAttribute.hpp>
Public Types
typedef std::vector< ::fwGdcmIO::container::DicomCodedAttribute > DicomCodedAttributeVectorType
DicomCodedAttribute container type.
Static Public Member Functions
static FWGDCMIO_API DicomCodedAttributeVectorType convertEntryToCodedAttribute (const std::string &entry)
Convert an entry of the form '(AAA;BBB;CCC)' into a list of DicomCodedAttributes. Several DicomCodedAttributes can be detected in a single entry.
static FWGDCMIO_API::gdcm::Segment::BasicCodedEntryVector convertEntryToGDCMCodedAttribute (const std::string &entry)
Convert an entry of the form '(AAA;BBB;CCC)' into GDCM's BasicCodedEntryVector. Several DicomCodedAttributes can be detected in a single entry.
static FWGDCMIO_API bool checkAndFormatEntry (std::string &entry, bool multipleValue=false)
Retrieve '(AAA;BBB;CCC)' patterns inside of the entry string. Remove spaces or other characters that might be present between matches. If a single value is requested, check the uniqueness of the value.
Detailed Description
Helper class to manage DICOM coded attributes.
Definition at line 24 of file helper/DicomCodedAttribute.hpp.
Member Function Documentation
bool fwGdcmIO::helper::DicomCodedAttribute::checkAndFormatEntry (std::string & entry, bool multipleValue = false) static
Retrieve '(AAA;BBB;CCC)' patterns inside of the entry string. Remove spaces or other characters that might be present between matches. If a single value is requested, check the uniqueness of the value.
Parameters
[in,out] entry Value that shall be verified and formatted
[in] multipleValue If set to 'false', check the uniqueness of the value
Definition at line 62 of file helper/DicomCodedAttribute.cpp.
Referenced by fwGdcmIO::helper::SegmentedPropertyRegistry::SegmentedPropertyRegistry().
DicomCodedAttribute::DicomCodedAttributeVectorType fwGdcmIO::helper::DicomCodedAttribute::convertEntryToCodedAttribute (const std::string & entry) static
Convert an entry of the form '(AAA;BBB;CCC)' into a list of DicomCodedAttributes. Several DicomCodedAttributes can be detected in a single entry.
Parameters
[in] entry Entry containing one or several coded attributes.
Definition at line 19 of file helper/DicomCodedAttribute.cpp.
Referenced by convertEntryToGDCMCodedAttribute().
gdcm::Segment::BasicCodedEntryVector fwGdcmIO::helper::DicomCodedAttribute::convertEntryToGDCMCodedAttribute (const std::string & entry) static
Convert an entry of the form '(AAA;BBB;CCC)' into GDCM's BasicCodedEntryVector. Several DicomCodedAttributes can be detected in a single entry.
Parameters
[in] entry Entry containing one or several coded attributes.
Definition at line 47 of file helper/DicomCodedAttribute.cpp.
References convertEntryToCodedAttribute().
Referenced by fwGdcmIO::writer::ie::Surface::writeSurfaceSegmentationAndSurfaceMeshModules().
The documentation for this class was generated from the following files:
helper/DicomCodedAttribute.hpp
helper/DicomCodedAttribute.cpp