fw4spl: fwComEd::helper::SeriesDB Class Reference
fwComEd::helper::SeriesDB Class Reference
Defines an helper to modify an fwMedData::SeriesDB and create in parallel the message to announce this modification.
#include <SeriesDB.hpp>
Public Member Functions
FWCOMED_API SeriesDB (::fwMedData::SeriesDB::wptr seriesDB)
Constructor. Initialize parameters.
FWCOMED_API ~SeriesDB ()
Destrucotr. Do nothing.
FWCOMED_API void add (::fwMedData::Series::sptr newSeries)
Add a Series in the SeriesDB.
FWCOMED_API void remove (::fwMedData::Series::sptr oldSeries)
Remove a Series in the SeriesDB.
FWCOMED_API void clear ()
Clear all series in the SeriesDB.
FWCOMED_API void merge (::fwMedData::SeriesDB::sptr seriesDBIn)
Merge seriesDBIn all series from seriesDBIn to the SeriesDB.
FWCOMED_API void notify (::fwServices::IService::sptr serviceSource, bool notifySource=false)
Send the message of modification.
Detailed Description
Defines an helper to modify an fwMedData::SeriesDB and create in parallel the message to announce this modification.
Date:
2007-20013.
Definition at line 29 of file core/fwComEd/include/fwComEd/helper/SeriesDB.hpp.
Member Function Documentation
void fwComEd::helper::SeriesDB::add (::fwMedData::Series::sptr newSeries)
Add a Series in the SeriesDB.
Parameters:
[in] newSeries object to add in the SeriesDB
Prepare the message to announce the modification.
Definition at line 34 of file core/fwComEd/src/fwComEd/helper/SeriesDB.cpp.
References OSLM_ASSERT.
Referenced by merge(), uiMedData::editor::SSeries::onExportClicked(), uiMedData::action::SExportSeries::updating(), and uiMedData::action::SInitNewSeries::updating().
void fwComEd::helper::SeriesDB::clear ()
Clear all series in the SeriesDB.
Prepare the message to announce the modification.
Definition at line 67 of file core/fwComEd/src/fwComEd/helper/SeriesDB.cpp.
void fwComEd::helper::SeriesDB::merge (::fwMedData::SeriesDB::sptr seriesDBIn)
Merge seriesDBIn all series from seriesDBIn to the SeriesDB.
Prepare the message to announce the modification.
Definition at line 79 of file core/fwComEd/src/fwComEd/helper/SeriesDB.cpp.
References add().
Referenced by ioITK::SInrSeriesDBReader::updating(), uiIO::action::SSeriesDBMerger::updating(), and ioVTK::SSeriesDBReader::updating().
void fwComEd::helper::SeriesDB::remove (::fwMedData::Series::sptr oldSeries)
Remove a Series in the SeriesDB.
Parameters:
[in] oldSeries object to remove from the SeriesDB.
Prepare the message to announce the modification.
Definition at line 50 of file core/fwComEd/src/fwComEd/helper/SeriesDB.cpp.
References OSLM_ASSERT.
The documentation for this class was generated from the following files:
core/fwComEd/include/fwComEd/helper/SeriesDB.hpp
core/fwComEd/src/fwComEd/helper/SeriesDB.cpp