fw4spl: fwPacsIO::SeriesRetriever Class Reference
fwPacsIO::SeriesRetriever Class Reference
Reads DICOM series from pacs.
#include <SeriesRetriever.hpp>
Public Types
typedef ::fwCom::Slot< void(const std::string &, unsigned int, const std::string &)> ProgressCallbackSlotType
Public Member Functions
virtual bool isA (const std::string &type) const
FWPACSIO_API SeriesRetriever ()
Constructor.
FWPACSIO_API ~SeriesRetriever ()
Destructor.
FWPACSIO_API void initialize (const std::string &applicationTitle, unsigned short applicationport, int timeout=3, ProgressCallbackSlotType::sptr progressCallback=ProgressCallbackSlotType::sptr())
Initialize the connection.
FWPACSIO_API bool start ()
Start the server.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Attributes
static FWPACSIO_APIconst::fwCom::Slots::SlotKeyType s_PROGRESS_CALLBACK_SLOT = "CMoveProgressCallback"
Protected Member Functions
virtual OFCondition handleIncomingCommand (T_DIMSE_Message *incomingMsg, const DcmPresentationContextInfo &presContextInfo)
Handle Incoming Command (Override)
virtual OFCondition handleSTORERequest (T_DIMSE_Message *incomingMsg, T_ASC_PresentationContextID presID)
Handle C-STORE Request.
Protected Attributes
::boost::filesystem::path m_path
Path where the files must be saved.
ProgressCallbackSlotType::sptr m_progressCallback
Progress callback slot.
unsigned int m_instanceIndex
Dowloaded instance index.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Reads DICOM series from pacs.
Definition at line 30 of file SeriesRetriever.hpp.
Member Function Documentation
OFCondition fwPacsIO::SeriesRetriever::handleSTORERequest (T_DIMSE_Message * incomingMsg, T_ASC_PresentationContextID presID) protected virtual
Handle C-STORE Request.
Parameters
[in] incomingMsg Incoming DIMSE message
[in] presID Presentation context ID
Returns
OFTrue on success
Definition at line 109 of file SeriesRetriever.cpp.
References m_instanceIndex, m_path, m_progressCallback, OSLM_TRACE, and SLM_TRACE.
Referenced by handleIncomingCommand().
void fwPacsIO::SeriesRetriever::initialize (const std::string & applicationTitle, unsigned short applicationport, int timeout = 3, ProgressCallbackSlotType::sptr progressCallback = ProgressCallbackSlotType::sptr())
Initialize the connection.
Parameters
[in] applicationTitle Move application title
[in] applicationport Move application port
[in] path Local dicom folder path
[in] timeout Connection timeout
[in] progressCallback Progress callback
Definition at line 42 of file SeriesRetriever.cpp.
References fwTools::System::getTemporaryFolder(), fwDcmtkTools::Dictionary::loadDictionary(), m_path, m_progressCallback, and SLM_ASSERT.
The documentation for this class was generated from the following files:
SeriesRetriever.hpp
SeriesRetriever.cpp