fw4spl: fwThread::WorkerAsio Class Reference
fwThread::WorkerAsio Class Reference
Private implementation of fwThread::Worker using boost::asio.
Public Types
typedef ::boost::asio::io_service IOServiceType
typedef ::boost::asio::io_service::work WorkType
typedef std::shared_ptr< WorkType > WorkPtrType
typedef ::boost::thread ThreadType
Public Types inherited from fwThread::Worker
typedef ::fwCore::HiResClock::HiResClockType PeriodType
typedef ::boost::function< void() > TaskType
typedef ::boost::any ExitReturnType
typedef ::boost::shared_future< ExitReturnType > FutureType
Public Member Functions
void stop ()
Waits for the last task to be processed and stops the loop.
void post (TaskType handler)
Requests invocation of the given task handler and returns immediately.
ThreadIdType getThreadId () const
Returns the worker's thread id.
std::shared_ptr< ::fwThread::Timer > createTimer ()
Creates and returns a fwThread::Timer running in this Worker.
virtual void processTasks ()
Processes all worker pending tasks for the calling thread until there are no more tasks to process. You can call this function occasionally when your program is busy performing a long operation.
virtual void processTasks (PeriodType maxtime)
Processes worker pending tasks for the calling thread for maxtime milliseconds or until there are no more tasks to process. You can call this function occasionally when your program is busy performing a long operation.
Public Member Functions inherited from fwThread::Worker
virtual bool isA (const std::string &type) const
template<typename R , typename CALLABLE >
::boost::shared_future< R > postTask (CALLABLE f)
Requests invocation of the given callable and returns a shared future.
virtual FutureType getFuture ()
Returns a boost::shared_future associated with the execution of Worker's loop.
template<typename R , typename TASK >
::boost::shared_future< R > postTask (TASK f)
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
Public Member Functions inherited from fwCore::BaseObject
Protected Member Functions
WorkerAsio (const WorkerAsio &)
Copy constructor forbidden.
WorkerAsio & operator= (const WorkerAsio &)
Copy operator forbidden.
Protected Member Functions inherited from fwThread::Worker
Worker (const Worker &)
Copy constructor forbidden.
Worker & operator= (const Worker &)
Copy operator forbidden.
Protected Attributes
IOServiceType m_ioService
Class provides functionality to manipulate asynchronous tasks.
WorkPtrType m_work
Class to inform the io_service when it has work to do.
std::shared_ptr< ThreadType > m_thread
Thread created and managed by the worker.
Protected Attributes inherited from fwThread::Worker
FutureType m_future
Worker's loop future.
Additional Inherited Members
Static Public Member Functions inherited from fwThread::Worker
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Protected Member Functions inherited from fwThread::Worker
static FWTHREAD_API std::shared_ptr< Worker > defaultFactory ()
Detailed Description
Private implementation of fwThread::Worker using boost::asio.
Definition at line 32 of file WorkerAsio.cpp.
Member Function Documentation
void fwThread::WorkerAsio::processTasks () virtual
Processes all worker pending tasks for the calling thread until there are no more tasks to process. You can call this function occasionally when your program is busy performing a long operation.
Warning
WxWidgets version is not yet implemented.
Implements fwThread::Worker.
Definition at line 201 of file WorkerAsio.cpp.
void fwThread::WorkerAsio::processTasks (PeriodType maxtime) virtual
Processes worker pending tasks for the calling thread for maxtime milliseconds or until there are no more tasks to process. You can call this function occasionally when your program is busy performing a long operation.
Parameters
maxtime milliseconds to process worker pending tasks.
Warning
Qt implementation processes all Qt and Worker pending events, be careful.
WxWidgets version is not yet implemented.
Implements fwThread::Worker.
Definition at line 206 of file WorkerAsio.cpp.
References fwCore::TimeStamp::modified(), fwCore::TimeStamp::periodExpired(), and fwCore::TimeStamp::setLifePeriod().
The documentation for this class was generated from the following file:
WorkerAsio.cpp