fw4spl: fwRenderVTK::IVtkAdaptorService Class Reference
fwRenderVTK::IVtkAdaptorService Class Reference
Inherits fwServices::IService.
Inherited by visuVTKAdaptor::Axes, visuVTKAdaptor::BoxWidget, visuVTKAdaptor::Camera, visuVTKAdaptor::Camera2, visuVTKAdaptor::Cube, visuVTKAdaptor::Distance, visuVTKAdaptor::Image, visuVTKAdaptor::Image3DCursor, visuVTKAdaptor::ImageLandmarks, visuVTKAdaptor::ImageMultiDistances, visuVTKAdaptor::ImagePickerInteractor, visuVTKAdaptor::ImagesBlend, visuVTKAdaptor::ImageSeries, visuVTKAdaptor::ImageSlice, visuVTKAdaptor::ImageSliceOrientationText, visuVTKAdaptor::ImagesProbeCursor, visuVTKAdaptor::InteractorStyle, visuVTKAdaptor::LabeledPointList, visuVTKAdaptor::Medical3DCamera, visuVTKAdaptor::Mesh, visuVTKAdaptor::MeshesBoxWidget, visuVTKAdaptor::MeshNormals, visuVTKAdaptor::ModelSeries, visuVTKAdaptor::NegatoMPR, visuVTKAdaptor::NegatoOneSlice, visuVTKAdaptor::NegatoSlicingInteractor, visuVTKAdaptor::NegatoWindowingInteractor, visuVTKAdaptor::OrientationMarker, visuVTKAdaptor::PickerInteractor, visuVTKAdaptor::Plane, visuVTKAdaptor::PlaneInteractor, visuVTKAdaptor::PlaneList, visuVTKAdaptor::PlaneSelectionNotifier, visuVTKAdaptor::PlaneSelector, visuVTKAdaptor::Point, visuVTKAdaptor::PointList, visuVTKAdaptor::PointListInteractor, visuVTKAdaptor::ProbeCursor, visuVTKAdaptor::Reconstruction, visuVTKAdaptor::Resection, visuVTKAdaptor::ResectionDB, visuVTKAdaptor::ResetCamera, visuVTKAdaptor::SliceFollowerCamera, visuVTKAdaptor::SlicesCursor, visuVTKAdaptor::Snapshot, visuVTKAdaptor::Text, visuVTKAdaptor::Transform, visuVTKAdaptor::VectorField, visuVTKAdaptor::Video, and visuVTKVRAdaptor::Volume.
Public Types
typedef fwServices::IService SuperClass
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IVtkAdaptorService)(::fwServices::IService))
virtual void show (bool b=true)
To set a representation.
virtual void hide ()
FWRENDERVTK_API void setRenderService (VtkRenderService::sptr service)
FWRENDERVTK_API void setRenderId (VtkRenderService::RendererIdType newID)
FWRENDERVTK_API
VtkRenderService::sptr getRenderService ()
FWRENDERVTK_API
VtkRenderService::RendererIdType getRenderId ()
FWRENDERVTK_API vtkRenderer * getRenderer ()
FWRENDERVTK_API void setPickerId (VtkRenderService::PickerIdType newID)
FWRENDERVTK_API
VtkRenderService::PickerIdType getPickerId ()
FWRENDERVTK_API
vtkAbstractPropPicker * getPicker (std::string pickerId="")
FWRENDERVTK_API void setTransformId (VtkRenderService::VtkObjectIdType newID)
FWRENDERVTK_API
VtkRenderService::VtkObjectIdType getTransformId ()
FWRENDERVTK_API vtkTransform * getTransform ()
FWRENDERVTK_API vtkObject * getVtkObject (VtkRenderService::VtkObjectIdType objectId)
FWRENDERVTK_API
vtkRenderWindowInteractor * getInteractor ()
virtual
FWRENDERVTK_API::fwData::Object::sptr getAssociatedObject (vtkProp *prop, int depth=0)
FWRENDERVTK_API void getAllSubProps (vtkPropCollection *propc, int depth=-1)
FWRENDERVTK_API void setVtkPipelineModified ()
bool getAutoRender () const
Returns true if the service automatically triggers the rendering.
void setAutoRender (bool autoRender)
Sets if the service automatically triggers the rendering.
Protected Types
typedef std::vector
< ::fwRenderVTK::IVtkAdaptorService::wptr > ServiceVector
Protected Member Functions
FWRENDERVTK_API IVtkAdaptorService () throw ()
constructor
virtual FWRENDERVTK_API ~IVtkAdaptorService () throw ()
destructor
virtual FWRENDERVTK_API void doStart ()=0
virtual FWRENDERVTK_API void doStop ()=0
virtual FWRENDERVTK_API void doSwap ()=0
virtual FWRENDERVTK_API void doUpdate ()=0
virtual FWRENDERVTK_API void doReceive (::fwServices::ObjectMsg::csptr msg)=0
ServiceVector & getRegisteredServices ()
FWRENDERVTK_API void registerService (::fwRenderVTK::IVtkAdaptorService::sptr service)
FWRENDERVTK_API void unregisterServices ()
FWRENDERVTK_API void registerProp (vtkProp *prop)
FWRENDERVTK_API void unregisterProps ()
FWRENDERVTK_API void addToRenderer (vtkProp *prop)
FWRENDERVTK_API void addToPicker (vtkProp *prop, std::string pickerId="")
FWRENDERVTK_API void removeFromPicker (vtkProp *prop, std::string pickerId="")
FWRENDERVTK_API void removeAllPropFromRenderer ()
Standard service methods
virtual FWRENDERVTK_API void info (std::ostream &_sstream)
Overrides.
FWRENDERVTK_API void starting () throw (fwTools::Failed)
Initialize the service activity.
FWRENDERVTK_API void stopping () throw (fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
FWRENDERVTK_API void swapping () throw (fwTools::Failed)
Overrides.
FWRENDERVTK_API void updating () throw (fwTools::Failed)
Overrides.
FWRENDERVTK_API void receiving (::fwServices::ObjectMsg::csptr msg) throw (fwTools::Failed)
Overrides.
Static Protected Member Functions
static FWRENDERVTK_API void getProps (vtkPropCollection *propc, vtkProp *prop)
Protected Attributes
::fwServices::ObjectMsg::sptr m_message
double m_comChannelPriority
priority of comChannel observing related object (specified with objectId)
bool m_vtkPipelineModified
state of the pipeline
VtkRenderService::RendererIdType m_rendererId
VtkRenderService::PickerIdType m_pickerId
VtkRenderService::VtkObjectIdType m_transformId
VtkRenderService::wptr m_renderService
::fwServices::helper::SigSlotConnection::sptr m_connections
ServiceVector m_subServices
vtkPropCollection * m_propCollection
bool m_autoRender
Friends
class VtkRenderService
Detailed Description
Definition at line 28 of file IVtkAdaptorService.hpp.
Member Function Documentation
void fwRenderVTK::IVtkAdaptorService::setRenderService (VtkRenderService::sptr service)
Preconditions
Definition at line 99 of file IVtkAdaptorService.cpp.
References fwServices::IService::isStopped(), and SLM_ASSERT.
void fwRenderVTK::IVtkAdaptorService::setVtkPipelineModified ()
set the pipeline modified so a render request can be send. end-user have to call this method when it have modified a vtk structure
Definition at line 117 of file IVtkAdaptorService.cpp.
References m_vtkPipelineModified.
Referenced by visuVTKAdaptor::Mesh::buildPipeline(), visuVTKAdaptor::Transform::doUpdate(), visuVTKAdaptor::Mesh::newActor(), visuVTKAdaptor::Mesh::setActorPropertyToUnclippedMaterial(), visuVTKAdaptor::Reconstruction::setVisibility(), visuVTKAdaptor::Mesh::updateMesh(), and visuVTKAdaptor::Mesh::updateVisibility().
void fwRenderVTK::IVtkAdaptorService::starting () throw (fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Install observation
Implements fwServices::IService.
Reimplemented in visuVTKAdaptor::PointLabel.
Definition at line 51 of file IVtkAdaptorService.cpp.
References fwServices::IService::getObject(), and fwServices::IService::getObjSrvConnections().
void fwRenderVTK::IVtkAdaptorService::stopping () throw (fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Stop observation
Implements fwServices::IService.
Reimplemented in visuVTKAdaptor::PointLabel.
Definition at line 64 of file IVtkAdaptorService.cpp.
The documentation for this class was generated from the following files:
IVtkAdaptorService.hpp
IVtkAdaptorService.cpp