fw4spl: fwCore::Demangler Class Reference
fwCore::Demangler Class Reference
typeid, string or object name demangler.
#include <Demangler.hpp>
Public Member Functions
FWCORE_API std::string getLeafClassname () const
Returns "Object" from "::some::long::namespace::Object".
FWCORE_API std::string getFullClassname () const
Returns "some::long::namespace::Object" from "::some::long::namespace::Object".
FWCORE_API std::string getClassname () const
Like getRootedClassname(), present for backward compatibility.
FWCORE_API std::string getRootedClassname () const
Returns "::some::long::namespace::Object" from "::some::long::namespace::Object".
FWCORE_API std::string getFullNamespace () const
Returns "some::long::namespace" from "::some::long::namespace::Object".
FWCORE_API std::string getRootedNamespace () const
Returns "::some::long::namespace" from "::some::long::namespace::Object".
Constructor/Destructor
FWCORE_API Demangler (const std::type_info &t)
Constructor from a typeinfo object.
FWCORE_API Demangler (const std::string &s)
Constructor from a std::string.
template<typename T >
Demangler (T &s)
Constructor from any type.
virtual FWCORE_API ~Demangler ()
Destructor.
Protected Member Functions
std::string demangle () const
Process the name to demangle and return the same string whatever the OS is.
Protected Attributes
const std::string m_name
Store the name to demangle.
Detailed Description
typeid, string or object name demangler.
getClassname() is an alias for getRootedClassname()
Warning:
getRootedClassname() use on fundamentals types (int, float, ...) will give a bad result (ex: ::int)
Definition at line 28 of file Demangler.hpp.
Constructor & Destructor Documentation
fwCore::Demangler::Demangler (const std::type_info & t)
Constructor from a typeinfo object.
Parameters:
t Typeinfo to demangle
Definition at line 27 of file Demangler.cpp.
fwCore::Demangler::Demangler (const std::string & s)
Constructor from a std::string.
Parameters:
s string to demangle
Definition at line 31 of file Demangler.cpp.
template<typename T > fwCore::Demangler::Demangler (T & s) [inline]
Constructor from any type.
Parameters:
s object which type has to be demangled
Definition at line 56 of file Demangler.hpp.
Member Function Documentation
std::string fwCore::Demangler::demangle () const [protected]
Process the name to demangle and return the same string whatever the OS is.
Returns:
demangled string
Definition at line 93 of file Demangler.cpp.
References m_name.
Referenced by getFullClassname(), getFullNamespace(), getLeafClassname(), and getRootedClassname().
std::string fwCore::Demangler::getClassname () const
Like getRootedClassname(), present for backward compatibility.
Deprecated:
Use getRootedClassname() instead
Returns:
rooted (with leading "::") demangled class name
Definition at line 51 of file Demangler.cpp.
References getRootedClassname().
std::string fwCore::Demangler::getFullClassname () const
Returns "some::long::namespace::Object" from "::some::long::namespace::Object".
Returns:
demangled class name with namespace (without leading "::")
Definition at line 57 of file Demangler.cpp.
References demangle().
std::string fwCore::Demangler::getFullNamespace () const
Returns "some::long::namespace" from "::some::long::namespace::Object".
Returns:
demangled namespace (without leading "::")
Definition at line 72 of file Demangler.cpp.
References demangle().
Referenced by getRootedNamespace().
std::string fwCore::Demangler::getLeafClassname () const
Returns "Object" from "::some::long::namespace::Object".
Returns:
demangled class name only
Definition at line 39 of file Demangler.cpp.
References demangle().
std::string fwCore::Demangler::getRootedClassname () const
Returns "::some::long::namespace::Object" from "::some::long::namespace::Object".
Returns:
rooted (with leading "::") demangled class name
Definition at line 64 of file Demangler.cpp.
References demangle().
Referenced by getClassname().
std::string fwCore::Demangler::getRootedNamespace () const
Returns "::some::long::namespace" from "::some::long::namespace::Object".
Returns:
rooted demangled namespace (with leading "::")
Definition at line 87 of file Demangler.cpp.
References getFullNamespace().
The documentation for this class was generated from the following files:
Demangler.hpp
Demangler.cpp