fw4spl: gui::action::SSlotCaller Class Reference
gui::action::SSlotCaller Class Reference
Run a slot given by HasSlot id and slot key.This action works on a fwData::Object. It does the action specify by the specify config.
#include <SSlotCaller.hpp>
Public Types
typedef
::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef std::string HasSlotIDType
typedef std::pair
< HasSlotIDType,::fwCom::Slots::SlotKeyType > SlotInfoType
typedef std::vector< SlotInfoType > SlotInfoContainerType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SSlotCaller)(::fwGui::IActionSrv))
GUI_API SSlotCaller () throw ()
Constructor. Do nothing.
virtual GUI_API ~SSlotCaller () throw ()
Destructor. Do nothing.
Protected Member Functions
virtual GUI_API void info (std::ostream &_sstream)
This method gives information about the class. Do nothing.
GUI_API void updating () throw (fwTools::Failed)
This method run the specified slots.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Do nothing.
GUI_API void configuring () throw (::fwTools::Failed)
This method is used to configure the service parameters: specifies which slots must be called.
virtual GUI_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual GUI_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
Detailed Description
Run a slot given by HasSlot id and slot key.
This action works on a fwData::Object. It does the action specify by the specify config.
Definition at line 32 of file SSlotCaller.hpp.
Member Function Documentation
void gui::action::SSlotCaller::configuring () throw (::fwTools::Failed) [protected, virtual]
This method is used to configure the service parameters: specifies which slots must be called.
       <service uid="..." type="::fwGui::IActionSrv" impl="::gui::action::SSlotCaller" autoConnect="no">
          <slots>
              <slot>hasSlotsId/slotKey</slot>
          </slots>
       </service>
Implements fwServices::IService.
Definition at line 98 of file SSlotCaller.cpp.
References fwRuntime::ConfigurationElementContainer::findAllConfigurationElement(), fwRuntime::ConfigurationElementContainer::getElements(), fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, OSLM_ASSERT, SLM_ASSERT, and SLM_TRACE_FUNC.
void gui::action::SSlotCaller::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 43 of file SSlotCaller.cpp.
References fwGui::IActionSrv::actionServiceStarting(), and SLM_TRACE_FUNC.
void gui::action::SSlotCaller::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 51 of file SSlotCaller.cpp.
References fwGui::IActionSrv::actionServiceStopping(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
SSlotCaller.hpp
SSlotCaller.cpp