fw4spl: ioData::TransformationMatrix3DWriterService Class Reference
ioData::TransformationMatrix3DWriterService Class Reference
Transformation matrix 3D writer service.
#include <TransformationMatrix3DWriterService.hpp>
Public Types
typedef ::io::IWriter SuperClass
Super class of writer services.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((TransformationMatrix3DWriterService)(::io::IWriter))
virtual IODATA_API::io::IOPathType getIOPathType () const
Return path type managed by the service, here FILE.
Specified writer service methods (override from ::io::IWriter)
virtual IODATA_API void configureWithIHM ()
Configure the matrix path.
virtual IODATA_API std::vector
< std::string > getSupportedExtensions ()
returns (filename) extension
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual IODATA_API void starting () throw (::fwTools::Failed)
Starting method. This method is called by start() from base service (fwServices::IService)
virtual IODATA_API void stopping () throw (::fwTools::Failed)
Stopping method. This method is called by stop() from base service (fwServices::IService)
IODATA_API void updating () throw (::fwTools::Failed)
Updating method. This method is called by update() from base service (fwServices::IService)
void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
React on modifications : default does nothing.
virtual IODATA_API void info (std::ostream &_sstream)
Info method.
Detailed Description
Transformation matrix 3D writer service.
Date:
2009.
Service writing a TransformationMatrix3D object
Use setConfiguration(cfg) and configure() methods to configure the matrix filename.
Use start() to initialize the service.
Use update() to write the transformation matrix.
Use stop() to stop service before to destroy it.
Service registered details :
fwServicesRegisterMacro(::io::IWriter , ::ioData::TransformationMatrix3DWriterService , ::fwData::TransformationMatrix3D)
Definition at line 33 of file TransformationMatrix3DWriterService.hpp.
Member Function Documentation
void ioData::TransformationMatrix3DWriterService::configureWithIHM () [virtual]
Configure the matrix path.
This method is used to find the file path using a file selector.
Implements io::IWriter.
Definition at line 72 of file TransformationMatrix3DWriterService.cpp.
References fwGui::dialog::LocationDialog::addFilter(), io::IWriter::clearLocations(), fwGui::dialog::LocationDialog::saveDefaultLocation(), fwGui::dialog::LocationDialog::setDefaultLocation(), io::IWriter::setFile(), fwGui::dialog::LocationDialog::setOption(), fwGui::dialog::LocationDialog::setTitle(), fwGui::dialog::LocationDialog::show(), and SLM_TRACE_FUNC.
void ioData::TransformationMatrix3DWriterService::info (std::ostream & _sstream) [protected, virtual]
Info method.
This method is used to give informations about the service.
Parameters:
[out] _sstream output stream
Reimplemented from fwServices::IService.
Definition at line 40 of file TransformationMatrix3DWriterService.cpp.
References fwServices::IService::info().
void ioData::TransformationMatrix3DWriterService::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [inline, protected]
React on modifications : default does nothing.
Note:
This method is automaticaly called by update(msg) method from base service (fwServices::IService).
Parameters:
[in] _msg information message for modification
Definition at line 101 of file TransformationMatrix3DWriterService.hpp.
void ioData::TransformationMatrix3DWriterService::starting () throw (::fwTools::Failed) [protected, virtual]
Starting method. This method is called by start() from base service (fwServices::IService)
This method is used to initialize the service. The starting method is empty for this service.
Implements fwServices::IService.
Definition at line 57 of file TransformationMatrix3DWriterService.cpp.
References SLM_TRACE_FUNC.
void ioData::TransformationMatrix3DWriterService::stopping () throw (::fwTools::Failed) [protected, virtual]
Stopping method. This method is called by stop() from base service (fwServices::IService)
The stopping method is empty for this service.
Implements fwServices::IService.
Definition at line 100 of file TransformationMatrix3DWriterService.cpp.
References SLM_TRACE_FUNC.
void ioData::TransformationMatrix3DWriterService::updating () throw (::fwTools::Failed) [protected, virtual]
Updating method. This method is called by update() from base service (fwServices::IService)
This method is used to update the service. The transformation matrix is written with the writer fwDataIO::writer::TransformationMatrix3DWriter. Notify writing.
Implements fwServices::IService.
Definition at line 107 of file TransformationMatrix3DWriterService.cpp.
References io::IWriter::getFile(), fwServices::IService::getObject(), io::IWriter::hasLocationDefined(), fwComEd::TransformationMatrix3DMsg::MATRIX_IS_MODIFIED, fwServices::IEditionService::notify(), SLM_ASSERT, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
TransformationMatrix3DWriterService.hpp
TransformationMatrix3DWriterService.cpp