fw4spl: ctrlSelection::IManagerSrv Class Reference
ctrlSelection::IManagerSrv Class Reference
Base class for manager. A manager starts, stops or swaps services on object contained in a composite when it receives specific message.
#include <IManagerSrv.hpp>
Classes
struct ProxyConnections
Used to register proxy connection in order to properly disconnect it.
Public Types
typedef
::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef std::string ObjectIdType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IManagerSrv)(::fwServices::IService))
CTRLSELECTION_API IManagerSrv ()
IManagerSrv constructor. Do nothing.
virtual CTRLSELECTION_API ~IManagerSrv ()
IManagerSrv destructor. Do nothing.
Protected Types
typedef std::map< ObjectIdType,::fwServices::helper::SigSlotConnection::sptr > ObjectConnectionsMapType
typedef std::vector
< ProxyConnections > ProxyConnectionsVectType
typedef std::map< ObjectIdType,
ProxyConnectionsVectType > ProxyConnectionsMapType
Protected Member Functions
virtual CTRLSELECTION_API void swapping () throw (::fwTools::Failed)
Swaps the service from associated object to another object. Stops and starts this service.
void manageConnections (const std::string &objectId,::fwData::Object::sptr object, ConfigurationType config)
Manages all connections define in config associated to object. Call manageConnection()
void manageConnection (const std::string &objectId,::fwData::Object::sptr object, ConfigurationType config)
Manages a connection define in config associated to object.
void removeConnections (const std::string &objectId)
Disconnects all registred connection for objectId.
void manageProxies (const std::string &objectId,::fwData::Object::sptr object, ConfigurationType config)
Manages all proxies connections define in config associated to object Call manageProxy()
void manageProxy (const std::string &objectId,::fwData::Object::sptr object, ConfigurationType config)
Manages proxy connections define in config associated to object.
void disconnectProxies (const std::string &objectId)
Disconnects all proxies associated to objectId;.
Protected Attributes
ObjectConnectionsMapType m_objectConnections
Registers connection associated to an object. Connections are connected/disconnected when the object is added/removed.
ProxyConnectionsMapType m_proxyCtns
Proxy connection information map : used to properly disconnect proxies.
Detailed Description
Base class for manager. A manager starts, stops or swaps services on object contained in a composite when it receives specific message.
Date:
2007-2009.
Definition at line 25 of file IManagerSrv.hpp.
Member Function Documentation
void ctrlSelection::IManagerSrv::manageConnection (const std::string & objectId, ::fwData::Object::sptr object, ConfigurationType config) [protected]
Manages a connection define in config associated to object.
Parameters:
objectId Id of the object
object Object associated with the id
config configuration for a <connect> tag associated this object
Definition at line 46 of file IManagerSrv.cpp.
References fwServices::IService::getObject(), m_objectConnections, OSLM_ASSERT, and SLM_ASSERT.
Referenced by manageConnections().
void ctrlSelection::IManagerSrv::manageConnections (const std::string & objectId, ::fwData::Object::sptr object, ConfigurationType config) [protected]
Manages all connections define in config associated to object. Call manageConnection()
Parameters:
objectId Id of the object
object Object associated with the id
config configuration for this object
Definition at line 36 of file IManagerSrv.cpp.
References manageConnection().
void ctrlSelection::IManagerSrv::manageProxies (const std::string & objectId, ::fwData::Object::sptr object, ConfigurationType config) [protected]
Manages all proxies connections define in config associated to object Call manageProxy()
Parameters:
objectId Id of the object
object Object associated with the id
config configuration for this object
Definition at line 135 of file IManagerSrv.cpp.
References manageProxy().
void ctrlSelection::IManagerSrv::manageProxy (const std::string & objectId, ::fwData::Object::sptr object, ConfigurationType config) [protected]
Manages proxy connections define in config associated to object.
Parameters:
objectId Id of the object
object Object associated with the id
config configuration for a <proxy> tag associated this object
Definition at line 145 of file IManagerSrv.cpp.
References fwServices::registry::Proxy::getDefault(), fwServices::IService::getObject(), m_proxyCtns, OSLM_ASSERT, and SLM_ASSERT.
Referenced by manageProxies().
The documentation for this class was generated from the following files:
IManagerSrv.hpp
IManagerSrv.cpp