fw4spl: gui::aspect::DefaultToolBarSrv Class Reference
gui::aspect::DefaultToolBarSrv Class Reference
Defines the default toolbar for standard application.
#include <DefaultToolBarSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((DefaultToolBarSrv)(::fwGui::IToolBarSrv))
GUI_API DefaultToolBarSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~DefaultToolBarSrv () throw ()
Destructor. Do nothing.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual GUI_API void starting () throw (::fwTools::Failed)
This method create a new ToolBar in frame.
virtual GUI_API void stopping () throw (::fwTools::Failed)
This method remove the tools situated in the ToolBar.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
This method is used to update services on notification. Do nothing.
virtual GUI_API void updating () throw (::fwTools::Failed)
This method is used to update services. Do nothing.
virtual GUI_API void configuring () throw (::fwTools::Failed)
Configuring method allows to create a toolBar with several actions.
virtual GUI_API void info (std::ostream &_sstream)
This method is used to give information about the service. Do nothing.
Detailed Description
Defines the default toolbar for standard application.
Definition at line 25 of file DefaultToolBarSrv.hpp.
Member Function Documentation
void gui::aspect::DefaultToolBarSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method allows to create a toolBar with several actions.
Example of configuration
       <service uid="toolbar2" type="::fwGui::IToolBarSrv" impl="::gui::aspect::DefaultToolBarSrv" autoConnect="no" >
           <gui>
               <layout>
                   <menuItem name="My item 2" style="radio" icon="Bundles/TutoGui_0-1/icons/system.png"/>
                   <menuItem name="My item 3" style="radio" icon="Bundles/TutoGui_0-1/icons/system.png"/>
                   <separator />
                   <menuItem name="My item A" style="radio" icon="Bundles/TutoGui_0-1/icons/monkey.png"/>
                   <menuItem name="My item B" style="radio" icon="Bundles/TutoGui_0-1/icons/monkey.png"/>
                   <separator />
                   <menu name="My menu" />
                   <separator />
                   <editor />
               </layout>
           </gui>
           <registry>
               <menuItem sid="item2" />
               <menuItem sid="item3" />
               <menuItem sid="item4" />
               <menuItem sid="item5" />
               <menu sid="menu" />
               <editor sid="editor" />
           </registry>
       </service>
<gui> </gui> : (mandatory) describe the interface of the service.
<registry> </registry> : (mandatory) describe the service management.
<menuItem> represents IActionSrv
<menu> represents IMenuSrv
<editor> represents container service (IEditor, IView, ...)
Warning:
The number of item in the gui section must be EQUAL to the registry section.
The order of the item in each section (gui and registry) must be the same.
For example: the item named "My item 2" will be connected with the service which have the sid = "item2".
A toolbar can't have the same service connected on two different buttons.
See also:
fwGui::IToolBarSrv::initialize(), fwGui::layoutManager::IToolBarLayoutManager::initialize()
Implements fwServices::IService.
Definition at line 46 of file DefaultToolBarSrv.cpp.
References fwGui::IToolBarSrv::initialize(), and SLM_TRACE_FUNC.
void gui::aspect::DefaultToolBarSrv::starting () throw (::fwTools::Failed) [protected, virtual]
This method create a new ToolBar in frame.
Create the toolBar
See also:
fwGui::IToolBarSrv::create()
Implements fwServices::IService.
Definition at line 30 of file DefaultToolBarSrv.cpp.
References fwGui::IToolBarSrv::create(), and SLM_TRACE_FUNC.
void gui::aspect::DefaultToolBarSrv::stopping () throw (::fwTools::Failed) [protected, virtual]
This method remove the tools situated in the ToolBar.
See also:
fwGui::IToolBarSrv::destroy()
Implements fwServices::IService.
Definition at line 38 of file DefaultToolBarSrv.cpp.
References fwGui::IToolBarSrv::destroy(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
DefaultToolBarSrv.hpp
DefaultToolBarSrv.cpp