fw4spl: fwGui::dialog::LoggerDialog Class Reference
fwGui::dialog::LoggerDialog Class Reference
ILoggerDialog is used to display a dialog message and a set of logs Use the Delegate design pattern. The specific implementation selection is ensured by fwGuiRegisterMacro. The specific implementation is fwQt libraries.
#include <LoggerDialog.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWGUI_API LoggerDialog ()
Constructor that will instantiate the concrete implementation.
virtual FWGUI_API ~LoggerDialog ()
Destructor.
FWGUI_API LoggerDialog (const std::string &title, const std::string &message, const ::fwLog::Logger::sptr &logger)
virtual FWGUI_API void setTitle (const std::string &title) override
Set the dialog title.
virtual FWGUI_API void setMessage (const std::string &message) override
Set the dialog message.
virtual FWGUI_API void setLogger (const ::fwLog::Logger::sptr &logger) override
Set the dialog logger.
virtual FWGUI_API bool show () override
Show the dialog and return whether the user has selected the Ok or Cancel button.
Public Member Functions inherited from fwGui::dialog::ILoggerDialog
FWGUI_API ILoggerDialog ()
Constructor.
virtual FWGUI_API ~ILoggerDialog ()
Destructor.
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWGUI_API bool showLoggerDialog (const std::string &title, const std::string &message, const ::fwLog::Logger::sptr &logger)
Static Public Member Functions inherited from fwGui::dialog::ILoggerDialog
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Attributes
::fwGui::dialog::ILoggerDialog::sptr m_implementation
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwGui::dialog::ILoggerDialog
typedef std::string FactoryRegistryKeyType
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Static Public Attributes inherited from fwGui::dialog::ILoggerDialog
static FWGUI_API const FactoryRegistryKeyType REGISTRY_KEY = "::fwGui::dialog::LoggerDialog"
This unique key should be used for all factory for specific Selector(qt,wx,...)
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
ILoggerDialog is used to display a dialog message and a set of logs Use the Delegate design pattern. The specific implementation selection is ensured by fwGuiRegisterMacro. The specific implementation is fwQt libraries.
Definition at line 26 of file include/fwGui/dialog/LoggerDialog.hpp.
Constructor & Destructor Documentation
fwGui::dialog::LoggerDialog::LoggerDialog (const std::string & title, const std::string & message, const ::fwLog::Logger::sptr & logger)
Constructor. Create a selector with the specified title, message and logs.
Parameters
[in] title Title of the dialog
[in] message Message of the dialog
[in] logger Logger of the dialog
Definition at line 46 of file src/fwGui/dialog/LoggerDialog.cpp.
References fwGui::dialog::ILoggerDialog::REGISTRY_KEY.
Member Function Documentation
void fwGui::dialog::LoggerDialog::setLogger (const ::fwLog::Logger::sptr & logger) override virtual
Set the dialog logger.
Parameters
[in] logger Dialog logger
Implements fwGui::dialog::ILoggerDialog.
Definition at line 71 of file src/fwGui/dialog/LoggerDialog.cpp.
void fwGui::dialog::LoggerDialog::setMessage (const std::string & message) override virtual
Set the dialog message.
Parameters
[in] message Dialog message
Implements fwGui::dialog::ILoggerDialog.
Definition at line 64 of file src/fwGui/dialog/LoggerDialog.cpp.
void fwGui::dialog::LoggerDialog::setTitle (const std::string & title) override virtual
Set the dialog title.
Parameters
[in] title Dialog title
Implements fwGui::dialog::ILoggerDialog.
Definition at line 57 of file src/fwGui/dialog/LoggerDialog.cpp.
bool fwGui::dialog::LoggerDialog::showLoggerDialog (const std::string & title, const std::string & message, const ::fwLog::Logger::sptr & logger) static
Opens a default logger dialog with the specified title, message and logs.
Parameters
[in] title Title of the dialog
[in] message Message of the dialog
[in] logger Logger of the dialog
Returns
Returns true or false whether the user has selected the OK or CANCEL button
Definition at line 23 of file src/fwGui/dialog/LoggerDialog.cpp.
References show().
Referenced by ioGdcm::SDicomSeriesDBReader::getSelectorDialogTitle(), ioGdcm::SSeriesDBReader::getSelectorDialogTitle(), and ioGdcm::SDicomSeriesConverter::updating().
The documentation for this class was generated from the following files:
include/fwGui/dialog/LoggerDialog.hpp
src/fwGui/dialog/LoggerDialog.cpp