fw4spl: fwAtoms::String Class Reference
fwAtoms::String Class Reference
Class represented a String.
#include <String.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
String (::fwAtoms::Base::Key key)
Constructor.
virtual ~String ()
Destructor.
const std::string & getValue () const
void setValue (const std::string &value)
std::string getString () const override
Return the string representation of a value.
virtual FWATOMS_API Base::sptr clone () const override
Returns a clone object.
::fwAtoms::Base::AtomType type () const override
returns Atom type
Public Member Functions inherited from fwAtoms::Base
bool isValue () const
Test if the current base is a value or not (Value = {string;numeric;boolean})
bool isBoolean () const
Test if the current base is a boolean.
bool isNumeric () const
Test if the current base is a Numeric (real or integer)
bool isString () const
Test if the current base is a string.
bool isSequence () const
Test if the current base is a sequence.
bool isMapping () const
Test if the current base is a mapping.
bool isBlob () const
Test if the current base is a blob (a object with a buffer)
bool isObject () const
Test if the current base is an object (representation of fwData)
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWATOMS_API String::sptr New (std::string value)
Construct a new Object represented a string.
Static Public Member Functions inherited from fwAtoms::Base
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Attributes
std::string m_value
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwAtoms::Base
enum AtomType {
BOOLEAN = 1, NUMERIC, STRING, OBJECT,
SEQUENCE, MAP, BLOB
}
typedef ::fwAtoms::factory::Key Key
Static Public Attributes inherited from fwAtoms::Base
static FWATOMS_API const std::string s_VERSION = "1"
Defines fwAtoms version.
Protected Member Functions inherited from fwAtoms::Base
Base ()
Constructor.
Detailed Description
Class represented a String.
Definition at line 23 of file fwAtoms/include/fwAtoms/String.hpp.
Constructor & Destructor Documentation
fwAtoms::String::String (::fwAtoms::Base::Key key) inline
Constructor.
Parameters
key Private construction key
Definition at line 32 of file fwAtoms/include/fwAtoms/String.hpp.
Member Function Documentation
std::string fwAtoms::String::getString () const inline override virtual
Return the string representation of a value.
Returns
the value's representation, else "<Unknown>"
Reimplemented from fwAtoms::Base.
Definition at line 60 of file fwAtoms/include/fwAtoms/String.hpp.
String::sptr fwAtoms::String::New (std::string value) static
Construct a new Object represented a string.
Parameters
value the internal string.
Definition at line 17 of file fwAtoms/src/fwAtoms/String.cpp.
Referenced by fwMDSemanticPatch::V09ALA::V10::fwData::Image::apply(), fwMDSemanticPatch::V10::V09ALA::fwData::Image::apply(), fwMDSemanticPatch::V1::V2::fwData::Patient::apply(), fwStructuralPatch::fwData::Material::V1ToV2::apply(), fwStructuralPatch::fwData::Material::V3ToV4::apply(), fwStructuralPatch::fwData::Material::V4ToV3::apply(), fwMDSemanticPatch::V1::V2::fwData::Study::apply(), fwMDSemanticPatch::V1::V2::fwData::Acquisition::apply(), fwStructuralPatch::fwData::Patient::V1ToFwMedDataPatientV1::apply(), fwMDSemanticPatch::V1::V2::fwData::Composite::apply(), fwStructuralPatch::fwData::Study::V1ToFwMedDataStudyV1::apply(), fwStructuralPatch::fwData::Acquisition::V1ToFwMedDataImageSeriesV1::apply(), clone(), fwMDSemanticPatch::V1::V2::fwData::Composite::Composite(), fwStructuralPatch::creator::fwMedData::Equipment1::create(), fwStructuralPatch::creator::fwMedData::Patient1::create(), fwStructuralPatch::creator::fwMedData::Study1::create(), fwStructuralPatch::creator::fwMedData::Series1::create(), fwStructuralPatch::creator::fwMedData::ActivitySeries1::create(), and fwAtomsPatch::patcher::DefaultPatcher::processBase().
The documentation for this class was generated from the following files:
fwAtoms/include/fwAtoms/String.hpp
fwAtoms/src/fwAtoms/String.cpp