fw4spl: io::IWriter Class Reference
io::IWriter Class Reference
Writer service API. It manages extension points definition and extension configurationThis class represents the base interface for writer services. Use the base service methods :
#include <IWriter.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((IWriter)(::fwServices::IService))
virtual IO_API void configureWithIHM ()=0
Configure the image path (by default does nothing).
virtual IO_API::io::IOPathType getIOPathType () const
This method must be implemented by concrete service writers that use path file system to write data.
IO_APIconst::boost::filesystem::path & getFile () const
Returns the file path setted by user or setted during service configuration.
IO_API void setFile (const ::boost::filesystem::path &file)
Sets file path.
IO_APIconst::io::LocationsType & getFiles () const
Returns file paths setted by user or setted during service configuration.
IO_API void setFiles (const ::io::LocationsType &files)
Sets file paths.
IO_APIconst::boost::filesystem::path & getFolder () const
Returns folder path setted by user or setted during service configuration.
IO_API void clearLocations ()
Clear any location set by the setFile/setFiles/setFolder setter.
IO_APIconst::io::LocationsType & getLocations () const
Returns file/files/folder paths setted by user or setted during service configuration.
IO_API void setFolder (const ::boost::filesystem::path &folder)
Sets folder path.
IO_API bool hasLocationDefined () const
Returns if a location has been defined (by the configuration process or directly by user)
Protected Member Functions
virtual IO_API void configuring () throw (fwTools::Failed)
This method proposes to parse xml configuration to retrieve file/files/folder paths.
Detailed Description
Writer service API. It manages extension points definition and extension configuration
This class represents the base interface for writer services. Use the base service methods :
The service is configured with methods setConfiguration(cfg) and configure()
The method start() initialize the service
To write the object use update() method
Finally we must call stop() before deleting the service
Definition at line 31 of file IWriter.hpp.
Member Function Documentation
virtual IO_API void io::IWriter::configureWithIHM () [pure virtual]
Configure the image path (by default does nothing).
This method is used to find the file path using a file selector.
Implemented in ioData::MeshWriterService, ioITK::JpgImageWriterService, ioData::TransformationMatrix3DWriterService, ioITK::InrImageWriterService, ioVTK::MeshWriterService, ioITK::SImageSeriesWriter, ioITK::SJpgImageSeriesWriter, ioVTK::ImageWriterService, ioVTK::SModelSeriesObjWriter, ioVTK::SModelSeriesWriter, ioVtkGdcm::SImageSeriesWriter, ioVTK::SImageSeriesWriter, and ioAtoms::SWriter.
void io::IWriter::configuring () throw (fwTools::Failed) [protected, virtual]
This method proposes to parse xml configuration to retrieve file/files/folder paths.
You can implement your configuring method if you wan check another information or information not correspond to a path on filesystem, else you must use this generic approach.
Sample configuration for a file:
     <service ... >
        <file>/home/user/myFile.jpg<file/>
     </service>
Sample configuration for many files:
     <service ... >
        <file>/home/user/myFile01.jpg<file/>
        <file>/home/user/myFile02.jpg<file/>
        <file>/home/user/myFile03.jpg<file/>
     </service>
Sample configuration for a folder:
     <service ... >
        <folder>/home/user/myFolder<folder/>
     </service>
Implements fwServices::IService.
Reimplemented in ioAtoms::SWriter.
Definition at line 94 of file IWriter.cpp.
References io::FILE, io::FILES, io::FOLDER, getIOPathType(), fwServices::IService::m_configuration, setFile(), setFiles(), setFolder(), SLM_ASSERT, and io::TYPE_NOT_DEFINED.
const ::boost::filesystem::path & io::IWriter::getFile () const
Returns the file path setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
exception if service not supported FILE management
Definition at line 26 of file IWriter.cpp.
References io::FILE, and getIOPathType().
Referenced by ioITK::SImageSeriesWriter::updating(), ioITK::InrImageWriterService::updating(), ioVTK::SImageSeriesWriter::updating(), ioVTK::ImageWriterService::updating(), ioVTK::MeshWriterService::updating(), ioData::TransformationMatrix3DWriterService::updating(), ioData::MeshWriterService::updating(), and ioAtoms::SWriter::updating().
const ::io::LocationsType & io::IWriter::getFiles () const
Returns file paths setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
exception if service not supported FILES management
Definition at line 44 of file IWriter.cpp.
References io::FILES, and getIOPathType().
const ::boost::filesystem::path & io::IWriter::getFolder () const
Returns folder path setted by user or setted during service configuration.
Precondition:
exception if a folder path is not defined (m_locations.empty())
exception if service not supported FOLDER management
Definition at line 61 of file IWriter.cpp.
References io::FOLDER, and getIOPathType().
Referenced by ioITK::SJpgImageSeriesWriter::updating(), ioITK::JpgImageWriterService::updating(), ioVtkGdcm::SImageSeriesWriter::updating(), ioVTK::SModelSeriesWriter::updating(), and ioVTK::SModelSeriesObjWriter::updating().
io::IOPathType io::IWriter::getIOPathType () const [virtual]
This method must be implemented by concrete service writers that use path file system to write data.
This method returns supported path format (file, files or folder). A reader can support file and folder, or files and folder, but not file and files (because files include file concept).
Reimplemented in ioAtoms::SWriter, ioData::MeshWriterService, ioVTK::MeshWriterService, ioVTK::ImageWriterService, ioData::TransformationMatrix3DWriterService, ioVtkGdcm::SImageSeriesWriter, ioITK::JpgImageWriterService, ioITK::InrImageWriterService, ioITK::SImageSeriesWriter, ioITK::SJpgImageSeriesWriter, ioVTK::SModelSeriesObjWriter, ioVTK::SModelSeriesWriter, and ioVTK::SImageSeriesWriter.
Definition at line 148 of file IWriter.cpp.
References io::TYPE_NOT_DEFINED.
Referenced by configuring(), getFile(), getFiles(), getFolder(), setFile(), setFiles(), and setFolder().
const ::io::LocationsType & io::IWriter::getLocations () const
Returns file/files/folder paths setted by user or setted during service configuration.
Precondition:
exception if a file path is not defined (m_locations.empty())
Definition at line 79 of file IWriter.cpp.
void io::IWriter::setFile (const ::boost::filesystem::path & file)
Sets file path.
Precondition:
exception if service not supported FILE management
Definition at line 35 of file IWriter.cpp.
References io::FILE, and getIOPathType().
Referenced by ioAtoms::SWriter::configureWithIHM(), ioVTK::SImageSeriesWriter::configureWithIHM(), ioVTK::ImageWriterService::configureWithIHM(), ioITK::SImageSeriesWriter::configureWithIHM(), ioVTK::MeshWriterService::configureWithIHM(), ioITK::InrImageWriterService::configureWithIHM(), ioData::TransformationMatrix3DWriterService::configureWithIHM(), ioData::MeshWriterService::configureWithIHM(), and configuring().
void io::IWriter::setFiles (const ::io::LocationsType & files)
Sets file paths.
Precondition:
exception if service not supported FILES management
Definition at line 53 of file IWriter.cpp.
References io::FILES, and getIOPathType().
Referenced by configuring().
void io::IWriter::setFolder (const ::boost::filesystem::path & folder)
Sets folder path.
Precondition:
exception if service not supported FOLDER management
Definition at line 70 of file IWriter.cpp.
References io::FOLDER, and getIOPathType().
Referenced by ioVtkGdcm::SImageSeriesWriter::configureWithIHM(), ioVTK::SModelSeriesObjWriter::configureWithIHM(), ioVTK::SModelSeriesWriter::configureWithIHM(), ioITK::SJpgImageSeriesWriter::configureWithIHM(), ioITK::JpgImageWriterService::configureWithIHM(), and configuring().
The documentation for this class was generated from the following files:
IWriter.hpp
IWriter.cpp