fw4spl: fwGui::registrar::MenuBarRegistrar Class Reference
fwGui::registrar::MenuBarRegistrar Class Reference
Defines the menuBar registrar for IHM.
#include <MenuBarRegistrar.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWGUI_API MenuBarRegistrar (const std::string &sid)
Constructor.
virtual FWGUI_API ~MenuBarRegistrar ()
Destructor. Do nothing.
virtual FWGUI_API::fwGui::container::fwMenuBar::sptr getParent ()
Return the parent container.
virtual FWGUI_API::fwGui::container::fwMenu::sptr getFwMenu (std::string menuSid, std::vector< ::fwGui::container::fwMenu::sptr > menus)
Return the fwMenu associated with the menuSid.
virtual FWGUI_API void initialize (::fwRuntime::ConfigurationElement::sptr configuration)
Initialize registry managers.
virtual FWGUI_API void manage (std::vector< ::fwGui::container::fwMenu::sptr > menus)
Starting menu bar registrar. All services managed in local menus and with start="yes" in configuration will be started.
virtual FWGUI_API void unmanage ()
Stopping view manager. All services managed in local menus will be stopped.
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef std::map< std::string, std::pair< unsigned int, bool > > SIDMenuMapType
Protected Attributes
SIDMenuMapType m_menuSids
All menu services ID managed and associated with pair containing: menu's index vector and boolean describing if is started by the manager.
std::string m_sid
Main service ID associate with this MenuBarRegistrar.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
Defines the menuBar registrar for IHM.
Date
2009-2010.
Definition at line 29 of file MenuBarRegistrar.hpp.
Member Function Documentation
fwGui::container::fwMenu::sptr fwGui::registrar::MenuBarRegistrar::getFwMenu (std::string menuSid, std::vector< ::fwGui::container::fwMenu::sptr > menus) virtual
Return the fwMenu associated with the menuSid.
Parameters
menuSid sid of the menu service
menus vector containing the fwMenu manages by this registrar.
Definition at line 42 of file MenuBarRegistrar.cpp.
References m_menuSids, and SLM_ASSERT.
void fwGui::registrar::MenuBarRegistrar::initialize (::fwRuntime::ConfigurationElement::sptr configuration) virtual
Initialize registry managers.
Example of configuration
 <service uid="menuBar" type="::fwGui::IMenuBarSrv" impl="::gui::aspect::SDefaultMenuBar" autoConnect="no" >
    <gui>
        <layout>
            <menu name="My Menu"/>
            <menu name="My Menu 2"/>
        </layout>
    </gui>
    <registry>
        <menu sid="myMenu" start="yes" />
        <menu sid="myMenu2" start="yes" />
    </registry>
 </service>
This method analyzes the registry section of the configuration.
<menu sid="myMenu" start="yes" /> : define the service of the menu to add in the menu bar.
sid (mandatory): the service identifier.
start = {yes| no} (default value no): indicate if the service must be started by the menu bar service.
Definition at line 52 of file MenuBarRegistrar.cpp.
References m_menuSids, OSLM_ASSERT, and SLM_ASSERT.
void fwGui::registrar::MenuBarRegistrar::manage (std::vector< ::fwGui::container::fwMenu::sptr > menus) virtual
Starting menu bar registrar. All services managed in local menus and with start="yes" in configuration will be started.
Precondition
MenuBarRegistrar must be initialized before.
sub menus must be instanced before.
Definition at line 84 of file MenuBarRegistrar.cpp.
References fwGui::GuiRegistry::actionServiceStopping(), fwTools::fwID::exist(), fwServices::get(), m_menuSids, OSLM_ASSERT, and fwGui::GuiRegistry::registerSIDMenu().
The documentation for this class was generated from the following files:
MenuBarRegistrar.hpp
MenuBarRegistrar.cpp