fw4spl: fwGdcmIO::container::sr::DicomSRNode Class Reference
fwGdcmIO::container::sr::DicomSRNode Class Reference
This class defines a node in a SR document.
#include <DicomSRNode.hpp>
Public Types
typedef std::vector< std::shared_ptr< DicomSRNode > > SubNodeContainer
Public Member Functions
virtual FWGDCMIO_API void write (::gdcm::DataSet &dataset) const
Write the SR node in the dataset.
FWGDCMIO_API void addSubNode (const std::shared_ptr< DicomSRNode > &node)
Add a sub node.
const SubNodeContainer & getSubNodeContainer () const
Get Sub node container.
void setSubNodeContainer (const SubNodeContainer &subNodeContainer)
Set Sub node container.
const DicomCodedAttribute & getCodedAttribute () const
Get Coded attribute.
void setCodedAttribute (const DicomCodedAttribute &codedAttribute)
Set Coded attribute.
const std::string & getType () const
Get Type.
void setType (const std::string &type)
Set Type.
const std::string & getRelationship () const
Get Relationship.
void setRelationship (const std::string &relationship)
Set Relationship.
Protected Member Functions
DicomSRNode (const DicomCodedAttribute &codedAttribute, const std::string &type, const std::string &relationship="")
Constructor.
virtual ~DicomSRNode ()
Destructor.
virtual void print (std::ostream &os) const
Dump function.
::gdcm::SmartPointer< ::gdcm::SequenceOfItems > createConceptNameCodeSequence (const DicomCodedAttribute &codedAttribute) const
Create a concept name code sequence.
void writeContentSequence (::gdcm::DataSet &dataset) const
Write a content sequence.
Protected Attributes
SubNodeContainer m_subNodeContainer
SubNode container.
DicomCodedAttribute m_codedAttribute
Coded entry of the node.
std::string m_type
Node type (0040, a040)
std::string m_relationship
Node relationship (0040, a010)
Friends
FWGDCMIO_API friend std::ostream & operator<< (std::ostream &os, const DicomSRNode &node)
Dump operator.
Detailed Description
This class defines a node in a SR document.
Definition at line 27 of file DicomSRNode.hpp.
Member Function Documentation
void fwGdcmIO::container::sr::DicomSRNode::addSubNode (const std::shared_ptr< DicomSRNode > & node)
Add a sub node.
Parameters
[in] node Node that must be added
Definition at line 37 of file DicomSRNode.cpp.
References m_subNodeContainer.
Referenced by fwGdcmIO::writer::tid::Fiducial::createFiducial(), fwGdcmIO::writer::tid::Measurement::createMeasurement(), and fwGdcmIO::helper::StructuredReport::readSubNode().
gdcm::SmartPointer<::gdcm::SequenceOfItems > fwGdcmIO::container::sr::DicomSRNode::createConceptNameCodeSequence (const DicomCodedAttribute & codedAttribute) const protected
Create a concept name code sequence.
Parameters
[in] dataset Destination dataset
[in] codedAttribute Coded attribute to write
Definition at line 73 of file DicomSRNode.cpp.
References fwGdcmIO::container::DicomCodedAttribute::getCodeMeaning(), fwGdcmIO::container::DicomCodedAttribute::getCodeValue(), fwGdcmIO::container::DicomCodedAttribute::getCodingSchemeDesignator(), fwGdcmIO::container::DicomCodedAttribute::getCodingSchemeVersion(), and m_codedAttribute.
Referenced by write(), fwGdcmIO::container::sr::DicomSRCodeNode::write(), and fwGdcmIO::container::sr::DicomSRNumNode::writeMeasuredValueSequence().
void fwGdcmIO::container::sr::DicomSRNode::write (::gdcm::DataSet & dataset) const virtual
Write the SR node in the dataset.
Parameters
[in] dataset Destination dataset
Reimplemented in fwGdcmIO::container::sr::DicomSRSCoord3DNode, fwGdcmIO::container::sr::DicomSRNumNode, fwGdcmIO::container::sr::DicomSRSCoordNode, fwGdcmIO::container::sr::DicomSRCodeNode, fwGdcmIO::container::sr::DicomSRImageNode, fwGdcmIO::container::sr::DicomSRTextNode, fwGdcmIO::container::sr::DicomSRUIDRefNode, and fwGdcmIO::container::sr::DicomSRContainerNode.
Definition at line 44 of file DicomSRNode.cpp.
References createConceptNameCodeSequence(), fwGdcmIO::container::DicomCodedAttribute::getCodeValue(), fwGdcmIO::container::DicomCodedAttribute::getCodingSchemeDesignator(), m_codedAttribute, m_relationship, m_subNodeContainer, m_type, and writeContentSequence().
Referenced by fwGdcmIO::container::sr::DicomSRContainerNode::write(), fwGdcmIO::container::sr::DicomSRCodeNode::write(), fwGdcmIO::container::sr::DicomSRTextNode::write(), fwGdcmIO::container::sr::DicomSRUIDRefNode::write(), fwGdcmIO::container::sr::DicomSRImageNode::write(), fwGdcmIO::container::sr::DicomSRNumNode::write(), fwGdcmIO::container::sr::DicomSRSCoordNode::write(), and fwGdcmIO::container::sr::DicomSRSCoord3DNode::write().
void fwGdcmIO::container::sr::DicomSRNode::writeContentSequence (::gdcm::DataSet & dataset) const protected
Write a content sequence.
See also
PS 3.3 Table 8.8-1
Parameters
[in] dataset Destination dataset
Definition at line 110 of file DicomSRNode.cpp.
References m_subNodeContainer, and SPTR.
Referenced by write().
The documentation for this class was generated from the following files:
DicomSRNode.hpp
DicomSRNode.cpp