fw4spl: fwDataIO::writer::GzArrayWriter Class Reference
fwDataIO::writer::GzArrayWriter Class Reference
Array Writer. Write file format .raw.gz.
#include <GzArrayWriter.hpp>
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((GzArrayWriter)(GenericObjectWriter< ::fwData::Array >),(()),::fwDataIO::writer::factory::New< GzArrayWriter >)
FWDATAIO_API GzArrayWriter (::fwDataIO::writer::IObjectWriter::Key key)
Constructor. Do nothing.
virtual FWDATAIO_API ~GzArrayWriter ()
Destructor. Do nothing.
virtual FWDATAIO_API void write ()
Read the file with zlib API.
virtual FWDATAIO_API std::string extension ()
Defines extension supported by this writer ".raw.gz".
Detailed Description
Array Writer. Write file format .raw.gz.
Date:
2011
Ircad writer to write a fwData::Array on filesystem which the file format is .raw.gz. This format is basic. The buffer is written in a file with zlib.
Definition at line 32 of file GzArrayWriter.hpp.
Member Function Documentation
void fwDataIO::writer::GzArrayWriter::write () [virtual]
Read the file with zlib API.
test if can open archive
Implements fwDataIO::writer::IObjectWriter.
Definition at line 39 of file GzArrayWriter.cpp.
References fwComEd::helper::Array::getBuffer(), fwDataIO::writer::GenericObjectWriter< ::fwData::Array >::getConcreteObject(), and fwData::location::enableSingleFile< ::fwDataIO::writer::IObjectWriter >::getFile().
The documentation for this class was generated from the following files:
GzArrayWriter.hpp
GzArrayWriter.cpp