fw4spl: scene2D::adaptor::ViewportRangeSelector Class Reference
scene2D::adaptor::ViewportRangeSelector Class Reference
#include <ViewportRangeSelector.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ViewportRangeSelector)(::scene2D::adaptor::IAdaptor))
Protected Member Functions
SCENE2D_API void configuring () throw (::fwTools::Failed)
Not implemented in IAdaptor but in its subclasses.
SCENE2D_API void doStart () throw (::fwTools::Failed)
Pure virtual -> implemented in the subclasses.
SCENE2D_API void doUpdate () throw (::fwTools::Failed)
Pure virtual -> implemented in the subclasses.
SCENE2D_API void doReceive (fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
SCENE2D_API void doSwap () throw (::fwTools::Failed)
Pure virtual -> implemented in the subclasses.
SCENE2D_API void doStop () throw (::fwTools::Failed)
Pure virtual -> implemented in the subclasses.
SCENE2D_API void processInteraction (::scene2D::data::Event::sptr _event)
Interact with the mouse events catched on the IAdaptor (virtual function, its behavior is only defined in the specific adaptors).
SCENE2D_API void updateViewportFromShutter (double x, double y, double width, double height)
Protected Attributes
QGraphicsRectItem * m_shutter
bool m_isLeftInteracting
bool m_isRightInteracting
bool m_isInteracting
::scene2D::data::Coord m_dragStartPoint
::scene2D::data::Coord m_dragStartShutterPos
const int m_clickCatchRange
A spacing value for an easier picking onto shutter borders.
QGraphicsItemGroup * m_layer
(This is the only graphic item which has to be added into the scene).
float m_initialX
Initial position of the shutter on the X axis.
float m_initialWidth
Initial width of the shutter.
Detailed Description
The viewport range selector adaptor allows to select a delimited range of a viewport. It uses a graphical delimiter (called shutter) that can be moved from both left to right and right to left directions (in those cases, shutter's width is changing).
Clicking onto the approximative center of the shutter allows the user to change its position, according to mouse's cursor position (width won't change).
Clicking onto the approximative left/right (respectively) border of the shutter allows the user to change the width of the shutter: the right/left (respectively) border doesn't move during resizing.
Each change onto the shutter will cause this adaptor to update the managed scene2D::data::Viewport object.
Configuration example:
   <adaptor id="viewSelector" class="::scene2D::adaptor::ViewportRangeSelector" objectId="myViewport">
       <config xAxis="xAxis" yAxis="yAxis" zValue="5" />
   </adaptor>
objectId : the viewport object that is updated by this adaptor
xAxis : see scene2D::adaptor::IAdaptor
yAxis : see scene2D::adaptor::IAdaptor
zValue : see scene2D::adaptor::IAdaptor
initialX : initial position of the shutter on the X axis
initialWidth : initial width of the shutter
This adaptor is intended to be used with a scene2D::adaptor::ViewportUpdater adaptor.
Definition at line 54 of file ViewportRangeSelector.hpp.
Member Function Documentation
void scene2D::adaptor::ViewportRangeSelector::updateViewportFromShutter (double x, double y, double width, double height) [protected]
Update the viewport object according to the current state of the shutter (coordinates are mapped from the scene).
Definition at line 318 of file ViewportRangeSelector.cpp.
References scene2D::adaptor::IAdaptor::mapSceneToAdaptor(), and SLM_TRACE_FUNC.
Referenced by doStart(), and processInteraction().
The documentation for this class was generated from the following files:
ViewportRangeSelector.hpp
ViewportRangeSelector.cpp