fw4spl: gui::action::ConfigActionSrv Class Reference
gui::action::ConfigActionSrv Class Reference
To manage configuration file defines in xml extension.
#include <ConfigActionSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((ConfigActionSrv)(::fwGui::IActionSrv))
GUI_API ConfigActionSrv () throw ()
Constructor. Do nothing.
virtual GUI_API ~ConfigActionSrv () throw ()
Destructor. Do nothing.
virtual GUI_API void setIsActive (bool isActive)
Set the action service is activated/inactivated.
Static Public Attributes
static
GUI_APIconst::fwCom::Signals::SignalKeyType s_LAUNCHED_SIG = "launched"
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
This method launches the IAction::starting method.
virtual void stopping () throw (::fwTools::Failed)
This method launches the IAction::stopping method.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Management of observations (overrides).
virtual void updating () throw (::fwTools::Failed)
Starts the view and initialize the operator.
virtual void configuring () throw (fwTools::Failed)
Declare the configuration to associate with an operator type and a view config.
virtual void info (std::ostream &_sstream)
Overrides.
virtual void startConfig ()
Read the configuration and show the parameters view.
virtual void stopConfig ()
Close the parameters view.
void AddGenericUidToFieldApadtor ()
Add GENERIC_UID to field to adapt.
void connectToConfigRoot ()
helper to connect tp config root
void disconnectToConfigRoot ()
helper to disconnect tp config root
Protected Attributes
std::string m_viewConfigId
Id of plugin extension where the configuration is defined.
bool m_configIsRunning
to know if config is running
::fwServices::AppConfigManager::sptr m_configTemplateManager
std::map< std::string,
std::string > m_fieldAdaptors
keep the association between the PATTERN and the associated key as fieldAdaptors[PATTERN] = AssociatedKey.
::fwServices::helper::SigSlotConnection::sptr m_connections
To manage connection to the config root.
Defines signal triggered when config is started
typedef ::fwCom::Signal< void() > LaunchedSignalType
LaunchedSignalType::sptr m_sigLaunched
Detailed Description
To manage configuration file defines in xml extension.
Date:
2010.
This action starts/stops a template configuration given by its identifier in this action configuration.
You can specified pattern to replace in the template configuration by the tag 'replace'.
The pattern GENERIC_UID is replaced by a generated unique identifier when the configuration is launch. This assure that the created object and services in the configuration have a unique uid even if this configuration is launch several times.
Example of this service configuration
   <service impl="::gui::action::ConfigActionSrv" type="::fwGui::IActionSrv">
       <config id="IdOfTemplateConfig" />
       <replace val="VALUE" pattern ="PATTERN_TO_REPLACE_BY_VALUE" />
   </service>
Example of template configuration
   <extension implements="::fwServices::registry::AppConfig">
       <id>Activity1Config</id>
       <type>template</type>
       <config>
           <object uid="GENERIC_UID_myComposite" type="::fwData::Composite">
               <service uid="GENERIC_UID_myService" type="..." impl="..." autoConnect="no" />
               <item key="myImage">
                   <object uid="PATTERN_TO_REPLACE_BY_VALUE" src="ref" type="::fwData::Image" />
               </item>
               <!-- ... -->
           </object>
       </config>
   </extension>
Definition at line 67 of file ConfigActionSrv.hpp.
Member Function Documentation
void gui::action::ConfigActionSrv::configuring () throw (fwTools::Failed) [protected, virtual]
Declare the configuration to associate with an operator type and a view config.
Call the IAction::configuring()
Example of this service configuration
       <service impl="::gui::action::ConfigActionSrv" type="::fwGui::IActionSrv">
           <config id="IdOfTemplateConfig" />
           <replace val="VALUE" pattern ="PATTERN_TO_REPLACE_BY_VALUE" />
       </service>
Implements fwServices::IService.
Reimplemented in gui::action::ConfigActionSrvWithKey.
Definition at line 74 of file ConfigActionSrv.cpp.
References fwGui::IActionSrv::initialize(), fwServices::IService::m_configuration, m_fieldAdaptors, m_viewConfigId, SLM_ASSERT, and SLM_TRACE_FUNC.
void gui::action::ConfigActionSrv::receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed) [protected, virtual]
Management of observations (overrides).
Stop configuration when it receives "WINDOW_CLOSED" event (ie. close the param view).
Reimplemented in gui::action::ConfigActionSrvWithKey.
Definition at line 125 of file ConfigActionSrv.cpp.
References fwGui::IActionSrv::setIsActive().
Referenced by gui::action::ConfigActionSrvWithKey::receiving().
The documentation for this class was generated from the following files:
ConfigActionSrv.hpp
ConfigActionSrv.cpp