fw4spl: fwDataIO::writer::GzBufferImageWriter Class Reference
fwDataIO::writer::GzBufferImageWriter Class Reference
Image Writer. Write file format .raw.gz.
#include <GzBufferImageWriter.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((GzBufferImageWriter)(GenericObjectWriter< ::fwData::Image >))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwDataIO::writer::factory::New< GzBufferImageWriter >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((GzBufferImageWriter)(GenericObjectWriter< ::fwData::Image >)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWDATAIO_API GzBufferImageWriter (::fwDataIO::writer::IObjectWriter::Key key)
Constructor. Do nothing.
virtual FWDATAIO_API ~GzBufferImageWriter ()
Destructor. Do nothing.
virtual FWDATAIO_API void write ()
Read the file with zlib API.
virtual FWDATAIO_API std::string extension ()
Defines extension supported by this writer ".raw.gz".
Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Image >
__FWCORE_CLASS_TYPEDEFS ((GenericObjectWriter< ::fwData::Image >)(::fwDataIO::writer::IObjectWriter))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((GenericObjectWriter< ::fwData::Image >)(::fwDataIO::writer::IObjectWriter)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
GenericObjectWriter ()
Constructor. Do nothing.
virtual ~GenericObjectWriter ()
Destructor. Do nothing.
virtual void setObject (::fwTools::Object::sptr obj)
m_object setter.
virtual std::shared_ptr< DataType > getConcreteObject ()
m_object getter.
Public Member Functions inherited from fwDataIO::writer::IObjectWriter
__FWCORE_CLASS_TYPEDEFS ((IObjectWriter))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((IObjectWriter)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual FWDATAIO_API void setLocation (const ::fwData::location::ILocation::sptr location)
m_location setter.
virtual FWDATAIO_API::fwData::location::ILocation::sptr getLocation ()
m_location getter.
virtual FWDATAIO_API::fwTools::Object::sptr getObject ()
m_object getter.
virtual FWDATAIO_API void cancel ()
Requests writer abortion.
virtual FWDATAIO_API std::shared_ptr< ::fwJobs::IJob > getJob () const
Returns the internal job, nullptr by default.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwData::location::enableSingleFile< ::fwDataIO::writer::IObjectWriter >
enableSingleFile (::fwDataIO::writer::IObjectWriter *rw)
constructor
void setFile (ILocation::PathType path)
Set file system path.
ILocation::PathType getFile ()
Get file system path.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Image >
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwDataIO::writer::IObjectWriter
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwDataIO::writer::GenericObjectWriter< ::fwData::Image >
typedef ::fwData::Image DataType
the object type related
Public Types inherited from fwDataIO::writer::IObjectWriter
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< void() > CancelCallback
typedef ::fwDataIO::writer::factory::Key Key
Protected Member Functions inherited from fwDataIO::writer::IObjectWriter
FWDATAIO_API IObjectWriter ()
Constructor. Do nothing.
virtual FWDATAIO_API ~IObjectWriter ()
Destructor. Do nothing.
Protected Attributes inherited from fwDataIO::writer::IObjectWriter
::fwTools::Object::wptr m_object
Object write on filesystem by the process.
::fwData::location::ILocation::sptr m_location
Object location (file path, directory path, url, etc)
std::string m_extension
Extension of file format.
Detailed Description
Image Writer. Write file format .raw.gz.
Date
2009
Ircad writer to write a fwData::Image on filesystem which the file format is .raw.gz. This format is basic. The buffer is writen in a file with zlib.
Definition at line 33 of file GzBufferImageWriter.hpp.
Member Function Documentation
fwDataIO::writer::GzBufferImageWriter::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwDataIO::writer::factory::New< GzBufferImageWriter > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((GzBufferImageWriter)(GenericObjectWriter< ::fwData::Image>)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((GzBufferImageWriter)(GenericObjectWriter< ::fwData::Image>)).
void fwDataIO::writer::GzBufferImageWriter::write () virtual
Read the file with zlib API.
test if can open archive
Implements fwDataIO::writer::IObjectWriter.
Definition at line 44 of file GzBufferImageWriter.cpp.
References fwComEd::helper::Image::getBuffer(), fwDataIO::writer::GenericObjectWriter< ::fwData::Image >::getConcreteObject(), fwData::location::enableSingleFile< ::fwDataIO::writer::IObjectWriter >::getFile(), OSLM_TRACE, and SLM_ASSERT.
The documentation for this class was generated from the following files:
GzBufferImageWriter.hpp
GzBufferImageWriter.cpp