fw4spl: opVTKMesh::SVTKMesher Class Reference
opVTKMesh::SVTKMesher Class Reference
Service to generate mesh with VTK.
#include <SVTKMesher.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((SVTKMesher)(::opVTKMesh::IMesher))
Protected Member Functions
virtual OPVTKMESH_API void starting () throw (::fwTools::Failed)
Initialize the service activity.
virtual OPVTKMESH_API void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual OPVTKMESH_API void receiving (::fwServices::ObjectMsg::csptr _pMsg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
virtual OPVTKMESH_API void configuring () throw (::fwTools::Failed)
Declare the configuration to define percent of reduction, image source and ModelSeries destination.
virtual OPVTKMESH_API void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual OPVTKMESH_API void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
Service to generate mesh with VTK.
Definition at line 21 of file SVTKMesher.hpp.
Member Function Documentation
void opVTKMesh::SVTKMesher::configuring () throw (::fwTools::Failed) [protected, virtual]
Declare the configuration to define percent of reduction, image source and ModelSeries destination.
Example of this service configuration
       <service impl="::opVTKMesh::SVTKMesher" type="::opVTKMesh::IMesher">
           <config>
                <percentReduction>80</percentReduction>
                <image>IMAGE_KEY</image>
                <modelSeries>MODELSERIES_KEY</modelSeries>
            </config>
       </service>
Implements fwServices::IService.
Definition at line 70 of file SVTKMesher.cpp.
References fwServices::IService::getConfigTree(), and SLM_ASSERT.
void opVTKMesh::SVTKMesher::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 184 of file SVTKMesher.cpp.
void opVTKMesh::SVTKMesher::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 65 of file SVTKMesher.cpp.
void opVTKMesh::SVTKMesher::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 55 of file SVTKMesher.cpp.
void opVTKMesh::SVTKMesher::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 60 of file SVTKMesher.cpp.
void opVTKMesh::SVTKMesher::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Notification
Implements fwServices::IService.
Definition at line 93 of file SVTKMesher.cpp.
References fwComEd::ModelSeriesMsg::ADD_RECONSTRUCTION, fwVtkIO::helper::Mesh::fromVTKMesh(), fwServices::IEditionService::notify(), OSLM_TRACE, and SLM_ASSERT.
The documentation for this class was generated from the following files:
SVTKMesher.hpp
SVTKMesher.cpp