fw4spl: uiMeasurement::action::AddDistance Class Reference
uiMeasurement::action::AddDistance Class Reference
This action adds distance on image.
#include <AddDistance.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((AddDistance)(::fwGui::IActionSrv))
Protected Member Functions
void configuring () throw (::fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
void starting () throw (::fwTools::Failed)
Initialize the service activity.
void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
void stopping () throw (::fwTools::Failed)
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
UIMEASUREMENT_API void info (std::ostream &_sstream)
Write information in a stream.
Detailed Description
This action adds distance on image.
Date:
2010.
Definition at line 25 of file AddDistance.hpp.
Member Function Documentation
void uiMeasurement::action::AddDistance::configuring () throw (::fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 100 of file AddDistance.cpp.
References fwGui::IActionSrv::initialize().
void uiMeasurement::action::AddDistance::info (std::ostream & _sstream) [protected, virtual]
Write information in a stream.
This method is used by operator<<(std::ostream & _sstream, IService& _service) to avoid declaration of << by all services.
Reimplemented from fwServices::IService.
Definition at line 51 of file AddDistance.cpp.
void uiMeasurement::action::AddDistance::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 114 of file AddDistance.cpp.
void uiMeasurement::action::AddDistance::starting () throw (::fwTools::Failed) [protected, virtual]
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also:
start()
Implements fwServices::IService.
Definition at line 107 of file AddDistance.cpp.
References fwGui::IActionSrv::actionServiceStarting().
void uiMeasurement::action::AddDistance::stopping () throw (::fwTools::Failed) [protected, virtual]
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also:
stop()
Implements fwServices::IService.
Definition at line 119 of file AddDistance.cpp.
References fwGui::IActionSrv::actionServiceStopping().
void uiMeasurement::action::AddDistance::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 58 of file AddDistance.cpp.
References fwComEd::ImageMsg::DISTANCE, fwComEd::Dictionary::m_imageDistancesId, fwServices::IEditionService::notify(), and SLM_TRACE.
The documentation for this class was generated from the following files:
AddDistance.hpp
AddDistance.cpp