fw4spl: scene2D::adaptor::TransferFunction Class Reference
scene2D::adaptor::TransferFunction Class Reference
Public Types
enum LineType { PLAIN, DOTTED }
Enumeration of authorized line types.
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((TransferFunction)(::scene2D::adaptor::IAdaptor))
SCENE2D_API TransferFunction () throw ()
Constructor, add handle events TRANSFERFUNCTION and WINDOWING.
virtual SCENE2D_API ~TransferFunction () throw ()
Basic destructor, do nothing.
Protected Member Functions
SCENE2D_API void configuring () throw (::fwTools::Failed)
Configuring the TransferFunction adaptor.
SCENE2D_API void doStart () throw (::fwTools::Failed)
SCENE2D_API void doUpdate () throw (::fwTools::Failed)
SCENE2D_API void doReceive (fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
If the message is TRANSFERFUNCTION or WINDOWING, call DoUpdate().
SCENE2D_API void doSwap () throw (::fwTools::Failed)
SCENE2D_API void doStop () throw (::fwTools::Failed)
SCENE2D_API void processInteraction (SPTR(::scene2D::data::Event) _event)
Detailed Description
Definition at line 22 of file Bundles/LeafVisu/scene2D/include/scene2D/adaptor/TransferFunction.hpp.
Member Function Documentation
void scene2D::adaptor::TransferFunction::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring the TransferFunction adaptor.
Example of configuration
    <adaptor id="tf2" class="::scene2D::adaptor::TransferFunction" objectId="myImage">
        <config lineColor="lightGray" circleColor="lightGray" xAxis="xAxis" yAxis="yAxis" zValue="4"/>
    </adaptor>
<config lineColor="lightGray" circleColor="lightGray" xAxis="xAxis" yAxis="yAxis" zValue="4"/> : Set the config.
lineColor : no mandatory (default value : black) : Set the color of the lines between the TF points.
circleColor : no mandatory (default value : black) : Set the outline color of the circles representing the TF points.
xAxis : no mandatory (default value : ::scene2D::data::Axis::New() : m_origin (0), m_scale (1), m_scaleType (LINEAR)) : Set the x Axis of the TF layer.
yAxis : no mandatory (default value : ::scene2D::data::Axis::New() : m_origin (0), m_scale (1), m_scaleType (LINEAR)) : Set the y Axis of the TF layer.
zValue : no mandatory (default value : 0) : Set the zValue of the TF layer (the higher the zValue, the higher the layer is).
Reimplemented from scene2D::adaptor::IAdaptor.
Definition at line 58 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References fwServices::IService::m_configuration, fwComEd::helper::MedicalImageAdaptor::parseTFConfig(), scene2D::data::InitQtPen::setPenColor(), and SLM_ASSERT.
void scene2D::adaptor::TransferFunction::doStart () throw (::fwTools::Failed) [protected, virtual]
Initialize the layer m_layer (QGraphicsGroupItem), m_circleWidth and m_circleHeight from the viewport dimensions, and call DoUpdate().
Implements scene2D::adaptor::IAdaptor.
Definition at line 501 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References doUpdate(), fwData::Object::s_OBJECT_MODIFIED_SIG, and fwServices::IService::s_RECEIVE_SLOT.
void scene2D::adaptor::TransferFunction::doStop () throw (::fwTools::Failed) [protected, virtual]
Clear the m_circles and m_linesAndPolygons vectors and remove the layer (and therefore all it's related items) from the scene.
Implements scene2D::adaptor::IAdaptor.
Definition at line 562 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References fwCom::Connection::disconnect().
void scene2D::adaptor::TransferFunction::doSwap () throw (::fwTools::Failed) [protected, virtual]
Todo:
Implements scene2D::adaptor::IAdaptor.
Definition at line 553 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References doUpdate().
void scene2D::adaptor::TransferFunction::doUpdate () throw (::fwTools::Failed) [protected, virtual]
Call buildTFPoints(), buildCircles(), buildLinesAndPolygons() and buildLayer() to build the tf points map, the circles vector, the lines and polygons vector, and to add'em all to the layer and add it to the scene.
Implements scene2D::adaptor::IAdaptor.
Definition at line 523 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References fwComEd::helper::MedicalImageAdaptor::updateImageInfos(), and fwComEd::helper::MedicalImageAdaptor::updateTransferFunction().
Referenced by doStart(), doSwap(), and processInteraction().
void scene2D::adaptor::TransferFunction::processInteraction (SPTR(::scene2D::data::Event) _event) [protected]
Iterate m_circles vector (and in parallel m_TFPoints map) and, as the case, call the function associated to a specific event.
Definition at line 585 of file Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp.
References doUpdate(), scene2D::adaptor::IAdaptor::m_viewInitialSize, and SLM_ASSERT.
The documentation for this class was generated from the following files:
Bundles/LeafVisu/scene2D/include/scene2D/adaptor/TransferFunction.hpp
Bundles/LeafVisu/scene2D/src/scene2D/adaptor/TransferFunction.cpp