fw4spl: fwGdcmIO::container::DicomSurface Class Reference
fwGdcmIO::container::DicomSurface Class Reference
This class defines one surface mesh item in order to transform into DICOM/FW4SPL form.
#include <DicomSurface.hpp>
Public Member Functions
FWGDCMIO_API DicomSurface ()
Constructor.
FWGDCMIO_API ~DicomSurface ()
Destructor.
FWGDCMIO_API void setFromData (fwData::Reconstruction::csptr reconstruction)
Set members from a reconstruction.
FWGDCMIO_API void convertToData (fwData::Reconstruction::sptr reconstruction)
Set a reconstruction from DicomSurface data.
FWGDCMIO_API::fwData::Mesh::sptr convertToData (const float *coord, const unsigned long coordSize, const uint32_t *index, const unsigned long indexSize, const float *normalCoord)
Convert Surface to fwData::Mesh.
FWGDCMIO_API const ::boost::shared_ptr< float > getPointCoordData () const
Return point coordinates.
FWGDCMIO_API unsigned long getPointCoordSize () const
Return number of points.
FWGDCMIO_API const ::boost::shared_ptr< uint32_t > getPointIndexList () const
Return index list.
FWGDCMIO_API unsigned long getPointIndexSize () const
Return number of index.
FWGDCMIO_API const ::boost::shared_ptr< float > getNormalCoordData () const
Return normal list.
FWGDCMIO_API unsigned long getNormalCoordSize () const
Return number of normals.
FWGDCMIO_API void setPointCoordData (const ::boost::shared_ptr< float > array)
Set point coordinates.
FWGDCMIO_API void setPointCoordSize (const unsigned long size)
Set number of points.
FWGDCMIO_API void setPointIndexList (const ::boost::shared_ptr< uint32_t > array)
Set index list.
FWGDCMIO_API void setPointIndexSize (const unsigned long size)
Set number of index.
FWGDCMIO_API void setNormalCoordData (const ::boost::shared_ptr< float > array)
Set normals list.
FWGDCMIO_API void setNormalCoordSize (const unsigned long size)
Set number of normals.
Detailed Description
This class defines one surface mesh item in order to transform into DICOM/FW4SPL form.
Definition at line 25 of file DicomSurface.hpp.
Member Function Documentation
void fwGdcmIO::container::DicomSurface::convertToData (fwData::Reconstruction::sptr reconstruction)
Set a reconstruction from DicomSurface data.
Note
All members have to be set before.
Parameters
[in] reconstruction Destination reconstruction
Definition at line 192 of file DicomSurface.cpp.
References fwDataTools::helper::Array::begin().
Referenced by fwGdcmIO::reader::ie::Surface::readSurfaceMeshModule().
fwData::Mesh::sptr fwGdcmIO::container::DicomSurface::convertToData (const float * coord, const unsigned long coordSize, const uint32_t * index, const unsigned long indexSize, const float * normalCoord)
Convert Surface to fwData::Mesh.
Parameters
[in] coord Coordinates
[in] coordSize Number of coordinates
[in] index Indices
[in] indexSize Number of indices
[in] normalCoord Normal coordinates
Definition at line 256 of file DicomSurface.cpp.
References fwDataTools::helper::Array::begin().
void fwGdcmIO::container::DicomSurface::setFromData (fwData::Reconstruction::csptr reconstruction)
Set members from a reconstruction.
Parameters
[in] reconstruction Source reconstruction
Definition at line 120 of file DicomSurface.cpp.
References fwDataTools::helper::Array::begin(), and fwDataTools::Mesh::hasUniqueCellType().
void fwGdcmIO::container::DicomSurface::setNormalCoordData (const ::boost::shared_ptr< float > array)
Set normals list.
Parameters
[in] array Normals list
Definition at line 106 of file DicomSurface.cpp.
void fwGdcmIO::container::DicomSurface::setNormalCoordSize (const unsigned long size)
Set number of normals.
Parameters
[in] size Number of normals
Definition at line 113 of file DicomSurface.cpp.
void fwGdcmIO::container::DicomSurface::setPointCoordData (const ::boost::shared_ptr< float > array)
Set point coordinates.
Parameters
[in] array Point coordinates
Definition at line 78 of file DicomSurface.cpp.
void fwGdcmIO::container::DicomSurface::setPointCoordSize (const unsigned long size)
Set number of points.
Parameters
[in] size Number of points
Definition at line 85 of file DicomSurface.cpp.
void fwGdcmIO::container::DicomSurface::setPointIndexList (const ::boost::shared_ptr< uint32_t > array)
Set index list.
Parameters
[in] array Index list
Definition at line 92 of file DicomSurface.cpp.
void fwGdcmIO::container::DicomSurface::setPointIndexSize (const unsigned long size)
Set number of index.
Parameters
[in] size Number of index
Definition at line 99 of file DicomSurface.cpp.
The documentation for this class was generated from the following files:
DicomSurface.hpp
DicomSurface.cpp