fw4spl: ctrlSelection::manager::MedicalImageManagerSrv Class Reference
ctrlSelection::manager::MedicalImageManagerSrv Class Reference
This manager converts the images specified by key to medical image (with landmarks, transfer function fields)
#include <MedicalImageManagerSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((MedicalImageManagerSrv)(::ctrlSelection::IManagerSrv))
CTRLSELECTION_API MedicalImageManagerSrv () throw ()
Constructor. Do nothing.
virtual CTRLSELECTION_API ~MedicalImageManagerSrv () throw ()
Destructor. Do nothing.
virtual CTRLSELECTION_API void starting () throw (::fwTools::Failed)
Implements starting method derived from IService. Do nothing.
virtual CTRLSELECTION_API void stopping () throw (::fwTools::Failed)
Implements stopping method derived from IService. Do nothing.
virtual CTRLSELECTION_API void configuring () throw (::fwTools::Failed)
Configure the service.
virtual CTRLSELECTION_API void reconfiguring () throw (::fwTools::Failed)
Implements reconfiguring method derived from IService. Do nothing.
virtual CTRLSELECTION_API void updating () throw (::fwTools::Failed)
Implements updating method derived from IService. Do nothing.
virtual CTRLSELECTION_API void info (std::ostream &_sstream)
Implements info method derived from IService. Print classname.
virtual CTRLSELECTION_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
Detailed Description
This manager converts the images specified by key to medical image (with landmarks, transfer function fields)
Definition at line 25 of file MedicalImageManagerSrv.hpp.
Member Function Documentation
void ctrlSelection::manager::MedicalImageManagerSrv::configuring () throw (::fwTools::Failed) [virtual]
Configure the service.
     <service uid="medicalImageManager" impl="::ctrlSelection::manager::MedicalImageManagerSrv" type="::ctrlSelection::IManagerSrv" autoConnect="yes">
         <update imageCompositeKey="image" />
     </service>
Implements fwServices::IService.
Definition at line 100 of file MedicalImageManagerSrv.cpp.
References fwRuntime::ConfigurationElementContainer::begin(), fwRuntime::ConfigurationElementContainer::end(), fwServices::IService::m_configuration, OSLM_DEBUG, fwRuntime::ConfigurationElementContainer::size(), SLM_ASSERT, and SLM_FATAL_IF.
void ctrlSelection::manager::MedicalImageManagerSrv::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 44 of file MedicalImageManagerSrv.cpp.
References fwComEd::CompositeMsg::ADDED_KEYS, fwComEd::CompositeMsg::CHANGED_KEYS, and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
MedicalImageManagerSrv.hpp
MedicalImageManagerSrv.cpp