fw4spl: uiVisu::BasicFloatEditor Class Reference
uiVisu::BasicFloatEditor Class Reference
BasicFloatEditor service permits to edit a float value.
#include <BasicFloatEditor.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((BasicFloatEditor)(::gui::editor::IEditor))
UIVISUQT_API BasicFloatEditor () throw ()
Constructor. Do nothing.
virtual UIVISUQT_API ~BasicFloatEditor () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Slots
void onModifyValue (QString value)
This method is called when the value change.
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
Install the layout.
virtual void stopping () throw (::fwTools::Failed)
Destroy the layout.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Do nothing.
virtual void updating () throw (::fwTools::Failed)
Do nothing.
virtual void swapping () throw (::fwTools::Failed)
Do nothing.
virtual void configuring () throw (fwTools::Failed)
Configure the editor. Do nothing.
virtual void info (std::ostream &_sstream)
Overrides.
Detailed Description
BasicFloatEditor service permits to edit a float value.
Date:
2011.
Definition at line 29 of file BasicFloatEditor.hpp.
Member Function Documentation
void uiVisu::BasicFloatEditor::onModifyValue (QString value) [protected, slot]
This method is called when the value change.
Check if the value is a valid float, update the Float object value and notify the modification.
Definition at line 140 of file BasicFloatEditor.cpp.
References fwData::Object::copy(), fwServices::IEditionService::notify(), OSLM_TRACE, SLM_TRACE_FUNC, updating(), and fwComEd::FloatMsg::VALUE_IS_MODIFIED.
Referenced by starting(), and stopping().
The documentation for this class was generated from the following files:
BasicFloatEditor.hpp
BasicFloatEditor.cpp