fw4spl: fwTest::generator::SeriesDB Class Reference
fwTest::generator::SeriesDB Class Reference
Static Public Member Functions
static FWTEST_API std::shared_ptr< ::fwMedData::SeriesDB > createSeriesDB (const unsigned char nbImgSeries, const unsigned char nbModelSeries, const unsigned char nbActivitySeries)
Creates a SeriesDB.
static FWTEST_API std::shared_ptr< ::fwMedData::Patient > createPatient ()
Returns a Patient with dummy informations.
static FWTEST_API std::shared_ptr< ::fwMedData::Study > createStudy ()
Returns a Study with dummy informations.
static FWTEST_API std::shared_ptr< ::fwMedData::Equipment > createEquipement ()
Returns an Equipment with dummy informations.
static FWTEST_API void generateSeriesInformation (std::shared_ptr< ::fwMedData::Series > series)
Generates dummy informations for the series.
static FWTEST_API std::shared_ptr< ::fwMedData::ImageSeries > createImageSeries ()
Returns an ImageSeries with a randomized image.
static FWTEST_API std::shared_ptr< ::fwMedData::ModelSeries > createModelSeries (unsigned char nbReconstruction)
Returns a ModelSeries containing random Reconstructions.
static FWTEST_API std::shared_ptr< ::fwMedData::ActivitySeries > createActivitySeries ()
Returns an ActivitySeries with dummy data.
static FWTEST_API void generateReconstruction (std::shared_ptr< ::fwData::Reconstruction > rec)
Generate a reconstruction.
Detailed Description
Definition at line 43 of file tests/fwTest/include/fwTest/generator/SeriesDB.hpp.
Member Function Documentation
fwMedData::ModelSeries::sptr fwTest::generator::SeriesDB::createModelSeries (unsigned char nbReconstruction) static
Returns a ModelSeries containing random Reconstructions.
Parameters
nbReconstruction number of Reconstrutions to add in the ModelSeries
Definition at line 180 of file tests/fwTest/src/fwTest/generator/SeriesDB.cpp.
References generateReconstruction(), and generateSeriesInformation().
Referenced by createSeriesDB().
fwMedData::SeriesDB::sptr fwTest::generator::SeriesDB::createSeriesDB (const unsigned char nbImgSeries, const unsigned char nbModelSeries, const unsigned char nbActivitySeries) static
Creates a SeriesDB.
Parameters
nbImgSeries number of ImageSeries to add in seriesDB
nbModelSeries number of ModelSeries to add in seriesDB
nbActivitySeries number of ActivitySeries to add in seriesDB
Returns
The created SeriesDB
Definition at line 39 of file tests/fwTest/src/fwTest/generator/SeriesDB.cpp.
References createActivitySeries(), createImageSeries(), createModelSeries(), and fwTest::generator::Image::initRand().
void fwTest::generator::SeriesDB::generateReconstruction (std::shared_ptr< ::fwData::Reconstruction > rec) static
Generate a reconstruction.
Parameters
rec reconstruction to generate
Definition at line 220 of file tests/fwTest/src/fwTest/generator/SeriesDB.cpp.
References fwTest::generator::Mesh::generateMesh(), and fwTest::generator::Image::generateRandomImage().
Referenced by createModelSeries(), and fwTest::generator::Object::generateResection().
The documentation for this class was generated from the following files:
tests/fwTest/include/fwTest/generator/SeriesDB.hpp
tests/fwTest/src/fwTest/generator/SeriesDB.cpp