fw4spl: fwMedDataTools::ModelSeries Class Reference
fwMedDataTools::ModelSeries Class Reference
This class contains helper to manipulate ::fwData::ModelSeries.
#include <ModelSeries.hpp>
Static Public Member Functions
static FWMEDDATATOOLS_API void addReconstruction (::fwMedData::ModelSeries::sptr &_modelSeries,::fwData::Reconstruction::sptr &_rec)
Add a mesh into a model series. A reconstruction for this mesh will be created.
static FWMEDDATATOOLS_API::fwData::Reconstruction::sptr createReconstructionFromMesh (const ::fwData::Mesh::sptr &_mesh, const std::string &_organName, const std::string &_structureType, const ::fwData::Color::sptr &_color=::fwData::Color::New(),::fwData::Material::RepresentationType _mode=::fwData::Material::SURFACE, bool _visible=true)
Create a reconstruction from a mesh.
static FWMEDDATATOOLS_API void addMesh (::fwMedData::ModelSeries::sptr &_modelSeries, const ::fwData::Mesh::sptr &_mesh, const std::string &_organName, const std::string &_structureType, const ::fwData::Color::sptr &_color=::fwData::Color::New(),::fwData::Material::RepresentationType _mode=::fwData::Material::SURFACE, bool _visible=true)
Add a mesh into a model series. A reconstruction for this mesh will be automatically created.
Detailed Description
This class contains helper to manipulate ::fwData::ModelSeries.
Definition at line 28 of file ools/include/fwMedDataTools/ModelSeries.hpp.
Member Function Documentation
void fwMedDataTools::ModelSeries::addMesh (::fwMedData::ModelSeries::sptr & _modelSeries, const ::fwData::Mesh::sptr & _mesh, const std::string & _organName, const std::string & _structureType, const ::fwData::Color::sptr & _color = ::fwData::Color::New(), ::fwData::Material::RepresentationType _mode = ::fwData::Material::SURFACE, bool _visible = true) static
Add a mesh into a model series. A reconstruction for this mesh will be automatically created.
Parameters
_modelSeries Model series where the mesh must be added.
_mesh Mesh that must be added
_organName Organ name to associate with the mesh
_structureType Structure type to associate with the mesh
_color Color of the material of the reconstruction.
_mode Representation mode of the material of the reconstruction.
_visible Visibility flag of the reconstruction.
Definition at line 17 of file ools/src/fwMedDataTools/ModelSeries.cpp.
References addReconstruction(), createReconstructionFromMesh(), and fwMedData::ModelSeries::s_RECONSTRUCTIONS_ADDED_SIG.
void fwMedDataTools::ModelSeries::addReconstruction (::fwMedData::ModelSeries::sptr & _modelSeries, ::fwData::Reconstruction::sptr & _rec) static
Add a mesh into a model series. A reconstruction for this mesh will be created.
Parameters
_modelSeries Model series where the mesh must be added.
_rec Reconstruction that must be added
Definition at line 63 of file ools/src/fwMedDataTools/ModelSeries.cpp.
Referenced by addMesh().
fwData::Reconstruction::sptr fwMedDataTools::ModelSeries::createReconstructionFromMesh (const ::fwData::Mesh::sptr & _mesh, const std::string & _organName, const std::string & _structureType, const ::fwData::Color::sptr & _color = ::fwData::Color::New(), ::fwData::Material::RepresentationType _mode = ::fwData::Material::SURFACE, bool _visible = true) static
Create a reconstruction from a mesh.
Parameters
_mesh Mesh that must be added
_organName Organ name to associate with the mesh
_structureType Structure type to associate with the mesh
_color Color of the material of the reconstruction.
_mode Representation mode of the material of the reconstruction.
_visible Visibility flag of the reconstruction.
Returns
Output reconstruction.
Definition at line 38 of file ools/src/fwMedDataTools/ModelSeries.cpp.
Referenced by addMesh().
The documentation for this class was generated from the following files:
ools/include/fwMedDataTools/ModelSeries.hpp
ools/src/fwMedDataTools/ModelSeries.cpp