fw4spl: fwVtkIO::BitmapImageReader Class Reference
fwVtkIO::BitmapImageReader Class Reference
Read a bitmap image.
#include <BitmapImageReader.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWVTKIO_API BitmapImageReader (::fwDataIO::reader::IObjectReader::Key key)
Constructor.
FWVTKIO_API ~BitmapImageReader ()
Destructor.
FWVTKIO_API void read () override
Reading operator.
FWVTKIO_API std::string extension () override
FWVTKIO_API std::shared_ptr< ::fwJobs::IJob > getJob () const override
Public Member Functions inherited from fwDataIO::reader::GenericObjectReader< ::fwData::Image >
GenericObjectReader ()
Constructor. Do nothing.
virtual ~GenericObjectReader ()
Destructor. Do nothing.
virtual void setObject (::fwTools::Object::sptr obj) override
m_object setter.
virtual std::shared_ptr< DataType > getConcreteObject ()
m_object getter.
Public Member Functions inherited from fwDataIO::reader::IObjectReader
virtual FWDATAIO_API::fwTools::Object::sptr getObject ()
m_object getter.
virtual FWDATAIO_API void setLocation (const ::fwData::location::ILocation::sptr _location)
m_location setter.
virtual FWDATAIO_API::fwData::location::ILocation::sptr getLocation ()
m_location getter.
FWDATAIO_API void cancel ()
Requests reader abortion.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwData::location::enableSingleFile< ::fwDataIO::reader::IObjectReader >
enableSingleFile (::fwDataIO::reader::IObjectReader *rw)
constructor
void setFile (ILocation::PathType path)
Set file system path.
ILocation::PathType getFile ()
Get file system path.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWVTKIO_API void getAvailableExtensions (std::vector< std::string > &ext)
Static Public Member Functions inherited from fwDataIO::reader::GenericObjectReader< ::fwData::Image >
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwDataIO::reader::IObjectReader
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwDataIO::reader::GenericObjectReader< ::fwData::Image >
typedef ::fwData::Image DataType
the object type related
Public Types inherited from fwDataIO::reader::IObjectReader
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< void() > CancelCallback
typedef ::fwDataIO::reader::factory::Key Key
Protected Member Functions inherited from fwDataIO::reader::IObjectReader
FWDATAIO_API IObjectReader ()
Constructor. Do nothing.
virtual FWDATAIO_API ~IObjectReader ()
Destructor. Do nothing.
Protected Attributes inherited from fwDataIO::reader::IObjectReader
::fwTools::Object::wptr m_object
Object result of reading process.
::fwData::location::ILocation::sptr m_location
Object location (file path, directory path, url, etc)
Detailed Description
Read a bitmap image.
Read a Bitmap Image using the VTK library
Definition at line 33 of file BitmapImageReader.hpp.
Member Function Documentation
std::string fwVtkIO::BitmapImageReader::extension () override virtual
Returns
The available file extensions for loading bitmap images.
Reimplemented from fwDataIO::reader::GenericObjectReader< ::fwData::Image >.
Definition at line 111 of file BitmapImageReader.cpp.
void fwVtkIO::BitmapImageReader::getAvailableExtensions (std::vector< std::string > & ext) static
Returns
A vector of the available bitmap extensions for the vtkImageReader2 class
Definition at line 125 of file BitmapImageReader.cpp.
Referenced by BitmapImageReader(), ioVTK::SImageSeriesReader::configureWithIHM(), ioVTK::SImageReader::configureWithIHM(), and ioVTK::SImageReader::loadImage().
fwJobs::IJob::sptr fwVtkIO::BitmapImageReader::getJob () const override virtual
Returns
internal job
Reimplemented from fwDataIO::reader::IObjectReader.
Definition at line 118 of file BitmapImageReader.cpp.
The documentation for this class was generated from the following files:
BitmapImageReader.hpp
BitmapImageReader.cpp