fw4spl: fwAtoms::Blob Class Reference
fwAtoms::Blob Class Reference
Representation of a buffer.
#include <Blob.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Blob)(::fwAtoms::Base))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwAtoms::factory::New< Blob >,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Blob)(::fwAtoms::Base)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
Blob (::fwAtoms::Base::Key key)
Constructor.
virtual ~Blob ()
Destructor.
virtual FWATOMS_API Base::sptr clone () const
Returns a clone object.
::fwAtoms::Base::AtomType type () const
returns Atom type
FWATOMS_API::fwMemory::BufferObject::sptr getBufferObject () const
buffer accessor.
FWATOMS_API void setBufferObject (const ::fwMemory::BufferObject::sptr &bo)
buffer accessor.
Public Member Functions inherited from fwAtoms::Base
__FWCORE_CLASS_TYPEDEFS ((Base)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Base)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
bool isValue () const
Test if the current base is a value or not (Value = {string;numeric;boolean})
bool isBoolean () const
Test if the current base is a boolean.
bool isNumeric () const
Test if the current base is a Numeric (real or integer)
bool isString () const
Test if the current base is a string.
bool isSequence () const
Test if the current base is a sequence.
bool isMapping () const
Test if the current base is a mapping.
bool isBlob () const
Test if the current base is a blob (a object with a buffer)
bool isObject () const
Test if the current base is an object (representation of fwData)
virtual FWATOMS_API std::string getString () const
Return the string representation of a value.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWATOMS_API Blob::sptr New (::fwMemory::BufferObject::sptr buffer)
create a new Blob shared ptr.
static FWATOMS_API Blob::sptr New (void *buffer, unsigned int size)
create a new Blob shared ptr.
Static Public Member Functions inherited from fwAtoms::Base
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes
::fwMemory::BufferObject::sptr m_bufferObject
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwAtoms::Base
enum AtomType {
BOOLEAN = 1, NUMERIC, STRING, OBJECT,
SEQUENCE, MAP, BLOB
}
typedef ::fwAtoms::factory::Key Key
Static Public Attributes inherited from fwAtoms::Base
static FWATOMS_API const std::string s_VERSION = "1"
Defines fwAtoms version.
Protected Member Functions inherited from fwAtoms::Base
Base ()
Constructor.
Detailed Description
Representation of a buffer.
A blob wraps a buffer
Definition at line 23 of file Blob.hpp.
Constructor & Destructor Documentation
fwAtoms::Blob::Blob (::fwAtoms::Base::Key key) inline
Constructor.
Parameters
key Private construction key
Definition at line 32 of file Blob.hpp.
Member Function Documentation
fwAtoms::Blob::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (::fwAtoms::factory::New< Blob > , (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Blob)(::fwAtoms::Base)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Blob)(fwAtoms::Base)).
fwMemory::BufferObject::sptr fwAtoms::Blob::getBufferObject () const
buffer accessor.
Returns
the a pointer to the first buffer element.
Definition at line 37 of file Blob.cpp.
Blob::sptr fwAtoms::Blob::New (::fwMemory::BufferObject::sptr buffer) static
create a new Blob shared ptr.
Parameters
buffer the buffer object
Definition at line 17 of file Blob.cpp.
Referenced by clone(), fwStructuralPatch::creator::fwMedData::ImageSeries1::create(), New(), and fwAtomsPatch::patcher::DefaultPatcher::processBase().
Blob::sptr fwAtoms::Blob::New (void * buffer, unsigned int size) static
create a new Blob shared ptr.
Parameters
buffer the buffer
size the buffer size
Definition at line 27 of file Blob.cpp.
References New().
void fwAtoms::Blob::setBufferObject (const ::fwMemory::BufferObject::sptr & bo)
buffer accessor.
Returns
the a pointer to the first buffer element.
Definition at line 44 of file Blob.cpp.
The documentation for this class was generated from the following files:
Blob.hpp
Blob.cpp