fw4spl: fwGdcmIO::reader::tid::MeasurementReport Class Reference
fwGdcmIO::reader::tid::MeasurementReport Class Reference
Measurement Report TID - This a root template.
#include <MeasurementReport.hpp>
Public Member Functions
FWGDCMIO_API MeasurementReport (const std::shared_ptr< const ::fwMedData::DicomSeries > &dicomSeries, const std::shared_ptr< ::gdcm::Reader > &reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const ::fwData::Image::sptr &image, const ::fwLog::Logger::sptr &logger)
Constructor.
virtual FWGDCMIO_API ~MeasurementReport ()
Destructor.
virtual FWGDCMIO_API void readSR (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > &root)
Create Measurement Report template root node.
Public Member Functions inherited from fwGdcmIO::reader::tid::TemplateID< ::fwData::Image >
FWGDCMIO_API TemplateID (const std::shared_ptr< const ::fwMedData::DicomSeries > &dicomSeries, const std::shared_ptr< ::gdcm::Reader > &reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > &instance, const std::shared_ptr< ::fwData::Image > &object, const ::fwLog::Logger::sptr &logger)
Constructor.
virtual FWGDCMIO_API ~TemplateID ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from fwGdcmIO::reader::tid::TemplateID< ::fwData::Image >
std::shared_ptr< const ::fwMedData::DicomSeries > m_dicomSeries
Dicom Series.
std::shared_ptr< ::gdcm::Reader > m_reader
GDCM Reader.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > m_instance
DICOM Instance.
std::shared_ptr< ::fwData::Image > m_object
FW4SPL Object.
::fwLog::Logger::sptr m_logger
Logger.
Detailed Description
Measurement Report TID - This a root template.
See also
TID t1tt1 FIXME: Set the final TID
Definition at line 25 of file reader/tid/MeasurementReport.hpp.
Constructor & Destructor Documentation
FWGDCMIO_API fwGdcmIO::reader::tid::MeasurementReport::MeasurementReport (const std::shared_ptr< const ::fwMedData::DicomSeries > & dicomSeries, const std::shared_ptr< ::gdcm::Reader > & reader, const std::shared_ptr< ::fwGdcmIO::container::DicomInstance > & instance, const ::fwData::Image::sptr & image, const ::fwLog::Logger::sptr & logger)
Constructor.
Parameters
[in] dicomSeries DicomSeries used to access computed tag values.
[in] reader GDCM reader that must be used to read series.
[in] instance DICOM instance used to share informations between modules
[in] image FW4SPL data object
[in] logger Logger
Member Function Documentation
void fwGdcmIO::reader::tid::MeasurementReport::readSR (const std::shared_ptr< ::fwGdcmIO::container::sr::DicomSRNode > & root) virtual
Create Measurement Report template root node.
Parameters
[in] root Root node
Definition at line 38 of file reader/tid/MeasurementReport.cpp.
References fwGdcmIO::container::sr::DicomSRNode::getCodedAttribute(), fwGdcmIO::container::sr::DicomSRNode::getSubNodeContainer(), fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_instance, fwGdcmIO::writer::tid::TemplateID< ::fwData::Image >::m_object, fwGdcmIO::reader::tid::Fiducial::readNode(), fwGdcmIO::reader::tid::Measurement::readNode(), and SPTR.
Referenced by fwGdcmIO::reader::ie::Document::readSR().
The documentation for this class was generated from the following files:
reader/tid/MeasurementReport.hpp
reader/tid/MeasurementReport.cpp