fw4spl: vtkSimpleMesh::RendererService Class Reference
vtkSimpleMesh::RendererService Class Reference
Renderer service.
#include <RendererService.hpp>
Public Types
typedef ::boost::shared_array
< double > SharedArray
typedef ::fwCom::Slot< void(SharedArray,
SharedArray, SharedArray)> UpdateCamPositionSlotType
typedef ::fwCom::Signal< void(SharedArray,
SharedArray, SharedArray) > CamUpdatedSignalType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((RendererService)(::fwRender::IRender))
VTKSIMPLEMESH_API RendererService () throw ()
Constructor.
virtual VTKSIMPLEMESH_API ~RendererService () throw ()
Destructor.
void updateCamPosition (SharedArray positionValue, SharedArray focalValue, SharedArray viewUpValue)
Slot to receive new camera information (position, focal, viewUp). Update camera with new information.
void notifyCamPositionUpdated ()
This method is used to notify that the VTK camera position is updated.
Static Public Attributes
static
VTKSIMPLEMESH_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_CAM_POSITION_SLOT = "updateCamPosition"
static
VTKSIMPLEMESH_APIconst::fwCom::Signals::SignalKeyType s_CAM_UPDATED_SIG = "camUpdated"
Protected Member Functions
virtual VTKSIMPLEMESH_API void starting () throw (fwTools::Failed)
Starting method.
virtual VTKSIMPLEMESH_API void configuring () throw (::fwTools::Failed)
Configuring method.
virtual VTKSIMPLEMESH_API void stopping () throw (fwTools::Failed)
Stopping method.
virtual VTKSIMPLEMESH_API void updating () throw (fwTools::Failed)
Updating method.
virtual VTKSIMPLEMESH_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Updating method (react on data modifications).
Protected Attributes
vtkRenderer * m_render
vtk renderer
Detailed Description
Renderer service.
Date:
2009.
Service rendering a fwData::Mesh using VTK.
Service registered details :
fwServicesRegisterMacro(::fwRender::IRender , ::vtkSimpleMesh::RendererService , ::fwData::Mesh)
Definition at line 40 of file vtkSimpleMesh/include/vtkSimpleMesh/RendererService.hpp.
Member Function Documentation
void vtkSimpleMesh::RendererService::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method.
XML configuration sample:
    <service impl="::vtkSimpleMesh::RendererService" type="::fwRender::IRender" autoConnect="yes" />
This method is used to configure the service. Initialize qt container.
Implements fwServices::IService.
Definition at line 141 of file vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::initialize().
void vtkSimpleMesh::RendererService::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Updating method (react on data modifications).
Parameters:
[in] _msg ::fwServices::ObjectMsg::csptr.
This method is used to update the vtk pipeline when the mesh is modified.
Reimplemented from fwServices::IService.
Definition at line 173 of file vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp.
References fwComEd::MeshMsg::NEW_MESH, OSLM_INFO, and fwVtkIO::helper::Mesh::toVTKMesh().
void vtkSimpleMesh::RendererService::starting () throw (fwTools::Failed) [protected, virtual]
Starting method.
This method is used to initialize the service. Initialize VTK renderer and qt containers
Implements fwServices::IService.
Definition at line 112 of file vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::create(), and m_render.
void vtkSimpleMesh::RendererService::stopping () throw (fwTools::Failed) [protected, virtual]
Stopping method.
Destroy VTK renderer and qt containers
Implements fwServices::IService.
Definition at line 148 of file vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::destroy(), m_render, and SLM_ASSERT.
void vtkSimpleMesh::RendererService::updating () throw (fwTools::Failed) [protected, virtual]
Updating method.
This method is used to update the service. Make a render if necessary
Implements fwServices::IService.
Definition at line 166 of file vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp.
The documentation for this class was generated from the following files:
vtkSimpleMesh/include/vtkSimpleMesh/RendererService.hpp
vtkSimpleMesh/src/vtkSimpleMesh/RendererService.cpp