fw4spl: uiReconstruction::RepresentationEditor Class Reference
uiReconstruction::RepresentationEditor Class Reference
RepresentationEditor service.
#include <RepresentationEditor.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((RepresentationEditor)(::gui::editor::IEditor))
UIRECONSTRUCTIONQT_API RepresentationEditor () throw ()
Constructor. Do nothing.
virtual UIRECONSTRUCTIONQT_API ~RepresentationEditor () throw ()
Destructor. Do nothing.
Protected Types
typedef
::fwRuntime::ConfigurationElement::sptr Configuration
Protected Slots
void onChangeRepresentation (int id)
void onChangeShading (int id)
void onShowNormals (int state)
Protected Member Functions
virtual void starting () throw (::fwTools::Failed)
This method launches the IEditor::starting method.
virtual void stopping () throw (::fwTools::Failed)
This method launches the IEditor::stopping method.
virtual void receiving (CSPTR(::fwServices::ObjectMsg) _msg) throw (::fwTools::Failed)
Management of observations (overrides)
virtual void updating () throw (::fwTools::Failed)
Perform some computations according to object (this service is attached to) attribute values and its internal state.
virtual void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual void configuring () throw (fwTools::Failed)
Configure the service before starting. Apply the configuration to service.
virtual void info (std::ostream &_sstream)
Overrides.
void notifyMaterial ()
void notifyMesh ()
Detailed Description
RepresentationEditor service.
Date:
2010.
Definition at line 35 of file RepresentationEditor.hpp.
Member Function Documentation
void uiReconstruction::RepresentationEditor::configuring () throw (fwTools::Failed) [protected, virtual]
Configure the service before starting. Apply the configuration to service.
See also:
configure()
Implements fwServices::IService.
Definition at line 167 of file RepresentationEditor.cpp.
References fwGui::IGuiContainerSrv::initialize(), and SLM_TRACE_FUNC.
void uiReconstruction::RepresentationEditor::swapping () throw (::fwTools::Failed) [protected, virtual]
Swap the service from associated object to another object.
See also:
swap()
Todo:
This method must be pure virtual
FIXME after code update for all services
This method must have in parameter the new object or the old ?
Reimplemented from fwServices::IService.
Definition at line 193 of file RepresentationEditor.cpp.
References updating().
void uiReconstruction::RepresentationEditor::updating () throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also:
update()
Implements fwServices::IService.
Definition at line 175 of file RepresentationEditor.cpp.
References SLM_ASSERT.
Referenced by starting(), and swapping().
The documentation for this class was generated from the following files:
RepresentationEditor.hpp
RepresentationEditor.cpp