fw4spl: fwData::Object Class Reference
fwData::Object Class Reference abstract
Base class for each data object.
#include <Object.hpp>
Classes
class Registrar
Class used to register a class factory in factory registry. This class defines also the object factory ('create')
Public Types
typedef ::fwData::factory::Key Key
typedef std::string FieldNameType
typedef std::vector< FieldNameType > FieldNameVectorType
typedef ::boost::unordered_map< FieldNameType,::fwData::Object::sptr > FieldMapType
typedef ::boost::unordered_map< ::fwData::Object::csptr,::fwData::Object::sptr > DeepCopyCacheType
Public Types inherited from fwTools::DynamicAttributes< ::fwData::Object >
typedef std::string AttrNameType
typedef std::shared_ptr< ::fwData::Object > AttrType
typedef std::vector< AttrNameType > AttrNameVectorType
typedef ::boost::reference_wrapper< AttrType > AttrRefType
typedef std::map< AttrNameType, AttrRefType > AttrMapType
typedef std::shared_ptr< const ::fwData::Object > ConstAttrType
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwTools::Object))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwTools::Object)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWDATA_API::fwData::Object::sptr getField (const FieldNameType &name,::fwData::Object::sptr defaultValue=::fwData::Object::sptr()) const
Returns a pointer of corresponding field (null if non exist).
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > getField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue) const
Returns a pointer of corresponding field.
template<typename DATA_TYPE >
std::shared_ptr< DATA_TYPE > setDefaultField (const FieldNameType &name, std::shared_ptr< DATA_TYPE > defaultValue)
Returns a pointer of corresponding field. If field did not exist, it is set to defaultValue if defaultValue is not null.
FWDATA_API::fwData::Object::csptr getConstField (const FieldNameType &name) const
Returns a pointer of corresponding field (null if non exist).
FWDATA_API const FieldMapType & getFields () const
Returns fields map.
FWDATA_API FieldNameVectorType getFieldNames () const
Returns vector of field names.
FWDATA_API void setField (const FieldNameType &name,::fwData::Object::sptr obj)
Register field with specified name. If the name does already exist, the matching field will be replaced.
FWDATA_API void setFields (const FieldMapType &fieldMap)
Replace the field map content.
FWDATA_API void removeField (const FieldNameType &name)
Removes field with specified name.
FWDATA_API void updateFields (const FieldMapType &fieldMap)
Updates the field map content with fieldMap. Duplicated name will be replaced.
virtual FWDATA_API void shallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void deepCopy (const ::fwData::Object::csptr &source)
Make a deep copy from the source Calling this method may invalidate any DumpLock, RescursiveLock or helper on the object. Prefer using fwData::Object::copy instead.
FWDATA_API void fieldShallowCopy (const ::fwData::Object::csptr &source)
A shallow copy of fields (objects in m_children)
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source)
A deep copy of fields (objects in m_children)
::fwCore::mt::ReadWriteMutex & getMutex ()
Returns the object's mutex.
Public Member Functions inherited from fwTools::Object
__FWCORE_CLASS_TYPEDEFS ((Object)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Object)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual ConstAttrType getConstAttribute (AttrNameType attrName) const
virtual AttrType getAttribute (AttrNameType attrName)
bool hasAttribute (AttrNameType attrName)
virtual void setAttribute (AttrNameType attrName, AttrType _obj)
virtual AttrNameVectorType getAttributeNames ()
virtual void __FWTOOLS_ATTRIBUTES_REGISTER_FUNC_NAME ()
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source)
return a copy of the source. if source is a null pointer, return a null pointer.
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes
FieldMapType m_fields
Fields.
::fwCore::mt::ReadWriteMutex m_mutex
Mutex to protect object access.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwTools::DynamicAttributes< ::fwData::Object >
AttrMapType __FWTOOLS_ATTRIBUTE_MAP_NAME
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Signals
typedef ::fwCom::Signal< void() > ModifiedSignalType
Type of signal m_sigModified.
typedef std::map< std::string,::fwData::Object::sptr > FieldsContainerType
Type of signal m_sigModified.
typedef ::fwCom::Signal< void(FieldsContainerType) > AddedFieldsSignalType
Type of signal when objects are added.
typedef ::fwCom::Signal< void(FieldsContainerType, FieldsContainerType) > ChangedFieldsSignalType
Type of signal when objects are changed (newObjects, oldObjects)
typedef ::fwCom::Signal< void(FieldsContainerType) > RemovedFieldsSignalType
Type of signal when objects are removed.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_MODIFIED_SIG = "modified"
Key in m_signals map of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_ADDED_FIELDS_SIG = "addedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_CHANGED_FIELDS_SIG = "changedFields"
Type of signal m_sigModified.
static FWDATA_APIconst::fwCom::Signals::SignalKeyType s_REMOVED_FIELDS_SIG = "removedFields"
Type of signal m_sigModified.
FWDATA_API void fieldDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
virtual FWDATA_API void cachedDeepCopy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)=0
Internal-use methods to implement Object's deepCopy.
static FWDATA_API::fwData::Object::sptr copy (const ::fwData::Object::csptr &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< const DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
template<typename DATA_TYPE >
static std::shared_ptr< DATA_TYPE > copy (const std::shared_ptr< DATA_TYPE > &source, DeepCopyCacheType &cache)
Internal-use methods to implement Object's deepCopy.
Additional Inherited Members
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
__FWCORE_CLASS_TYPEDEFS ((fwID))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((fwID)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Protected Member Functions inherited from fwTools::DynamicAttributes< ::fwData::Object >
virtual AttrRefType getAttributeRef (AttrNameType attrName)
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Base class for each data object.
Each object can optionally embed sub-object with string identifier. We name this concept a Field. An Object containing a field name "dummy" corresponds to having a labeledObject with label "dummy" and containing a specific Object. When accessing to this object with getField("dummy") we get the specific Object
Definition at line 48 of file core/fwData/include/fwData/Object.hpp.
Member Function Documentation
void fwData::Object::fieldDeepCopy (const ::fwData::Object::csptr & source)
A deep copy of fields (objects in m_children)
Parameters
[in] source source of the copy.
Definition at line 134 of file core/fwData/src/fwData/Object.cpp.
Referenced by scene2D::data::Viewport::cachedDeepCopy(), fwData::location::MultiFiles::cachedDeepCopy(), scene2D::data::Axis::cachedDeepCopy(), fwMedData::Equipment::cachedDeepCopy(), fwData::Material::cachedDeepCopy(), fwMedData::Study::cachedDeepCopy(), fwMedData::Patient::cachedDeepCopy(), fwData::Boolean::cachedDeepCopy(), fwData::Integer::cachedDeepCopy(), fwData::String::cachedDeepCopy(), fwData::Edge::cachedDeepCopy(), fwData::location::Folder::cachedDeepCopy(), fwData::Line::cachedDeepCopy(), fwData::location::SingleFile::cachedDeepCopy(), fwMedData::Series::cachedDeepCopy(), fwData::TransformationMatrix3D::cachedDeepCopy(), fwData::Plane::cachedDeepCopy(), fwData::Histogram::cachedDeepCopy(), fwData::ResectionDB::cachedDeepCopy(), fwData::Resection::cachedDeepCopy(), fwData::Float::cachedDeepCopy(), fwData::PlaneList::cachedDeepCopy(), fwData::Color::cachedDeepCopy(), fwData::PointList::cachedDeepCopy(), fwData::Reconstruction::cachedDeepCopy(), fwData::Point::cachedDeepCopy(), fwData::StructureTraitsDictionary::cachedDeepCopy(), fwData::Array::cachedDeepCopy(), fwData::Port::cachedDeepCopy(), scene2D::data::Event::cachedDeepCopy(), fwData::ReconstructionTraits::cachedDeepCopy(), fwData::Tag::cachedDeepCopy(), fwData::Node::cachedDeepCopy(), fwData::ROITraits::cachedDeepCopy(), fwData::Image::cachedDeepCopy(), fwMedData::SeriesDB::cachedDeepCopy(), fwData::List::cachedDeepCopy(), fwData::Vector::cachedDeepCopy(), fwData::Spline::cachedDeepCopy(), fwData::Composite::cachedDeepCopy(), fwData::TransferFunction::cachedDeepCopy(), fwData::Mesh::cachedDeepCopy(), fwData::ProcessObject::cachedDeepCopy(), fwData::StructureTraits::cachedDeepCopy(), and fwData::Graph::getCRefConnections().
void fwData::Object::fieldShallowCopy (const ::fwData::Object::csptr & source)
A shallow copy of fields (objects in m_children)
Parameters
[in] source source of the copy.
Definition at line 120 of file core/fwData/src/fwData/Object.cpp.
References setFields().
Referenced by fwData::Graph::getCRefConnections(), scene2D::data::Viewport::shallowCopy(), scene2D::data::Axis::shallowCopy(), fwMedData::Equipment::shallowCopy(), fwMedData::Study::shallowCopy(), fwData::Material::shallowCopy(), fwMedData::Patient::shallowCopy(), fwData::Boolean::shallowCopy(), fwData::Integer::shallowCopy(), fwData::String::shallowCopy(), fwData::Edge::shallowCopy(), fwData::location::Folder::shallowCopy(), fwData::Line::shallowCopy(), fwData::location::SingleFile::shallowCopy(), fwMedData::Series::shallowCopy(), fwData::TransformationMatrix3D::shallowCopy(), fwData::Plane::shallowCopy(), fwData::Histogram::shallowCopy(), fwData::ResectionDB::shallowCopy(), fwData::Resection::shallowCopy(), fwData::Float::shallowCopy(), fwData::PlaneList::shallowCopy(), fwData::PointList::shallowCopy(), fwData::Reconstruction::shallowCopy(), fwData::Color::shallowCopy(), fwData::Point::shallowCopy(), fwData::StructureTraitsDictionary::shallowCopy(), fwData::Port::shallowCopy(), scene2D::data::Event::shallowCopy(), fwData::Node::shallowCopy(), fwData::Tag::shallowCopy(), fwData::Image::shallowCopy(), fwMedData::SeriesDB::shallowCopy(), fwData::List::shallowCopy(), fwData::Vector::shallowCopy(), fwData::Composite::shallowCopy(), fwData::TransferFunction::shallowCopy(), fwData::Mesh::shallowCopy(), and fwData::ProcessObject::shallowCopy().
fwData::Object::csptr fwData::Object::getConstField (const FieldNameType & name) const
Returns a pointer of corresponding field (null if non exist).
Parameters
[in] name Field name
Returns
null sptr if field is not found
Definition at line 58 of file core/fwData/src/fwData/Object.cpp.
References getField().
fwData::Object::sptr fwData::Object::getField (const FieldNameType & name, ::fwData::Object::sptr defaultValue = ::fwData::Object::sptr()) const
Returns a pointer of corresponding field (null if non exist).
Parameters
[in] name Field name
[in] defaultValue Default value
Returns
defaultValue if field is not found
Definition at line 45 of file core/fwData/src/fwData/Object.cpp.
References m_fields.
Referenced by fwComEd::fieldHelper::MedicalImageHelpers::checkImageSliceIndex(), and getConstField().
template<typename DATA_TYPE > std::shared_ptr< DATA_TYPE > fwData::Object::getField (const FieldNameType & name) const
Returns a pointer of corresponding field.
Parameters
[in] name Field name
Returns
pointer to corresponding field, nullptr if field is not found.
Definition at line 283 of file core/fwData/include/fwData/Object.hpp.
References SPTR.
template<typename DATA_TYPE > std::shared_ptr< DATA_TYPE > fwData::Object::getField (const FieldNameType & name, std::shared_ptr< DATA_TYPE > defaultValue) const
Returns a pointer of corresponding field.
Parameters
[in] name Field name
[in] defaultValue Default value
Returns
pointer to corresponding field, defaultValue if field is not found.
Definition at line 294 of file core/fwData/include/fwData/Object.hpp.
References SPTR.
void fwData::Object::removeField (const FieldNameType & name)
Removes field with specified name.
Parameters
[in] name Field name
Definition at line 101 of file core/fwData/src/fwData/Object.cpp.
References m_fields, and OSLM_ASSERT.
template<typename DATA_TYPE > std::shared_ptr< DATA_TYPE > fwData::Object::setDefaultField (const FieldNameType & name, std::shared_ptr< DATA_TYPE > defaultValue)
Returns a pointer of corresponding field. If field did not exist, it is set to defaultValue if defaultValue is not null.
Parameters
[in] name Field name
[in] defaultValue default return value if field was not found
Returns
pointer to corresponding field.
Definition at line 305 of file core/fwData/include/fwData/Object.hpp.
References SPTR.
void fwData::Object::setField (const FieldNameType & name, ::fwData::Object::sptr obj)
Register field with specified name. If the name does already exist, the matching field will be replaced.
Parameters
[in] name Field name
[in] obj Field
Definition at line 83 of file core/fwData/src/fwData/Object.cpp.
References m_fields.
Referenced by fieldDeepCopy(), and fwComEd::parser::Object::updating().
void fwData::Object::shallowCopy (const ::fwData::Object::csptr & source) virtual
A shallow copy of fields (objects in m_children)
Parameters
[in] source source of the copy.
Reimplemented in fwMedData::SeriesDB, scene2D::data::Event, fwMedData::ModelSeries, fwMedData::ActivitySeries, fwMedData::ImageSeries, fwMedData::Series, fwMedData::Patient, fwMedData::Study, scene2D::data::Axis, fwMedData::Equipment, uiMedData::InsertSeries, and scene2D::data::Viewport.
Definition at line 154 of file core/fwData/src/fwData/Object.cpp.
References getClassname(), and SLM_FATAL.
The documentation for this class was generated from the following files:
core/fwData/include/fwData/Object.hpp
core/fwData/src/fwData/Object.cpp