fw4spl: fwGui::registrar::ViewRegistrar Class Reference
fwGui::registrar::ViewRegistrar Class Reference
Defines the generic view manager for IHM.
#include <ViewRegistrar.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWGUI_API ViewRegistrar (const std::string &sid)
Constructor.
virtual FWGUI_API ~ViewRegistrar ()
Destructor. Do nothing.
virtual FWGUI_API::fwGui::container::fwContainer::sptr getParent ()
virtual FWGUI_API void setParent (std::string wid)
virtual FWGUI_API void initialize (::fwRuntime::ConfigurationElement::sptr configuration)
Initialize managers.
virtual FWGUI_API void manage (std::vector< ::fwGui::container::fwContainer::sptr > subViews)
Starting view manager. All services managed in local subViews and with start="yes" in configuration will be started.
virtual FWGUI_API void manageMenuBar (::fwGui::container::fwMenuBar::sptr menuBar)
Register menu bar. If start="yes" in configuration the menu bar services will be started.
virtual FWGUI_API void manageToolBar (::fwGui::container::fwToolBar::sptr toolBar)
Register tool bar. If start="yes" in configuration the tool bar services will be started.
virtual FWGUI_API void unmanage ()
Stopping view manager. All services managed in local subViews will be stopped.
virtual FWGUI_API void unmanageToolBar ()
Stopping view manager. ToolBar service will be stopped.
virtual FWGUI_API void unmanageMenuBar ()
Stopping view manager. MenuBar service will be stopped.
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef std::map< std::string, std::pair< unsigned int, bool > > SIDContainerMapType
typedef std::map< std::string, unsigned int > WIDContainerMapType
typedef std::pair< std::string, bool > SIDMenuBarPairType
typedef std::pair< std::string, bool > SIDToolBarPairType
Protected Attributes
SIDContainerMapType m_sids
All services ID managed and associated with pair containing: subViews index vector and boolean describing if is started by the manager.
WIDContainerMapType m_wids
All windows containers ID managed (and associated with subViews index vector).
SIDMenuBarPairType m_menuBarSid
Menu bar service ID associate with this ViewRegistrar.
SIDToolBarPairType m_toolBarSid
Tool bar service ID associate with this ViewRegistrar.
std::string m_parentWid
::fwGui::container::fwContainer::sptr m_parentContainer
std::string m_sid
Main service ID associate with this ViewRegistrar.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
Defines the generic view manager for IHM.
Date
2009-2010.
Definition at line 31 of file ViewRegistrar.hpp.
Member Function Documentation
void fwGui::registrar::ViewRegistrar::initialize (::fwRuntime::ConfigurationElement::sptr configuration) virtual
Initialize managers.
Example of configuration
 <service uid="subView1" type="::gui::view::IView" impl="::gui::view::SDefaultView" autoConnect="no" >
     <gui>
         <layout type="::fwGui::LineLayoutManager" >
             <orientation value="horizontal" />
             <view caption="view3" />
             <view caption="view4" />
             <view caption="view5" />
         </layout>
         <toolBar />
         <menuBar />
     </gui>
     <registry>
         <parent wid="myView" />
         <toolBar sid="toolbar" start="yes" />
         <menuBar sid="menubar" start="yes" />
         <view sid="subView3" start="yes" />
         <view wid="subView4" />
         <view wid="subView5" />
     </registry>
 </service>
<parent wid="myView" /> : This section isn't mandatory. When the parent section is present, the wid attribute is used to find its parent container. Otherwise, the service uid is used to find its parent container.
<toolBar sid="toolbar1" start="yes" /> : This section isn't mandatory.
sid (mandatory): the tool bar identifier.
start = {yes| no} (default value no): indicate if the tool bar service must be started by the service.
<menuBar sid="menubar1" start="yes" /> : This section isn't mandatory.
sid (mandatory): the menu bar identifier.
start = {yes| no} (default value no): indicate if the menu bar service must be started by the service.
<view sid="subView3" start="yes" /> : define the service of the view to add in the container.
sid (mandatory): the service identifier.
start = {yes| no} (default value no): indicate if the view service must be started by the service.
<view wid="subView4" /> : reserve a sub container for the view in the parent container with the name "subView4". The service which want to use this sub container will have define a parent with <parent wid="subView4" />.
wid (mandatory): the window identifier.
Warning
The number of view item in the gui section must be equal or greater than in the registry section.
The order of the view in each section (gui and registry) must be the same.
For example: the view caption "view3" will be connected with the service which have the sid = "subView3" (It could also be a wid).
Definition at line 65 of file ViewRegistrar.cpp.
References m_menuBarSid, m_sids, m_toolBarSid, m_wids, OSLM_ASSERT, and SLM_ASSERT.
void fwGui::registrar::ViewRegistrar::manage (std::vector< ::fwGui::container::fwContainer::sptr > subViews) virtual
Starting view manager. All services managed in local subViews and with start="yes" in configuration will be started.
Precondition
ViewRegistrar must be initialized before.
sub containers must be instanced before.
Definition at line 154 of file ViewRegistrar.cpp.
References fwTools::fwID::exist(), m_sids, m_wids, OSLM_ASSERT, fwGui::GuiRegistry::registerSIDContainer(), fwGui::GuiRegistry::registerWIDContainer(), and SLM_TRACE.
The documentation for this class was generated from the following files:
ViewRegistrar.hpp
ViewRegistrar.cpp