fw4spl: fwActivities::builder::ActivitySeries Class Reference
fwActivities::builder::ActivitySeries Class Reference
Defines the default builder for the data ActivitySeries.
#include <ActivitySeries.hpp>
Public Types
typedef std::string RegistryKeyType
Public Member Functions
fwCoreClassDefinitionsWithFactoryMacro ((ActivitySeries)(::fwActivities::IBuilder),(()),::fwActivities::builder::factory::New< ActivitySeries >)
FWACTIVITIES_API ActivitySeries (::fwActivities::IBuilder::Key key)
Constructor. Do nothing.
virtual FWACTIVITIES_API ~ActivitySeries ()
Destructor. Do nothing.
virtual
FWACTIVITIES_API::fwMedData::ActivitySeries::sptr buildData (const ::fwActivities::registry::ActivityInfo &activityInfo, SPTR(::fwData::Vector) currentSelection) const
Build an ActivitySeries with required data present in currentSelection and defined in configuration. returns specific data ActivitySeries for the specified Activity, or a null pointer if the builder canceled the activity creation.
Detailed Description
Defines the default builder for the data ActivitySeries.
Date:
2013.
Definition at line 26 of file fwActivities/include/fwActivities/builder/ActivitySeries.hpp.
Member Function Documentation
fwMedData::ActivitySeries::sptr fwActivities::builder::ActivitySeries::buildData (const ::fwActivities::registry::ActivityInfo & activityInfo, SPTR(::fwData::Vector) currentSelection) const [virtual]
Build an ActivitySeries with required data present in currentSelection and defined in configuration. returns specific data ActivitySeries for the specified Activity, or a null pointer if the builder canceled the activity creation.
Parameters:
[in] activityInfo a structure which contains all the Activity configuration
[in] currentSelection a vector which contains current selected data.
Returns:
ActivitySeries or null
Implements fwActivities::IBuilder.
Reimplemented in fwActivities::builder::ActivitySeriesInitData.
Definition at line 73 of file fwActivities/src/fwActivities/builder/ActivitySeries.cpp.
References fwData::Object::copy(), fwTools::UUID::generateUUID(), fwTools::getDate(), fwTools::getTime(), OSLM_ASSERT, and SLM_ASSERT.
The documentation for this class was generated from the following files:
fwActivities/include/fwActivities/builder/ActivitySeries.hpp
fwActivities/src/fwActivities/builder/ActivitySeries.cpp