fw4spl: ioAtoms::SWriter Class Reference
ioAtoms::SWriter Class Reference
Atoms writer. Service to write an fwData medical data converted in fwAtoms.
#include <SWriter.hpp>
Public Types
typedef ::fwCom::Signal< void(::fwJobs::IJob::sptr) > JobCreatedSignalType
Signal type for job creation.
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef ::boost::shared_future< void > SharedFutureType
Slot to call start method.
typedef ::boost::packaged_task< void > PackagedTaskType
Slot to call start method.
typedef ::boost::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Public Member Functions
virtual bool isA (const std::string &type) const
IOATOMS_API SWriter ()
Does nothing.
virtual IOATOMS_API ~SWriter () throw ()
Does nothing.
IOATOMS_API void configureWithIHM ()
Propose to create a medical data file.
Public Member Functions inherited from io::IWriter
IO_APIconst::boost::filesystem::path & getFile () const
Returns the file path setted by user or setted during service configuration.
IO_API void setFile (const ::boost::filesystem::path &file)
Sets file path.
IO_APIconst::io::LocationsType & getFiles () const
Returns file paths setted by user or setted during service configuration.
IO_API void setFiles (const ::io::LocationsType &files)
Sets file paths.
IO_APIconst::boost::filesystem::path & getFolder () const
Returns folder path setted by user or setted during service configuration.
IO_API void clearLocations ()
Clear any location set by the setFile/setFiles/setFolder setter.
IO_APIconst::io::LocationsType & getLocations () const
Returns file/files/folder paths setted by user or setted during service configuration.
IO_API void setFolder (const ::boost::filesystem::path &folder)
Sets folder path.
IO_API bool hasLocationDefined () const
Returns if a location has been defined (by the configuration process or directly by user)
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const throw ()
Return the global process status.
FWSERVICES_API bool isStarted () const throw ()
Test if the service is started or not.
FWSERVICES_API bool isStopped () const throw ()
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const throw ()
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const throw ()
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const OutputMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from io::IWriter
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static FWSERVICES_API void setVersion (int version)
static FWSERVICES_API bool isVersion2 ()
Streaming a service.
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef std::map< std::string, std::string > FileExtension2NameType
Maps file extension to format name.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Protected Member Functions
IOATOMS_API void configuring () throw (::fwTools::Failed)
Configures the writer.
IOATOMS_API void starting () throw (::fwTools::Failed)
Does nothing.
IOATOMS_API void stopping () throw (::fwTools::Failed)
Does nothing.
IOATOMS_API void updating () throw (::fwTools::Failed)
Convert fwData to fwAtoms, and apply the writer chosen from file extension.
IOATOMS_API::io::IOPathType getIOPathType () const
Returns managed path type, here service manages only single file.
bool versionSelection ()
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key) throw (::fwTools::Failed)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void reconfiguring () throw (::fwTools::Failed)
Reconfigure the service activity when is started.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
virtual FWSERVICES_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated objects signals, this method is used for obj/srv auto connection.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Attributes
bool m_useAtomsPatcher
To activate atom patcher.
std::string m_exportedVersion
Selected exported version of atom.
std::string m_context
Defines context of data.
std::string m_version
Current version of format.
std::set< std::string > m_allowedExts
Allowed file extensions.
FileExtension2NameType m_customExts
Maps custom extensions to known format.
FileExtension2NameType m_allowedExtLabels
Labels shown in file dialog for each allowed extension.
JobCreatedSignalType::sptr m_sigJobCreated
Signal emitted when job created.
std::string m_selectedExtension
Extension selected in file dialog.
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Atoms writer. Service to write an fwData medical data converted in fwAtoms.
Date
2013
Definition at line 31 of file SWriter.hpp.
Member Function Documentation
void ioAtoms::SWriter::configuring () throw (::fwTools::Failed) protected virtual
Configures the writer.
 <config>
  <patcher context="..." version="..." />
  <archive backend="json">
      <extension>.j</extension>
  </archive>
  <archive backend="jsonz">
      <extension>.vpz</extension>
  </archive>
  <extensions>
      <extension label="XML">.xml</extension>
      <extension label="Zipped XML>.xmlz</extension>
      <extension>.f4s</extension>
      <extension>.j</extension>
      <extension label="Medical workspace">.mw</extension>
      <extension>.vpz</extension>
  </extensions>
 </config>
archive : defines custom file extensions. The file to be saved with an extension given in 'archive' tag will be written with the given backend in archive tag (the 'backend' attribute is mandatory). Extensions must begin with '.'. Available 'backend' values are json, xml, jsonz and xmlz.
extensions : defines available extensions displayed in dialog to save file. If the 'extensions' is empty or not specified, all the extensions (.json, .xml, .jsonz, .xmlz extensions and custom extensions) are available. The attribute label (not mandatory) allows to display a label in front of extension when the file dialog is shown.
See also
io::IWriter
Exceptions
fwTools::Failed
Reimplemented from io::IWriter.
Definition at line 83 of file SWriter.cpp.
References io::IWriter::configuring(), m_allowedExtLabels, m_allowedExts, fwServices::IService::m_configuration, m_context, m_customExts, m_exportedVersion, m_useAtomsPatcher, m_version, OSLM_ASSERT, ioAtoms::SReader::s_EXTENSIONS, SLM_ASSERT, and SPTR.
void ioAtoms::SWriter::updating () throw (::fwTools::Failed) protected virtual
Convert fwData to fwAtoms, and apply the writer chosen from file extension.
Note
Data is locked (mutex) recursively during writing
Implements fwServices::IService.
Definition at line 209 of file SWriter.cpp.
References fwJobs::IJob::cancelRequested(), fwJobs::IJob::done(), fwJobs::IJob::doneWork(), io::IWriter::getFile(), io::IWriter::hasLocationDefined(), m_allowedExts, fwServices::IService::m_associatedWorker, m_context, m_customExts, m_exportedVersion, m_selectedExtension, m_sigJobCreated, m_useAtomsPatcher, m_version, fwJobs::Job::New(), fwJobs::Aggregator::New(), OSLM_ERROR, fwGui::Cursor::setCursor(), fwGui::dialog::MessageDialog::showMessageDialog(), and fwAtomsPatch::PatchingManager::transformTo().
bool ioAtoms::SWriter::versionSelection () protected
Proposes a gui to select available exports (set m_exportedVersion). Returns false if user cancel the selection.
Definition at line 168 of file SWriter.cpp.
References fwAtomsPatch::VersionsManager::getDefault(), m_context, m_exportedVersion, m_version, fwGui::dialog::SelectorDialog::setMessage(), fwGui::dialog::SelectorDialog::setSelections(), fwGui::dialog::SelectorDialog::setTitle(), and fwGui::dialog::SelectorDialog::show().
Referenced by configureWithIHM().
The documentation for this class was generated from the following files:
SWriter.hpp
SWriter.cpp