fw4spl: fwTools::TypeInfo Class Reference
fwTools::TypeInfo Class Reference
Purpose: offer a first-class, comparable wrapper over std::type_info (but copy construcible)
#include <TypeInfo.hpp>
Public Member Functions
FWTOOLS_API TypeInfo ()
default constructor
FWTOOLS_API TypeInfo (const std::type_info &)
copy constructor
FWTOOLS_API TypeInfo & operator= (const TypeInfo &ti)
copy method
FWTOOLS_API const std::type_info & type_info () const
access for the wrapped std::type_info
FWTOOLS_API operator const std::type_info & () const
cast operator TypeInfo -> std::type_info
FWTOOLS_API bool before (const TypeInfo &rhs) const
compatibility functions (std::type_info like)
FWTOOLS_API const char * name () const
compatibility functions (std::type_info like)
Detailed Description
Purpose: offer a first-class, comparable wrapper over std::type_info (but copy construcible)
Date
2007-2009.
Code imported from Loki-Library and adapted for FW4SPL
Definition at line 25 of file TypeInfo.hpp.
Member Function Documentation
bool fwTools::TypeInfo::before (const TypeInfo & rhs) const
compatibility functions (std::type_info like)
Returns
true iff TypeInfo is "before" an other, (ordering is defined as std::type_info::before())
Definition at line 33 of file TypeInfo.cpp.
References SLM_ASSERT.
const char * fwTools::TypeInfo::name () const
compatibility functions (std::type_info like)
Returns
the lexical name of the typeinfo (= td::type_info::name())
Definition at line 46 of file TypeInfo.cpp.
References SLM_ASSERT.
FWTOOLS_API fwTools::TypeInfo::operator const std::type_info & () const inline
cast operator TypeInfo -> std::type_info
Returns
a const reference on the embedded std::type_info
Definition at line 52 of file TypeInfo.hpp.
TypeInfo & fwTools::TypeInfo::operator= (const TypeInfo & ti)
copy method
Parameters
[in] ti the TypeInfo to copy
Returns
the copied TypeInfo
Definition at line 54 of file TypeInfo.cpp.
References type_info().
const std::type_info & fwTools::TypeInfo::type_info () const
access for the wrapped std::type_info
Returns
a const reference on the embedded std::type_info
Definition at line 40 of file TypeInfo.cpp.
References SLM_ASSERT.
Referenced by fwTools::getString(), and operator=().
The documentation for this class was generated from the following files:
TypeInfo.hpp
TypeInfo.cpp