fw4spl: fwDataTools::helper::Vector Class Reference
fwDataTools::helper::Vector Class Reference
Defines an helper to modify an fwData::Vector and create in parallel the message to announce this modification.
#include <Vector.hpp>
Public Member Functions
FWDATATOOLS_API Vector (::fwData::Vector::wptr vector)
Constructor. Initialize parameters.
FWDATATOOLS_API ~Vector ()
Destrucotr. Do nothing.
FWDATATOOLS_API void add (::fwData::Object::sptr _newObject)
Add an object in the vector.
FWDATATOOLS_API void remove (::fwData::Object::sptr _oldObject)
Remove an object in the vector.
FWDATATOOLS_API void clear ()
Clear all objects in the vector.
FWDATATOOLS_API void notify ()
Send the signal of modification.
Detailed Description
Defines an helper to modify an fwData::Vector and create in parallel the message to announce this modification.
Definition at line 22 of file ools/include/fwDataTools/helper/Vector.hpp.
Member Function Documentation
void fwDataTools::helper::Vector::add (::fwData::Object::sptr _newObject)
Add an object in the vector.
Parameters
[in] _newObject object to add in the vector
Prepare the signal to announce the modification.
Definition at line 39 of file ools/src/fwDataTools/helper/Vector.cpp.
References OSLM_ASSERT.
Referenced by ctrlSelection::SManage::addOrSwap(), ctrlSelection::SManage::clear(), and uiMedDataQt::editor::SSelector::onSelectedSeries().
void fwDataTools::helper::Vector::clear ()
Clear all objects in the vector.
Prepare the signal to announce the modification.
Definition at line 69 of file ools/src/fwDataTools/helper/Vector.cpp.
Referenced by ctrlSelection::SManage::clear().
void fwDataTools::helper::Vector::remove (::fwData::Object::sptr _oldObject)
Remove an object in the vector.
Parameters
[in] _oldObject object to remove from the vector.
Prepare the signal to announce the modification.
Definition at line 53 of file ools/src/fwDataTools/helper/Vector.cpp.
References OSLM_ASSERT.
Referenced by uiMedDataQt::editor::SSelector::onSelectedSeries(), ctrlSelection::SManage::remove(), and ctrlSelection::SManage::removeIfPresent().
The documentation for this class was generated from the following files:
ools/include/fwDataTools/helper/Vector.hpp
ools/src/fwDataTools/helper/Vector.cpp