fw4spl: fwGuiQt::dialog::LocationDialog Class Reference
fwGuiQt::dialog::LocationDialog Class Reference
Defines the generic file/folder dialog for IHM.
#include <LocationDialog.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWGUIQT_API LocationDialog (::fwGui::GuiBaseObject::Key key)
FWGUIQT_API::fwData::location::ILocation::sptr show ()
FWGUIQT_API void setType (::fwGui::dialog::ILocationDialog::Types type)
FWGUIQT_API::fwGui::dialog::ILocationDialog & setOption (::fwGui::dialog::ILocationDialog::Options option)
FWGUIQT_API void addFilter (const std::string &filterName, const std::string &wildcardList)
specify some filtering when browsing files:
Public Member Functions inherited from fwGui::dialog::ILocationDialog
virtual FWGUI_API void setTitle (const std::string &title)
set the title for the dialog
virtual FWGUI_API const std::string & getTitle ()
returns the title for the dialog
virtual FWGUI_API void setDefaultLocation (::fwData::location::ILocation::sptr loc)
set the initial location for the dialog
virtual FWGUI_APIconst::boost::filesystem::path getDefaultLocation ()
get the default location for the dialog (from preferences or specified by user)
virtual FWGUI_API void saveDefaultLocation (::fwData::location::ILocation::sptr loc)
save the specified default location for the dialog in preferences (if available)
virtual FWGUI_API void setType (Types type)=0
set the type of location for the dialog (SINGLE_FILE, FORLDER, MULTI_FILES)
virtual FWGUI_API ILocationDialog & setOption (Options option)=0
allow to set option to the file dialog mode=READ/WRITE , check=FILE_MUST_EXIST
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::dialog::ILocationDialog
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
QString fileFilters ()
helper to transform m_filters into qt encoding ("BMP and GIF files (*.bmp *.gif);;PNG files (*.png)"
FWGUIQT_API std::string getCurrentSelection () const
Gets the current extension file selection.
Protected Member Functions inherited from fwGui::dialog::ILocationDialog
FWGUI_API void readConfig ()
FWGUI_API void writeConfig ()
FWGUI_API::fwData::Composite::sptr getPreferenceUI ()
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Protected Attributes
::fwGui::dialog::ILocationDialog::Options m_style
::fwGui::dialog::ILocationDialog::Types m_type
std::vector< std::pair< std::string, std::string > > m_filters
std::string m_wildcard
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwGui::dialog::ILocationDialog
enum Options { NONE = 0, READ = 1 << 1, WRITE = 1 << 2, FILE_MUST_EXIST = 1 << 3 }
enum Types { SINGLE_FILE, FOLDER, MULTI_FILES }
typedef std::string FactoryRegistryKeyType
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Static Public Attributes inherited from fwGui::dialog::ILocationDialog
static FWGUI_API const FactoryRegistryKeyType REGISTRY_KEY = "::fwGui::dialog::LocationDialog"
this unique key should be used for all factory for specific LocationDialog(qt,wx,...)
static FWGUI_API const std::string SOFTWARE_UI = "SOFTWARE_UI"
static FWGUI_API const std::string DLG_DEFAULT_LOCATION = "DLG_DEFAULT_LOCATION"
Detailed Description
Defines the generic file/folder dialog for IHM.
Date
2009-2010.
Definition at line 38 of file t/include/fwGuiQt/dialog/LocationDialog.hpp.
Member Function Documentation
void fwGuiQt::dialog::LocationDialog::addFilter (const std::string & filterName, const std::string & wildcardList) virtual
specify some filtering when browsing files:
Parameters
[in] filterName a string that will be displayed as filter name
[in] wildcardList a string of extension (glob syntax) separated by spaces example : addFilter("images","*.png *.jpg")
Implements fwGui::dialog::ILocationDialog.
Definition at line 176 of file t/src/fwGuiQt/dialog/LocationDialog.cpp.
fwData::location::ILocation::sptr fwGuiQt::dialog::LocationDialog::show () virtual
Display the dialog
Returns
the ILocation selected or null sptr if user cancel the operation
Implements fwGui::dialog::ILocationDialog.
Definition at line 43 of file t/src/fwGuiQt/dialog/LocationDialog.cpp.
References fwGui::dialog::LocationDialog::getDefaultLocation(), fwGui::dialog::LocationDialog::getTitle(), fwGui::dialog::LocationDialog::setOption(), fwGui::dialog::LocationDialog::setType(), and SLM_ASSERT.
The documentation for this class was generated from the following files:
t/include/fwGuiQt/dialog/LocationDialog.hpp
t/src/fwGuiQt/dialog/LocationDialog.cpp