fw4spl: vtkCompositeMesh::RendererService Class Reference
vtkCompositeMesh::RendererService Class Reference
Renderer service.
#include <RendererService.hpp>
Public Types
typedef ::boost::shared_array
< double > SharedArray
typedef ::fwCom::Slot< void(SharedArray,
SharedArray, SharedArray)> UpdateCamPositionSlotType
typedef ::fwCom::Signal< void(SharedArray,
SharedArray, SharedArray) > CamUpdatedSignalType
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((RendererService)(::fwRender::IRender))
VTKCOMPOSITEMESH_API RendererService () throw ()
Constructor.
virtual VTKCOMPOSITEMESH_API ~RendererService () throw ()
Destructor.
void notifyCamPositionUpdated ()
This method is used to notify that the VTK camera position is updated.
virtual VTKCOMPOSITEMESH_API void updateCamPosition (SharedArray positionValue, SharedArray focalValue, SharedArray viewUpValue)
Slot to receive new camera information (position, focal, viewUp). Update camera with new information.
Static Public Attributes
static
VTKCOMPOSITEMESH_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_CAM_POSITION_SLOT = "updateCamPosition"
static
VTKCOMPOSITEMESH_APIconst::fwCom::Signals::SignalKeyType s_CAM_UPDATED_SIG = "camUpdated"
Protected Member Functions
virtual VTKCOMPOSITEMESH_API void starting () throw (fwTools::Failed)
Starting method.
virtual VTKCOMPOSITEMESH_API void configuring () throw (::fwTools::Failed)
Configuring method.
virtual VTKCOMPOSITEMESH_API void stopping () throw (fwTools::Failed)
Stopping method.
virtual VTKCOMPOSITEMESH_API void updating () throw (fwTools::Failed)
Updating method.
virtual VTKCOMPOSITEMESH_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Receiving method (react on data modifications).
Protected Attributes
vtkRenderer * m_render
vtk renderer
Detailed Description
Renderer service.
Date:
2009.
Service rendering fwData::Mesh contained in a fwData::Composite using VTK.
Service registered details :
fwServicesRegisterMacro(::fwRender::IRender , ::vtkCompositeMesh::RendererService , ::fwData::Composite)
Definition at line 43 of file vtkCompositeMesh/include/vtkCompositeMesh/RendererService.hpp.
Member Function Documentation
void vtkCompositeMesh::RendererService::configuring () throw (::fwTools::Failed) [protected, virtual]
Configuring method.
XML configuration sample:
    <service impl="::vtkCompositeMesh::RendererService" type="::fwRender::IRender" autoConnect="yes" />
This method is used to configure the service. Initialize qt container.
Implements fwServices::IService.
Definition at line 129 of file vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::initialize().
void vtkCompositeMesh::RendererService::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Receiving method (react on data modifications).
Parameters:
[in] _msg ::fwServices::ObjectMsg::csptr.
This method is used to update the vtk pipeline when the mesh is modified.
Reimplemented from fwServices::IService.
Definition at line 162 of file vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp.
References fwComEd::MeshMsg::NEW_MESH.
void vtkCompositeMesh::RendererService::starting () throw (fwTools::Failed) [protected, virtual]
Starting method.
This method is used to initialize the service. Initialize VTK renderer and create qt containers
Implements fwServices::IService.
Definition at line 113 of file vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::create(), and m_render.
void vtkCompositeMesh::RendererService::stopping () throw (fwTools::Failed) [protected, virtual]
Stopping method.
Destroy VTK renderer and containers
Implements fwServices::IService.
Definition at line 136 of file vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp.
References fwGui::IGuiContainerSrv::destroy(), m_render, and SLM_ASSERT.
void vtkCompositeMesh::RendererService::updating () throw (fwTools::Failed) [protected, virtual]
Updating method.
This method is used to update the service. Make a render if necessary
Implements fwServices::IService.
Definition at line 155 of file vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp.
The documentation for this class was generated from the following files:
vtkCompositeMesh/include/vtkCompositeMesh/RendererService.hpp
vtkCompositeMesh/src/vtkCompositeMesh/RendererService.cpp