fw4spl: fwGui::registrar::ToolBarRegistrar Class Reference
fwGui::registrar::ToolBarRegistrar Class Reference
Defines the toolBar registrar for IHM.
#include <ToolBarRegistrar.hpp>
Public Types
typedef std::vector< ::fwGui::IMenuItemCallback::sptr > CallbacksType
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((ToolBarRegistrar)(::fwGui::GuiBaseObject))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new ToolBarRegistrar,(((const std::string &))))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((ToolBarRegistrar)(::fwGui::GuiBaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWGUI_API ToolBarRegistrar (const std::string &sid)
Constructor.
virtual FWGUI_API ~ToolBarRegistrar ()
Destructor. Do nothing.
virtual FWGUI_API::fwGui::container::fwToolBar::sptr getParent ()
Return the parent container.
virtual FWGUI_API::fwGui::container::fwMenuItem::sptr getFwMenuItem (std::string actionSid, std::vector< ::fwGui::container::fwMenuItem::sptr > menuItems)
Return the fwMenuItem associated with the actionSid.
virtual FWGUI_API void initialize (::fwRuntime::ConfigurationElement::sptr configuration)
Initialize registry managers.
virtual FWGUI_API void manage (std::vector< ::fwGui::container::fwMenuItem::sptr > toolBarItems)
manages action service associated with menuItem of toolbar.
virtual FWGUI_API void manage (std::vector< ::fwGui::container::fwMenu::sptr > toolBarItems)
manages menu service associated with item of toolbar.
virtual FWGUI_API void manage (std::vector< ::fwGui::container::fwContainer::sptr > toolBarItems)
manages editor service associated with item of toolbar.
virtual FWGUI_API void unmanage ()
Stopping toolBar items manager. All services managed in local toolBar items will be stopped.
virtual FWGUI_API void onItemAction ()
This method is called when an action is clicked.
virtual CallbacksType getCallbacks ()
Returns callbacks associate with toolBar items.
Public Member Functions inherited from fwGui::GuiBaseObject
__FWCORE_CLASS_TYPEDEFS ((GuiBaseObject)(::fwCore::BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((GuiBaseObject)(::fwCore::BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Types
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
typedef std::map< std::string, std::pair< unsigned int, bool > > SIDToolBarMapType
Protected Attributes
SIDToolBarMapType m_actionSids
All toolBar services ID managed and associated with pair containing: action's index vector and boolean describing if is started by the manager.
SIDToolBarMapType m_menuSids
All toolBar services ID managed and associated with pair containing: menus index vector and boolean describing if is started by the manager.
SIDToolBarMapType m_editorSids
All toolBar services ID managed and associated with pair containing: editors index vector and boolean describing if is started by the manager.
std::string m_sid
Main service ID associate with this ToolBarRegistrar.
CallbacksType m_callbacks
Callback associate with toolBar items.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
Defines the toolBar registrar for IHM.
Date
2009-2010.
Definition at line 33 of file ToolBarRegistrar.hpp.
Member Function Documentation
fwGui::registrar::ToolBarRegistrar::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new ToolBarRegistrar, (((const std::string &))))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((ToolBarRegistrar)(::fwGui::GuiBaseObject)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((ToolBarRegistrar)(fwGui::GuiBaseObject)).
fwGui::container::fwMenuItem::sptr fwGui::registrar::ToolBarRegistrar::getFwMenuItem (std::string actionSid, std::vector< ::fwGui::container::fwMenuItem::sptr > menuItems) virtual
Return the fwMenuItem associated with the actionSid.
Parameters
actionSid sid of the action service
menuItems vector containing the fwMenuItem manages by this registrar.
Definition at line 43 of file ToolBarRegistrar.cpp.
References m_actionSids, and SLM_ASSERT.
void fwGui::registrar::ToolBarRegistrar::initialize (::fwRuntime::ConfigurationElement::sptr configuration) virtual
Initialize registry managers.
Example of configuration
    <service uid="toolbar2" type="::fwGui::IToolBarSrv" impl="::gui::aspect::SDefaultToolBar" autoConnect="no" >
        <gui>
            <layout>
                <menuItem name="My item 2" style="radio" icon="Bundles/TutoGui_0-1/icons/system.png"/>
                <menuItem name="My item 3" style="radio" icon="Bundles/TutoGui_0-1/icons/system.png"/>
                <separator />
                <menuItem name="My item A" style="radio" icon="Bundles/TutoGui_0-1/icons/monkey.png"/>
                <menuItem name="My item B" style="radio" icon="Bundles/TutoGui_0-1/icons/monkey.png"/>
                <separator />
                <menu name="My menu" />
                <separator />
                <editor />
            </layout>
        </gui>
        <registry>
            <menuItem sid="item2" />
            <menuItem sid="item3" />
            <menuItem sid="item4" />
            <menuItem sid="item5" />
            <menu sid="menu" />
            <editor sid="editor" />
        </registry>
    </service>
This method analyzes the registry section of the configuration.
<menuItem sid="item2" start="no" /> : define the service of the menuItem to add in the toolbar.
sid (mandatory): the service identifier.
start = {yes| no} (default value no): indicate if the service must be started by the toolbar service.
Definition at line 53 of file ToolBarRegistrar.cpp.
References m_actionSids, m_callbacks, m_editorSids, m_menuSids, OSLM_ASSERT, and SLM_ASSERT.
void fwGui::registrar::ToolBarRegistrar::manage (std::vector< ::fwGui::container::fwMenuItem::sptr > toolBarItems) virtual
manages action service associated with menuItem of toolbar.
Register the menuItem containers for the associated services. Start the services if start=yes.
If a menuItem has attribut start="no", the associated action won't be started and the menuItem will be disabled. If a menuItem has attribut start="yes", two possibilities:
the associated action has attribut executable="false" then the menuItem will be disabled.
the associated action has attribut executable="true" then the menuItem will be enabled.
Warning
If the action is present in a toolbar and a menu it must be started only one time.
See also
fwGui::registrar::MenuRegistrar for more information on interaction between menubar and toolbar.
Precondition
ToolBarRegistrar must be initialized before.
sub toolBar items must be instanced before.
Definition at line 142 of file ToolBarRegistrar.cpp.
References fwGui::GuiRegistry::actionServiceStarting(), fwGui::GuiRegistry::actionServiceStopping(), fwTools::fwID::exist(), fwServices::get(), m_actionSids, m_sid, OSLM_ASSERT, and fwGui::GuiRegistry::registerActionSIDToParentSID().
void fwGui::registrar::ToolBarRegistrar::manage (std::vector< ::fwGui::container::fwMenu::sptr > toolBarItems) virtual
manages menu service associated with item of toolbar.
Register the menu containers for the associated services. Start the services if start=yes.
Precondition
ToolBarRegistrar must be initialized before.
sub toolBar items must be instanced before.
Definition at line 175 of file ToolBarRegistrar.cpp.
References fwTools::fwID::exist(), m_menuSids, OSLM_ASSERT, and fwGui::GuiRegistry::registerSIDMenu().
void fwGui::registrar::ToolBarRegistrar::manage (std::vector< ::fwGui::container::fwContainer::sptr > toolBarItems) virtual
manages editor service associated with item of toolbar.
Register the containers for the associated services. Start the services if start=yes.
Precondition
ToolBarRegistrar must be initialized before.
sub toolBar items must be instanced before.
Definition at line 196 of file ToolBarRegistrar.cpp.
References fwTools::fwID::exist(), m_editorSids, OSLM_ASSERT, and fwGui::GuiRegistry::registerSIDContainer().
The documentation for this class was generated from the following files:
ToolBarRegistrar.hpp
ToolBarRegistrar.cpp