fw4spl: fwDicomIOFilter::helper::Filter Class Reference
fwDicomIOFilter::helper::Filter Class Reference
Filter Helper.
#include <Filter.hpp>
Public Types
typedef std::vector< ::fwMedData::DicomSeries::sptr > DicomSeriesContainerType
Static Public Member Functions
static FWDICOMIOFILTER_API bool applyFilter (DicomSeriesContainerType &dicomSeriesContainer,::fwDicomIOFilter::IFilter::sptr filter, bool forcedApply=false, const ::fwLog::Logger::sptr &logger=::fwLog::Logger::New())
Apply a filter to the DicomSeries.
Detailed Description
Filter Helper.
Definition at line 23 of file Filter.hpp.
Member Function Documentation
bool fwDicomIOFilter::helper::Filter::applyFilter (DicomSeriesContainerType & dicomSeriesContainer, ::fwDicomIOFilter::IFilter::sptr filter, bool forcedApply = false, const ::fwLog::Logger::sptr & logger = ::fwLog::Logger::New()) static
Apply a filter to the DicomSeries.
Parameters
[in,out] dicomSeriesContainer DicomSeries that must be filtered
[in] filter Filter that must be applied
Returns
Return true if errors have been ignored
Definition at line 17 of file Filter.cpp.
References fwDicomIOFilter::IFilter::COMPOSITE.
Referenced by ioDicom::SFilterSelectionEditor::addFilter(), fwDicomIOFilter::splitter::ImageDimensionsSplitter::apply(), fwGdcmIO::reader::SeriesDB::read(), fwDcmtkIO::SeriesDBReader::read(), and fwGdcmIO::reader::SeriesDB::readFromDicomSeriesDB().
The documentation for this class was generated from the following files:
Filter.hpp
Filter.cpp