fw4spl: fwRuntime::EConfigurationElement Class Reference
fwRuntime::EConfigurationElement Class Reference
Editable configuration element : allow the self configuration element building, which reading XML structure provided by bundle descriptions.
#include <EConfigurationElement.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWRUNTIME_API EConfigurationElement (const std::string &name)
Constructor.
virtual FWRUNTIME_API ~EConfigurationElement ()
Destructor : does nothing.
FWRUNTIME_API EConfigurationElement::sptr addConfigurationElement (const std::string &name)
Create and add a configuration element.
FWRUNTIME_API void addConfigurationElement (EConfigurationElement::sptr element)
Adds a new configuration element to the extension.
FWRUNTIME_API void setAttributeValue (const std::string &name, const std::string &value) throw ()
FWRUNTIME_API void setValue (const std::string &value) throw ()
Public Member Functions inherited from fwRuntime::ConfigurationElement
FWRUNTIME_API const std::shared_ptr< Bundle > getBundle () const throw ()
Retrieves the bundle the configuration element is attached to.
FWRUNTIME_API const std::string getAttributeValue (const std::string &name) const throw ()
Retrieves the value of an attribute for the specified name.
FWRUNTIME_API const std::string getExistingAttributeValue (const std::string &name) const throw (NoSuchAttribute)
Retrieves the value of an attribute for the specified name.
FWRUNTIME_API const AttributePair getSafeAttributeValue (const std::string &name) const throw ()
Retrieves the value of an existing attribute for the specified name.
FWRUNTIME_API const std::string getName () const throw ()
Retrieves the name of the configuration element.
FWRUNTIME_API const std::string getValue () const throw ()
Retrieves the configuration element value.
FWRUNTIME_API bool hasAttribute (const std::string &name) const throw ()
Tells if the specified attributes exists.
FWRUNTIME_API const std::map< std::string, std::string > getAttributes () const throw ()
Return the map with attributes.
FWRUNTIME_API std::vector< ConfigurationElement::sptr > find (std::string name="", std::string attribute="", std::string attributeValue="", int depth=1)
Find recursively all the corresponding configuration elements.
virtual FWRUNTIME_API ~ConfigurationElement ()
Used only because this class inherit from enable_shared_from_this.
Public Member Functions inherited from fwRuntime::ConfigurationElementContainer
FWRUNTIME_API Iterator begin ()
Retrieves the iterator on the first managed configuration element.
FWRUNTIME_API Iterator end ()
Retrieves the iterator on the end of the configuration element container.
FWRUNTIME_API const Container & getElements () const
Returns the configuration element container.
FWRUNTIME_API const std::shared_ptr< ConfigurationElement > findConfigurationElement (const std::string &name) const
Retrieves the first configuration corresponding to the specified name.
FWRUNTIME_API bool hasConfigurationElement (const std::string &name) const
Test if has an configuration corresponding to the specified name.
FWRUNTIME_API ConfigurationElementContainer findAllConfigurationElement (const std::string &name) const
Retrieves the configurations corresponding to the specified name.
FWRUNTIME_API size_t size () const
Return the number of configurations.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwRuntime::ConfigurationElement
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Public Types inherited from fwRuntime::ConfigurationElement
typedef std::pair< bool, std::string > AttributePair
Defines the attribute pair type.
Public Types inherited from fwRuntime::ConfigurationElementContainer
typedef std::vector< std::shared_ptr< ConfigurationElement > > Container
Defines the configuration element container type.
typedef Container::iterator Iterator
Defines the configuration element container type.
Protected Member Functions inherited from fwRuntime::ConfigurationElement
FWRUNTIME_API ConfigurationElement (const std::shared_ptr< Bundle > bundle, const std::string &name)
Constructor.
FWRUNTIME_API void setAttributeValue (const std::string &name, const std::string &value) throw ()
Sets an attribute with the specified name and value.
FWRUNTIME_API void setValue (const std::string &value) throw ()
Sets the value of the configuration element it-self.
Protected Member Functions inherited from fwRuntime::ConfigurationElementContainer
FWRUNTIME_API void addConfigurationElement (std::shared_ptr< ConfigurationElement > element)
Adds a new configuration element to the extension.
Detailed Description
Editable configuration element : allow the self configuration element building, which reading XML structure provided by bundle descriptions.
Date
2006-2009
Definition at line 23 of file EConfigurationElement.hpp.
Constructor & Destructor Documentation
fwRuntime::EConfigurationElement::EConfigurationElement (const std::string & name)
Constructor.
Parameters
[in] name name of the configuration element
Definition at line 17 of file EConfigurationElement.cpp.
Member Function Documentation
EConfigurationElement::sptr fwRuntime::EConfigurationElement::addConfigurationElement (const std::string & name)
Create and add a configuration element.
Parameters
[in] name name of the configuration element
Returns
the created configuration element
Definition at line 26 of file EConfigurationElement.cpp.
References fwRuntime::ConfigurationElementContainer::addConfigurationElement().
void fwRuntime::EConfigurationElement::addConfigurationElement (EConfigurationElement::sptr element)
Adds a new configuration element to the extension.
Parameters
[in] element a shared pointer to the configuration element to add
Definition at line 33 of file EConfigurationElement.cpp.
References fwRuntime::ConfigurationElementContainer::addConfigurationElement(), fwRuntime::ConfigurationElement::setAttributeValue(), and fwRuntime::ConfigurationElement::setValue().
The documentation for this class was generated from the following files:
EConfigurationElement.hpp
EConfigurationElement.cpp