fw4spl: ctrlSelection::wrapper::MsgForwarderSrv Class Reference
ctrlSelection::wrapper::MsgForwarderSrv Class Reference
This service forwards an event from specific object to object specified with key in in composite.
#include <MsgForwarderSrv.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((MsgForwarderSrv)(::ctrlSelection::IWrapperSrv))
Protected Member Functions
virtual CTRLSELECTION_API void starting () throw (::fwTools::Failed)
Implements starting method derived from IService. Does nothing.
virtual CTRLSELECTION_API void stopping () throw (::fwTools::Failed)
Implements stopping method derived from IService. Does nothing.
virtual CTRLSELECTION_API void swapping () throw (::fwTools::Failed)
Implements swapping method derived from IService. Convert the image.
virtual CTRLSELECTION_API void configuring () throw (::fwTools::Failed)
Configures the service.
virtual CTRLSELECTION_API void updating () throw (::fwTools::Failed)
Implements updating method derived from IService. Does nothing.
virtual CTRLSELECTION_API void info (std::ostream &_sstream)
Implements info method derived from IService. Print classname.
virtual CTRLSELECTION_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
Detailed Description
This service forwards an event from specific object to object specified with key in in composite.
Date:
2011.
Definition at line 30 of file MsgForwarderSrv.hpp.
Member Function Documentation
void ctrlSelection::wrapper::MsgForwarderSrv::configuring () throw (::fwTools::Failed) [protected, virtual]
Configures the service.
       <service uid="forwarderMsg" impl="::ctrlSelection::wrapper::MsgForwarderSrv" type="::ctrlSelection::IWrapperSrv" autoConnect="no">
           <forward compositeKey="frontImage" onEvent="SLICE_INDEX" fromUID="*" msgType="::fwComEd::ImageMsg" />
           <forward compositeKey="frontImage" onEvent="CHANGE_SLICE_TYPE" fromUID="*" msgType="::fwComEd::ImageMsg" />
       </service>
With :
compositeKey : key of the object in the composite,
onEvent : event of the message to receive,
fromUID : uid of the object which sent the message. If "*" the message can be received from any object,
msgType : type of the message to receive.
Implements fwServices::IService.
Definition at line 84 of file MsgForwarderSrv.cpp.
References fwRuntime::ConfigurationElementContainer::getElements(), fwServices::IService::m_configuration, OSLM_INFO, fwRuntime::ConfigurationElementContainer::size(), SLM_ASSERT, SLM_FATAL_IF, and SLM_TRACE_FUNC.
void ctrlSelection::wrapper::MsgForwarderSrv::receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed) [protected, virtual]
Perform some computations according to modifications specified in the _msg parameter. _msg generally indicates modification to occur (or having occured) on the object the service is attached to.
See also:
receive(fwServices::ObjectMsg::csptr)
Reimplemented from fwServices::IService.
Definition at line 36 of file MsgForwarderSrv.cpp.
References fwServices::IEditionService::notify(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
MsgForwarderSrv.hpp
MsgForwarderSrv.cpp