fw4spl: fwStructuralPatch::creator::fwMedData::Series1 Class Reference
fwStructuralPatch::creator::fwMedData::Series1 Class Reference
Structural creator for fwMedData::Series version 1.
#include <Series1.hpp>
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((Series1)(::fwAtomsPatch::IStructuralCreator))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Series1,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((Series1)(::fwAtomsPatch::IStructuralCreator)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWSTRUCTURALPATCH_API Series1 ()
Constructor.
FWSTRUCTURALPATCH_API ~Series1 ()
Destructor.
FWSTRUCTURALPATCH_API Series1 (const Series1 &cpy)
Copy constructor.
virtual FWSTRUCTURALPATCH_API::fwAtoms::Object::sptr create ()
Creates the specified object.
Public Member Functions inherited from fwAtomsPatch::IStructuralCreator
__FWCORE_CLASS_TYPEDEFS ((IStructuralCreator))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((IStructuralCreator)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
__FWCORE_TYPEDEF_SHARED_PTR_CONST_NAME __FWCORE_CONST_SPTR_FROM_THIS_FUNC_NAME () const
return a casted const shared ptr from this object
__FWCORE_TYPEDEF_SHARED_PTR_NAME __FWCORE_SPTR_FROM_THIS_FUNC_NAME ()
return a casted shared ptr from this object
FWATOMSPATCH_API IStructuralCreator ()
Constructor.
FWATOMSPATCH_API IStructuralCreator (const IStructuralCreator &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IStructuralCreator ()
Destructor.
virtual FWATOMSPATCH_API const std::string & getObjectVersion () const
Returns the version of the object.
virtual FWATOMSPATCH_API const std::string & getObjectClassname () const
Returns the classname of the object.
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::IStructuralCreator
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Protected Member Functions inherited from fwAtomsPatch::IStructuralCreator
FWATOMSPATCH_API::fwAtoms::Object::sptr createObjBase () const
Create the object base : create meta infos : classname, version and id.
Protected Attributes inherited from fwAtomsPatch::IStructuralCreator
std::string m_classname
Object classname.
std::string m_version
Object version.
Detailed Description
Structural creator for fwMedData::Series version 1.
Definition at line 21 of file Series1.hpp.
Member Function Documentation
fwStructuralPatch::creator::fwMedData::Series1::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new Series1, (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((Series1)(::fwAtomsPatch::IStructuralCreator)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((Series1)(fwAtomsPatch::IStructuralCreator)).
fwAtoms::Object::sptr fwStructuralPatch::creator::fwMedData::Series1::create () virtual
Creates the specified object.
Calls creators for 'patient', 'study' and 'equipment' attributes and sets remaining attributes.
Implements fwAtomsPatch::IStructuralCreator.
Reimplemented in fwStructuralPatch::creator::fwMedData::ActivitySeries1, fwStructuralPatch::creator::fwMedData::ImageSeries1, and fwStructuralPatch::creator::fwMedData::ModelSeries1.
Definition at line 43 of file Series1.cpp.
References fwAtomsPatch::helper::Object::addAttribute(), fwAtomsPatch::IStructuralCreator::createObjBase(), fwAtomsPatch::StructuralCreatorDB::getDefault(), and fwAtoms::String::New().
Referenced by fwStructuralPatch::creator::fwMedData::ImageSeries1::create(), fwStructuralPatch::creator::fwMedData::ModelSeries1::create(), and fwStructuralPatch::creator::fwMedData::ActivitySeries1::create().
The documentation for this class was generated from the following files:
Series1.hpp
Series1.cpp