fw4spl: fwGui::dialog::LocationDialog Class Reference
fwGui::dialog::LocationDialog Class Reference
Defines the generic file/folder selector dialog for IHM.
#include <LocationDialog.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWGUI_API LocationDialog ()
Will instantiate the concrete implementation.
FWGUI_API::fwData::location::ILocation::sptr show () override
Display the dialog.
FWGUI_API::fwGui::dialog::ILocationDialog & setOption (::fwGui::dialog::ILocationDialog::Options option) override
allow to set option to the file dialog mode=READ/WRITE, check=FILE_MUST_EXIST
FWGUI_API void setType (::fwGui::dialog::ILocationDialog::Types type) override
Set the type of location for the dialog (SINGLE_FILE, FORLDER, MULTI_FILES)
FWGUI_API void addFilter (const std::string &filterName, const std::string &wildcardList) override
specify some filtering when browsing files:
FWGUI_API void setTitle (const std::string &title) override
Set the title for the dialog.
FWGUI_API const std::string & getTitle () override
Returns the title for the dialog.
virtual FWGUI_API void setDefaultLocation (::fwData::location::ILocation::sptr loc) override
Set the initial location for the dialog.
FWGUI_APIconst::boost::filesystem::path getDefaultLocation () override
Gets the default location for the dialog (from preferences or specified by user)
FWGUI_API void saveDefaultLocation (::fwData::location::ILocation::sptr loc) override
Save the specified default location for the dialog in preferences (if available)
FWGUI_API std::string getCurrentSelection () const override
Gets the current extension file selection.
Public Member Functions inherited from fwGui::dialog::ILocationDialog
virtual FWGUI_API void setType (Types type)=0
set the type of location for the dialog (SINGLE_FILE, FORLDER, MULTI_FILES)
virtual FWGUI_API ILocationDialog & setOption (Options option)=0
allow to set option to the file dialog mode=READ/WRITE , check=FILE_MUST_EXIST
Public Member Functions inherited from fwGui::GuiBaseObject
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwGui::dialog::ILocationDialog
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwGui::GuiBaseObject
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Protected Attributes
::fwGui::dialog::ILocationDialog::sptr m_implementation
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwGui::dialog::ILocationDialog
enum Options { NONE = 0, READ = 1 << 1, WRITE = 1 << 2, FILE_MUST_EXIST = 1 << 3 }
enum Types { SINGLE_FILE, FOLDER, MULTI_FILES }
typedef std::string FactoryRegistryKeyType
Public Types inherited from fwGui::GuiBaseObject
typedef ::fwGui::factory::Key Key
Static Public Attributes inherited from fwGui::dialog::ILocationDialog
static FWGUI_API const FactoryRegistryKeyType REGISTRY_KEY = "::fwGui::dialog::LocationDialog"
this unique key should be used for all factory for specific LocationDialog(qt,wx,...)
static FWGUI_API const std::string SOFTWARE_UI = "SOFTWARE_UI"
static FWGUI_API const std::string DLG_DEFAULT_LOCATION = "DLG_DEFAULT_LOCATION"
Protected Member Functions inherited from fwGui::dialog::ILocationDialog
FWGUI_API void readConfig ()
FWGUI_API void writeConfig ()
FWGUI_API::fwData::Composite::sptr getPreferenceUI ()
Protected Member Functions inherited from fwGui::GuiBaseObject
GuiBaseObject ()
virtual ~GuiBaseObject ()
Detailed Description
Defines the generic file/folder selector dialog for IHM.
Use the Delegate design pattern. The specific implementation selection is ensured by fwGuiRegisterMacro. The specific implementation are in fwGuiWX and fwGuiQT libraries.
Date
2009-2010.
Definition at line 25 of file include/fwGui/dialog/LocationDialog.hpp.
Member Function Documentation
void fwGui::dialog::LocationDialog::addFilter (const std::string & filterName, const std::string & wildcardList) override virtual
specify some filtering when browsing files:
Parameters
[in] filterName a string that will be displayed as filter name
[in] wildcardList a string of extension (glob syntax) separated by spaces example : addFilter("images","*.png *.jpg")
Implements fwGui::dialog::ILocationDialog.
Definition at line 56 of file src/fwGui/dialog/LocationDialog.cpp.
Referenced by ioData::TransformationMatrix3DReaderService::configureWithIHM(), ioData::TransformationMatrix3DWriterService::configureWithIHM(), ioData::SAttachmentSeriesReader::configureWithIHM(), ioData::STrianMeshReader::configureWithIHM(), ioITK::SImageSeriesWriter::configureWithIHM(), ioVTK::SImageSeriesReader::configureWithIHM(), ioVTK::SMeshReader::configureWithIHM(), ioVTK::SImageReader::configureWithIHM(), ioITK::InrImageWriterService::configureWithIHM(), ioITK::InrImageReaderService::configureWithIHM(), ioVTK::SModelSeriesReader::configureWithIHM(), ioVTK::SImageSeriesWriter::configureWithIHM(), ioVTK::SMeshWriter::configureWithIHM(), ioData::MeshWriterService::configureWithIHM(), ioVTK::SImageWriter::configureWithIHM(), ioVTK::SSeriesDBReader::configureWithIHM(), ioITK::SInrSeriesDBReader::configureWithIHM(), ioTuto::ExternalDataReaderService::configureWithIHM(), ioAtoms::SWriter::configureWithIHM(), ioAtoms::SReader::configureWithIHM(), ioQt::SPdfWriter::configureWithIHM(), uiVisu::action::SSnapshot::info(), uiVisuQt::SnapshotEditor::onSnapButton(), uiMeasurement::action::LoadLandmark::updating(), and uiMeasurement::action::SaveLandmark::updating().
fwData::location::ILocation::sptr fwGui::dialog::LocationDialog::show () override virtual
Display the dialog.
Returns
the ILocation selected or null sptr if user cancel the operation
Implements fwGui::dialog::ILocationDialog.
Definition at line 36 of file src/fwGui/dialog/LocationDialog.cpp.
References fwServices::registry::ActiveWorkers::getDefaultWorker(), fwGui::dialog::ILocationDialog::show(), and SPTR.
Referenced by ioData::TransformationMatrix3DReaderService::configureWithIHM(), ioData::TransformationMatrix3DWriterService::configureWithIHM(), ioData::SAttachmentSeriesReader::configureWithIHM(), ioGdcm::SSeriesDBWriter::configureWithIHM(), ioGdcm::SSurfaceSegmentationWriter::configureWithIHM(), ioData::STrianMeshReader::configureWithIHM(), ioITK::SImageSeriesWriter::configureWithIHM(), ioGdcm::SDicomSeriesWriter::configureWithIHM(), ioVTK::SMeshReader::configureWithIHM(), ioVTK::SImageSeriesReader::configureWithIHM(), ioITK::SJpgImageSeriesWriter::configureWithIHM(), ioVtkGdcm::SImageSeriesWriter::configureWithIHM(), ioITK::InrImageWriterService::configureWithIHM(), ioVTK::SImageReader::configureWithIHM(), ioITK::InrImageReaderService::configureWithIHM(), ioITK::JpgImageWriterService::configureWithIHM(), ioVTK::SModelSeriesReader::configureWithIHM(), ioVTK::SImageSeriesWriter::configureWithIHM(), ioVTK::SMeshWriter::configureWithIHM(), ioVTK::SImageWriter::configureWithIHM(), ioData::MeshWriterService::configureWithIHM(), ioVTK::SModelSeriesWriter::configureWithIHM(), ioVTK::SModelSeriesObjWriter::configureWithIHM(), ioVTK::SSeriesDBReader::configureWithIHM(), ioTuto::ExternalDataReaderService::configureWithIHM(), ioITK::SInrSeriesDBReader::configureWithIHM(), ioVtkGdcm::SSeriesDBLazyReader::configureWithIHM(), ioVtkGdcm::SSeriesDBReader::configureWithIHM(), ioAtoms::SWriter::configureWithIHM(), ioDcmtk::SSeriesDBReader::configureWithIHM(), ioGdcm::SDicomSeriesDBReader::configureWithIHM(), ioAtoms::SReader::configureWithIHM(), ioQt::SPdfWriter::configureWithIHM(), ioGdcm::SSeriesDBReader::configureWithIHM(), uiVisu::action::SSnapshot::info(), uiVisuQt::SnapshotEditor::onSnapButton(), uiMeasurement::action::LoadLandmark::updating(), uiMeasurement::action::SaveLandmark::updating(), uiIO::action::SFolderSelector::updating(), and uiPreferences::action::SPreferencesConfiguration::updating().
The documentation for this class was generated from the following files:
include/fwGui/dialog/LocationDialog.hpp
src/fwGui/dialog/LocationDialog.cpp