fw4spl: gui::frame::DefaultFrame Class Reference
gui::frame::DefaultFrame Class Reference
Defines the default frame for standard application.
#include <DefaultFrame.hpp>
Public Member Functions
fwCoreServiceClassDefinitionsMacro ((DefaultFrame)(::fwGui::IFrameSrv))
GUI_API DefaultFrame () throw ()
Constructor. Do nothing.
virtual GUI_API ~DefaultFrame () throw ()
Destructor. Do nothing.
Protected Member Functions
Service methods (override from ::fwServices::IService)
virtual GUI_API void configuring () throw (::fwTools::Failed)
This method is used to configure the class parameters.
virtual GUI_API void starting () throw (::fwTools::Failed)
Register a view with defined id.
virtual GUI_API void stopping () throw (::fwTools::Failed)
This method remove the view in the frame.
virtual GUI_API void receiving (::fwServices::ObjectMsg::csptr _msg) throw (::fwTools::Failed)
This method is used to update services on notification. Do nothing.
virtual GUI_API void updating () throw (::fwTools::Failed)
This method is used to update services. Do nothing.
virtual GUI_API void info (std::ostream &_sstream)
This method gives information about the class. Do nothing.
Detailed Description
Defines the default frame for standard application.
Definition at line 24 of file DefaultFrame.hpp.
Member Function Documentation
void gui::frame::DefaultFrame::configuring () throw (::fwTools::Failed) [protected, virtual]
This method is used to configure the class parameters.
See also:
fwGui::IFrameSrv::initialize()
Implements fwServices::IService.
Definition at line 32 of file DefaultFrame.cpp.
References fwGui::IFrameSrv::initialize(), fwServices::IService::m_configuration, and SLM_ASSERT.
void gui::frame::DefaultFrame::starting () throw (::fwTools::Failed) [protected, virtual]
Register a view with defined id.
See also:
fwGui::IFrameSrv::create()
Implements fwServices::IService.
Definition at line 40 of file DefaultFrame.cpp.
References fwGui::IFrameSrv::create(), and SLM_TRACE_FUNC.
void gui::frame::DefaultFrame::stopping () throw (::fwTools::Failed) [protected, virtual]
This method remove the view in the frame.
See also:
fwGui::IFrameSrv::destroy()
Implements fwServices::IService.
Definition at line 48 of file DefaultFrame.cpp.
References fwGui::IFrameSrv::destroy(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
DefaultFrame.hpp
DefaultFrame.cpp