fw4spl: fwCore::TimeStamp Class Reference
fwCore::TimeStamp Class Reference
Provides a timestamp and a expiracy system.
#include <TimeStamp.hpp>
Public Types
typedef ::fwCore::HiResClock::HiResClockType TimeStampType
Type used in logical typestamp.
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((TimeStamp)(BaseObject))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new TimeStamp,(()))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((TimeStamp)(BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWCORE_API void modified ()
Update the timestamp to the current EPOCH time.
FWCORE_API TimeStampType getTimeStamp () const
FWCORE_API bool operator> (const TimeStamp &ts) const
Greater than operator for TimeStamp.
FWCORE_API bool operator< (const TimeStamp &ts) const
Lesser than operator for TimeStamp.
FWCORE_API operator TimeStampType () const
Cast operator for TimeStamp.
FWCORE_API void setLifePeriod (TimeStampType period)
Setter for the life period.
FWCORE_API TimeStampType getLifePeriod () const
Getter for the life period.
FWCORE_API bool periodExpired () const
Check TimeStamp expiracy status.
Constructor/Destructor
FWCORE_API TimeStamp ()
Public Member Functions inherited from fwCore::BaseObject
__FWCORE_CLASS_TYPEDEFS ((BaseObject))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((BaseObject)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Provides a timestamp and a expiracy system.
Definition at line 20 of file TimeStamp.hpp.
Member Function Documentation
fwCore::TimeStamp::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new TimeStamp, (()))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((TimeStamp)(BaseObject)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((TimeStamp)(BaseObject)).
FWCORE_API TimeStampType fwCore::TimeStamp::getLifePeriod () const inline
Getter for the life period.
Returns
TimeStamp life period
Definition at line 106 of file TimeStamp.hpp.
FWCORE_API TimeStampType fwCore::TimeStamp::getTimeStamp () const inline
Returns
TimeStamp's current value
Definition at line 55 of file TimeStamp.hpp.
FWCORE_API bool fwCore::TimeStamp::operator< (const TimeStamp & ts) const inline
Lesser than operator for TimeStamp.
Parameters
ts TimeStamp to compare to
Definition at line 77 of file TimeStamp.hpp.
FWCORE_API bool fwCore::TimeStamp::operator> (const TimeStamp & ts) const inline
Greater than operator for TimeStamp.
Parameters
ts TimeStamp to compare to
Definition at line 67 of file TimeStamp.hpp.
FWCORE_API bool fwCore::TimeStamp::periodExpired () const inline
Check TimeStamp expiracy status.
Returns
True if more than m_lifePeriod milliseconds are elapsed from TimeStamp value
Definition at line 118 of file TimeStamp.hpp.
References fwCore::HiResClock::getTimeInMilliSec().
Referenced by fwThread::WorkerAsio::processTasks().
FWCORE_API void fwCore::TimeStamp::setLifePeriod (TimeStampType period) inline
Setter for the life period.
Parameters
period Period in milliseconds
Definition at line 96 of file TimeStamp.hpp.
Referenced by fwThread::WorkerAsio::processTasks().
The documentation for this class was generated from the following files:
TimeStamp.hpp
TimeStamp.cpp