fw4spl: fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader Class Reference
fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader Class Reference
This class is used to read the buffer of a DICOM image in LAZY mode when a pixel lookup must be performed.
#include <ImageRGBLookupLazyReader.hpp>
Static Public Member Functions
template<typename T >
static void * createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr &instance, const T *redLookup, const T *greenLookup, const T *blueLookup, unsigned short pixelValueBitsAllocated)
Create an instance buffer according to the image type. The template T is used to determine color format.
template<typename T , typename U >
static T * createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr &instance, const T *redLookup, const T *greenLookup, const T *blueLookup)
Create an instance buffer according to the image type. The template T is used to determine color format The template U is used to determine pixel value format.
Detailed Description
This class is used to read the buffer of a DICOM image in LAZY mode when a pixel lookup must be performed.
Definition at line 33 of file ImageRGBLookupLazyReader.hpp.
Member Function Documentation
template<typename T > static void* fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader::createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr & instance, const T * redLookup, const T * greenLookup, const T * blueLookup, unsigned short pixelValueBitsAllocated) inline static
Create an instance buffer according to the image type. The template T is used to determine color format.
Parameters
[in] rows Number of rows
[in] columns Number of columns
[in] instance Path to the instance
[in] redLookup Red lookup table
[in] greenLookup Red lookup table
[in] blueLookup Red lookup table
[in] pixelValueBitsAllocated Pixel value bits allocated
Definition at line 49 of file ImageRGBLookupLazyReader.hpp.
Referenced by fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource::ImageRGBLookupLazySource(), and fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazySource::read().
template<typename T , typename U > static T* fwDcmtkIO::reader::rgblookup::ImageRGBLookupLazyReader::createInstanceBuffer (unsigned int rows, unsigned int columns, const ::fwMemory::BufferObject::sptr & instance, const T * redLookup, const T * greenLookup, const T * blueLookup) inline static
Create an instance buffer according to the image type. The template T is used to determine color format The template U is used to determine pixel value format.
Parameters
[in] rows Number of rows
[in] columns Number of columns
[in] instance Path to the instance
[in] redLookup Red lookup table
[in] greenLookup Red lookup table
[in] blueLookup Red lookup table
Definition at line 79 of file ImageRGBLookupLazyReader.hpp.
References fwDcmtkIO::helper::Codec::cleanup(), fwMemory::BufferObject::LockBase< T >::getBuffer(), OSLM_WARN_IF, and fwDcmtkIO::helper::Codec::registerCodecs().
The documentation for this class was generated from the following file:
ImageRGBLookupLazyReader.hpp