fw4spl: fwStructuralPatch::fwData::Study::V1ToFwMedDataStudyV1 Class Reference
fwStructuralPatch::fwData::Study::V1ToFwMedDataStudyV1 Class Reference
Transforms a ::fwData::Study to a fwMedData::Study.
#include <V1ToFwMedDataStudyV1.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
FWSTRUCTURALPATCH_API V1ToFwMedDataStudyV1 ()
Constructor.
FWSTRUCTURALPATCH_API ~V1ToFwMedDataStudyV1 ()
Destructor.
FWSTRUCTURALPATCH_API V1ToFwMedDataStudyV1 (const V1ToFwMedDataStudyV1 &cpy)
Copy constructor.
virtual FWSTRUCTURALPATCH_API void apply (const ::fwAtoms::Object::sptr &previous, const ::fwAtoms::Object::sptr &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions) override
Applies patch.
Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
FWATOMSPATCH_API IStructuralPatch ()
Constructor.
FWATOMSPATCH_API IStructuralPatch (const IStructuralPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IStructuralPatch ()
Destructor.
virtual FWATOMSPATCH_API void apply (const std::shared_ptr< ::fwAtoms::Object > &previous, const std::shared_ptr< ::fwAtoms::Object > &current,::fwAtomsPatch::IPatch::NewVersionsType &newVersions) override
Applies the patch to the specified object.
virtual FWATOMSPATCH_API const std::string & getTargetClassname () const
Returns the target classname of the object.
virtual FWATOMSPATCH_API const std::string & getTargetVersion () const
Returns the target version of the object.
Public Member Functions inherited from fwAtomsPatch::IPatch
FWATOMSPATCH_API IPatch ()
Constructor. Does nothing.
FWATOMSPATCH_API IPatch (const IPatch &cpy)
Copy constructor.
virtual FWATOMSPATCH_API ~IPatch ()
Destructor. Does nothing.
virtual FWATOMSPATCH_API const std::string & getOriginClassname () const
Returns the origin classname of the object.
virtual FWATOMSPATCH_API const std::string & getOriginVersion () const
Returns the origin version of the object.
Public Member Functions inherited from fwCore::BaseObject
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwAtomsPatch::IStructuralPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwAtomsPatch::IPatch
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwAtomsPatch::IPatch
typedef std::map< ::fwAtoms::Object::sptr,::fwAtoms::Object::sptr > NewVersionsType
Protected Member Functions inherited from fwAtomsPatch::IStructuralPatch
FWATOMSPATCH_API void updateVersion (std::shared_ptr< ::fwAtoms::Object > current)
Updates the version of the patched object.
Protected Attributes inherited from fwAtomsPatch::IStructuralPatch
std::string m_targetClassname
Target type.
std::string m_targetVersion
Target version.
Protected Attributes inherited from fwAtomsPatch::IPatch
std::string m_originClassname
Origin classname of the object.
std::string m_originVersion
Origin version of the object.
Detailed Description
Transforms a ::fwData::Study to a fwMedData::Study.
Definition at line 24 of file V1ToFwMedDataStudyV1.hpp.
Member Function Documentation
void fwStructuralPatch::fwData::Study::V1ToFwMedDataStudyV1::apply (const ::fwAtoms::Object::sptr & previous, const ::fwAtoms::Object::sptr & current, ::fwAtomsPatch::IPatch::NewVersionsType & newVersions) override virtual
Applies patch.
Removes attributes 'hospital', 'modality', 'acquisition_zone', 'ris_id', 'db_id' and 'acquisitions', renames 'uid' to 'instance_uid', adds 'referring_physicians_name' and 'patient_age'.
Implements fwAtomsPatch::IPatch.
Definition at line 44 of file V1ToFwMedDataStudyV1.cpp.
References fwAtomsPatch::helper::Object::addAttribute(), fwAtoms::String::New(), fwAtomsPatch::helper::Object::removeAttribute(), fwAtomsPatch::helper::Object::renameAttribute(), and fwAtomsPatch::IStructuralPatch::updateVersion().
The documentation for this class was generated from the following files:
V1ToFwMedDataStudyV1.hpp
V1ToFwMedDataStudyV1.cpp