fw4spl: visuVTKAdaptor::SProbeCursor Class Reference
visuVTKAdaptor::SProbeCursor Class Reference
Cursor management: displays a red cross representing the image picked point.
#include <SProbeCursor.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const override
virtual VISUVTKADAPTOR_API void updateView (double world[3])
VISUVTKADAPTOR_API void setVisibility (bool visibility)
VISUVTKADAPTOR_API void startSProbeCursor ()
Public Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
virtual FWDATATOOLS_API ~MedicalImageAdaptor ()
Destructor. Do nothing.
virtual FWDATATOOLS_API void setOrientation (Orientation orientation)
Set the image orientation.
Orientation getOrientation () const
Return the image orientation.
FWDATATOOLS_API void setTransferFunction (const ::fwData::TransferFunction::sptr &tf)
Set the current TransferFunction.
Public Member Functions inherited from fwRenderVTK::IAdaptor
FWRENDERVTK_API void setRenderService (SRender::sptr service)
Sets the assiciated render service.
FWRENDERVTK_API SRender::sptr getRenderService () const
Returd the associated render service.
FWRENDERVTK_API void setRendererId (SRender::RendererIdType newID)
Sets the renderer identifier.
FWRENDERVTK_API SRender::RendererIdType getRendererId () const
Returns the renderer identifier.
FWRENDERVTK_API vtkRenderer * getRenderer ()
Returns the renderer.
FWRENDERVTK_API void setPickerId (SRender::PickerIdType newID)
Sets the identifier of the picker used by this adaptor.
FWRENDERVTK_API SRender::PickerIdType getPickerId () const
Gets the identifier of the picker used by this adaptor.
FWRENDERVTK_API vtkAbstractPropPicker * getPicker (std::string pickerId="")
Get the picker.
FWRENDERVTK_API void setTransformId (SRender::VtkObjectIdType newID)
Sets the identifier of the transform used by this adaptor.
FWRENDERVTK_API SRender::VtkObjectIdType getTransformId () const
Returns the identifier of the transform used by this adaptor.
FWRENDERVTK_API vtkTransform * getTransform ()
Returns the transform used by this adaptor.
FWRENDERVTK_API vtkObject * getVtkObject (const SRender::VtkObjectIdType &objectId) const
Returns the vtk object defined by 'objectId' in the vtk scene.
FWRENDERVTK_API vtkRenderWindowInteractor * getInteractor ()
Returns the render interactor.
FWRENDERVTK_API IAdaptor::sptr getAssociatedAdaptor (vtkProp *prop, int depth)
Returns the adaptor associated to the vtkProp.
FWRENDERVTK_API void getAllSubProps (vtkPropCollection *propc, int depth=-1)
Gets all the vtkProp associated to this adaptor.
FWRENDERVTK_API void setVtkPipelineModified ()
End-user have to call this method when a vtk structure has been modified, thus a render request will be sent.
FWRENDERVTK_API bool getAutoRender () const
Returns true if the service automatically triggers the rendering.
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void registerInput (const ::fwData::Object::csptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an input object for this service.
FWSERVICES_API void registerInOut (const ::fwData::Object::sptr &obj, const std::string &key, const bool autoConnect=false, const bool optional=false)
Register an in/out object for this service.
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const noexcept
Return the global process status.
FWSERVICES_API bool isStarted () const noexcept
Test if the service is started or not.
FWSERVICES_API bool isStopped () const noexcept
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const noexcept
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const noexcept
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const InOutMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API const OutputMapType & getOutputs () const
Return the outouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &key) const
Return the output object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getOutput (const KeyType &keybase, size_t index) const
Return the output object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
virtual FWSERVICES_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
FWSERVICES_API bool hasObjectId (const KeyType &_key) const
Return true if the object with the given key has an identifier.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Public Member Functions inherited from fwServices::IHasServices
const ServiceVector & getRegisteredServices () const
Get all subservices linked to this service.
FWSERVICES_API std::shared_ptr< const ::fwServices::IService > getRegisteredService (const ::fwTools::fwID::IDType &_id) const
Return a specific registered service.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwRenderVTK::IAdaptor
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & classname ()
return full object's classname with its namespace, i.e. fwCore::BaseObject
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Static Public Attributes
static const ::fwCom::Slots::SlotKeyType s_UPDATE_SLICE_INDEX_SLOT = "updateSliceIndex"
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Member Functions
VISUVTKADAPTOR_API void configuring () override
Configure the service before starting. Apply the configuration to service.
VISUVTKADAPTOR_API void starting () override
Initialize the service activity.
VISUVTKADAPTOR_API void updating () override
Perform some computations according to object (this service is attached to) attribute values and its internal state.
VISUVTKADAPTOR_API void stopping () override
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
virtual VISUVTKADAPTOR_API KeyConnectionsMap getAutoConnections () const override
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
void buildTextActor ()
void buildPolyData ()
void computeCrossExtremity (fwData::Image::csptr image, const int probeSlice[3], double worldCross[4][3])
Protected Member Functions inherited from fwDataTools::helper::MedicalImageAdaptor
FWDATATOOLS_API MedicalImageAdaptor ()
Constructor. Do nothing.
FWDATATOOLS_API void setOrientation (int orientation)
Set the orientation of the image.
FWDATATOOLS_API void getImageSpacing (double spacing[3]) const
Get the image spacing.
FWDATATOOLS_API void getImageOrigin (double origin[3]) const
Get the image origin.
FWDATATOOLS_API void getImageDataSize (int size[3]) const
Get the image data size (number of slices).
FWDATATOOLS_API void getImageSize (double size[3]) const
Get the image size (= dataSize * spacing).
FWDATATOOLS_API void getCurrentSliceCenter (double center[3])
Get the slice center.
FWDATATOOLS_API void worldToSliceIndex (const double world[3], int index[3])
Convert world coordinates to slice index coordinates.
FWDATATOOLS_API void worldToImageSliceIndex (const double world[3], int index[3])
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void sliceIndexToWorld (const int index[3], double world[3])
Convert from world coordinates system to image coordinates system.
FWDATATOOLS_API::fwData::Image::sptr getImage () const
Return the image.
template<typename FLOAT_ARRAY_3 >
void getImageSpacing (FLOAT_ARRAY_3 spacing)
Get the image spacing.
template<typename INT_INDEX >
void getImageDataSize (INT_INDEX size)
Get the image data size (number of slices).
template<typename WORLD , typename INT_INDEX >
void worldToSliceIndex (const WORLD world, INT_INDEX *index)
Convert world coordinates to slice index coordinates.
template<typename WORLD , typename INT_INDEX >
void worldToImageSliceIndex (const WORLD world, INT_INDEX *index)
Convert coordinates in the world to coordinates in the image.
FWDATATOOLS_API void getPlane (double points[4][3], int sliceNumber)
Return the 4 points of the image plane.
FWDATATOOLS_API bool setSliceIndex (const int index[3])
Set the slice index.
FWDATATOOLS_API void getSliceIndex (::fwData::Integer::sptr index[3])
Get the slice index.
FWDATATOOLS_API void updateImageInfos (::fwData::Image::sptr image)
Update the image information (slice index, min/max,...)
FWDATATOOLS_API void createTransferFunction (::fwData::Image::sptr image)
Create and set the default transfer function.
FWDATATOOLS_API void setOrCreateTF (const ::fwData::TransferFunction::sptr &_tf, const fwData::Image::sptr &_image)
Sets the transfer function, creates one if _tf is null (.
FWDATATOOLS_API::fwData::TransferFunction::sptr getTransferFunction () const
Get the current transfer function.
FWDATATOOLS_API void installTFConnections ()
Install connections to listen TF modifications.
FWDATATOOLS_API void removeTFConnections ()
Remove the TF connections.
FWDATATOOLS_API void installTFSlots (::fwCom::HasSlots *hasslots)
Install the slots to managed TF modifications.
virtual FWDATATOOLS_API void updateTFPoints ()
Slot: called when transfer function points are modified.
virtual FWDATATOOLS_API void updateTFWindowing (double window, double level)
Slot: called when transfer function windowing is modified.
Protected Member Functions inherited from fwRenderVTK::IAdaptor
FWRENDERVTK_API IAdaptor () noexcept
constructor
virtual FWRENDERVTK_API ~IAdaptor () noexcept
destructor
FWRENDERVTK_API void configureParams ()
Parse the xml configuration for renderer, picker and transform.
FWRENDERVTK_API void initialize ()
Initialize the adaptor with the associated render service. (must be call in starting).
FWRENDERVTK_API void registerProp (vtkProp *prop)
Registers the vtkProp.
FWRENDERVTK_API void unregisterProps ()
Unregisters all the vtkProp.
FWRENDERVTK_API void addToRenderer (vtkProp *prop)
Adds the vtkProp to the renderer.
FWRENDERVTK_API void removeAllPropFromRenderer ()
Removes all the vtkProp from the renderer.
FWRENDERVTK_API void addToPicker (vtkProp *prop, std::string pickerId="")
Adds the vtkProp to the picking list.
FWRENDERVTK_API void removeFromPicker (vtkProp *prop, std::string pickerId="")
Removes the vtkProp to the picking list.
FWRENDERVTK_API void requestRender ()
notify a render request iff vtkPipeline is modified
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual void swapping ()
Swap the service from associated object to another object.
virtual void swapping (const KeyType &key)
Swap the service from an associated object to another object. The key in parameter indicates allows to retrieve the new data with getInput(), getInOut() or getOutput(). If you need the old object, you need to keep a shared pointer on it inside your service implementation.
virtual FWSERVICES_API void reconfiguring ()
Reconfigure the service activity when is started.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Protected Member Functions inherited from fwServices::IHasServices
FWSERVICES_API IHasServices () noexcept
Constructor.
virtual FWSERVICES_API ~IHasServices () noexcept
Destructor.
FWSERVICES_API std::shared_ptr< ::fwServices::IService > registerService (const std::string &_implType, const std::string &_id="")
Register a new service linked to this service.
template<class T >
std::shared_ptr< T > registerService (const std::string &_implType, const std::string &_id="")
Register a new service linked to this service.
FWSERVICES_API void unregisterService (const ::fwTools::fwID::IDType &_id)
Unregister a specific service.
FWSERVICES_API void unregisterService (const ::fwServices::IService::sptr &_service)
Unregister a specific service.
FWSERVICES_API void unregisterServices (const std::string &_implType="")
Unregister all services linked to this service, optionally matches only a given type of services.
Protected Attributes
float m_priority
vtkCommand * m_vtkObserver
vtkActor2D * m_textActor
vtkTextMapper * m_textMapper
vtkPolyData * m_cursorPolyData
vtkPolyDataMapper * m_cursorMapper
vtkActor * m_cursorActor
Protected Attributes inherited from fwDataTools::helper::MedicalImageAdaptor
Orientation m_orientation
Image orientation.
::fwData::Integer::sptr m_axialIndex
Axial slice index.
::fwData::Integer::sptr m_frontalIndex
Frontal slice index.
::fwData::Integer::sptr m_sagittalIndex
Sagittal slice index.
UpdateTFPointsSlotType::sptr m_slotUpdateTFPoints
Slot called when transfer function points are modified.
UpdateTFWindowingSlotType::sptr m_slotUpdateTFWindowing
Slot called when transfer function windowing is modified.
Protected Attributes inherited from fwRenderVTK::IAdaptor
bool m_vtkPipelineModified
state of the pipeline
SRender::RendererIdType m_rendererId
SRender::PickerIdType m_pickerId
SRender::VtkObjectIdType m_transformId
SRender::wptr m_renderService
vtkPropCollection * m_propCollection
::fwCom::helper::SigSlotConnection m_connections
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
std::shared_ptr< ::fwTools::UUID > m_uuid
UUID used to identify the object, notably for serialization.
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Friends
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const override
return object's classname without its namespace, i.e. BaseObject
virtual const std::string & getClassname () const override
return full object's classname with its namespace, i.e. fwCore::BaseObject
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Additional Inherited Members
Public Types inherited from fwDataTools::helper::MedicalImageAdaptor
enum Orientation { X_AXIS = 0, Y_AXIS, Z_AXIS }
Image orientation.
Public Types inherited from fwRenderVTK::IAdaptor
typedef fwServices::IService SuperClass
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > InOutMapType
typedef std::map< KeyType, std::shared_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef std::shared_future< void > SharedFutureType
Slot to call start method.
typedef std::packaged_task< void()> PackagedTaskType
Slot to call start method.
typedef std::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Public Types inherited from fwServices::IHasServices
typedef std::vector< std::weak_ptr< ::fwServices::IService > > ServiceVector
Protected Types inherited from fwDataTools::helper::MedicalImageAdaptor
typedef ::fwCom::Slot< void()> UpdateTFPointsSlotType
Slot called when transfer function points are modified.
typedef ::fwCom::Slot< void(double, double)> UpdateTFWindowingSlotType
Slot called when transfer function points are modified.
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwRenderVTK::IAdaptor
static FWRENDERVTK_API void getProps (vtkPropCollection *outPropc, vtkProp *inProp)
Get all the vtkProp associated to the inProp (actors, actors2D, volumes)
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname without its namespace, i.e. BaseObject
static const std::string & classname ()
return object's classname without its namespace, i.e. BaseObject
Detailed Description
Cursor management: displays a red cross representing the image picked point.
Slots
updateSliceIndex(int axial, int frontal, int sagittal) : update image slice index
XML Configuration
 <service type="::visuVTKAdaptor::SProbeCursor" autoConnect="yes">
     <inout key="image" uid="..." />
     <config renderer="default" picker="negatodefault" transform="trf" />
 </service>
In-Out
image [fwData::Image]: image to display.
Configuration
config(mandatory) : contains the adaptor configuration
renderer (mandatory): defines the renderer to show the SProbeCursor.
picker (mandatory): identifier of the picker
transform (optional): the vtkTransform to associate to the adaptor
Definition at line 53 of file SProbeCursor.hpp.
Member Function Documentation
void visuVTKAdaptor::SProbeCursor::configuring () override protected virtual
Configure the service before starting. Apply the configuration to service.
See also
configure()
Implements fwServices::IService.
Definition at line 212 of file SProbeCursor.cpp.
Referenced by visuVTKAdaptor::SImagesProbeCursor::configuring().
fwServices::IService::KeyConnectionsMap visuVTKAdaptor::SProbeCursor::getAutoConnections () const override protected virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Image::s_MODIFIED_SIG to this::s_UPDATE_SLOT Connect Image::s_SLICE_INDEX_MODIFIED_SIG to this::s_UPDATE_SLICE_INDEX_SLOT Connect Image::s_BUFFER_MODIFIED_SIG to this::s_UPDATE_BUFFER_SLOT
Reimplemented from fwServices::IService.
Reimplemented in visuVTKAdaptor::SImagesProbeCursor.
Definition at line 431 of file SProbeCursor.cpp.
References fwData::Image::s_BUFFER_MODIFIED_SIG, fwData::Object::s_MODIFIED_SIG, and fwData::Image::s_SLICE_INDEX_MODIFIED_SIG.
void visuVTKAdaptor::SProbeCursor::starting () override protected virtual
Initialize the service activity.
Use configuration to start his job. For example : the start method installs a button in a frame and show the frame.
See also
start()
Implements fwServices::IService.
Definition at line 241 of file SProbeCursor.cpp.
Referenced by visuVTKAdaptor::SImagesProbeCursor::starting().
void visuVTKAdaptor::SProbeCursor::stopping () override protected virtual
Uninitialize the service activity. The stop() method is always invoked before destroying a service.
See also
stop()
Implements fwServices::IService.
Definition at line 286 of file SProbeCursor.cpp.
References fwDataTools::helper::Image::getPixelAsString(), OSLM_TRACE, and SLM_ASSERT.
Referenced by visuVTKAdaptor::SImagesProbeCursor::stopping().
void visuVTKAdaptor::SProbeCursor::updating () override protected virtual
Perform some computations according to object (this service is attached to) attribute values and its internal state.
See also
update()
Implements fwServices::IService.
Definition at line 274 of file SProbeCursor.cpp.
References SLM_ASSERT.
The documentation for this class was generated from the following files:
SProbeCursor.hpp
SProbeCursor.cpp