fw4spl: fwGdcmIO::reader::Series Class Reference
fwGdcmIO::reader::Series Class Reference
Series class used to read Series.
#include <Series.hpp>
Public Types
typedef std::map< std::shared_ptr< ::fwGdcmIO::container::DicomInstance >,::fwMedData::Series::sptr > SeriesContainerMapType
typedef std::function< void(std::uint64_t) > ProgressCallback
typedef std::function< bool() > CancelRequestedCallback
Public Member Functions
FWGDCMIO_API Series ()
Constructor.
FWGDCMIO_API ~Series ()
Destructor.
FWGDCMIO_API::fwMedData::Series::sptr read (const ::fwMedData::DicomSeries::csptr &dicomSeries) throw (::fwGdcmIO::exception::Failed)
Read DICOM series.
const ::fwLog::Logger::sptr & getLogger () const
Get Logger.
void setLogger (const ::fwLog::Logger::sptr &logger)
Set Logger.
void setProgressCallback (ProgressCallback callback)
Set progress callback.
void setCancelRequestedCallback (CancelRequestedCallback callback)
Set cancel callback.
void setBufferRotationEnabled (bool enabled)
Enable buffer rotation.
Protected Member Functions
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > getSpatialFiducialsReferencedSeriesInstance (const ::fwMedData::DicomSeries::csptr &dicomSeries)
Get referenced series when dealing with Spatial Fiducials.
std::shared_ptr< ::fwGdcmIO::container::DicomInstance > getStructuredReportReferencedSeriesInstance (const ::fwMedData::DicomSeries::csptr &dicomSeries)
Get referenced series when dealing with Structured Report.
Protected Attributes
SeriesContainerMapType m_seriesContainerMap
Series Container Map.
::fwLog::Logger::sptr m_logger
Logger.
ProgressCallback m_progressCallback
Progress callback for jobs.
CancelRequestedCallback m_cancelRequestedCallback
Cancel information for jobs.
bool m_enableBufferRotation
Enable buffer rotation.
Detailed Description
Series class used to read Series.
Definition at line 21 of file io/fwGdcmIO/include/fwGdcmIO/reader/Series.hpp.
Member Function Documentation
fwMedData::Series::sptr fwGdcmIO::reader::Series::read (const ::fwMedData::DicomSeries::csptr & dicomSeries) throw (::fwGdcmIO::exception::Failed)
Read DICOM series.
Parameters
[in] dicomSeries DICOM series that shall be read
Definition at line 53 of file io/fwGdcmIO/src/fwGdcmIO/reader/Series.cpp.
References fwDicomTools::Series::convertToImageSeries(), fwDicomTools::Series::convertToModelSeries(), getSpatialFiducialsReferencedSeriesInstance(), getStructuredReportReferencedSeriesInstance(), m_cancelRequestedCallback, m_enableBufferRotation, m_logger, m_progressCallback, m_seriesContainerMap, fwGdcmIO::reader::iod::ComprehensiveSRIOD::read(), fwGdcmIO::reader::iod::SpatialFiducialsIOD::read(), fwGdcmIO::reader::iod::CTMRImageIOD::read(), fwGdcmIO::reader::iod::SurfaceSegmentationIOD::read(), fwGdcmIO::reader::iod::CTMRImageIOD::setBufferRotationEnabled(), SLM_ASSERT, and SPTR.
void fwGdcmIO::reader::Series::setCancelRequestedCallback (CancelRequestedCallback callback) inline
Set cancel callback.
Parameters
[in] callback Cancel callback
Definition at line 67 of file io/fwGdcmIO/include/fwGdcmIO/reader/Series.hpp.
void fwGdcmIO::reader::Series::setProgressCallback (ProgressCallback callback) inline
Set progress callback.
Parameters
[in] callback Progress callback
Definition at line 59 of file io/fwGdcmIO/include/fwGdcmIO/reader/Series.hpp.
The documentation for this class was generated from the following files:
io/fwGdcmIO/include/fwGdcmIO/reader/Series.hpp
io/fwGdcmIO/src/fwGdcmIO/reader/Series.cpp