fw4spl: fwDataTools::helper::Array Class Reference
fwDataTools::helper::Array Class Reference
Helper to manage array buffer. Lock the buffer before to modify it.
#include <Array.hpp>
Public Member Functions
virtual bool isA (const std::string &type) const
FWDATATOOLS_API Array (::fwData::Array::sptr array)
virtual FWDATATOOLS_API void setItem (const ::fwData::Array::IndexType &id, const void *value)
Setter for one item components of the array.
virtual FWDATATOOLS_API void setItem (const ::fwData::Array::IndexType &id, const size_t component, const void *value)
Setter for one item component of the array.
virtual FWDATATOOLS_API void * getItem (const ::fwData::Array::IndexType &id, const size_t component=0)
Getter for a buffer item. pointer to the requested item in the buffer.
template<typename T >
T * getItem (const ::fwData::Array::IndexType &id, const size_t component=0)
Typed version of getItem.
virtual FWDATATOOLS_API void getItem (const ::fwData::Array::IndexType &id, void *value) const
Copies the data into the buffer pointed by
virtual FWDATATOOLS_API void getItem (const ::fwData::Array::IndexType &id, const size_t component, void *value) const
FWDATATOOLS_API void setBuffer (void *buf, bool takeOwnership, const ::fwTools::Type &type, const ::fwData::Array::SizeType &size, size_t nbOfComponents)
Setter for the array buffer.
virtual FWDATATOOLS_API char * begin ()
Returns the begining/end of the buffer interpreted as a char buffer.
virtual FWDATATOOLS_API char * end ()
virtual FWDATATOOLS_API const char * begin () const
virtual FWDATATOOLS_API const char * end () const
template<typename T >
T * begin ()
Returns the begining/end of the buffer, casted to T.
template<typename T >
T * end ()
FWDATATOOLS_API::fwMemory::BufferObject::Lock getLock () const
Returns a copy of current lock on array.
virtual FWDATATOOLS_API void * getBuffer ()
Getter for the array buffer.
virtual FWDATATOOLS_API const void * getBuffer () const
Getter for the array buffer.
FWDATATOOLS_API char * getBufferPtr (const ::fwData::Array::IndexType &id, size_t component, size_t sizeOfType)
Get a pointer to the value described by given parameters.
FWDATATOOLS_API const char * getBufferPtr (const ::fwData::Array::IndexType &id, size_t component, size_t sizeOfType) const
Get a pointer to the value described by given parameters.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Protected Member Functions
virtual FWDATATOOLS_API void setBuffer (void *buf, bool takeOwnership=false)
Protected setter for the array buffer. An existing buffer will be released if the array own it.
Protected Attributes
::fwData::Array::sptr m_array
::fwMemory::BufferObject::Lock m_lock
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Helper to manage array buffer. Lock the buffer before to modify it.
Definition at line 27 of file ools/include/fwDataTools/helper/Array.hpp.
Member Function Documentation
void * fwDataTools::helper::Array::getBuffer () virtual
Getter for the array buffer.
Returns
Array's buffer, if exists, else NULL
Definition at line 30 of file ools/src/fwDataTools/helper/Array.cpp.
Referenced by fwDataTools::helper::ArrayGetter::begin(), fwDataTools::AlgoMeshDeformation::computeSimu(), fwDcmtkIO::reader::ImageStorageReader::directRead(), fwDcmtkIO::reader::ImageStorageReader::directRGBLookupRead(), fwDataTools::helper::ArrayGetter::getBufferPtr(), fwGdcmIO::helper::DicomSeriesWriter::processWrite(), fwGdcmIO::helper::DicomSeriesWriter::processWriteArchive(), fwDataIO::reader::GzArrayReader::read(), ioDicom::SSliceIndexDicomEditor::readImage(), ioPacs::SSliceIndexDicomPullerEditor::readImage(), fwDataTools::Mesh::shakeNormals(), Tuto15MultithreadCtrl::SReadArray::updating(), Tuto15MultithreadCtrl::SShowArray::updating(), Tuto15MultithreadCtrl::SIncrementArray::updating(), and fwDataIO::writer::GzArrayWriter::write().
const void * fwDataTools::helper::Array::getBuffer () const virtual
Getter for the array buffer.
Returns
Array's buffer, if exists, else NULL
Definition at line 37 of file ools/src/fwDataTools/helper/Array.cpp.
char * fwDataTools::helper::Array::getBufferPtr (const ::fwData::Array::IndexType & id, size_t component, size_t sizeOfType)
Get a pointer to the value described by given parameters.
Parameters
id Item id
component Item component id
sizeOfType size of a component
Returns
buffer item pointer
Definition at line 106 of file ools/src/fwDataTools/helper/Array.cpp.
Referenced by fwDataTools::helper::ArrayGetter::getItem().
const char * fwDataTools::helper::Array::getBufferPtr (const ::fwData::Array::IndexType & id, size_t component, size_t sizeOfType) const
Get a pointer to the value described by given parameters.
Parameters
id Item id
component Item component id
sizeOfType size of a component
Returns
buffer item pointer
Definition at line 116 of file ools/src/fwDataTools/helper/Array.cpp.
void * fwDataTools::helper::Array::getItem (const ::fwData::Array::IndexType & id, const size_t component = 0) virtual
Getter for a buffer item. pointer to the requested item in the buffer.
Parameters
id Item id
component Component id
Returns
Pointer to the requested item in the buffer
Definition at line 147 of file ools/src/fwDataTools/helper/Array.cpp.
template<typename T > T * fwDataTools::helper::Array::getItem (const ::fwData::Array::IndexType & id, const size_t component = 0)
Typed version of getItem.
Template Parameters
T Type in which the pointer will be returned
Parameters
id Item id
component Component id
Returns
Array buffer pointer casted to T
Definition at line 174 of file ools/include/fwDataTools/helper/Array.hpp.
void fwDataTools::helper::Array::getItem (const ::fwData::Array::IndexType & id, void * value) const virtual
Copies the data into the buffer pointed by
Parameters
id Item id
[out] value Buffer to write into
Definition at line 156 of file ools/src/fwDataTools/helper/Array.cpp.
void fwDataTools::helper::Array::setBuffer (void * buf, bool takeOwnership, const ::fwTools::Type & type, const ::fwData::Array::SizeType & size, size_t nbOfComponents)
Setter for the array buffer.
An existing buffer will be released if the array own it.
Parameters
buf Buffer to set as Array's buffer
takeOwnership if true, the Array will manage allocation and destroy the buffer when needed.
type Type of the array view
size Size of the array view
nbOfComponents Number of components of the array view, Min value : 1
Definition at line 65 of file ools/src/fwDataTools/helper/Array.cpp.
Referenced by fwItkIO::dataImageFactory(), and fwGdcmIO::reader::ie::Image::readImagePixelModule().
void fwDataTools::helper::Array::setBuffer (void * buf, bool takeOwnership = false) protected virtual
Protected setter for the array buffer. An existing buffer will be released if the array own it.
Parameters
buf Buffer to set as Array's buffer
takeOwnership if true, the Array will manage allocation and destroy the buffer when needed.
Definition at line 44 of file ools/src/fwDataTools/helper/Array.cpp.
void fwDataTools::helper::Array::setItem (const ::fwData::Array::IndexType & id, const void * value) virtual
Setter for one item components of the array.
Parameters
id Item id
value Valid buffer of elements of type <m_type> with a length equal to <m_nbOfComponents> to be copied to array 'id'
Definition at line 126 of file ools/src/fwDataTools/helper/Array.cpp.
void fwDataTools::helper::Array::setItem (const ::fwData::Array::IndexType & id, const size_t component, const void * value) virtual
Setter for one item component of the array.
Parameters
id Item id
component Component id to write data in.
value Valid buffer of elements of type <m_type> with a length equal to <m_nbOfComponents> to be copied to array 'id', component n 'component'
Definition at line 136 of file ools/src/fwDataTools/helper/Array.cpp.
The documentation for this class was generated from the following files:
ools/include/fwDataTools/helper/Array.hpp
ools/src/fwDataTools/helper/Array.cpp