fw4spl: scene2D::Render Class Reference
scene2D::Render Class Reference
Scene2D rendering class.
#include <Render.hpp>
Public Types
typedef std::string AdaptorIDType
A string type representing adaptors id.
typedef std::string ObjectIDType
A string type representing objects id.
typedef float AdaptorZValueType
A float type representing adaptors zValue.
Public Types inherited from fwServices::IService
enum AccessType : std::uint8_t { INPUT, OUTPUT, INOUT }
typedef ::boost::property_tree::ptree ConfigType
typedef std::string IdType
typedef std::string KeyType
typedef std::map< KeyType, std::weak_ptr< const ::fwData::Object > > InputMapType
typedef std::map< KeyType, std::weak_ptr< ::fwData::Object > > OutputMapType
enum GlobalStatus {
STARTED, STARTING, SWAPPING, STOPPED,
STOPPING
}
Defines all possible global status for a service, including transitions.
enum UpdatingStatus { UPDATING, NOTUPDATING }
Defines all possible status for an update process.
enum ConfigurationStatus { CONFIGURING, CONFIGURED, UNCONFIGURED }
Defines all possible status for a configuration process.
typedef ::fwCom::Signal< void()> StartedSignalType
typedef ::fwCom::Signal< void()> UpdatedSignalType
typedef ::fwCom::Signal< void()> StoppedSignalType
typedef ::boost::shared_future< void > SharedFutureType
Slot to call start method.
typedef ::boost::packaged_task< void > PackagedTaskType
Slot to call start method.
typedef ::boost::future< void > UniqueFutureType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StartSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> StopSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType()> UpdateSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(::fwData::Object::sptr)> SwapSlotType
Slot to call start method.
typedef ::fwCom::Slot< SharedFutureType(const KeyType &,::fwData::Object::sptr)> SwapKeySlotType
Slot to call start method.
typedef ::fwCom::helper::SigSlotConnection::KeyConnectionsType KeyConnectionsType
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Types inherited from fwCom::HasSlots
typedef std::shared_ptr< HasSlots > sptr
typedef std::shared_ptr< const HasSlots > csptr
Public Types inherited from fwCom::HasSignals
typedef std::shared_ptr< HasSignals > sptr
typedef std::shared_ptr< const HasSignals > csptr
Public Member Functions
virtual bool isA (const std::string &type) const
SCENE2D_API Render () throw ()
Constructor, set coordinates m_sceneStart to (-100, -100), m_sceneWidth to (200, 200) and add new handle events.
virtual SCENE2D_API ~Render () throw ()
Basic destructor, do nothing.
SCENE2D_API QGraphicsScene * getScene () const
Get the scene.
SCENE2D_API Scene2DGraphicsView * getView () const
Get the view.
SCENE2D_API std::shared_ptr< ::scene2D::data::Viewport > getViewport ()
Get the viewport.
SCENE2D_API std::shared_ptr< ::fwData::Object > getRegisteredObject (ObjectIDType _objectID) const
Get the object referenced in m_objectID2Object by the key _objectID.
SCENE2D_API void dispatchInteraction (std::shared_ptr< ::scene2D::data::Event > _event)
Iterate on the m_zValue2AdaptorID map and, if the event hasn't been accepted yet, call the adaptor processInteraction function.
SCENE2D_API::scene2D::data::Coord mapToScene (const ::scene2D::data::Coord &coord) const
Returns the viewport coordinate point mapped to scene coordinates.
SCENE2D_API Qt::AspectRatioMode getAspectRatioMode () const
Returns what happens to scene's aspect ratio on view resize events.
SCENE2D_API void updateSceneSize (float ratioPercent=0)
Update scene size from items bounding rect, this bounding can be enlarged with ratioPercent parameter.
virtual SCENE2D_API KeyConnectionsType getObjSrvConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
virtual SCENE2D_API KeyConnectionsMap getAutoConnections () const
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Public Member Functions inherited from fwRender::IRender
Public Member Functions inherited from fwGui::IGuiContainerSrv
FWGUI_API::fwGui::container::fwContainer::sptr getContainer ()
FWGUI_API void setParent (std::string wid)
Public Member Functions inherited from fwServices::IService
FWSERVICES_API void setConfiguration (const ::fwRuntime::ConfigurationElement::sptr _cfgElement)
Affect the configuration, using a generic XML like structure.
FWSERVICES_API void setConfiguration (const Config &_configuration)
Set the configuration.
FWSERVICES_API void setConfiguration (const ConfigType &ptree)
Affect the configuration, using a boost property tree.
FWSERVICES_API void configure ()
Invoke configuring() if m_globalState == STOPPED. Invoke reconfiguring() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType start ()
Invoke starting() if m_globalState == STOPPED. Does nothing otherwise.
FWSERVICES_API SharedFutureType stop ()
Invoke stopping() if m_globalState == STARTED. Does nothing otherwise. Stops all observations.
FWSERVICES_API SharedFutureType update ()
Invoke updating() if m_globalState == STARTED. Does nothing otherwise.
FWSERVICES_API SharedFutureType swap (::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API SharedFutureType swapKey (const KeyType &_key,::fwData::Object::sptr _obj)
Associate the service to another object.
FWSERVICES_API GlobalStatus getStatus () const throw ()
Return the global process status.
FWSERVICES_API bool isStarted () const throw ()
Test if the service is started or not.
FWSERVICES_API bool isStopped () const throw ()
Test if the service is stopped or not.
FWSERVICES_API ConfigurationStatus getConfigurationStatus () const throw ()
Return the configuration process status.
FWSERVICES_API UpdatingStatus getUpdatingStatus () const throw ()
Return the update process status.
FWSERVICES_API::fwRuntime::ConfigurationElement::sptr getConfiguration () const
Return the configuration, in an xml format read using runtime library.
FWSERVICES_API ConfigType getConfigTree () const
Return the configuration, in an boost property tree.
FWSERVICES_API::fwData::Object::sptr getObject ()
Return the object associated to service.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getObject ()
Return the object associated to service. The object is casted.
FWSERVICES_API const InputMapType & getInputs () const
Return the inputs map associated to service.
FWSERVICES_API const OutputMapType & getInOuts () const
Return the inouts map associated to service.
FWSERVICES_API std::vector< ::fwData::Object::csptr > getObjects () const
Return the objects associated to service.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &key) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &key) const
Return the inout object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< const DATATYPE > getInput (const KeyType &keybase, size_t index) const
Return the input object at the given key. Asserts if the data is not of the right type.
template<class DATATYPE >
std::shared_ptr< DATATYPE > getInOut (const KeyType &keybase, size_t index) const
Return the inout object at the given key. Asserts if the data is not of the right type.
FWSERVICES_API void setOutput (const ::fwServices::IService::KeyType &key, const ::fwData::Object::sptr &object, size_t index=0)
Register an output object at a given key in the OSR, replacing it if it already exists.
size_t getKeyGroupSize (const KeyType &keybase) const
Return the number of key in a group of keys.
FWSERVICES_API void setWorker (std::shared_ptr< ::fwThread::Worker > worker)
Initializes m_associatedWorker and associates this worker to all service slots.
FWSERVICES_API std::shared_ptr< ::fwThread::Worker > getWorker () const
Returns associate worker.
FWSERVICES_API IdType getObjectId (const KeyType &_key) const
Return the id of the object, throw if it is not found.
FWSERVICES_API void setObjectId (const KeyType &_key, const IdType &_id)
Set the id of an object key.
Public Member Functions inherited from fwTools::Object
FWTOOLS_API std::string className () const
return the sub class classname : an alias of this->getClassname
FWTOOLS_API void modified ()
FWTOOLS_API void timeModified ()
FWTOOLS_API void setLifePeriod (::fwCore::TimeStamp::TimeStampType p)
FWTOOLS_API::fwCore::TimeStamp::TimeStampType getLifePeriod ()
FWTOOLS_API bool periodExpired ()
::fwCore::TimeStamp::sptr getTimeStamp () const
::fwCore::LogicStamp::sptr getLogicStamp () const
::fwCore::LogicStamp::csptr getOSRKey () const
void setName (const std::string _strName)
Set a name for an object.
const std::string getName () const
Retrieve the name object.
Public Member Functions inherited from fwCore::BaseObject
Public Member Functions inherited from fwCom::HasSlots
std::shared_ptr< SlotBase > slot (const Slots::SlotKeyType &key) const
template<typename SlotType >
std::shared_ptr< SlotType > slot (const Slots::SlotKeyType &key) const
template<typename F , typename A >
std::shared_ptr< Slot< typename::fwCom::util::convert_function_type< F >::type > > newSlot (const Slots::SlotKeyType &key, F f, A a)
Public Member Functions inherited from fwCom::HasSignals
std::shared_ptr< SignalBase > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > signal (const Signals::SignalKeyType &key) const
template<typename SignalType >
std::shared_ptr< SignalType > newSignal (const Signals::SignalKeyType &key)
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Static Public Member Functions inherited from fwRender::IRender
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwGui::IGuiContainerSrv
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwServices::IService
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static FWSERVICES_API void setVersion (int version)
static FWSERVICES_API bool isVersion2 ()
Streaming a service.
Static Public Member Functions inherited from fwTools::Object
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Static Public Member Functions inherited from fwCore::BaseObject
static bool isTypeOf (const std::string &type)
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Member Functions
SCENE2D_API void configuring () throw (::fwTools::Failed)
Configuring the Render service.
SCENE2D_API void starting () throw (::fwTools::Failed)
Call startContext to set the scene, the viewport and the view, and add'em to the QtContainer and start the adaptors.
SCENE2D_API void updating () throw (::fwTools::Failed)
Do nothing.
SCENE2D_API void swapping () throw (::fwTools::Failed)
Swap the service from associated object to another object.
SCENE2D_API void swapping (const KeyType &key) throw (::fwTools::Failed)
Start/stop adaptors.
SCENE2D_API void stopping () throw (::fwTools::Failed)
Stop all the adaptors attached to the render related composite, stop all those rattached to the objects contained.
Protected Member Functions inherited from fwRender::IRender
FWRENDER_API IRender () throw ()
Constructor. Initialize default values.
virtual FWRENDER_API ~IRender () throw ()
Destructor. Do nothing.
Protected Member Functions inherited from fwGui::IGuiContainerSrv
FWGUI_API void initialize ()
Initialize managers.
FWGUI_API void create ()
Creates view, sub-views and toolbar containers. Manages sub-views and toobar services.
FWGUI_API void destroy ()
Stops sub-views and toobar services. Destroys view, sub-views and toolbar containers.
Protected Member Functions inherited from fwServices::IService
FWSERVICES_API IService ()
IService constructor.
virtual FWSERVICES_API ~IService ()
IService desctructor.
virtual FWSERVICES_API void reconfiguring () throw (::fwTools::Failed)
Reconfigure the service activity when is started.
virtual FWSERVICES_API void info (std::ostream &_sstream)
Write information in a stream.
Protected Member Functions inherited from fwTools::fwID
FWTOOLS_API bool hasID () const
Return true if the object has an id set.
FWTOOLS_API IDType getID (Policy policy=GENERATE) const
Returns the id of the object. If it is not set and the policy value is.
virtual FWTOOLS_API void setID (IDType newID)
Set a newID for the object, (newID must not exist in fwID), the oldest one is released.
FWTOOLS_API void resetID ()
Release the id for the object.
fwID ()
Constructor : does nothing.
Protected Member Functions inherited from fwCom::HasSlots
HasSlots (const HasSlots &)
Copy constructor forbidden.
HasSlots & operator= (const HasSlots &)
Copy operator forbidden.
Protected Member Functions inherited from fwCom::HasSignals
HasSignals (const HasSignals &)
Copy constructor forbidden.
HasSignals & operator= (const HasSignals &)
Copy operator forbidden.
Friends
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Additional Inherited Members
Static Public Attributes inherited from fwServices::IService
static FWSERVICES_API const std::string s_DEFAULT_OBJECT = "defaultObject"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STARTED_SIG = "started"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATED_SIG = "updated"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOPPED_SIG = "stopped"
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_START_SLOT = "start"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_STOP_SLOT = "stop"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_UPDATE_SLOT = "update"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAP_SLOT = "swap"
Slot to call start method.
static FWSERVICES_APIconst::fwCom::Slots::SlotKeyType s_SWAPKEY_SLOT = "swapKey"
Slot to call start method.
Protected Types inherited from fwGui::IGuiContainerSrv
typedef ::fwRuntime::ConfigurationElement::sptr ConfigurationType
Protected Types inherited from fwTools::fwID
enum Policy { EMPTY = 1, GENERATE, MUST_EXIST }
typedef std::string IDType
Static Protected Member Functions inherited from fwTools::fwID
static bool isTypeOf (const std::string &type)
static FWTOOLS_API bool exist (IDType _id)
static FWTOOLS_API std::shared_ptr< ::fwTools::Object > getObject (IDType requestID)
Retrieve the object attached to the given id. Return a null sptr if no correspondence exist.
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Protected Attributes inherited from fwServices::IService
::fwRuntime::ConfigurationElement::sptr m_configuration
Configuration element used to configure service internal state using a generic XML like structure TODO Make this const, we are not supposed to edit that !
::fwData::Object::wptr m_associatedObject
associated object of service
StartSlotType::sptr m_slotStart
Slot to call start method.
StopSlotType::sptr m_slotStop
Slot to call stop method.
UpdateSlotType::sptr m_slotUpdate
Slot to call update method.
SwapSlotType::sptr m_slotSwap
Slot to call swap method.
SwapKeySlotType::sptr m_slotSwapKey
Slot to call swap method.
std::shared_ptr< ::fwThread::Worker > m_associatedWorker
Associated worker.
Protected Attributes inherited from fwTools::Object
::fwCore::TimeStamp::sptr m_timeStamp
::fwCore::LogicStamp::sptr m_logicStamp
std::shared_ptr< ::fwTools::UUID > m_uuid
Protected Attributes inherited from fwCom::HasSlots
Slots m_slots
Protected Attributes inherited from fwCom::HasSignals
Signals m_signals
Static Protected Attributes inherited from fwGui::IGuiContainerSrv
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SET_ENABLED_SLOT = "setEnabled"
Slot to enable/disable the action.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_ENABLE_SLOT = "enable"
Slot to enable the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_DISABLE_SLOT = "disable"
Slot to disable the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SET_VISIBLE_SLOT = "setVisible"
Slot to show/hide the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_SHOW_SLOT = "show"
Slot to show the container.
static FWGUI_APIconst::fwCom::Slots::SlotKeyType s_HIDE_SLOT = "hide"
Slot to hide the container.
Detailed Description
Scene2D rendering class.
Definition at line 45 of file Render.hpp.
Member Function Documentation
void scene2D::Render::configuring () throw (::fwTools::Failed) protected virtual
Configuring the Render service.
Example of configuration
 <service uid="GENERIC_UID_Scene2D" impl="::scene2D::Render" type="::fwRender::IRender" autoConnect="yes">
  <scene>
      <scene x="-1100" y="-1.1" width="2500" height="1.2" />
      <viewport id="view1" x="-500" y="-1.1" width="500" height="1.2" />
      <axis id="xAxis" origin="0.0" scale="1.0" scaleType="LINEAR" />
      <axis id="yAxis" origin="0.0" scale="-1.0" scaleType="LINEAR" />
      <axis id="axeHistogramY" origin="0.0" scale="-0.000005" scaleType="LINEAR" />
      <adaptor id="grid" class="::scene2D::adaptor::GridFromFloat" objectId="myData">
          <config xMin="-1200" xMax="1500" yMin="-0.7" yMax="1.7" xSpacing="100" ySpacing="0.1"
              color="darkGray" xAxis="xAxis" yAxis="yAxis" zValue="1"/>
      </adaptor>
      <connect>
          <signal>adaptorUID/modified</signal>
          <slot>serviceUid/updateTM</slot>
      </connect>
      <connect waitForKey="myData">
          <signal>adaptorUID/modified</signal>
          <slot>serviceUid/updateTM</slot>
      </connect>
      <connect waitForKey="myData">
          <signal>modified</signal><!-- signal for object "myData" -->
          <slot>serviceUid/updateTM</slot>
      </connect>
  </scene>
 </service>
<scene x="-1100" y="-1.1" width="2500" height="1.2" /> : Set the scene coordinates
x : mandatory : Set the x coordinate of the top left scene corner
y : mandatory : Set the y coordinate of the top left scene corner
width : mandatory : Set the width of the scene
height : mandatory : Set the height of the scene
antialiasing : not mandatory : activate scene antialiasing if attribute's value set to 'true'
<viewport id="view1" x="-500" y="-1.1" width="500" height="1.2" /> : Set a viewport coordinates
id : mandatory : Set the viewport id
x : mandatory : Set the x coordinate of the top left viewport corner
y : mandatory : Set the y coordinate of the top left viewport corner
width : mandatory : Set the width of the viewport
height : mandatory : Set the height of the viewport
<axis id="xAxis" origin="0.0" scale="1.0" scaleType="LINEAR" /> : Set an axis specifications
id : mandatory : Set the axis id
origin : mandatory : Set the axis origin
scale : mandatory : Set the axis scale
scaleType : mandatory : Set the axis scaleType
<adaptor id="grid" class="::scene2D::adaptor::GridFromFloat" objectId="myData"> : Set an adaptor
id : mandatory : Set the adaptor id
class : mandatory : Set the adaptor type
objectId : mandatory : Set the adaptor related object id
uid : no mandatory : Set the adaptor uid
connect : not mandatory, connects signal to slot
waitForKey : not mandatory, defines the required object key for the signal/slot connection
signal : mandatory, must be signal holder UID, followed by '/', followed by signal name. To use the object (defined by waitForKey) signal, you don't have to write object uid, only the signal name.
slot : mandatory, must be slot holder UID, followed by '/', followed by slot name
Implements fwServices::IService.
Definition at line 124 of file Render.cpp.
References fwGui::IGuiContainerSrv::initialize(), fwServices::IService::m_configuration, OSLM_ASSERT, SLM_ASSERT, and SLM_TRACE_FUNC.
fwServices::IService::KeyConnectionsMap scene2D::Render::getAutoConnections () const virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Composite::s_ADDED_OBJECTS_SIG to this::s_UPDATE_OBJECTS_SLOT Connect Composite::s_CHANGED_OBJECTS_SIG to this::s_UPDATE_OBJECTS_SLOT Connect Composite::s_REMOVED_OBJECTS_SIG to this::s_UPDATE_OBJECTS_SLOT
Reimplemented from fwServices::IService.
Definition at line 805 of file Render.cpp.
References fwData::Composite::s_ADDED_OBJECTS_SIG, fwData::Composite::s_CHANGED_OBJECTS_SIG, fwServices::IService::s_DEFAULT_OBJECT, and fwData::Composite::s_REMOVED_OBJECTS_SIG.
fwServices::IService::KeyConnectionsType scene2D::Render::getObjSrvConnections () const virtual
Returns proposals to connect service slots to associated object signals, this method is used for obj/srv auto connection.
Connect Composite::s_ADDED_OBJECTS_SIG to this::s_ADD_OBJECTS_SLOT Connect Composite::s_CHANGED_OBJECTS_SIG to this::s_CHANGE_OBJECTS_SLOT Connect Composite::s_REMOVED_OBJECTS_SIG to this::s_REMOVE_OBJECTS_SLOT
Reimplemented from fwServices::IService.
Definition at line 793 of file Render.cpp.
References fwData::Composite::s_ADDED_OBJECTS_SIG, fwData::Composite::s_CHANGED_OBJECTS_SIG, and fwData::Composite::s_REMOVED_OBJECTS_SIG.
scene2D::data::Coord scene2D::Render::mapToScene (const ::scene2D::data::Coord & coord) const
Returns the viewport coordinate point mapped to scene coordinates.
Returns the viewport coordinate point mapped to scene coordinates.
Definition at line 114 of file Render.cpp.
void scene2D::Render::swapping () throw (::fwTools::Failed) protected virtual
Swap the service from associated object to another object.
See also
swap()
Deprecated:
use swapping(const KeyType& key) instead
Reimplemented from fwServices::IService.
Definition at line 310 of file Render.cpp.
References fwServices::helper::Config::disconnectProxies(), fwServices::IService::info(), fwServices::IService::isVersion2(), and SLM_TRACE_FUNC.
The documentation for this class was generated from the following files:
Render.hpp
Render.cpp