fw4spl: build_docset Namespace Reference
build_docset Namespace Reference
Functions
def bootstrap_docset ()
def gather_sources ()
def parse_related_pages ()
def file_repo (f_soup)
def parse_file (f_)
def populate_db (conn_, services)
def copy_files ()
def main ()
Variables
CFG = dict()
REPO_NAMES = dict()
CLASS_FILE_RE = re.compile(r'class([a-zA-Z_][a-zA-Z0-9_]*)_1_1([a-zA-Z_][a-zA-Z0-9_]*)\.html')
CLASS_RE = re.compile('fw4spl: (.+) Class Reference')
STRUCT_FILE_RE = re.compile(r'struct([a-zA-Z_][a-zA-Z0-9_]*)_1_1([a-zA-Z_][a-zA-Z0-9_]*)\.html')
STRUCT_RE = re.compile('fw4spl: (.+) Struct Reference')
NAMESPACE_FILE_RE = re.compile(r'namespace.+\.html')
NAMESPACE_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_:]*) Namespace Reference')
SRV_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_]*::(?:[a-zA-Z_][a-zA-Z0-9_]*::)*(S[A-Z0-9][a-zA-Z0-9_]*)) Class Reference')
BAD__SRV_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_]*::(?:[a-zA-Z_][a-zA-Z0-9_]*::)*([A-Z0-9][a-zA-Z0-9_]*)) Class Reference')
OBJ_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_]*::(?:[a-zA-Z_][a-zA-Z0-9_]*::)*([A-Z0-9][a-zA-Z0-9_]*)) Class Reference')
IFACE_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_]*::(?:[a-zA-Z_][a-zA-Z0-9_]*::)*(I[A-Z0-9][a-zA-Z0-9_]*|IService)) Class Reference')
EXCEPT_RE = re.compile('fw4spl: ([a-zA-Z_][a-zA-Z0-9_]*::(?:[a-zA-Z_][a-zA-Z0-9_]*::)*([A-Z0-9][a-zA-Z0-9_]*)) Struct Reference')
list FILE_SKIP_RE
Detailed Description
Generate a dash docset from a doxygen documentation.
Function Documentation
def build_docset.bootstrap_docset ()
Create the skeleton for the docset, i.e. the directory structure along with the SQLite database. Return the SQLite
database connection.
Definition at line 39 of file build_docset.py.
Referenced by main().
def build_docset.copy_files ()
Copy the doxygen HTML files into the docset destination.
Definition at line 261 of file build_docset.py.
Referenced by main().
def build_docset.file_repo (f_soup)
Return the name of the repository that a particular documentation file was generated from, or None if not possible.
Definition at line 83 of file build_docset.py.
Referenced by parse_file().
def build_docset.gather_sources ()
Return a list containing the paths to all interesting HTML files contained at the root of the Doxygen html
directory. We're not interested in what's in the subdirectories.
Definition at line 58 of file build_docset.py.
Referenced by main().
def build_docset.main (void)
Builds the dash docset.
Definition at line 273 of file build_docset.py.
References bootstrap_docset(), copy_files(), gather_sources(), parse_file(), parse_related_pages(), and populate_db().
def build_docset.parse_file (f_)
Parse a HTML file and return a (potentially empty) list of 3-tuples to add to the SQLite database.
Definition at line 97 of file build_docset.py.
References file_repo().
Referenced by main().
def build_docset.parse_related_pages ()
Parse the 'pages.html' doxygen file and generate the list of related pages.
Definition at line 68 of file build_docset.py.
Referenced by main().
def build_docset.populate_db (conn_, services)
Fill the sqlite database with the supplied list of (name, entry_type, file_path) triples.
Definition at line 249 of file build_docset.py.
Referenced by main().
Variable Documentation
list build_docset.FILE_SKIP_RE
Initial value:
 = [
     re.compile('pages.html'),
     re.compile(r'dir_.+\.html'),
     re.compile('.+_source.html')
 ]
Definition at line 33 of file build_docset.py.