fw4spl: fwTools::os Namespace Reference
fwTools::os Namespace Reference
Namespace fwTools::os contains tools methods which depend on os like get user application data directory.
Functions
FWTOOLS_API std::string getEnv (const std::string &name, bool *ok=NULL)
Returns a environment variable value.
FWTOOLS_API std::string getEnv (const std::string &name, const std::string &defaultValue)
Returns a environment variable value.
FWTOOLS_API std::string getUserDataDir (std::string company="", std::string appName="", bool createDirectory=false)
Return the users's application data directory.
Detailed Description
Namespace fwTools::os contains tools methods which depend on os like get user application data directory.
Date:
2009-2010.
Function Documentation
std::string fwTools::os::getEnv (const std::string & name, bool * ok = NULL)
Returns a environment variable value.
Parameters:
name environment variable 'name'
[out] ok boolean set to true if variable exists
Returns:
The environment variable content if it exists, else an empty string
Definition at line 18 of file Os.cpp.
Referenced by getEnv(), getUserDataDir(), and uiMedData::action::SExportSeries::updating().
std::string fwTools::os::getEnv (const std::string & name, const std::string & defaultValue)
Returns a environment variable value.
Parameters:
name environment variable 'name'
defaultValue Value returned if variable 'name' doesn't exist
Definition at line 31 of file Os.cpp.
References getEnv().
std::string fwTools::os::getUserDataDir (std::string company = "", std::string appName = "", bool createDirectory = false)
Return the users's application data directory.
Parameters:
company The company name
appName The application name
createDirectory if true, create the returned directory if it don't exist
Date:
2007-2009.
Return the application data directory. If company or appName is not empty, append them to the path. Under unix, XDG conventions are repected. For example, the UserDataDir under linux will be "~/.config/company/appName"
Definition at line 40 of file Os.cpp.
References getEnv(), OSLM_ERROR, and OSLM_INFO.