fw4spl: fwCore::HiResClock Namespace Reference
fwCore::HiResClock Namespace Reference
This namespace provides several function that returns a hi resolution EPOCH time.
Typedefs
typedef double HiResClockType
Type returned by HiResClock Functions.
Functions
FWCORE_API HiResClockType getTimeInMicroSec ()
FWCORE_API HiResClockType getTimeInMilliSec ()
FWCORE_API HiResClockType getTimeInSec ()
Detailed Description
This namespace provides several function that returns a hi resolution EPOCH time.
Warning:
EPOCH time has not the same reference on each operating system.
Function Documentation
HiResClockType fwCore::HiResClock::getTimeInMicroSec ()
Returns:
EPOCH time in microseconds
Definition at line 25 of file HiResClock.cpp.
Referenced by getTimeInMilliSec(), and getTimeInSec().
HiResClockType fwCore::HiResClock::getTimeInMilliSec ()
Returns:
EPOCH time in milliseconds
Definition at line 46 of file HiResClock.cpp.
References getTimeInMicroSec().
Referenced by fwCore::TimeStamp::periodExpired().
HiResClockType fwCore::HiResClock::getTimeInSec ()
Returns:
EPOCH time in seconds
Definition at line 52 of file HiResClock.cpp.
References getTimeInMicroSec().