fw4spl: fwServices Namespace Reference
fwServices Namespace Reference
Namespace fwServices is dedicated to (mimic) the dynamic affectation of methods to (pure data) objects (fwTools::Object), and component orientation transparently. This is assimilable to the notion of role (corresponding to the IService class).
Namespaces
factory
Contains fwServices::factory utilities.
op
The namespace fwServices::op contains several methods for managing services to object.
OSR
OSR wraps main Object-Service registry access.
registry
The namespace fwServices::registry contains class to manage services, object and config.
Classes
class AppConfigManager
This class provides an API to manage config template.
class IController
This interface defines control service API. Does nothing particularly, can be considered as a default service type to be implemented by unclassified services.
class IService
Base class for all services.
class IXMLParser
Service type for the construction of an object and associated services from an XML-based description.
class SConfigController
To manage configuration file defines in xml extension.
class ServiceFactoryRegistrar
Helper for registering a service Creates internally the service factory and adds it to the FactoryRegistry.
Typedefs
typedef std::pair< std::string, std::string > ObjectServiceKeyType
Functions
template<class DATATYPE >
SPTR (DATATYPE) IService
void displayPt (::boost::property_tree::ptree &pt, std::string indent="")
std::ostream & operator<< (std::ostream &_ostream, IService &_service)
Streaming a service.
class BOOST_PP_CAT (ServiceTypeConceptCheck, __LINE__)
class BOOST_PP_CAT (ServiceImplConceptCheck, __LINE__)
class BOOST_PP_CAT (ServiceObjectConceptCheck, __LINE__)
Methods for creating and attaching services to object
FWSERVICES_API::fwServices::IService::sptr add (::fwData::Object::sptr obj, std::string serviceType, std::string _implementationId, std::string _id="")
Create and attach to the object obj a service of type serviceType, implementation _implementationId with the universal unique identifier _id.
template<class SERVICE >
std::shared_ptr< SERVICE > add (::fwData::Object::sptr obj, std::string _implementationId, std::string _id="")
Create and attach to the object obj a service of type serviceType, implementation _implementationId with the universal unique identifier _id.
Methods for accessing services
FWSERVICES_API::fwServices::IService::sptr get (::fwData::Object::sptr obj, std::string serviceType) throw (fwTools::Failed)
Get the first service of type serviceType which is attached to obj.
template<class SERVICE >
std::shared_ptr< SERVICE > get (::fwData::Object::sptr obj) throw (fwTools::Failed)
Get the first service of type serviceType which is attached to obj.
FWSERVICES_API::fwServices::IService::sptr get (std::string uid) throw (fwTools::Failed)
Return a registered IService having uid as unique universal identifier , its an alias on fwData::Object::getID(...) method.
Detailed Description
Namespace fwServices is dedicated to (mimic) the dynamic affectation of methods to (pure data) objects (fwTools::Object), and component orientation transparently. This is assimilable to the notion of role (corresponding to the IService class).
IService : API to normalize manipulation, using a limited set of well defined methods
IService : contract for service implementation
macros.hpp : declaration of service to object bindings
Function Documentation
fwServices::IService::sptr fwServices::add (::fwData::Object::sptr obj, std::string serviceType, std::string _implementationId, std::string _id = "")
Create and attach to the object obj a service of type serviceType, implementation _implementationId with the universal unique identifier _id.
Returns
the service
Note
the template method is also available, where the template parameter SERVICE corresponds to the serviceType
Definition at line 22 of file Add.cpp.
References fwServices::registry::ServiceFactory::getDefault(), and OSLM_ASSERT.
template<class SERVICE > std::shared_ptr< SERVICE > fwServices::add (::fwData::Object::sptr obj, std::string _implementationId, std::string _id = "")
Create and attach to the object obj a service of type serviceType, implementation _implementationId with the universal unique identifier _id.
Returns
the service
Note
the template method is also available, where the template parameter SERVICE corresponds to the serviceType
Definition at line 21 of file Add.hxx.
References OSLM_ASSERT, SLM_ASSERT, and SPTR.
fwServices::IService::sptr fwServices::get (::fwData::Object::sptr obj, std::string serviceType) throw (fwTools::Failed)
Get the first service of type serviceType which is attached to obj.
Note
The template method is also available, where the template parameter SERVICE relates the service type serviceType
Todo:
Do not automatically add service, raise an error instead
Returns
the requested service, null if not
Definition at line 17 of file Get.cpp.
References OSLM_ASSERT.
Referenced by fwGui::registrar::MenuBarRegistrar::manage(), fwGui::registrar::MenuRegistrar::manage(), fwGui::registrar::ToolBarRegistrar::manage(), fwServices::AppConfigManager::startConnections(), fwComEd::ut::ConfigParserTest::testBuildComposite(), fwServices::ut::ServiceTest::testCommunication(), fwComEd::ut::ConfigParserTest::testObjectCreationWithConfig(), and fwServices::ut::ServiceTest::testStartStopUpdate().
template<class SERVICE > std::shared_ptr< SERVICE > fwServices::get (::fwData::Object::sptr obj) throw (fwTools::Failed)
Get the first service of type serviceType which is attached to obj.
Note
The template method is also available, where the template parameter SERVICE relates the service type serviceType
Todo:
Do not automatically add service, raise an error instead
Returns
the requested service, null if not
Definition at line 22 of file Get.hxx.
References OSLM_ASSERT, and SPTR.
std::ostream& fwServices::operator<< (std::ostream & _ostream, IService & _service)
Streaming a service.
See also
IService::operator<<(std::ostream & _ostream, IService& _service)
Note
Invoke IService::info(std::ostream)
Definition at line 351 of file IService.cpp.
References fwServices::IService::info().