fw4spl: fwVtkIO Namespace Reference
fwVtkIO Namespace Reference
Namespace fwVtkIO.
Classes
struct FilteringStream
class ImageReader
Read an image.Read a VTK Image using the VTK lib.
class ImageStream
class ImageWriter
Write an image.Write a VTK Image using the VTK lib.
class MeshReader
Read a mesh.Read a VTK Mesh using the VTK lib.
class MeshWriter
Write a mesh.Write a VTK Mesh using the VTK lib.
class MetaImageReader
Read a MetaImage.Read a MetaImage using the VTK lib.
class MetaImageWriter
Write a MetaImage.Write a MetaImage using the VTK lib.
class ModelSeriesObjWriter
Write a fwData::Reconstruction.Write a fwData::Reconstruction as .obj file using the VTK lib and the obj format.
class SeriesDBReader
Read a SeriesDB.Read VTK Mesh or Image files using the VTK lib, convert to ModelSeries or ImageSeries and push to SeriesDB.
struct TypeTranslator
class VtiImageReader
Read an image.Read a VTK Image using the VTK lib.
class VtiImageWriter
Write an image.Write a VTK Image using the VTK lib.
Functions
FWVTKIO_API int getVtkScalarType (::fwData::Image::sptr image)
Convert fwData::Image PixelType to the VTK data type of pixels.
FWVTKIO_API void toVTKImage (::fwData::Image::sptr _data, vtkImageData *dst)
Allocate a new vtkImageData* from a ::fwData::Image::sptr.
FWVTKIO_API void fromVTKImage (vtkImageData *_source,::fwData::Image::sptr _destination)
Convert a vtkImageData* to a ::fwData::Image::sptr.
FWVTKIO_API void configureVTKImageImport (::vtkImageImport *_pImageImport,::fwData::Image::sptr _pDataImage)
Configure a vtkImageImport* from a ::fwData::Image::sptr.
FWVTKIO_API vtkMatrix4x4 * toVTKMatrix (::fwData::TransformationMatrix3D::sptr _transfoMatrix)
Convert a ::fwData::TransformationMatrix3D::sptr to a vtkMatrix4x4*.
FWVTKIO_API bool fromVTKMatrix (vtkMatrix4x4 *_matrix,::fwData::TransformationMatrix3D::sptr _transfoMatrix)
Convert a vtkMatrix4x4* to a ::fwData::TransformationMatrix3D::sptr.
vtkSmartPointer< vtkActor > createActor (const ::fwData::Reconstruction::sptr &pReconstruction)
void initSeries (::fwMedData::Series::sptr series, const std::string &instanceUID)
template<typename T , typename FILE >
vtkSmartPointer< vtkDataObject > getObj (FILE &file, const ::fwJobs::Observer::sptr &job)
::fwData::Object::sptr getDataObject (const vtkSmartPointer< vtkDataObject > &obj, const boost::filesystem::path &file)
bool checkIfReadDataTypeIsImage (const vtkSmartPointer< vtkMetaImageReader > &reader)
bool checkIfReadDataTypeIsImage (const vtkSmartPointer< vtkGenericDataObjectReader > &reader)
bool checkIfReadDataTypeIsImage (const vtkSmartPointer< vtkXMLGenericDataObjectReader > &reader)
void updateImageFromVtkInfo (const vtkSmartPointer< vtkInformation > &info, const ::fwData::Image::sptr &imgObj)
void getInfo (const vtkSmartPointer< vtkGenericDataObjectReader > &reader, const ::fwData::Image::sptr &imgObj)
void getInfo (const vtkSmartPointer< vtkXMLGenericDataObjectReader > &reader, const ::fwData::Image::sptr &imgObj)
template<typename DATA_READER >
::fwData::Image::sptr lazyRead (const ::boost::filesystem::path &file)
template<typename IMAGETYPE >
void * newBuffer (size_t size)
template<typename IMAGETYPE >
void fromRGBBuffer (void *input, size_t size, void *&destBuffer)
template<typename IMAGETYPE >
void fromRGBBufferColor (void *input, size_t size, void *&destBuffer)
Detailed Description
Namespace fwVtkIO.
Date
2009.
The namespace fwVtkIO contains reader, writer and helper using the VTK lib for output and input actions between data and the frameWork
Function Documentation
void fwVtkIO::configureVTKImageImport (::vtkImageImport * _pImageImport, ::fwData::Image::sptr _pDataImage)
Configure a vtkImageImport* from a ::fwData::Image::sptr.
Parameters
[in] _pDataImage ::fwData::Image::sptr.
[out] _pImageImport vtkImageImport*.
Definition at line 306 of file vtk.cpp.
References fwComEd::helper::Image::getBuffer().
Referenced by toVTKImage().
void fwVtkIO::fromVTKImage (vtkImageData * _source, ::fwData::Image::sptr _destination)
Convert a vtkImageData* to a ::fwData::Image::sptr.
Parameters
[in] _source vtkImageData*.
[out] _destination ::fwData::Image::sptr.
Throw an exception if the conversion fails
Definition at line 212 of file vtk.cpp.
References fwComEd::helper::Image::getBuffer(), OSLM_TRACE, SLM_ASSERT, SLM_TRACE, and SLM_WARN_IF.
bool fwVtkIO::fromVTKMatrix (vtkMatrix4x4 * _matrix, ::fwData::TransformationMatrix3D::sptr _transfoMatrix)
Convert a vtkMatrix4x4* to a ::fwData::TransformationMatrix3D::sptr.
Parameters
[in] _matrix vtkMatrix4x4*.
[out] _transfoMatrix ::fwData::TransformationMatrix3D::sptr.
Returns
bool.
Returns true if the conversion is a success and false if it fails
Definition at line 352 of file vtk.cpp.
References SLM_TRACE_FUNC.
FWVTKIO_API int fwVtkIO::getVtkScalarType (::fwData::Image::sptr image)
Convert fwData::Image PixelType to the VTK data type of pixels.
Parameters
[in] image ::fwData::Image::sptr.
Returns
int : VTK data scalar type
void fwVtkIO::toVTKImage (::fwData::Image::sptr _data, vtkImageData * dst)
Allocate a new vtkImageData* from a ::fwData::Image::sptr.
Parameters
[in] _data ::fwData::Image::sptr.
[out] dst the vtk image to fill if provided
if dst is provided the new image will be imported into the dst image else allocate a new vtkImage from a fwData::Image, vtkImage doesn't manage its buffer (the buffer is not copied)
Definition at line 131 of file vtk.cpp.
References configureVTKImageImport(), and OSLM_ERROR.
vtkMatrix4x4 * fwVtkIO::toVTKMatrix (::fwData::TransformationMatrix3D::sptr _transfoMatrix)
Convert a ::fwData::TransformationMatrix3D::sptr to a vtkMatrix4x4*.
Parameters
[in] _transfoMatrix ::fwData::TransformationMatrix3D::sptr.
Returns
vtkPolyData*.
Definition at line 337 of file vtk.cpp.