fw4spl: fwRuntime::IExecutable Struct Reference
fwRuntime::IExecutable Struct Reference abstract
Defines the base executable interface.An executable object is an instance created by an extension point of a plugin.
#include <IExecutable.hpp>
Public Member Functions
virtual FWRUNTIME_API ~IExecutable ()
Destructor : does nothing.
virtual std::shared_ptr< Bundle > getBundle () const =0 throw ()
Retrieves the bundle the executable originates from.
virtual void setInitializationData (const std::shared_ptr< ConfigurationElement > configuration)=0 throw ()
Initializes the executable instance with the specified configuration element.
Protected Member Functions
virtual void setBundle (std::shared_ptr< Bundle > bundle)=0
Updates the bundle the executable originates from.
Friends
struct Runtime
Detailed Description
Defines the base executable interface.
An executable object is an instance created by an extension point of a plugin.
Date
2004-2009
Definition at line 41 of file IExecutable.hpp.
Member Function Documentation
virtual std::shared_ptr<Bundle> fwRuntime::IExecutable::getBundle () const throw () pure virtual
Retrieves the bundle the executable originates from.
Returns
a pointer to the originating bundle.
Implemented in fwRuntime::Executable, and fwRuntime::Plugin.
Referenced by fwRuntime::findExtensionPoint().
virtual void fwRuntime::IExecutable::setBundle (std::shared_ptr< Bundle > bundle) protected pure virtual
Updates the bundle the executable originates from.
Parameters
[in] bundle a pointer to the bundle the executable originates from
Implemented in fwRuntime::Executable, and fwRuntime::Plugin.
Referenced by fwRuntime::Runtime::createExecutableInstance().
virtual void fwRuntime::IExecutable::setInitializationData (const std::shared_ptr< ConfigurationElement > configuration) throw () pure virtual
Initializes the executable instance with the specified configuration element.
Parameters
[in] configuration a shared pointer to the configuration element used to trigger this execution
Implemented in fwRuntime::Executable, and fwRuntime::Plugin.
Referenced by fwRuntime::Runtime::createExecutableInstance().
The documentation for this struct was generated from the following files:
IExecutable.hpp
IExecutable.cpp