fw4spl: fwRuntime::dl::Native Struct Reference
fwRuntime::dl::Native Struct Reference abstract
Defines the abstract class for native module implementors.
#include <Native.hpp>
Public Member Functions
Native (const boost::filesystem::path &modulePath) throw ()
Constructor.
virtual ~Native () throw ()
Destructor : does nothing.
virtual bool isLoaded () const =0 throw ()
Tells if the module is loaded.
virtual void * getSymbol (const std::string &name) const =0 throw (RuntimeException)
Retrieves the address of a symbol specified by its name.
virtual void load ()=0 throw (RuntimeException)
Loads the module.
virtual void unload ()=0 throw (RuntimeException)
Undloads the module.
const boost::filesystem::path getFullPath (const bool _bMustBeFile=false) const throw (RuntimeException)
Retrieves the file path of the library including the owning bundle's path.
const boost::filesystem::path getPath () const throw (RuntimeException)
Retrieves the file path of the native library.
void setBundle (const ::fwRuntime::Bundle *bundle) throw ()
Set the bundle the library is attached to.
const ::boost::regex getNativeName () const
Retrieves the pattern of the dynamic library file name given the host OS.
Friends
struct ::fwRuntime::Bundle
Detailed Description
Defines the abstract class for native module implementors.
Definition at line 31 of file Native.hpp.
Constructor & Destructor Documentation
fwRuntime::dl::Native::Native (const boost::filesystem::path & modulePath) throw ()
Constructor.
Parameters
[in] modulePath a path to the module to manage
Definition at line 24 of file Native.cpp.
Member Function Documentation
const ::boost::filesystem::path fwRuntime::dl::Native::getFullPath (const bool _bMustBeFile = false) const throw (RuntimeException)
Retrieves the file path of the library including the owning bundle's path.
Parameters
[in] _bMustBeFile if true : bundle is a dynamic library and we want return an exception if is not a file
Returns
a file path
See also
getPath
Definition at line 49 of file Native.cpp.
References getPath(), and SLM_ASSERT.
const ::boost::regex fwRuntime::dl::Native::getNativeName () const
Retrieves the pattern of the dynamic library file name given the host OS.
Returns
the boost::regex
Definition at line 76 of file Native.cpp.
References fwRuntime::Bundle::getVersion(), and fwRuntime::Version::string().
Referenced by getPath().
const ::boost::filesystem::path fwRuntime::dl::Native::getPath () const throw (RuntimeException)
Retrieves the file path of the native library.
Note
This path is relative to the owning bundle's path.
Returns
a string containing the native module file path
Definition at line 98 of file Native.cpp.
References getNativeName(), and SLM_ASSERT.
Referenced by getFullPath().
virtual void* fwRuntime::dl::Native::getSymbol (const std::string & name) const throw (RuntimeException) pure virtual
Retrieves the address of a symbol specified by its name.
Parameters
[in] name a string containing the symbol name.
Returns
a pointer to the found symbol or null if none has been found
virtual bool fwRuntime::dl::Native::isLoaded () const throw () pure virtual
Tells if the module is loaded.
Returns
true or false
void fwRuntime::dl::Native::setBundle (const ::fwRuntime::Bundle * bundle) throw ()
Set the bundle the library is attached to.
Parameters
[in] bundle a pointer to a bundle instance
Definition at line 126 of file Native.cpp.
References SLM_ASSERT.
The documentation for this struct was generated from the following files:
Native.hpp
Native.cpp