fw4spl: fwRuntime::Plugin Struct Reference
fwRuntime::Plugin Struct Reference
Provides a default plugin implementation.
#include <Plugin.hpp>
Inherits fwRuntime::IPlugin.
Inherited by activities::Plugin, appXml::Plugin, basicRegistration::Plugin, console::Plugin, ctrlCamp::Plugin, ctrlHistory::Plugin, ctrlMemory::Plugin, ctrlSelection::Plugin, dataReg::Plugin, filterVRRender::Plugin, fwRuntime::EmptyPlugin, gui::Plugin, guiQt::Plugin, ioAtoms::Plugin, ioData::Plugin, ioDcmtk::Plugin, ioDicom::Plugin, ioDicomWeb::Plugin, ioGdcm::Plugin, ioITK::Plugin, ioPacs::Plugin, ioQt::Plugin, ioTuto::Plugin, ioVTK::Plugin, ioVtkGdcm::Plugin, memory::Plugin, monitor::Plugin, monitorQt::Plugin, opImageFilter::Plugin, opVTKMesh::Plugin, patchMedicalData::Plugin, preferences::Plugin, scene2D::Plugin, servicesReg::Plugin, Tuto02DataServiceBasicCtrl::Plugin, Tuto14MeshGenerator::Plugin, Tuto16MultithreadConsole::Plugin, TutoTrianConverterCtrl::Plugin, uiGenericQt::Plugin, uiImageQt::Plugin, uiIO::Plugin, uiMeasurement::Plugin, uiMeasurementQt::Plugin, uiMedDataQt::Plugin, uiPreferences::Plugin, uiReconstructionQt::Plugin, uiTF::Plugin, uiVisu::Plugin, uiVisuQt::Plugin, visuVTK::Plugin, visuVTKAdaptor::Plugin, visuVTKQt::Plugin, visuVTKVRAdaptor::Plugin, vtkCompositeMesh::Plugin, vtkSimpleMesh::Plugin, and vtkSimpleNegato::Plugin.
Public Member Functions
FWRUNTIME_API std::shared_ptr< Bundle > getBundle () const noexcept override
Retrieves the bundle the executable originates from.
virtual FWRUNTIME_API void setInitializationData (const std::shared_ptr< ConfigurationElement >configuration) noexcept override
Initializes the executable instance with the specified configuration element.
Public Member Functions inherited from fwRuntime::IPlugin
virtual FWRUNTIME_API ~IPlugin ()
Destructor : does nothing.
virtual void start ()=0
Notifies the plugin about its start.
virtual FWRUNTIME_API void initialize ()
Notifies the plugin about its initialisation.
virtual FWRUNTIME_API void uninitialize ()
Notifies the plugin about its uninitialisation.
virtual void stop () noexcept=0
Notifies the plugin about its stop.
Public Member Functions inherited from fwRuntime::IExecutable
virtual FWRUNTIME_API ~IExecutable ()
Destructor : does nothing.
Protected Member Functions
FWRUNTIME_API void setBundle (std::shared_ptr< Bundle > bundle) noexcept override
Updates the bundle the executable originates from.
Detailed Description
Provides a default plugin implementation.
This class is intended to be sub-classed. The IPlugin::start and IPlugin::stop function must be implemented.
Definition at line 21 of file SrcLib/core/fwRuntime/include/fwRuntime/Plugin.hpp.
Member Function Documentation
std::shared_ptr< Bundle > fwRuntime::Plugin::getBundle () const override virtual noexcept
Retrieves the bundle the executable originates from.
Returns
a pointer to the originating bundle.
Implements fwRuntime::IExecutable.
Definition at line 16 of file SrcLib/core/fwRuntime/src/Plugin.cpp.
Referenced by memory::Plugin::start(), appXml::Plugin::start(), and guiQt::Plugin::stop().
void fwRuntime::Plugin::setBundle (std::shared_ptr< Bundle > bundle) override protected virtual noexcept
Updates the bundle the executable originates from.
Parameters
[in] bundle a pointer to the bundle the executable originates from
Implements fwRuntime::IExecutable.
Definition at line 29 of file SrcLib/core/fwRuntime/src/Plugin.cpp.
void fwRuntime::Plugin::setInitializationData (const std::shared_ptr< ConfigurationElement > configuration) override virtual noexcept
Initializes the executable instance with the specified configuration element.
Parameters
[in] configuration a shared pointer to the configuration element used to trigger this execution
Implements fwRuntime::IExecutable.
Definition at line 23 of file SrcLib/core/fwRuntime/src/Plugin.cpp.
The documentation for this struct was generated from the following files:
SrcLib/core/fwRuntime/include/fwRuntime/Plugin.hpp
SrcLib/core/fwRuntime/src/Plugin.cpp