fw4spl: fwRuntime::ConfigurationElementContainer Struct Reference
fwRuntime::ConfigurationElementContainer Struct Reference
Defines the generic configuration element container class.
#include <ConfigurationElementContainer.hpp>
Public Types
Type Definitions
typedef std::vector
< ::boost::shared_ptr
< ConfigurationElement > > Container
Defines the configuration element container type.
typedef Container::iterator Iterator
Defines the configuration element container iterator type.
Public Member Functions
FWRUNTIME_API Iterator begin ()
Retrieves the iterator on the first managed configuration element.
FWRUNTIME_API Iterator end ()
Retrieves the iterator on the end of the configuration element container.
FWRUNTIME_API const Container & getElements () const
Returns the configuration element container.
FWRUNTIME_API const
::boost::shared_ptr
< ConfigurationElement > findConfigurationElement (const std::string &name) const
Retrieves the first configuration corresponding to the specified name.
FWRUNTIME_API bool hasConfigurationElement (const std::string &name) const
Test if has an configuration corresponding to the specified name.
FWRUNTIME_API
ConfigurationElementContainer findAllConfigurationElement (const std::string &name) const
Retrieves the configurations corresponding to the specified name.
FWRUNTIME_API size_t size () const
Return the number of configurations.
Protected Member Functions
FWRUNTIME_API void addConfigurationElement (::boost::shared_ptr< ConfigurationElement > element)
Adds a new configuration element to the extension.
Friends
struct BundleDescriptorReader
Detailed Description
Defines the generic configuration element container class.
Date:
2004-2009
Definition at line 36 of file ConfigurationElementContainer.hpp.
Member Function Documentation
void fwRuntime::ConfigurationElementContainer::addConfigurationElement (::boost::shared_ptr< ConfigurationElement > element) [protected]
Adds a new configuration element to the extension.
Parameters:
[in] element a shared pointer to the configuration element to add
Definition at line 45 of file ConfigurationElementContainer.cpp.
Referenced by findAllConfigurationElement().
ConfigurationElementContainer::Iterator fwRuntime::ConfigurationElementContainer::begin ()
Retrieves the iterator on the first managed configuration element.
Returns:
an iterator
Definition at line 52 of file ConfigurationElementContainer.cpp.
Referenced by ctrlSelection::IUpdaterSrv::configureManagedEvents(), ctrlSelection::manager::MedicalImageManagerSrv::configuring(), ctrlMemory::manager::LockDumpManagerSrv::configuring(), fwRuntime::ConfigurationElement::find(), and fwRuntime::getAllExecutableForPoint().
ConfigurationElementContainer::Iterator fwRuntime::ConfigurationElementContainer::end ()
Retrieves the iterator on the end of the configuration element container.
Returns:
an iterator
Definition at line 59 of file ConfigurationElementContainer.cpp.
Referenced by ctrlSelection::IUpdaterSrv::configureManagedEvents(), ctrlSelection::manager::MedicalImageManagerSrv::configuring(), ctrlMemory::manager::LockDumpManagerSrv::configuring(), fwRuntime::ConfigurationElement::find(), and fwRuntime::getAllExecutableForPoint().
ConfigurationElementContainer fwRuntime::ConfigurationElementContainer::findAllConfigurationElement (const std::string & name) const
Retrieves the configurations corresponding to the specified name.
Parameters:
[in] name a string containing a configuration element name
Returns:
a configuration element container that contains configuration element instances
Definition at line 90 of file ConfigurationElementContainer.cpp.
References addConfigurationElement().
Referenced by ctrlSelection::IUpdaterSrv::configureManagedEvents(), and gui::action::SSlotCaller::configuring().
const ::boost::shared_ptr< ConfigurationElement > fwRuntime::ConfigurationElementContainer::findConfigurationElement (const std::string & name) const
Retrieves the first configuration corresponding to the specified name.
Parameters:
[in] name a string containing a configuration element name
Returns:
a pointer to a configuration element instance or null if none
Definition at line 81 of file ConfigurationElementContainer.cpp.
const ConfigurationElementContainer::Container & fwRuntime::ConfigurationElementContainer::getElements () const
Returns the configuration element container.
Returns:
an configuration element container
Definition at line 66 of file ConfigurationElementContainer.cpp.
Referenced by ctrlSelection::wrapper::MsgWrapperSrv::configuring(), ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv::configuring(), ctrlSelection::wrapper::MsgForwarderSrv::configuring(), and gui::action::SSlotCaller::configuring().
bool fwRuntime::ConfigurationElementContainer::hasConfigurationElement (const std::string & name) const
Test if has an configuration corresponding to the specified name.
Parameters:
[in] name a string containing a configuration element name
Returns:
true if the method find at least one configuration
Definition at line 73 of file ConfigurationElementContainer.cpp.
size_t fwRuntime::ConfigurationElementContainer::size () const
Return the number of configurations.
Returns:
Return the number of configurations
Definition at line 109 of file ConfigurationElementContainer.cpp.
Referenced by ctrlSelection::IUpdaterSrv::configureManagedEvents(), ctrlSelection::manager::MedicalImageManagerSrv::configuring(), ctrlSelection::wrapper::MsgWrapperSrv::configuring(), ctrlSelection::wrapper::ObjToCompositeMsgForwarderSrv::configuring(), and ctrlSelection::wrapper::MsgForwarderSrv::configuring().
The documentation for this struct was generated from the following files:
ConfigurationElementContainer.hpp
ConfigurationElementContainer.cpp