fw4spl: fwRuntime::ExtensionPoint Struct Reference
fwRuntime::ExtensionPoint Struct Reference
Defines the extension point class.
#include <ExtensionPoint.hpp>
Public Types
typedef Extension::Container ConfigurationElementContainer
Public Member Functions
const ConfigurationElementContainer getAllConfigurationElements () const
Retrieves all configuration elements contributed by extensions connected to the extension point instance.
template<typename OutputIterator >
void getAllConfigurationElements (OutputIterator &output) const
Retrieves all configuration elements contributed by extensions connected to the extension point instance.
template<typename OutputIterator >
void getAllExtensions (OutputIterator &output) const
Retrieves all extensions contributed to the point instance.
FWRUNTIME_API const std::string & getIdentifier () const
Retrieves the extension point identifier.
FWRUNTIME_API std::shared_ptr< io::Validator > getExtensionValidator () const
Retrieves the extension validator.
Public Member Functions inherited from fwRuntime::BundleElement
FWRUNTIME_API std::shared_ptr< Bundle > getBundle () const
Retrieves the bundle that owns the extension.
FWRUNTIME_API bool isEnable () const
Tells if the element is enabled or not.
FWRUNTIME_API void setEnable (const bool enable)
Set if the element is enabled or not.
Protected Member Functions
ExtensionPoint (const std::shared_ptr< Bundle > bundle, const std::string &id, const boost::filesystem::path &schema)
constructor
Protected Member Functions inherited from fwRuntime::BundleElement
BundleElement ()
Constructor.
BundleElement (std::shared_ptr< Bundle > bundle)
Constructor.
Friends
struct ::fwRuntime::io::BundleDescriptorReader
Detailed Description
Defines the extension point class.
Definition at line 39 of file ExtensionPoint.hpp.
Constructor & Destructor Documentation
fwRuntime::ExtensionPoint::ExtensionPoint (const std::shared_ptr< Bundle > bundle, const std::string & id, const boost::filesystem::path & schema) protected
constructor
Parameters
[in] bundle a shared pointer to the bundle where the extension point is declared
[in] id a string containing the extension point identifier
[in] schema a path to a file containing an XML schema used to validate extensions contributed to the point.
Definition at line 18 of file ExtensionPoint.cpp.
Member Function Documentation
const ConfigurationElementContainer fwRuntime::ExtensionPoint::getAllConfigurationElements () const inline
Retrieves all configuration elements contributed by extensions connected to the extension point instance.
Returns
a container with all found configuration elements
Definition at line 51 of file ExtensionPoint.hpp.
template<typename OutputIterator > void fwRuntime::ExtensionPoint::getAllConfigurationElements (OutputIterator & output) const inline
Retrieves all configuration elements contributed by extensions connected to the extension point instance.
Parameters
[out] output an output iterator that will be used to store shared pointer to the found configuration elements
Definition at line 71 of file ExtensionPoint.hpp.
References OSLM_DEBUG_IF.
template<typename OutputIterator > void fwRuntime::ExtensionPoint::getAllExtensions (OutputIterator & output) const inline
Retrieves all extensions contributed to the point instance.
Parameters
[out] output an output iterator that will be used to store shared pointers to found extensions
Definition at line 102 of file ExtensionPoint.hpp.
References fwRuntime::Runtime::extensionsBegin(), fwRuntime::Runtime::extensionsEnd(), fwRuntime::Runtime::getDefault(), and fwRuntime::Extension::Valid.
std::shared_ptr< io::Validator > fwRuntime::ExtensionPoint::getExtensionValidator () const
Retrieves the extension validator.
Returns
a shared pointer to the extension validator, or null when none
Definition at line 35 of file ExtensionPoint.cpp.
References fwRuntime::BundleElement::getBundle(), and OSLM_DEBUG.
const std::string & fwRuntime::ExtensionPoint::getIdentifier () const
Retrieves the extension point identifier.
Returns
a string containing the extension point identifier
Definition at line 28 of file ExtensionPoint.cpp.
The documentation for this struct was generated from the following files:
ExtensionPoint.hpp
ExtensionPoint.cpp