fw4spl: fwRuntime::io::BundleDescriptorReader Struct Reference
fwRuntime::io::BundleDescriptorReader Struct Reference
Defines the bundle descriptor reader class.
#include <BundleDescriptorReader.hpp>
Public Types
typedef std::vector< std::shared_ptr< Bundle > > BundleContainer
typedef std::pair< SPTR(ExtensionPoint), std::vector< SPTR(Extension) > > PointExtensionsPairType
Pair of created extension point associated with extensions.
Static Public Member Functions
static FWRUNTIME_API std::shared_ptr< Bundle > createBundle (const boost::filesystem::path &location) throw (RuntimeException)
Look for a descriptor at the specified location, reads it and creates a bundle with it.
static FWRUNTIME_API std::shared_ptr< Bundle > createBundleFromXmlPlugin (const ::boost::filesystem::path &location) throw (RuntimeException)
Look for a descriptor at the specified location, reads it and creates a bundle with it.
static FWRUNTIME_API const BundleContainer createBundles (const boost::filesystem::path &location) throw (RuntimeException)
Creates all bundles that are found at the given location.
static FWRUNTIME_API std::shared_ptr< ConfigurationElement > processConfigurationElement (xmlNodePtr node, const std::shared_ptr< Bundle > bundle) throw (RuntimeException)
Processes a configuration element XML node.
Detailed Description
Defines the bundle descriptor reader class.
Definition at line 40 of file BundleDescriptorReader.hpp.
Member Function Documentation
std::shared_ptr< Bundle > fwRuntime::io::BundleDescriptorReader::createBundle (const boost::filesystem::path & location) throw (RuntimeException) static
Look for a descriptor at the specified location, reads it and creates a bundle with it.
Parameters
[in] location a path to a directory that should contain a bundle description
Returns
a shared pointer to the created bundle
Definition at line 87 of file BundleDescriptorReader.cpp.
References fwRuntime::Runtime::getDefault(), and fwRuntime::Runtime::getWorkingPath().
Referenced by createBundles().
std::shared_ptr< Bundle > fwRuntime::io::BundleDescriptorReader::createBundleFromXmlPlugin (const ::boost::filesystem::path & location) throw (RuntimeException) static
Look for a descriptor at the specified location, reads it and creates a bundle with it.
Parameters
[in] location a path to a plugin.xml that should contain a bundle description
Returns
a shared pointer to the created bundle
Definition at line 156 of file BundleDescriptorReader.cpp.
References fwRuntime::Runtime::getDefault(), and fwRuntime::Runtime::getWorkingPath().
const BundleDescriptorReader::BundleContainer fwRuntime::io::BundleDescriptorReader::createBundles (const boost::filesystem::path & location) throw (RuntimeException) static
Creates all bundles that are found at the given location.
Parameters
[in] location a path to a directory containing bundles
Returns
a container with all created bundles
Definition at line 44 of file BundleDescriptorReader.cpp.
References createBundle(), OSLM_INFO, and SPTR.
ConfigurationElement::sptr fwRuntime::io::BundleDescriptorReader::processConfigurationElement (xmlNodePtr node, const std::shared_ptr< Bundle > bundle) throw (RuntimeException) static
Processes a configuration element XML node.
Parameters
node a pointer to the XML node that represents a configuration element
bundle a pointer to the bundle the extension will be attached to
Returns
a pointer to the created configuration element
Definition at line 225 of file BundleDescriptorReader.cpp.
References fwRuntime::Runtime::findBundle(), fwRuntime::Runtime::getDefault(), OSLM_WARN_IF, SLM_ASSERT, and SLM_FATAL.
Referenced by fwRuntime::Convert::toXmlString().
The documentation for this struct was generated from the following files:
BundleDescriptorReader.hpp
BundleDescriptorReader.cpp