fw4spl: fwRuntime::ConfigurationElement Struct Reference
fwRuntime::ConfigurationElement Struct Reference
Defines the configuration element class.
#include <ConfigurationElement.hpp>
Classes
struct NoSuchAttribute
Defines the a class for attributes exceptions.
Public Types
typedef std::pair< bool, std::string > AttributePair
Defines the attribute pair type.
Public Types inherited from fwRuntime::ConfigurationElementContainer
typedef std::vector< std::shared_ptr< ConfigurationElement > > Container
Defines the configuration element container type.
typedef Container::iterator Iterator
Defines the configuration element container iterator type.
Public Member Functions
__FWCORE_CLASS_TYPEDEFS ((ConfigurationElement))
__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new ConfigurationElement,(((const std::shared_ptr< Bundle >))((const std::string))))
__FWCORE_GENERATE_CAST (__FWCORE_GET_CLASSNAME((ConfigurationElement)), __FWCORE_TYPEDEF_ROOTCLASS_NAME)
virtual bool isA (const std::string &type) const
FWRUNTIME_API const std::shared_ptr< Bundle > getBundle () const throw ()
Retrieves the bundle the configuration element is attached to.
FWRUNTIME_API const std::string getAttributeValue (const std::string &name) const throw ()
Retrieves the value of an attribute for the specified name.
FWRUNTIME_API const std::string getExistingAttributeValue (const std::string &name) const throw (NoSuchAttribute)
Retrieves the value of an attribute for the specified name.
FWRUNTIME_API const AttributePair getSafeAttributeValue (const std::string &name) const throw ()
Retrieves the value of an existing attribute for the specified name.
FWRUNTIME_API const std::string getName () const throw ()
Retrieves the name of the configuration element.
FWRUNTIME_API const std::string getValue () const throw ()
Retrieves the configuration element value.
FWRUNTIME_API bool hasAttribute (const std::string &name) const throw ()
Tells if the specified attributes exists.
FWRUNTIME_API const std::map< std::string, std::string > getAttributes () const throw ()
Return the map with attributes.
FWRUNTIME_API std::vector< ConfigurationElement::sptr > find (std::string name="", std::string attribute="", std::string attributeValue="", int depth=1)
Find recursively all the corresponding configuration elements.
virtual FWRUNTIME_API ~ConfigurationElement ()
Used only because this class inherit from enable_shared_from_this.
Public Member Functions inherited from fwRuntime::ConfigurationElementContainer
FWRUNTIME_API Iterator begin ()
Retrieves the iterator on the first managed configuration element.
FWRUNTIME_API Iterator end ()
Retrieves the iterator on the end of the configuration element container.
FWRUNTIME_API const Container & getElements () const
Returns the configuration element container.
FWRUNTIME_API const std::shared_ptr< ConfigurationElement > findConfigurationElement (const std::string &name) const
Retrieves the first configuration corresponding to the specified name.
FWRUNTIME_API bool hasConfigurationElement (const std::string &name) const
Test if has an configuration corresponding to the specified name.
FWRUNTIME_API ConfigurationElementContainer findAllConfigurationElement (const std::string &name) const
Retrieves the configurations corresponding to the specified name.
FWRUNTIME_API size_t size () const
Return the number of configurations.
Static Public Member Functions
static bool isTypeOf (const std::string &type)
Protected Member Functions
FWRUNTIME_API ConfigurationElement (const std::shared_ptr< Bundle > bundle, const std::string &name)
Constructor.
FWRUNTIME_API void setAttributeValue (const std::string &name, const std::string &value) throw ()
Sets an attribute with the specified name and value.
FWRUNTIME_API void setValue (const std::string &value) throw ()
Sets the value of the configuration element it-self.
Protected Member Functions inherited from fwRuntime::ConfigurationElementContainer
FWRUNTIME_API void addConfigurationElement (std::shared_ptr< ConfigurationElement > element)
Adds a new configuration element to the extension.
Friends
struct ::fwRuntime::io::BundleDescriptorReader
class ::boost::serialization::access
template<class , class >
struct ::boost::python::objects::pointer_holder
template<class , class , class >
class ::fwTools::ClassFactory
class ::fwTools::Factory
FWRUNTIME_API friend std::ostream & operator<< (std::ostream &_sstream, ConfigurationElement &_configurationElement)
Print contents.
Demangling methods
virtual const std::string & getLeafClassname () const
return object's classname given by fwCore::Demangler::getLeafClassname()
virtual const std::string & getClassname () const
return object's classname given by fwCore::Demangler::getClassname()
virtual const std::string & getFullClassname () const
return object's classname given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedClassname () const
return object's classname given by fwCore::Demangler::getRootedClassname()
virtual const std::string & getFullNamespace () const
return object's namespace given by fwCore::Demangler::getFullClassname()
virtual const std::string & getRootedNamespace () const
return object's namespace given by fwCore::Demangler::getRootedNamespace()
static const std::string & leafClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & classname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedClassname ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & fullNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
static const std::string & rootedNamespace ()
return object's classname given by fwCore::Demangler::getLeafClassname()
Detailed Description
Defines the configuration element class.
Date
2004-2009
Definition at line 46 of file ConfigurationElement.hpp.
Constructor & Destructor Documentation
fwRuntime::ConfigurationElement::ConfigurationElement (const std::shared_ptr< Bundle > bundle, const std::string & name) protected
Constructor.
Parameters
[in] bundle a shared pointer to the bundle to the configuration element is attached to
[in] name a string containing the configuration element name
Todo:
test parameters validity
Definition at line 41 of file ConfigurationElement.cpp.
Member Function Documentation
fwRuntime::ConfigurationElement::__FWCORE_GENERATE_FACTORIES_WITH_ONE_FACTORY (new ConfigurationElement, (((const std::shared_ptr< Bundle >))((const std::string))))
Specialized version of shared_ptr (alias to shared_ptr< __FWCORE_GET_CLASSNAME((ConfigurationElement)) >) \ * with embeded factory for __FWCORE_GET_CLASSNAME((ConfigurationElement)).
std::vector< ConfigurationElement::sptr > fwRuntime::ConfigurationElement::find (std::string name = "", std::string attribute = "", std::string attributeValue = "", int depth = 1)
Find recursively all the corresponding configuration elements.
Parameters
[in] name name of the configuration element (if name is empty, find all name)
[in] attribute attribute which must be contained by the configuration element (if attribute is empty, this doesn't check the attribute)
[in] attributeValue value of the attribute which must be contained by the configuration element (if value is empty, this doesn't check the value)
[in] depth depth of the recursion
Definition at line 142 of file ConfigurationElement.cpp.
References fwRuntime::ConfigurationElementContainer::begin(), fwRuntime::ConfigurationElementContainer::end(), getAttributeValue(), getName(), and hasAttribute().
const std::string fwRuntime::ConfigurationElement::getAttributeValue (const std::string & name) const throw ()
Retrieves the value of an attribute for the specified name.
This method will search for an attribute having the specified name and return it's value. When no matching attribute is found, an empty string is returned.
Parameters
[in] name a string containing an attribute value
Returns
a string containing the attribute value or nothing when none has been found
See also
getExistingAttributeValue
getSafeAttributeValue
Definition at line 57 of file ConfigurationElement.cpp.
Referenced by find().
const std::shared_ptr< Bundle > fwRuntime::ConfigurationElement::getBundle () const throw ()
Retrieves the bundle the configuration element is attached to.
Returns
a shared pointer to a bundle instance
Definition at line 50 of file ConfigurationElement.cpp.
const std::string fwRuntime::ConfigurationElement::getExistingAttributeValue (const std::string & name) const throw (NoSuchAttribute)
Retrieves the value of an attribute for the specified name.
This method will search for an attribute having the specified name and return it's value. When no matching attribute is found, an object of type NoSuchAttribute is thrown.
Parameters
[in] name a string containing an attribute name
Returns
a string containing an attribute value
Exceptions
NoSuchAttribute no attribute with the specified name has been found
See also
getAttributeValue
getSafeAttributeValue
Definition at line 65 of file ConfigurationElement.cpp.
Referenced by fwServices::helper::Config::createProxy().
const std::string fwRuntime::ConfigurationElement::getName () const throw ()
Retrieves the name of the configuration element.
Returns
a string containing the configuration element name
Definition at line 93 of file ConfigurationElement.cpp.
Referenced by find().
const ConfigurationElement::AttributePair fwRuntime::ConfigurationElement::getSafeAttributeValue (const std::string & name) const throw ()
Retrieves the value of an existing attribute for the specified name.
The returned value is a pair where the first element is a boolean telling if the attribute really exists and the second element is the attribute value.
Parameters
[in] name a string containing an attribute name
Returns
a pair where the first element is a boolean telling if the attribute really exists and the second element is the attribute value
See also
getAttributeValue
getExistingAttributeValue
Definition at line 77 of file ConfigurationElement.cpp.
const std::string fwRuntime::ConfigurationElement::getValue () const throw ()
Retrieves the configuration element value.
Returns
a string containing the configuration element value
Definition at line 100 of file ConfigurationElement.cpp.
bool fwRuntime::ConfigurationElement::hasAttribute (const std::string & name) const throw ()
Tells if the specified attributes exists.
Parameters
[in] name a string containing an attribute name
Returns
true or false
Definition at line 107 of file ConfigurationElement.cpp.
Referenced by fwServices::helper::Config::createProxy(), and find().
void fwRuntime::ConfigurationElement::setAttributeValue (const std::string & name, const std::string & value) throw () protected
Sets an attribute with the specified name and value.
Setting a value for an existing attribute will override the old value.
Parameters
[in] name a string containing the attribute name
[in] value a string containing the attribute value
Definition at line 122 of file ConfigurationElement.cpp.
Referenced by fwRuntime::EConfigurationElement::addConfigurationElement().
void fwRuntime::ConfigurationElement::setValue (const std::string & value) throw () protected
Sets the value of the configuration element it-self.
Parameters
[in] value a string containing the new configuration element value
Definition at line 129 of file ConfigurationElement.cpp.
Referenced by fwRuntime::EConfigurationElement::addConfigurationElement().
The documentation for this struct was generated from the following files:
ConfigurationElement.hpp
ConfigurationElement.cpp