fw4spl: fwRuntime::Bundle Struct Reference
fwRuntime::Bundle Struct Reference
Defines the bundle class.
#include <Bundle.hpp>
Public Types
Type definitions
typedef std::set< std::shared_ptr< ExecutableFactory > > ExecutableFactoryContainer
Defines the executable factory container type.
typedef ExecutableFactoryContainer::const_iterator ExecutableFactoryConstIterator
Defines the executable factory container constant iterator type.
typedef std::set< std::shared_ptr< Extension > > ExtensionContainer
Defines the extension container type.
typedef ExtensionContainer::const_iterator ExtensionConstIterator
Defines the extension container constant iterator type.
typedef std::set< std::shared_ptr< ExtensionPoint > > ExtensionPointContainer
Defines the extension point container type.
typedef ExtensionPointContainer::const_iterator ExtensionPointConstIterator
Defines the extension point container constant iterator type.
typedef std::set< std::shared_ptr< dl::Library > > LibraryContainer
Defines the dynamic library container type.
typedef LibraryContainer::const_iterator LibraryConstIterator
Defines the dynamic library container constant iterator type.
Public Member Functions
FWRUNTIME_API void initialize () throw (RuntimeException)
Initialize the bundle.
FWRUNTIME_API void uninitialize () throw (RuntimeException)
bool isStarted ()
bool isInitialized ()
Dynamic Libraries
FWRUNTIME_API void addLibrary (std::shared_ptr< dl::Library > library)
Adds the specified library to the bundle.
FWRUNTIME_API LibraryConstIterator librariesBegin () const
Retrieves the iterator on the first item in the managed dynamic library collection.
FWRUNTIME_API LibraryConstIterator librariesEnd () const
Retrieves the iterator on the ending item in the managed dynamic library collection.
Executable Factories & Dynamic Objects Instantiation
FWRUNTIME_API void addExecutableFactory (std::shared_ptr< ExecutableFactory > factory)
Adds an executable factory instance to the bundle.
FWRUNTIME_API IExecutable * createExecutableInstance (const std::string &type) throw (RuntimeException)
Create an instance of the given executable object type.
FWRUNTIME_API ExecutableFactoryConstIterator executableFactoriesBegin () const
Retrieves the iterator on the first item in the managed executable factory collection.
FWRUNTIME_API ExecutableFactoryConstIterator executableFactoriesEnd () const
Retrieves the iterator on the ending item in the managed executable factory collection.
FWRUNTIME_API std::shared_ptr< ExecutableFactory > findExecutableFactory (const std::string &type) const
Retrieves the executable factory instance for the specified type name.
Extensions
void addExtension (std::shared_ptr< Extension > extension)
Adds the specified extension to the bundle.
FWRUNTIME_API bool hasExtension (const std::string &identifier) const
Tells if an specific extension exists.
FWRUNTIME_API void setEnableExtension (const std::string &identifier, const bool enable)
Search a specific extension in the bundle to enable or disable it.
FWRUNTIME_API ExtensionConstIterator extensionsBegin () const
Retrieves the iterator on the first item in the managed extension collection.
FWRUNTIME_API ExtensionConstIterator extensionsEnd () const
Retrieves the iterator on the ending item in the managed extension collection.
Extension Points
void addExtensionPoint (std::shared_ptr< ExtensionPoint > extension)
Adds the specified extension point to the bundle.
FWRUNTIME_API std::shared_ptr< ExtensionPoint > findExtensionPoint (const std::string &identifier) const
Retrieves the extension point for the given identifier.
FWRUNTIME_API bool hasExtensionPoint (const std::string &identifier) const
Tells if a specific extension point exists.
FWRUNTIME_API void setEnableExtensionPoint (const std::string &identifier, const bool enable)
Search a specific extension point in the bundle to enable or disable it.
FWRUNTIME_API ExtensionPointConstIterator extensionPointsBegin () const
Retrieves the iterator on the first item in the managed extension point collection.
FWRUNTIME_API ExtensionPointConstIterator extensionPointsEnd () const
Retrieves the iterator on the ending item in the managed extension point collection.
Misc
FWRUNTIME_API void addRequirement (const std::string &requirement)
Adds a requirement to the bundle.
FWRUNTIME_API const std::string & getIdentifier () const
Retrieves the bundle identifier.
FWRUNTIME_API const boost::filesystem::path & getLocation () const
Retrieves the bundle location.
FWRUNTIME_API const std::string getClass () const
Retrieves the class representing the bundle executable part.
FWRUNTIME_API const Version & getVersion () const
Retrieves the version of the bundle.
FWRUNTIME_API std::shared_ptr< IPlugin > getPlugin () const
Retrieves the plugin instance for the specified bundle identifier.
State Management
FWRUNTIME_API bool isEnable () const
Tells if the bundle is enable.
FWRUNTIME_API void setEnable (const bool state)
Changes the enable state of the bundle.
FWRUNTIME_API void start () throw (RuntimeException)
Starts the bundle.
FWRUNTIME_API void stop () throw (RuntimeException)
Tells if the bundle is enable.
Parameters Management
FWRUNTIME_API void addParameter (const std::string &identifier, const std::string &value)
Adds a parameter to the bundle.
FWRUNTIME_API const std::string getParameterValue (const std::string &identifier) const
Retrieves the value of the given parameter.
FWRUNTIME_API bool hasParameter (const std::string &name) const
Tells if a parameter exists.
Static Public Member Functions
static std::shared_ptr< Bundle > getLoadingBundle ()
Retrieves the pointer to the bundle that is currently loading its dynamic libraries.
Protected Member Functions
Bundle (const boost::filesystem::path &location, const std::string &id, const std::string &version)
Constructor.
Bundle (const boost::filesystem::path &location, const std::string &id, const std::string &version, const std::string &pluginClass)
Constructor.
Friends
struct ::fwRuntime::io::BundleDescriptorReader
Detailed Description
Defines the bundle class.
Date
2004-2009
Definition at line 51 of file Bundle.hpp.
Constructor & Destructor Documentation
fwRuntime::Bundle::Bundle (const boost::filesystem::path & location, const std::string & id, const std::string & version) protected
Constructor.
Parameters
[in] location a path to the directory containing the bundle
[in] id a string containing the bundle identifier
[in] version a string containing the bundle version
Definition at line 44 of file Bundle.cpp.
fwRuntime::Bundle::Bundle (const boost::filesystem::path & location, const std::string & id, const std::string & version, const std::string & pluginClass) protected
Constructor.
Parameters
[in] location a path to the directory containing the bundle
[in] id a string containing the bundle identifier
[in] version a string containing the bundler version
[in] pluginClass a string containing the bundle's pugin class name
Definition at line 61 of file Bundle.cpp.
Member Function Documentation
void fwRuntime::Bundle::addExecutableFactory (std::shared_ptr< ExecutableFactory > factory)
Adds an executable factory instance to the bundle.
Parameters
[in] factory a shared pointer to the executable factory instance to add
Definition at line 81 of file Bundle.cpp.
void fwRuntime::Bundle::addExtension (std::shared_ptr< Extension > extension)
Adds the specified extension to the bundle.
Parameters
[in] extension a shared pointer to the extension to add
Definition at line 118 of file Bundle.cpp.
void fwRuntime::Bundle::addExtensionPoint (std::shared_ptr< ExtensionPoint > extension)
Adds the specified extension point to the bundle.
Parameters
[in] extension a shared pointer to the extension point to add
Definition at line 168 of file Bundle.cpp.
void fwRuntime::Bundle::addLibrary (std::shared_ptr< dl::Library > library)
Adds the specified library to the bundle.
Parameters
[in] library a shared pointer to the library to add
Definition at line 235 of file Bundle.cpp.
References fwRuntime::dl::LibraryBridge< Implementor >::setBundle().
void fwRuntime::Bundle::addParameter (const std::string & identifier, const std::string & value)
Adds a parameter to the bundle.
Parameters
[in] identifier a string containing the parameter identifier
[in] value a string containing the parameter value
Definition at line 546 of file Bundle.cpp.
void fwRuntime::Bundle::addRequirement (const std::string & requirement)
Adds a requirement to the bundle.
Parameters
[in] requirement a string containing a bundle identifier that is required
Definition at line 257 of file Bundle.cpp.
FWRUNTIME_API IExecutable* fwRuntime::Bundle::createExecutableInstance (const std::string & type) throw (RuntimeException)
Create an instance of the given executable object type.
Parameters
type a string containing an executable type
Returns
a pointer to the created executable instance
Bundle::ExecutableFactoryConstIterator fwRuntime::Bundle::executableFactoriesBegin () const
Retrieves the iterator on the first item in the managed executable factory collection.
Returns
an iterator
Definition at line 88 of file Bundle.cpp.
Bundle::ExecutableFactoryConstIterator fwRuntime::Bundle::executableFactoriesEnd () const
Retrieves the iterator on the ending item in the managed executable factory collection.
Returns
an iterator
Definition at line 95 of file Bundle.cpp.
Bundle::ExtensionPointConstIterator fwRuntime::Bundle::extensionPointsBegin () const
Retrieves the iterator on the first item in the managed extension point collection.
Returns
an iterator
Definition at line 221 of file Bundle.cpp.
Bundle::ExtensionPointConstIterator fwRuntime::Bundle::extensionPointsEnd () const
Retrieves the iterator on the ending item in the managed extension point collection.
Returns
an iterator
Definition at line 228 of file Bundle.cpp.
Bundle::ExtensionConstIterator fwRuntime::Bundle::extensionsBegin () const
Retrieves the iterator on the first item in the managed extension collection.
Returns
an iterator
Definition at line 155 of file Bundle.cpp.
Bundle::ExtensionConstIterator fwRuntime::Bundle::extensionsEnd () const
Retrieves the iterator on the ending item in the managed extension collection.
Returns
an iterator
Definition at line 162 of file Bundle.cpp.
std::shared_ptr< ExecutableFactory > fwRuntime::Bundle::findExecutableFactory (const std::string & type) const
Retrieves the executable factory instance for the specified type name.
Parameters
[in] type a string containing a type name
Returns
a shared pointer to the found executable factory instance or null if none
Definition at line 102 of file Bundle.cpp.
std::shared_ptr< ExtensionPoint > fwRuntime::Bundle::findExtensionPoint (const std::string & identifier) const
Retrieves the extension point for the given identifier.
Parameters
[in] identifier a string containing the extension point identifier
Returns
a shared pointer to the found extensoin point, may be empty if none
Definition at line 175 of file Bundle.cpp.
const std::string fwRuntime::Bundle::getClass () const
Retrieves the class representing the bundle executable part.
Returns
a string containing the bundle's plugin class
Definition at line 264 of file Bundle.cpp.
Referenced by start().
const std::string & fwRuntime::Bundle::getIdentifier () const
Retrieves the bundle identifier.
Returns
a string containing the bundle identifier
Definition at line 271 of file Bundle.cpp.
Referenced by getVersion(), initialize(), start(), and stop().
const boost::filesystem::path & fwRuntime::Bundle::getLocation () const
Retrieves the bundle location.
Returns
a path representing the bundle location
Definition at line 278 of file Bundle.cpp.
Referenced by fwRuntime::dl::Native::~Native().
const std::string fwRuntime::Bundle::getParameterValue (const std::string & identifier) const
Retrieves the value of the given parameter.
Remarks
When no such parameter has been found, an empty string is returned.
See also
hasParameter
Parameters
[in] identifier a string containing a parameter identifier
Returns
a string containing the parameter value
Definition at line 553 of file Bundle.cpp.
std::shared_ptr< IPlugin > fwRuntime::Bundle::getPlugin () const
Retrieves the plugin instance for the specified bundle identifier.
Returns
a shared pointer to a plugin instance or null if the bundle has not been started.
Definition at line 285 of file Bundle.cpp.
const Version & fwRuntime::Bundle::getVersion () const
Retrieves the version of the bundle.
Returns
the bundle version
Definition at line 292 of file Bundle.cpp.
References fwRuntime::Runtime::findBundle(), fwRuntime::Runtime::getDefault(), getIdentifier(), SLM_ASSERT, SLM_ERROR, SLM_TRACE, and SPTR.
Referenced by fwRuntime::dl::Native::getNativeName().
bool fwRuntime::Bundle::hasExtension (const std::string & identifier) const
Tells if an specific extension exists.
Parameters
[in] identifier the extension identifier
Returns
true or false
Definition at line 125 of file Bundle.cpp.
bool fwRuntime::Bundle::hasExtensionPoint (const std::string & identifier) const
Tells if a specific extension point exists.
Parameters
[in] identifier the extension point identifier
Returns
true or false
Definition at line 191 of file Bundle.cpp.
bool fwRuntime::Bundle::hasParameter (const std::string & name) const
Tells if a parameter exists.
Returns
true or false
Definition at line 562 of file Bundle.cpp.
void fwRuntime::Bundle::initialize () throw (RuntimeException)
Initialize the bundle.
Remarks
The bundle and it's own dependencies must be started to be able to be initialized.
Definition at line 494 of file Bundle.cpp.
References getIdentifier(), SLM_ASSERT, and SLM_TRACE.
Bundle::LibraryConstIterator fwRuntime::Bundle::librariesBegin () const
Retrieves the iterator on the first item in the managed dynamic library collection.
Returns
an iterator
Definition at line 243 of file Bundle.cpp.
Bundle::LibraryConstIterator fwRuntime::Bundle::librariesEnd () const
Retrieves the iterator on the ending item in the managed dynamic library collection.
Returns
an iterator
Definition at line 250 of file Bundle.cpp.
void fwRuntime::Bundle::setEnable (const bool state)
Changes the enable state of the bundle.
Remarks
It is possible to disable a started bundle but this will have no effect.
Definition at line 539 of file Bundle.cpp.
void fwRuntime::Bundle::setEnableExtension (const std::string & identifier, const bool enable)
Search a specific extension in the bundle to enable or disable it.
Remarks
if the extension is not found, the method do nothing.
Parameters
[in] identifier the extension identifier
[in] enable enable or disable this extension
Definition at line 141 of file Bundle.cpp.
void fwRuntime::Bundle::setEnableExtensionPoint (const std::string & identifier, const bool enable)
Search a specific extension point in the bundle to enable or disable it.
Remarks
if the extension point is not found, the method do nothing.
Parameters
[in] identifier the extension point identifier
[in] enable enable or disable this extension point
Definition at line 207 of file Bundle.cpp.
void fwRuntime::Bundle::start () throw (RuntimeException)
Starts the bundle.
Remarks
The bundle must be enabled to be able to start.
Definition at line 385 of file Bundle.cpp.
References fwRuntime::Runtime::createExecutableInstance(), getClass(), fwRuntime::Runtime::getDefault(), getIdentifier(), OSLM_ASSERT, OSLM_TRACE, SLM_ASSERT, SLM_TRACE, and SPTR.
The documentation for this struct was generated from the following files:
Bundle.hpp
Bundle.cpp